### ISSUE TITLE
add forward/backward buttons in time travel view that snap to where author changed

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1041]
in the timetravel (especially the changes view), besides the forward/backward buttons for moving between single revisions, add buttons that jump to the points where the author has changed. i.e. if there is author X and Y, and you're viewing a change author Y did, pressing this backward button either snaps to the very last change previously done by author X or the very first revision ever.

**Comment by williamstein** [comment]
I think this would complicate the UI too much.  Maybe functionality like this could be provided somehow, but not by adding a bunch more buttons.
