### ISSUE TITLE
scroll position is not restored in preview of .md tab

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1097]
- Open .md file that is longer than one screenful.
- Scroll to bottom in preview panel.
- Switch to another SMC tab.
- Return to .md editor tab. Preview panel is repositioned at top of file.

**Comment by williamstein** [comment]
@johnjeng -- more react fallout -- probably easy-ish.

**Comment by DrXyzzy** [comment]
Re-opening because this bug is back, noticed around Monday 2017-07-24.

**Comment by williamstein** [comment]
I'm annoyed by this all the time.

**Comment by DrXyzzy** [comment]
I have been seeing this all morning today editing a .md file, tabbing away, then coming back.

Now, I can't reproduce it. I'll update this ticket if I find a way to make it repeatable.

**Comment by williamstein** [comment]
> Now, I can't reproduce it. I'll update and reopen this ticket if I find a way to make it repeatable.

Since tabbing away and back does nothing except hide (via css) the codemirror editor, 
 any way to reproduce this would likely have to involve the *other* document that you are tabbing to show somehow "messing up the style/css/flow" of the page.   So think about what else you had opened.

**Comment by haraldschilly** [comment]
Maybe try editing it concurrently in two different tabs? My thought is that maybe updating it causes it to reset to be at the top again.
