### ISSUE TITLE
course style inconsistency issue (not a bug)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1152]
Look at the assignments and handouts tabs side by side, both opened and closed.  There are **numerous** differences and significant style/design changes (e.g., delete button, whether there are buttons in the panel header, spacing, etc.).  They should look very, very similar right?

With them closed:

<img width="1369" alt="screen shot 2016-10-27 at 5 04 32 pm" src="https://cloud.githubusercontent.com/assets/1276278/19789826/c19c4174-9c67-11e6-9cef-4a208b237bba.png">

And with them opened:

<img width="1403" alt="screen shot 2016-10-27 at 5 05 28 pm" src="https://cloud.githubusercontent.com/assets/1276278/19789825/c1959f2c-9c67-11e6-8eaa-521efc2f2fa4.png">

**Comment by williamstein** [comment]
Just to be clear, I'm not saying one or the other is better!  Just that they should be more consistent.

**Comment by novoselt** [comment]
Still applies! It seems that they should reuse the same code and have the same look automatically.
