### ISSUE TITLE
(smc-in-smc dev only) stop all projects also stops the instructor's project

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1153]

**Comment by johnjeng** [comment]
This doesn't seem to happen on the live servers.

**Comment by williamstein** [comment]
priority low since not on the live servers...

**Comment by williamstein** [comment]
There's nothing really having to do with courses here.  It's just some bug in how closing projects work with smc-in-smc.  I've seen that with two projects open, closing one closes both, etc.   I think the code for closing/controlling projects for smc-in-smc is completely different than in live smc, and it's maybe more likely to be buggy.  Maybe there is some funny scoping error or something in some smc-hub code...

**Comment by williamstein** [comment]
This is an issue with the forever command which daemonizes the project local_hub.  It's really a pain to fix without switching to something else entirely (not forever).  I did try to fix this recently for an hour.  Basically any time any project is stopped all of them are killed.

**Comment by williamstein** [comment]
Was an issue with how we were using forever, which I recently finally fixed!
