### ISSUE TITLE
use pdf2htmlEX for rendering the latex/pdf preview

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#117]
Not sure about scalability (there is something about splitting pages for large PDFs [here]/(http://coolwanglu.github.io/pdf2htmlEX/doc/tb108wang.html) in 4.3 … but  still http://coolwanglu.github.io/pdf2htmlEX/ looks nice.

**Comment by williamstein** [comment]
?????

**Comment by williamstein** [comment]
Unclear in 2017 and not clarified, so closing.
