### ISSUE TITLE
figure out how to enable chunks for the static web content of SMC

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1195]
See

  https://github.com/sagemathinc/smc/commit/cfa014e15ddb15a8b46e3ebfaf9d64898c74fb6a

The problem with chunks and the way we deploy SMC's static webapp (via docker containers) is illustrated by this:

- User loads the SMC site
- We upgrade smc-webapp-static
- User displays a 3d plot for the first time, thus loading a new chunk of javascript... which is gone due to the upgrade.  They just silently get a "... js file not found" error in the console.

This really does cause a lot of user confusion (and some bug reports).  To solve this, we need to change our static webserver to somehow serve all chunks ever served... at least since the last forced version update.   That's what this ticket involves figuring out how to do.

IDEAS? 

Modify our docker image build process -- which is [here](https://github.com/sagemathinc/smc/blob/master/src/k8s/smc-webapp-static/image/Dockerfile), to do the normal build, **then** rsync all files it created to some location (??), then rsync everything from that location to the static build in the container.  This seems totally do-able.

**Comment by haraldschilly** [comment]
we could also start using a CDN (likely GCS) instead of those pods. anyways, I've assigned this to me and I'll write up my ideas...

**Comment by williamstein** [comment]
> To solve this, we need to change our static webserver to somehow serve all chunks ever served... 

Another idea, which isn't as good:
  - *always* display a message requesting user to refresh when we upgrade.
  - somehow make doing a refresh keep all open tabs, etc., as is.  One idea -- if you click a specific button on the page to do the refresh, then something is set in localStorage which says "next to you load this page, open exactly these files/tabs" (one time only).  This would be very easy to implement, and would make refreshing for upgrades fairly painless.

**Comment by williamstein** [comment]
@haraldschilly -- I think you solved this problem; if so, please close.

**Comment by haraldschilly** [comment]
oh yes, sure, I'm closing this
