### ISSUE TITLE
Cursor jumps when clicking on a Sage worksheet for the first time

### ISSUE THREAD

**Issue by aarontresham** [sagemathinc/cocalc#1210]
When I open a Sage worksheet with lots of text output, then many of those output cells appear as a single blank line when the worksheet is first opened, and then the actual output will show up as the browser processes things. Since this output is usually longer than one line, rendering the actual output results in later parts of the page being moved down. (Plots may cause similar behavior, since they are often delayed as well, but I didn't check this extensively).

When I click on an early line (above the point where any shifting has occurred), then the cursor appears right where I clicked. However, if I click on a later line, then the cursor will jump several lines below where I click. It appears that the jump size increases as I go further down the page. It may be (but I'm not sure) that the amount of jump depends on the size of the shift resulting from the rendered output.

This only happens on the first such click. After this, everything works as expected.

I also noticed that the original cursor position also shifts. For example, if I have the cursor on line 100 when I close the worksheet, then when I re-open the worksheet the cursor begins at line 100. But then line 100 gets shifted down the page due to output above that showing up. Instead of the cursor staying with line 100 as it moves, the cursor stays in the same spot. So as the lines move down, the cursor may end up in line 90; it may even end up in the middle of an output cell.

Here is an example of the kinds of worksheets I use:

https://cloud.sagemath.com/projects/a8975d68-235e-4f21-8635-2051d699f504/files/13%20-%20Riemann%20Sums%20Assignment/Riemann%20Sums%20Notes.sagews

**Comment by DrXyzzy** [comment]
I am able to duplicate the problem using Chrome with this non-public worksheet: https://cloud.sagemath.com/projects/db982efa-e439-4e2d-933b-7c7011c6b21a/files/QMSE02-2016-01-20/W13-2016-02-07.sagews and vim keybindings.
1. When opening the sheet, hit "I" to get the editor into input mode as soon as the sheet starts to appear.
1. Scroll down into the sheet to input region of some cell, for example around line 82.
1. Wait for sheet to render.
1. Displayed cursor stays in mid screen as sheet renders. In my browser it appears near line 73 after sheet is fully displayed.
1. If you scroll down to line 82 you can see it is highlighted, and if you tap an arrow key you can see that the cursor actually stayed on line 82, it's just that during opening the displayed cursor isn't moved to keep up with the actual cursor.

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks.  That will be #6374
