### ISSUE TITLE
when using two views on the same codemirror editor, and insert lines in one view, don't let viewport change in the other

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1215]
This is the **fault** of codemirror, which does things wrong.  I've fixed this with multiple editors in multiple browsers, but not for a single browser and linked codemirrors.  The fix will probably be to move the viewport back after any change.... NOT sure.

**Comment by williamstein** [comment]
The viewport change is entirely managed by codemirror, so this will be challenging.

**Comment by DrXyzzy** [comment]
Problem is seen with split view in one edit tab, editing a file with more lines than will fit in a screen. Have first view at the top of the file, second view at the bottom of the file. Inserting lines at the top in the first view causes the second view to scroll down.

Is that the correct way to reproduce the problem?

**Comment by williamstein** [comment]
> Is that the correct way to reproduce the problem?

Yep.  Not surprised it is still a problem, since I haven't fixed it yet.

**Comment by williamstein** [comment]
I'm closing this.  It's upstreams behavior.  If anybody is annoyed (nobody but me has ever reported this), open an issue at https://github.com/codemirror/CodeMirror
