### ISSUE TITLE
make the project memory usage update much more frequently (e.g., by having the project write to the database)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1223]
Basically this is the output of `smem -ntk`.   Needs to get written periodically to some table.  Info about processes should also get written, but that can be another ticket.

PLAN:

- add a table to db-schema.coffee with appropriate permissions for project memory info.  Maybe this is just adding a field and modifying the permissions for the existing projects table.

- add module imported by local_hub that periodically write to that table.  The client code in local hub can write to db -- it does so far various other reasons, e.g., for sync file editing stuff. 

Requested by: David Roe, and of course planned forever.

Related: we should obviously also do something similar for running processes.  @haraldschilly wrote something like this over a year ago...

**Comment by haraldschilly** [comment]
closing, since we have that processes tab, which shows memory usage.
