### ISSUE TITLE
In the host down message, don't show payment info for member projects

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1226]
when running a member project, don't show message for paying a member project.

> Host down
> The host for this project is down, [...] please become a paying customer (US $7/month) [...]
> "timeout"

**Comment by williamstein** [comment]
Still true?

**Comment by DrXyzzy** [comment]
Looks as if message still includes text about becoming a paying member: https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/project_files.cjsx#L2102

**Comment by haraldschilly** [comment]
This is somehow similar to https://github.com/sagemathinc/smc/issues/1628 ... not the same issue, but the same spot in the code

**Comment by haraldschilly** [comment]
I pushed to https://github.com/sagemathinc/smc/tree/issue/1226 but that's not done (untested, and I'm not sure what exactly should happen in all the cases). also, this should  ideally  also fix #1628 in one go.
