### ISSUE TITLE
Support drag and drop of images onto chatroom messages

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#1238]
Many programs, including Slack, Google Hangouts, Facebook, and Gitter, support copy and paste of images into messages, issues, etc.   Let's do the same.

For this ticket, in particular, we should implement drag and drop of image files onto chat messages.  When the image is dropped, it should either be uploaded to the blob store or uploaded to a hidden subdirectory (not sure which), and a link `<img src=...>` should be inserted.   (What Github does, which involves changing the markdown for the link as the file uploads is interesting, but probably overkill.)   I think probably sending the file to the blob store would be best, since otherwise moving the .sage-chat file might break all embedded images.

**Comment by johnjeng** [comment]
Done for dedicated chat room files. There's an issue open for side chat.
