### ISSUE TITLE
IRC Chat

### ISSUE THREAD

**Issue by scj643** [sagemathinc/cocalc#1244]
IRC Chat for help with set up would be useful also a bot could be used to notify people of a new push or pull request.

**Comment by williamstein** [comment]
Are you requesting to add a link to our chatroom to some documentation? https://gitter.im/sagemath/cloud

**Comment by scj643** [comment]
Gitter seems dead

**Comment by haraldschilly** [comment]
I'm using riot.io via matrix.io to follow freenode/#sagemath a bit. maybe we should have a #sagemathcloud on freenode? is that what you mean?

**Comment by williamstein** [comment]
Gitter is not dead.

**Comment by haraldschilly** [comment]
Hello @scj643 this ticket is sitting here and at least I have no clue what this is about. Can you please explain the problem and then how you envision how to solve it? In particular, I don't get what you mean by

> for help with set up 

what set up?

**Comment by haraldschilly** [comment]
cocalc is on discord, the newest iteration of IRC. https://discord.gg/nEHs2GK
