### ISSUE TITLE
add haskell jupyter kernel

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#125]
See https://github.com/gibiansky/IHaskell

**Comment by williamstein** [comment]
Marked insanely hard since I tried many times and failed...  Shouldn't it be trivial to install all the Jupyter kernels into the most recent Ubuntu?  Nope.

**Comment by williamstein** [comment]
https://github.com/gibiansky/IHaskell/issues/694

**Comment by vaibhavsagar** [comment]
I wouldn't say insanely hard, just very fiddly :smile:

**Comment by williamstein** [comment]
Internal link -- https://cloud.sagemath.com/projects/83f61217-0b89-4ad4-88bf-15fa303a2c96/files/haskell.sage-chat -- some guy seems to have got it to work!

**Comment by vaibhavsagar** [comment]
I should have added a disclaimer: I've only built the executable statically, but not confirmed that this fixes the issues we were having previously.

**Comment by vaibhavsagar** [comment]
Can we close this :smile:?

**Comment by williamstein** [comment]
Success!
