### ISSUE TITLE
add error msg when directly opening a private ipynb file and not being signed in

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1265]
when opening a *private* ipynb file directly via an url, there is just an empty iframe. add an error message like there is for sagews.

possible follow up: which other filetypes lack such an error message?

**Comment by williamstein** [comment]
To clarify, do you mean "when opening a private ipynb file directly via an url when you do not have permissions to do so but are logged in"?

**Comment by haraldschilly** [comment]
no, that's for the case when someone's not signed in.

**Comment by DrXyzzy** [comment]
To reproduce
1. Locate a non-shared .ipynb file in some project.
1. Use the Share checkbox to find a public link, but do not share the file.
1. Use the link in an incognito browser session. You get an empty files list and no warning message.

Compare the images below from trying to view private .ipynb vs. private .sagews:

![screenshot 2017-02-23 11 03 38](https://cloud.githubusercontent.com/assets/528072/23270025/0b19d638-f9b8-11e6-9289-be54210ec93c.png)

![screenshot 2017-02-23 11 04 45](https://cloud.githubusercontent.com/assets/528072/23270041/1e4d80e2-f9b8-11e6-936d-e580fcdbf2ee.png)

**Comment by williamstein** [comment]
Is this still a problem?  I bet the jupyter rewrite fixed it...

**Comment by williamstein** [comment]
Yes, this is now fixed -- you get a proper error.  We no longer use an iframe for jupyter.
