### ISSUE TITLE
sagews export button

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1272]
Next to "save", a new "export" dropdown button should make it easy for everyone to get the file out of SMC. For the start, the two initial entries are a "normal" download of the underlying sagews file, and a "PDF" download, which is exactly the same as printing except that it initiates a file download.

Jupyter also has a couple of export options, which are based on pandoc. Once we have a good html export of sagews, I bet we can leverage it to also offer epub, etc.

**Comment by williamstein** [comment]
done via pr jus now.
