### ISSUE TITLE
sagews: evaluating empty "cell" shouldn't insert a new cell

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1274]
when evaluating all cells in a sagews, it adds a delimiter at the bottom. e.g. do this repeatedly in an empty sagews:

1. ctrl-a
1. shift-return

you'll end up with more and more pointless cells

**Comment by williamstein** [comment]
I'm closing this ticket, because our current behavior (to create a new cell if you select all cells and hit shifter enter) is exactly the same as the behavior right now of all three of Jupyter classic, cocalc-jupyter, and JupyterLab.
