### ISSUE TITLE
Add new special characters to big omega button

### ISSUE THREAD

**Issue by AndreWin** [sagemathinc/cocalc#129]
There are many useful special characters at [this page](http://www.dionysia.org/html/entities/symbols.html). 

It would be nice to add them in big omega button that on button panels for html.

[source for this suggestion](https://groups.google.com/forum/#!topic/sage-cloud/T30E_l5doSw).

**Comment by williamstein** [comment]
1. I added many emojis to the big omega button recently, so that's a ton more.
2. Otherwise it's not at all clear what is missing, etc., so I'm closing this.
