### ISSUE TITLE
TimeTravel history changes -- cursor offset?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1292]
I just noticed, that my cursor in a timetravel changes view has a vertical offset. In the screenshot, notice that it is actually the faint blue line (`right = 2cm ...`) where the cursor should be...

Examples:
![smc-timetravel-cursor-offset](https://cloud.githubusercontent.com/assets/207405/20564619/5c04241c-b18e-11e6-9bd7-bbbd9e329a4c.png)

![mismatch](https://cloud.githubusercontent.com/assets/618575/20945273/76e4131e-bbbb-11e6-907a-4dc267889f8f.png)

**Comment by haraldschilly** [comment]
problem is, it's not consistently happening. sometimes it can be triggered after changing the sliders, changing window width, toggling changes off and on again, etc.

**Comment by williamstein** [comment]
Maybe there is a missing call to codemirror's refresh function?

**Comment by johnjeng** [comment]
To reproduce:
1. Open a file, go to time travel
2. Go to changes mode.
3. Change the slider
4. Based on some timing, clicking on the changing editor will result in a mismatch

**Comment by williamstein** [comment]
One fix would be to not show a cursor.

**Comment by williamstein** [comment]
I fixed this when I rewrote TimeTravel in react with the frame editor...
