### ISSUE TITLE
support R and Octave (and other) Jupyter kernels in the SMC docker image

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1304]
This is especially important since %r and %octave (etc.) modes in Sage worksheets now rely on Jupyter kernels, rather than pexpect.

**Comment by williamstein** [comment]
@haraldschilly:
>  That means, that the "ir" kernel for R (and many others) aren't available in that image. I mean, you're running a local version of smc with some minimal subset of the necessary stuff on the back-end -- that's it. In total there is much much more, but that's outside the scope of smc. ​ Here is a most likely working copy of that kernel: https://github.com/sagemathinc/smc/tree/master/src/smc-build/jupyter-kernels/ir

**Comment by jackdyson31** [comment]
Ok,
I have managed to completely update the docker image with a pull from the repo. I suppose to get those kernels I'd have to install the Jupyter system into the docker right ?

PS Once I understand the configuration of the node based setup you guys use (think I made some progress on that but can't get the backend to connect to the smc local site - errors in configuration on my part I'm sure) for "singleuser" machines - I can start specializing a setup just for distribution as a single machine smc as a test without docker.

**Comment by williamstein** [comment]
>  I suppose to get those kernels I'd have to install the Jupyter system into the docker right ?

Jupyter is installed already in our docker image.  That said, I strongly encourage you to experiment -- which is extremely safe to do in Docker.

**Comment by jackdyson31** [comment]
Cheers W,

I am experimenting, I think I have a few ideas.

Info: Found a small "error" in the local install  so I hacked it for now:

1. bug in : sagews2pdf.py, fixed
changed "site" variable to point to localhost for printing locally - will
change to more stable source later

J

**Comment by williamstein** [comment]
I've made a ticket for proper sagews2pdf printing.   https://github.com/sagemathinc/smc/issues/1319

**Comment by EWouters** [comment]
I'm trying to install additional kernels in the docker image, I have been looking through the [code](https://github.com/sagemathinc/smc/blob/master/src/smc-build/build.py) and [documentation](https://github.com/sagemathinc/smc/blob/master/src/smc-build/anaconda.md) here, but haven't found a way to install anaconda or the ir kernels for instance.

Could you point me in the right direction, maybe make documentation about installing other kernels?

I really like the project and want to include it in my personal server, replacing the jupyter installation.

**Comment by haraldschilly** [comment]
@EWouters 

there are a couple of slightly outdated copies of kernels here: https://github.com/sagemathinc/smc/blob/master/src/smc-build/jupyter-kernels/ ... there are no install instructions, because it depends on what is installed where exactly in the docker image. one would have to create templates for the kernel.json files and fill in the paths where the executables are.

another important point is, where to install those kernels. the default system-wide location is `/usr/local/share/jupyter/kernels` but I don't know if the docker image is configured differently.

**Comment by EWouters** [comment]
@haraldschilly 
Thanks for the answer. I managed to install a current anaconda kernel in the docker image with most of the packages you include in smc.
Steps:

I ran the docker image:
`docker run --name=smc -d -p 80:80 -p 443:443 sagemathinc/sagemathcloud`
I created an account with sudo rights:
```
docker exec -it smc bash
useradd -M -G sudo erik
passwd erik
```
Then I opened a root shell:
```
su erik
sudo su
```

I ran the following commands:
```
cd /tmp

wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh && \
    echo "73b51715a12b6382dd4df3dd1905b531bd6792d4aa7273b2377a0436d45f0e78 *Anaconda3-4.2.0-Linux-x86_64.sh" | sha256sum -c -
	
umask 002

export CONDA_DIR=/projects/anaconda3

bash Anaconda3-4.2.0-Linux-x86_64.sh -f -b -p $CONDA_DIR

# install directory must not exist beforehand, I'll put it into `/projects/anaconda3` ... IT'S NOT POSSIBLE TO MOVE THE DIR LATER ON (rpath FTW?)

# cd /projects

# chown -R salvus:salvus anaconda3
    # exit # ... such that you are salvus again
# cd anaconda3

# OK, that looks good, numba, ipython, jupyter, etc. are installed.

#activate the environment

cd $CONDA_DIR

. bin/activate root

umask 002
conda update conda -y
conda update --all -y

echo "channels:
  - amueller
  - vpython
  - ioos
  - omnia
  - Unidata
  - jjhelmus
  - juanlu001
  - obspy
  - bokeh
  - r
  - astropy
  - pypi
  - plotly
  - conda-forge
  - mutirri
  - activisiongamescience
  - defaults
show_channel_urls: True
#  - bioconda
#  - mro" > /projects/anaconda3/.condarc

umask 002

conda install -y basemap bcolz blist boost bsdiff4 btrees bz2file cherrypy chest cloudpickle coverage cssselect csvkit cubes cvxopt cymem dask distributed xarray datrie db dill django docopt toolz cytoolz datashader pymc gdal
conda install -y python-symengine

conda install -y ecdsa ephem execnet feedparser flake8 flask-wtf flask-login future gensim geos gunicorn heapdict html5lib lancet libnetcdf line_profiler llvm locket lockfile logilab-common mako markdown2 mdp mock markdown pysal
conda install -y descartes wordcloud vpython

conda install -y mpi4py mpich2 mpmath msgpack-python natsort ncurses netcdf4 numpydoc paramiko partd pylint pymc pyramid_jinja2 pyramid_mako pystan queuelib runipy scikit-bio seaborn sh stripe mpmath plotly
conda install -y geopandas ccdproc
# conda install -y python-libsbml cobra

conda install -y thinc translationstring twisted unidecode venusian virtualenv webtest whoosh yt pandas-datareader pandas pandasql blaze cvxopt tabulate pycrypto biopython gensim keras
conda install -y geopandas mahotas bqplot rpy2 r-recommended r-essentials simpy altair tweepy
# conda install -y r-plotly cufflinks

conda install -y xarray dask netcdf4 rasterio cython shapely lxml psycopg2 datashader quandl
conda install -y geopandas geojson folium mplleaflet cartopy rasterstats ipyleaflet pykml jsanimation qutip emcee astroquery asciitree corner
conda install -y rasterio
# conda install -y pyamg opencv mercurial

# Personal:
#conda install -y ipyparallel
#conda install -y -c conda-forge ipywidgets
#conda install -y -c conda-forge jupyter_contrib_nbextensions

#conda clean --all --yes

pip install --no-deps git+https://github.com/timothydmorton/isochrones.git

#getting the data-files is weird. some hard-coded paths are wrong (in the code, as of dec 2016) and running it from the ipython shell causes it to crash because there is no X server. however:

#python -c 'from isochrones import get_ichrone; print(get_ichrone("mist"))' python -c 'from isochrones import get_ichrone; print(get_ichrone("dartmouth"))' python -c 'from isochrones import get_ichrone; print(get_ichrone("dartmouthfast"))' python -c 'from isochrones.mist import MIST_Isochrone; print(MIST_Isochrone().radius(1.0, 9.7, 0.0))' python -c "from isochrones.dartmouth import Dartmouth_Isochrone; print(Dartmouth_Isochrone(['z', 'B', 'W3', 'LSST_r', 'J', 'UK_J']))"

###source .$CONDA_DIR/bin/activate root

#inside /projects/anaconda3: . bin/activate root where root just stands for the base environment of anaconda (not the root user)

#to exit the environment: . deactivate

cd /usr/local/share/jupyter

mkdir kernels
cd kernels
mkdir anaconda3

echo "{
 \"display_name\": \"Anaconda (Python 3)\",
 \"argv\": [
  \"/projects/anaconda3/bin/python3\",
  \"-E\",
  \"-m\",
  \"ipykernel\",
  \"--matplotlib=inline\",
  \"-f\",
  \"{connection_file}\"
 ],
 \"language\": \"python\",
 \"env\":{
    \"LD_LIBRARY_PATH\" : \"/projects/anaconda3/lib\",
    \"PYTHONPATH\" : \"/projects/anaconda3/lib/python3.5:/projects/anaconda3/lib/python3.5/site-packages\",
    \"PYTHONHOME\" : \"/projects/anaconda3/lib/python3.5\"
 }
}" > /usr/local/share/jupyter/kernels/anaconda3/kernel.json

```

After that finished I was able to use the anaconda kernel in Jupyter notebooks or Sage worksheets.

I hope this may be useful to other people. If you like I can create a Dockerfile with the anaconda kernel installed, based on the official docker image. However, I am a very novice user of docker so I don't know anything about security.

**Comment by haraldschilly** [comment]
yes, looks in general pretty good.

What I don't know is the state of some channels. E.g. I think you might
want to get rid of "jjhelmus", since it ships a broken (at least, two weeks
ago) tensorflow 0.12 release candidate. In conda-forge is a working non-rc
0.11. The conda tool automatically picks the newer one, regardless of being
stable or not. (maybe there is a way to teach it not to do it, but I don't
know. ... long term, I hope only the main channels like default,
conda-forge, omnia and some like astropy should be sufficient)

Besides that, sometimes the permissions aren't set right. To make the
anaconda dir readable by all other users, you can always run:

src/scripts/smc-fix-permissions.sh /projects/anaconda3

-- harald

**Comment by williamstein** [comment]
> If you like I can create a Dockerfile with the anaconda kernel installed, based on the official docker image. However, I am a very novice user of docker 

What you should do is send us a pull request to modify our own dockerfile.   That said, all you should do is:

(1) create a shell script with all of your code above.  (Do **not** try to do all those things with dozens of commands in a Dockerfile!)

(2) Add one single line to the Dockerfile that copies the shell script into the image and another line that runs it -- if you look at the current dockerfile, you'll see this sort of thing is already done. 

(3) Build and test (will take an hour).

**Comment by EWouters** [comment]
I'm working on this and a few things have come up:

- The image size will more than double, so that might be undesirable for some people.
- I had to increase the default disk size of my docker machine to more than 20G in order for it to build.

I think it would be better to make this a layer on top of the base smc image. That way the dockerfile would look something like:

```
FROM sagemathinc/sagemathcloud

MAINTAINER William Stein <wstein@sagemath.com>

# Configure environment
ENV CONDA_DIR /projects/anaconda3
ENV PATH $CONDA_DIR/bin:$PATH
ENV KERNELS_DIR /usr/local/share/jupyter

# Install conda as root
RUN cd /tmp && \
    mkdir -p $CONDA_DIR && \
    wget --quiet https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh && \
    echo "73b51715a12b6382dd4df3dd1905b531bd6792d4aa7273b2377a0436d45f0e78 *Anaconda3-4.2.0-Linux-x86_64.sh" | sha256sum -c - && \
	umask 002 && \
	/bin/bash Anaconda3-4.2.0-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Anaconda3-4.2.0-Linux-x86_64.sh && \
    $CONDA_DIR/bin/conda install --yes conda

# Update conda
RUN cd $CONDA_DIR && \
	. bin/activate root && \
	umask 002 && \
	conda update conda -y && \
	conda update --all -y && \
	. deactivate

# Configure conda channels
COPY conda_channels $CONDA_DIR/.condarc

# Install conda packages
COPY install_conda_packages.sh /tmp/install_conda_packages.sh
RUN ./tmp/install_conda_packages.sh && \
	rm /tmp/install_conda_packages.sh

# Install conda kernel file to jupyter
RUN mkdir -p $KERNELS_DIR/kernels/anaconda3
ADD https://raw.githubusercontent.com/sagemathinc/smc/master/src/smc-build/jupyter-kernels/anaconda3/kernel.json $KERNELS_DIR/kernels/anaconda3

# run permission script on $CONDA_DIR
#TODO
```

**Comment by EWouters** [comment]
Would it be possible to use the ansible files to install the other kernels into the docker image? It seems this would simplify the maintenance a lot.

**Comment by williamstein** [comment]
R is now supported.  For other kernels open new issues, one for each kernel.

**Comment by jackdyson31** [comment]
Thanks William! Appreciated.
