### ISSUE TITLE
docker image: support sagews2pdf.py "convert to PDF" button by pointing download source to localhost rather the cloud.sagemath.com

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1319]
We need some sensible way of doing this, e.g., an environment variable or something. It can't just be hard coded.

**Comment by haraldschilly** [comment]
sorry, I don't understand the headline :-(

anyways, I'm working on a html exporter, maybe that one solve this issue because this doesn't come up any more in the first place.

**Comment by williamstein** [comment]
> sorry, I don't understand the headline :-(

When printing, graphics are downloaded from the blob store, which is made available via a URL at cloud.sagemath.com.  If you run SMC yourself via docker, you have to point sagews2pdf at a different blob store.  That's all.

> anyways, I'm working on a html exporter

It absolutely would solve this issue, and do so in a very eloquent way!   Is there a link to a branch or something?

**Comment by williamstein** [comment]
Oops

**Comment by haraldschilly** [comment]
ahh, now I get it, thank's!

> When printing, graphics are downloaded from the blob store ...

That's exactly the same when running sagews2pdf inside the smc-in-smc dev projects. They also download from the wrong place and end up with empty files. Ok. The solution is to pass the correct url down to the python utility.

**Comment by williamstein** [comment]
This might be fixed by Harald's rewrite -- I'll test soon.

**Comment by williamstein** [comment]
I've checked:

(1) the new print button works fine in docker.

(2) the "convert to PDF" button (next to print) just times out and silently **fails**. 

So to close this issue we need to either remove the "convert to PDF" button, or fix the functionality as discussed above.

 -- William

**Comment by haraldschilly** [comment]
This just got a tick more complex: be3455d1ee811b7c21ce38bbfe66bbb80ed44436

The solution is to add this to the "theme" configuration file as a setting, fallback is the base url there, and then siphon this base_url into sagews2pdf.py as the base url there.

**Comment by williamstein** [comment]
Heh, I don’t think I made it that much more complicated...

**Comment by eMPee584** [comment]
Uhm, PDF generation from the docker image is still broken. It does give a lengthy error message about 404 failage on cocalc.com :trollface:

**Comment by williamstein** [comment]
no longer relevant because cocalc-docker is deprecated
