### ISSUE TITLE
vim mode, orphan cells

### ISSUE THREAD

**Issue by edgarcosta** [sagemathinc/cocalc#1325]
Perhaps these are two bugs, but I think the source of them is all the same

1. In vim mode I can modify the "insert a new cell line", for example, I can delete it with dd, or delete the delimiter char.
2. If I delete the first "insert a new cell line" and first input cell, then the first output cell becomes an orphan, and I cannot delete it...

Cheers,
Edgar

**Comment by DrXyzzy** [comment]
It's also possible to make a .sagews that does not save.
1. In new sage worksheet, execute two simple cells, for example
    ```
    42
    --
         42
    -- new cell
    43
    --
         43
    ```
1. In vim edit mode, delete lines 1 and 2 of the worksheet, leaving orphan output cell `42` on line 1.
1. Wait for autosave. When autosave starts, it spins forever.

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks.  That will be #6374.
