### ISSUE TITLE
add html5 vnc support for SMC projects so that we can use X11, X windows applications -- noVNC looks good

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#135]
Motivation: this would at least make it possible for people to use various native apps (like GIMP? Octave?) if _necessary_.  Better than nothing.  It's something people expect.   Also, this could be an easy feature to add that wouldn't have any negative effect on our UI -- it would just increase usage.  One way to do it would be via simply a document type, e.g., ".vnc", which when opened provides a full vnc session/desktop/etc using the account of that project.   Easy, simple, no added ui weight.    I've been planning to do this for a long, long time. 

Technology to use: https://kanaka.github.io/noVNC/

A discussion of a similar product: https://news.ycombinator.com/item?id=10289673

Sync -- like in terminals in SMC -- does work, e.g., I tried opening the same vnc session in two browsers and either one can fully interact with the session.

**Comment by williamstein** [comment]
<img width="1190" alt="screen shot 2015-09-28 at 9 54 40 am" src="https://cloud.githubusercontent.com/assets/1276278/10142334/fc322c3c-65c6-11e5-98c7-2f3a36a61094.png">

**Comment by rbeezer** [comment]
R Commander would be a (graphical) application many introductory statistics courses would find appealing on SMC.

http://www.rcommander.com/

**Comment by timothyclemansinsea** [comment]
I need this ASAP because of an OpenCV script I'm trying to use requiring X server. I tried building on Icebergs.io but it failed.

**Comment by williamstein** [comment]
Another possibility: https://news.ycombinator.com/item?id=11744430

**Comment by williamstein** [comment]
This goes against the whole point/philosophy/dream/argument of SMC.  So let's not do this.

**Comment by williamstein** [comment]
Discussion of some approaches to this problem here: https://news.ycombinator.com/item?id=16358774

And reopening, since I disagree with my previous comment - this can be viewed similarly to term.js

**Comment by slel** [comment]
Would this allow to run TeXmacs on CoCalc?

**Comment by williamstein** [comment]
Instead supporting Wayland might be a reasonable alternative/tradeoff.  See https://github.com/udevbe/greenfield

**Comment by williamstein** [comment]
This will be available soon :-)

**Comment by williamstein** [comment]
Teaser screenshot showing VSCode, Octave, TexMacs, and RStudio all running in a cocalc-docker instance remotely...

![screenshot 2018-10-12 at 1 17 59 pm](https://user-images.githubusercontent.com/1276278/46892177-5760bb80-ce21-11e8-8eeb-88928c7a9dd7.png)

**Comment by rbeezer** [comment]
Killer!

**Comment by slel** [comment]
Note that many plugins for [GNU TeXmacs](http://texmacs.org) just [got updated and given a new home](https://lists.gnu.org/archive/html/texmacs-dev/2018-10/msg00002.html),
including

- [Haskell](https://github.com/texmacs/Haskell.tm),
- [Macaulay2](https://github.com/texmacs/Macaulay2.tm),
- [Maxima](https://github.com/texmacs/Maxima.tm),
- [Python3](https://github.com/texmacs/Python3.tm),
- [Rust](https://github.com/texmacs/Rust.tm),
- [SageMath](https://github.com/texmacs/SageMath.tm),
- [Scala](https://github.com/texmacs/TeXmacs.scala).

**Comment by williamstein** [comment]
Another teaser...

![image](https://user-images.githubusercontent.com/1276278/47099866-0bc85c00-d1eb-11e8-8a73-5c05b49424d5.png)

**Comment by williamstein** [comment]
It's now possible to try this out.  **CAVEAT: It's still far from done and focus is pretty broken, etc., etc.,**

But if anybody wants to just try this out, refresh your browser after I write this, then make a file that ends in .x11.  Just do this in any project.  You'll get a terminal.  As a test, try running gvim or emacs or starting R and drawing a plot.

You do NOT have to do anything to explicitly start or stop any servers, and this *is* collaborative -- multiple people can open the same .x11 file.  However, it's no more collaborative than terminals.

Once you have a new .x11 open, you can use the terminal to open app *or* do this in any non-X11 terminal:
```
~$ export DISPLAY=:0
~$ gvim
etc.
```

and tabs will pop up in the .x11 thing for now.

![image](https://user-images.githubusercontent.com/1276278/47183592-51fde800-d2dd-11e8-9901-a4fd23872683.png)


William

**Comment by williamstein** [comment]
We now have this.   It lets you run any graphical Linux X11 applications in your browser.   If you want to try it, click 

+New --> X11 Desktop

You'll get a terminal on the left and a blank desktop on the right.  Type

`~$ xclock&` 

in the terminal, and you'll a tab appear on the right. Click it and see a clock.  Similar for lots of other things
like inkscape, libreoffice, octave, gvim, emacs, gnome-shell, rstudio, VS code, nteract, etc.

**Comment by rbeezer** [comment]
Very nice.  I guess all I need now is a ChromeBook and a CoCalc subscription.  ;-)

I spent some time messing around with RStudio and LibreOffice and it all seemed 
to work quite well.  I think folks are going to like this.
