### ISSUE TITLE
cobrapy fails due to broken libSbML

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1381]
the goal is to install cobrapy, but it fails in python 2 or 3.

new info from a support request:

> I notified the libsbml developers about this bug and they came back with the following explanation:
> http://sbml.org/Software/libSBML/docs/python-api/libsbml-issues.html#gcc5-python
> This is most likely due to the GCC version used, which would also explain why the bug no longer occurs in newer Ubuntu versions.

the deadline to fix this situation is summer 2016. either update ubuntu or build it with one of those workarounds.

**Comment by haraldschilly** [comment]
link no longer works. looks like the only way to solve this is to update the compute environment.

**Comment by haraldschilly** [comment]
cobrapy works (well, I don't know anything about their xml modeling language, but the lib does load up in python3 and solves an empty model. good enough!)

**Comment by schwartzjmc** [comment]
Hi Harald,

I tested it today and confirm that it works, thanks for enabling this.

Best,
Jean-Marc
