### ISSUE TITLE
distorted list_plot3d 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1405]
when plotting `pts` defined via

```
%var x, y
f(x,y) = 5 - x^2/2 - y^2/4
pts = []
for i in range(1000):
    pt = [uniform(-10,10), uniform(-10,10)]
    pt.append(f(pt[0], pt[1]))
    pts.append(pt)
```

it works this way

```
sum(point3d(pt) for pt in pts)
```

but gives a distorted output for

```
list_plot3d(pts)
```

![distorted-list-plot3d](https://cloud.githubusercontent.com/assets/207405/21345192/6cae274c-c69f-11e6-8d31-16759fd19576.png)

**Comment by williamstein** [comment]
Closing this, since it's a question about sage and has nothing to do with cocalc.
