### ISSUE TITLE
chat's scroll position distorted when images load

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1429]
when there are images in the chat and one switches back and forth, those images might reload and hence change the height of the chat. this causes the bottom to be no longer at the bottom. 

this ticket's aim is to deal with loading images. one idea is to listen to `load` events, and if they happen ,the scroll position is corrected by the height of the image. maybe there are better ideas...

**Comment by williamstein** [comment]
Right now the code to restore the scroll position is called before the images are loaded, hence it's impossible for it to work properly.    This is a difficult problem since images can take arbitrarily long to load.... 

I just explicitly changed my img tags in our chat today to have height= explicitly given, and the problem (mostly) goes away... hmmm.

**Comment by hhaidar** [comment]
Hey!

I'm working on a chat app myself and I've managed to solve this issue quite nicely using `MutationObserver` and the `img load` event. If you need to support older browsers (ie10 and under), it's still possible to drop `MutationObserver` with something else.

Here's a code snippet of what I have (please let me know if you have any questions!):

```javascript
const observer = new MutationObserver(mutations => {

  const onLoadImage = e => {

    this.scroll();

    e.target.removeEventListener('load', onLoadImage);

  };

  const processMutation = mutation => {

    if (mutation.type !== 'childList') {
      return;
    }

    mutation.addedNodes.forEach(processNode);

  }

  const processNode = node => {

    const imgs = node.querySelectorAll('.lcb-message-text img');

    imgs.forEach(img => {

      if (img.complete) {
        return;
      }

      img.addEventListener('load', onLoadImage);

    });

  };

  mutations.forEach(processMutation);

});

observer.observe(listNode, {
  childList: true
});
```

**Comment by williamstein** [comment]
Thanks for the advise but I'm using a potentially more hackish approach, partly because imageload is not the only thing that could result in resizing the rendered chat list (e.g., mathjax rendering, etc.); instead I'm just using a dumb heuristing involving setTimeout...
