### ISSUE TITLE
chat: add "face"-buttons to filter messages by participant

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1436]
this feature enhancement works like this: all participants of a chat are listed somewhere with their icons as toggle buttons (like tags).  
* when none of them are clicked, all messages are shown.
* when one or more of them are enabled, only their messages are rendered
   * in that case, also show a "clear X" button

**Comment by williamstein** [comment]
More modern: should filter by threads where the person participated somewhere in the thread.

**Comment by williamstein** [comment]
I just made a commit so you can type the name of a person in the search filter  and it works to only show threads that they wrote a message in (or were mentioned).  Seems easy enough.  No need for a full dropdown.
