### ISSUE TITLE
output cells getting created in one worksheet in some cases when two clients have the worksheet open

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1458]
At the JMM booth there has been something weird involving output cells getting inserted in worksheets when multiple browser are left open pointing at the same worksheet -- you can see this in the timetravel for [demo1.sagews](https://cloud.sagemath.com/projects/632efe98-a2ab-45ef-bb7e-0ab6799c6fd9/files/demo1.sagews) there.  Checking TimeTravel, I saw the additions going partly back and forth between two clients.

This is definitely something I should fix -- probably by adding a *rule*, which is that a worksheet will never in any way be modified by a client -- even during rendering, unless the client has recently actively made an edit themselves.  Enforcing that would ensure that such a feedback loop is impossible.

Regarding dogfood, it would be good practice as devs to keep an extra laptop (or browser tab) open on the same document you're actively using, as a test...

**Comment by DrXyzzy** [comment]
To replicate:
1. Open .sagews file in Chrome and position cursor at top.
1. Open same file in Firefox and position cursor at top.
1. Start a new cell at the top in Chrome and type a line, but do not hit return.
1. Wait about 15 seconds and an empty output cell will appear in the Firefox window under the new top input cell.
1. Execute the top cell in the Chrome window and you will get a second output cell.

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.
