### ISSUE TITLE
Make the button bars like in %latex mode on Sage worksheets also work in latex docs

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1467]

**Comment by haraldschilly** [comment]
my idea about this is, to add a narrow (maybe 50px) button bar on the left. e.g. "H" for headers, "F" for various formatting options, etc. Reason is, that whatever is added at the top does clutter the UI even more and there is plenty of space on the left hand side of the input area.

**Comment by williamstein** [comment]
we have all the formatting buttons now.
