### ISSUE TITLE
Implement bottom terminal similar to side chat

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#1474]
For running files I think it makes much more sense to run them in a true terminal,. This would be  especially true if there's raw input involved or a lot of output.

**Comment by williamstein** [comment]
Can you change this to bottom terminal.  Side terminal would be too thin.  

Terminals are also useful because they work **interactively**.

**Comment by williamstein** [comment]
Now done.   Just make another frame and set to Terminal type.

![screenshot 2018-09-29 at 8 02 02 pm](https://user-images.githubusercontent.com/1276278/46253033-00bdaf80-c427-11e8-8a8e-25c171accb82.png)
