### ISSUE TITLE
design and implement a solution to the anonymity problem for courses

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1484]
Example question: "We hire (advanced) undergrads to grade problem sets but this requires anonymity.   Making them collaborators on a project is therefore undesirable (for many other reasons as well)."

**Comment by williamstein** [comment]
My current ideas, which I shared with the question asker:

Oxford used SMC and required such anonymity.  They had the students create an SMC account for the class with email address

   something+assigned_number@foo.edu

and have their official name in SMC for that account by "assigned_number".
Then only those who knew the mapping "name <--> assigned_number" knew who any student is.   Graders could then be collaborators on the project containing the .course, and everything ended up working well.

The drawback of the above is that password reset emails all go to

   something@foo.edu

so you'll have to have the instructor do something manually if a student forgets or looses their password.

A second workaround, which I've not heard about anybody using yet, is that you could copy all the collected homework to another project, which you setup specifically for the purposes of graders, and you only add them as collaborators. It's very easy to copy an entire directory tree of files to any other project in SMC (click the checkbox next to a folder, then click copy, then click "to another project").    The students would then grade those files; you would copy them back when they are done.    The collected homework I think does contain an informational file identifying each student, so if not anonymized as above, you would have to run a single command first to remove those files, e.g.,
 
    rm */STUDENT*.txt

in a terminal.  Otherwise, the directories with the collected homework are all just random 36-character strings.   

This second approach, with a *grader project*, is probably exactly how we will implement a solution to your problem in SMC.   It's best to think of an SMC project as "the way to define a group of people with common access to some files", so it's natural to introduce another project for the purposes of grading.

**Comment by johnjeng** [comment]
>This second approach, with a grader project, is probably exactly how we will implement a solution to your problem in SMC. It's best to think of an SMC project as "the way to define a group of people with common access to some files", so it's natural to introduce another project for the purposes of grading.

This sounds like the solution to me. Extends naturally to any other group that would want to interact with a course too. Auditors come to mind.

Some auxiliary thoughts:
 - We could let people set a name for themselves on a per project basis if they want. 
 - We could create a system that allows a user to make a temporary identifier to allow themselves to be added to any project and when they remove the identifier, we remove them from all projects that they had for this identifier. Of course this is just like having multiple accounts but in this case it's integrated seamlessly.

**Comment by novoselt** [comment]
Using fake emails seems to be sufficient in practice.
