### ISSUE TITLE
Install the QuantLib Python bindings into Sage, etc.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1488]
It should be just:
```
apt-get install libquantlib0 libquantlib0-dev quantlib-examples quantlib-python r-cran-rquantlib
```

I already did this on compute4, and it simply doesn't work:
```
root@compute4-us:/home/salvus# python
Python 2.7.10 (default, Oct 14 2015, 16:09:02)
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import QuantLib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/QuantLib/__init__.py", line 24, in <module>
    from QuantLib import *
  File "/usr/lib/python2.7/dist-packages/QuantLib/QuantLib.py", line 28, in <module>
    _QuantLib = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/QuantLib/QuantLib.py", line 24, in swig_import_helper
    _mod = imp.load_module('_QuantLib', fp, pathname, description)
ImportError: /usr/lib/python2.7/dist-packages/QuantLib/_QuantLib.so: undefined symbol: _ZThn120_N8QuantLib19CappedFlooredCoupon6updateEv
>>>
```

I didn't know that Debian/Ubuntu doesn't have a basic test suite that involves "running a command" to verify a package they setup to install actually works at all.   I guess they don't.

---

**So -- another approach:** download the tarball from here https://sourceforge.net/projects/quantlib/files/QuantLib/1.9/other%20languages/, then going to the Python subdirectory and doing `python setup.py install`.    The 1.9.1 version just says "use 1.9".

The direct link, which is a pain to get from sourceforge, is 

    http://downloads.sourceforge.net/project/quantlib/QuantLib/1.9/other%20languages/QuantLib-SWIG-1.9.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fquantlib%2Ffiles%2FQuantLib%2F1.9%2Fother%2520languages%2F&ts=1484184072&use_mirror=cytranet

**Comment by williamstein** [comment]
Further remarks.  I built the 1.8 bindings for a user, and it works fine.    We have I think 1.8 installed systemwide, since that's what Ubuntu has.  I tried building 1.9 (linked to above) and it immediately fails with errors.

**Comment by haraldschilly** [comment]
The sad story about this is that the ubuntu packages seem to work well in my newer compute image, it's just broken in the old one running right now.

**Comment by slel** [comment]
Is this easy now that CoCalc has moved to Ubuntu 18.04?

**Comment by haraldschilly** [comment]
Is there some example code to test for QuantLib? Here is how it loads in python3 (as of today)

```
~/smc/src$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import QuantLib
>>> QuantLib.__version__
'1.12'
```
