### ISSUE TITLE
Send a notification email when sharing a project with a collaborator.

### ISSUE THREAD

**Issue by semorrison** [sagemathinc/cocalc#150]
I recently shared a project with a collaborator. They kept insisting that they hadn't received the invitation; they assumed an email would arrive with a link, so never actually logged in to see that they had access already.

**Comment by williamstein** [comment]
Currently an email is *only* sent when the collaborator you are adding does not already have a SageMathCloud account.    Yes, it would make a lot of sense to send emails in all cases, and would be easy to implement.

**Comment by williamstein** [comment]
Not "easy" since things like abuse/security have to be kept in mind when implementing features like this...

**Comment by timothyclemansinsea** [comment]
Removing myself as assigned because I would probably struggle trying to implement this.

**Comment by slel** [comment]
This has been implemented for some time, hasn't it?

**Comment by haraldschilly** [comment]
true!
