### ISSUE TITLE
Make chat messages appear as floating bubbles like with system wide alerts

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#1500]
I'm often doing work and see chat alerts. It would be nice if the chat messages would appear like system wide alerts do. It would also be nice to have a keystroke to make the alerts disappear.

**Comment by williamstein** [comment]
Some questions:

- what keystroke?
- when do we show the bubble exactly?  How do we avoid showing it more than once (if user refreshes browser)
- does the bubble show any information about the actual notifications, or just the number of them?

This is fundamentally different than the current model, where the notification information is 100% just a function of state of file use. 

Also, the current model is inspired by facebook in a web browser, where there are no pop up bubbles in the browser.  However, they do use HTML5 notifications in various ways (and of course send notifications to phones, etc.); how they do that may suggest answers to the above questions.
