### ISSUE TITLE
give professors a clear understanding of any SMC-based collaboration by their students

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1502]
This is one of those difficult and unclear issues that arises from use of SMC in actual exams.  Basically, it's a problem we probably have to solve

Here is the inspiring question from a user (Dominique Soudiere):
> Sometimes I ask students to work with others, but when i give an individual an evaluated work I have to be sure they didn't collaborate each other.  I can look at the log file but it is rather long. So  actually when they are in exam I look at the instant message of activity. I was asking of a possibility to activate an alarm : when in a course one student is collaborating with an other one on the exam project, the teacher is alerted.

Obviously the information is available to provide this.    There are many subtleties, e.g., a student could share their login credentials with another student (but then that student would be logged in twice... which we could also detect).

OK, given all that, it would be nice if we could design some sort of "overview of what students are doing in real time" that is natural, useful, and just *happens* to solve the above problem.   If one such clear idea appears that we agree on, this ticket will be come that.  If not, we close this ticket.

**Comment by timothyclemansinsea** [comment]
I would like to see "overview of what students are doing in real time" done in a way that is generic.

**Comment by novoselt** [comment]
>  If one such clear idea appears that we agree on, this ticket will be come that. If not, we close this ticket.
