### ISSUE TITLE
Provide our resource limitations functionality, based on cgroups, inside the docker container

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1513]
If yes, implement this.  If not, say why and close this issue.  Basically, can one use cgroups inside Docker?  (My guess, yes, but docker will have to run in privileged mode.)

**Comment by williamstein** [comment]
This is what we would eventually use: https://hub.docker.com/_/docker/

**Comment by HighwayStar** [comment]
Are there any news on cgroups based resource management for docker?

**Comment by williamstein** [comment]
> Are there any news on cgroups based resource management for docker?

Unfortunately, nobody is working on it for cocalc-docker, as far as I know.

**Comment by williamstein** [comment]
If somebody ends up wanting to contribute a solution (PR's welcome!), I don't think it would be too hard to implement.  Probably the best approach is to edit this file and run a snippet of code as root in the container (maybe using ulimit) to enforce some per user limits:

https://github.com/sagemathinc/cocalc/blob/master/src/smc_pyutil/smc_pyutil/smc_compute.py

You can experiment with doing so in a running cocalc-docker container by directly editing this file as root (via sudo docker exec -it cocalc bash):

/usr/local/lib/python3.8/dist-packages/smc_pyutil/smc_compute.py

**Comment by HighwayStar** [comment]
Actually this works using current Kubernetes related code. 

All you need to get it up and running on current docker image is to install package cgroup-tools

```
apt-get install cgroup-tools
```

and fix little issue in /usr/local/lib/python3.8/dist-packages/smc_pyutil/smc_compute.py

```
diff --git a/src/smc_pyutil/smc_pyutil/smc_compute.py b/src/smc_pyutil/smc_pyutil/smc_compute.py
index 5a129d08f..5e0066052 100755
--- a/src/smc_pyutil/smc_pyutil/smc_compute.py
+++ b/src/smc_pyutil/smc_pyutil/smc_compute.py
@@ -383,7 +383,7 @@ class Project(object):
         if self._dev or self._kubernetes:
             return
         cfs_quota = int(100000 * cores)
-        if os.system("which cgcreate") != 0:
+        if os.system("which cgcreate > /dev/null") != 0:
             # cgroups not installed
             return
 ```
After this enabling kebenetes onprem UI in Admin setting will provide way to set limits. 

Some docker host will need 
```
swapaccount=1
```
in host kernel commandline to make swap limits work. Set it if you getting error about permission denied to /sys/fs/cgroup/memory/%s/memory.memsw.limit_in_bytes  in /var/log/compute.err

**Comment by haraldschilly** [comment]
I suggest to close this. The supported and scalable way to do this is to go with CoCalc OnPrem.

**Comment by williamstein** [comment]
I agree.  I'm adding the wontfix label, by which I mean "there is still something here, but we are explicitly deciding not to do it at this time.  If we have way more resources we may revisit this later."
