### ISSUE TITLE
do not load stripe or google analytics in any way when commercial is not yes (e.g., for the Docker image)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1516]
This will avoid messing up our metrics, make things faster, etc.

**Comment by williamstein** [comment]
> hsy: yes, this is something I wanted to look into, but it is a bit tricky. It's basically the same as with the current wrapping and defered loading of google analytics.

**Comment by haraldschilly** [comment]
Just to clarify what is quoted above: there is no google analytics token in the smc codebase. If it isn't defined in the secret file for it, there is nothing written to the main index.html file and hence nothing it loaded. Any calls to do anything with google analytics are not doing anything. Regarding `commercial != yes`, I don't think we need any additional measurements for that. I.e. I think it's perfectly ok to include google analytics, if someone installs one's own google analytics token on a noncommercial instance of SMC. 

Regarding stripe, there is already lazy loading of the stripe api. The only remaining question is, if there should be a "commercial" check before `load_stripe` [here in submit_payment_info](https://github.com/sagemathinc/smc/blob/9dabbe6c98967e37c0f8a9a8ccd68189a0c8ef22/src/smc-webapp/billing.cjsx#L108)

**Comment by williamstein** [comment]
>  I don't think we need any additional measurements for that. I.e. I think it's perfectly ok to include google analytics, if someone installs one's own google analytics token on a noncommercial instance of SMC.

I totally disagree.  What if the user doesn't have internet access at all, or is very careful about services they run opening connections to third party services?

**Comment by haraldschilly** [comment]
>  What if the user doesn't have internet access at all, or is very careful about services they run opening connections to third party services?

I'm wondering why would they then explicitly add the google analytics token in the first place? It's weird for me to setup SMC (no token for GA) and having the desire to avoid third party services, then they install the token explicitly (it's opt-in, not opt-out), and then commercial=no should disable it again? Besides that, why should GA always be disabled if there is an existing token for GA but commercial=no?

**Comment by williamstein** [comment]
I completely misunderstood you; sorry.  If GA isn't queried at all if there is no token, that's fine.
