### ISSUE TITLE
when commercial is no, don't include the links to historical and other usage stats, which make no sense

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1517]
Right now this is basically the "More data..." link on help and landing pages:

<img width="388" alt="screen shot 2017-01-16 at 12 07 17 pm" src="https://cloud.githubusercontent.com/assets/1276278/21997463/5adf5450-dbe4-11e6-8ef1-bf03dd74e92e.png">

**Comment by haraldschilly** [comment]
This exists in a different way and works fine. Also, the internal long-term stats are not shown outside of the `cocalc.com` world.
