### ISSUE TITLE
Some of the "getting started" panels in the bottom of the About page hardcode cloud.sagemath.com.  

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1518]
These panels should use whatever the current site is is not be there at all if they don't work.

**Comment by williamstein** [comment]
@haraldschilly -- did you fix this already with the cocalc rebrand?

**Comment by haraldschilly** [comment]
well, let's just close this. I think the panels have all changed. There is only one legit use of the old domain name:

```
⋊> ~/s/s/smc-webapp on master ⨯ git grep 'cloud.sagemath.com'
misc_page.coffee:128:    is_formersmc  = document.location.origin == 'https://cocalc.com' and misc.startswith(href, "https://cloud.sagemath.com")
```
