### ISSUE TITLE
course feature request: when adding a new student, automatically assign all already-assigned assignments to that student.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#153]
From: Jayadev Athreya

**Comment by kcrisman** [comment]
Very sensible idea, at least as an option.

**Comment by johnjeng** [comment]
Current plan:
Have a checkbox option: `Update this/these student with all distributed content?` where "distributed content" means assignments and handouts given to *any* student.

Potential future plan:
Have an option somewhere that allows instructors to default to automatically do this, never do this, or always ask.

**Comment by williamstein** [comment]
Requested AGAIN by: Jayadev Athreya

**Comment by williamstein** [comment]
There's a catch up button now-a-days that solves this.
