### ISSUE TITLE
make it possible for instructors of courses to assign "team homework assignments"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1535]
It's silly that SMC's only officially supported assignment method strongly encourages students to NOT collaborate at all.  SMC is about collaboration.  

From a professor:
>  I intend to have students work in teams of 2 for their labs. (These teams
will rotate, so that there will be brand new partner assignments for each
lab.) Do you have any thoughts on the best way to have a single partner turn
in their team's lab, yet the grade for that lab be recorded for both
participating students?

>    On the bottom of this page:   https://github.com/mikecroucher/SMC_tutorial/blob/master/interactions/interactions.md

>    I read about the "one project per team" option. That sounds like what I
want, but with a possibly different workflow...is it possible for me to assign
an assignment, as normal, and then for one parter on each team to mark their
copy of the assignment as collaboratively-shared by the other? Then both
partners can work together on the same shared project, and turn it in via the
normal assignment collection/grade/return process? Or will it be messed up
since the second partner will also have their own (unshared) copy of the
assignment in their project? Can the two co-exist?

**Comment by sj-graves** [comment]
This is a really good idea; I'm teaching an "intro to programming for mathematicians" course through SMC this semester. I think the way that student projects currently work as a collaborative project between the professor and student is brilliant, but since collaboration is at the project level, Alice would have to share her whole course project with Bob for them to work together on an individual assignment.

Is there any way to make collaboration more granular, sort of the way that Google Drive allows individual files/folders to be shared?

**Comment by williamstein** [comment]
> Is there any way to make collaboration more granular, sort of the way that Google Drive allows individual files/folders to be shared?

Not yet -- collaboration is defined at the *project* level.   In SMC -- unlike Google Drive -- a key component is **compute**, i.e., actually running code, and this is encapsulated in the container/Linux user that a project provides.  However, projects are very lightweight, and you can make many of them.  Google drive's big difference compared to SMC is that you can't run arbitrary complicated Linux programs in Google drive...

In the future, we will likely have a notion of "several projects that all share the same quota", so they are separate from a permissions/users point of view, but share the same compute upgrades.   This will be easy when we make our new Kubernetes backend live...

**Comment by johnjeng** [comment]
This is #196?

**Comment by gabindu** [comment]
If I may, I have a concrete suggestion for a partial solution to this, which focusses just on **returning** marked assignments & grades to all team members, with very little changes necessary on the backend.

Here is the workflow I already use for team work:

1. Distribute an assignment to all students as usual.
1. Ask each team to have only one member (the "team leader") submit the work (I tell them to use the team member with the "alphabetically-first last name") - but to collaborate in a separate shared project beforehand.
1. Collect the assignment (from all students) as usual
1. Mark the assignment only for the "team leaders"
1. **return the assignment** (by _manually_ copying the marked files from the team leader into the folders of the other team members, before clicking on "return" - I actually wrote a kludgy shell script for this, but that's clearly not ideal.)

----

To greatly simplify especially the last step, I think a **relatively simple solution** would be the following (**all done at the level of the `.course` file**, decided by the instructor):

1. **Add a checkbox to turn the assignment into a "group assignment"** _(simply saved as a boolean variable in the `.course` file)_
2. **Add the ability to assign a team number & a "team leader" boolean variable** for each student in this assignment _(again simply stored as metadata in the `.course` file)_ - this could be simply done with a _pull-down menu and a checkbox_ for each student, or (fancier) using drag-and-drop. A possibility to copy the team attributions from a previous assignment would be a bonus. (For me, teams very rarely change during the semester - but I'm sure others might need that.)
3. Ideally, **filter the student view to only show the team leader for each team**, or group them.  _(Really just a visual change in the UI, so not even top-priority)_
4. The **"collect" button then could focus just on the team leader** (or pull in from all students just as usual)
5. (Most importantly) **The "return" button** should then place copies of the returned files to **all** team members.
6. (optional) For each team (& assignment), automatically create a new shared project for all team members. This could then even be used **instead** of the team leader's project, for collecting and returning... 

It seems to me that all this could be done without requiring any change to the way projects and course memberships are handled right now. It'd be great if even just a small subset of these could be implemented, but no pressure! ;-)

**Comment by williamstein** [comment]
This is a duplicate of #196.  Of course, @gabindu, your comment above is greatly appreciated.
