### ISSUE TITLE
In chat message sent "time ago" does not update until a new message is sent

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#1548]
Time ago used to be accurate in chats. Then someone added rendering restrictions that prevent time ago from being accurate.

**Comment by williamstein** [comment]
Annoying to me -- so priority high!   but you're right that it is M-low.

**Comment by williamstein** [comment]
I fixed this in my jupyter2 branch.  It was caused by TimeAgo changing their minPeriod parameter from seconds to ms...  so this will be fixed when I merge that later this week.
