### ISSUE TITLE
create a not-yet-supported editor for some common file types, to avoid corruption

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1556]
1. upload your super valuable xlsx  excel spreadsheet to smc
2. click on it
3. It's now corrupted!

Fix: make a really simple editor that says "this file type not supported" and register it for xlsx, and maybe some other types.

Longterm fix: support xlsx somehow...

**Comment by haraldschilly** [comment]
there is a fallback editor, which tries to guess the filetype and shows it if it is text … or otherwise reports it is binary without being currently supported. Anyways, those files won't get corrupted any more, unless the user decides to still open them.
