### ISSUE TITLE
project upgrade inconsistencies

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1557]
in some cases, upgraded projects stop working. their quota is set to `member: 1` but their assigned host is either undefined (field is empty) or still a free node.

**Comment by williamstein** [comment]
Switching to Kubernetes will fix this (or replace it by a different bug).

**Comment by slel** [comment]
Has the problem reported here occurred again after the switch to Kubernetes?

**Comment by haraldschilly** [comment]
well, no, the above can't happen. I'm closing this ticket.
