### ISSUE TITLE
Remove given upgrades when deleting a student

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#1562]
This just makes sense to me. Especially at the beginning of courses, instructors are adding and dropping students all the time.

I'd say it's analogous to removing upgrades when deleting a project.

**Comment by williamstein** [comment]
closely related to https://github.com/sagemathinc/cocalc/issues/1486

**Comment by johnjeng** [comment]
Fixed this bit. 

Undeleted students should have their upgrades restored if possible but I think that will be included in #1486
