### ISSUE TITLE
add an additional field next to the grade field for courses called "comment"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1573]
In addition to giving each student a grade, it is very useful to be able to type a full sentence comment about why they got that grade.  This should be put into the "GRADE" file that the student gets back.  It should of course be optional.  Also, it must be put in the csv file as well as another column.

Requested by: Kristin McCully (UCLA), who has taught a LOT using SMC...

**Comment by novoselt** [comment]
It seems to me that all is implemented!
