### ISSUE TITLE
When creating a new file allow one to easy change directory

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#1574]
I have found myself trying to create a file in the wrong directory and having to click on a tab in the right directory and then back to create file or go to files tab then right directory then create file. It would be nice to not have to do that.

**Comment by johnjeng** [comment]
You can just move the file after you create it in the wrong place. Also, do you mean on the `New` page?

**Comment by haraldschilly** [comment]
I'm closing this. The main issue here might have been, that by switching files the current directory jumps around.
