### ISSUE TITLE
change all course tutorial links to the website

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1577]
new landing page for the smc course tutorial: https://mikecroucher.github.io/SMC_tutorial/

**Comment by williamstein** [comment]
I just looked critically at Croucher's pages on github versus the jenkins generated pages.  Frankly, I think the github hosted pages look way more clean and readable!   The Jenkins ones are way too small, the spacing is horrible, often section headings are repeated, etc.  It's confusing.   I also see things that we've changed -- e.g., removing "add collaborators" -- and I can't fix this instantly on any of croucher's stuff.  

This documentation is way too important and central to our goals to outsource or take a chance with it being even slightly wrong.  We need to take this over ourselves ASAP and make sure it is and stays completely perfect.
