### ISSUE TITLE
javascript/node kernels?

### ISSUE THREAD

**Issue by Fil** [sagemathinc/cocalc#1582]
Is there a way to create a javascript notebook/kernel?

I'm trying to do a comparison with [nteract](https://github.com/nteract/nteract), [kajero](https://github.com/JoelOtter/kajero), and jupyter+[IJavaScript](https://github.com/n-riesco/ijavascript).

**Comment by haraldschilly** [comment]
I've an "experimental" kernel in one of my development projects for IJavaScript. It should install pretty straightforward into your local `~/.local/share/jupyter ...` directory. If the installation works fine and you click on "refresh" in the jupyter notebook, it should appear there.

**Comment by williamstein** [comment]
We have had an official Javascript kernel for a very long time now.

<img width="527" alt="image" src="https://github.com/user-attachments/assets/89f1f684-ea8a-4b7e-9f52-2c8a641476ba">
