### ISSUE TITLE
Hyperlinks and URLs in LaTeX work in PDF view, but not preview

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#1584]
Using the url package to embed hotlinked URLs in a LaTeX file works in the PDF view, but the links don't seem to be active in the Preview view.

**Comment by williamstein** [comment]
The preview is just a PNG image, and I really have no clue how to implement this, so I'm labeling this "insanely hard'.    My best idea would be to use inverse search, find the corresponding source line, and heuristically searched for links there, and open whatever the first one is (so this might work, but not always, and I can't imagine how it would work for internal hyperlinks).

**Comment by kedlaya** [comment]
Fair enough!

**Comment by williamstein** [comment]
> Fair enough!

Well, I've thought things were insanely hard before, and suddenly @haraldschilly figure it out... or maybe one of our competitors has????

**Comment by haraldschilly** [comment]
There are libraries that convert arbitrary pdf to html + svg (to be part of a website) … they also handle all the urls. the problem is, that I don't know how to scale this up to hundreds of pages of PDF. we essentially need a technique that's constant in the size of the pdf.

**Comment by williamstein** [comment]
Yes, I shouldn't forget that a huge amount of the work of our preview system now is about efficiency. The problem isn't so hard if you don't care about speed / scalability.

**Comment by williamstein** [comment]
Sharelatex's preview does support this along with copy/paste.  It's not image based...

**Comment by williamstein** [comment]
this was solved long ago by switching to pdfjs.  We don't use png's anymore for preview.
