### ISSUE TITLE
make font size of side chat easily adjustable

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1591]
There should be both a global default, and the ability to adjust the font for a specific side chat (right from the chat).  Same with normal chat, though that should be another issue.

**Comment by williamstein** [comment]
Why?  @haraldschilly thinks the fonts of the side chat are too big, and I think they are too small!

**Comment by haraldschilly** [comment]
Well, I would be happy if the side chat has the same font size as the font size setting for the usual editor. My setting is 12px but side chat is 14px. That's why I said it's larger.

**Comment by williamstein** [comment]
> Well, I would be happy if the side chat has the same font size as the font size setting for the usual editor. 

That would definitely be a good start.  However, some people (like me) have eyes that get tired (or not) and I really like being able to trivially change the font size of anything I'm in on the fly, depending on my "mood".    With editors and terminals now, it's trivial to quickly change the font size, but not for chat.

**Comment by williamstein** [comment]
> Well, I would be happy if the side chat has the same font size as the font size setting for the usual editor.

That is true right now.
