### ISSUE TITLE
support Jeroen Demeyer's PARI/GP Jupyter kernel once it stabilizes

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#160]
See http://pari.math.u-bordeaux.fr/archives/pari-dev-1510/msg00008.html
It's clearly not ready to use right now, but should be soon.  Keep it in mind.

**Comment by williamstein** [comment]
How to do it now:
1. `sage -pip install pari_jupyter`
2. Here’s the kernel.json file to use:
```
{
    "argv":["sage", "-python", "-m", "PARIKernel", "-f", "{connection_file}"],
    "display_name":"PARI/GP",
    "language":"GP"
}
```

**Comment by haraldschilly** [comment]
I've installed the sage optional package `pari_jupyter` instead. It seems to be more safe to me to pick the spkg.

**Comment by williamstein** [comment]
Somebody could make screenshots and post an announcement about this (and also for GAP).
