### ISSUE TITLE
Make it easy to create multiple assignment folders at once. 

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#1606]
2 things: How many assignments do you want to create? Create another assignment. folder names would be assignment{n}

**Comment by williamstein** [comment]
Nobody has ever once requested that feature....

**Comment by timothyclemansinsea** [comment]
@williamstein Croucher mentions it "However, such a method could be quite time consuming when you need to create multiple folders, subfolders, and documents. If you are a terminal fan you could create a shell script in your preferred programming language and run it from the terminal."

**Comment by johnjeng** [comment]
Maybe someone can write a script for it or something (reading from a csv file?). But I think integrating it into our system would create too much clutter for too little gain. I can't think of this kind of functionality being offered by any OS.

**Comment by novoselt** [comment]
UI complication for little gain, in my opinion...
