### ISSUE TITLE
add line numbers to file url's

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#161]
Github adds `#L77` after a file url to indicate a given line number, starting with 1 (not 0).  We should too, e.g., 

   https://cloud.sagemath.com/projects/3702601d-9fbc-4e4e-b7ab-c10a79e34d3b/files/salvus/salvus/build.py#L190

would be line 190 of the file build.py in that project.   Then when somebody clicks to open the file, it would go to that line. 

While editing we could keep this up to date in the URL, but maybe only update it once every 5 seconds or so (have to experiment).   Also, we'll have to decide which cursor takes precedence when there are many of them.   We also have to make the "open a file" flux action fully support this, and also integrate this with the search in files page.

**Comment by williamstein** [comment]
Useful for https://github.com/sagemathinc/smc/issues/182

**Comment by rbeezer** [comment]
I'm interested in this one, since it will make it possible to link between worksheets and land at some interior location.

https://groups.google.com/d/topic/sage-cloud/JpUBRyvLyQc/discussion

**Comment by williamstein** [comment]
We have this now, plus much more regarding fragments...
