### ISSUE TITLE
multilingual support for TeX docs (utf8 encoding)

### ISSUE THREAD

**Issue by dimpase** [sagemathinc/cocalc#1610]
For people who write TeX files in some unusual encoding (e.g. `latin2`, or cyrillic encodings could be
even harder to deal with)---I guess on Windows or some other systems that support such
encodings natively---and then try them on SMC TeX it might be tricky to realise that they are supposed to do
everything in UTF-8, cf. e.g.[ this thread](https://groups.google.com/d/msg/sage-support/lPk6QUyrDb4/vwRdviUcBgAJ) - they start thinking that their specific language support is lacking etc. It ought to be documented that they should do `\usepackage[utf8]{inputenc}`.

**Comment by haraldschilly** [comment]
There could be a fourth tab on the right hand side of the latex editor titled "help". that could be a short intro and pointing to some links ... some pages maintained by smc, some others are like that wikibook latex guide. What do you think about this idea?

And regrading language support: one of the harder parts are special characters in code listings and so on. For that, one has to switch using xelatex. I don't really know it, but in some circumstances there is no way around it.

**Comment by dimpase** [comment]
there are particularly bad cases where only xelatex, or only pdflatex, work (Hebrew support comes to mind).
But the thing in the linked thread is OK with pdflatex.

**Comment by slel** [comment]
I think this is fixed by the (January to March 2017) commits to the file
https://github.com/sagemathinc/cocalc/commits/master/src/smc_pyutil/smc_pyutil/templates/linux/default.tex
