### ISSUE TITLE
update link to Croucher's SMC tute from .course settings page

### ISSUE THREAD

**Issue by dimpase** [sagemathinc/cocalc#1613]
it still points to https://github.com/mikecroucher/SMC_tutorial#sagemathcloud
rather than to https://mikecroucher.github.io/SMC_tutorial/

**Comment by williamstein** [comment]
I'm not convinced the prettier version is actually better, honestly.

**Comment by dimpase** [comment]
Well, I can point out that in the prettier version, once you're looking at a section, you can navigate to the next or to the previous directly (buttons at the bottom). 
I can also say that the source does not pop up there, and not everyone lives on github and is thus able to ignore such clutter automatically :-) But yes, the prettier version certainly can be improved... @mikecroucher

**Comment by haraldschilly** [comment]
closing this. the repo is here https://github.com/sagemathinc/cocalc_tutorial and actually, we should devote some time to it
