### ISSUE TITLE
course collection -- ability to limit size of student files

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1616]
> "Would it be possible to implement a feature that either (1) allows us to specify a size limit for collecting, or (2) automatically not collect files over a certain size? Otherwise we will probably keep running into this problem."

Flip a flag if large files were ignored, and in grading view give a link to the directory where the big files are located.

**Comment by williamstein** [comment]
Basic question: how to tell rsync to ignore files above a given size?

**Comment by cgreene** [comment]
Ooo! I think this is for our course! :+1: 

There is a flag for that:
     --max-size=SIZE         don't transfer any file larger than SIZE

**Comment by cgreene** [comment]
For a bit more detail:

`
cgreene@casey-greenelab:~$ man rsync | grep max-size
            --max-size=SIZE         don't transfer any file larger than SIZE
       --max-size=SIZE
              value (e.g. "--max-size=1.5m").
              Examples:    --max-size=1.5mb-1    is    1499999    bytes,   and
              --max-size=2g+1 is 2147483649 bytes.
              --max-size=0.
              small,  junk files.  See the --max-size option for a description
              been  appended).  See the --max-size option for a description of
cgreene@casey-greenelab:~$      --max-size=SIZE         don't transfer any file larger than SIZE
`

**Comment by novoselt** [comment]
> Otherwise we will probably keep running into this problem.

Looks like we are not running into it too often ;-)
