### ISSUE TITLE
 It would be nice if control+s (or command+s) in chat *sent* the message, which is like save.   

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1619]

**Comment by DrXyzzy** [comment]
Questions:
- `shift+s` would be uppercase S. Maybe `ctrl+s`?
- `command+s` on OS X brings up page save dialogue with Chrome, Firefox, and Safari. Do we want to override that?
- make both actions work in all operating systems? (where`command+s` same as `Windows key + s` on windows keyboards running Windows or Linux)

**Comment by williamstein** [comment]
> shift+s would be uppercase S. Maybe ctrl+s?

sorry, I meant ctrl+s.

> command+s on OS X brings up page save dialogue with Chrome, Firefox, and Safari. Do we want to override that?

YES -- exactly like we already do for most editors.

> make both actions work in all operating systems? 

Whatever the standard shortcut for save in an editor is in a given OS should save.  That's it.

**Comment by williamstein** [comment]
This makes zero sense today because command/control+s just saves the document (which now has a save button).  That shouldn't send a message.
