### ISSUE TITLE
restore the  position of the document in the latex preview when switching tabs away and back

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1621]
If you positive the preview in the latex editor, then change tabs, then come back, it is VERY ANNOYINGLY reset.

**Comment by williamstein** [comment]
@johnjeng  perfect for you, right - you just fixed this for courses.

**Comment by williamstein** [comment]
This makes latex editing incredibly painful if you're going to any other tabs.  OUCH.

**Comment by williamstein** [comment]
Other people are complaining about this...

**Comment by haraldschilly** [comment]
I think I solved this in june with that patch above. Closing.
