### ISSUE TITLE
Add Custom Ordering to Students

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#1623]
With sorting implemented in students, it makes sense to allow for custom sorting and also saving the last sort preference in localStorage.

>One issue I've run across is that students don't input their own names very well when they register for SMC. Some only use their first name, others include a middle name or initial, some have Jr., etc., some have compound names, some don't put a space between their first and last name, and so on.

>I would like to see the student list numbered, with the option of the instructor manually changing the numbers and sorting by number. Then I could put my students in the same order as they appear on my roster. I could also keep track of different sections this 

>Just make the current sort preference always be saved in localStorage on that client browser.

**Comment by aarontresham** [comment]
You can now sort students on the "Student" tab in a course, but it would be very helpful to be able to sort students under the "Assignments" tab for grading purposes.

**Comment by williamstein** [comment]
OK --  I made this https://github.com/sagemathinc/smc/issues/1635

**Comment by novoselt** [comment]
I do recall having similar issues trying to put together grades from different sources, but trying to keep track of some custom order is error-prone anyway, will complicate the user interface, and I don't recall seeing such a functionality in other student listings. We can revisit it with more demand!
