### ISSUE TITLE
Compare students in course to a given list

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#1629]
After a couple of weeks into a course, the list of students with projects may differ from the list of students enrolled in the course, due to students dropping the class. What I really need is an easy way to find all of the projects that do not correspond to email addresses on a given list, to identify those as candidates for deletion (so that they don't get assigned as part of peer grading).

**Comment by novoselt** [comment]
Assuming that email list is coming from the same source in the same format, looking at a diff between two versions should show removed students. As far as making it easy for users, having "Compare" function in the file explorer would be better than something limited to courses only. And for courses the ideal solution may be automatic sync with LMS.
