### ISSUE TITLE
grade export -- separate first and last name as two columns

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1640]
> "What would be really helpful is when it exports the grades to .csv that it would be first and last name into two different things, instead of combined, because then when I copy the grades into excel, I can't sort by last name. Well, I could write an excel function to split the names or something, but I wouldn't have to do that if the .csv just had it set that name normally. When using SMC for a class, this is the kind of thing that really does matter."

**Comment by novoselt** [comment]
I am confused on the status of this - instead of splitting the name into two columns, which seems quite natural at least as an option, we now allow sorting by the last name, but then dump CSV as combined anyway? And everybody is happy?

**Comment by williamstein** [comment]
Nobody has complained about this for 7 years, evidently.

**Comment by novoselt** [comment]
Then let's close it - existing users can apparently do without, so no need to complicate the UI for them.
