### ISSUE TITLE
non-mysterious ghost-tab

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1641]
sometimes, e.g. when I close/open an editor from the log (but I think it could happen any time), I see a half-tab right there. Is this a placeholder for something? Or a leftover from a previous operation?

I can hover it, and then it is visible to me. Maybe disable hover-CSS? I've attached a screenshot that should help. 

![smc-ghost-half-tab](https://cloud.githubusercontent.com/assets/207405/22560996/d6a3e4b2-e976-11e6-8bfe-eefc084bb276.png)

**Comment by williamstein** [comment]
@johnjeng implemented this; it was his clever trick to use flexbox so that if you close several tabs, they don't resize as you're trying to close them.  It should be that when you move the mouse away the ghost tab is removed.  Sometimes it isn't.  This is definitely a bug that I've seen.

**Comment by haraldschilly** [comment]
oh, makes sense, it goes away after a bit. well, then this is just about the css hover.

**Comment by haraldschilly** [comment]
ok, I think this is solved. The patch above removes such a ghost tab 5 secs after closing a tab.
