### ISSUE TITLE
course: make the grades be *synchronized* with contents of file GRADE.txt in grading folder

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1642]
Provide a button to sync grades with GRADE.txt files.  This would keep track of the timestamp of the file and the last time the grade was edited in the UI.  If the file changes, it would then overwrite the grade listed in the UI.  Conversely, if the UI changes later, then the file is updated.

This would help facilitate grading anonymously, where the grader gets a copy of assignments, and they get copied back.  It would also make it much easier to automate things.

**Comment by novoselt** [comment]
Sounds useful, but was there a continuous demand over the years?

**Comment by williamstein** [comment]
Nobody ever requested this.
