### ISSUE TITLE
we desperately need **immediate feedback** when you click on a file in the file listing

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1643]
1. click on a file in the listing (especially one not opened ever before).
2. visibly absolutely nothing happens for a second or two
3. Suddenly the tab appears, waiting, etc.

Step 2 should be replaced by some visible feedback.  One natural option is delete step 2.

This is very disconcerting to me, and I'm sure a lot of other people...

**Comment by DrXyzzy** [comment]
I almost never see the delay in step 2, but see step 3 delay frequently when opening .term, .sagews, and .md files. Tab for the file opens but appears empty for several seconds.

**Comment by williamstein** [comment]
1. click on a file in the log while the project is starting.
2. literally nothing visible happens.

**Comment by williamstein** [comment]
This should be much less of a problem because files now open 10x more quickly....
