### ISSUE TITLE
student cannot create his/her own course and add teacher

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1661]
This is for a meta-course, when an SMC course involves students creating their own courses. When a student creates a new .course file and searches for the instructor's email to add as a student, the result is
- "student already added" under the added students box,
- blue message box under `Find students...`: "Already added students or project collaborators: [teacher_email],[teacher_name]".
- "Students(0)" count displays at top of course file.

**Comment by williamstein** [comment]
This was a design decision...  But we will revisit it.

**Comment by DrXyzzy** [comment]
I can document it as such then. Instructor can view student projects, and their students' projects, I think... will be testing that this morning some more.

**Comment by DrXyzzy** [comment]
Design decision not to allow student creating course that adds teacher. But then shouldn't code issue an error when this is attempted, rather than the odd behavior observed?

**Comment by williamstein** [comment]
wontfix
