### ISSUE TITLE
make it possible to edit the displayed email address for a student in a course

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1669]
This is just a natural followup to https://github.com/sagemathinc/smc/pull/1645

Picture of where editing email would go:

<img width="654" alt="screen shot 2017-02-11 at 7 00 12 pm" src="https://cloud.githubusercontent.com/assets/1276278/22859322/818048e6-f08c-11e6-8c46-b3c99c40614b.png">

This will also make it possible add emails of students that you may have added by name, which is an often requested feature!

**Comment by johnjeng** [comment]
This is done.
