### ISSUE TITLE
parse TexShop/Tex configuration variables

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1675]
according to this posting: http://tex.stackexchange.com/a/78103/11611 there are sometimes `! TEX ...` configuration variables embedded into the tex file. We should parse them, especially the ones for the engine and the spellcheck language.

First step of this ticket would be to actually track them down, how they're called, and what they really mean.

**Comment by williamstein** [comment]
too vague and nobody ever asks for this.  or maybe we already do this?
