### ISSUE TITLE
course collection -- provide aliases for displaying the names of the folders

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1677]
> valeriodea@gmail.com: The course-collect folder is useful, but it would be more useful if the names of the folders containing the students' files would help identify the student. Instead I see strings of characters such as7e46bd8e-e11a-4df1-977e-e5d5cf878642. Is there a way to change this to the student's name?

---

We could implement this in many ways.  One option would be to provide an alias file, e.g., .smc-ls, which if visible, would provide aliases for displayed folder names.  The course manager could write such a file, and the smc-ls command (that python script) would be aware of it when computing and returning the directory listing.

We could also do something else involving a file and aliases. 

Note that this perhaps should NOT be made automatic, since some people consider the fact that student collect folders are random-looking (hence anonymous) to be a *feature*, not a bug (it's used for graders).

**Comment by novoselt** [comment]
I think access through the course interface should be made sufficient for all "manual" tasks, while for scripts naming should be irrelevant. And it does not seem to be a popular request.
