### ISSUE TITLE
add course actions to the project activity log (or better, to their own log?)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1692]
Expected behavior: assignments, handouts, adding/removing a student, etc. shows up in the project activity log.

**Comment by williamstein** [comment]
One subtlety -- this would be the first time that the project log has entries for actions in a file.  it's a little worrisome.  If we do this, where do we draw the line?   

The course itself could also have a log of actions.

**Comment by haraldschilly** [comment]
good point. that log is better kept inside of the course file.

**Comment by williamstein** [comment]
If the motivation is worry about corruption, robustness, etc., then the right fix is -- of course -- to make json-based sync'd documents "insanely robust"... even more than now...  I have a good plan for this, I think.

**Comment by timothyclemansinsea** [comment]
I like the idea of doing this with the existing project activity log so one is not having to duplicate a bunch of existing functionality.  My thought is add more stuff to project log and a tagging widget like projects and todos have to only show certain tags by default.

**Comment by williamstein** [comment]
Another possibility -- which makes WAY more sense to me -- is to make courses have their *own* activity log.  When using a course, you want to know what the activity is for that course, not across all courses, so that's probably where you want the log.

**Comment by williamstein** [comment]
>  to make json-based sync'd documents "insanely robust"... even more than now... I have a good plan for this, I think.

Which I carried out successfully years ago :-).

I'm closing this.

And the information about what happened is in the TimeTravel history for the file.   In addition, no actual course users have requested this, so it might be clutter.
