### ISSUE TITLE
add terminal mouse support, e.g., so can select tmux pane with mouse (or nano cursor position)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1694]
See http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking

**Comment by haraldschilly** [comment]
my https://github.com/sagemathinc/smc/tree/term.js-bugs branch fixes everything necesary to have mouse support -- although no idea how to get it to work in tmux. my test case is htop, i.e. that I can use the mouse to select the column to sort for, or click on a menu button at the bottom to execute an action (setup, tree-view, quit, etc.)

**Comment by haraldschilly** [comment]
As of today, mouse clicks do work in htop, but not in tmux. This means there is support for sending click commands, but tmux might need some additional help to understand it (tmux is also certainly outdated, so I'm closing this and we can revisit this later on a per-application basis or as part of a terminal rewrite)
