### ISSUE TITLE
add pari jupyter kernel

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1709]
https://github.com/jdemeyer/pari_jupyter

**Comment by slel** [comment]
Closing as duplicate of #160.

**Comment by slel** [comment]
For reference, the PARI Jupyter kernel is now hosted at
https://github.com/jdemeyer/pari_jupyter
and it can be installed on CoCalc by following the instructions there,
with slight changes which William will now describe.
