### ISSUE TITLE
strongly encourage students in classes to associated their account with gmail

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1716]
1. A student signs up for SMC for a course using say `jackson@uni.edu`
2. They take a class
3. They graduate and go work at Awesome Company
4. We introduce the perfect product that the student could use at Awesome Company
5. We have now way to tell the student about the product, since their @uni.edu email  is disabled!
6. The student wants to consult their work from the class they took to solve a problem for Awesome Company, but they can't remember their password and they can't do a password reset since they don't have access to their @uni.edu email.
---

We could solve all of this by strongly encouraging students to link their SMC account with their Gmail account.

**Comment by williamstein** [comment]
@johnjeng -- this is what we were just talking about...

**Comment by haraldschilly** [comment]
my 2 cents: let users have more than one email address. i.e. introduce to an `email_address2` field in the schema, which is an array, and think hard about how to update the code and all the ugly details to make that work. once that's done, we could expand that to allow merging accounts.

**Comment by williamstein** [comment]
@haraldschilly -- but is that needed at all for this problem?  All users have to do is link their gmail account, which is separate from their edu account.

That said, having multiple email addresses and multiple linked accounts would be desirable also.

**Comment by haraldschilly** [comment]
well, I also thought about those cases, where the edu account is a google account. I fear this could get messy, and we have to avoid breaking student invitations to courses by their school email address. that's why I argue for multiple email addresses

**Comment by williamstein** [comment]
> well, I also thought about those cases, where the edu account is a google account

In that case we do not display a request.    The way I described this ticket, it would be pretty easy for somebody to implement in two hours with no backend changes.  Doing what you describe might take day(s).  We should do both, but your should be another ticket.

**Comment by mforbes** [comment]
Just a comment here: university policy is often that students use their university account for all course-related activity.  We also do not always have student's gmail addresses, so automatically invite them with their university account.  What should we ask them to do right now?

1. Create a personal account with their gmail (other long-term email).
2. Share all their school projects with said gmail account?

Or

1. Change the email in there account to their gmail account? (This is an issue if they already have an account - they would need to merge them...)

Or, something else?

**Comment by williamstein** [comment]
In one week there will be https://github.com/sagemathinc/cocalc/pull/5790, and then you could require all students to use SSO through the university?

**Comment by novoselt** [comment]
The way how it is titled should definitely not be implemented, universities are likely to prefer their accounts. As a way to stay in touch with students later - I am a bit skeptical it will be beneficial. And supporting multiple emails while useful in principle, is unlikely to be widely used. It would be better to require at least one verified email instead.
