### ISSUE TITLE
Add a course info form to course settings

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#1733]
Add a form to the top of course settings asking for course name, course url, instructor's name, instructor's url, and institution. Explain that it is for https://github.com/sagemathinc/smc/wiki/Teaching For staff there would be a checkbox, called approved. On each edit by instructor approved becomes False and staff get an alert to review edit.

The purpose of this form is to give instructor's control over the listing of their course and speed up modifying the public list.

**Comment by novoselt** [comment]
That is definitely in conflict with privacy and making it done in a "politically correct" way is likely not worth the effort.
