### ISSUE TITLE
report student disk use in course project

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1739]
inform teachers about students nearing their disk quota limits in the course overview

**Comment by novoselt** [comment]
Sounds interesting and perhaps not difficult to implement, but it kind of puts the burden on instructors to monitor students disks and then act proactively. Or ignoring this info until students complain. While complicating the interface.

**Comment by williamstein** [comment]
It is also possible for an instructor to see this info by typing “df -h .” In the “run terminal command in all student projects” things.

**Comment by williamstein** [comment]
I.e., this is easy to do already with`df -h .`:


<img width="820" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/36d3236a-dbcb-4a75-adac-e562214211ac">

And `du -sch * |sort -h`: 

<img width="794" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/9c9a415f-8b31-42fe-a355-83e564d52c1d">
