### ISSUE TITLE
Provide a Jupyter kernel for OCaml

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#175]
We spent over an hour on this and failed (starting with https://github.com/andrewray/iocaml).

We did install the following packages system-wide:

   ocaml-batteries-included opam opam-docs

In theory everything else can be done by a user in their own project.   In a terminal:

These steps work:

```
opam init
opam install iocaml
mkdir ~/.sage
ipython profile create iocaml
```

This step fails, since there is no iocaml/profile stuff:

```
cp -r `opam config var share`/iocaml/profile/* `ipython locate profile iocaml`
```

In fact,

```
~$ cd `opam config var share`/iocaml/
~/.opam/system/share/iocaml$ ls
~/.opam/system/share/iocaml$  
```

There's also an open issue about getting iocaml to work with ipython 3.1 (and we're > ipython 4.0 now):

https://github.com/andrewray/iocaml/issues/35

If anybody can figure out how to get Iocaml support working with Jupyter in their project, let me know.  Otherwise, file bugs with iocaml devs and/or fix them.  If nothing else, their docs are confusing/broken.

**Comment by williamstein** [comment]
Hint from the developer of iocaml:

```
Hi,

Thanks for raising this issue.

I really haven't followed ipython/jupyter developments properly as
iocaml comes with it's own server component.

However, I am aware that the kernel is getting a bit old and crusty
these days.  Through backwards compatibility it seems to still just
about work (along with the fix in issue #35).

To fix the specific issue mentioned - the profile stuff seems to have
stopped being installed when the iocaml server became available.  It's
still in the iocaml repository though, so you might still be able to
getting it working using those files.

https://github.com/andrewray/iocaml/tree/master/profile

I have been thinking for some time now I need to find a few weeks to
properly overhaul iocaml and bring it right up to date with the latest
protocols.  Maybe over the Christmas period....

Cheers,
Andy
```

**Comment by slel** [comment]
It should now be possible to install iocaml-kernel and iocamljs-kernel, see

- their README files
  https://github.com/andrewray/iocaml
  https://github.com/andrewray/iocamljs

- instructions on IOCaml's wiki
  https://github.com/andrewray/iocaml/wiki/jupyter

- recently merged OPAM pull request "Bring iocaml up-to-date"
  https://github.com/ocaml/opam-repository/pull/5317

**Comment by slel** [comment]
Another option would be to use `simple_jucaml`:
https://github.com/KKostya/simple_jucaml

It might be easier since it plugs in to an existing Jupyter server,
while IOCaml uses its own Jupyter server, if I understand correctly.

**Comment by slel** [comment]
A new Jupyter kernel for OCaml is available as "OCaml Jupyter":
https://akabe.github.io/ocaml-jupyter/
https://github.com/akabe/ocaml-jupyter
Launched in July 2017, licensed under MIT license.

**Comment by slel** [comment]
Docker image for "OCaml Jupyter" was just made available:
https://github.com/akabe/docker-ocaml-jupyter

**Comment by haraldschilly** [comment]
well, the issue here is still that we don't know of a clean way to globally install ocaml libraries. I found https://github.com/ocaml/opam/issues/1950 which is promising, but despite that it is still open and someone claims there is progress, I can't tell what to do.

**Comment by williamstein** [comment]
Also, not much in the way of user requests...

**Comment by DrXyzzy** [comment]
Recently requested by Pascal Ortiz.

**Comment by haraldschilly** [comment]
It's a year since I made my last comment here. Any progress?

**Comment by williamstein** [comment]
wontfix, for now.  If somebody wants to tell us 100% what to do, we'll re-open...

**Comment by slel** [comment]
Here are some notes about installing:

- https://share.cocalc.com/share/43351b07-4480-47fd-a471-59a95015120a/Install-OCaml-Jupyter-in-CoCalc.md?viewer=share

Not sure why no output shows up when evaluating cells; same problem with
Almond, a Scala Jupyter kernel, or with the GAP Jupyter kernel...

**Comment by slel** [comment]
Requested by Matjaž Krnc on the cocalc mailing list:
- https://groups.google.com/d/topic/cocalc/qzgng7c9A4k/discussion

**Comment by slel** [comment]
Possibly related: https://github.com/akabe/ocaml-jupyter/issues/121
