### ISSUE TITLE
devise a method for offline grading

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1758]
the goal of this ticket is to devise a method for grading students in courses offline. for example

1. export a CSV file from SMC, containing the list of students and their IDs of the smc course, with partially columns for grades and comments (ticket #1573 ) ... they're only populated if there are already marks
2. instructors open that file locally, enter marks
3. that csv file is uploaded again and merged with the course state. that step is complicated, because one has to take care to deal with malformatted csv, etc. also, merging an entry when there was added a mark in the meantime should fail explicitly.

it's also not clear if exporting and importing the same file again always works (e.g. utf8 formatting changes to windows formatting and then suddenly the marks or comments seem to be different)

**Comment by williamstein** [comment]
Alternatively (or in addition), support offline work in a docker image, with the patches/changes that the user makes getting merged back into the main project periodically...

**Comment by novoselt** [comment]
I feel that if implemented merge conflicts are inevitable and dealing with them will be a huge pain for an uninitiated. While grading exams on an off-grid backpacking trip may sound exciting, I think the vast majority of CoCalc course users have a reliable network.
