### ISSUE TITLE
track process notes in issues

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1759]
this issue is for time tracking
time: 80 minutes

**Comment by DrXyzzy** [comment]
process: took about 30 minutes to design, 2.5 hours to implement basic tracking code. Queries github for issues updated in past 7 days, then for each issue, comments updated in past 7 days.

**Comment by DrXyzzy** [comment]
process: example of more than one process note per issue

**Comment by novoselt** [comment]
I assume it was part of a project that is no longer in use since I have no idea about it ;-)
