### ISSUE TITLE
if you enable peer grading but don't have enough students you get an uncaught exception

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1785]
1. Make a class with 1 student.
2. enable peer grading and assign
3. See this traceback:
```
Uncaught You need at least 2 students
exports.peer_grading @ misc.coffee?6d3d:1777
CourseActions.update_peer_assignment @ main.cjsx?a29f:826
```

**Comment by williamstein** [comment]
Confirmed to still be a bug.
<img width="1240" alt="screen shot 2017-05-17 at 11 49 08 pm" src="https://cloud.githubusercontent.com/assets/1276278/26189845/78b9239e-3b5b-11e7-8590-faedc65cb0cf.png">

Probably the right fix is to NOT ALLOW enabling peer grading if there are two few students.  So a few lines of code in the peer grading component and this bug is fixed.

**Comment by novoselt** [comment]
Still there!
