### ISSUE TITLE
feature request: be able to copy an existing course to a new folder or project and remove all student info, but keep assignments/handouts

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1826]
This is a "no brainer" feature that we don't have, which people need when teaching a class repeatedly...

**Comment by DrXyzzy** [comment]
Inquiry about this received from Stephen Davies in Aug 2019.

**Comment by williamstein** [comment]
Interestingly, the technique I used for nbgrader to generate the student version of a notebook is very similar to how one would implement this.   That code makes a new ipynb file with the same syncdb as the old one, then makes a bunch of changes, then commits the first version in the new history.

**Comment by johnjeng** [comment]
>That code makes a new ipynb file with the same syncdb as the old one, then makes a bunch of changes, then commits the first version in the new history.

Sounds similar to my preliminary code for this which was make a new course file, open a syncdb and course actions for it, run through `actions.add_assignment` and `actions.add_handout` for all the paths from the original course store.

**Comment by novoselt** [comment]
See #1566
