### ISSUE TITLE
keyboard moves react bootstrap dropdown cursor by *two* instead of one.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1827]
All react-bootstrap menus in SMC currently are broken in the following sense.  If you select one, then use the cursor keys to move up or down, you'll move by *two* steps instead of one each time.  For example:

1. Go the file page, and click the dropdown toggle to the right of the create button.
2. Hit the down arrow on your keyboard twice.

I have no idea whatever why this is happening.

**Comment by williamstein** [comment]
The dropdowns at https://react-bootstrap.github.io/components.html work fine, so it is either a bug in the version of react-bootstrap we have, or some other weird css or other interaction...

**Comment by williamstein** [comment]
For Jupyter completions I just wrote a new menu select thing from scratch, rather than use react bootstrap.  I needed custom behavior anyways, so this is fine.  See the Completions widget here: https://github.com/sagemathinc/smc/commit/07916901faff38dda44df60697a071925b39abf5

**Comment by williamstein** [comment]
And I should add that when using bootstrap in react directly (not through react-bootstrap) the keyboard movement works fine.  It also doesn't wrap around, which is much more standard.

**Comment by williamstein** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/2532

**Comment by williamstein** [comment]
We need to wait for https://github.com/react-bootstrap/react-bootstrap/issues/2532 to be merged...

**Comment by haraldschilly** [comment]
still open

**Comment by williamstein** [comment]
We don't use this library for menus anymore...
