### ISSUE TITLE
make it possible for one user to pay for a subscription for another user

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#183]
More precisely, make it possible for a user to share upgrades they purchase with other users.  This would be similar to adding collaborators on a project, but instead add collaborators on a subscription. Then any of the collaborators would get to allocate from that particular subscription to projects.

**Comment by williamstein** [comment]
Demoting the "high" -- this is important, but rarely requested, and the "admin shared account collaborator" work around seems to be fine for people.

**Comment by williamstein** [comment]
See https://github.com/sagemathinc/smc/issues/123

**Comment by haraldschilly** [comment]
closing this. a license purchased by person A has an ID, which can be passed on to person B.
