### ISSUE TITLE
File Upload Status is Not Persistent

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#1861]
If you upload a "large" file (for some given connection speed) on the files listing page, navigate away, and then navigate back, the upload status area is gone but the upload is still trying to happen.

Change this so that the Dropzone.js object is registered some place so that active uploads may be re-rendered correctly.

**Comment by williamstein** [comment]
Seems ugly due to Dropzone itself having state; may require ugly hide/show instead of proper react dom-level rendering.  Hmmm.

**Comment by williamstein** [comment]
This hasn't come up since, so closing as not a huge important problem. For people really seriously transferring larger amounts of data and wanting good background functionality, they should use an rsync  client along with our good ssh support.
