### ISSUE TITLE
react deprecation warnings

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1862]
after my latest update of all libs, I see the following deprecation warnings:

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Warning: Uncontrolled(Dropdown): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement
```

for `smc-react.coffee`, the dropzone component (?) and maybe something related to bootstrap-react. I don't know what those drop-in libs do. but anyways, we should keep an eye on that.

**Comment by haraldschilly** [comment]
Today, after updating npm packages, I started to get the warning below (it's huge and red, so I thought it's an error first). I don't know what is really causing that, though, and react timeago was updated months ago the last time. Anyways, that's the warning:

```
Warning: Unknown prop `now` on <time> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in time (created by TimeAgo)
    in TimeAgo (created by Misc-TimeAgo)
    in span (created by Tip)
    in Tip (created by Misc-TimeAgo)
    in Misc-TimeAgo (created by ProjectFiles-FileRow)
    in div (created by Col)
    in Col (created by ProjectFiles-FileRow)
    in div (created by Row)
    in Row (created by ProjectFiles-FileRow)
    in ProjectFiles-FileRow (created by ProjectFiles-FileListing)
    ...
```

**Comment by haraldschilly** [comment]
ok, about the above, after reading the code I think I understand. They construct [a <time> html tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) and accidentally included the `now` time as an attribute (they modify and extend the `@props` and pass it down to the element)

**Comment by williamstein** [comment]
This is so old.
