### ISSUE TITLE
notifications on mobile have recently been broken in multiple ways rendering them very, very frustrating. 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1879]
On my iphone 6+:

1. Notifications appear *below* the side menu instead of above 
2. Clicking is now completely broken so they don't work at all anymore -- this is very recent. 

I have no idea what caused this but it greatly impacts me.

**Comment by williamstein** [comment]
This is really weird.   In smc-in-smc mode I cannot replicate this on my phone or desktop browser (in mobile mode).  However, when using the live site I **can** with either my main account or my other test account (that has far fewer projects).  

I think the right fix is to just spend a few hours and make it so notifications have their own page on mobile.  Popups for this on a tiny phone make no sense anyways.     Just make a dedicated page.

**Comment by johnjeng** [comment]
>Just make a dedicated page.

Oh shit, right. Okay.

**Comment by williamstein** [comment]
Yeah!
