### ISSUE TITLE
Peer grading doesn't work with empty Assignments

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#1905]
If you make assignments that are just empty folders peer grading will fail to copy to fellow student projects. When you peer collect this non-existent folder, it returns an error:
>Somebody may have moved the folder that should have contained the assignment...

**Comment by haraldschilly** [comment]
I noticed the same or slightly related. Namely that when there are, e.g. 5 students, and you select to distribute the assignment to two peers, no distribution seems to happen. When trying again it works fine.

**Comment by novoselt** [comment]
Closing as stale, we can open a new issue if there will be demand.
