### ISSUE TITLE
chat status popup on mouseover of `Video Chat` does not appear in firefox

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1913]
From #1911, the popup seen on mouseover of the (n) Video Chat button, with the toggle message and chat occupants, does not appear in firefox.

See also: #1899.

**Comment by DrXyzzy** [comment]
Note that while appear.in video chat is not supported by Safari, the mouse-over status on the Video Chat button works.

**Comment by williamstein** [comment]
Is this a general tooltip problem with firefox -- e.g., what about in courses?

**Comment by DrXyzzy** [comment]
Tooltips show up in Firefox in a .course: Students, Assignments, Handouts, Settings, Shared Project all show tooltips; also, the buttons in the Files and Projects button bars show tooltips. 

Incidentally, tooltips pop up noticeably faster over the Files and Projects bars than over the .course buttons. That difference in latency is also visible with Google Chrome.

**Comment by williamstein** [comment]
> Incidentally, tooltips pop up noticeably faster

This is intentional; check out the source code.  The idea is that if you know what you're doing, then you don't want to see the tips all the time.  This may be bad design though.

**Comment by DrXyzzy** [comment]
Closing this bug in view of #2049 - wontfix
