### ISSUE TITLE
Support Plotly mimetype

### ISSUE THREAD

**Issue by rgbkrk** [sagemathinc/cocalc#1915]
Plotly exports a plotly mimetype 

If you want a react component that accepts the raw Plotly data, feel free to use [`@nteract/transform-plotly`](https://github.com/nteract/nteract/tree/master/packages/transform-plotly).

```js
import PlotlyTransform from '@nteract/transform-plotly'

...
<PlotlyTransform data={data} />
```

**Comment by williamstein** [comment]
NICE -- thanks!

**Comment by rgbkrk** [comment]
Whoop, forgot to note the mimetype here: `application/vnd.plotly.v1+json`

**Comment by williamstein** [comment]
Exactly what can I input in a cell (and for which kernel) to test this? 

I tried non-offline plotly examples from their website (with an account) and they just work as is via test/html.  

I tried offline as follows: 

    import plotly; from plotly.graph_objs import Scatter, Layout; data = [Scatter(x=[1, 2, 3, 4], y=[4, 3, 2, 1])]; layout = Layout(title="hello world"); z = {"data": data, "layout": layout}; plotly.offline.init_notebook_mode(connected=True); plotly.offline.iplot(z)

and that tries to use require and fails.

As far as I can tell, I'm not seeing any `application/vnd.plotly.v1+json` mimetype messages... coming back from "the" kernel that I happened to be using.

**Comment by rgbkrk** [comment]
When we were running the new realtime setup yesterday I used `iplot`, which should be outputting the plotly mimetype. It comes from here: https://github.com/plotly/plotly.py/blob/2be151ee02bca126e3d6af6d30f447ae2aa7e062/plotly/offline/offline.py#L362

That's been active [since the 2.0.1 release of Plotly](https://github.com/plotly/plotly.py/blob/38e20fb54ffe12c54921f644223c7b991f71183d/CHANGELOG.md#201---2017-02-07).

**Comment by rgbkrk** [comment]
I just noticed something weird with how they're sending several outputs for what should be one payload.

```
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/vnd.plotly.v1+html": [
              "<script>requirejs.config({paths: { 'plotly': ['https://cdn.plot.ly/plotly-latest.min']},});if(!window.Plotly) {{require(['plotly'],function(plotly) {window.Plotly=plotly;});}}</script>"
            ],
            "text/html": [
              "<script>requirejs.config({paths: { 'plotly': ['https://cdn.plot.ly/plotly-latest.min']},});if(!window.Plotly) {{require(['plotly'],function(plotly) {window.Plotly=plotly;});}}</script>"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/vnd.plotly.v1+html": [
              "<div id=\"4a443c63-7ccb-439e-af1b-211f78fb8a0d\" style=\"height: 525px; width: 100%;\" class=\"plotly-graph-div\"></div><script type=\"text/javascript\">require([\"plotly\"], function(Plotly) { window.PLOTLYENV=window.PLOTLYENV || {};window.PLOTLYENV.BASE_URL=\"https://plot.ly\";Plotly.newPlot(\"4a443c63-7ccb-439e-af1b-211f78fb8a0d\", [{\"y\": [4, 3, 2, 1], \"x\": [1, 2, 3, 4], \"type\": \"scatter\"}], {\"title\": \"hello world\"}, {\"linkText\": \"Export to plot.ly\", \"showLink\": true})});</script>"
            ],
            "text/html": [
              "<div id=\"4a443c63-7ccb-439e-af1b-211f78fb8a0d\" style=\"height: 525px; width: 100%;\" class=\"plotly-graph-div\"></div><script type=\"text/javascript\">require([\"plotly\"], function(Plotly) { window.PLOTLYENV=window.PLOTLYENV || {};window.PLOTLYENV.BASE_URL=\"https://plot.ly\";Plotly.newPlot(\"4a443c63-7ccb-439e-af1b-211f78fb8a0d\", [{\"y\": [4, 3, 2, 1], \"x\": [1, 2, 3, 4], \"type\": \"scatter\"}], {\"title\": \"hello world\"}, {\"linkText\": \"Export to plot.ly\", \"showLink\": true})});</script>"
            ],
            "application/vnd.plotly.v1+json": {
              "data": [
                {
                  "y": [
                    4,
                    3,
```

**Comment by rgbkrk** [comment]
Oh wait, never mind. The first output was from init_notebook_mode.

**Comment by williamstein** [comment]
It's 5 years later, and I'm no longer convinced this is better or even a good idea.  Whatever they do with straight html seems to work really well, to be honest, at least for my use cases.

**Comment by rgbkrk** [comment]
That's probably the one they test the most and get the most feedback about anyhow.
