### ISSUE TITLE
create an "exam proctoring mode"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1919]
In the “exam proctor mode”, you can lock SMC into only one worksheet that can be opened.  

This is to focus the students and also to avoid cheating on exams, e.g., where the student just opens up their old files and copy code in. 

Requested by instructors regularly.

**Comment by johnjeng** [comment]
My thoughts:
1. It should be "optional" to the student in the sense that they must opt in by opening a file or directory.
2. The student needs to be warned that they will be locked out.
2. They should be able to navigate away officially but with a warning like "This will immediately conclude this exam and you will not be able to do any more work on it. Are you sure?"
3. Sets a flag on the account so any other open tabs will also "lock down"

Proposal 1: Create a file extension `.exam` or something similar and create an editor for it which does some wrapping of the usual file extension. Files would look like `quiz1.sagews.exam`. 

Proposal 2: Put some meta data in a distributed directory to let the client know that it's a exam, to warn the student before opening, and then lock down access to anything outside that directory for the duration of the exam.

Proposal 1 seems super clean to me but Proposal 2 seems more general and matches how Assignments and Handouts work.

**Comment by williamstein** [comment]
This will also require either:
(1) a fundamentally new addition to our security and collaboration model, or 
(2) creating a new project just for this exam and temporarily **removing the students** from their project for the course. 

I think (1) is basically impossibly hard -- the security problems are likely insurmountable.  So (2) has to be the way to go, and will be easier after the k8s rewrite (when ephemeral projects will be easier to implement).

**Comment by johnjeng** [comment]
>For genuine security

I'm confused what you mean by this. I think locking them out of certain things via the client should be sufficient..

**Comment by williamstein** [comment]
> I'm confused what you mean by this.

If you can execute code in a worksheet than you have 100% full read/write access to absolutely anything in that project.     There is no possible way to restrict that.  It's the underlying OS security model.

**Comment by johnjeng** [comment]
Oh, you mean they could do something like parse old homework from within the exam worksheet?

**Comment by williamstein** [comment]
Yes.

**Comment by gabindu** [comment]
Are there any updates on this issue? This seems even more relevant these days, and I could & would certainly use this.

**Comment by williamstein** [comment]
> Are there any updates on this issue? 

Unfortunately, there has been no further work on this issue.

**Comment by novoselt** [comment]
#7110 is a fresh follow up with some proposals.
