### ISSUE TITLE
implement jupyter extension – functionality similar to (and 100% compatible with) nbgrader

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1929]
E.g., toolbars, etc.

See http://nbgrader.readthedocs.io/en/stable/
<img width="1090" alt="autograder_tests" src="https://cloud.githubusercontent.com/assets/1276278/25775892/cdf6a886-3264-11e7-885d-85e2d18a1265.png">

Once implemented, contact those who asked us about "nbgrader", e.g. Mehmet Ergezer.

**Comment by kedlaya** [comment]
I second this feature request!

**Comment by philip-sterne** [comment]
I third this feature request!

**Comment by williamstein** [comment]
@maarksman

**Comment by haraldschilly** [comment]
depends on #2641, in particular because nbgrader saves metadata for `editable` and `deletable` for self assessment validation of results:

```
{
  "editable": false,
  "deletable": false,
  "nbgrader": {
    "locked": true,
    "solution": false,
    "grade_id": "2",
    "points": 2,
    "schema_version": 1,
    "checksum": "248bf00d39fcbc8d2863047199e8293c",
    "grade": true
  },
  "trusted": false
}
```

**Comment by profbrady** [comment]
I would like this feature as well.

**Comment by DataScienceUWL** [comment]
I really would like to use nbgrader and would be happy to host our data science courses through cocalc if it incorporated nbgrader.  Without that capability I don't see any advantage to using cocalc over free colab or azure.

**Comment by williamstein** [comment]
@DataScienceUWL -- thanks for your comment.  I just increased the priority of this issue.  I'm personally prioritizing most of my cocalc dev time to cocalc-jupyter improvements now.   I need to finish full collaborative ipywidgets support first, and after that will turn to these other issues.
