### ISSUE TITLE
printing markdown file to pdf doesn't include images

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1965]
Another way to replicate:
1. Make an md file
2. Put `<img src='a.png' width=800>` in it.
3. Try to print: don't see any image.

<img width="1201" alt="screen shot 2017-05-18 at 12 01 33 am" src="https://cloud.githubusercontent.com/assets/1276278/26190233/338c8836-3b5d-11e7-8d2c-15c68af8f525.png">

**Comment by DrXyzzy** [comment]
### Choices

What is the preferred course of action? Here are some choices. Explanation follows.

1. Leave code as is and add an FAQ entry telling users to use pandoc-style image links in markdown.
1. Add a wrapper script (around pandoc) to the md editor print function, to detect `img` elements and if found, display a warning suggesting switch to pandoc links.
1. Add wrapper script as below if img is detected, converting first to html and then to pdf.

### Background
Pandoc expects image links like this, which prints to pdf correctly:
```
# test

heh -- ![a](a.png "sin curve")
```

A workaround for printing md with img elements to pdf from the CC md editor would be to use a wrapper script around pandoc. When the print icon is clicked, look for an `img` element in the .md and if present, do the following:
```
pandoc -t html filename.md | pandoc -f html -o filename.pdf
```

Reference: [Pandoc Markdown to PDF doesn't show images](https://tex.stackexchange.com/questions/253262/pandoc-markdown-to-pdf-doesnt-show-images)

Note: it's possible to set image width in a pandoc-style link, but the CC preview pane does not recognize it. Command line invocation of pandoc does recognize it, e.g. `pandoc -o filename.html filename.md`.
```
# test

heh -- ![a](a.png "sin curve"){width=200}
```

**Comment by williamstein** [comment]
I like 2, and in the warning include that width and height can be set.   I didn’t even know that!

**Comment by DrXyzzy** [comment]
Ok, will work on it. Also opened #2210 to fix the preview.

**Comment by williamstein** [comment]
As of today only the "Lock" view has a print option, and that print only prints via html, and works fine with image links:

<img width="1372" alt="image" src="https://github.com/user-attachments/assets/0eefea17-00fe-472a-b1cf-1631b7fe2fd4">
