### ISSUE TITLE
two edge cases for formulas in markdown

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1966]
```
\(x^3\)

\[x^5\]

$1
and $2
```

* the first two formulas use the default mathjax delimiters, they should work but don't.
* the second case wasn't rendering the formula `1 and` before ca1b4bab5aaa5925b7c15b5896d65b793d2c3c10 ... the heuristic was to only process formulas per line if they're between an even number of dollar signs.

**Comment by williamstein** [comment]
>  the heuristic was to only process formulas per line if they're between an even number of dollar signs.

I think we should forget about that heuristic.  It conflicts with what Jupyter and latex itself do.

Regarding the first two, I can't think of any reason for this behavior -- it seems very wrong.  (It is of course 100% consistent with Jupyter now.)  There sure are a lot of [tangentially related Jupyter issues, by the way](https://github.com/jupyter/notebook/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20mathjax%20%5C)...

**Comment by haraldschilly** [comment]
closing this. the  first two with the default syntax work as expected and the one with a linebreak is IMHO not ok, but well, consistent with jupyter.
