### ISSUE TITLE
fix remaining mentions of SageMathCloud or cloud.sagemath.com in smc repo

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1973]
`git grep 'cloud.sagemath.com'` in smc main repo, master branch, shows 14 remaining matches.

**Comment by haraldschilly** [comment]
just heads up, whoever goes through them don't change them blindly. e.g. `src/smc-webapp/misc_page.coffee:130` is legit. many of the others are comments.

**Comment by haraldschilly** [comment]
I've broadened the title to also look for the name itself, or abbreviations like "SMC". What we shouldn't touch here are the directory paths and filenames. Some of them have a lot of dependencies and need deeper investigation.

**Comment by haraldschilly** [comment]
What's also part of this and still not 100%, is the wiki: https://github.com/sagemathinc/smc.wiki.git

**Comment by rgbkrk** [comment]
😄

**Comment by haraldschilly** [comment]
I just pushed many more renamings to the wiki and well, the main repository contains some legit uses and all the other ones are in comments or dead code. So, I think we can close this, @DrXyzzy . my suggestions is to rather focus on more visible renaming tasks like the "cocalc tutorial" ...
