### ISSUE TITLE
CORS policy font bug

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1974]
> "Access to Font at 'https://static.cocalc.com/7Wz977wrvKaGNOETv6Fonwfway2ooTOws.cacheme.ttf' from origin 'https://cocalc.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cocalc.com' is therefore not allowed access.

<img width="1362" alt="screen shot 2017-05-21 at 7 23 25 pm" src="https://cloud.githubusercontent.com/assets/1276278/26290261/2002d81e-3e5b-11e7-8f2f-a28ad14ca5f8.png">

**Comment by haraldschilly** [comment]
I might have fixed it, but however, the most important lesson for me is how to actually see this properly. With curl, do this:

```
$ curl -k -I -H "Origin: https://cocalc.com" https://static.cocalc.com/7Wz977wrvKaGNOETv6Fonwfway2ooTOws.cacheme.ttf
HTTP/1.1 200 OK
Date: Thu, 25 May 2017 16:20:33 GMT
Content-Type: application/font-sfnt
[...]
Access-Control-Allow-Origin: https://cocalc.com
Access-Control-Expose-Headers: Content-Length, Content-Type, Date, Server, ...
```

I mean, there is now a `Access-Control-Allow-Origin` header, and it is set to the origin! Hence, at least this here contradicts the error from above. 

A second, nearby but technically unrelated issue relates to webpack. It creates small files to download the font via a script in a `*.ttf` file. Why? no idea. Commit 28d6c961133e7ca15d251ff563d86da95c40fa28 changes the config to use the url-loader, which ironically creates the *.ttf files properly without that intermediate level. (proper solution is likely webpack 2 and updating all those loaders to their latest stable version)

**Comment by haraldschilly** [comment]
Closing this, it's a culmination of several subtle details and apparently, any font file is treated like a potential security problem. I assume they are somehow used as attack vectors. Anyways, adjusting webpack and widening those CORS policies fixed it.
