### ISSUE TITLE
unable to search for strings containing "i", "j", "k" when editing .tasks file in vim mode

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1986]
1. In account prefs, choose `Editor keyboard bindings Vim`.
1. Open a .tasks file and create a task with some text including the word 'the'.
1. Enter vi search mode by hitting ESC and search for string 'the' by typing '/the'. All occurrences of 'the' are highlighted.
1. Clear search by hitting ESC again.
1. Try searching for 'project' by typing '/project'. The j is not echoed. Occurrences of 'proect' will be matched. Same thing happens if you search for 'prokect', the 'k is ignored.
1. Typing 'i' in the search string resets the search.
1. Note also that the search line obscures the bottom line of the task.

**Comment by williamstein** [comment]
Fixed in tasks react rewrite.
