### ISSUE TITLE
document the API

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1987]

**Comment by haraldschilly** [comment]
@DrXyzzy is this done? If so, please close it. (I just closed the last remaining issue about the introduction)

**Comment by DrXyzzy** [comment]
@haraldschilly,  Last part of API doc (& test) is waiting on #2185. Will you please have a look at that?

**Comment by DrXyzzy** [comment]
Done after merge & release of multiple PRs, latest being #2185. Will open new issues for edge cases and stripe API calls.
