### ISSUE TITLE
'Showing only public files" appears twice

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1989]
1. Open incognito/private tab on a project with no published files. The "Showing only public files" message appears twice. Happens whether there is a path appended to the link (shown below) or not.

<img width="622" alt="double-warning" src="https://cloud.githubusercontent.com/assets/528072/26340362/9070cea0-3f53-11e7-8c4b-b3515cb8386e.png">

**Comment by williamstein** [comment]
time: 8 minutes
