### ISSUE TITLE
webapp: drag&drop editor tab is all blue while dragged

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1991]
certainly some css style defs wrong after cocalc switch

**Comment by williamstein** [comment]
Can you post a screenshot?  I don't know what this is.

**Comment by haraldschilly** [comment]
weird, now it's all fine. I'll keep it open, maybe it's actually triggered by some "active" or "focused" mixup.

**Comment by haraldschilly** [comment]
ok, it's when it's not active, apparently. see screencast: https://cocalc.com/projects/14eed217-2d3c-4975-a381-b69edcb40e0e/files/scratch/cc-issue-blue-tab.webm

**Comment by haraldschilly** [comment]
today it's different: text is black, not white. Still, I'm closing it.

**Comment by williamstein** [comment]
Yep, I made this change as part of my flurry of iPad fixes...
