### ISSUE TITLE
Cannot change kernel under jupyter

### ISSUE THREAD

**Issue by bielcardona** [sagemathinc/cocalc#2000]
I have just installed cocalc locally via a docker container. After a fresh install, and launch of the docker, I created a project and a jupyter file inside it. The "change kernel" option is greyed out and I cannot switch to sagemath kernel (for instance).

![screen shot 2017-05-25 at 10 51 56](https://cloud.githubusercontent.com/assets/1281837/26443350/43eeb2c2-4138-11e7-8f62-2eab2e5283a3.png)

**Comment by williamstein** [comment]
I can't reproduce this wth my Docker instance.  Does it work if you wait a little longer, or restart your project?

**Comment by williamstein** [comment]
This is what it should look like

<img width="644" alt="screen shot 2017-05-25 at 7 34 27 am" src="https://cloud.githubusercontent.com/assets/1276278/26454733/cdb19978-411c-11e7-8504-c3a75ba38899.png">

**Comment by bielcardona** [comment]
I installed it on 3 different machines. The first one I installed (saturday, under os x sierra) works as expected. The other 2 ones I installed (today, one on Sierra and one on El Capitan) do not let me change the kernel. Maybe some problem with versions?

**Comment by williamstein** [comment]
I can't replicate this, so there's no possibility for me to fix this unfortunately.

**Comment by williamstein** [comment]
Re-opening since I was just able to replicate this.  I suspect it must be some sort of race condition

**Comment by williamstein** [comment]
The root problem -- you can't set a secure cookie over http.  So first, all of these problems are solved if you use https://localhost instead of http.

**Comment by williamstein** [comment]
I've significantly updated the README instructions to reflect that one must use a secure connection.

**Comment by bielcardona** [comment]
Thanks!
Maybe it could be configured so that no unsecure connection is allowed?

**Comment by williamstein** [comment]
> Maybe it could be configured so that no unsecure connection is allowed?

I updated the README instructions at https://github.com/sagemathinc/cocalc/blob/master/src/dev/docker/README.md so that running them would not allow an insecure connection.
