### ISSUE TITLE
API call `create_account` succeeds, but returns gateway timeout

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2005]
1. Issue API call to create an account.
    ```
    curl -u sk_....: -d first_name=John -d last_name=Doe \
      -d email_address=jd@test... -d password=....... -d agreed_to_terms=true \
      https://cocalc.com/api/v1/create_account
    ```

1. Response is an html page with the following info:
> Error 504 Ray ID: ... • ... UTC
> **Gateway time-out**
> You
> **Browser**
> Working
> Chicago
> **Cloudflare**
> Working
> cocalc.com
> **Host**
> Error
> **What happened?**
> The web server reported a gateway time-out error.
> 
> **What can I do?**
> Please try again in a few minutes.

In each case, the account is created, but the response from the API (including the new account id) is not received. It is possible to log into the new account. Trying the same command again elicits an error of `This e-mail address is already taken`. Other API calls such as `query` complete normally.

The error code of 504 is reported in the body of the response as well as in the HTTP/1.1 status code.

**Comment by williamstein** [comment]
time: 45 minutes
