### ISSUE TITLE
API create_account call may omit first_name and last_name

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2006]
Options `first_name` and `last_name` for API call `create_account` are listed as required in the API definition file [message.coffee](https://github.com/sagemathinc/cocalc/blob/master/src/smc-util/message.coffee), but an account will be created, with blank first and last name, if these options are omitted in an otherwise valid request. Account is not created if any of the other required opts is omitted.

**Comment by williamstein** [comment]
time: 20 minutes
