### ISSUE TITLE
major jupyter bridge issue with sage-7.6 kernel

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2019]
Observe:

<img width="617" alt="screen shot 2017-05-30 at 6 28 32 am" src="https://cloud.githubusercontent.com/assets/1276278/26585524/3bce91bc-4501-11e7-8675-1102fc69f9ea.png">

**Comment by williamstein** [comment]
If this is just a problem for sage kernels, one quick valid fix is to throw an exception for anything sage- jupyter kernels, and point the user at a wiki page about how to set ~/bin/sage to change the sage version for their project.

**Comment by haraldschilly** [comment]
imho, that's related to the kernel.json files. last time I saw that, the pythonpath (and other variables) were wrong. that's why I did set them explicitly.

**Comment by williamstein** [comment]
> that's why I did set them explicitly.

But that's sort of doomed.  Running one version of Sage from within another version is just asking for horrible troubles, due to all the LD_LIBRARY and other stuff...

**Comment by williamstein** [comment]
time: 22 minutes... since I kept messing up that kernel listing command.  It's really surprising it returns a string rather than a list of kernel names...
