### ISSUE TITLE
extend misc.defaults to support react types style type checking

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2020]
Support doing, e.g.,
```
opts = types opt,
    x : rtypes.number  # type checking -- ensures that if x is given it is a number
    y : rtypes.object.isRequired
    z : rtypes.immutable.Map.isRequired
```

This will just be purely runtime type checking.  This is not switching to TypeScript or using Flow.  This means that it will be possible to at least write code knowing it runs under sane assumption or very clearly blows up.

**Comment by williamstein** [comment]
It's presumably easy to get around "the default value is a function" problem by adding an attribute to each type object....

**Comment by williamstein** [comment]
@johnjeng

**Comment by williamstein** [comment]
Use https://github.com/facebook/prop-types and https://github.com/facebook/prop-types#proptypescheckproptypes

**Comment by johnjeng** [comment]
https://github.com/sagemathinc/cocalc/commit/da146de3b5832d79a8c0e56f8791b70c473edd66

Unsure how to go about testing this yet.
