### ISSUE TITLE
output indentation style problem

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2021]
<img width="483" alt="screen shot 2017-05-30 at 10 07 51 am" src="https://cloud.githubusercontent.com/assets/1276278/26595343/ea5b7d1c-451f-11e7-9b84-1f919a972620.png">

**Comment by williamstein** [comment]
Fixed by https://github.com/sagemathinc/cocalc/pull/2139

**Comment by haraldschilly** [comment]
side effect of fix: #2194

**Comment by haraldschilly** [comment]
I've reverted this and well, since code like

```
print("""abc
xxx""")
```

has no additional spaces before the "abc", hence this issue here must sit on a deeper level.

**Comment by haraldschilly** [comment]
and well, the example above isn't reproducible. I found one, though:

```
J0(33).decomposition(simple=False)
```

**Comment by bryantpq** [comment]
I didn't consider that some libraries might need the formatting. Thanks for catching that!
