### ISSUE TITLE
make https://embed.cocalc.com/ default to full screen mode

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2028]

**Comment by haraldschilly** [comment]
Besides the PR, I thought about this, and I still don't understand why there is a secondary subdomain. I am kind of against hardcoding any domain handling. I would rather suggest that "embedding" CoCalc means to point to `/app?fullscreen`.

**Comment by williamstein** [comment]
>  I still don't understand why there is a secondary subdomain.

I'm happy to eliminate it!

**Comment by williamstein** [comment]
Closing this in favor of @haraldschilly's much better ?fullscreen approach.
