### ISSUE TITLE
temporary API auth token generation and usage

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2029]
- [ ] Create a new API call that, given a email address and password, returns a temporary auth token.
- [ ] Make it so appending ?auth=blah to a URL and loading cocalc, switches to being signed in as the user with that auth token, and sets a cookie (with short expire time).

**Comment by haraldschilly** [comment]
Note: #2028 takes care of not only parsing `?auth=...` but also removes it upon further processing (e.g. opening a file)

**Comment by williamstein** [comment]
time: 1 day
