### ISSUE TITLE
implement automated testing of smc-util's opts.types

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2033]
> Unsure how to go about (automated) testing yet.

Here's how: https://github.com/sagemathinc/cocalc/blob/master/src/smc-util/test/types.coffee

**Comment by johnjeng** [comment]
Ah I was mostly wondering *what* we should test. All types found in React PropTypes? Or just a few of those and all of our custom ones?

**Comment by williamstein** [comment]
> I was mostly wondering what we should test.

Well I think *how* was also a fun challenge, since this library only works via the side effect of console.log...

>  All types found in React PropTypes? Or just a few of those and all of our custom ones?

Just a few, and definitely all of our custom ones.
