### ISSUE TITLE
webapp: dropzone 256mb limit

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2037]
see FAQ: https://github.com/enyo/dropzone/wiki/FAQ#why-are-large-files-not-uploading pointing out the `maxFilesize` parameter.

should this be raised?

**Comment by williamstein** [comment]
Sure, it should be raised.  I googled a little, which suggests that express doesn't have a limit now.  The recipient of the upload is "the raw express.js server" running in the project, so if it has no limit then we can eliminate the dropzone limit.  If it does have a limit, we should either raise it or match it.

**Comment by johnjeng** [comment]
Yeah, this can be raised. Should be very easy on the front end.

**Comment by johnjeng** [comment]
I'm guessing that people were running into this? I increased the limit. https://github.com/sagemathinc/cocalc/commit/47fbe22a83304a19a0d123bbda07c532f9da36a6

It could match a size limit somewhere else in the future.
