### ISSUE TITLE
easy enhancement -- add ?fullscreen to the end of the "share public" link

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2041]
Then the recipient sees something nice like this:

<img width="1003" alt="screen shot 2017-06-02 at 11 04 53 pm" src="https://cloud.githubusercontent.com/assets/1276278/26751175/ed50cdb8-47e7-11e7-9567-5e95ad0cf027.png">

I do wonder though if in that case we should make the fullscreen button even clearer?  I don't know.

**Comment by haraldschilly** [comment]
short answer: definitely yes. how? not sure. my first thought is it make its appearance depends on the login state:
* logged out: write there "exit fullscreen [icon]" in a faint way and make it darker and more visible when mouse cursor is close by
* logged in: that assumes it is in full screen on purpose, don't highlight it like described above ...

**Comment by haraldschilly** [comment]
Just tested this. Basically it can be closed, but when I'm signed in there is a stupid `padding-top: 5px;` for the `div.container-content`

**Comment by haraldschilly** [comment]
ahh, I misread it, thought it is about fullscreen. Ok, I still don't know if this is a good idea or how to do it properly.

**Comment by williamstein** [comment]
> I still don't know if this is a good idea

It's not.
