### ISSUE TITLE
webapp: guide users for sign in vs. sign up

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2051]
Some time ago, there was a ticket for the landing page about how to visually clarify sign up vs. sign in. After the cocalc switch, there is now a `has_remember_me` cookie, which can be used to distinguish between a known user and a new one.

Right now, there was a time based switch for checking this, which I almost forgot. I disabled it in f3c68c8 and hence this ticket is about figuring out if we want to do something like that, and if so, how exactly.

**Comment by williamstein** [comment]
Ping...

**Comment by williamstein** [comment]
I'm closing this.  Let's just provide a consistent predictable piece of software, instead of playing games like this.
