### ISSUE TITLE
API message `create_project` allows empty title and description

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2056]
Options `title` and `description` are listed as required in [src/smc-util/message.coffee](https://github.com/sagemathinc/cocalc/blob/master/src/smc-util/message.coffee), but may be blank or absent from the API request. A new project is still created, with corresponding field(s) empty.

See also: #2006

**Comment by williamstein** [comment]
Solution: change to making the default title and description either ''.  That's fine by me.  There's no reason to force setting the title/description -- they are there purely for users to know what their project is called, and not used in any other way, and can be easily changed at any time.

**Comment by DrXyzzy** [comment]
Done
