### ISSUE TITLE
sending invitation emails from docker install

### ISSUE THREAD

**Issue by zeigerpuppy** [sagemathinc/cocalc#2063]
With the docker install, I am trying to send invitation emails but they don't send.
I presume this is an issue of having the correct SMTP settings.

However, I am having trouble locating where I should set the outgoing SMTP settings.
I had a bit of a look inside the docker container.

The closest I found to a setting file was `src/smc-hub/email.coffee` but I'm not sure if that's where I should set my email server settings.  I have checked that my LAN email server is visible from the docker container.

**Comment by haraldschilly** [comment]
Emails and sent via sendgrid, that's a third party service. As far as I know, there is no support for SMTP.

**Comment by haraldschilly** [comment]
And yes, you were exactly in the right spot. The line

`email_server = sendgrid(api_key)`

is the key to understand all this. To make this happen, you - or someone else - would have to write a second implementation for sending mails via SMTP (using whatever lib necessary) that fit's into this exported `send_email` function. It would require a bit of refactoring, etc.

Alternatively, you have to setup yourself with sendgrid, make the templates for the emails, and then configure the hub to use your API key.

**Comment by zeigerpuppy** [comment]
thanks for the tips, good to see I was on the right track.  I'm still quite new to node.js but this may be a good opportunity to try to plug in a function.  I'll do a little more digging and, inevitably, ask for help when I get stuck!

Plan so far is to:
1. write an `smtp.coffee` that contains SMTP variables and defines the `sendsmtp()` function
2. see if I can plug this into the existing email sending mechanism 
3. once it's working with hardcoded variables, see how to define configuration variables
4. expose these variables to config from the docker container environment vars

**Comment by haraldschilly** [comment]
My plan idea:

1. find a node js library that sends emails via SMTP for you. First one that looks ok to me is: https://nodemailer.com/extras/smtp-connection/ (I haven't used it, but I guess that's a good one)
2. write those email credentials into a file, yes, smtp.coffee sounds good. make it a module, i.e. 
```
exports.smtp_config =
  host: "..."
  port: 433
  ...
```
(at best, match this to the config of that smtp-connection module) and store that file in `~/secrets/...`. You'll find other mentions for "secret" files in the hub, e.g. the api key for sendgrid.
3. Extend the email.coffee file, and you also have to introduce templates where the text is getting filled in, etc.
4. regarding docker, you can build your own image on top of the official one. Write a short "Dockerfile", that basically uses the official image and adds that file to the correct spot (`COPY smtp.coffee /secrets/smtp.coffee` ← something like that)

Do you intend to make this an official contribution to this project? We would certainly be happy about it :-)

**Comment by williamstein** [comment]
All such configuration should go in the database (just like for stripe), not in source code.

**Comment by williamstein** [comment]
> Do you intend to make this an official contribution to this project? We would certainly be happy about it :-)

The AGPL license we use would also likely "strongly encourage" you to contribute your code, which I think you're supposed to have to do if you're serving the Docker image publicly.  In any case, our intentions by choosing AGPL is that we want to get community contributions back.

**Comment by zeigerpuppy** [comment]
very happy to contribute code, this is a great project!

**Comment by zeigerpuppy** [comment]
as a temporary fix, I'm planning on using sendgrid while I try to get SMTP working.  Is there a template for the `/cocalc/src/data/secrets/sendgrid` file?  It's not present in the docker install but would be useful to at least have the fields formatted properly that can then be filled in.  Thanks...

**Comment by haraldschilly** [comment]
That file contains the API key, without a newline or any other extras.
