### ISSUE TITLE
please install python package 'latimes-calculate'

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2074]
This package is used by the LA Times [Python for Data Journalists](https://knightcenter.utexas.edu/blog/00-18396-sign-now-our-new-online-course-data-journalism-python-data-journalists-analyzing-money) free online course.

If it matters, the course uses python 2.7 and I have used the package successfully (user install) on CoCalc with Jupyter kernel `Python 2 (SageMath)`.

**Comment by haraldschilly** [comment]
done
