### ISSUE TITLE
investigate how to run tensorboard

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2079]
This ticket https://github.com/tensorflow/tensorflow/issues/2602 suggests it works, but it just gives "not found". There might be still something missing...

**Comment by haraldschilly** [comment]
some links we were pointed to

> One potential fix
> https://stackoverflow.com/questions/36615004/tensorflow-visualizer-tensorboard-not-working-under-anaconda

> Another fix link
> https://stackoverflow.com/questions/41009732/tensorboard-on-windows-404-error

**Comment by haraldschilly** [comment]
They also split their repo, so the upstream ticket is https://github.com/tensorflow/tensorboard/issues/69

**Comment by haraldschilly** [comment]
another upstream ticket: https://github.com/tensorflow/tensorboard/issues/30

**Comment by williamstein** [comment]
Solved: https://github.com/sagemathinc/cocalc/wiki/TensorBoard

It is now possible to run TensorBoard.
