### ISSUE TITLE
Ipad issue: no way to edit past chat messages in a chatroom since double click is ignored

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2089]
1. Type a message in a chatroom.
2. Try to double click on it (I guess by double tapping finger), and nothing happens.

**Comment by johnjeng** [comment]
I'm thinking the fix is long hold for context menu. This would also be the fix for tool tips.

**Comment by williamstein** [comment]
Give it a shot.  The fix here will either be long hold if it works (good), or a separate button.  E.g., on the top right a checkbox or button labeled "Edit", which when clicked shows an edit button next to each chat, and clicking that button allows for editing.   For example, in github their solution is to have a little pencil icon above each message, which you click on to edit the message - it's not so bad...

**Comment by williamstein** [comment]
Exactly the same problem happens for double click to edit markdown in Jupyter...
