### ISSUE TITLE
Ipad issue: it is difficult to change tabs for the currently opened file

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2090]
1. Open two files.
2. Tab on the tabs to switch between them.  Often nothing happens.

I think what is happening is that the drag-to-reorder for the tabs gets activated, instead of the click to select.   I'm not sure how to fix this, but maybe there is a parameter that influences heuristics.  Alternatively, maybe on ipad we change the tab slightly to make drag and click to select different parts of the tab.

**Comment by williamstein** [comment]
This click-not-working issue is not only for the draggable tabs, but for all tabs in a project and even for the tabs for switching between projects.  Basically you have to double click anything to get something to happen.

**Comment by williamstein** [comment]
Moreover, clicking once is basically like "hover".  It causes the tooltip to appear and just stay there.

**Comment by williamstein** [comment]
I also just managed to get a tab completely **stuck** in the drag state, so now I can't switch to it, can't close it, etc, and it is stuck with that drag style (where the text is not visible).

**Comment by williamstein** [comment]
My guess is that the drag and drop library used for the tabs involves a bunch of JavaScript hacks, which work on desktop browser, but are just broken on touch devices.

**Comment by johnjeng** [comment]
This is likely the drag 'n drop library not mixing well with tooltips. Dragging should be enabled by a long hold on the item and clicked otherwise. This may not be set correctly on the iPad. Tooltips may also try to trigger on a long hold.

**Comment by williamstein** [comment]
Can we just try disabling tooltips first to see what happens... I would be fine with just eliminating them across the board on ipad to see what the effect is.

**Comment by williamstein** [comment]
Fixed by https://github.com/sagemathinc/cocalc/commit/c320bf8d384c5135d95eb5e83965a20573d409a9
