### ISSUE TITLE
preview of .Rmd file creates duplicate .md file

### ISSUE THREAD

**Issue by zeigerpuppy** [sagemathinc/cocalc#2099]
when editing an .Rmd file, cocalc seems to perform an operation that results in the creation of a duplicate .md file with the same filename.

Is there a way to prevent this behaviour?

**Comment by williamstein** [comment]
@haraldschilly @DrXyzzy any comment on this?

**Comment by haraldschilly** [comment]
We have to come up with a proper side-by-side code editor and output display (similar to what we should do with latex, too). I have no idea how the synchronization works, otherwise I would work on this.

**Comment by haraldschilly** [comment]
I'm closing this. Maybe this (from 2017) did refer to an intermediate conversion to markdown? Processing going through rmarkdown's render function now.
