### ISSUE TITLE
chat comments disappear if file is renamed

### ISSUE THREAD

**Issue by zeigerpuppy** [sagemathinc/cocalc#2103]
To replicate:
1. create a file
2. start a chat and add comment
3. close document
4. rename document and reopen
5. the chat will have disappeared
6. renaming the file back to the original restores the chat.

This may be quite confusing to users if comments disappear.  I guess that the chat loading must be coupled to the filename somehow.  Perhaps when a file is created, a unique identifier could be created for a document and the chat linked to that identifier even if the file is moved or renamed.
I guess this would also require some form of persistent metadata at the file level.

Alternatively it may make sense to have a hidden file storing the chat data (eg .filename.chat) which is automatically renamed on a GUI rename function.  This would have the benefit of being relatively transparent when doing git operations too.

**Comment by haraldschilly** [comment]
In "files", when you click the eye to see hidden files, too, there is a chat file for any name `foo`, it's `.foo.sage-chat`. So, I think it's reasonable that when you rename the file in the UI with the rename button, this chat file should also be renamed.

**Comment by johnjeng** [comment]
Closing in favor of #2119 since renaming is fixed.
