### ISSUE TITLE
Ipad - the standby timeout is frequently triggered for no good reason

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2109]
My standby timeout is set to 2 hours.  However, on my ipad the CoCalc website frequently puts my browser in idle standby mode (where the background is grey).

Since ipad already aggressively idles/standbys everything, let's just get rid of the standby timeout entirely on ipad and iPhone (or mobile in general).

**Comment by DrXyzzy** [comment]
I see the annoying connection warning on MacBook Pro with Safari as well.
