### ISSUE TITLE
small bug related to markdown parsing vs. mathjax

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2117]
Recently I saw a small oddity. `\begin{equation}` ... `\end{equation}` in escaped code is still somehow active. It must be related to splitting up the input text for formula processing, although it should be ignored.

test:
```
test `\begin{equation}` bar `\end{equation}` test.
```

![screenshot from 2017-06-16 10-54-33](https://user-images.githubusercontent.com/207405/27219503-346bc9f6-5282-11e7-8108-3c3bd6806fa4.png)

**Comment by haraldschilly** [comment]
Adding upstream. I no longer have any idea how this is processed, but in my local legacy jupyter (jupyter version 4.3.0, notebook version 5.0.0) the same markdown code comes out similarly broken:

![screenshot from 2017-06-16 10-57-50](https://user-images.githubusercontent.com/207405/27219704-f2877796-5282-11e7-9a9b-60855bf50c11.png)

**Comment by mforbes** [comment]
Another small parsing bug is associated with `<x` as in "$<x$" which renders as a "$" in CoCalc's interface, but fine in the classic notebook backend.

**Comment by mforbes** [comment]
Another small issue:

```markdown
Look here:
$$
  x
$$
there is a strange indent on this line.
```

renders as

<img width="235" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1028433/a9b05b1a-6c0a-4759-92da-a33497749423">

Note that the line after the equation has a small indent that should not be there.

**Comment by williamstein** [comment]
this works fine, probably because I totally rewrite our markdown parsing properly.
