### ISSUE TITLE
sagews: typeset_mode distorts behavior of "_"

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2124]
The value of "_" is not set when `typeset_mode(True)`. Example:

```
3+4
sqrt(_)
typeset_mode(True)
3*5
sqrt(_) ← _ is set to sqrt(7), which is the last result before typeset_mode(True)
```

Similar issue: #445

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.

Jupyter handles setting _, I think.
