### ISSUE TITLE
improve jupyter2 handling of read-only files

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2128]
When I open up a ipynb file from  the `~/.snapshots/.../` with the newer jupyter, I can evaluate it and it is recorded in the history. Do we really want to support this?

My expectation is
* The file is only viewable but not editable
* Maybe even some UI to guide me to copying the file to the home directory

**Comment by williamstein** [comment]
> Do we really want to support this?

Definitely not; that's certainly a bug caused by me.  Or rather, I never implemented proper handling of read only for the new jupyter rewrite, evidently.  Woops.

**Comment by williamstein** [comment]
Reopening, since my fix above in fact makes things worse.

**Comment by williamstein** [comment]
This issue is surprisingly difficult due to the distinction between the .ipynb file, which is only used for interoperability, and the the syncdb file which is REALLY used.

**Comment by williamstein** [comment]
Note - things should basically work as expected for browsing jupyter notebooks in snapshots edited in cocalc.  No other case is likely to work properly.

**Comment by williamstein** [comment]
This is definitely still open/broken.

**Comment by williamstein** [comment]
I just checked and the notebook is read only, as expected.
