### ISSUE TITLE
jupyter: support "Update Display Data"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2132]
See http://jupyter-client.readthedocs.io/en/latest/messaging.html#update-display-data

@rgbkrk

**Comment by rgbkrk** [comment]
Example notebook: http://nbviewer.jupyter.org/github/ipython/ipython/blob/6.x/examples/IPython%20Kernel/Updating%20Displays.ipynb

nteract's implementation of this is to keep track of "display paths" where are the key paths to get to an object. Roughly:

```
// The current output
const keypath = ["notebook", "cellMap", cellID, "outputs", outputIndex]

// Get all the keypaths for this display ID, if there are any
const keyPaths = state.getIn(
  ["transient", "keyPathsForDisplays", displayID], new Immutable.List())
  .push(keyPath);

// Update each output which has that display id
const newState = keyPaths
  .reduce(
    (currState: DocumentState, kp: KeyPath) =>
      currState.setIn(kp, immutableOutput),
    state
  )
  .setIn(["transient", "keyPathsForDisplays", displayID], keyPaths);
```

Actual source: https://github.com/nteract/nteract/blob/548fa45734b7655aad711195619d3fd407f06d08/src/notebook/reducers/document.js#L165-L211

**Comment by rgbkrk** [comment]
We have something similar for an `update_display`

**Comment by williamstein** [comment]
Due to our goal for compat with jupyterlab, not having this is a bug.  A good example is at #4574 .

**Comment by williamstein** [comment]
It would be relatively easy to implement this in a stupid and inefficient way by just including them in the underlying syncdoc rather than keeping them ephemeral. In fact, that's what we have been doing for the last decade already... it's just that we don't render them.  

So maybe i'll first implement this by rendering them, then have a follow up ticket about doing something much trickier, which is similar to our ipywidgets sync'd state implementation.
