### ISSUE TITLE
rename the blog

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2134]
1. Got to blog.cocalc.com and get nothing
2. Go to http://blog.sagemath.com/ and get what is our cocalc blog.
3. Notice the title, favicon and logo are still  "**SageMath**Cloud Blog"

**Comment by haraldschilly** [comment]
here is the name change https://github.com/sagemathinc/smi-blog/commit/d60d8343cf77079accfa5005c9042c87461d33aa

**Comment by williamstein** [comment]
Should we make https://blog.cocalc.com redirect to blog.sagemath.com?

**Comment by haraldschilly** [comment]
Well, I don't know. I've made this ticket instead https://github.com/sagemathinc/smi-blog/issues/1 and closing this one here. Changing the url also means to setup GCS, etc.

**Comment by williamstein** [comment]
We don’t have to change the URL; we could just make it redirect?   Maybe it is fine as is, since the company is sagemath.com after all.

**Comment by haraldschilly** [comment]
the blog.cocalc.com link works, too
