### ISSUE TITLE
add "git grep" to project's "find" dialog

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2146]
Add an additional option to project's "Find" dialog for using "git", such that instead of normal `grep` it uses `git grep` or `git grep -i`. 

Make sure it fails nicely when there is no git repository.

**Comment by souravsingh** [comment]
@haraldschilly I am interested in working on the issue. How do I start?

**Comment by haraldschilly** [comment]
@souravsingh you can do dev work right inside cocalc. instructions and some supplemental scripts are here: https://github.com/sagemathinc/cocalc/tree/master/src/dev/project

next step for you would be to find the corresponding code in smc-webapp and well, start working on it in your own fork :-)

before you submit an actual PR, we also need a signed CLA from you.

**Comment by williamstein** [comment]
>  you can do dev work right inside cocalc.

NOTE: It probably requires more RAM/disk than free projects get by default.

**Comment by souravsingh** [comment]
@haraldschilly Where do I sign the CLA for the contribution?

**Comment by haraldschilly** [comment]
@souravsingh please email cla@sagemath.com  and I'll get back to

**Comment by williamstein** [comment]
I really want this!
