### ISSUE TITLE
Add python3 kernel

### ISSUE THREAD

**Issue by tehdehzeh** [sagemathinc/cocalc#2149]
While there seems to be a python3 installed within the docker image, one cannot select a python3 kernel and I also see no straight-forward way to add the kernel myself.
It would be wonderful to have python3 as well, as I would like to import libraries which are not compatible with python2.

**Comment by williamstein** [comment]
closed in favor of https://github.com/sagemathinc/cocalc-docker/issues/8

**Comment by lwintermelon** [comment]
Besides Python3 kernel, what about other kernel, like octave
