### ISSUE TITLE
api: reset project idle time

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2152]
Is there an API endpoint to trigger a reset of the project's idle time?

* If yes, we should document that, useful for SSH users
* If not, this would be something we should implement.

Ref: https://groups.google.com/d/topic/cocalc/_mnStvbciGw/discussion

**Comment by williamstein** [comment]
This doesn't make sense. 

1. If people want a longer timeout they should pay us.
2. If we want active ssh use to reset the idle timeout, then we should implement **that**, not provide an API that users have to use to hack the same behavior.
