### ISSUE TITLE
webapp: sign in → projects listing

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2153]
After signing in, the user should see the projects listing page.

I think I fixed this quite some time ago, at least I know that it was working that way... Maybe it got messed up after introducing that landing page?

Ref: https://groups.google.com/d/topic/cocalc/OXtAM8Rq508/discussion

**Comment by haraldschilly** [comment]
Hmm, I can't confirm this, works fine in dev and prod for me... Some essential information must be missing.

**Comment by williamstein** [comment]
Maybe Aaron has a bookmark or link to the settings page or something and isn’t just visiting cocalc.com?

**Comment by williamstein** [comment]
Closing.
