### ISSUE TITLE
jupyter: implement an integrated RISE-style slideshow mode

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2158]
Requested by: Max Külshammer

> "Would it be possible to have Reveal.js/Jupyter RISE like presentation mode for the new Jupyter Notebooks?

YES -  definitely planned and high on the todo list.

**Comment by williamstein** [comment]
Very interesting relevant discussion here: https://groups.google.com/forum/m/#!topic/jupyter-education/SPHzGIpr3OE

**Comment by williamstein** [comment]
New version of RISE released today, along with a blog post about what they are doing: http://www.damian.oquanta.info/posts/rise-510-is-out.html

**Comment by slel** [comment]
Another new version of RISE today.
http://www.damian.oquanta.info/posts/rise-520-is-out.html

**Comment by williamstein** [comment]
We did do this a while ago.

We also have a full excel-style slideshow editor that supports jupyter cells.
