### ISSUE TITLE
support fallback to codemirror meta dictionary (?)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#216]
See

  https://github.com/codemirror/CodeMirror/blob/master/mode/meta.js

Though note that we don't bundle everything with SMC.  So to do the above, we would maybe want to introduce lazy loading for modes, since modes are big.  Webpack makes this fairly easy...

**Comment by williamstein** [comment]
Also, it would be good to autodetect scripts, e.g., `#!/usr/bin/env python` should use Python node, even though the file has no extension.

**Comment by jasongrout** [comment]
Lazy loading in the codemirror demos: https://codemirror.net/demo/loadmode.html (see also https://github.com/codemirror/CodeMirror/blob/master/addon/mode/loadmode.js).  I also have an implementation using systemjs System.import as well, but implementing the loading logic is pretty straightforward.

**Comment by williamstein** [comment]
Thanks -- we would use webpack lazy loading though, since codemirror in SMC goes through webpack.   See https://webpack.github.io/docs/code-splitting.html

**Comment by jasongrout** [comment]
yep, makes sense.

**Comment by williamstein** [comment]
No clue what this was about...
