### ISSUE TITLE
tabs can get stuck (very low probability, but happens)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2169]
Sometimes (and this is rare) when switching between tabs of open files, one will get STUCK.  At that point, it can’t be selected and it is on top of everything.  Switching projects doesn’t even impact it.  The only solution is refresh your browser.

![img_0175](https://user-images.githubusercontent.com/1276278/27774532-aa2d33b4-5f48-11e7-82ac-1457861c20b3.PNG)
![img_0176](https://user-images.githubusercontent.com/1276278/27774533-aa30c04c-5f48-11e7-8ae5-699f367cd304.PNG)

**Comment by haraldschilly** [comment]
sounds like a dup of #2159 to me

**Comment by williamstein** [comment]
I’m closing this, since I haven’t seen this once in over two weeks of very heavy usage.

**Comment by williamstein** [comment]
Well, just hit this again.

**Comment by williamstein** [comment]
I’m closing #2159 in favor of this, but please look at the traceback there....

**Comment by williamstein** [comment]
This is also less annoying now that we have sessions.

**Comment by williamstein** [comment]
With the react16 + all related upgrades, I have not seen this even once.
