### ISSUE TITLE
Add something signalling that the user is actively viewing the document/project

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#2172]
Add something like a green dot to the viewing chat head. It's nice to know if the person is actively viewing the document or not.

**Comment by williamstein** [comment]
- I asusme this should be done not just for chat but for all docs.
- Implementing it will require adding a whole new data structure to the backend; something that tracks info about the current open tab for each session, which we do not have right now, so marking this hard.

**Comment by williamstein** [comment]
Closing since the face is there exactly when there is active viewing already...
