### ISSUE TITLE
rename docker image to sagemathinc/cocalc

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2174]
Right now, everything points to https://hub.docker.com/r/sagemathinc/sagemathcloud/

but it should be https://hub.docker.com/r/sagemathinc/cocalc/

Also, I think it's wise to delete https://hub.docker.com/r/williamstein/sagemathcloud/ to avoid confusion

**Comment by williamstein** [comment]
Fixed.
