### ISSUE TITLE
sagews: rendering a poset fails

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2175]
In a SageWS, I think this should work, but fails

```
CT = "E7"
W = WeylGroup(CT)
AS = W.domain()
FW = AS.fundamental_weights()
RP = AS.root_poset(facade=True)
nonparabolic_roots = [x.to_ambient() for x in AS.root_system.root_lattice().positive_roots_nonparabolic(index_set=(1,2,3,4,5,6))]
print(len(nonparabolic_roots))
p0 = RP.subposet(nonparabolic_roots)

# p0.plot() # <- this works!

show(p0)
```

with

```
14
Error in lines 1-1
Traceback (most recent call last):
  File "/projects/sage/sage-7.6/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 995, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/projects/sage/sage-7.6/local/lib/python2.7/site-packages/smc_sagews/sage_salvus.py", line 2649, in show
    s = show0(objs, combine_all=True)
  File "/projects/sage/sage-7.6/local/lib/python2.7/site-packages/smc_sagews/sage_salvus.py", line 2610, in show0
    b = show0(a)
  File "/projects/sage/sage-7.6/local/lib/python2.7/site-packages/smc_sagews/sage_salvus.py", line 2635, in show0
    sage.misc.latex.latex.eval(s)
  File "/projects/sage/sage-7.6/local/lib/python2.7/site-packages/smc_sagews/sage_salvus.py", line 1467, in latex0
    sage.misc.latex.Latex.eval(sage.misc.latex.latex, s, **kwds)
  File "/projects/sage/sage-7.6/local/lib/python2.7/site-packages/sage/misc/latex.py", line 1130, in eval
    os.path.join(orig_base, filename + ".png"))
  File "/projects/sage/sage-7.6/local/lib/python/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/projects/sage/sage-7.6/local/lib/python/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/projects/20e4a191-73ea-4921-80e9-0a5d792fc511/.sage/temp/compute0-us/1132/dir_vSd5c3/tmpvffo_v.png'
```

Ref: ZD-3716

**Comment by vit-tucek** [comment]
It worked this morning and then it stopped for no apparent reason.

**Comment by williamstein** [comment]
Weird.   I tried `open('a.tex','w').write(latex(p0))`, then put some header/footer info in a.tex, and it works fine to show the diagram:

<img width="1274" alt="screen shot 2017-07-04 at 7 05 12 am" src="https://user-images.githubusercontent.com/1276278/27833322-2d8fa360-6087-11e7-84f2-01ebd59cdbb1.png">


 Also %latex in sage worksheets isn't broken.

**Comment by vit-tucek** [comment]
Nope, %latex is broken too! I've just checked and this

> %latex
\begin{tikzpicture}[>=latex,line join=bevel,]
%%
\node (node_14) at (19.0bp,6.5bp) [draw,draw=none] {${{{-}a{ }+{ }1}}$};
  \node (node_9) at (96.0bp,55.5bp) [draw,draw=none] {$2$};
  \node (node_8) at (81.0bp,398.5bp) [draw,draw=none] {$9$};
  \node (node_7) at (53.0bp,104.5bp) [draw,draw=none] {${{{-}a{ }+{ }3}}$};
  \node (node_13) at (81.0bp,300.5bp) [draw,draw=none] {$7$};
  \node (node_5) at (53.0bp,55.5bp) [draw,draw=none] {${{{-}a{ }+{ }2}}$};
  \node (node_4) at (75.0bp,6.5bp) [draw,draw=none] {${{{-}a{ }+{ }1}}$};
  \node (node_3) at (96.0bp,104.5bp) [draw,draw=none] {$3$};
  \node (node_12) at (66.0bp,202.5bp) [draw,draw=none] {$5$};
  \node (node_11) at (81.0bp,251.5bp) [draw,draw=none] {$6$};
  \node (node_2) at (96.0bp,153.5bp) [draw,draw=none] {$4$};
  \node (node_10) at (118.0bp,6.5bp) [draw,draw=none] {$1$};
  \node (node_1) at (81.0bp,349.5bp) [draw,draw=none] {$8$};
  \node (node_6) at (53.0bp,153.5bp) [draw,draw=none] {${{{-}a{ }+{ }4}}$};
  \node (node_0) at (96.0bp,202.5bp) [draw,draw=none] {$5$};
  \draw [black,->] (node_5) ..controls (53.0bp,68.603bp) and (53.0bp,79.062bp)  .. (node_7);
  \draw [black,->] (node_4) ..controls (69.235bp,19.817bp) and (64.107bp,30.772bp)  .. (node_5);
  \draw [black,->] (node_7) ..controls (64.66bp,118.24bp) and (75.615bp,130.22bp)  .. (node_2);
  \draw [black,->] (node_13) ..controls (81.0bp,313.6bp) and (81.0bp,324.06bp)  .. (node_1);
  \draw [black,->] (node_6) ..controls (56.367bp,166.67bp) and (59.306bp,177.3bp)  .. (node_12);
  \draw [black,->] (node_3) ..controls (96.0bp,117.6bp) and (96.0bp,128.06bp)  .. (node_2);
  \draw [black,->] (node_2) ..controls (96.0bp,166.6bp) and (96.0bp,177.06bp)  .. (node_0);
  \draw [black,->] (node_1) ..controls (81.0bp,362.6bp) and (81.0bp,373.06bp)  .. (node_8);
  \draw [black,->] (node_5) ..controls (64.66bp,69.245bp) and (75.615bp,81.219bp)  .. (node_3);
  \draw [black,->] (node_7) ..controls (53.0bp,117.6bp) and (53.0bp,128.06bp)  .. (node_6);
  \draw [black,->] (node_11) ..controls (81.0bp,264.6bp) and (81.0bp,275.06bp)  .. (node_13);
  \draw [black,->] (node_14) ..controls (28.065bp,20.031bp) and (36.355bp,31.491bp)  .. (node_5);
  \draw [black,->] (node_10) ..controls (112.23bp,19.817bp) and (107.11bp,30.772bp)  .. (node_9);
  \draw [black,->] (node_9) ..controls (96.0bp,68.603bp) and (96.0bp,79.062bp)  .. (node_3);
  \draw [black,->] (node_12) ..controls (69.908bp,215.75bp) and (73.351bp,226.53bp)  .. (node_11);
  \draw [black,->] (node_0) ..controls (92.092bp,215.75bp) and (88.649bp,226.53bp)  .. (node_11);
  \draw [black,->] (node_4) ..controls (80.503bp,19.817bp) and (85.398bp,30.772bp)  .. (node_9);
  \draw [black,->] (node_2) ..controls (88.047bp,166.96bp) and (80.84bp,178.25bp)  .. (node_12);
%
\end{tikzpicture}

works fine. Actually, for this poset of noncompact roots with nonnegative scalar product with cetain weight vector even `view(nRP)` works fine.

On the other hand, the bigger poset of all noncompact roots of $E_7$

>%latex
\begin{tikzpicture}[>=latex,line join=bevel,]
%%
\node (node_26) at (233.5bp,851.0bp) [draw,draw=none] {$-\epsilon_{7} + \epsilon_{8}$};
  \node (node_24) at (140.5bp,7.0bp) [draw,draw=none] {$-\epsilon_{5} + \epsilon_{6}$};
  \node (node_25) at (39.5bp,421.0bp) [draw,draw=none] {$\epsilon_{5} + \epsilon_{6}$};
  \node (node_22) at (140.5bp,57.0bp) [draw,draw=none] {$-\epsilon_{4} + \epsilon_{6}$};
  \node (node_23) at (111.5bp,367.0bp) [draw,draw=none] {$\epsilon_{4} + \epsilon_{6}$};
  \node (node_20) at (140.5bp,107.0bp) [draw,draw=none] {$-\epsilon_{3} + \epsilon_{6}$};
  \node (node_21) at (111.5bp,313.0bp) [draw,draw=none] {$\epsilon_{3} + \epsilon_{6}$};
  \node (node_9) at (111.5bp,475.0bp) [draw,draw=none] {$\frac{1}{2}\epsilon_{1} - \frac{1}{2}\epsilon_{2} - \frac{1}{2}\epsilon_{3} - \frac{1}{2}\epsilon_{4} + \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_8) at (233.5bp,799.0bp) [draw,draw=none] {$-\frac{1}{2}\epsilon_{1} + \frac{1}{2}\epsilon_{2} + \frac{1}{2}\epsilon_{3} + \frac{1}{2}\epsilon_{4} + \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_7) at (422.5bp,421.0bp) [draw,draw=none] {$-\frac{1}{2}\epsilon_{1} + \frac{1}{2}\epsilon_{2} + \frac{1}{2}\epsilon_{3} - \frac{1}{2}\epsilon_{4} - \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_6) at (350.5bp,475.0bp) [draw,draw=none] {$-\frac{1}{2}\epsilon_{1} + \frac{1}{2}\epsilon_{2} - \frac{1}{2}\epsilon_{3} + \frac{1}{2}\epsilon_{4} - \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_5) at (111.5bp,529.0bp) [draw,draw=none] {$-\frac{1}{2}\epsilon_{1} + \frac{1}{2}\epsilon_{2} - \frac{1}{2}\epsilon_{3} - \frac{1}{2}\epsilon_{4} + \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_4) at (352.5bp,529.0bp) [draw,draw=none] {$-\frac{1}{2}\epsilon_{1} - \frac{1}{2}\epsilon_{2} + \frac{1}{2}\epsilon_{3} + \frac{1}{2}\epsilon_{4} - \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_3) at (114.5bp,583.0bp) [draw,draw=none] {$-\frac{1}{2}\epsilon_{1} - \frac{1}{2}\epsilon_{2} + \frac{1}{2}\epsilon_{3} - \frac{1}{2}\epsilon_{4} + \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_2) at (114.5bp,637.0bp) [draw,draw=none] {$-\frac{1}{2}\epsilon_{1} - \frac{1}{2}\epsilon_{2} - \frac{1}{2}\epsilon_{3} + \frac{1}{2}\epsilon_{4} + \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_1) at (259.5bp,259.0bp) [draw,draw=none] {$-\frac{1}{2}\epsilon_{1} - \frac{1}{2}\epsilon_{2} - \frac{1}{2}\epsilon_{3} - \frac{1}{2}\epsilon_{4} - \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_0) at (170.5bp,207.0bp) [draw,draw=none] {$-\epsilon_{1} + \epsilon_{6}$};
  \node (node_19) at (111.5bp,259.0bp) [draw,draw=none] {$\epsilon_{2} + \epsilon_{6}$};
  \node (node_18) at (140.5bp,157.0bp) [draw,draw=none] {$-\epsilon_{2} + \epsilon_{6}$};
  \node (node_17) at (111.5bp,207.0bp) [draw,draw=none] {$\epsilon_{1} + \epsilon_{6}$};
  \node (node_16) at (352.5bp,583.0bp) [draw,draw=none] {$\frac{1}{2}\epsilon_{1} + \frac{1}{2}\epsilon_{2} + \frac{1}{2}\epsilon_{3} + \frac{1}{2}\epsilon_{4} - \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_15) at (352.5bp,637.0bp) [draw,draw=none] {$\frac{1}{2}\epsilon_{1} + \frac{1}{2}\epsilon_{2} + \frac{1}{2}\epsilon_{3} - \frac{1}{2}\epsilon_{4} + \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_14) at (233.5bp,691.0bp) [draw,draw=none] {$\frac{1}{2}\epsilon_{1} + \frac{1}{2}\epsilon_{2} - \frac{1}{2}\epsilon_{3} + \frac{1}{2}\epsilon_{4} + \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_13) at (256.5bp,313.0bp) [draw,draw=none] {$\frac{1}{2}\epsilon_{1} + \frac{1}{2}\epsilon_{2} - \frac{1}{2}\epsilon_{3} - \frac{1}{2}\epsilon_{4} - \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_12) at (233.5bp,745.0bp) [draw,draw=none] {$\frac{1}{2}\epsilon_{1} - \frac{1}{2}\epsilon_{2} + \frac{1}{2}\epsilon_{3} + \frac{1}{2}\epsilon_{4} + \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_11) at (256.5bp,367.0bp) [draw,draw=none] {$\frac{1}{2}\epsilon_{1} - \frac{1}{2}\epsilon_{2} + \frac{1}{2}\epsilon_{3} - \frac{1}{2}\epsilon_{4} - \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \node (node_10) at (184.5bp,421.0bp) [draw,draw=none] {$\frac{1}{2}\epsilon_{1} - \frac{1}{2}\epsilon_{2} - \frac{1}{2}\epsilon_{3} + \frac{1}{2}\epsilon_{4} - \frac{1}{2}\epsilon_{5} + \frac{1}{2}\epsilon_{6} - \frac{1}{2}\epsilon_{7} + \frac{1}{2}\epsilon_{8}$};
  \draw [black,->] (node_6) ..controls (351.08bp,490.95bp) and (351.46bp,500.97bp)  .. (node_4);
  \draw [black,->] (node_15) ..controls (314.74bp,654.5bp) and (283.84bp,668.0bp)  .. (node_14);
  \draw [black,->] (node_25) ..controls (58.839bp,435.97bp) and (77.748bp,449.62bp)  .. (node_9);
  \draw [black,->] (node_7) ..controls (400.32bp,438.02bp) and (383.5bp,450.16bp)  .. (node_6);
  \draw [black,->] (node_10) ..controls (161.91bp,438.09bp) and (144.63bp,450.4bp)  .. (node_9);
  \draw [black,->] (node_11) ..controls (234.32bp,384.02bp) and (217.5bp,396.16bp)  .. (node_10);
  \draw [black,->] (node_22) ..controls (140.5bp,70.707bp) and (140.5bp,80.976bp)  .. (node_20);
  \draw [black,->] (node_10) ..controls (238.22bp,438.83bp) and (283.65bp,453.06bp)  .. (node_6);
  \draw [black,->] (node_19) ..controls (151.91bp,274.49bp) and (194.86bp,289.89bp)  .. (node_13);
  \draw [black,->] (node_11) ..controls (310.22bp,384.83bp) and (355.65bp,399.06bp)  .. (node_7);
  \draw [black,->] (node_18) ..controls (148.67bp,171.07bp) and (155.59bp,182.14bp)  .. (node_0);
  \draw [black,->] (node_3) ..controls (114.5bp,598.95bp) and (114.5bp,608.97bp)  .. (node_2);
  \draw [black,->] (node_9) ..controls (111.5bp,490.95bp) and (111.5bp,500.97bp)  .. (node_5);
  \draw [black,->] (node_5) ..controls (112.36bp,544.95bp) and (112.94bp,554.97bp)  .. (node_3);
  \draw [black,->] (node_21) ..controls (151.91bp,328.49bp) and (194.86bp,343.89bp)  .. (node_11);
  \draw [black,->] (node_21) ..controls (111.5bp,327.63bp) and (111.5bp,339.75bp)  .. (node_23);
  \draw [black,->] (node_19) ..controls (111.5bp,273.63bp) and (111.5bp,285.75bp)  .. (node_21);
  \draw [black,->] (node_17) ..controls (111.5bp,220.95bp) and (111.5bp,232.26bp)  .. (node_19);
  \draw [black,->] (node_18) ..controls (132.6bp,171.07bp) and (125.91bp,182.14bp)  .. (node_17);
  \draw [black,->] (node_24) ..controls (140.5bp,20.707bp) and (140.5bp,30.976bp)  .. (node_22);
  \draw [black,->] (node_23) ..controls (91.483bp,382.46bp) and (70.843bp,397.36bp)  .. (node_25);
  \draw [black,->] (node_23) ..controls (131.11bp,381.97bp) and (150.28bp,395.62bp)  .. (node_10);
  \draw [black,->] (node_13) ..controls (256.5bp,328.95bp) and (256.5bp,338.97bp)  .. (node_11);
  \draw [black,->] (node_16) ..controls (352.5bp,598.95bp) and (352.5bp,608.97bp)  .. (node_15);
  \draw [black,->] (node_1) ..controls (258.64bp,274.95bp) and (258.06bp,284.97bp)  .. (node_13);
  \draw [black,->] (node_0) ..controls (154.15bp,221.85bp) and (138.27bp,235.32bp)  .. (node_19);
  \draw [black,->] (node_12) ..controls (233.5bp,760.95bp) and (233.5bp,770.97bp)  .. (node_8);
  \draw [black,->] (node_8) ..controls (233.5bp,815.12bp) and (233.5bp,825.1bp)  .. (node_26);
  \draw [black,->] (node_3) ..controls (192.75bp,601.1bp) and (260.63bp,615.93bp)  .. (node_15);
  \draw [black,->] (node_0) ..controls (194.89bp,221.7bp) and (218.18bp,234.79bp)  .. (node_1);
  \draw [black,->] (node_4) ..controls (274.25bp,547.1bp) and (206.37bp,561.93bp)  .. (node_3);
  \draw [black,->] (node_2) ..controls (152.26bp,654.5bp) and (183.16bp,668.0bp)  .. (node_14);
  \draw [black,->] (node_6) ..controls (271.93bp,493.1bp) and (203.76bp,507.93bp)  .. (node_5);
  \draw [black,->] (node_4) ..controls (352.5bp,544.95bp) and (352.5bp,554.97bp)  .. (node_16);
  \draw [black,->] (node_20) ..controls (140.5bp,120.71bp) and (140.5bp,130.98bp)  .. (node_18);
  \draw [black,->] (node_14) ..controls (233.5bp,706.95bp) and (233.5bp,716.97bp)  .. (node_12);
%
\end{tikzpicture}

gives the error. 
> IOError: [Errno 2] No such file or directory: '/projects/<snip>/.sage/temp/compute2-us/11056/dir_rhlr3d/tmpZqIlQF.png'

TikZ can have quite intense demands on computing power. Maybe there is  insufficient quota on CPU time? Or perhaps some timeout for view & friends that's too short for LaTeX process to finish rendering?

**Comment by haraldschilly** [comment]
Another one:

```
Dom6 = posets.IntegerPartitionsDominanceOrder(6) 
show(Dom6)
```

It gives an error:IOError: [Errno 2] No such file or directory: '/projects/650e9ad1-6815-46e6-84a4-8f4b84e93685/.sage/temp/compute3-us/28553/dir_01nF1O/tmpplz2Ce.png'

while this works:
```
Comp5 = posets.IntegerCompositions(5) 
show(Comp5)
```

**Comment by williamstein** [comment]
Still completely broken after the switch to KuCalc, new images, etc.

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.

**Comment by williamstein** [comment]
Also, this sort of works actually, as of today in my cocalc-docker install:

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/94be18a4-c22d-4751-be80-c87c960bfe01">


but is broken on cocalc.com:

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/439b0860-4d63-4f1f-a487-73a264abbaf3">

With Jupyter it explicitly says in a message to use the plot method:

<img width="1344" alt="image" src="https://github.com/user-attachments/assets/159333bc-e0aa-42f6-81fe-b9fe92731498">

And the plot looks completely different than what I got above.

I'm just going to close this.
