### ISSUE TITLE
API get_support_tickets returns empty list when tickets are present

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2177]
I created two new ZD tickets for my personal account. One is open and the other is pending. I have verified that `account_id` is correct in the ZD agent view of both tickets. Yet the following happens when requesting tickets:
```
curl -u sk_...: -X POST https://cocalc.com/api/v1/get_support_tickets
{"event":"support_tickets","id":"655ab616-ec87-46cf-a829-6c48944fb95a","tickets":[]}
```

**Comment by DrXyzzy** [comment]
Never mind, it is there now. I guess it takes several minutes for the tickets to show up. And `account_id` must be provided in the API call.

**Comment by haraldschilly** [comment]
yes, just to confirm, without the `account_id` you won't get anything. That's the only common identifier across both systems. Said that, I could imagine that the API, as we have it right now, knows the `account_id`  and would be able to automatically insert it ?

**Comment by DrXyzzy** [comment]
@haraldschilly - Yes, it looks as if `account_id` is optional in the message definition, but the account_id custom field in the ZD ticket did not get filled in when I did not provide it explicitly in the test with curl. In contrast, `account_id` is not required by `get_support_tickets`.
