### ISSUE TITLE
this PR completely broke realtime usage stats for users

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2178]
This PR https://github.com/sagemathinc/cocalc/pull/2176 seems to have completely broken realtime stats for users.  Not surprising, as our automated testing showed the same thing.

My suggestion: make the defaults exactly like they were before the PR – hence making the API backward compatible, then change the client code to set use your new options....?
![image](https://user-images.githubusercontent.com/1276278/27876717-dec8e318-616c-11e7-9149-fbd2a6337d1e.jpg)

**Comment by haraldschilly** [comment]
Closing in favor of improving the UI via #2180
