### ISSUE TITLE
make statistics box in about page smarter about handling outdated or missing data

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2180]
If `/stats` isn't updated regularly, or never done at all, the  "r_help" page's `HelpPageUsageSection` might show a never ending loading indicator or throw an error. Goal of the ticket is to improve this, e.g. only show statistics, if there are some available.

Ref: this came up as part of #2178

**Comment by williamstein** [comment]
This is also something we (admins) should be monitoring somehow, and get a notification if it happens.

**Comment by williamstein** [comment]
This could be added to admin.py as another test that triggers an email notification.  The test would be to query the stats endpoint, then confirm the timestamp is within 15m (say).

**Comment by williamstein** [comment]
I’m going to close, since we now have a hub-stats deployment, which is extremely robust.
