### ISSUE TITLE
Exporting Sage Worksheet to PDF does not include tables in markdown cells

### ISSUE THREAD

**Issue by nvcleemp** [sagemathinc/cocalc#2182]
Take the following steps to reproduce:

1. Create a new Sage Worksheet
2. Enter the following text:
```
%md(hide=true)
|Column 1|Column 2|
|--------|--------|
| x      | y      |
```
3. Press Shift+Enter
4. Click the convert to PDF button.

The output of the cell contains the table, but the PDF does not.

**Comment by haraldschilly** [comment]
Well, this one of the rather insurmountable issues when converting html to latex. That's why we recommend the html conversion. I'm inclined to categorize it as "wontfix", unless someone has at least a good idea how to solve this in general.

**Comment by williamstein** [comment]
There is a good way to solve this (=proper formated markdown only) in general.  Pandoc *does* properly handle tables, e.g., it properly handles precisely this  input.  We do not currently use pandoc in our sagews –> pdf pipeline.  However, we could.  That would, I think, mostly likely be the best approach, as pandoc seems to be the best open source tool for converting random things to pdf...

**Comment by williamstein** [comment]
Also, despite the pain, please don’t discount the value of a sagews –> pdf via latex to mathematicians, who find the look of latex and computer modern fonts to be the only thing that looks good (and all else is ugly).

**Comment by williamstein** [comment]
This is supported well in Jupyter.  Labeling this wontfix.
