### ISSUE TITLE
saving the scroll position for chat isn’t working

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2189]
Broken on ipad, Firefox and chrome....

**Comment by DrXyzzy** [comment]
Correction, looks broken on Chrome on MBP, too. I had not refreshed since recent updates to chat on earlier test. After browser refresh, Chrome doesn't restore vertical position, either.

**Comment by johnjeng** [comment]
Fixed with https://github.com/sagemathinc/cocalc/commit/88ae78f80ec70c344eb87b02d3371e0b5f344c1f
