### ISSUE TITLE
Race condition when using "?auth_token" parameter

### ISSUE THREAD

**Issue by brianfields** [sagemathinc/cocalc#2204]
Occasionally, we are seeing a UI glitch when viewing a file in a project when using the authentication method of including an "auth_token" parameter on the URL. Here's a video where you can see the effect: https://s3-us-west-2.amazonaws.com/test-signed-videos/NotPublicRaceCondition.mp4

As you can see, upon initial load, there is a message that the file is not public. Quickly thereafter, the file becomes visible, although the secondary box indicating the error condition lingers for a few seconds longer.

Not critical, as the file does become operational, but it could be a bit confusing to a user.

**Comment by johnjeng** [comment]
Looked into this today. @williamstein 
https://github.com/sagemathinc/cocalc/blob/53b46d85afb14ac9f607410605fc1a8fbd20e413/src/smc-util/client.coffee#L1959
Finishes later with `resp.error == 'not signed in'`

Even though the user has already signed in via auth_token. The project page even gets to render first with the correct group assigned before the callback chain above leads to
https://github.com/sagemathinc/cocalc/blob/53b46d85afb14ac9f607410605fc1a8fbd20e413/src/smc-util/client.coffee#L555
