### ISSUE TITLE
UTF-8 locale is missing in our public Docker image (terminal is awkward for international users not using a US keyboard layout)

### ISSUE THREAD

**Issue by saraedum** [sagemathinc/cocalc#2205]
If you ssh into a cocalc instance, unicode characters are not supported by the shell. The reason for that is that `LANG` and `LC_*` are set to `POSIX`. I am not sure if that was done on purpose.
At least, users should be able to set their locale to something like `en_US.UTF-8`. This is currently not possible even though `/etc/locale.gen` reads
```
en_US.UTF-8 UTF-8
```
To fix this, root needs to run `locale-gen` once. With that, I can tell my ssh to send `LC_*` and `LANG` to the remote server and finally type in my last name on a terminal :)

**Comment by williamstein** [comment]
Clarification: this makes it possible to type non-US **dead-key character sequences** after ssh’ing into the Docker image.  It does NOT make it so this works in the terminal via the browser... at least not for Gonzalo or Samuel using Chrome/Firefox/Opera.  It *did* work for me on my iPad though (weird).

**Comment by williamstein** [comment]
A workaround might be to enable the 1-line mobile input box for all browsers (not just mobile).  This at least would allow users to type anything on the command line...

**Comment by williamstein** [comment]
@slel

**Comment by slel** [comment]
Although related to the present UTF8 issue, the dead-key issue is possibly separate.
I opened #2211.

**Comment by haraldschilly** [comment]
@saraedum do you have experience with installing `locales` and `locales-all`? that's what I am planning for doing with the upcoming compute environments.

**Comment by saraedum** [comment]
No sorry, I don't.

**Comment by haraldschilly** [comment]
I've troubles replicating this issue. How do you ssh into it? what's your environment and your terminal?

Here is my ssh session snippet:

```
~$ env | grep LANG
LANG=en_US.UTF-8
LANGUAGE=en_US:en
~$ env | grep LC
LC_PAPER=de_AT.UTF-8
LC_ADDRESS=de_AT.UTF-8
LC_MONETARY=de_AT.UTF-8
LC_NUMERIC=de_AT.UTF-8
LC_ALL=C.UTF-8
LC_TELEPHONE=de_AT.UTF-8
LC_IDENTIFICATION=de_AT.UTF-8
LC_MEASUREMENT=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_NAME=de_AT.UTF-8
~$ echo "öäüß"
öäüß
~$ echo "êùû2"
êùû2
```

At the bottom ,I even switched to french keyboard layout and was able to type in that `ê` with a dead key (where my german keyboard has the `ü` character)

Locale directory contains 186 subdirectories, maybe one is missing? german and french variants are there:

```
/usr/share/locale$ ls -1 /usr/share/locale | wc -l
186

/usr/share/locale$ ls -d /usr/share/locale/fr*
/usr/share/locale/fr  /usr/share/locale/fr_CA  /usr/share/locale/fr_FR  /usr/share/locale/frp

/usr/share/locale$ hostname
compute8-us
```

**Comment by williamstein** [comment]
> I've troubles replicating this issue

This is only a problem with our Docker image.  I’ve changed the title to better reflect this.

**Comment by slel** [comment]
This is now https://github.com/sagemathinc/cocalc-docker/issues/7
