### ISSUE TITLE
Measuring assignment completion and correctness

### ISSUE THREAD

**Issue by philip-sterne** [sagemathinc/cocalc#2206]
As a professor I often give exercises to students to help them better understand the material, but I don't get a lot of feedback on how much of the exercises get successfully completed.

It would be an amazing feature if CoCalc could add some sort of functionality that helps with this.

I would envision this as a pair of python notebooks.  The first notebook contains the assignment that I give them, while the second notebook contains some test code to determine whether or not the exercise has been successfully completed.  

Once a student is confident in having completed the exercise then they can click a submit button and the second notebook is executed server-side.  If any exceptions are raised then the student has not successfully completed the exercise.  (For a less binary measure the completion could be measured as the number of tests which pass in the second notebook.)

As the professor, I would then be able to see who successfully completed the exercises.

**Comment by haraldschilly** [comment]
Well, this doesn't directly fit into the current model in cocalc, but I understand what you mean and that it is helpful. It is meant as a dual-purpose feedback utility, such that students can self-assess their work, and then after submitting the answer worksheet, you as an instructor can use it to test it, too, and also inspect it in more detail if necessary.

Do you know nbgrader? https://github.com/jupyter/nbgrader

It offers some of these aspects, but diverts with others of your description. We have issue #1929 about this.

**Comment by philip-sterne** [comment]
Thanks for the fast reply @haraldschilly - I was not aware of nbgrader.  If nbgrader can be integrated into CoCalc then that would definitely be good enough for me!

I am subscribing to #1929 and closing this issue.

**Comment by williamstein** [comment]
I consider nbgrader the top-priority extention to re-implement...
