### ISSUE TITLE
jupyter2: inconsistency with tags vs metadata of cells

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2207]
first, do this in legacy jupyter version 5:

1. view → cell toolbars → tags
2. add tag "asdf"
3. view → cell toolbars → edit metadata
4. click on the cells metadata edit button, you'll see:

```
{
  "trusted": true,
  "tags": [
    "asdf"
  ]
}
```

Now, we do the analog steps in jupyter2 on cocalc, but we end up with

```
{
}
```

i.e. tags are gone, but they're still visible in the UI. 

expected: the list of tags is  still there in the metadata and in general this should work as a two way sync, such that editing the metadata and changing the tags, should also reflect on the displayed tags (in legacy jupyter notebook, editing the metadata tags list also changes the displayed tags when switching back to the tags editing toolbar)

**Comment by williamstein** [comment]
This is a change in the semantics that I made on purpose.   I'm addressing this now by clarifying the instructions and button name to emphasize that this is only for editing CUSTOM metadata.
