### ISSUE TITLE
add links to “courses using cocalc” and “how to teach using cocalc” to the cocalc landing page

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2208]
- https://github.com/sagemathinc/cocalc/wiki/Teaching

- https://tutorial.cocalc.com

The “courses using cocalc” page is even very hard to find from just landing at https://github.com/sagemathinc/cocalc/wiki; I couldn’t find.

**Comment by haraldschilly** [comment]
I made some adjustments and added links in c018dbd. I'm closing this. Next up on that front is to flesh out the planned features page.
