### ISSUE TITLE
jupyter2: multiple input(...) per cell can get stuck

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2209]
1. set to python3 kernel
2. run this cell:
```
a = input('a')
b = input('b')
c = input('c')
d = input('d')
print((a, b, c, d))
```
3. type in something in each box. In about 2/3rd of the cases, it does get stuck after the first or second box and keeps there and hangs.

**Comment by haraldschilly** [comment]
I also tried to split this up into several cells, one for each input, and this does also get stuck...

**Comment by williamstein** [comment]
Does it work fine with classical Jupyter?

**Comment by haraldschilly** [comment]
Hmm, I should have checked. Ok, just tested it a couple of times and it works in classical jupyter. 

I also tried to figure out what's going on in the front-end, and my only observation so far is that there is simply no cell output message coming in to display the box. I hope this isn't a bug in spawnteract...

**Comment by williamstein** [comment]
Seems like the fixes was getting the message format right.
