### ISSUE TITLE
implement jupyter extension – table of contents

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2213]

**Comment by mkarakoc** [comment]
Could you allow to install nbextensions (https://github.com/ipython-contrib/jupyter_contrib_nbextensions) just for a user project itself? I tried to install many times but no luck. I do not want to wait the "implementation" process.

**Comment by mkarakoc** [comment]
I have managed to install nbextensions for Plain Jupyter server using the following.
```terminal
pip3 install --user --no-deps jupyter_nbextensions_configurator
pip3 install --user --no-deps jupyter_contrib_core
smc-jupyter restart
jupyter nbextensions_configurator enable --user
```

**Comment by haraldschilly** [comment]
thank you @mkarakoc, I'll check how safe it is to deploy this globally by default

**Comment by VectorPosse** [comment]
I was just looking for this as well. A table of contents would be awesome!

**Comment by williamstein** [comment]
Thanks for the reminder -- I've been doing a LOT of frontend work lately, so doing this one would be a good idea...

**Comment by haraldschilly** [comment]
Here is a link to toc2, which shows a TOC on the left hand side of the cells (I don't like the floating window approach, the second one is the one I mean): https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html#second-demo-save-as-html-with-toc-navigation-menu

![](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/_images/demo21.gif)

**Comment by williamstein** [comment]
There is now a Table of contents frame for CoCalc Jupyter:

![image](https://user-images.githubusercontent.com/1276278/63556243-d8d0b200-c4f8-11e9-918b-a08a97f8a1e3.png)

You can get it by "File --> Table of Contents" or clicking the "Contents" button, or changing any frame to the "Table of Contents" type:

![Screenshot 2019-08-22 at 4 20 18 PM](https://user-images.githubusercontent.com/1276278/63556264-f140cc80-c4f8-11e9-9811-d950704930c9.png)

The first two methods put the contents on the left using 1/3 of the screen.   You can also further split the contents or put it in any other frame, depending on your taste.  In addition, there's zoom buttons to change the font size.

I did not yet implement: section numbering or section folding ("Collapsible headings").

Hide input has been implemented for a while, though only via a menu option in the Edit menu.
