### ISSUE TITLE
latex: word count

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2215]
add a button (or another UI element) to compute the word count of the document. report should show stats for the number of words, lines, formulas, etc.

we also need a utility to actually do this. the first one I found is [texcount](http://app.uio.no/ifi/texcount/download.html) which seems to be still active despite the old school looking webstie. I've no experience, maybe there are better ones out there, ...

**Comment by williamstein** [comment]
There’s no reason to restrict this to LaTeX.

**Comment by haraldschilly** [comment]
this was fixed a long time ago
