### ISSUE TITLE
support embedding content that you make public in a cocalc project

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2218]
Basically something like this for various file types: https://kyso.blog/posts/embed-jupyter-notebooks

**Comment by haraldschilly** [comment]
It shouldn't be hard to match this, given that we already render many filetypes. In detail, there are two aspects we don't offer:

* by default, only rendering the  output notebook of the cells. the idea seems to be to show the results (graphics, plot.js, etc.). Additionally, at the top is a some selector, where code cells can be shown, too.
* at the bottom is some "powered by" footer. i.e. linking to the service and the document

Regarding the URL, it should be straight forward to support appending `?embed` to any URL pointing to a file.

**Comment by williamstein** [comment]
I’m going to close this since we do have kiosk and fullscreen mode, support iframes, and this ticket is way too broad and general.
