### ISSUE TITLE
Scalable user interface to select jupyter kernel

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2224]
As more jupyter kernels become available in CoCalc,
- allow optionally selecting the kernel of a new jupyter notebook by naming it, eg
  - `mynotebook.sage.ipynb` would default to SageMath kernel,
  - `mynotebook.gap.ipynb` would default to GAP kernel,
  - etc.
- redesign the 'Kernels' menu so that
  - a short list of kernels are listed there by default
  - one menu item offers a longer list
  - one can customize the default list in any project
  - said customization is accessible via the Kernels menu
  - five most recent kernels selected or used are at the top

**Comment by haraldschilly** [comment]
Hmm, what do you mean with "one menu item offers a longer list" ? There is no support for 2nd-level menu popouts, and this is also really bad in general. Maybe you mean to have a list of "highlighted" kernels on top, then a delimiter, and then the list of all other kernels?

**Comment by williamstein** [comment]
He means a single menu item that opens a separate modal dialog or page....

**Comment by williamstein** [comment]
@jasongrout any comments about the kernel filename default idea above?

**Comment by williamstein** [comment]
@haraldschilly already did this _**very nicely**_ a few months ago.
