### ISSUE TITLE
persistent sessions

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2229]
I think I finally know how to deal with "browser refresh preserve session" very nicely. 

IDEA: 
- When you load any url at cocalc.com, if there is no `?session=foo` at the end of the url, generate a new session code and append it to the URL.
- If there is `?session=foo`, then check to see if you have `foo` as a saved session; if not start new one with that name.  If so, restore all open projects and tabs in those projects from that session, and also the URL before ?session=foo, with that is as the current live page.

And that's it.   If you share a URL and forgot to remove `?session=foo`, then it'll basically have no effect.  Our explicit share links don't include a session.  If you have a bunch of tabs open in several projects, and refresh your browser, then they get restored exactly as is.  If you bookmark that session, it is restored.  You can easily have multiple distinct sessions.  

The sessions will be stored on the the backend in a synctable, just like everything else we store.  Thus it isn't tied to any particular device.  You can bookmark and work with the same session on your home and work computer. 

Thoughts?  My motivation is my iPAD -- sometimes it crashes or it refreshes the page due to having swapped the page out of RAM.  Basically, there is an assumption in iOS that refreshing a page doesn't change it.  By adding `?session=` I think we solve this problem nicely for me, but others will of course appreciate it. 

Note that we can still easily allow a user to open a tab in a new window, e.g., via some pop-out link, which will just start a new session with one document. 

Obviously, the order of tabs and order of projects should be recorded too.

We should probably expire sessions not used in the last 6 months (or something)...  On the other hand, session state is useful information to analyze too to better serve our users.

**Comment by haraldschilly** [comment]
I've an idea on top of this: we should make the sessions visible in the "project" overview. I.e. there is a button to create a session out of what's currently opened, or when you open cocalc.com without it, that you can click on a session. (maybe, also to delete or rename them, etc.)

**Comment by roed314** [comment]
I like this session idea a lot.  Harald, it sounds like William was suggesting always having a session active, so it doesn't make sense to create a new session out of what's currently open (though copying, moving, deleting, modifying sessions would make sense).

**Comment by haraldschilly** [comment]
@roed314 ok, I didn't fully understand, what I would find a bit ugly is to always have this `?session=...` in the URL. it should be set once when loading cocalc. Then, yes, I understand your point that there is always a session, and such a dialog I mention above would initially name it with some default, e.g. `0` (like tmux starts with "0") and you can rename it, etc.

**Comment by williamstein** [comment]
I implemented this, but client side for now.  I disagree about `?session=...` in the URL being ugly; in fact, it's the only reasonable thing to do as far as I can tell.

**Comment by williamstein** [comment]
opening https://github.com/sagemathinc/cocalc/issues/2256 for persistence to the backend, which is much harder...
