### ISSUE TITLE
prolog jupyter kernel

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2233]
Requested by: Minerva

**Comment by williamstein** [comment]
https://github.com/Calysto/calysto_prolog

**Comment by haraldschilly** [comment]
It's installed, but not working 100%. (and I'm by far not an expert on prolog ...)

* In the new jupyter2, the question mark at the end triggers an autocompletion (resulting in the error: `{"error":"completion failed"}` in a help box opening up at the bottom)
* It does something more useful when switching to the classical one.
* There seem to be no "False" answers? Not sure about their syntax though ... Maybe there is even some implementation issue with the kernel itself.
* Answers always show `Use '%continue' for more results.` and then in the next cell, `%continue` gives another such warning and shows one more ... that's maybe something for upstream, too.

Link to see current status: https://cocalc.com/projects/94169f5c-20cd-43f0-9bfd-8c62c9c56e6c/files/prolog.ipynb

Console:

```
$ jupyter console --kernel=calysto_prolog
Jupyter console 5.1.0
 
Prolog kernel - evaluates Prolog programs
 
 
In [1]: has(a, b).
      : 
Rule added to database.
 
In [2]: has(a, b)?
      : 
Use '%continue' for more results.
Out[2]: True

In [3]: has(a, c)?
      : 
No more results.
 
```

**Comment by haraldschilly** [comment]
note about completions: `smc-webapp/jupyter/parsing.coffee` is clearly the culprit of breaking prolog.

**Comment by williamstein** [comment]
? help is fixed.

**Comment by williamstein** [comment]
@haraldschilly -- what's current status on this?

**Comment by haraldschilly** [comment]
I don't remember much about this. I think you mentioned that this should be somehow fixed differently. Also, it's weird for me that there is any parsing going on regarding question marks at all. Besides that, this prolog kernel is working again. Hence this issue from my first comment is resolved.

**Comment by williamstein** [comment]
OK, I'll close it.
