### ISSUE TITLE
new mode like ?fullscreen=true called maybe ?embed=true or ?fullscreenlock=true

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2234]
- would remove fullscreen toggle
- clicking anything that would open a new tab/project, just opens that in the usual way in a new tab with no fullscreen at all

**Comment by williamstein** [comment]
REQUESTED BY: MINERVA

**Comment by haraldschilly** [comment]
Ok, just to clarify, the main goal is to disable the fullscreen toggle? (and other means of getting rid of fullscreen?)

That's usually called "kiosk" mode, i.e. where you can browse on a page in a web-browser, but you can't switch to another website. I think that's the idea. Hence `?kiosk` might be appropriate.

Besides that, we could consider to remove other UI elements too (my first thought is the project setting, or even all project tabs) ... as follow up tickets.

wikipedia: https://en.wikipedia.org/wiki/Kiosk_software

**Comment by williamstein** [comment]
yes, EXACTLY -- kiosk mode.

**Comment by haraldschilly** [comment]
the referenced implementation realizes this via `?fullscreen=kiosk` (in addition to the usual `?fullscreen`)

**Comment by williamstein** [comment]
Live in a moment!
