### ISSUE TITLE
No kernel in Jupyter

### ISSUE THREAD

**Issue by klimanek** [sagemathinc/cocalc#2239]
In the latest Cocalc Docker env, no kernels seem to be available in Jupyter. Used to be OK in previous SMC stack. Did I overlook something? 

<img width="1182" alt="cocalc-docker-latest" src="https://user-images.githubusercontent.com/9097163/28778656-9384989a-7600-11e7-8c50-4bca8253bbe3.png">

**Comment by haraldschilly** [comment]
Please send us an URL link to your project to help@sagemath.com such that we can have a look.

**Comment by klimanek** [comment]
It is a docker env on localhost (under Mac OS X), not the public service...

**Comment by haraldschilly** [comment]
well, we don't give support for docker. did you try to click on the "classical notebook" button to switch back? we'll likely fix this once we update docker the next time, but I can't promise when this will be.

**Comment by klimanek** [comment]
Yes, I did. It never switches, though. After a while, I am prompted to log in to the Cocalc again (and that auto-log-off happens randomly after a few minutes, sometimes even seconds, no matter what I do in Cocalc). This docker build seems to be buggy, yes -- I will wait. Thanks.

**Comment by klimanek** [comment]
Well, it finally has given some response now:

> Classical Jupyter is not working
> Please try the plain non-collaborative server, or switch back to the modern Jupyter notebook server.

If I try to run `jupyter notebook` in Cocalc Term (I know, makes almost no sense, but still):

```
~$ jupyter notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1120, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/lib/python2.7/dist-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 193, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

```

**Comment by klimanek** [comment]
Why is this marked as "closed"? Other ppl have been reporting issues with Docker, too.

**Comment by williamstein** [comment]
This is a support question.  Perhaps you're visiting the wrong URL when trying to use docker...

**Comment by klimanek** [comment]
@williamstein I still do not understand. Here is a list of bugs related to Cocalc Docker Image: https://github.com/sagemathinc/cocalc/issues?q=is%3Aopen+is%3Aissue+label%3AA-docker -- so I just forgot to use the A-docker label, right? So why is "my" bug (bugs, for that matter) unimportant and closed? Could this be moved or something? I do know see any reason why people would download a faulty Cocalc docker image.

**Comment by williamstein** [comment]
Answer this question: **EXACTLY WHAT URL ARE YOU USING TO VISIT YOUR DOCKER IMAGE?**

**Comment by klimanek** [comment]
Thank science for clarifying the question ;) -- cuz it was ambiguous. I really thought you were suggesting I am on a wrong URL (here). As I said above, using Kinematic (Docker app), it opens localhost. I tried manually 127.0.0.1 but the result is the same. Funny thing is that in Cocalc settings, I see "localhost.[smc-or-cocalc] (cannot remember, using a different Mac now).

**Comment by williamstein** [comment]
If you visit http://127.0.0.1 instead of https://127.0.0.1, then you'll get exactly the error you are reporting.  This might now be documented in our README.md. See  https://github.com/sagemathinc/cocalc/blob/master/src/dev/docker/README.md
