### ISSUE TITLE
3d plot in sagews ignores frame=False option

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2240]
Try the following in a sage worksheet and notice that `frame=False` is ignored:
```
t,x,y,z = var('t,x,y,z')
helix = (cos(t), sin(t), t)
helix_plot = parametric_plot3d(helix, (t,-4*pi,4*pi), frame=False)
helix_plot
```

Frame does not appear in file created if `helix_plot.save("img.png")` is done and file is viewed.
See also heart and trefoil examples from [here](http://doc.sagemath.org/html/en/reference/plot3d/sage/plot/plot3d/parametric_plot3d.html).

**Comment by DrXyzzy** [comment]
Looks as if the problem comes from a change in rendering routines in [sage_salvus.py](https://github.com/sagemathinc/cocalc/blob/master/src/smc_sagews/smc_sagews/sage_salvus.py#L2596):
```
                salvus.threed(obj, **kwds)
                # graphics.show_3d_plot_using_threejs(obj, **kwds)
```
The newer (uncommented) function, `salvus.threed`, does not pick up `frame` and other options from `obj._extra_kwds`. The commented-out function, `graphics.show_3d_plot_using_threejs` did this.

**Comment by haraldschilly** [comment]
@DrXyzzy I've merged your patch and rolled it out.
