### ISSUE TITLE
Improve "ERROR: 'killed'" message

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2245]
While working in a CoCalc Sage worksheet (.sagews), at some point I got this error message:

    ERROR: 'killed'
    Communication with the Sage server is failing.
    Please try: running this cell again, restarting your project,
    closing and opening this file, refreshing your browser,
    or deleting the contents of ~/.local

This error message could be made clearer, maybe as follows:

    ERROR: 'killed'
    Communication with the Sage server is failing.
    Here are some things you could try:
    - check your internet connection,
    - (if the error persits:) run this cell again,
    - (if the error persists:) close and reopen this file,
    - (if the error persists:) restart your project,
    - (if the error persists:) restart your browser,
    - (if the error persists:) delete some of the content of ~/.local,
      (proceed with care, especially since extra pip packages or Jupyter kernels
      you might have installed would probably be stored there)

**Comment by haraldschilly** [comment]
My PR here is merged, hence I'm closing this issue. Further improvements or changes should be in their own new ticket.
