### ISSUE TITLE
kiosk hardening -- too easy to break out for Jupyter

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2254]
Followup to https://github.com/sagemathinc/cocalc/issues/2234

1. Open a jupyter notebook url and put `?fullscreen=kiosk` at the end.
2. Go into the file menu and click on some of the options (e.g., New), and sort of break out...

Since embedded Juypter is the motivation for kiosk in the first place, it would be good to make some changes to how the File menu is rendered in kiosk mode.

There may be other editors with issues... e.g., "export sage worksheet to jupyter" opens a jupyter notebook after exporting.

This is NOT a security issue and doesn't have to be perfect.  It's just about making the UX good.

**Comment by williamstein** [comment]
Lower priority since no user actually seems to care yet.

**Comment by benepo** [comment]
This functionality would be helpful for our K-12 classrooms use case where students are running through a pre-prepared notebook and we want to limit ways in which they could break out of it or get distracted or click the wrong thing and take up educator time fixing it.

**Comment by haraldschilly** [comment]
@benepo I just saw your comment right now. There is already a kiosk mode, this ticket is just collecting ideas how to harden it.

Related to notebooks: in case you talk about jupyter, we support edit and/or delete protected cells in our own jupyter implementation. This helps with limiting random damage that can be done :-)

**Comment by williamstein** [comment]
Interestingly, this is no longer broken, i.e., clicking new stays in kiosk mode (and silently does nothing).   Yeah.
