### ISSUE TITLE
Restarting project necessary before files visible to collaborators

### ISSUE THREAD

**Issue by zeigerpuppy** [sagemathinc/cocalc#2257]
In the docker version, when collaborators are added to a project, they cannot see the project files until the project is restarted.
They get the error "this folder is not public".

**Comment by williamstein** [comment]
Same with this -- I can't replicate this (it works fine for me).   Please give **very, very precise** steps for precisely how you observed this issue.   From start to finish, including exact OS, browser, exact command to run the Docker image...
