### ISSUE TITLE
Creating accouts with token timeouts

### ISSUE THREAD

**Issue by zeigerpuppy** [sagemathinc/cocalc#2258]
In docker version, when a account signup token is enabled, accounts can no longer be created.
When the user enters their details, the signin button shows the progress animation but never completes the new user creation.
No error is shown to the user or in the browser console.
Creation of users with the token disabled is working.

**Comment by williamstein** [comment]
I can't replicate this.  it works fine for me.

**Comment by williamstein** [comment]
Please give **very, very precise** steps for precisely how you observed this issue.   From start to finish, including exact OS, browser, exact command to run the Docker image...

**Comment by zeigerpuppy** [comment]
Some more details:

Tested with multiple browsers:
- OSX 10.10/10.9 - Safari, Firefox, Chromium
- Windows 7 - Firefox

Docker container was started in Ubuntu 14.04.5 with the following command:

```
docker run --restart=always --name=cocalc -d -v /mnt/experiments/cocalc/projects -p 9080:80 -p 9443:443 sagemathinc/sagemathcloud 
```

The installation is proxied behind an nginx server with the following settings:

```
server {
        listen 443 ssl;
#       listen [::]:443 default_server ipv6only=on;
        server_name    cocalc.mytld.net;

        ssl_certificate    /etc/apache2/ssl-certs/mytld.net/mytld.net_chained.crt;
        ssl_certificate_key /etc/apache2/ssl-certs/mytld.net/private/mytld.net_dec.key;

#add_header X-Frame-Options SAMEORIGIN;
    add_header Content-Security-Policy "frame-ancestors 'self' mytld.net *.mytld.net;";

# include ssl settings
        include /etc/nginx/snippets/ssl_include.conf;

# cocalc is served by research-server via docker
    location / {
      proxy_pass http://res2:9080;
      proxy_redirect http://res2:9080/ $scheme://$host/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_read_timeout 20d;
    }

}
```

**Comment by williamstein** [comment]
Please read the latest version of https://github.com/sagemathinc/cocalc/blob/master/src/dev/docker/README.md
and start over.  E.g., get rid of the port 9080:80 forwarding here -- many things can fail if you use port 80, and **pull the new image** -- we cchanged the name to cocalc a long time ago, so you're getting an old/broken image.

**Comment by zeigerpuppy** [comment]
thank you, it works with the newer image sagemathinc/cocalc

I'm not sure how I ended up following the old guide!
It's really nice that the project files and users pull over nicely to the new docker instance when external storage is mapped.
