### ISSUE TITLE
fix fallout caused by PR 2261

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2267]
https://github.com/sagemathinc/cocalc/pull/2261

It's so confusing too -- showing the directory tree as buttons instead of something that looks like a directory tree.  What OS does that?  What if my directory tree were Create/Upload/Terminal -- then I see buttons labeled "Create", "Upload", and "Terminal" ?

Also looks bad on ipad
[
![img_0073](https://user-images.githubusercontent.com/1276278/29091115-b7096110-7c36-11e7-958a-89b23e209d84.PNG)
](url)

**Comment by williamstein** [comment]
I do not understand why you're using buttons here -- it doesn't look like a directory path at all, e.g., like the output of `pwd`...

**Comment by williamstein** [comment]
(also buttons tend to not express an explicit heierarchy from left to right, whereas the forward slash of a directory tree does.)

**Comment by johnjeng** [comment]
This is #2266
