### ISSUE TITLE
Sage worksheet underscore for last output does not work when typeset_mode is true

### ISSUE THREAD

**Issue by TimMcLEC** [sagemathinc/cocalc#2268]
This is bug #445, which has been closed by williamstein but still exists in CoCalc as of 08/08/2017:

_ does not work if %typeset_mode True has been run.  This is pretty serious, in that in means you can never use Typeset Mode if you ever want to refer to an earlier output.  The problem is fixed in the Mac version of Sage 8.0, but on CoCalc, the same error occurs as in

Example: https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-02-29-underscore_and_typeset_mode.sagews

**Comment by williamstein** [comment]
dup of #2124
