### ISSUE TITLE
disable command mode of files search box in a public project

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2273]
1. open a directory of a project where you're not a collaborator (public project feature)
2. enter '/' in the files search box
3. it happily switches command line mode and even tries to execute a command (fails with an error, though)

expected: it shouldn't even enter command mode

**Comment by johnjeng** [comment]
What should happen in public mode when you search `/something`? `/`'s are not allowed in names. Only show directories?

**Comment by haraldschilly** [comment]
I've made a small change in https://github.com/sagemathinc/cocalc/pull/2274
to just show nothing. Yes, it's not allowed, and it doesn't find something
either.

**Comment by williamstein** [comment]
public projects no longer exist
