### ISSUE TITLE
webapp: subscriptions say "powered by ... whom?"

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2277]
the stripe logo or string is missing.

![screenshot from 2017-08-10 23-32-37](https://user-images.githubusercontent.com/207405/29193104-366fda30-7e24-11e7-99fa-494bab1ef5a6.png)

**Comment by williamstein** [comment]
whom = stripe.  Maybe the font-awesome name changed?

**Comment by rgbkrk** [comment]
> Powered bye bye

I'll... show myself out

**Comment by haraldschilly** [comment]
I pushed a simple fix. This name is a special case, because it clashes with the prefix name of our own icons. I didn't think about that what I wrote that. well...
