### ISSUE TITLE
Add SSH Key 'Type not supported' error is too sticky

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2293]
Tested in kucalc.

1. Generate an ssh public key and copy to your clipboard.
1. In project settings, click 'Add an SSH Key' and paste the public key into 'Key' input field.
1. Make the key invalid by deleting the space between key type and key.
1. Click 'Add SSH Key' and get the error message 'Type not supported'.
1. Click 'Cancel' to close the dialogue.
1. Now click 'Add an SSH Key' key again. Key entry dialogue is empty, but error message is still there. 
1. Error is cleared by either
  - clicking away, e.g. to Files list, and back, or
  - entering a valid key

**Comment by williamstein** [comment]
It was even more "sticky" initially, but I had tried to fix it.  I guess I didn't fix it sufficiently.
