### ISSUE TITLE
creating a large course results in error/timeout messages while working perfectly fine

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2299]
See -- I'm making a course with 200 students.  It *is* working perfectly and the counter keeps making additional projects.  The error banners are just wrong!

<img width="1264" alt="screen shot 2017-08-16 at 5 13 31 pm" src="https://user-images.githubusercontent.com/1276278/29390618-579c1cce-82a6-11e7-8f0b-b9e47c887c65.png">

**Comment by johnjeng** [comment]
I've only been able to replicate the banners. For example, disconnecting shortly will make that project not complete. Though, the project itself could have been created. In my testing, scrolling down to the project creation that timed out will reveal itself to not have been created.

Added a commit to improve the error message.
https://github.com/sagemathinc/cocalc/commit/f2fcecf793e1933538f5bc8ae0a076665d5cd7a1

**Comment by williamstein** [comment]
Closing due to message.
