### ISSUE TITLE
in course settings it always says "1 of xxx student projects currently running." after they have **all** stopped.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2300]
See:

<img width="579" alt="screen shot 2017-08-16 at 7 18 34 pm" src="https://user-images.githubusercontent.com/1276278/29393287-c1356e72-82b7-11e7-8db2-f30ebfb9d8df.png">

I have no idea why.  I looked at the code and it looks good.

**Comment by johnjeng** [comment]
I've looked at this several times and couldn't figure it out. I'll take a harder look..

**Comment by johnjeng** [comment]
So far I've been able to replicate this once..

**Comment by williamstein** [comment]
I’m no longer replicating this on the live site, but instead have seen it work fine frequently. Closing.
