### ISSUE TITLE
broken error when creating file (a terminal) right before project started up

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2306]
This is what I just saw when I:
1. Make a new project
2. Click to create a new terminal... before the project has finished starting:

![img_0098](https://user-images.githubusercontent.com/1276278/29470877-eb333ffa-8402-11e7-8441-66397545dbc8.PNG)

What should happen:
  - It should work.  The project does start up fine a few seconds later — might as well have file creation retry a few times, rather than showing a broken error.  Use `misc.retry_until_success`.

**Comment by johnjeng** [comment]
This seems to only be a problem in Kucalc. Cannot replicate on live site nor smc-in-smc. It seems to wait until the terminal is creatable and then opens it or times out if the project takes a while.

**Comment by williamstein** [comment]
Very easy to replicate on cocalc.com right now on the Files page too...
![64e9abbe-b19e-41b8-8275-5b22bd7a66d6](https://user-images.githubusercontent.com/1276278/30130988-fd1233fa-92ff-11e7-9f71-29fa9656ba49.jpeg)

**Comment by williamstein** [comment]
fixed long ago.
