### ISSUE TITLE
allow specifying registration token on kucalc API create_account

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2308]
Call to create_account API in kucalc gives
```
{"event":"account_creation_failed",
 "id":"c3276a92-e9cb-466a-82ce-abf229cba7f3",
 "reason":{"token":"Incorrect registration token."}}
```

**Comment by DrXyzzy** [comment]
This has been fixed by @williamstein.

**Comment by williamstein** [comment]
wait — I definitely don't remember fixing this.

**Comment by DrXyzzy** [comment]
I guess it was never a bug. Sorry. I tested API `create_account` in kucalc yesterday and the correct token was definitely required. So we should be ok now.

According to `git blame`, code to make it work has been there since May 13:
 [src/smc-hub/create-account.coffee](https://github.com/sagemathinc/cocalc/blob/master/src/smc-hub/create-account.coffee#L93)
