### ISSUE TITLE
make Jupyter notebook show sage plots as svg by default

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2313]

**Comment by williamstein** [comment]
I'm hitting this again.  PNG looks so damn ugly!   I don't even know a workaround, i.e., [this](https://stackoverflow.com/questions/36622237/jupyter-notebook-inline-plots-as-svg) does not work.

**Comment by slel** [comment]
Not sure if any of the svg-related Sage trac tickets can help,
and can't find anything relevant in sagecell or sagenb repos:

- https://trac.sagemath.org/query?order=id&desc=1&summary=~svg
- https://github.com/sagemath/sagecell/search?q=svg
- https://github.com/sagemath/sagenb/search?q=svg

But maybe these two posts by Simon Willerton and Volker Braun
in a sage-support discussion can be helpful:

- https://groups.google.com/d/msg/sage-support/MLndF5sA9DE/1nAH3TANBQAJ
- https://groups.google.com/d/msg/sage-support/MLndF5sA9DE/p1GLtmjeAwAJ

**Comment by williamstein** [comment]
I'm closing this, since as @slel remarks it's not really something we should be forcing to change by default... and there are cases where png is way better.
