### ISSUE TITLE
kucalc: julia in sagews ?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2318]
I think we see the pexpect interface going mental.

![screenshot from 2017-08-22 21-25-14](https://user-images.githubusercontent.com/207405/29583490-976989fc-8780-11e7-9541-25def764d9c8.png)

terminal:

```
~$ jupyter console --kernel=julia
WARNING: [ ... several ijulia internal warnings .... ] 
Starting kernel event loops.
Jupyter console 5.1.0
 
Julia: A fresh approach to technical computing.
 
 
In [1]: 1+1
Out[1]: 2
 
In [2]:  
```

:+1:

**Comment by DrXyzzy** [comment]
bash kernel also uses pexpect #2311. Has the version changed? Update to pexpect (possibly incompatible with sage) was a cause of breakage during early jupyter bridge dev IIRC.

**Comment by haraldschilly** [comment]
well, it's sage 8.0 now. maybe they've updated or changed something upstream? 

%python3 and %r do work, though (well, python3's plot is 2x sized, but I'm not worrying about this downscaling issue for now)

**Comment by williamstein** [comment]
Is #2419
