### ISSUE TITLE
show file upload progress with kucalc

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2327]
I tried to upload a file that was about 200 MB from my laptop. I saw no progress indication and `ls` in target directory didn't show anything. I checked back a couple hours later and the file was there.

**Comment by williamstein** [comment]
File upload does show a progress indicator, then a checkbox at the end when it is done.  I'm closing this unless you can clarify what you mean.  File upload progress is a basic feature of the "Dropzone" component we use for uploads.
