### ISSUE TITLE
make it easy to hide/delete all projects matching a search

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2339]
Requested by Ed Snyder;

>  Will it be possible in the future to delete multiple student projects from past courses all at once?

Hmm-- if you type a search in the project listing, you then get a chance to remove yourself from everything matches that search.  It would be easy to enhance that button to also let you delete or hide all matches.

**Comment by williamstein** [comment]
@bryantpq is working on this.

**Comment by bryantpq** [comment]
Done! [#2365](https://github.com/sagemathinc/cocalc/pull/2365)
