### ISSUE TITLE
get ssh-agent authentication to work when users ssh into CoCalc

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2340]
I have configured an ssh public key for a CoCalc account and confirmed that it can be used to ssh into a project. However, it's still necessary to enter password when doing ssh from the project, and doing `ssh-add -L` in the CoCalc project does not show the user's key. It produces the following instead:
```
~$ ssh-add -L
Could not open a connection to your authentication agent.
```

**Comment by williamstein** [comment]
We should probably add 
```
X11Forwarding yes
AllowAgentForwarding yes
```
in either the ssh gateway or for the sshd running in the project or both.  Will have to try on kucalc test cluster first, then live...

**Comment by williamstein** [comment]
Done.
