### ISSUE TITLE
support interactive widgets in classical Jupyter notebook

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2353]
![c8167885-73ec-4dc2-80a0-2a9cd4c7cab6](https://user-images.githubusercontent.com/1276278/30074344-15e4d944-9226-11e7-9798-1cc533085354.jpeg)

REQUIRED BY: many, many people including Donna Calhoun

**Comment by haraldschilly** [comment]
Well, [documentation](http://ipywidgets.readthedocs.io/en/latest/user_install.html) says

> Installing ipywidgets with conda will also enable the extension for you.

I'm reinstalling it, let's see if this triggers the setup properly.

**Comment by haraldschilly** [comment]
attached are screenshots for python 2 (linux) and python 3 (anaconda)

![python3-anaconda-ipywidgets](https://user-images.githubusercontent.com/207405/30104344-a5f8f482-92f5-11e7-95a4-8a9068a0ba9b.png)

![ipywidgets-python2](https://user-images.githubusercontent.com/207405/30104345-a5fb5b82-92f5-11e7-9b64-c0b10d4984f3.png)

**Comment by jaliste** [comment]
Hi, it does not work for me. When Trying the code in the screenshot, I get the following message: 
Failed to display Jupyter Widget of type Text.

If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions.

If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.

**Comment by DrXyzzy** [comment]
@jaliste, you will see those messages if you try to use Jupyter widgets in the [modern CoCalc Jupyter Notebook](http://blog.sagemath.com/jupyter/2017/05/05/jupyter-rewrite-for-smc.html), which is the default. Ipywidgets are only supported in the Classic Jupyter notebook. To start Classic notebooks, open the project settings page (wrench icon <img src="https://github.com/encharm/Font-Awesome-SVG-PNG/raw/master/black/png/16/wrench.png">) and click `Plain Jupyter Server` at bottom right:

<img width="670" alt="plain-jupyter-server" src="https://user-images.githubusercontent.com/528072/35364630-cde5ded4-0135-11e8-8bdb-aba6675325f4.png">

For additional info, see the wiki page: [JupyterClassicModern](../wiki/JupyterClassicModern).

**Comment by perez1987** [comment]
@haraldschilly I see that the ipywidgets within cocalc have worked for you in the collaborative environment. Works? I can not get it to work ..
