### ISSUE TITLE
jupyter2: alt+return ?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2372]
I don't know what all keyboard shortcuts symbols in jupter2's menu mean. Does the one next to cell -> "run cells and insert below" stand for "alt+return" ?

If so, it doesn't work. Enter something like "2+2" into the cell, type "alt+return", and you're still in the same cell. The active cell should be below. I think it works if the "2+2" cell isn't in edit mode, though.

**Comment by williamstein** [comment]
Yes, it means alt.  The behavior must match upstream jupyter or it is bug.  It's almost the same -- it does in fact "run cells and insert [a new cell] below." However, upstream jupyter also makes that new cell be focused, but Cocalc only does that in command mode (not edit mode).  So yep, bug.
