### ISSUE TITLE
add jupyter keyboard shortcut for run all cells

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2375]
Note that in modern jupyter notebook, if you put the sheet in command mode (blue sidebar at left of current cell), you can do Ctrl+A to select all cells and shift+Enter to run them. Tested with Python 3 (Anaconda) kernel.

**Comment by slel** [comment]
To go to command mode you can also press Esc. So to run all cells, type Esc, Ctrl-A, Shift-Enter.

**Comment by williamstein** [comment]
I think for now the workaround posted above are sufficient. Closing.

**Comment by cnaccio** [comment]
Thanks for the tip; exactly what I was looking for.

**Comment by Ahmedborhamy** [comment]
Thanks for the tip; exactly what I was looking for.
