### ISSUE TITLE
Migrate to Webpack 3.x

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2387]
We are currently using Webpack 1.13.x, which is ancient and probably slow, barely maintained, etc.   I'm sick of regularly running out of RAM when just trying to use Webpack at all.  

As I write this the current version is **Webpack 3.6.0**.  Presumably it is much better in many ways, since webpack got a lot of funding/dev effort as a result of the explosion in React, etc.

**Comment by johnjeng** [comment]
On Webpack 4.1.1 now.
