### ISSUE TITLE
install GPy

### ISSUE THREAD

**Issue by benchun** [sagemathinc/cocalc#2389]
We initially expected that scikit.learn would be sufficient for everything, but have now found out that their Gaussian Process support isn't particularly good.

Can we get the "GPy" package installed?  It should just be a case of "pip install GPy" (note the unusual capitalization).

**Comment by haraldschilly** [comment]
Hello, can you please be specific about which python environment? (system, version 2 or 3, sagemath or anaconda?)

In itself it is python2 and 3 compatible, so, ideally it could be in all four of them :-)

**Comment by williamstein** [comment]
@benchun -- **they use anaconda3**

**Comment by philip-sterne** [comment]
@williamstein, @haraldschilly : 
Some students are writing python 2 and some are writing python 3 code.  So at the very least anaconda2 and anaconda3 would be nice.  

If it's possible to install on all 4 then it would help remove a source of issues in class if students are using the "wrong" version.

**Comment by haraldschilly** [comment]
We don't have anaconda2, sorry, but there is a system-wide python2. I'm installing GPy in the python2, python3 and anaconda3 environments.

Good news is, I update the master image and ran the included test in the anaconda environment: 

```
Ran 389 tests in 246.611s
FAILED (SKIP=4, errors=3)
```

bad news is there seems to be some plotting commands triggering QT libraries. 
 `os.environ['QT_QPA_PLATFORM']='offscreen'`  tells it that there is no display and avoids a crash. I think we should set this variable by default.

**Comment by haraldschilly** [comment]
![screenshot from 2017-09-23 16-20-48](https://user-images.githubusercontent.com/207405/30773935-34db5b58-a07b-11e7-9d71-dccec69b74e4.png)

**Comment by haraldschilly** [comment]
It's installed, closing issue
