### ISSUE TITLE
redo the ROOT (cern library) support for Sage and Jupyter notebooks

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#239]

**Comment by williamstein** [comment]
NOTE: ROOT right now is installed systemwide and you might be able to use it from the Jupyter notebook by selecting the "Python 2 (Ubuntu, plain)" kernel.

**Comment by williamstein** [comment]
> mkarakoc 10:47 -- If it is possible, would you ask to the developer(s) why I am getting from from ROOT import TSpectrum this "ImportError: cannot import name TSpectrum". Is this package does not exist ROOT version ( Version 5.34/30 23 April 2015 ) in SMC?

**Comment by mkarakoc** [comment]
How to create a ROOTbook?
https://root.cern.ch/how/how-create-rootbook

ROOT kernel for Jupyter notebooks. It may be more convient, but I am not sure.

**Comment by slel** [comment]
Not sure this is insanely hard. Following the instructions at
https://root.cern.ch/building-root
one can easily build a recent version of ROOT.

**Comment by slel** [comment]
Follow-up issue, sort of duplicate but taking into account X11 support, at #3398.

**Comment by haraldschilly** [comment]
I'm closing this ticket. There is a ROOT kernel, but for the usual C interface.
