### ISSUE TITLE
support making an entire project  public 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2391]
REQUESTED BY: Sean Raleigh

In his words: 
> "I can see how to share individual files and folders within projects, but I can't see anywhere to share a whole project publicly. I'd even be okay with being able to select all the files/folders within a project and share, but as soon as I select more than one, the Share button goes away."

**Comment by johnjeng** [comment]
Seems easy enough since public is just a flag which is easy enough to set. 
Any reason that the Share button goes away for multiple selections?

**Comment by johnjeng** [comment]
Guidance: For anyone who wants to do this, see `set_public_path` in [project_store.coffee](https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/project_store.coffee) and `render_action_buttons` in [project_files.cjsx](https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/project_files.cjsx)

**Comment by williamstein** [comment]
> Any reason that the Share button goes away for multiple selections?

Yes, because we were worried that it is inefficient to have many of them set, since each is a separate addition to the database.

I dont't think the public flag in the projects table (if there is one) is relevant to anything anymore -- it does nothing and means nothing these days (it was important in 2013).    What matters is the public_paths table.

To make an entire project public would I guess mean making the HOME directory of the project public, which might mean making `""` or `"."` public.  Not sure.   This is every different of course than making all visible folders public, since this would also impact newly added folders.

**Comment by williamstein** [comment]
REQUESTED BY: Kevin Buzzard a few times recently, since it would be very helpful with Lean on cocalc.

We did actually used to have this. 

Some thoughts:

- It's not clear where to put an option to make an entire project public.  It used to be in project settings.
- If you click the big green button "Open in CoCalc with One Click!", then if the public shared content is a project, CoCalc should always create an entire new project, rather than re-using an existing one.

Other than that, this seems pretty easy to re-enable.

**Comment by novoselt** [comment]
Stumbled on this by accident, but thought about it before. It would make perfect sense for publishing books, for example, when the whole project is created specifically for the purpose of sharing that book. It may be also quite desirable to automatically share everything new in the project.

However I see the point that it is not very clear how our existing interface should be modified to support this and complicating it is undesirable.

I am also very concerned about hidden files - I expect they are shared as well in every shared folder (and I would think it is a bug if they are not), but that means that some stuff can leak inadvertently, from ssh keys to just plain shell history. So perhaps to avoid dealing with these issues (including explaining to users that there is nothing to worry about), we just should not support this feature and add a note in documentation that it is not going to happen?

**Comment by williamstein** [comment]
I think the last person to request this was several *years* ago.  I agree we should close this, as it is a security hassle.   I would rather come up with something similar but at the level of compute server images.

**Comment by novoselt** [comment]
https://doc.cocalc.com/share.html#publishing-the-whole-project
