### ISSUE TITLE
destination directory list slow to appear when copying file to different project

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2395]
This is an old issue but I don't see a bug report for it. Latency is most noticeable when the destination is a project with many directories and subdirectories.
1. Select a file in Files view by clicking left checkbox.
1. Click Copy.
1. Click "a different project" in "Copy to a folder or _a different project_".
1. Select a project under "In the project" that has a large number of folders in the home directory and many subfolders under them.
1. Click the downward arrow to the right under "Destination".
1. Notice that it can take a long time (30 seconds or more) for options to appear under "Destination".

**Comment by williamstein** [comment]
The right fix is (obviously) to compeletely remove this listing entirely.  Instead, we should show a directory browser for the target project.  We should make a small more embeddable version of our current directory browser component. 

The reason it takes a long time now is that basically `find` (I think) is run to scan the entire directory hierarchy first.

**Comment by williamstein** [comment]
We do now show a directory browser for the target project.
