### ISSUE TITLE
cannot scroll message preview in chat

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2396]
Seen with Chrome and Firefox on macOS 10.12.6:

1. Open chat room (.sage-chat) file.
1. Paste text into Send box that is longer than the browser tab.
1. Click Preview. A preview of the bottom part of the message is displayed.
1. Notice that chat preview cannot be scrolled.
1. Also the 'x' at upper right to dismiss the preview is not visible. The 'x' is made visible again by shortening the contents of the Send box or sending the message.

**Comment by williamstein** [comment]
No longer the case...
