### ISSUE TITLE
Raw cells in jupyter notebook don't render fully until selected

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#2397]
When I switch between jupyter notebooks in a single project, I have been observing that raw cells often do not render fully at first; only a few lines at the top of the cell are visible, the rest appearing blank. However, once I select the cell it starts to render correctly, and continues to do so until I switch to something else in the project.

**Comment by williamstein** [comment]
@kedlaya -- I fixed this just now...

**Comment by kedlaya** [comment]
Yes, this looks like it is now fixed. Thanks!
