### ISSUE TITLE
add an extra input box next to the grade box for a comment.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2398]
Requested by Kristin McCully:

> "Currently we've been putting both a numerical score & comments in the grade box. That's difficult to parse out in the resulting CSV. It would be great to have a small grade box just for the grade and a separate larger comment box for more text that would be separate columns in the CSV, so we can upload them to our gradebook as separate columns in CSV. Thus far, we've either had to enter scores in our gradebook manually or use complicated code/Excel function to parse out numerical scores. I hope that's specific enough ..."

(whoever does this may as well also make returning without a grade optional -- just don't do that check and include the return button -- it would probably just involve commenting out a line of code.)

**Comment by johnjeng** [comment]
So, this will be a breaking change for people parsing their CSV files. Do we want to warn them?

**Comment by williamstein** [comment]
Is there a way to do this that is backward compatible?  E.g., put the new column at the very end?

**Comment by johnjeng** [comment]
Yeah, we can do that. Organizationally it makes less sense to me.

**Comment by johnjeng** [comment]
Oh, except it mirrors the organization of the Python export. Cool.

**Comment by williamstein** [comment]
Done!

**Comment by williamstein** [comment]
<img width="1365" alt="screen shot 2017-10-02 at 2 08 32 pm" src="https://user-images.githubusercontent.com/1276278/31099578-56ec022c-a77b-11e7-9a11-b3a2844e7178.png">
