### ISSUE TITLE
Subdirectories with a "#" in their names stopped existing.

### ISSUE THREAD

**Issue by diataha** [sagemathinc/cocalc#2400]
I have a CoCalc project where I wrote lecture notes. It has subdirectories named things like "Homework #1" and "Lecture #1". When I now try accessing those I get an error message:

> No such directory
> The path Lecture #1 does not exist.

Only the subdirectories with a # sign in their names have that problem.

**Comment by haraldschilly** [comment]
Hello, that must be a bug. Do you need help renaming these directories back to have no "#"? In the meantime we're working on a bugfix.

**Comment by williamstein** [comment]
fix will be live in a few minutes; only will applies to newly (re-)started projects.

**Comment by diataha** [comment]
Works like a charm. Thanks!
