### ISSUE TITLE
typeset of long output line in sagews wraps too far to the right

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2402]
Try the following in a sagews cell. 
```
typeset_mode(True)
%var alpha, beta, delta
B1 = matrix([[-1,1],[1,1]])
B2 = matrix([[1,0],[0,cos(delta)+i*sin(delta)]])
B3 = matrix([[1,1],[1,-1]])
BB = 1/2 *B3 * B2 * B1
(BB*vector([alpha,beta]))[0].norm()
```
Text goes out of browser tab on the right in Chrome and Firefox.

**Comment by DrXyzzy** [comment]
Equivalent cell in jupyter notebook with sage 8.0 kernel does not show the problem:
```
var('alpha', 'beta', 'delta')
B1 = matrix([[-1,1],[1,1]])
B2 = matrix([[1,0],[0,cos(delta)+i*sin(delta)]])
B3 = matrix([[1,1],[1,-1]])
BB = 1/2 *B3 * B2 * B1
show((BB*vector([alpha,beta]))[0].norm())
```

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.

Output in #6374 will just be exactly the Jupyter output in a line widget.
