### ISSUE TITLE
package installed with pip in user anaconda environment is not accessible

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2403]
The last two lines work (i.e., grep finds the _see_ package and import succeeds) in ordinary ubuntu, but not in a cocalc term:
```
anaconda3
conda create --name bunnies
source activate bunnies
# now in (bunnies) environment
pip install see         # does not report any errors
conda list | grep see   # ** no output
python -c 'import see'  # ** ModuleNotFoundError
```

**Comment by haraldschilly** [comment]
I think this is sort of invalid and confusing things are going on. "conda" is its own system, and you're installing via the system pip. That way, it ends up in `~/.local/...` outside of the environment.

However, what you can do is to first install "pip" into your own anaconda environment, i.e.

```
(bunnies) $ conda install pip
(bunnies) $ which pip
/home/user/.conda/envs/bunnies/bin/pip
```

That way, pip is no longer the system ones and `pip` installs into. However, we also alias "pip" as a bash command to automatically add `--user` for install requests. That way, we help novice users and they do not see the error message about needing sudo rights for global installs. (If you have a better idea here, tell me :-) ). 

Therefore, you also have to do

```
unset pip
unset pip3
```

to get the "pure" behavior.  After that, pip installs into

```
/home/user/.conda/envs/bunnies/lib/python3.6/site-packages/see*
```

Which looks like the correct place to me. 

However, in anaconda's bunnies environment, the python's `sys.path` array still does not list this `site-packages` directory. I don't know why. I think this is some sort of bug or "decision" made by anaconda how to treat this. Maybe there is an upstream ticket somewhere for adding the local site-packages path to the pythonpath for environments in conda?

**Comment by DrXyzzy** [comment]
Thanks. I'm closing this because I wasn't aware of bash alias masking pip, etc. :-) After doing `unset pip`, I can use my environment to install a package with pip and it appears in the package list, so my 'not accessible' bug report is incorrect.
```
~$ anaconda3
(root) ~$ type pip
pip is a function
...
(root) ~$ unset pip pip3
(root) ~$ conda create -n foo
(root) ~$ source activate foo
(foo) ~$ conda install pip
(foo) ~$ type pip
pip is /home/user/.conda/envs/foo/bin/pip
(foo) ~$ pip install see
(foo) ~$ conda list see
...
see                       1.4.1                     <pip>
```

BTW here's the link to the tutorial covering use of `pip` in a `conda` environment to install a package that's not in [conda-forge](https://anaconda.org/conda-forge):

https://conda.io/docs/user-guide/getting-started.html#installing-a-package-with-pip 

They don't say to install pip in the conda environment in this tutorial but do mention it elsewhere in the docs.

**Comment by anishmittal2020** [comment]
@haraldschilly Thank you for the nice explanation. However, please clarify this:

As the pip is aliased may be as follows (bash function)

```
pip() {
	if [[ $1 == "install" ]]; then
		command pip install --user "${@:2}" # Refer: 17
	else
		command pip "$@"
	fi
}
```

When we are inside a conda environment, which has pip installed (in the environment), the pip (of environemnt) is ahead in the ${PATH} than `/usr/local/bin/pip`. So, when the shell function is executed, shouldn't the environment pip be invoked?

My question why do we need to unset pip (although it works as you said, but I am not sure why)?

**Comment by haraldschilly** [comment]
@anishmittal2020 see:

```
~$ type anaconda5
anaconda5 is a function
anaconda5 () 
{ 
    unset -f pip pip2 pip3;
    source "$ANACONDA5/bin/activate" root
}
```
