### ISSUE TITLE
don't ship ES2016+ code (was: Immediately show a big red error and halt load if the web browser is any version of Internet Explorer)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2407]
CoCalc works very well in recent versions of Safari, Firefox, Chrome, and (I'm told) Edge.  However, it does not work at all in any version of Internet Explorer. 

I'm labeling this a bug, since it is a confusing thing that will surprise some users.

For fun, here is the actual browser usage of cocalc during the last week:

![b8441e5a-8cdb-4d77-8d76-e159710d9bb4](https://user-images.githubusercontent.com/1276278/30973847-fa6efdac-a422-11e7-83de-8972e45f69f1.jpeg)

**Comment by williamstein** [comment]
Here's what all 917 of those IE users would have saw this week:

![6b4a208b-78f8-4994-a9ad-008651924373](https://user-images.githubusercontent.com/1276278/30973983-5222b372-a423-11e7-88e6-b2a274f80741.jpeg)

**Comment by williamstein** [comment]
Alternatively, use babel or a conditional import (try/catch) to not support certain functionality on IE.  E.g., maybe this latest problem was caused by prom-client?

**Comment by haraldschilly** [comment]
I've worked on this for a bit, it's tricky. There is no try/catch for syntax errors, splitting up the code in permutations for browser versions is a lot of overhead, testing almost impossible.

At least, I know for 100% that it is caused by prom-client/lib/util.js

**Comment by williamstein** [comment]
Then we should disable this prom-client stuff for now and instead use webpack+babel to properly convert it to valid code before shipping it to the browser; or, alternatively, conditionally load it after the main page load.  I will disable the client code for now.
