### ISSUE TITLE
make single line install command

### ISSUE THREAD

**Issue by peoplesnsa** [sagemathinc/cocalc#241]
See https://gist.github.com/btm/6700524

**Comment by williamstein** [comment]
The single line for smc is going to be

    npm install sagemathcloud

This is a standard thing supported by npm.   There's still a lot of work before this is ready though.  Right now, to setup SMC for development requires doing:

     git clone https://github.com/sagemathinc/smc; git checkout smc-in-smc; cd smc/src; npm run make

**Comment by haraldschilly** [comment]
closing this, no longer applicable and since you need a database, this requires some additional steps specific to your system. notes are here: https://github.com/sagemathinc/cocalc/blob/master/src/README.md
