### ISSUE TITLE
Canonicalize conversion from normal file names to .py file names

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#2410]
Example from courses, exporting grades to python files will result in an invalid python file name if the course name has spaces or dashes. 

Spaces should be replaces with underscores. Not sure what to replace dashes with.

**Comment by williamstein** [comment]
How about if we put all exported files in a new subdirectory called `coursefilename-export/`.  Then we can give them a name that is based on the current timestamp and is a valid Python filename.

**Comment by williamstein** [comment]
My suggestion evidently got implemented long long ago:

<img width="677" alt="image" src="https://github.com/user-attachments/assets/e9b1f131-1bc5-4e82-bdea-d8d369d35f18">
