### ISSUE TITLE
Student tutorial either missing or hard to find

### ISSUE THREAD

**Issue by lahvak** [sagemathinc/cocalc#2418]
The Cocalc documentation says: "We have added a students’ mini tutorial! This might be handy for when you implement your lectures. Just click on the Students tab!",  however, I don't seem to be able to find any such thing.  If it is there, it is well hidden.

**Comment by haraldschilly** [comment]
My understanding is, that this refers to the links at the top. You click on "Students" and then you end up here: https://tutorial.cocalc.com/students/

**Comment by haraldschilly** [comment]
and well, looking at that page, it should be updated a little bit ... :roll_eyes:

**Comment by haraldschilly** [comment]
I made this part of the tutorial a link, so no need to look for the tab. I've also fixed some other broken links and made small changes. Closing this ticket.

Note to the future: Issues with the tutorial are best reported right at its repository: https://github.com/sagemathinc/cocalc_tutorial/issues
