### ISSUE TITLE
failed assignments in a course should not be in the state "done"

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2432]
When an assignment fails due to an error, it makes little sense to let the UI show it as if the files are copied. 

That makes reassigning the failed ones hard, because the UI thinks all are done. Also, the collect button would collect from nowhere...
![screenshot from 2017-10-18 12-12-06](https://user-images.githubusercontent.com/207405/31713204-c8c0d812-b3fd-11e7-94ab-58543b80cc45.png)

**Comment by williamstein** [comment]
Maybe fixed
