### ISSUE TITLE
Clearing scrollback buffer in .terminal

### ISSUE THREAD

**Issue by zeigerpuppy** [sagemathinc/cocalc#2433]
Is there a way to delete the scrollback buffer in a cocalc terminal without deleting the terminal?
I would like to clear some sensitive data but want to keep the chat and command history associated with the terminal.

I tried with CTRL+L but the scrollback is still present

**Comment by zeigerpuppy** [comment]
Here's a kludge.... fills the scrolback buffer so that earlier stuff not visible

```
printf 'Clear\n%.0s' {1..1000}
```

**Comment by haraldschilly** [comment]
Hmm, I think I understand what you mean. 

In a "plain" terminal, type in "reset". That's a bash command to reinitialize itself. Should clear the buffer.

If you use tmux or another multiplexer, this is on top of the managed tty interface. Here, you type in "reset" and then close and reopen the terminal tab.

**Comment by haraldschilly** [comment]
I've made short [faq entry](https://github.com/sagemathinc/cocalc/wiki/FAQ#clearterminal) ... I hope it is correct and understandable. Closing issue.

**Comment by zeigerpuppy** [comment]
thanks, that's exactly what I needed, the `reset` command is what I needed.
