### ISSUE TITLE
running all cells in sagews keeps appending an empty cell

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2435]
Repeating the following steps causes a new empty cell to be appended to the worksheet every time.
1. In any sagews file, select all cells.
1. Hit shift-Enter.
1. Reposition cursor in top cell. (Optional. This step shows that the problem is not just because cursor is left at bottom after running all cells.)

**Comment by williamstein** [comment]
This matches the behavior of Jupyter so is correct.
