### ISSUE TITLE
plot size larger with Anaconda jupyter kernel, even more so with shared notebook

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2457]
Run the following in a jupyter notebook with different Python kernels and view as private and as shared:
```
import numpy as np
import matplotlib.pyplot as plt

-- new cell --
x = np.linspace(0, 2*np.pi, 100, endpoint=True)
y = np.sin(x)
plt.plot(x, y);
```
Here's a sample notebook used:
https://cocalc.com/projects/bfcc0898-8cc2-4b97-9230-ada8a57e5b53/files/Public/simple-plot2.ipynb

1. The plot with the Anaconda kernel in private view is larger than with other kernels in private view.
1. When viewed from incognito session as shared file, the plot with Anaconda kernel is almost twice as large as in the private view.

This table shows approximate pixel sizes of the rectangular border of the plot, using google chrome on MacBook laptop:

|kernel|shared|width|height|
|-|-|-:|-:|
|Python 3 (Anaconda)|no|670|380|
|Python 3 (Anaconda)|yes|1110|630|
|Python 3 (Ubuntu Linux)|no|332|218|
|Python 3 (Ubuntu Linux)|yes|332|218|
|Python 2 (Sagemath)|no|466|310|
|Python 2 (Sagemath)|yes|466|310|
|Python 2 (Ubuntu Linux)|no|340|220|
|Python 2 (Ubuntu Linux)|yes|340|220|

**Comment by haraldschilly** [comment]
For anaconda, they're 2x oversampled on purpose and should be resized to half their dimensions. It's still odd that there are so many different sizes, I would expect to have only two. And no idea what's up with private vs. shared ....

**Comment by williamstein** [comment]
I can no longer reproduce this.  I guess it got fixed as a side effect of other things.
