### ISSUE TITLE
allow viewing the MORE of the project activity log

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2471]
Present display of project activity log is truncated. Add a button that pulls in *more* of the log. Click it once in that project and more is there until you refresh.

[edited: changed to more -- pulling in all is nuts in general, it could be 100K long...]

**Comment by DrXyzzy** [comment]
Is there a way to filter all of the log for some text? That's the main reason I'm interested in history going back a long way. Maybe do MORE on the result if it's lengthy.

**Comment by williamstein** [comment]
> Is there a way...

no, there is no way to do that sort of query into the db from a client.  You can only say "give me the most recent k entries".

**Comment by williamstein** [comment]
Maybe there should also be just an entirely separate table that is what you really want, e.g., "the last 200 files opened in this project in order from newest to oldest" and that's it.   It might be called `recent_files`.

**Comment by williamstein** [comment]
I think we sufficiently have this now.  It's not the complete history in general, but it's quite big.
