### ISSUE TITLE
REACT 16 -- major new bug that completely crashes the entire session

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2472]
1. stop a project
2. go to the file listing
3. right as it starts loading, type "ls"[enter] in the miniterminal on the right.
4. BOOM!!  Screen goes blank.  Big traceback in the log.

<img width="1070" alt="screen shot 2017-11-03 at 11 11 01 am" src="https://user-images.githubusercontent.com/1276278/32389484-fd1cee0c-c087-11e7-839f-89d06bccdb78.png">

Link goes to https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcode%2C%20errno%2C%20syscall%2C%20address%2C%20port%7D&args[]=

**Comment by williamstein** [comment]
I was able to reproduce on the production site easily, but not on my cc-in-cc dev project...

**Comment by williamstein** [comment]
@johnjeng any ideas?

**Comment by DrXyzzy** [comment]
Maybe related:
1. Put a git clone command in your clipboard, e.g.  
`git clone https://github.com/astropy/astropy.git`.
1. Create a new project.
1. Immediately, while the project is starting, paste the git command into the mini terminal.
1. Session goes blank. Refreshing browser brings back CoCalc session.

**Comment by williamstein** [comment]
@DrXyzzy yep, that sounds like precisely the same bug...

**Comment by johnjeng** [comment]
My guess is that the callback to `webapp_client.exec` in `project_miniterm.cjsx` is being called with an error object with the keys `{code, errno, syscall, address, port}`. Potential fix #2474
