### ISSUE TITLE
Implement: "a new version is available" for the browser client

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2478]
I implement a "a new version is available" that is very unobtrusive.    I bet @haraldschilly  would know very well how to do this right.   It could be like with Chrome where it just shows a little "upgrade" icon in the upper right.   The client could periodically ping the **static** webserver for the latest version number and compare to what it has.     I would be against doing this before we added sessions functionality.  However, now that refreshing is almost painless, I think we should do it.

**Comment by haraldschilly** [comment]
Yes, that's not hard to detect. There is `SMC_GIT_REV`  in the webapp, e.g. see `r_misc`, and on the server there is https://cocalc.com/static/assets.json containing this revision version in the metadata. 

I think `.json` files are served with the default caching headers in nginx on kucalc, but that's easy to fix.
