### ISSUE TITLE
sometimes two email verification emails go out.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2507]
First time I tried it in ws1, I got two identical email verification emails (same token):

![screenshot 2017-11-19 at 10 30 11 am](https://user-images.githubusercontent.com/1276278/32994226-ec5e8592-cd18-11e7-9563-30033093a310.png)

**Comment by haraldschilly** [comment]
PR https://github.com/sagemathinc/cocalc/pull/4346 addressed the problem of sending out two emails via the api. it didn't handle the situation where the api is being called twice or more.
