### ISSUE TITLE
fix a misc collection of subtle style issues that make cocalc.com look unprofessional

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2510]
- [x] login/password fields overlap: (if 1password plugin -- also,  the width of the email/password/button fields aren't the same, either. col-xs-5, col-xs-5 and col-xs-2)
- [ ] The project title button text is about 1-2px higher than the Account/CoCalc/Help text.
- [ ] If screen is skinny then project tabs look horrible
- [x] hide labels of Account/CoCalc/Help/Projects when screen skinny
- [ ] points out: "click student must pay checkbox in course and watch the fireworks".
- [x] divider bars look unpro because they are excessively noisy and could simply have less lines/rounding.   (@ws/@j3 -- bars look ok, but not the rounded corners...)
- [x] excessive rounded corners meeting other elements.
 (also css `.webapp-editor-html-md-preview`, `webapp-editor-html-md-resize-bar`, ...)
- [x] "Drag and drop files." (should be no period)
- [x] in project settings (and everywhere), the capitalization of headings is wildly inconsistent.  Let's make it so the first letter is capital and the rest is lower.
- [ ] Help dialog: reword the help questions in some cases to sound more professional.
- [x] issues with CSS during page load

**Comment by williamstein** [comment]
(at least they overlap on chrome on a chromebook at default zoom; maybe not on something else...)

**Comment by haraldschilly** [comment]
what I saw after rollout of the first commit above, mostly title-case wordings

* [ ] account settings/preferences: editor vs. terminal box titles: they should have the same wording in the parents (maybe improve it in some way?) and be either gray or black. not mixed.
* [ ] account/subscriptions: "Add Payment Method..." button in title-case? same for "Add Subscription..."
* [ ] pricing page and hence account/upgrades: intro title: "Shared Resources"
* [ ] account/ssh keys: button "Add SSH Key" (maybe the rule is to title case buttons? I don't think so) 
* [ ] r_help/software section: "Software and Programming Libraries Details"
* [ ] project settings: "Idle Timeout", "CPU Usage", "Restart Sage Worksheet Server" button (where, Sage → SageMath)
* [ ] project settings/Hide or delete project box: both buttons
* [ ] project settings/ssh keys: button there says "Add and SSH Key" (different from account/ssh keys)

**Comment by williamstein** [comment]
Regarding the "horrible CSS flicker", I think this is caused by react-bootstrap.  I'm putting this in our pug header for now, since it eliminates it.  I hope it doesn't cause problems:
```
link(rel="stylesheet", href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u",crossOrigin="anonymous")
```

**Comment by slel** [comment]
- [ ] in the default project description for course shared projects,
  the second line is "---", which is interpreted as a markdown instruction
  for a header, and makes the description of course shared projects
  jump out to the eye in the Projects list view when one logs in to CoCalc.

  Specifically, the default description is
  ```
  No description
  ---
  This project is shared with all students.
  ```

  Maybe replace it with
  ```
  Course shared project for the course "Name of the course".
  This project is shared with all students and instructors in the course.
  ```

**Comment by williamstein** [comment]
Nothing in a long time.  Make new focused issues.
