### ISSUE TITLE
jupyter "Fetch additional output" button can get stuck

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2514]
1. Execute the following cell in modern Jupyter with Anaconda 3 kernel but do not click `Fetch additional output`:
    ```
    for n in range(500):
        print("fjaklfjdajfadkajfkdakjfakljdka;jdkj;fkdlaf;ajdkfja")
    ```
1. Change "500" to "501".
1. Click `Fetch additional output`. Nothing happens.
1. Button is usable again if cell is executed.

Shouldn't the button be removed when cell input is changed?

**Comment by haraldschilly** [comment]
I found a strange variant of that. Put this into a cell:

```
t = ''
for i in range(300):
    t += '\n{} 0.80874704, -1.33684689, -1.1773399 ,  0.7004631 ,  0.58144061,'.format(i)
print(t)
```

the button shows up, and when clicked should reveal the lines. I tested python2, sagemath, and anaconda5, where this works fine. But in python3, however, the button isn't doing anything.

**Comment by haraldschilly** [comment]
Testing @DrXyzzy example in these 4 kernels: with python2, python3 and anaconda5 the button does **not** do anything, while it works fine in sagemath.

**Comment by slel** [comment]
Could this have to do with whether the underlying Jupyter Notebook server
is Python2-based or Python3-based?

Python3 has trouble with very long lines containing many methods, see

- [Python issue 32758](https://bugs.python.org/issue32758)

**Comment by williamstein** [comment]
>  But in python3, however, the button isn't doing anything.

It works fine for me now.   

However, the original bug in the description at the top is still here!

**Comment by williamstein** [comment]
I can't reproduce any of these bugs now.  Yeah!
