### ISSUE TITLE
cocalc-jupyter: some special characters for clearing the output of stdout/stderr are not working

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2520]
Example: there is a library called [tqdm](https://github.com/tqdm/tqdm). It wraps an iterable and plots progress bars. However, it uses some special characters to clear the output string, such that it looks like as if the progress bar is progressing. 

Code:

```
from tqdm import tqdm
data = range(100)
x = tqdm(iterable = data, total=len(data))

from time import sleep
s = 0
for i in x:
    s += i
    sleep(0.05)
```

Screenshots:

classic:

![tqdm-jupyter-classic](https://user-images.githubusercontent.com/207405/33188117-6d21abec-d097-11e7-84c2-2ebdcbc4b1a7.png)

jupyter2:

![tqdm-jupyter2](https://user-images.githubusercontent.com/207405/33188120-72e2e6fe-d097-11e7-8827-e6e38930837b.png)

---

Interesting detail: the classical notebook has this in the ipynb json:

```
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 100/100 [00:05<00:00, 18.59it/s]\n"
     ]
    }
   ],
```

while jupyter2 is explicit about each and every output:

```
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\r  1%|          | 1/100 [00:00<00:10,  9.02it/s]"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\r  3%|▎         | 3/100 [00:00<00:09, 10.77it/s]"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\r  5%|▌         | 5/100 [00:00<00:07, 12.47it/s]"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\r  7%|▋         | 7/100 [00:00<00:06, 14.02it/s]"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\r  9%|▉         | 9/100 [00:00<00:05, 15.36it/s]"
     ]
    },
    {
[... many more until 100% ...]
```

---

This makes me wonder, if there is some special-case handling in jupyter for these types of characters. I.e. that a new message does delete all previous ones?

**Comment by kevinywlui** [comment]
This bug makes tensorflow somewhat annoying to use within cocalc since progress bars are shown whenever you train a model. For example, in this notebook: https://www.tensorflow.org/tutorials/keras/classification

**Comment by haraldschilly** [comment]
yes, I also find that very annoying. I looked into this when I reported it, but I don't know enough about how jupyter works in cocalc to fix this. Sorry.

**Comment by williamstein** [comment]
> This makes me wonder, if there is some special-case handling in jupyter for these types of characters. I.e. that a new message does delete all previous ones?

It must be.  Since this is a significant compatibility issue between jupyter classic and cocalc-jupyter, I'll prioritize it more highly.    

Is there a simplest-possible-example that illustrates the issue?   If somebody could provide that, then I could probably fix this bug more quickly.

**Comment by kevinywlui** [comment]
I think I figured out the difference in the tensorflow example. I haven't figured out the difference in the tqdm example.

![image](https://user-images.githubusercontent.com/1445341/66273570-e7b1c080-e829-11e9-97fe-b490f627649a.png)

It turns out the boxes are backspace characters which jupyter classic and cocalc-jupyter handles differently, for example,
```
print('ab\b')
```

**Comment by kevinywlui** [comment]
For tqdm, I think the difference is how `\r` is handled. For example, try
```
print('a\rb')
```

**Comment by williamstein** [comment]
Note that Jupyter's support for \b is really weird and different than the command line terminal, and is arguably buggy:  https://stackoverflow.com/questions/55440152/multiple-b-doesnt-work-as-expected-in-jupyter

Fortunately handling of \r is consistent in command line python and Jupyter classic/JupyterLab.  I don't personally necessarily agree that this interpretation makes sense, but obviously I should implement it for consistency.

**Comment by williamstein** [comment]
ansi-to-react (from the nteract project) solves our problem for \r, which is enough for me.  When or if they deal with \b then that would also get automatically solved in cocalc.  I'm going to fix this just for \r and close this issue, since that solves the progress bar problem.
