### ISSUE TITLE
Global option: absolute timestamps

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#2521]
In various places in CoCalc (e.g., the "last modified" column in a file view, or the "due" column in a task list, or in TimeTravel) timestamps are displayed relative to the present (e.g., "about a week from now"). This is often the most useful point of view, but there are times when I would prefer an absolute display (dates and times). In some cases I can get this in another way (e.g., for a file list I can switch to a terminal and run ls), but it would be nice to have a global setting to tell CoCalc to switch from relative to absolute display of timestamps (leaving relative as the default).

**Comment by williamstein** [comment]
In most cases if you hover the mouse of the TimeAgo widget, it will show the absolute timestamp in a hover tip that appears.    Tasks isn't like this, since it still hasn't been rewritten in react, but almost everything else has been.

**Comment by kedlaya** [comment]
That is useful to know, but there are still use cases where I would like to be able to see all of the absolute times at once, without doing the mouseover.

Real example I have in mind: at the end of my course this winter, I need to write a report to justify the course relief I've been promised for curriculum development (yay!). In order to write that, I'd like to be able to open up my to-do list and look to see what got done when, but with real dates rather than relative measurements.

**Comment by williamstein** [comment]
Now half-done, but only for react.   "(This toggle does not work yet for some views, e.g., TimeTravel and task lists.)"

**Comment by kedlaya** [comment]
Great! If there is a separate open ticket for finishing the conversion to react, then you should treat this as solved and close the ticket.

**Comment by williamstein** [comment]
Yep:

 - https://github.com/sagemathinc/cocalc/issues/583
- https://github.com/sagemathinc/cocalc/issues/2525

**Comment by slel** [comment]
Follow-up at #3358: add option to display ISO-8601-compliant datestamps.
