### ISSUE TITLE
latex preview lists only an incomplete list of preview pages

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2534]
This is a bit hard to explain, but it is definitely a bug drastically reducing the overall usability:

Consider you have a multi page long latex document (e.g. 20 for a presentation). Then, when it renders the image-preview, it is supposed to show all 20 pages and renders the visible ones with a low resolution image and then replaces them with a high resolution image. 

The problem is, sometimes it only loads the first 3 pages. The remaining 17 aren't there, so you can't scroll down. Interestingly, after 1-2 secs, the 4th page shows up (in full resolution), then, after scrolling down again, the 5th, and so on.

Toggling the "build" preview or closing&reopening the tab could fix this. Also, sometimes I wasn't even able to replicate it. Hence "heisenbug".

It's also rather new, because I know for sure that 3 or 4 weeks ago this did work all fine. 

my suspicion is that the underlying command for computing the total number of pages has changed, or there is some issue with updating some status.

**Comment by haraldschilly** [comment]
some thoughts

* the pdfinfo command is alright
* the preview window is initialized twice, which isn't good. i.e. LatexEditor → init PNG_Preview. and then shortly afterwards, again LatexEditor → init PNG_Preview.
* that's why I think the updates no longer really match, e.g. it changes from num_pages 20 to 0 again, etc.

also, once the document is edited, the compilation goes through and in the end triggers an update, it number of pages is fine again. 

so, why is there this duplicate initialization?

**Comment by williamstein** [comment]
We should rewrite this damned editor in React.

**Comment by williamstein** [comment]
I did rewrite it in react, and also react-virtuoso.  I'm sure this is long since fixed.
