### ISSUE TITLE
large matrices in sage worksheets should print how to see their str repr but don't

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2536]
sage in a terminal *and* jupyter both work fine.  But in sage worksheets, doing this does not explain how to actually see the matrix:
```
matrix(QQ,24,25)
---
24 x 25 dense matrix over Rational Field
```

Examples here:  

- Jupyter is fine: https://cocalc.com/share/4a5f0542-5873-4eed-a85c-a18c706e8bcd/support/2017-11-29-matrix-print.ipynb?viewer=share

- Sagews is not: https://cocalc.com/share/4a5f0542-5873-4eed-a85c-a18c706e8bcd/support/2017-11-29-matrix-print.sagews?viewer=share

**Comment by williamstein** [comment]
@DrXyzzy maybe the sort of thing you would be interested in...

**Comment by DrXyzzy** [comment]
I've started investigating. Seems to involve sage pretty_print, possibly `sage/src/sage/repl/display/fancy_repr.py:LargeMatrixHelpRepr` and toplevel().

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.

https://github.com/sagemathinc/cocalc/issues/6374 will be based on the existing sage kernel so should just automatically solve this.
