### ISSUE TITLE
courses: peer grading isn't robust enough

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2544]

**Comment by williamstein** [comment]
@haraldschilly -- please add minimal reproduce directions!

**Comment by haraldschilly** [comment]
Here is a screencast, which is my second attempt to reproduce this. It failed in both cases, but I only recorded the second one.

Setup: empty directory, 4 students, 1:1 peer grading, all student projects were already running.

Screencast: https://cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/peer-grading-robustness-20180315.webm?viewer=share

After the error appears, I show that one of the previous peer assignments must have failed to complete. Repeating the failed one does the trick, student gets the files and collecting works.

**Comment by williamstein** [comment]
Now fixed -- it's my commit after merging john's course typescript rewrite. Basically I hit exactly this when testing his rewrite, then I used **course timetravel** to reset the course to the step before it happened, and could then very easily reproduce it over and over.  Putting in console.log's made everything clear.
