### ISSUE TITLE
in jupyter, clicking from formatted markdown cell to code cell unformats the markdown

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2547]
Tested in new modern notebook with Python 3 (Anaconda) kernel:

1. Create this notebook.
```
--- first cell is markdown
# TEST
--- second cell is code
x = 99
x
```
2. Run both cells.
3. Click in first cell. It stays formatted.
4. Click in second cell. First cell is unformatted.

**Comment by DrXyzzy** [comment]
After browser refresh, it looks as if step 4 above no longer causes the first cell to be unformatted, but now I see:

5. Click back in first cell and it is unformatted. With classic notebook, I would have to double-click at this point to unformat the first cell (i.e. put it into edit mode).

**Comment by williamstein** [comment]
I cannot reproduce your 5.   It's completely fixed for me.  Are you sure?  Maybe you accidentally double clicked?     If you're certain make a new ticket with clear steps starting at 1 to reproduce the problem.
