### ISSUE TITLE
in jupyter with vim binding, clicking on formatted markdown cell sometimes unformats

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2555]
See also #2547.

This issue appears when editor keyboard bindings setting is `Vim`. Does not appear with `Standard` bindings. So maybe this is a feature and not a bug?

1. In new modern notebook with Python 3 (Anaconda) kernel. Create this notebook.
```
--- first cell is markdown
# TEST
--- second cell is code
x = 99
x
```
2. Run both cells.
3. Click in first cell. It stays formatted.
4. Click in second cell. It stays formatted.
5. Click back in first cell and it is unformatted. 

Files were closed and reopened during testing after each keyboard binding change.

**Comment by williamstein** [comment]
I don't know what the vim-mode behavior of official jupyter is like.  You might want to try testing that somehow.

**Comment by williamstein** [comment]
That said, this seems like undesirable behavior as is (what you describe).

**Comment by DrXyzzy** [comment]
I don't think standard Jupyter has a Vim mode. Switching CoCalc notebooks above to classical makes Vim bindings unavailable. I did see a Jupyter extension to add Vim bindings [here](https://github.com/lambdalisue/jupyter-vim-binding), but it appears to be unmaintained.

Might make sense to close and label this `wontfix`, because of vanishing returns and the weirdness of Jupyter + Vim anyway (3 keyboard modes, as pointed out in README.md at link above).

**Comment by williamstein** [comment]
I can't reproduce this.
