### ISSUE TITLE
Support using asymptote with CoCalc Jupyter2

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2571]
REQUESTED BY: Stefan Lukits

**Comment by DrXyzzy** [comment]
sagews `%asy` mode code might help; see around L1675 in [sage_salvus.py](https://github.com/sagemathinc/cocalc/blob/master/src/smc_sagews/smc_sagews/sage_salvus.py#L1675)

**Comment by williamstein** [comment]
I think this is a request to support 

https://github.com/jrjohansson/ipython-asymptote

which hasn't been touched in a decade, and was an extension for jupyter classic.  So closing.
