### ISSUE TITLE
hub tests: unexpected prefix FATAL

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2575]
many fail in the way shown below. must be related to 90593c24b7123687421b74076fc650343c6d9cdb

```
       Error: Expected 'FATAL: no anonymous set queries' to equal 'no anonymous set queries'
      + expected - actual
 
      -FATAL: no anonymous set queries
      +no anonymous set queries
```

**Comment by haraldschilly** [comment]
@DrXyzzy this is something I'm assigning to you. Looks sort of straightforward. There might be some tests that are really broken in between, I don't know. A few weeks ago all of them did pass, so I'm confident this can be brought up to :100: % again!

I don't know about the status for the hub api tests. Maybe worth a check, too.

**Comment by williamstein** [comment]
This is my fault -- I added "FATAL: " to the beginning of some of the errors, but didn't update tests.  But @DrXyzzy could fix them (by changing the tests).

**Comment by DrXyzzy** [comment]
working on that now

**Comment by DrXyzzy** [comment]
Done.
