### ISSUE TITLE
taking a long time to 2-factor login when using the authenticated login redirect doesn't work (used by juno)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2581]
(This is probably explained only clearly enough for me (william) to understand...)

The first time I tested Juno adding cocalc it took a while since I had to sign into google, type in my 2-factor, etc., so I signed in fine, but the mini browser just showed normal cocalc.  I then just closed and reopened it and it worked fine the second time.    To reproduce:

1. Sign in with SSO and just take a LONG time
2. End up in normal cocalc rather than at the auth_token url.

**Comment by navoshta** [comment]
This is also reproducible on desktop:

**Expected**
1. Open https://cocalc.com/app?get_api_key=appname
2. Try signing in with SSO
3. Note redirect to `https://authenticated/?api_key=...` URL where desktop browser would typically display an error.

**Actual**
1. Open https://cocalc.com/app?get_api_key=appname
2. Try signing in with SSO, waiting for 10-15 minutes before completing the sign-in process
3. There is no redirect to `https://authenticated/?api_key=...`, instead page loads usual CoCalc interface.

**Comment by williamstein** [comment]
This is caused by the line
```
 cookies.set(api_key_cookie_name(base_url), req.query.get_api_key, {maxAge:60*1000})
```
in [auth.coffee](https://github.com/sagemathinc/cocalc/blob/master/src/smc-hub/auth.coffee#L411).

Thus waiting greater than 1 minute should be enough to replicate this.

Not sure how to deal with this.    I could just raise the limit to 10 minutes (say), but then any attempt for this user to login  up to 10 minutes with this particular browser (and its cookies) would redirect them.  Maybe that is fine?

**Comment by navoshta** [comment]
Redirect where? Although it should be OK I think, as we clear website data storage every time we show the login screen.

**Comment by williamstein** [comment]
I can make the cookie age a query param, so you can set it however you want -- it can default to 1m (say), but you could set it to an hour if you want for your application...

**Comment by williamstein** [comment]
Fix will be live in a few minutes...

**Comment by williamstein** [comment]
The fix is just that the timeout is now 30minutes instead of 1m.  I implemented a customizable timeout, but it is clearly not needed and just makes the code complicated, so I deleted that.
