### ISSUE TITLE
sometimes when saving a jupyter notebook, images are not saved

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2598]
From Harald:

So, I from my POV this is getting more random than ever. I can confirm this "restart project" issue, but not all the time. I also refreshed the webapp client in between restart the project, and maybe it also makes a difference if I open the file via the "open" command or click on the file in the "files" listing.

Also, even with these timestamps:

-rw-------  1 user user  643 2017-12-21 13:31:02.380857657 +0000 .save-plots.ipynb.sage-jupyter2
-rw-------  1 user user 1.2K 2017-12-21 13:31:02.388858275 +0000 save-plots.ipynb
and then clicking to open the file the plot disappears.

---

From: Stuart Littlefair
Yesterday 11:43
 
Many thanks for investigating this issue.

I've done my own investigation, and the disappearing images is related to project server restarts, rather than collection or saving. I create the issue with the following steps:

1. Open and run the cells in the notebook below.

https://cocalc.com/projects/e98bae95-28c7-4ac6-92bf-bbc7d88d6074/files/jottings.ipynb?session=default

2. Save file - file size in browser changes from ~1.5KB to 45kB.

3. Close and Halt notebook.

4. Restart project server.

5. Open notebook.

The image has disappeared from the notebook. Since some time elapses between students saving their work and me marking, I believe this explains any issues I found above. Image should persist between project restarts, shouldn't they?

Stuart

**Comment by williamstein** [comment]
I'll either fix whatever the bug is, or fundamentally re-architect how images work to fix this robustly.

**Comment by williamstein** [comment]
When fixed, contact: Tania R Allard

**Comment by williamstein** [comment]
I'm now seriously working on implementing a fix for this.  It's unfortunately a full 2-day project to do...

**Comment by williamstein** [comment]
I've made it so closing a tab and also "Close and Halt" both also save to disk, and made the autosave interval on the backend be 45s.  I consider this sufficient to properly address this issue and am closing it.

**Comment by williamstein** [comment]
It turns out, based on user feedback, that this was *clearly* not sufficient.  We will implement an additional fallback, in case all else fails:

 - each time an image is created, push it to our central blob store (with some n days expire time)
 - if when saving to disk (or requesting to view) an image, only the sha1 is known but not the image itself, we pull it back from central blob store.

**Comment by williamstein** [comment]
When fixed contact: Gregory Way and Tania R Allard

**Comment by gwaygenomics** [comment]
Thanks @williamstein!

**Comment by williamstein** [comment]
I'm now making significant progress on this.  Basically fixed it very nicely via introducing a sqlite instance on the backend... but needs some more testing and refinement.
