### ISSUE TITLE
Upgrade to OCaml 4.07.0

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2605]
Upgrade from the currently installed OCaml 4.02.3, released 2015-07-27,
to OCaml 4.07.0, released 2018-07-10.

Refs:
- https://ocaml.org/releases/
- https://cocalc.com/doc/software-executables.html

**Comment by slel** [comment]
OCaml 4.07.0 was released.

**Comment by haraldschilly** [comment]
we have `4.08.1`
