### ISSUE TITLE
jupyter2: sometimes, the loading spinner doesn't stop

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2614]
I just noticed with the sage/R kernel, that the kernel loading spinner in the jupyter2 notebook continues to spin although it has already loaded. In particular, I can happily run `1+1` and see `2`. This then stops the spinner.

Running `sage-ir` in the console shows a few warnings, maybe that's the problem?

---

Well, tried it again with a freshly restarted project and it did work immediately. Added heisenbug, and let's keep this open and I'll add more insights if they occur to me over time.

**Comment by williamstein** [comment]
No more insight or reports of this.  Closing.
