### ISSUE TITLE
Need Help with a Matrix

### ISSUE THREAD

**Issue by ferbinius** [sagemathinc/cocalc#2623]
I uploadet 2 pictures of my issues Maybe someone can help me. 

https://www.dropbox.com/sh/myolvakqlyo8qtb/AAC7TSefyXD53pK-MCIPQdjna?dl=0

**Comment by haraldschilly** [comment]
Hello, the error clearly states that there is a syntax error. Apart from that, please either contact us via the help dialog (top right where it says "Help") or if you're part of a class, contact your teacher.

**Comment by ferbinius** [comment]
Could you say the right Syntax? Pls. I didn‘t know what i did wrong
