### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by ferbinius** [sagemathinc/cocalc#2624]
https://www.dropbox.com/sh/myolvakqlyo8qtb/AAC7TSefyXD53pK-MCIPQdjna?dl=0

Could someone help me please

**Comment by kcrisman** [comment]
This is not really a CoCalc issue, but a Python one.  You have several weird things.

1. You can't really do a nested for loop with `for i in range(0,5), j in range(0,5)` or whatever syntax you used.  See [here](http://sagecell.sagemath.org/?z=eJzLVLBVMODlygJSFrxcaflFCpkKmXkKRYl56akappo6ClkIrpmmFS-XAhAUFGXmlShk6mQBAOphEFw=&lang=sage), for example.

2. You can't return an equals sign, like `return C[i,j]=0`.  You can use the double equals for testing equality `return C[i,j]==0`, perhaps.

Anyway, I recommend a good Python tutorial, you will do well.  Good luck!

@haraldschilly you should close this.
