### ISSUE TITLE
switch from appear.in to something else for video chat (maybe configurable)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2625]
![screenshot 2018-01-08 at 9 12 11 am](https://user-images.githubusercontent.com/1276278/34682585-2d2f2ff6-f454-11e7-91fe-5eb70caa7978.png)

**Comment by williamstein** [comment]
And the amount they charge is WAY above our budget.

**Comment by slel** [comment]
Just stumbled on the "matrix.org" project which might give ideas:
- https://en.wikipedia.org/wiki/Matrix_(communication_protocol)
- https://matrix.org/
- https://matrix.org/docs/projects/try-matrix-now.html

**Comment by williamstein** [comment]
done, long ago. jitsi is great!
