### ISSUE TITLE
many unit tests for smc-hub/api are broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2627]
I'm using node8 in a cc-in-cc project:

```
../smc-hub$ npm run testapi
...
  84 passing (49s)
  16 failing
```
  
Obviously, be sure to do `npm install --dev` in smc-hub...

**Comment by haraldschilly** [comment]
this db92deba4fabbe52c8cb69f333fe388339f52b5b fixes the test for inviting collaborators

**Comment by haraldschilly** [comment]
Tests like that are completely broken. There is a module which can't be found:

```
Error: Cannot find module './failing-to-save'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/smc/src/smc-util/syncstring.coffee:62:21)
    at Object.<anonymous> (/home/user/smc/src/smc-util/syncstring.coffee:1:1)
[...]
```

**Comment by williamstein** [comment]
> There is a module which can't be found:

It's because it is in typescript now.

**Comment by haraldschilly** [comment]
I ran it today, and got 

```
  92 passing (2m)
  9 failing
```

Assigning @DrXyzzy and well, I think this tries to test too much. Maybe hub<->db are ok, maybe some aspects about projects, but those parts that are about sage and so on should be mocked. Although, of these 9 failing tests, some were about copying files between projects.

**Comment by williamstein** [comment]
We have CI now and all tests we have work regularly.
