### ISSUE TITLE
Write an editor for .lean files (the theorem prover)

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2634]
Requested by Thomas Hales (@thalesant).

See the github repo at
- https://github.com/leanprover/lean

**Comment by williamstein** [comment]
https://github.com/leanprover/lean

Even github has .lean file highlighting support...

**Comment by williamstein** [comment]
It seems that codemirror doesn't have this yet: https://codemirror.net/mode/index.html
so we will need to write it...

**Comment by slel** [comment]
Emacs lean mode and vscode lean mode:
https://github.com/leanprover/lean-mode
https://github.com/leanprover/vscode-lean
