### ISSUE TITLE
Install Coq

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2635]
Install Coq system-wide.

- home: https://coq.inria.fr/
- download: https://coq.inria.fr/download
- github: https://github.com/coq/coq/
- releases: https://github.com/coq/coq/releases/
- license (GNU LGPL 2.1): https://github.com/coq/coq/blob/master/LICENSE

**Comment by haraldschilly** [comment]
Hello, do you have an example how this can be used? Or, what exactly is the use case? One general problem is that this is a program with a graphical user interface. I don't really know how to run it from the command line...

**Comment by haraldschilly** [comment]
just to protocol this, something related to it is installed:

```
~$ coqc --version
The Coq Proof Assistant, version 8.4pl4 (November 2015)
compiled on Nov 04 2015 12:56:53 with OCaml 4.02.3
```

**Comment by jdchristensen** [comment]
The Proof General emacs interface to Coq seems to work fine, so unless @slel has another specific request, I'd say that this can be closed.

**Comment by slel** [comment]
No other request.

**Comment by haraldschilly** [comment]
Cool! I've an idea, would it be very tedious to write up a short intro how to use Coq via that "Proof Generals Emacs Interface" to put on our cocalc blog? Personally, I have no idea what this even is, and I suspect there could be some out there who might be interested in a little intro how to get started...

**Comment by jdchristensen** [comment]
Most people who use Coq do so through the emacs interface, so there isn't really anything specific to Cocalc to mention here.  Any tutorial about using Coq via Proof General will apply, e.g.

https://coq.inria.fr/tutorial-nahas

**Comment by slel** [comment]
Further discussion at #2867.
