### ISSUE TITLE
classical jupyter notebook mode: close and halt doesn't work well

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2650]
When running a "classical jupyter notebook" in the webapp, there is a problem with "close and halt" in the menu. I think it stops the kernel, or at least attempts to, but it doesn't close the tab.

Maybe the best overall solution of this is to actually get rid of that mode, or redesign it in a way such that it is "more vanilla".

**Comment by williamstein** [comment]
We should just eliminate the menu option... via monkey patching it out.

**Comment by williamstein** [comment]
I can confirm that:

- jupyter classic in an iframe with RTC in cocalc does still exist and work, amazingly.
- the issue you describe here is still a problem; indeed the tab doesn't close.
- and I have zero interest in every fixing this.

**Comment by williamstein** [comment]
I.e., it's hard to justify maintaining and supporting jupyter classic, when it is completely deprecated by the jupyter classic devs.

**Comment by williamstein** [comment]
Jupyter classic is deprecated.  Closing this.
