### ISSUE TITLE
CoCalc Jupyter display Python results in Markdown

### ISSUE THREAD

**Issue by profbrady** [sagemathinc/cocalc#2651]
There is already an extension for showing Python results in Markdown cells. It would be nice to have the same functionality in CoCalc Jupyter. The extension requires `{{x}}` to display the value associated with the name `x`. Obviously `x`would need to be assigned before the Markdown cell is rendered for this to work.

**Comment by williamstein** [comment]
Can you link to the extension? There are a lot of potential design choices, and I would want to make them the same way...

**Comment by williamstein** [comment]
Too vague and not enough interest.

A possibly neat approach though would be to make it so the code execution in markdown (which we now have) used the same kernel as the notebook itself. That is doable... and would partly address this, maybe.
