### ISSUE TITLE
3d plot in jupyter notebook with sage kernel is truncated

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2662]
Try:
```
var('x,y')
plot3d(x^2+y^2, (x,-2,2),(y,-2,2))
```
![plt-trunc](https://user-images.githubusercontent.com/528072/35425017-58b1fc0e-021d-11e8-9efa-bab1f21f9852.png)

Thanks to Kiran Kedlaya for reporting this problem.

**Comment by DrXyzzy** [comment]
Also reported by Ingo Dahn.

**Comment by DrXyzzy** [comment]
Workaround is to zoom by using secondary drag (right mouse button drag, or two finger trackpad drag, etc. depending on your device setup) with up and down motion.

**Comment by williamstein** [comment]
Current renderer is completely different and doesn't have this problem:

<img width="1592" alt="image" src="https://github.com/user-attachments/assets/e880c09b-fef5-4bfd-80c3-7ce86e745297">
