### ISSUE TITLE
Jupyter Widgets not working

### ISSUE THREAD

**Issue by Newmsy** [sagemathinc/cocalc#2667]
Do I need to move from an unpaid server to ensure they work? I get this:
Failed to display Jupyter Widget of type HBox.

If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions.

If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.

**Comment by haraldschilly** [comment]
switch to classical, or the standalone server. see https://github.com/sagemathinc/cocalc/wiki/JupyterClassicModern
