### ISSUE TITLE
in jupyter with vim binding, cursor disappears after tab completion and focus is lost after selection

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2668]
1. Set `Account / Editor keyboard bindings` to `vim`.
1. Open jupyter notebook with Python 3 (Ubuntu) kernel.
1. In a new code cell, insert `[1].` and press [tab], then accept `append` as completion.
1. Note that cursor is gone.

See #2555 for another jupyter/vim issue.

**Comment by DrXyzzy** [comment]
Also, reported by Alex Rasstriguine:

After display of completion window, when a completion choice is made, focus seems removed from the current cell, i.e. you have to click in the cell again to resume editing.

**Comment by williamstein** [comment]
now fixed.
