### ISSUE TITLE
Support for ipywidgets in CoCalc Jupyter

### ISSUE THREAD

**Issue by profbrady** [sagemathinc/cocalc#2670]
Would be nice to be able to add ipywidgets to notebooks. I especially would like to add quick questions in assignment notebooks that feature interactivity using buttons, drop down lists, etc. Plus the ability to create interactive plots.

**Comment by williamstein** [comment]
Yes, I definitely need to implement this.  It's #1934.  For now you have to use either a Sage worksheet or Jupyter classic.
