### ISSUE TITLE
expose a version of used upgrades via our api (see https://cocalc.com/settings/upgrades?session=default) 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2672]
REQUESTED BY: Minerva

We wrote code that computes the data for this picture:

![screenshot 2018-01-30 at 3 46 18 pm](https://user-images.githubusercontent.com/1276278/35597733-bbcd4e96-05d4-11e8-8675-5fea92e8b948.png)

Expose that via the API.

**Comment by DrXyzzy** [comment]
Implementation: @ws commit 55ce8f5fb755a35. Will test.

**Comment by DrXyzzy** [comment]
Manual tests passed using bash (curl) and python scripts. Updated api.html in #2688.
