### ISSUE TITLE
Viewing Jupyter notebook TimeTravel with macOS Safari, file appears empty

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2675]
On macOS 10.12.6, Safari 10.1.2, clicking TimeTravel on an open .ipynb shows an empty file. Version scrubber bar at the top is still there and seems to work normally.

Problem does not appear with Safari on iPad with iOS 11.2.5.

To do: I will update macOS and test again. There is an update available, but I need to run backups first.

**Comment by williamstein** [comment]
Of course this works fine today:

<img width="1320" alt="image" src="https://github.com/user-attachments/assets/4017413a-1317-4c82-acdd-68bf97797199">
