### ISSUE TITLE
timetravel with load history and changes view compares wrong versions

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2678]
User report with .tex file with long history - thanks Robert Brijder for reporting this
1. open timetravel view
1. load all history
1. click changes
1. higher version in comparison is the last number from view before history is loaded

**Comment by DrXyzzy** [comment]
Here's a .tex file with enough history to show the problem.

https://cocalc.com/projects/d564a8b2-3c57-4d64-986f-791fcb6df773/files/WEEM41/.ExploringData.tex.sage-history?session=default

Problem also verified with .md and .sagews files.

**Comment by DrXyzzy** [comment]
Workaround: Click `Changes` first, then click `Load All History`. Slider bar expands to show two handles at revisions `n/2` and `n`, where `n` is the highest revision number shown before loading history. Handles can then travel the full range of versions.

TimeTravel slider before clicking `Changes` or `Load All History`:

![before-clicks](https://user-images.githubusercontent.com/528072/35695513-59aa6646-074a-11e8-922d-d26aa8a78070.png)

TimeTravel slider after clicking `Changes` then `Load All History`:

![after-c-then-l](https://user-images.githubusercontent.com/528072/35695521-623e0358-074a-11e8-9ad4-f674390c3302.png)

**Comment by williamstein** [comment]
Changes works fine after doing load all now.  The version number instability does mean that the range starts out in a weird place, which is related to https://github.com/sagemathinc/cocalc/issues/2679
