### ISSUE TITLE
Limit which collaborators on a course become collaborators on student projects

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#2680]
My CoCalc course has both TAs, who I'd like to have the same access to the course projects as I do, and a grader, who should *only* have access to the master course project but not to the individual student projects. Would it be possible to have an option in the course file to specify which collaborators on the course project should be forwarded to the student projects? The default would be all of them, as in the current behavior.

**Comment by williamstein** [comment]
Yes, this is a great idea, and would be easy to implement.

**Comment by novoselt** [comment]
I'll close this as stale and not exactly easy to implement.

In the current security/collaboration model anybody who has write access to some file, e.g. for entering grades, must be a collaborator on the project. This collaborator can then adjust course configuration and get added to student projects, if desired. So having this extra list for a subset of collaborators will not really protect students accounts from access by other collaborators. It may be a nice feature for an honour system, but then one can also instruct the grader not to look into students projects.
