### ISSUE TITLE
jupyter2: tab completion duplication

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2685]
I'm not sure if this was ever reported, or maybe it's just me noticing this? When I tab-complete in jupyter, I see all entries listed twice.  Attached is a screenshot. It also happens when completing a partially typed in attribute.

![cocalc-jupyter2-duplicate-tab-completion](https://user-images.githubusercontent.com/207405/35766268-56ed9f04-08d5-11e8-8979-a6f61cf0dcb7.png)

**Comment by jasongrout** [comment]
There have been reports of similar things in Jupyter...IIRC it was related to the kernel. You might first check to see if the kernel is giving duplicates.

**Comment by williamstein** [comment]
@jasongrout's right - this might be kernel specific.  I don't see it with the anaconda3 kernel:

![screenshot 2018-02-04 at 8 50 11 am](https://user-images.githubusercontent.com/1276278/35779842-7c65aae8-0988-11e8-9f57-2fa67af4c3d6.png)

**Comment by haraldschilly** [comment]
I found the upstream issue: https://github.com/ipython/ipython/pull/10969

**Comment by williamstein** [comment]
We can still workaround this by making the function `complete` on line 579 (right now) of src/smc-project/jupyter/jupyter.coffee a little more complicated, by making it dedup what it gets.  This will require:

(1) understanding the format of the output,
(2) changing it.

Doing this on the backend is the way to go, to avoid extra network traffic entirely.  Want to give it a shot.  Just modify that function in your dev project, and do "restart project"...

**Comment by williamstein** [comment]
I forgot about this ticket, but did implement a workaround as indicated above anyways, in some code that looks like this:
```
    // For some reason, sometimes complete.matches are not unique, which is annoying/confusing,
    // and breaks an assumption in our react code too.
    complete.matches = Array.from(new Set(complete.matches)).sort();
```
in jupyter/actions.ts.
