### ISSUE TITLE
course: implement skipping steps for peer grading (not yet implemented)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2695]
There is a button for skipping steps in courses. For peer grading, it has weird behavior. What is the supposed outcome of skipping a step here?  Below is a screenshot showing there is no next step when skipping. (also, similar observations for assign and collecting peer grading)

![cocalc-skip-collecting-peer-grading](https://user-images.githubusercontent.com/207405/36037320-b96f2472-0dbc-11e8-987e-86eef80ef650.png)

**Comment by williamstein** [comment]
It is not implemented for peer grading.  That's why the button says "Please disable this".  It doesn't work.   I thought it was clearer than just mysteriously greying it out. 

Probably the right ticket would be "implement skipping parts of the peer grading steps".

**Comment by haraldschilly** [comment]
ahh! that text didn't ring any bells in understanding it. ok ok. I see. yes.

**Comment by novoselt** [comment]
Closing as stale, we can open a new issue if there will be demand.
