### ISSUE TITLE
cocalc jupyter improvement: add nbtutor support or similar

### ISSUE THREAD

**Issue by profbrady** [sagemathinc/cocalc#2696]
I am using CoCalc Jupyter notebooks to teach a course in computing for engineering technology students. I am using Anaconda Python 3. Some are having trouble visualizing how loops and conditionals are or will work. It would be great if nbtutor support could be baked in to CoCalc Jupyter.

See https://github.com/lgpage/nbtutor

This would be helpful while teaching (would not have to leave CoCalc to use something like PythonTutor) and students could use it while developing answers to assigned problems.

**Comment by slel** [comment]
Until this exists system-wide, you might be able to install it as a user
(from there it should be easy to propagate to a class), and then take
advantage of it using "Classic Jupyter" in CoCalc.
See an example of installing an extra kernel for Jupyter, as a user:
https://cocalc.com/share/4711033a-b5d8-4fb3-9708-e9019ba1c158/Install-xeus-cling-in-CoCalc-project.md?viewer=share
Hoping to find time to explore this nbtutor issue in the coming days
unless someone beats me to it.

**Comment by williamstein** [comment]
Out of scope and no other demand.
