### ISSUE TITLE
Truncating Tasks

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#2703]
Start with a task like this:
<img width="388" alt="screen shot 2018-02-12 at 2 26 41 pm" src="https://user-images.githubusercontent.com/618575/36123218-d3fd3ca2-1000-11e8-9932-ab07d9f6a491.png">

Make sure it's toggled close:
<img width="349" alt="screen shot 2018-02-12 at 2 26 49 pm" src="https://user-images.githubusercontent.com/618575/36123217-d3e3887a-1000-11e8-9f74-068845ccc1ee.png">

Check the box: (notice the toggle is gone)
<img width="354" alt="screen shot 2018-02-12 at 2 26 56 pm" src="https://user-images.githubusercontent.com/618575/36123215-d3ccc266-1000-11e8-9465-fddbcc7f97f5.png">

Oh no! It's actually missing.
<img width="454" alt="screen shot 2018-02-12 at 2 27 03 pm" src="https://user-images.githubusercontent.com/618575/36123214-d3aba14e-1000-11e8-8d3a-ff4a893ddf53.png">

**Comment by williamstein** [comment]
Oops -- that makes perfect sense now that I think about it.  thanks for reporting this.
