### ISSUE TITLE
jupyter2: wrong ending for exporting R kernel notebooks to an executable file

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2711]
1. open an ipynb file in modern jupyter
2. select R kernel
3. file → download → executable script mentions `.txt` as it's ending. 

Actually: it is `.r`

File is saved correctly, so that's a pure UI issue.

**Comment by williamstein** [comment]
It just says "Executable Script" now, so fixed.  Oh, and it does work.

<img width="940" alt="image" src="https://github.com/user-attachments/assets/563b158a-d0c9-4b3b-ac80-3b55d34b7773">
