### ISSUE TITLE
course: lock an assignment from students after collecting it

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2712]
> can I delete, hide, or lock an assignment from students after collecting it. I don't want the test questions to leak out before every section has taken their test.

at the moment, this isn't possible. 

requested by prof. brady in support.

**Comment by slel** [comment]
Would re-assigning with an empty assignment overwrite the previous version?

**Comment by williamstein** [comment]
> Would re-assigning with an empty assignment overwrite the previous version?

No.  The closest you could do is replace all files by empty versions of themselves, assign, then do that again (touching all files).  The snapshots and TimeTravel versions of the files would still all be there though.

**Comment by novoselt** [comment]
The quoted problem has only two reliable solutions - simultaneous tests and different tests. Everything  else will have an easy possibility for cheating, by making a screenshot if nothing else.
