### ISSUE TITLE
in a course, selecting "skip assignment" should make it so collect all is enabled.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2714]
This screenshot shows what currently happens, which is of course not very useful since there is no "collect all" button:

![screenshot 2018-02-19 at 7 34 43 am](https://user-images.githubusercontent.com/1276278/36385477-88f2b484-1547-11e8-804c-71443aee8388.png)

**Comment by johnjeng** [comment]
Fixed by #2746.
