### ISSUE TITLE
add "jupyter lab" start button in project settings

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2715]
probably setup everything analogous to how it is setup for `cc-jupyter` ...

![screenshot from 2018-02-20 19-11-30](https://user-images.githubusercontent.com/207405/36441097-df990aec-1671-11e8-9cfb-2d318836a516.png)

**Comment by williamstein** [comment]
There is a script  `cc-jupyter` in smc_pyutil/.   It has a line starting `jupyter notebook...` in it.  If you change "notebook" to "lab", then jupyter lab starts instead.

Here's how I ran Jupyter lab in my project:

1. `pip install jupyterlab`
2. Type this: `jupyter lab --port-retries=0 --no-browser --NotebookApp.iopub_data_rate_limit=2000000 --NotebookApp.iopub_msg_rate_limit=50 --NotebookApp.mathjax_url=/static/mathjax/MathJax.js  --NotebookApp.base_url=/$COCALC_PROJECT_ID/port/4000/  --ip=192.168.141.7 --port=4000 --NotebookApp.token='' --NotebookApp.password=''` 
3. Visit https://cocalc.com/45f4aab5-7698-4ac8-9f63-9fd307401ad7/port/4000/, where of course you have to put the project_id...

**Comment by williamstein** [comment]
@haraldschilly  Can you install jupyterlab so it is available in the compute image, so this can move forward.?

**Comment by haraldschilly** [comment]
It's installed for quite a while now. I should check it's version and maybe update it, though.

```
$ which jupyter-lab
/usr/local/bin/jupyter-lab
```

```
$ jupyter lab --help | head
JupyterLab - An extensible computational environment for Jupyter.
 
This launches a Tornado based HTML Server that serves up an HTML5/Javascript
JupyterLab client....
```

**Comment by williamstein** [comment]
Cool -- thanks!  We should get this ticket done soon then...

**Comment by haraldschilly** [comment]
There is also this "juypter hub", and a connector (?) between lab and hub. I'll look into this. It shouldn't hurt to have the software available.
