### ISSUE TITLE
ipynb→pdf: show formulas in "Math" to facilitate correct pdf conversion.

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2726]
When a formula is displayed in an ipynb notebook in "sagemath" mode (maybe there are others, but I only looked at sagemath), it is wrapped in a way which is ignored by the nbconvert export filter when converted to PDF. The resulting PDF simply lacks the formula output.

But, when someone wraps the formula's latex code in a `Math` object, the conversion works!

So, the goal of this ticket is to investigate this and if possible, automatically wrap any such symbolic expression in `Math`.

Note, there is also this `%display latex` mode, which automatically wraps any output. In such a case, all output appears to be gone.

Attached is a screenshot, where one can see the missing output for the first command, while the second output is fine.

![cocalc-sagemath-formula-pdf](https://user-images.githubusercontent.com/207405/36947307-5882859e-1fca-11e8-928d-de03646e361a.png)

**Comment by haraldschilly** [comment]
... I added "upstream", because maybe that's actually something SageMath has to fix.

**Comment by williamstein** [comment]
This works fine now via latex export to pdf via nbconvert:

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/6c7ee304-be5d-422f-8066-38d558c995d2">

I think this was a dup of another issue, which was fixed upstream in 2020ish.
