### ISSUE TITLE
duplicate file shows trailing slash in log

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2728]
1. Duplicate a file.
2. See this: `William Stein copied work/2018-03-05-all-hands.md to work/2018-03-05-all-hands-1.md/ 3 minutes ago`

**Comment by haraldschilly** [comment]
maybe [this commit](https://github.com/sagemathinc/cocalc/commit/a2d29d5784b5908ae2e1511cf5439fc2c5403047) is relevant.
