### ISSUE TITLE
course: make it possible to search for student in an assignment and assignments in students

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2729]
![screenshot 2018-03-05 at 3 56 05 pm](https://user-images.githubusercontent.com/1276278/37006546-b949bd02-208d-11e8-9568-e8312b4af051.png)

Motivation: Is there a way to group/tag students?

Not exactly. However, in the course where it lists the students, you can edit their names, and this just impacts the instructors' view of their students. So just change the first or last name to also include the section.

You can then easily search (using Find students at the top) for students in a given section, and you'll see only those. However, that search only applies to all students -- you can't currently search for students from the assignment page, so this still might not be so useful.

We could fairly easily add an additional student search box on the assignment page, so when you enter something in both boxes you would only see the matching students for the matching assignments. Thoughts?

**Comment by williamstein** [comment]
REQUESTED BY: Alexei Gilchrist

**Comment by aalexei** [comment]
Changing the either the first of last name is not entirely private. It will change the name in the student's view of the project (the title for the project). This is more a cosmetic nuisance  than anything but it would be better if admin structures are not visible

**Comment by williamstein** [comment]
Better would be to introduce an additional field about the student, so  in addition to first/last/email here:

![screenshot 2018-03-05 at 3 49 08 pm](https://user-images.githubusercontent.com/1276278/37007237-302a74cc-2091-11e8-8936-167e2778691b.png)

there is also "Note: [      ]" and a statement that the note is private (but nothing else is).
