### ISSUE TITLE
Enable authors to insert code snippets into input cells

### ISSUE THREAD

**Issue by ingodahn** [sagemathinc/cocalc#2733]
It would be great if authors could define a collection of code snippets which are then represented in a menu. A click on a particular entry in this menu should insert the respective snippet, ideally after requesting important parameters through a form.

**Example:** 

 Educational materials become more efficient if they provide critical feedback to students. Automatically graded questions are one such form and I'd like to include them using iframes with snippets like
```
<iframe width="800" height="400" src="https://www.wamap.org/multiembedq.php?id=100000">
</iframe>
```
The author would have to edit the _id_ and possibly _width_ and _height_. It would be even better if the author would be presented a form to edit these parameters so that he doesn't have to edit the code. 

In a similar way the author could embed YouTube videos or Geogebra animations with the required additional license information

**Comment by williamstein** [comment]
too vague, but maybe this idea will come up again in the form of templates...
