### ISSUE TITLE
make drag and drop of images to chat rename the file by putting a timestamp at the end to avoid issues with duplicates

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2734]
I just drag and droppped an image into chat named 2018.svg,... and see that it gets named `.chat-images/2018.svg`.  This is kind of very bad, IMHO, since what if there is already an image with the same name in .chat-images...?  Then it would get overwritten.  Very confusing/dangerous.  I just tried uploading a png to github, and Github renamed it `37127627-75fbd0cc-222b-11e8-99c4-e60938f08f04.png`... we should do the same: make drag and drop of images to chat name the file as a random uuid...

**Comment by slel** [comment]
Or append a timestamp to the image name?

**Comment by williamstein** [comment]
It's now uploaded to the blobstore database and named with a sha1 hash, so this is no longer relevant.
