### ISSUE TITLE
create a "trivial" electron app (maybe?) now that chrome apps are deprecated

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2739]
Only do this if the whole creation, update, distribution problem isn't too much work...

**Comment by mthomas7** [comment]
[This page](https://thenextweb.com/dd/2016/08/29/use-this-tool-to-quickly-port-your-chrome-app-to-electron-and-run-it-on-any-os/) seems promising, describing the tool [here](https://github.com/koush/electron-chrome). It seems to not work on linux, only windows and mac, so I can't test it on my laptop.

**Comment by mthomas7** [comment]
Better yet - [nativefier](https://github.com/jiahaog/nativefier) did it. I built it on my laptop, and it works perfectly. Not sure what the easiest thing is, but I can send the electron app it built.

**Comment by williamstein** [comment]
This is now solved via   https://github.com/sagemathinc/cocalc-desktop/releases/tag/v1.0.0

I did test out nativefier (mentioned above), and it may have been amazing in 2018, but 3 years it isn't.
