### ISSUE TITLE
sagews %coffeescript broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2752]
I bet not many are using it, but still worthwhile to report it and just annoyed me. I think this is just a fallout of switching to a newer version of coffeescript itself, or some tiny webpack 3.0 config issue.

As far as I can see, it's in `misc_page`, the line `require("script-loader!coffeescript/lib/coffeescript/index.js")`

(I hope this is the only case where such `require(...)` deferred loading constructs fail)

```
addScript.js?3fe7:8 [Script Loader] ReferenceError: require is not defined
    at eval (index.js:7)
    at eval (index.js:177)
    at eval (<anonymous>)
    at module.exports (VM2328 217:20)
    at eval (index.js?87c4:1)
    at Object.1466 (2.nocache.js:11)
    at __webpack_require__ (smc.nocache.js:56)
    at eval (misc_page.coffee?7fa1:1645)
```

**Comment by haraldschilly** [comment]
well, my bet was wrong, it's used by our users …

**Comment by haraldschilly** [comment]
We have to at least add a try/catch to make old worksheets that run code blocks like 
```
%auto
%hide
%coffeescript
```
evaluate in full to be able to edit that first setup cell again

**Comment by williamstein** [comment]
This hasn't worked in over 2 years, and nobody cares about coffeescript anymore.  I'm going to just deprecate this functionality (rather than ever fix it).
