### ISSUE TITLE
files listing updated too early after delete operation

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2753]
When I do this repeatedly:

1. `touch x` (or a, or foo) in the miniterm
2. select the file `x` in the UI
3. delete and confirm deletion

The file is still listed in the listing in about 20% of the cases. When it is still there, clicking on the file listing refresh button clears it up.

I think the listing is just not waiting properly for the delete callback to succeed.

This might also be true for rename operations, etc.

Bonus material: [a screencast](https://cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/cocalc-files-delete-callback-missing.webm?viewer=share)

**Comment by williamstein** [comment]
I addressed this while I was at it in https://github.com/sagemathinc/cocalc/pull/4466 and also since listings are now done using inotify/watch.
