### ISSUE TITLE
deleting a jupyter file should also delete the synchronization meta file

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2754]
otherwise the previous content leaks when the directory containing the sync file is copied to another project and  the associated jupyter file is created.

Also, the case of deleting the sync meta file in the original location still causes #2693

Report back to Kiran, at ZD 5047

**Comment by williamstein** [comment]
I addressed this while I was at it in https://github.com/sagemathinc/cocalc/pull/4466
