### ISSUE TITLE
typing ' /' in .term with firefox can trigger quick find

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2761]
Most readily seen with all these
- vi command history
- bottom of .term window
- using tmux

**Typing ESC-/ brings up Quick Find instead of bash command history.** Quickfind bar disappears after a few seconds. The problem does not happen all the time.

![quick-find-bug-sm](https://user-images.githubusercontent.com/528072/37593421-e51f60e6-2b3f-11e8-9c41-5798a5aa43f0.jpg)

This is a [known problem](https://support.mozilla.org/en-US/questions/984845) with FireFox.
Extensions [searchhotkeys](https://freeshell.de//~kaosmos/index-en.html#searchkeys) (abandoned) and [shortkeys](https://addons.mozilla.org/en-US/firefox/addon/shortkeys/) (no effect) do not solve the problem.

Posting the problem here to indicate it's a known issue.

**Comment by DrXyzzy** [comment]
Correction: [shortkeys](https://github.com/mikecrittenden/shortkeys) provides a workaround. After installing shortkeys, add the following, then reload tabs to use the new shortcut:
- Keyboard shortcut: /
- Behavior: Do nothing (disable browser shortcut)

**Comment by DrXyzzy** [comment]
This bug came up in CoCalc help request 5686 [note by @ws]:

>  I can reproduce this. If I change tabs away (in cocalc), then click to go back to the terminal tab, it still does NOT focus the terminal... sometimes (this is a bug: https://github.com/sagemathinc/cocalc/issues/3180). If I then type / it does a find. If I then click on the terminal itself, the terminal is focused, and doing / works fine (not invoking find). I tested this in several versions of firefox.
> ...
> I cannot reproduce your issue at all if the terminal is focused (which you can tell by the blue line around it).

**Comment by DrXyzzy** [comment]
Here is a way I can reproducibly trigger the quick-find bug in terminal, see it when the terminal has the blue line around it, and then clear it.

1. Open a CoCalc project in Firefox (I am using version 62.0 on macOS 10.13.6) and open a .term.
1. Type a slash.
1. If you didn't get the quick-find box at the bottom, type a new url into the location at the top of the browser, for example "github.com", and hit enter, so that the CoCalc tab is overwritten by the new tab.
1. Hit the browser back button.
1. When the .term reappears, typing a slash brings up quick-find. Note that the term has a blue outline.
1. Clear the problem by clicking inside the term.

**Comment by DrXyzzy** [comment]
Looks as if there will be an [option to disable quick find in Firefox](https://techdows.com/2018/06/disable-quick-find-firefox.html) starting with version 63.

> Ensure you’re using Firefox 63 (which is currently in Nightly)
> 
> 1. Visit about:config
> 
> 2. Search for find, in the search results shown, select ‘accessibility.typeaheadfind.manual‘ preference

Closing this issue for now.

**Comment by williamstein** [comment]
I'm going to re-open this, since I'm rewriting terminals / switching to xterm.js right now, and this problem might be fully solvable in a way that preserves quick-find support.

**Comment by DrXyzzy** [comment]
Note this issue was also reported by CoCalc user Dave Rosoff in our help request # 5686.

**Comment by williamstein** [comment]
I'm going to close this since things seem sufficiently robust with xterm.js, or it's unsolvable by us.
