### ISSUE TITLE
Make it easy to create a course that has a default course structure with folders for weekly handouts and assignments

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2765]
IDEA FROM: Shweta Jain

I'm not sure how this would work exactly.  However, it could be a menu or button in assignments (say), which brings up a dialog asking for the dates, a filename format, etc., then previews what it will create, then automatically creates directories and adds them to the course as assignments.  Similar for handouts. 

It may be useful to look at how this is done with other CRM's.

It might also be important to make it easy to exclude certain days.

**Comment by novoselt** [comment]
How much effort does it take to create a folder, and how much - the actual assignment? I think the value added by such functionality is pretty minimal, while the amount of thought that can/should go into designing it carefully may be substantial. Having dates in folder names is a great idea. But what if one wants to copy the course for a later use? Someone who can really save a lot of time from this being implemented may very well better served by a python script which is fully editable and configurable, not relying on any GUI.
