### ISSUE TITLE
how to install other kernels in the container

### ISSUE THREAD

**Issue by labrador0115** [sagemathinc/cocalc#2772]
i have installed the container and it works well, but it only has three kernel, i tired to install the octave, but failed, i do not know how to install octave in the container.

**Comment by haraldschilly** [comment]
Which container, you probably meant to open a ticket here: https://github.com/sagemathinc/cocalc-docker/issues ?

There is no support for this standalone version of cocalc. You have full control over it and probably just have to follow the  usual instructions for installing the octave kernel. That's all.
