### ISSUE TITLE
Put in log stopping/restarting of project

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#278]
I noticed that my project mysteriously stopped so I went to log and didn't see a stop event.

**Comment by williamstein** [comment]
Good idea. This will have to be inserted in he log by the backend instead
of the frontend like all the current log messages, but this is doable due
to the log being stored in the database...

On Friday, November 20, 2015, timothyclemansinsea <notifications@github.com>
wrote:

> I noticed that my project mysteriously stopped so I went to log and didn't
> see a stop event.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/278>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by williamstein** [comment]
I did this recently.
