### ISSUE TITLE
Files toolbar switches between long and short buttons randomly

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2783]
In the Files toolbar, it seems the  buttons for New, Settings, etc. are randomly switching between long (with text) and short (icon only)forms. Google Chrome 65.0.3325.181 (Official Build) (64-bit), MacBook Pro running macOS 10.13.3. I haven't figured how to make it reproducible. I have refreshed the browser several times. This is in a project open with 4 files tabs.

For example, Settings below went from long to short form. Sometimes the change happens while I am editing a file.

![screenshot 2018-03-26 09 53 59](https://user-images.githubusercontent.com/528072/37915075-49d6f5dc-30de-11e8-80c1-2b3998925778.png)

![screenshot 2018-03-26 09 56 22](https://user-images.githubusercontent.com/528072/37915046-35025322-30de-11e8-8625-6cbd3f7b6f00.png)

I'll keep testing to see if I can find a repeatable trigger and see if it happens in other browsers.

**Comment by haraldschilly** [comment]
yes, I saw that, too. But not today, so, I'll add this heisenbug tag. I also have the impression they "talk" to each other, i.e. that when I open one of them, like "+ new" it expands to show the text while at the same time "files" and "log" disappeared. It has definitely something to do with the width of the window and how much space there is in the bar.

**Comment by williamstein** [comment]
I'll fix this. Not heisenbug after discussion...

**Comment by haraldschilly** [comment]
This is ok now, closing.
