### ISSUE TITLE
with md edit with vim bindings, deleted text at end of line is not shown in preview immediately

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2784]
1. set Account/Preferences/Editor Settings/Editor keyboard bindings to "Vim" and refresh browser
1. open a .md file
1. type

    ```
    abc def

    123
    ```

1. in edit mode, put cursor at start of "def" and hit "D" to delete to end of line
1. notice that preview does not update to show the deletion
1. inserting text anywhere will show the deletion

Seen with Chrome and Firefox
Not seen with Default editor bindings

**Comment by williamstein** [comment]
nice find!
