### ISSUE TITLE
sagews: %python --mode 2x "from sympy import *" results in error

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2788]
I don't know what's going on, but importing sympy in sagews's python mode must configure/import something that causes some trouble with evaluation. It doesn't happen with every library, though. I only saw this with sympy, but there is no reason why there aren't others with a similar issue.

Sympy `__init__.py` is here: `/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sympy/__init__.py`

Error:

```python-stacktrace
Error in lines 1-1
Traceback (most recent call last):
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 1013, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "<string>", line 1
    e = from sympy import *
           ^
SyntaxError: invalid syntax
```

obligatory screenshot

![screenshot from 2018-03-27 12-14-07](https://user-images.githubusercontent.com/207405/37961360-5d8b0dae-31b8-11e8-8b76-bba6737894e4.png)

**Comment by williamstein** [comment]
This has nothing to do with sympy.  There is something very funny with %python, e.g.,
```
%python
print 'hi'
```
also breaks it, since it is trying to run `e = print 'hi'`.

I will change the titlel

**Comment by haraldschilly** [comment]
Well, did you try this with a restarted session? E.g. I'm pointing to sympy, because doing the same twice with numpy works fine. This is what I see:

![screenshot from 2018-03-27 20-28-20](https://user-images.githubusercontent.com/207405/37987069-7fc27764-31fd-11e8-89c7-fe97956f1e19.png)

**Comment by williamstein** [comment]
Woops -- I was misled.  Changing title back...

**Comment by williamstein** [comment]
Doing `from foo import *` can and should be able to break everything.  In this case it change 909 things in our globals() namespace.  In particular, it completley overwrites the python function that gets run by %python by a new python function defined by sympy:
```
File: /ext/sage/sage-8.1/local/lib/python2.7/site-packages/sympy/printing/python.py
Signature : sympy.python(expr, **kwds)
Docstring :
Return Python interpretation of passed expression
(can be passed to the exec() function without any modifications)
```

There is a reason that `from blah import *` is so very strongly frowned upon. 

I'm closing this -- if you disagree, open a new ticket that is about maybe protecting % modes (maybe having them in a separate namespace) or printing warnings when variables in globals() or overwritten... which would be pretty annoying.
