### ISSUE TITLE
course/peer grading: non-informative error message

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2791]
I saw this while assigning a single peer assignment. result of this issue is just to make sure that this error object is human readable.

![screenshot from 2018-03-28 14-32-07](https://user-images.githubusercontent.com/207405/38028987-de86581e-3294-11e8-9eaa-f92f0b3e5397.png)

**Comment by novoselt** [comment]
Closing as stale, we can open a new issue if there will be demand.
