### ISSUE TITLE
when searching for assignment folders, add a spinner or some info indicating that something is happening.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2797]
There is no visual indication when you're adding an assignment that the list of directories in the project is being scanned:

![screenshot 2018-03-29 at 10 15 04 am](https://user-images.githubusercontent.com/1276278/38103057-1ddef840-333a-11e8-91a0-015019e25aa3.png)

Fix this with a quick hack for now...

**Comment by profbrady** [comment]
I have had the same issue with working sometimes and not others. In fact, it happened to me a few minutes ago. When it does happen, the only that seems to fix it is a browser refresh.
