### ISSUE TITLE
reimplement "delete file" to be MUCH more robust

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2805]
REQUESTED BY: Kiran Kedlaya who says:

> "My main friction point was that deleting files often doesn't stick; the
files have a habit of reappearing without warning. This came up a few
times when I was pushing out handouts or assignments; sometimes an
unintended temporary file got pushed out too. (I got in the habit of
running through a checklist before pushing things out: did I remove all
output? Did I remove all temporary files?)"

We have to take care in doing this better (without, e.g., making switching between git branches really annoying or breaking autosave), but I have some ideas...

Coming up with some clear steps to reproduce this would also be very helpful.  @DrXyzzy ?

WORKAROUND: close all browsers with the file opened, restart the project, then delete the file

**Comment by DrXyzzy** [comment]
One set of cases is described at [Deleted Notebook Comes Back](https://github.com/sagemathinc/cocalc/wiki/Deleted-Notebook-Comes-Back)

I can write up examples.

**Comment by DrXyzzy** [comment]
Also reported by Gregory Bard, this scenario:

1. Work on a file in project home directory.
1. Make a new directory and move file there.
1. Notice file with same name in home directory after the move but do not notice that this (phantom) file has zero length.
1. Move phantom file into new directory, thus clobbering the content in the file.
1. Work is recovered using time machine.

**Comment by DrXyzzy** [comment]
Reported by David Jeschke: deleted .md file can come back.

* If someone clicks on the name of the deleted file in the project activity log, CoCalc will open a 0-length file with that name.

* If a file is deleted in one browser session but open in another session, activity in the second session can make the file reappear. In fact, if a second user had the file open, then closed their browser while the first user deleted the file, the file can come back when the second user reopens the browser.

**Comment by williamstein** [comment]
> * If someone clicks on the name of the deleted file in the project activity log, CoCalc will open a 0-length file with that name.

That's what is supposed to happen.  E.g., it gives you access to TimeTravel for the file.

> * If a file is deleted in one browser session but open in another session, activity in the second session can make the file reappear.

This is not supposed to happen, so it is a bug.

**Comment by williamstein** [comment]
Upon reflection, probably the right fix is to always require the user to take some manual step to confirm that they want to recreate the file.  Then, even if they have another tab open on the same file (etc.,) it doesn't get created.

**Comment by stumpc5** [comment]
What happens when moving elsewhere a file instead? Does another open tab with the same file understand that the file has moved? It seems that moving files should anyway also properly work in this scenario.

Have you thought of having per default a trash folder and deleting moves files there?

**Comment by rljacobson** [comment]
Not sure if this is the same issue, but:

1. I accidentally created a .sagews file instead of a folder. 
2. I deleted the .sagews file, but it apparently was still listed in the file list.
3. Selecting the files to move to the newly created folder, I must have also selected the just-deleted .sagews file.
4. I try to move everything to the new folder but get an error saying the .sagews file does not exist, which is true, I supposed. The rest of the files were moved successfully. 

Screenshot attached. As you can see, the file list is not refreshed as the error message is displayed. Maybe that's what is happening in my case: I selected a nonexistent file before the file list was refreshed.
<img width="1154" alt="Screen Shot 2019-04-08 at 5 50 38 PM" src="https://user-images.githubusercontent.com/1412598/55759682-032d4180-5a28-11e9-959c-af743f9ce7fb.png">

**Comment by williamstein** [comment]
I'm seriously working on this at https://github.com/sagemathinc/cocalc/pull/4466 right now...

**Comment by williamstein** [comment]
I addressed this while I was at it in https://github.com/sagemathinc/cocalc/pull/4466

**Comment by williamstein** [comment]
There are reports of this happening again, so I'm re-opening it.  There's a specific suggestion from a user to record more information about why a file was deleted, and also in case of renaming a file:

> "And neither file renaming nor file deletion works as I would expect, meaning that the deleted/renamed file comes back again and again. In case of a renaming, we then have two files available and some then edit the old and some the new file so that everything gets corrupted.

> The reason might be that someone else has that (then removed) file (with the old name) still open in the running project.

> I am actually not sure this problem has a solution. But I could maybe think of a method that this file is closed/renamed for all project participants together with a warning of this behavior. ("WARNING: The file XXX you had open was deleted by YYY. Please make sure you agree with this deletion." or "WARNING: The file XXX you had open was renamed by YYY. Please check for the new filename and make sure you agree with this renaming.").

**Comment by stumpc5** [comment]
> There are reports of this happening again, so I'm re-opening it.

This happened on your cocalc setup at our uiversity, so I do not know which version of CoCalc runs there.
