### ISSUE TITLE
latex parsing issues

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2807]
This ticket lists a few examples where dollars in latex parsing do cause some issues. In particular, they should be ignored because of the context where they are.

this overlaps with #2771 

[demo worksheet](https://cocalc.com/share/14eed217-2d3c-4975-a381-b69edcb40e0e/scratch/markdown-latex-issues.ipynb?viewer=share)

condensed example list:

case 1: backslashes

    use `$`, e.g. `table(people$sex)`

case 2: 4-space indented should be pre/code text.

    These $ should be ignored $.

case 3: dollar sign in html attributes

    <span class="style-$">This is odd</span><span class="style2-$">styled</span>

**Comment by williamstein** [comment]
Note that we now do *all* math extraction at the html level, not markdown.  So, e.g., the fix for case 2 will be to ignore $'s inside code blocks.

**Comment by haraldschilly** [comment]
Here is another example where html vs. dollar signs cause problems:

* `# foo $x^2$ bar` works
* `# foo $$x^2$$ bar` broken (no formula processing)
* `foo $$x^2$$ bar` also broken, when on it's own line (no formula processing)

It's hard to tell what in the second case should happen. At least, processing the formula as usual would be fine. In the third case, a whole new div block with a centered formula should be inserted.

Workaround (for a bold and large formula, which is centered)

* on a line without text around it: `$$\bf \Large x^2$$`

**Comment by williamstein** [comment]
Opened https://github.com/sagemathinc/cocalc/issues/2853 for the one loose end, which is lower priority.
