### ISSUE TITLE
restarting the haskell kernel does not work

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2820]
With CoCalc Jupyter:

1. Create an ipynb with Haskell Kernel.
2. Type `2+2` and see it work fine.
3. Click to restart the kernel.
4. Observe it fail forever, even if you try to run code.

**WORKAROUND:** When you can't restart the kernel, just change the kernel to any other kernel, wait a moment, then change it back to Haskell.  Then try to evaluate a cell.  It'll start working.

**Comment by williamstein** [comment]
NOTE: if you use the classical Jupyter server (e.g., "Plain Jupyter Server" in project settings), then restarting the kernel works fine, so the problem is in our backend code, probably.

**Comment by haraldschilly** [comment]
I played a bit around directly in coffee. First thing I noticed is the lack of output, compared with the "python3" kernel, after trying to run a snippet of code. i.e. this:

```
coffee> j = require('./smc-project/jupyter/jupyter')
coffee> k = j.kernel(name:'haskell', path:'x.ipynb')
coffee> k.execute_code(all:true, cb:((x) -> console.log(JSON.stringify(x))), code:'3 + 3')
Client.jupyter.Kernel('haskell',path='x.ipynb')._process_execute_code_queue:  state='off'
Client.jupyter.Kernel('haskell',path='x.ipynb')._process_execute_code_queue:  queue has 1 items; ensure kernel running
Client.jupyter.Kernel('haskell',path='x.ipynb').spawn:  spawning kernel...
undefined
coffee> 
```
and nothing. running the same with `python3` would have resulted in a few IOpub messages, including the one for the output.

continuing with in that session:

```
coffee> k._process_execute_code_queue()
Client.jupyter.Kernel('haskell',path='x.ipynb')._process_execute_code_queue:  state='starting'
Client.jupyter.Kernel('haskell',path='x.ipynb')._process_execute_code_queue:  queue has 1 items; ensure kernel running
Client.jupyter.Kernel('haskell',path='x.ipynb')._process_execute_code_queue:  now executing oldest item in queue
Client.jupyter.Kernel('haskell',path='x.ipynb')._execute_code('3 + 3'):  code='3 + 3', all=true
Client.jupyter.Kernel('haskell',path='x.ipynb')._execute_code('3 + 3'):  send the message
[.... lot more messages ...]
[ and finally: ]
coffee> Client.jupyter.Kernel('haskell',path='x.ipynb')._execute_code('3 + 3'):  got IOPUB message -- {"header":{"username":"","msg_type":"display_data","version":"5.0","msg_id":"51fdd67c-dda1-4178-8681-dc75f8835ded"
,"session":""},"parent_header":{"username":"","msg_type":"execute_request","version":"5.0","msg_id":"execute_02fb4655-f5b6-4440-8376-49085ebfa085","session":""},"metadata":{},"content":{"data":{"text/plain":"6"},"met
adata":{},"source":"haskell"},"buffers":[]}
[ ... 2 more ...]
```

**Comment by williamstein** [comment]
**Another Workaround:** You can use a Sage Worksheet in Haskell mode, like [this](https://cocalc.com/share/77a92d07-c122-4577-9c4c-c051379cacfe/HASK1/haskell2.sagews?viewer=share)
