### ISSUE TITLE
Feature request: New students in class inherit project quota

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#283]
> Paul Smart: I've noticed if I setup a class and add one student, then set the quotas, when I add more students, they don't inherit the same quota. There's no simple way to add the quota to them other than removing all quota from all students and then re-adding.

**Comment by williamstein** [comment]
Should change to a  declarative approach to student upgrades (and collabs) with a "control loop" to ensure it is true.

**Comment by haraldschilly** [comment]
I'm closing this, because we more or less switched to the license model, which is also more declarative than distributing fractions of a limited quantity. In any case, new student projects are configured uniformly.
