### ISSUE TITLE
it is difficult to know what user I'm signed in as, so change the gear icon next to "Account" to be the user's avatar

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2836]
This is bog standard and what every other website does (show the avatar).

**Comment by williamstein** [comment]
Here's the relevant commented out code: https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/desktop_app.cjsx#L116

**Comment by tscholl2** [comment]
This was merged in 2935.
