### ISSUE TITLE
if you close a project then re-open it, should it open all the files you had opened before?

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2837]
It would be natural that if session=blah is set, then following is how it should work:
1. Open a project P
2. Open files foo and bar
3. Close project P
4. Reopen project P... and see foo and bar already open.

This is of course very easy to implement by slightly enhancing the session data structure store in local storage.  However, maybe it is a bad idea?  

Thought?

**Comment by haraldschilly** [comment]
I like that. Couple of days ago I was angry that I accidentally closed my dev project and my opened files were gone.
