### ISSUE TITLE
webapp: showing recent errors somehow broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2840]
This top right corner thingy stopped to flow out upon hover for me (after there was an error)

![screenshot from 2018-04-17 13-24-49](https://user-images.githubusercontent.com/207405/38866954-da697b9a-4242-11e8-9926-43a7a82753d8.png)

it's also a bit darker right around the arrow down. hence my first guess is this happened when updating awesome fonts.

**Comment by williamstein** [comment]
The solution for this should probably be just to rewrite this whole pnotify alert thing using React.  This is one of the first jquery plugins I ever used, and definitely needs to go.

**Comment by williamstein** [comment]
> This top right corner thingy 

It no longer exists.
