### ISSUE TITLE
Make Sage's browse_sage_doc open html documentation in a new tab

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2842]
On CoCalc, if I run

    browse_sage_doc(eulers_method)

- in the Sage REPL in a CoCalc terminal: the documentation opens in Lynx
- in a CoCalc worksheet (.sagews): nothing visible happens
- in a SageMath-kernel Jupyter worksheet (.ipynb): nothing visible happens

Having the html documentation render in a new CoCalc tab would be nice
in the last two cases (possibly in the first case too).

**Comment by williamstein** [comment]
I doubt we can or should support this.  I suspect almost nobody even knows about browse_sage_doc, and people just use https://doc.sagemath.org/ or google now-a-days.
