### ISSUE TITLE
autoload file for jupyter notebook

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2843]
Requested by William Paulsen.

See [jupyter/notebook/issues/1451] for discussion of this topic.

**Comment by DrXyzzy** [comment]
Use case for William Paulsen is a series of example sage (.sws) files for his Abstract Algebra [book](https://www.crcpress.com/Abstract-Algebra-An-Interactive-Approach-Second-Edition/Paulsen/p/book/9781498719766) that all use a common setup file, `absalgtext.sage`. Example files are hosted [here](http://myweb.astate.edu/wpaulsen/algebra.html). The idea is to make a set of Jupyter notebooks running Sage kernel, based on the .sws sheets, each of which loads the .sage setup.

**Comment by williamstein** [comment]
I think this is both a nice feature and a potential security nightmare.  Nobody else has requested it in years.
In JupyterLab I couldn't find a way to do this, beyond people writing and installing custom extensions (see https://discourse.jupyter.org/t/autorun-some-code-cells-jupyterlab3/8737/9).
