### ISSUE TITLE
slow switching between jupyter classic notebooks in cocalc tabs

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2848]
To reproduce the problem:

1. Upload this notebook: [Beat Frequencies.ipynb](https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Beat%20Frequencies.ipynb) into a CoCalc modern notebook with either Python 3 Jupyter kernel. 
1. Select `File` > `Switch to classical notebook...` to open the notebook in a CoCalc tab.
1. Select `Kernel` > `Restart & Run All`. Verify that the ipywidgets update output in real time.
1. Repeat previous steps with this as second notebook: [Lorenz Differential Equations.ipynb](https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Lorenz%20Differential%20Equations.ipynb).
1. Switch between the two CoCalc notebook tabs. Observe that time to render a notebook when its tab is selected can vary between 1 and 10 seconds. Tab appears empty at first.

Workarounds:

- View the classical notebooks using `Project Settings` and select `Plain Jupyter Server`, which puts each notebook in a separate browser tab. The latency problem does not occur this way.
- Shift-click the CoCalc tab for each notebook to pop it out into a separate browser window. Then the local window manager will render each notebook instantly when it receives pointer focus.
- Changing the size of the browser window will cause the classical notebook in a CoCalc tab to be rendered instantly.

Reported by Stuart Prescott.

**Comment by mforbes** [comment]
Recently, after clicking "Switch to classical notebook..." with Chrome, it took >30s for the page to render.  Not sure if this is related, but the page was blank for this time.  A warning message saying "starting server... please wait" or something similar would be helpful.  Let me know if I should submit a new ticket.

**Comment by williamstein** [comment]
Jupyter classic is deprecated, so even if slow, we're not going to fix/support it in its current form.
