### ISSUE TITLE
sagews 3d printing has problems

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2851]
there is an exception `Error rendering worksheet TypeError: n.e is not a function` pointing to

```
L=c("<video src='".concat(A,"' class='sagews-output-video' controls>
</video>")),
S.append(L);
break;
case"sage3d":(l=c("<div class='webapp-3d-container'></div>")).data("uuid",D.uuid),
S.append(l),
// BREAKS BELOW AFTER n.e
n.e(1).then(function(){return n(800).render_3d_scene({u
```
which is in sagews/sagews:

```
                    when 'sage3d'
                        elt = $("<div class='webapp-3d-container'></div>")
                        elt.data('uuid',val.uuid)
                        output.append(elt)
                        require.ensure [], () =>   # only load 3d library if needed
                            require('./3d').render_3d_scene
                                url     : target
                                element : elt
                                cb      : (err, obj) =>
                                    if err
                                        # TODO: red?
                                        elt.append($("<div>").text("error rendering 3d scene -- #{err}"))
                                    else
                                        elt.data('width', obj.opts.width / $(window).width())
```

symptom: existing 3d plots cause the file to not be processed correctly, new plots do not show up.

**Comment by haraldschilly** [comment]
note: the above obviously increases the load size and we should get require.ensure working again. 

to replicate the issue, one has to do a production build. a normal development build does not show this problem.

**Comment by williamstein** [comment]
And it also just came out of nowhere recently for no apparent reason.

**Comment by williamstein** [comment]
> looking at the commits, it doesn't help me. 

Those are orthogonal to this and after it.

I say we just close this and stick with your hotfix.  It doesn't matter, since I'm going to rewrite sage worksheets from scratch very soon anyways.  Your hotfix is fine.
