### ISSUE TITLE
paste into the terminal

### ISSUE THREAD

**Issue by edgarcosta** [sagemathinc/cocalc#2854]
I have noticed that one cannot paste something that has stylization in a straightforward way (e.g. CMD+V),  for example something with some code highlighting from jupyter.

A fix is to do right click, select paste and then press some input key (and your text will popup).
After you have done this once, you can happily repaste the same text again with CMD+V

**Comment by DrXyzzy** [comment]
@edgarcosta can you give a specific example? e.g. link to a file in a project and say exactly 1) what you are doing, 2) what happens, and 3) what you would like to happen? Thanks.

One thing to try is, after copying into your clipboard and switching to CoCalc .term tab, position your cursor inside the text area and click mouse or pointer device. Then try CMD+V.

**Comment by edgarcosta** [comment]
See the gif:
![copyandpaste](https://user-images.githubusercontent.com/322822/39473784-9497f808-4d1e-11e8-8045-c63ed88cefe3.gif)

Let me know if you need anything else.

**Comment by slel** [comment]
Similar issue, observed under macOS, not sure how related:

With a CoCalc terminal open,

- go to another browser tab or another application
- copy text with cmd-C
- come back to the CoCalc terminal
- paste by cmd-V does not work
- now click inside the CoCalc terminal
- paste by cmd-V works again

and you can repeat this whole sequence,
it every time fails to paste, until you have
clicked inside the CoCalc terminal.

**Comment by slel** [comment]
It seems all the issues reported here are fixed in the new xterm.js-based terminal.
@edgarcosta please confirm.

**Comment by edgarcosta** [comment]
confirmed! tks!
