### ISSUE TITLE
opening some .sagews in macOS with Chrome causes CPU spin

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2856]
On macOS:
- open Activity Monitor and select CPU tab
- open [this private file](https://cocalc.com/projects/77a92d07-c122-4577-9c4c-c051379cacfe/files/PAULSEN/TESTSAGEWS/group00.sagews?session=default)
- observe that CPU utilization for Google Chrome spikes and UI becomes unresponsive

Seen with macOS 10.13.3, Chrome latest =  Version 66.0.3359.139 (Official Build) (64-bit), with all browser extensions and plugins disabled and hardware acceleration disabled.

Noticed when investigating #2852.

**Comment by williamstein** [comment]
Data point -- For what it is worth, on Chrome OS (Pixelbook) Version 65.0.3325.209 (Official Build) (64-bit), this problem does **not** happen:

1. There is high CPU utilization for a few seconds (not sure how long?).  
2. Then the entire Sage worksheet appears (it's big).
3. The CPU is back to zero. 

---

I tried running the chrome profiler and it takes about 25s to load the worksheet with the profiler running. It really is running some sort of CPU intensive "script".  So even though it does work for me, taking 25s to load is obviously unacceptable.

**Comment by DrXyzzy** [comment]
On macOS, CPU goes to around 300% on my Intel i7 MacBook and stays there. Entire desktop UI becomes extremely sluggish. I have waited over a minute before closing the browser window and have not got to the rendered page with Chrome on this computer.

**Comment by williamstein** [comment]
closing as stale.
