### ISSUE TITLE
support  python3-style print function inside sage worksheets (in %sage mode and %python mode)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2862]
REQUESTED BY: James Byerly

I don't think this is possible yet. We probably need to add something at the level of the backend sage server somewhere, probably in sage_server.py. 

Would it be reasonable to have it always on (e.g., probably by just sticking a line at the top of sage_server.py), or would that break things too much??

**Comment by dv-extrarius** [comment]
As a workaround for python mode, I copied the built-in python3 mode and just changed the kernel to python2 ([sagews showing my workaround](https://cocalc.com/share/242a28c7-af3c-47f5-97ac-483a0f1972f2/python2.sagews?viewer=share)). Ideally, I really want support for the python `__future__` system in %sage mode as well.

**Comment by slel** [comment]
In Sage mode, if you just run this line

    from __future__ import print_function

then you can use the Python3-style print function.

If you put that line in the file `~/.sage/init.sage`
(create it if it does not exist), then this should be
run at startup every time you start stage.

**Comment by williamstein** [comment]
@slel, that doesn't work in a Sage worksheet:  https://cocalc.com/share/4a5f0542-5873-4eed-a85c-a18c706e8bcd/support/2018-05-03-python3-printing.sagews?viewer=share

In a Jupyter notebook with a Sage kernel it *does* work nicely: https://cocalc.com/share/4a5f0542-5873-4eed-a85c-a18c706e8bcd/support/2018-05-03-python3-printing.ipynb?viewer=share

**Comment by dv-extrarius** [comment]
As williamstein noted, it doesn't work in a sage worksheet, even if it is in the same cell: https://cocalc.com/share/242a28c7-af3c-47f5-97ac-483a0f1972f2/future.sagews?viewer=share

**Comment by williamstein** [comment]
@dv-extrarius incidentally, you could:

1. Clone this repo https://github.com/sagemathinc/cocalc/ into your project.
2. cd into the [src/smc_sagews](https://github.com/sagemathinc/cocalc/tree/master/src/smc_sagews) directory.
3. Type `pip install --user smc_sagews/`
4. Restart your Sage server (in project settings).

... and then any restarted worksheets should use the code you just installed.

Have a look in smc_sagews...;  if you want to do something with that code, we can help...

**Comment by DrXyzzy** [comment]
@williamstein:
> Would it be reasonable to have it always on (e.g., probably by just sticking a line at the top of sage_server.py), or would that break things too much??

Doing `from __future__ import print_function` unconditionally breaks `print 'hello'` syntax in legacy sage and python worksheets. I don't think we want that.

How about adding a mode that is remembered across cells (until/unless it is changed), e.g. `py3print_mode(True)`? I'm testing a patch for that now.

**Comment by dv-extrarius** [comment]
@DrXyzzy while that addresses my original ticket, it'd be really nice if `__future__` could be made to work, or at perhaps add py3division_mode also?

**Comment by williamstein** [comment]
PR will be live in a few minutes. @dv-extrarius  please open another ticket for more!
