### ISSUE TITLE
(c) markdown bug

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2876]
In Markdown if you type (c) then (d), the (c) is not a copyright symbol.

For some reason in cocalc right now it is.  I blame markdown-it.  This is definitely wrong.

![screenshot 2018-05-10 at 4 40 02 pm](https://user-images.githubusercontent.com/1276278/39899487-0c9fa45a-5471-11e8-8314-f8a86d9b32f2.png)

**Comment by DrXyzzy** [comment]
Reported by Stuart Prescott.
Workaround tested in .sagews and .ipynb is to use `($ $c)`.

**Comment by williamstein** [comment]
Good example: 
["Question 1(c)"](https://cocalc.com/share/6783f022-0788-4da3-a6a8-118cc81adc07/copyright%20symbol%20test.ipynb?viewer=share)
