### ISSUE TITLE
dot (.) command with vim keyboard bindings in macOS Safari duplicates characters

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2888]
Not seen with Chrome. ~~Can't use Firefox on macOS at the moment due to websocket bug #2875.~~ Safari on iOS was not tested with vim bindings due to lack of ESC key on smart [sic] keyboard.

This only happens while editing a .md file, not while entering markdown in a .ipynb or .sagews markdown or compute cell.

1. Type `cocalc`.
1. Position cursor over leading `c` in edit mode and hit `~` to change to upper case.
1. Position cursor over second `c` and hit `.` to repeat the capitalization command at the new cursor position.
1. Instead of just capitalizing, the text `CoCCalc` results, and sometimes `CoCCCalc`

**Comment by williamstein** [comment]
I just tried this several times with the latest Safari on the latest iOS and am not seeing this problem.   I have all the keyboard settings on (their defaults):

<img width="470" alt="image" src="https://user-images.githubusercontent.com/1276278/102719815-1c7e2c00-42a5-11eb-8bf8-ea18517089ca.png">
