### ISSUE TITLE
ansi codes in warnings not correctly rendered in modern Jupyter with Julia kernel

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2889]
Noted previously within the comments in #2427 but should be its own issue.

Example:
```
warn("foo")
```

![julia-warn-foo](https://user-images.githubusercontent.com/528072/40253204-85fdd860-5aa4-11e8-80c0-f61bff020401.png)

**Comment by DrXyzzy** [comment]
Additional points of information:

1. The problem does not appear in a .sagews using the same jupyter kernel:

<img width="209" alt="jwarn" src="https://user-images.githubusercontent.com/528072/41358655-745403c4-6eee-11e8-8664-9a5c93ac31b3.png">

2. Sending the same control codes to stdout in a Jupyter Julia notebook does not show ansi codes, but appears in the wrong color. This is probably due to a different, known issue, [Why do colored strings break contains() in v0.6?](https://discourse.julialang.org/t/why-do-colored-strings-break-contains-in-v0-6/4455)

<img width="574" alt="jwarn2" src="https://user-images.githubusercontent.com/528072/41358838-d3b9ed42-6eee-11e8-88b7-1602772d9f82.png">

3. Here is what the julia kernel sends for `warn("hello")`. Log obtained by setting `debug=True` with Jupyter bridge. Line breaks added for legibility:
```
iopub stream {'text': '\x1b[1m\x1b[33mWARNING:
 \x1b[39m\x1b[22m\x1b[33mhello\x1b[39m\n',
 'name': 'stderr'}
```
and here is what it sends for `println("\e[1m\e[33mWARNING: \e[39m\e[22m\e[33mhello\e[39m")`:
```
iopub stream {'text': '\x1b[1m\x1b[33mWARNING:
 \x1b[39m\x1b[22m\x1b[33mhello\x1b[39m\n',
 'name': 'stdout'}
```
The difference in the messages is the `name` field.

**Comment by haraldschilly** [comment]
This reminds me of: https://github.com/sagemathinc/cocalc/issues/2520, where the control code for clearing the last line isn't interpreted.
