### ISSUE TITLE
if you create an account associated to github/google/facebook/etc single sign on, you can't later add email/password auth

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#289]
> Dear all,  I think this is a bug, but as I am not sure, I ask here.
> In SMC I signed in via github, but now want to change this to a standard email-password authentication.  However in order to add a (new) email (or new password) I must have an (old) password, which I do not have.  Can anyone help?

**Comment by johnjeng** [comment]
I'm having a trouble replicating this issue with dummy accounts.
The UI is certainly unhelpful and I'm fixing that at the moment. However, it seems to me that you can add an email no problem (it lets you do this if you just type anything into the password field) and you can add a new password by putting anything into the "Current Password" field that *isn't* your desired password and filling the rest as desired.

**Comment by williamstein** [comment]
I never replicated this either -- and my memory is that things should work like you describe.  So maybe the main thing is to fix the UI.

**Comment by williamstein** [comment]
This could be a major issue for students in courses who click to SSO, then can't use the right email to get added to a class.

**Comment by williamstein** [comment]
Evidently you **can** add your email.  However, the UI asks for your password, which you haven't set.  If you ignore that, then things work.  It's confusing.

**Comment by williamstein** [comment]
I think i fixed this sufficiently when adding anonymous user support.
