### ISSUE TITLE
extra pop-up during automatic kernel selection

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2896]
Seen with Chrome and Safari on macOS 10.13.3.

Open a julia notebook with outdated kernelspec and language_info, notification and kernel selection work properly, but a small window drops down to left of the kernel selection dialog with redundant content and a pointer to a file tab that is not the active one:

<img src="https://user-images.githubusercontent.com/528072/40522637-7f80fb50-5f97-11e8-9f88-41a2e19696b5.png" width="80%"/> 

Sometimes after clicking to choose the available kernel, the CPU and memory values are also displayed redundantly.

<img src="https://user-images.githubusercontent.com/528072/40522653-8f4029f8-5f97-11e8-8b6f-bf0a80431221.png" width="80%"/>

To reproduce the problem

1. Use a .term to create an .ipynb file with the contents below. The file is a simplified version of notebooks found online.
1. You may want to copy the test file to a backup so you can restore it for repeated testing.
1. Open the file using the File browser:

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
   ],
   "source": [
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Julia 0.4.6",
   "language": "julia",
   "name": "julia-0.4"
  },
  "language_info": {
   "file_extension": ".jl",
   "mimetype": "application/julia",
   "name": "julia",
   "version": "0.4.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```
This relates to  PR #2894.

**Comment by williamstein** [comment]
Current behavior seems fine:

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/06dd50fc-cb48-4b1e-bc97-4e27d0ae9c1c">
