### ISSUE TITLE
*every* single time you start the julia kernel it blasts a pile of deprecation warnings. 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2908]
1. Do anything at all with the Julia kernel in CoCalc Jupyter:
2. See this:
```
WARNING: Compat.UTF8String is deprecated, use String instead.
  likely near /ext/julia/julia/share/julia/site/v0.6/IJulia/src/kernel.jl:31
WARNING: Compat.UTF8String is deprecated, use String instead.
  likely near /ext/julia/julia/share/julia/site/v0.6/IJulia/src/kernel.jl:31
WARNING: Compat.UTF8String is deprecated, use String instead.
  likely near /ext/julia/julia/share/julia/site/v0.6/IJulia/src/kernel.jl:31
WARNING: Compat.UTF8String is deprecated, use String instead.
  likely near /ext/julia/julia/share/julia/site/v0.6/IJulia/src/kernel.jl:31
WARNING: Compat.UTF8String is deprecated, use String instead.
  likely near /ext/julia/julia/share/julia/site/v0.6/IJulia/src/kernel.jl:31
```
3. Feel that Julia + CoCalc is broken.

![screenshot 2018-05-31 at 4 36 01 pm](https://user-images.githubusercontent.com/1276278/40813635-bd9647de-64f0-11e8-8d5c-a12f001d6a78.png)

Ideas to fix:

1. At least dedup stupid deprecation warnings!  I mean come on.
2. Upgrade Julia.

**Comment by haraldschilly** [comment]
closing this. that's not the case and it happens with outdated packages.

![screenshot from 2018-12-21 14-45-22](https://user-images.githubusercontent.com/207405/50345373-25f62180-052f-11e9-87a0-03c565e0378d.png)
![screenshot from 2018-12-21 14-44-58](https://user-images.githubusercontent.com/207405/50345374-25f62180-052f-11e9-9c82-63f7cbb8c072.png)
