### ISSUE TITLE
Getting "Missing PDF -- Build or fix" errors when working with LaTeX

### ISSUE THREAD

**Issue by EyeBool** [sagemathinc/cocalc#2909]
Cocalc was working fine, and then it prompted me to reload because a new version was available.

Now when I am using the LaTeX editor, I get a "Missing PDF -- Build or fix" error in the _PDF Review_ window. In the _PDF - Native_ window, I get "Couldn't open PDF Something's keeping this PDF from opening." using MS Edge, and "This plugin is not supported" using Brave.

It still builds fines, and output a valid PDF file in the directory.

**Comment by williamstein** [comment]
Please use Google chrome.

**Comment by EyeBool** [comment]
Google Chrome is producing the same errors.

Developer Tools show that I get two 404 replies on loading the editor. This is from a fresh chrome install, no extensions or anything.

![capture](https://user-images.githubusercontent.com/26015273/40827699-3cf052d0-6533-11e8-9f29-520ba445291e.PNG)

**Comment by williamstein** [comment]
1. Restart your project
2. Send a link to your Tex file.

**Comment by EyeBool** [comment]
Restarted project. Behavior persists.

Link to file: https://cocalc.com/projects/efe89b8b-c1e1-4e3b-ae4f-26f54b21b7e1/files/Final/Final%20%23B/Final%20%23B.tex?session=default

**Comment by williamstein** [comment]
I think this is being caused by the # in the path. You can rename the path
as a workaround for now. I will look into a proper fix tomorrow.

**Comment by EyeBool** [comment]
Cool, removing the # makes it work. :)

**Comment by williamstein** [comment]
I've fixed the bug -- after a browser refresh, files with # should work fine again.
