### ISSUE TITLE
Catch Ctrl-W in a terminal window

### ISSUE THREAD

**Issue by leoluk** [sagemathinc/cocalc#2910]
Feature suggestion: Embedded terminals should catch accidental Ctrl-W shortcuts by displaying a tab close confirmation dialog. Some people (including me) are hardwired to use Ctrl-W to delete the last word.

**Comment by williamstein** [comment]
Unfortunately, this is probably impossible as requested, due to how browsers work.  A workaround is to select "Confirm: always ask for confirmation before closing the browser window" in account preferences.

**Comment by tscholl2** [comment]
@leoluk It may be worth mentioning that you can always SSH into your project directly. If you go to your project settings, there is a box on the bottom left of the page titled "SSH keys". You can use this to add an SSH key to your project so you can login to your project from any terminal you want. This is especially helpful for these situations.
