### ISSUE TITLE
Improve list of courses

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2911]
Maybe the list of courses, currently on the wiki at

- https://github.com/sagemathinc/cocalc/wiki/Teaching

could become a database of courses that have used CoCalc.

There could be a form to add a new course, allowing to enter

- course title
- person in charge
- year of studies
- field and subfield, eg Mathematics / Geometry
- how many students
- how many instructors
- software used/taught in the course, e.g.
  GAP, Julia, Jupyter, Python, R, Sage, scikit-learn, etc.
- taught in-person, online, or both
- course webpage
- comments on how the course went
- ...

**Comment by williamstein** [comment]
We are no longer keeping a list of courses.   It's both hard to keep up to date using public info, and potentially conflicts with privacy requirements when we use non-public info, making this complicated.
