### ISSUE TITLE
file creation: fix up the mess and revamp file creation.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2919]
We need to change our File creation system so there is only **one** way to make a file, and deferr when you have to name a thing. Naming things is hard!

> "Imagine if I had to name my puppy before I could even meet and buy her!"

What we need to do:

1. Replace the +New page entirely by a page called Library, and delete everything from there except the library.   (Later this could also have a new section which is a library of examples/templates of "Sage Worksheets", etc....)
2. Move the button in the files page currently labeled "Create" to the far left, rename it "+New", and ensure that it has options that are the most important file types in a group at the top, then a divide line, then *everything* in the current File menu of the *current* +New page.
3. If the user clicks the new +"New" button, which is ONLY available in the Files page, we generated a sequential filename such as "Untitled [n]".
4. We do the hard (but much needed anyways!) work to make file and directory renaming way easier. 

--- 

It would be nice if our new +New dropdown had 3 sections:

- the last five types you've used first, then a bar
- the popular well supported types (e.g., Jupyter, Sage, etc.),
- then a long list of everything else.

**Comment by williamstein** [comment]
The above is what to do.  Here's some discussion about why...

## I watched a user try to make a task list, and here's what happened

> The different ways messed her up? 0.o

It was absurd. 

1. She made something through +New, then deleted it.
2. She clicked on the create button, selected "Task list", then got the error about having to put a filename in the "box above".
3. She put a name in the box above, which changes the main file listing to show that name too with a HUGE button to make a sage worksheet, so she clicked that HUGE button (which in her mind clearly knew she had just tried to make a task list).  She got a sage worksheet.
4. Confusion about what the hell a sage worksheet is.  I stepped in and explained, so she deleted it.
5. She went back to files and clicked "create", then "Task list", and got the error again.
6. She typed the filename, hit return, and got a sage worksheet.
7. Delete sage worksheet.
8. Literally same problems again and *another* damned sage worksheet.
9. Click on +New, saw that page, and I guess thought "oops" and muttered, "definitely not this", and went back to the file listing.
10. Maybe made yet another sage worksheet... and another?
11. Finally, I told her what to do and she got a task list.
12. I think she just saw all the buttons or whatever, and thought "no way I can use this task list", and gave up.
13. I said "click +New to make a new task", so she... clicked the "+New" above and was back in the create files (and library and upload) page.  
14. I got her back to tasks, but at this point is was too late.

**Comment by williamstein** [comment]
## How other projects do it;

How do other apps solve the problem of "make a new file"? 

- ChromeOS:  strangely, they just don't?  I can't see any way to make a new file!  You just end up with files by saving or downloading something... 

- Google drive: There is a button in the upper left labeled "+New", much like we have.  When you click on it, there is a drop down listing types of docs.  You click and a new file *with no name* is created.  You can have several completely different files with the same "no name", which is "Untitled document".  So evidently the documents really have some underlying UID...   Basically, they put off the problem of when to name the file until later, and make it very easy to rename it (essentially decoupling from file system).  We can't do that.

- Dropbox -- a button on the right labeled "Create Paper doc".  Otherwise, it is identical to Google drive, where the file is "Untitled", and you can have many files at once with this same name and in the same directory.

- Jupyter --  you get a new "untitled [n]" file, which then you rename. What happens if you make two new files though? Both Dropbox and Google drive make two files with the SAME NAME. With Jupyter it makes "Untitled1" then "Untitled2", etc. That's more what I think we should do.  Incidentally, the "New" menu in Jupyter forces you to think about which kernel you want every time, with no intelligence about that you might ALWAYS be using Singular (say). 

- For example in word, when you make a new document it's untitled first.

**Comment by williamstein** [comment]
We still don't solve the problem illustrated by the user store above.  The easiest solution to that right now would probably be to just disable the file search --> create file functionality, which is clearly very confusing.  I never use it.

**Comment by vuluongj20** [comment]
@williamstein I would suggest deleting the file creation page, and keeping the drop-down menu as the only way to create files. If we can't implement post-creation naming, then we could just have a pop-up asking for file name the moment the user chooses a file type from the menu.

**Comment by haraldschilly** [comment]
@williamstein incidentally, I'm the opposite and use it to create files all the time. To me this sounds more like there shouldn't be a default filetype. 

@vuluongj20 I fear it's confusing for many users to remove it. Still, I like your suggestion to guide a user with a filename. Instead of the error, there could be a dialog panel with an input box to enter the filename, where the type is already fixed (visible, but can't be edited). The name itself could be prefilled and selected, such that you can either continue via a click or the return key, or start typing to change how it is called.
