### ISSUE TITLE
Install Sage package surface_dynamics

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2926]
Could this Sage package be installed system-wide:

- `surface_dynamics`: https://pypi.org/project/surface_dynamics/

Installation is easy:

    sage --pip install surface_dynamics

**Comment by jathreyauw** [comment]
I heartily endorse this request!

**Comment by haraldschilly** [comment]
I installed it, but it throws errors. I don't understand what's going on.

https://cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/sage-surface_dynamics.sagews?viewer=share

**Comment by haraldschilly** [comment]
ok, fun fact, it works in a jupyter notebook. Hence the issue above must be Sage Worksheet related …

https://cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/sage-surface_dynamics.ipynb?viewer=share

**Comment by haraldschilly** [comment]
follow up: #2930
