### ISSUE TITLE
Comments/Grading in courses

### ISSUE THREAD

**Issue by jathreyauw** [sagemathinc/cocalc#2928]
When grading in a course, comments don't save automatically while you are looking at the student file. So if you comment, and don't save manually, things are lost if you toggle back and forth between the student file and the comment file.

To see this, create a course, add students, and create an assignment. Collect the assignment, and open up the student file. Start to write a comment, and then go look at the student file. Your comment will be lost when you return.

**Comment by williamstein** [comment]
@johnjeng  fixed this.
