### ISSUE TITLE
salvus sage server problems with the surface dynamics module 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2930]
When running some commands of the surface dynamics module in a sage worksheet, they throw errors.

https://cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/sage-surface_dynamics.sagews?viewer=share

The same works in ipynb with a sage kernel

https://cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/sage-surface_dynamics.ipynb?viewer=share

code:

```
from surface_dynamics.all import Origami
o = Origami('(1,2)','(1,3)')
o.sum_of_lyapunov_exponents()
```

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.
