### ISSUE TITLE
share server: rename raw to download?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2933]
On a share server page for a shared file: I think for average users it is not clear that by clicking on "Raw" it is possible to download the actual file. Renaming it to "Download" might help.

![screenshot from 2018-06-21 11-34-03](https://user-images.githubusercontent.com/207405/41710864-03ead16c-7547-11e8-96fa-af73e156dbc9.png)

**Comment by slel** [comment]
More generally, it would be nice to have some extra text when you mouse over
each of "Open in CoCalc", "Raw", "Embed", to say a little more on what they do.

For instance, do I understand correctly that "Open in CoCalc" will
- open the original file if you are a collaborator on the project where it lives,
- create a new project for you with a copy of that file otherwise.

I don't know what "Embed" does.

**Comment by williamstein** [comment]
This is not what "raw" is. It is definitely *not* download, e.g., if you click on an html file, it just exactly loads that file in your browser and renders it.

**Comment by slel** [comment]
Right, "raw" links to the raw file, and what happens upon clicking depends on
the helper application set in one's browser preferences for this file type, if any.

Some 2-3 line explanatory text could get displayed when one hovers over
these links, to help one decide which one to click.

Maybe add a "Download" link to force downloading the file.

**Comment by haraldschilly** [comment]
Well, then I'm for removing any "raw" links. If not even I understand what this is supposed to be, what should an average user think what this is about?

**Comment by haraldschilly** [comment]
A while after I wrote that, I realized you must have been thinking about github. I never thought about that in the context of the share server. For me, a download link with the very same behavior would make perfect sense, though. I think we should come up with a list of actions we want to offer, and then sort them by priority.

**Comment by williamstein** [comment]
Yes, I was copying Github.

**Comment by williamstein** [comment]
Raw and download are different. There is now a Download link as well, which is download, and uses express's `res.download(...)`.

**Comment by slel** [comment]
Thanks for adding a "Download" link. Very nice to have!

Would there be a way to display some explanatory text
when one mouses over "Raw", such as for instance:

> Link to the raw file. Depending on the file type and on
> your browser settings, this could display the file in your
> browser, download it, or open it in another application

and a similar explanatory text for "Embed" (still not sure
what "Embed" is for).
