### ISSUE TITLE
CoCalc terminal and German keyboard: trouble with AltGr and dead keys

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2939]
Some issues with German keyboard in CoCalc terminal.

Using a German keyboard, one normally types
- `AltGr-7`, `AltGr-8`, `AltGr-9`, `AltGr-0`, `AltGr-+`, `AltGr-ß`
  to input `{`, `[`, `]`, `}`, `~`, `\`.
- a dead key for "acute accent" or "grave accent", followed by
  a letter key, to input accented letters, such as `é`, `è`, etc.

Under Windows 10 Pro, version 1803, build 17134.112, 
- using Opera 53.0, none of the `AltGr` key combos above work,
- using Firefox 60.0.2, `AltGr-7`, `AltGr-8`, don't work, the others work,
- the dead-key combos work fine.

Under Gentoo Linux, Firefox 52.8.0,
- `AltGr` combos work fine,
- dead-key combos don't work.

Reminiscent of previously reported issues with French and Spanish keyboards:
- https://github.com/sagemathinc/cocalc/issues/2211
- https://github.com/sagemathinc/cocalc/issues/2221

Might be solved by a Terminal rewrite (I know that's a lot of work!),
see https://github.com/sagemathinc/cocalc/issues/2671.

**Comment by williamstein** [comment]
Solved by our switch to xterm.js!

**Comment by slel** [comment]
Under Windows 10, using Opera as a web browser, and a German keyboard,
everything now works perfectly.

In particular `AltGr` `ß` now gives `\` and `AltGr` `+` now gives `~`,
and the `AltGr` `7` and friends for `{` and friends work too.

There subsists a glitch under Windows 10 with Firefox 62.0.2 (64-bit)
and a German keyboard, where typing `AltGr` `7` displays `(arg: 7)`,
and when another character is typed after that, it gets repeated 7 times,
e.g. `AltGr` `7` `e` yields `eeeeeee`. This sounds like a conflict with
some vim-mode or emacs-mode or something like that maybe?
