### ISSUE TITLE
completely quit using wordpress's gravatar functionality at reimplement something similar ourselves

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2948]
It's very awkward having to use Gravatar at all.  But beyond that, I just tried **several times** to change my gravatar at the wordpress site, and failed.  Maybe it will work eventually -- I just don't know...

**Comment by williamstein** [comment]
For the record -- it wasn't working due to browser caching.... We can do better (e.g., random query param).

**Comment by tscholl2** [comment]
Hopefully fixed by #2969

**Comment by williamstein** [comment]
Yes, this is even better than the request, since Gravatar is still an option!
