### ISSUE TITLE
cocalc tab of pdf file is not updated when file changes

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2968]
Try this in a cocalc xterm
```
date | pandoc -o foo.pdf
open foo.pdf
```
View the .pdf file. Now change it from the .term:
```
uptime | pandoc -o foo.pdf
```
Notice that none of the views, `PDF.js (svg)`, `PDF.js - Canvas`, or `PDF - Native` shows the new file contents until the browser is refreshed. Merely closing and reopening the file tab does not show the updated view.

**Comment by williamstein** [comment]
You're right -- I forgot to implement the "Reload" button (like we had before).  This should be easy, so I'll do it ASAP.
