### ISSUE TITLE
deleting an ipynb/jupyter file through the interface should delete the hidden jupyter2 file as well.

### ISSUE THREAD

**Issue by tscholl2** [sagemathinc/cocalc#2977]
Steps to reproduce:

1. Create an ipynb file named `a.ipynb`.
2. Go back to file list.
3. Select `a.ipynb`, hit delete, and confirm.
4. Run `ls -lah` in the terminal.

Expected: `.a.ipynb.sage-jupyter2` does not appear.

Actual: `.a.ipynb.sage-jupyter2` appears.

**Comment by haraldschilly** [comment]
The case I'm worried about is when the same file is created again. I mean, it's not clear why someone would do that, but it could happen. So, try this.

1. create `delme.ipynb`, do some 1+1 calculation, close it via "halt".
2. delete it
3. run `rm .delme.ipynb.sage-jupyter2`
4. open a file named `delme.ipynb` again

You're getting stuck at "Loading…" and well, to overcome this, you have to do something like restarting the project (well, local hub I guess) and close and reopen the project (or refresh browser tab). Maybe just try it and see what happens.

So, if you implement this, something needs to be recorded in the database about the deleted file. When it is created again, it should properly synchronize as being empty.

**Comment by williamstein** [comment]
It now does.

**Comment by williamstein** [comment]
I addressed this while I was at it in https://github.com/sagemathinc/cocalc/pull/4466
