### ISSUE TITLE
extraneous output with eqnarray in .sagews and .md

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2979]
Reported by Zachary Stone.

1. Run the following in a .sagews code cell and see normal array output.

    ```
    %html

    Test

    \begin{eqnarray}
    2\times2&=& 4\\
    2\times3&=& 6
    \end{eqnarray}

    Paragraph 1

    \begin{eqnarray}
    1+1&=& 2\\
    1+2&=& 3
    \end{eqnarray}

    Paragraph 2
    ```
1. Append the following lines to the same cell and run it again.
    ```
    <br>
    <br>
    Paragraph 3
    ```
1. Notice that the text lines, but not the equations, are repeated and out of order in the output.

Notes:

1. Incorrect output is cleared by refreshing the browser.
1. Incorrect output disappears if you tab away and come back a few minutes later.
1. Also seen in .md files.
1. Incorrect output persists in other tabs in the same browser window. If you copy the code into your clipboard and paste into another file, which may be .md as well as .sagews, and may even be in another project, you will see the incorrect output on the *first* run of the code, i.e. you won't have to run it twice to see the problem. This does not occur if you paste into a new file in a different browser window, i.e. if you copy the code from a Chrome window and paste into Safari.
1. You might not see the duplication on every attempt, but once it occurs, it is seen on every attempt to execute the code cell. If you don't see it using the steps above, try adding the following a few lines at a time:
    ```
    <br>
    <br>
    Paragraph 4
    <br>
    <br>
    \begin{eqnarray}
    1+2&=& 3\\
    1+3&=& 4\\
    \end{eqnarray}
    <br>
    <br>
    Paragraph 5
    ```

**Comment by williamstein** [comment]
> Also seen in .md files.

How?  Doing the steps above does NOT reproduce the problem in a Markdown file.  I would much prefer steps to reproduce the bug there, since it'll be much easier to fix, and will probably fix the sagews bug as a side effect.

**Comment by DrXyzzy** [comment]
One way to see the incorrect output in an .md file is to cause it to happen in a .sagews cell. Then copy the input of that cell into your clipboard. Open a new .md and paste the content there, and the bad output appears.
