### ISSUE TITLE
Sometimes unable to select outputs in Jupyter cells

### ISSUE THREAD

**Issue by kevinywlui** [sagemathinc/cocalc#2982]
I'm not always able to reproduce this but sometimes I cannot always select the output. Here's a gif of what I mean:
![trying_to_select_output](https://user-images.githubusercontent.com/1445341/42983114-bf8d37c6-8b99-11e8-99fd-a6be398f8795.gif)

**Comment by haraldschilly** [comment]
looks like a dup of #2884 … you made a nice screencast, though

**Comment by williamstein** [comment]
fixed long ago
