### ISSUE TITLE
when grading assignment, markdown comments are allowed but student receives .txt

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2987]
To see this:
1. Open a .course file and collect an assignment. 
1. Click `Enter grade` and note that markdown is allowed and rendered in the comments. Type in some markdown.
1. In the student project, in folder `graded-<assignment>`, see comments returned with markdown unrendered because they are in file `GRADE.txt`.

**Comment by johnjeng** [comment]
Fixed by a885ee926536b14e00aa7a4d49633bad1d9f4fb1 and https://github.com/sagemathinc/cocalc/commit/1e7b1d8faaca8b6c1c534c72155a6c96c858f3b4
