### ISSUE TITLE
(high priority) user search bug

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2991]
1. Search for "james davenport" to add as a collaborator to a project.
2. Get no results.

Do the same search as an admin; get a result!

![screenshot 2018-07-22 at 3 01 07 pm](https://user-images.githubusercontent.com/1276278/43050573-38294094-8dc0-11e8-9b15-3443d0ae1280.png)

Searching for James by his email address also works.  So something is messed up with the query.

**Comment by haraldschilly** [comment]
Some code is merged, but I'm not sure if we can close it. Maybe there are additional restrictions by time encoded in the webapp. So, until this is confirmed to work, we leave it open.

**Comment by haraldschilly** [comment]
this was fixed by me via another issue and two PRs.

**Comment by williamstein** [comment]
Heh, this is not fixed now :-(

**Comment by williamstein** [comment]
I'll fix this -- it's very easy.
