### ISSUE TITLE
latex editor custom build command bug -- it switches back if don't defocus quickly enough after changing

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2992]
1. Open a new latex document
2. In the "Build Control and Log" panel, try to change the build command a little by manually editing it.
3. Wait a bit and see it change back.
4. Instead change it and quickly defocus the input -- this works and saves the build command.

---

I'm guessing this is easy to fix and involves something dumb with state...   This is of course definitely a new bug caused by the latex editor rewrite into react/typescript, and it's my fault.

**Comment by williamstein** [comment]
I just found a little latex editor bug I introduced: https://github.com/sagemathinc/cocalc/issues/2992

I found this while trying out the markdown environment in latex: http://ftp.math.purdue.edu/mirrors/ctan.org/macros/generic/markdown/markdown.html#introduction

and wanting to [allow shell escape in pdflatex (instead of using slower luatex)](https://tex.stackexchange.com/questions/374160/how-to-have-latexmk-always-use-shell-escape).

Of course, it would be good to also have a checkbox in cocalc that allows shell escape.

**Comment by haraldschilly** [comment]
I raised the priority of this one, because it got impossible for me to make any changes to the command.
