### ISSUE TITLE
share server pages with issues

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2996]
there are a couple of publicly linked URLs on the share server, which (according to google) do not work. It might be worth to look into this, because if there is a problem with the share server code, it might block the service, cause an exception, etc.

Since they're all the same share, and related to that lmfdb database, it might just be that the files are too large (not sure about the .tex file, though). Hence the common fix might be to abort early with a suitable error message.

* https://cocalc.com/share/5d54f9d642cd3ef1affd88397ab0db616c17e5e0/www/Tables/an_s2g0new_301-400_hiprec.gp?viewer=share
* https://cocalc.com/share/5d54f9d642cd3ef1affd88397ab0db616c17e5e0/www/merel/ss_p1-499.gp?viewer=share
* https://cocalc.com/share/5d54f9d642cd3ef1affd88397ab0db616c17e5e0/www/breuil/report-03-28-01.tex?viewer=share
* https://cocalc.com/share/5d54f9d642cd3ef1affd88397ab0db616c17e5e0/www/Tables/an_s2g0new_401-500_hiprec.gp?viewer=share
* https://cocalc.com/share/5d54f9d642cd3ef1affd88397ab0db616c17e5e0/www/Tables/an_s6g0new_51-100_hiprec.gp?viewer=share

**Comment by williamstein** [comment]
The tex file is huge, but did load for me.  Some others time out.  

I think the right fix is that if a file is above a certain thresh in size (maybe 1MB), only render the first part of it, and at the bottom including a link to click to download the full file.   I think right now codemirror is trying to syntax highlight some MASSIVE files, and it just times out.  

I wonder what github does with HUGE files?  I think it just renders none of the file and gives a link... maybe.

**Comment by williamstein** [comment]
Definitely fixed now.
