### ISSUE TITLE
empty "blinking" project in projects listing

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3001]
sometimes, when I look at the projects listing, I see an empty row. it appears for one or two seconds, and then it goes away. few seconds later it's back again. hence why I call this "blinking".

I think this must have something to do with sync updates, because of the frequency and my general feeling. has anyone else ever saw that?

the screenshot below is representative, but it could also happen that such a ghost.entry is in the third row. if I ever see it again, I'll update this issue with a video.

![empty-project-on-projects-link](https://user-images.githubusercontent.com/207405/43220237-dcafb8a6-9049-11e8-9bb3-9da89852698a.png)

**Comment by williamstein** [comment]
I have also seen this...

**Comment by williamstein** [comment]
not seen in years.
