### ISSUE TITLE
terminal resize control codes

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3007]
Problem: the terminal doesn't work well if you do not use tmux

Workarounds: 
 - Type `tmux` in the terminal and use it.
 - Use ssh into your project instead -- see http://blog.sagemath.com/cocalc/2017/09/08/using-ssh-with-cocalc.html

This will get fixed soon via a proper rewrite of the underlying communications layer.

**Comment by haraldschilly** [comment]
I guess we can close this one?

**Comment by williamstein** [comment]
Yes.  If there any issues with codes appearing in terminals, they have nothing to do with *resizing*, which is the subject of this issue.  Instead, they would have to be caused by unsupported codes in the term.js renderer.
