### ISSUE TITLE
Install reveal-md

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#3011]
Please install reveal-md, whose slogan is:

> ## reveal-md
>
> reveal.js on steroids! Get beautiful reveal.js presentations from your Markdown files.

- Home page: http://webpro.github.io/reveal-md/
- Code repo: https://github.com/webpro/reveal-md

**Comment by haraldschilly** [comment]
done, but I'm not sure right now how this works in cocalc. maybe you could come up with a short tutorial tailored for cocalc?

```
~$ reveal-md --version
2.0.7
```
