### ISSUE TITLE
course bug: when you assign an assignment is counts it as assigned at the top even if it isn't finished (and if you cancel it, then it counts it as done, even though not done)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3013]
See screenshots:

![screenshot 2018-07-28 at 5 46 16 pm](https://user-images.githubusercontent.com/1276278/43361772-389e7030-928e-11e8-8c3c-a36188356999.png)
![screenshot 2018-07-28 at 5 46 08 pm](https://user-images.githubusercontent.com/1276278/43361773-38b415d4-928e-11e8-9b69-6b500b72baca.png)

**Comment by novoselt** [comment]
2/285 assigned seems to be a very clear message to me that something is not right. It should not remain "freshly blue" when something has already started. So then some other state has to be introduced. Or the count label should suffice.
