### ISSUE TITLE
latex editor: repeated build action (when cached) should trigger a force build

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3017]
imagine the following situation:

1. .tex file is built, but an external dependency is missing (sty file, etc.)
2. external dependency is added (uploaded), and the .tex file is kept the same
3. when clicking "build" again, there is no new build being done, because the last modified timestamp is still the same.

the proposal of this ticket is to send back some information from the project to the webapp that the command was not executed due to caching. then, after step 3, triggered by that piece of information,

4. exchange the build button to the "force build" button, and when the user clicks it, the force build is issued and the button changes back to the usual build button.

**Comment by williamstein** [comment]
As of now we have both build and force build buttons, and also there doesn't seem to be caching, since every time I click Build, the pdf is rebuilt, even if I don't change the file.

<img width="370" alt="image" src="https://github.com/user-attachments/assets/067c35da-8f82-4c40-bd9d-769ec4713a3c">
