### ISSUE TITLE
smc-sagews2ipynb could translate '%typeset_mode(true)'

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3021]
[Reported](https://groups.google.com/d/msg/cocalc/ffDHwde2_q8/UOAGkgeLCgAJ) by Juan Carlos Bustamante:

> I noticed that when converting from .sagews to .ipynb some code, like
> 
> typeset_mode(true)
> 
> is copied as is, instead of being replaced by
> 
> %display typeset

**Comment by williamstein** [comment]
There's presumably many subtle things that could be done but aren't...
