### ISSUE TITLE
GAP examples in jupyter assistant

### ISSUE THREAD

**Issue by tscholl2** [sagemathinc/cocalc#3027]
Steps to reproduce:

1. Open a jupyter notebook
2. Set the kernel to GAP
3. Click on the "Assistant" button

Expected: a great library of interesting examples for how to use GAP.

Actual:

![image](https://user-images.githubusercontent.com/8905985/43556625-efdf7e92-95bd-11e8-955e-671660e7f31c.png)

**Comment by haraldschilly** [comment]
→ [upstream](https://github.com/sagemathinc/cocalc-assistant)

well, adding at least one single example would be great, but I don't know any gap besides `1+1;` and the version number.

**Comment by haraldschilly** [comment]
duplicate #3040 points to a source for many examples

**Comment by haraldschilly** [comment]
closing, because there is work for the dup which points to the pdf
