### ISSUE TITLE
Some interacts in sage worksheets are pretty broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3035]
I'm just testing interacts a little in a Sage worksheets and tried:
```
@interact
def f(A=matrix(5,5)):
    print(A)
```

and:

- [ ] the submit icon next to the matrix is broken,
- [ ] I can't edit half the entries in the matrix at all! 

So this is bad.  The solution is to delete all this code and finish the react rewrite of sage worksheets and jupyter widgets. Then close this issue.

![image](https://user-images.githubusercontent.com/1276278/43611308-e2d7f348-9665-11e8-86c0-c4ce34e8e292.png)

**Comment by sj-graves** [comment]
Has there been any motion on this?

**Comment by williamstein** [comment]
> Has there been any motion on this?

One change is that CoCalc Jupyter notebooks now fully support @interact.  Create a Jupyter notebook, select a Sage kernel, and this example works really well:

![image](https://user-images.githubusercontent.com/1276278/66145601-0d3b9180-e5c0-11e9-95de-ce1a3893c84e.png)


```
@interact
def f(A=matrix(SR,3), auto_update=False):
    print(A, A.det())
```

You can also click the "Jupyter" button near the upper right of any Sage worksheet to convert it to a Jupyter notebook...

**Comment by williamstein** [comment]
http://doc.sagemath.org/html/en/reference/repl/sage/repl/ipython_kernel/interact.html

**Comment by williamstein** [comment]
If you want to use widgets, use Jupyter notebooks -- they are now fully supported in cocalc jupyter, and that is the path going forward.  I'll definitely not be working on the old widget model in sage worksheets ever.  Closing this.
