### ISSUE TITLE
jupyter loses edit mode on switching tabs/alt-tab

### ISSUE THREAD

**Issue by tscholl2** [sagemathinc/cocalc#3041]
Steps to reproduce:

1. Open a ipynb file
2. Start editing a cell
3. While still in "edit mode", switch browser tabs or alt-tab to a different window
4. Go back to the jupyter notebook

Expected: You are still in "edit mode" and any selection is still selected

Actual: You are not still in "edit mode" and any selection is lost

**Comment by williamstein** [comment]
Key point: our code editors and Sage worksheets do NOT loose focus when doing the exact same thing.  It's just CoCalc jupyter that has the problem.

**Comment by williamstein** [comment]
Heh, I guess I accidentally fixed this with my react-windowed work...
