### ISSUE TITLE
markdown: emojis should be ignored in code blocks (and other places?)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3043]
1. Put this in a chat message (or anywhere that does markdown):
<pre>
```
:-)
```
</pre>

2. See this mess:

![image](https://user-images.githubusercontent.com/1276278/43663011-26d8e218-9725-11e8-8dab-32368957afc5.png)

---

What should happen is what happens above with github...

**Comment by haraldschilly** [comment]
we'll might want to deprecate what we have and also introduce using an emoji picker like http://blog.tommoor.com/emojione-picker/

**Comment by williamstein** [comment]
We should switch to using unicode for emoji, which just makes this problem go away.

**Comment by williamstein** [comment]
There's a similar bug in math mode:

![image](https://user-images.githubusercontent.com/1276278/103972348-ab9e9700-5121-11eb-9353-646f1235b951.png)

**Comment by williamstein** [comment]
Fixed in 0d766b118215257c66ce4a7bfadcdd72be7bbe7a, which isn't merged into master yet, but will be soon-ish.

**Comment by williamstein** [comment]
That's a commit in this branch: https://github.com/sagemathinc/cocalc/pull/5147
