### ISSUE TITLE
printing the rendered rmarkdown often doesn't show graphics (or work at all)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3044]
1. put this as the input to an .rmd file:
<pre>
---
title: "More colors"
output: html_document
---

```{r include = FALSE}

# colorFunc <- "heat.colors"
colorFunc <- "terrain.colors"
# colorFunc <- "topo.colors"
# colorFunc <- "cm.colors"
# colorFunc <- "rainbow"
```

Base R comes with many functions for generating colors. The code below demonstrates the `r colorFunc` function.

Blah blah!

## `r colorFunc`

```{r fig.cap = "The Maunga Whau volcano.", echo = FALSE}
image(volcano, col = get(colorFunc)(5))
```
</pre>

2. On save, see an image on the right
3. Try to print the preview on the right, and it doesn't work.

See:

![image](https://user-images.githubusercontent.com/1276278/43665582-e6312294-972d-11e8-9555-fc6f2ec03e82.png)

**Comment by haraldschilly** [comment]
I tried this and it works fine out of the box. So, I'm not sure if we could ever fix this. It's 1 1/2 years old …

![Screenshot from 2020-06-19 20-17-43](https://user-images.githubusercontent.com/207405/85168012-0ba71c00-b26a-11ea-8eba-0dff630b93c2.png)
