### ISSUE TITLE
wrong directory listed in path

### ISSUE THREAD

**Issue by tscholl2** [sagemathinc/cocalc#3046]
Steps to reproduce:

1. Make two directories: `dirA` and `dirAB`
2. Put a file `a` in `dirA` and a file `b` in `dirAB`
3. Navigate to `dirAB`, you should see `b`
4. Navigate up a directory
5. Navigate to `dirA`, you should see `a`

Expected: the path is `~/dirA`

Actual: the path is `~/dirAB` 

---

edit: a line to quickly set this up: `mkdir test; mkdir test/dirA; mkdir test/dirAB; touch test/dirA/a; touch test/dirAB/b; open test/dirA/a`

**Comment by haraldschilly** [comment]
QA: confirmed to be fixed in prod
