### ISSUE TITLE
syntax highlight the blocks of r code in rnw/rtex files

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3047]
This is easy using a codemirror multimode, like is done for sage worksheets.  This will also dramatically improve the usability of our rtex editor.

**Comment by williamstein** [comment]
Similar remark applies for rmd files.

**Comment by williamstein** [comment]
And sagetex in latex...

**Comment by haraldschilly** [comment]
and Rnw files?

**Comment by haraldschilly** [comment]
closing, see screenshot in https://github.com/sagemathinc/cocalc/pull/3193
