### ISSUE TITLE
when grade is entered it sometimes vanishes from the form

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3049]
Reported by Gabriela Dorfman Furman:

In a course, after distributing an assignment:
1. Click the "Collect .." button (task)
1. Try to write in the window under the caption "Enter Grade" (where it says "Grade (any text) ...")
1. After a few seconds the grade is deleted (like nothing is written) or the save button does not work

Sometimes, if the bug does not appear at first, you can hit tab to enter a comment, then shift-tab to go back and enter new text for the grade, and _that_ grade vanishes after a second or so.

Seen with browsers: 
- Chrome 67 on Windows
- Safari 11.0.3 on macOS

May be related to #2928 - grade & comments are not retained on tabbing away and back.

**Comment by williamstein** [comment]
Thanks.  This is definitely a super high priority blocker to fix!
