### ISSUE TITLE
in file listing, make public button a link to the public path

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#305]
right now, the "public" button has no real action, right? make it a link pointing to the public path ... 

i.e. such that right click & copy link gives you the path for sharing.

**Comment by williamstein** [comment]
huh?

**Comment by haraldschilly** [comment]
yes, I think that would be a good feature. I don't know how to describe it better, but I'll assign it to me instead of @leejt

**Comment by haraldschilly** [comment]
well, the public button opens up the share dialog, where there is the link. no need for this ticket any more.
