### ISSUE TITLE
course: provide a *compact* grade view

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3062]
Basically, the request is for a more compact view without needing to expand anything of all the grades for students on assignments.  It's just another view of the same info:

> "It would be nice if a student saw his or her list of grades immediately, instead of clicking on 'Grade.txt' files separately for each problem.  Same for professor, better user interface; now you have to download, and expand columns to see everything properly. In university gradebooks such feature is available, and I am quite used to this."

REQESTED BY: Andrew Sarantsev

**Comment by novoselt** [comment]
If it ever gets requested again, it would be nice to have a more clear description of how exactly the current UI should be changed to work better.
