### ISSUE TITLE
course: always allow editing student name

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3066]
>  Dear William Stein, I added some of the students via emails; now they are recorded as <wstein@gmail.com>. However, I would like to add the name 'William Stein' as first and last name (which are currently occupied by their email).

Once they have created an account there will be a button "Edit
Student" under their name, where you can put any name you want.
Unfortunately, this button doesn't show up until after the student
creates an account.

**Comment by novoselt** [comment]
Done!
