### ISSUE TITLE
Can't install an R package (lib is not writable)

### ISSUE THREAD

**Issue by michaelkuzmin** [sagemathinc/cocalc#3068]
I'm new to cocalc so maybe I'm missing something super obvious. I am trying to install a couple of packages and I am getting the same error. I am getting this error both when I try to run this from a terminal and from jupyter. I am using a regular monthly subscription. 

> install.packages("marima")
> 
> Warning message in install.packages("marima"):
> “'lib = "/ext/sage/sage-8.2_1604/local/lib/R/library"' is not writable”
> Error in install.packages("marima"): unable to install packages
> Traceback:
> 1. install.packages("marima")
> 2. stop("unable to install packages")

**Comment by michaelkuzmin** [comment]
When I tried to follow the wiki I first got the same error with the other instance of R. Then I tried the alternative route with R-sage. It asked me if I wanted to install to a local lib instead, I said yes, and it finally worked. Then I tried the original instance, and it worked again. So it was just temporarily not allowing me to install, maybe something to do with the fact that I only recently purchased a subscription. Not sure. The point is, it works now. But it took a couple of attempts. Also, maybe the wiki should have a quick explanation as to how to get to the terminal :)

**Comment by haraldschilly** [comment]
I think the confusion is the distinction between `R` (as written in the wiki entry) and not `r` (which is the special "littler" wrapper). Although I can't understand why it tries to install in the sage R library path...

for future readers, our wiki notes are here: https://github.com/sagemathinc/cocalc/wiki/Programming#Rpack

**Comment by slel** [comment]
The link ending in `#Rpack` does not seem to send to the correct place in the page.
Try this one instead:
https://github.com/sagemathinc/cocalc/wiki/Programming#-question-i-would-like-to-install-new-r-packages
