### ISSUE TITLE
the Singular Jupyter kernel silently swallows error messages

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3071]
This is maybe an upstream issue...

First, in Singular itself, using fractions without declaring a ring is an error:
```
~/cocalc/src$ Singular
                     SINGULAR                                 /
 A Computer Algebra System for Polynomial Computations       /   version 4.0.3
                                                           0<
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \   Jan 2016
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \  Debian 4.0.3+ds-1
> 1/3 + 4/3;
   ? no ring active
   ? error occurred in or before STDIN line 1: `1/3 + 4/3;`
> 2 + 3;
5
> Auf Wiedersehen.
```

Now let's try the Singular kernel:

```
~/cocalc/src$ jupyter console --kernel=singular
/usr/local/lib/python3.5/dist-packages/jupyter_console/ptshell.py:95: UserWarning: No lexer found for language 'singular'. Treating as plain
text.
  warn("No lexer found for language %r. Treating as plain text." % name)
Jupyter console 5.2.0
 
Singular Jupyter Kernel
 
In [1]: 1/3;
 
In [2]: 2 + 3;
Out[2]: 
5
  
 ```

As you can see above, it silently ignores the errors with fractions. 

Same sort of problems when the kernel is used via CoCalc Jupyter, which also strangely shows something about `skipping text from... error at token` (??).

![image](https://user-images.githubusercontent.com/1276278/43965340-d3c480ba-9c73-11e8-823b-3f319066949f.png)

Of course, everything works just fine in Sage worksheets, since they use the singular <--> Sage pexpect interface that I wrote in 2006 (?), which is evidently much better than the official Singular Jupyter kernel (how can that be!?).  See, the error is probably shown below:

![screenshot 2018-08-10 at 8 07 55 am](https://user-images.githubusercontent.com/1276278/43965633-9dc40b7e-9c74-11e8-938a-85009c1100cc.png)

**Comment by slel** [comment]
cc @sebasguts

**Comment by sebasguts** [comment]
Thanks for noticing. I think this is a problem with the Python-Singular-Wrapper. It is supposed to be more stable than the pexpect interface, but sometimes swallows errors because of the way it is written. Anyway, I will try to get this issue fixed on monday.

**Comment by slel** [comment]
Please install upgrade to the latest Singular and pip install PySingular.

**Comment by sebasguts** [comment]
Or just set the `PATH` to the Sage bin dir, so it finds a `libsingular-config` executable.

**Comment by haraldschilly** [comment]
Hmm, I don't really know how the kernel works. What's on CoCalc is something that already calls Sage's Python. It also loads the module installed within sage's own universe. Is there maybe another (better?) way to define the kernel? Below is a copy of terminal session running in a cocalc project.

```
$ cat /ext/jupyter/kernels/singular/kernel.json 
{
    "argv": ["sage", "--python", "-m", "jupyter_kernel_singular", "-f", "{connection_file}"],
    "codemirror_mode": "singular",
    "display_name": "Singular",
    "env": {
        "PS1": "$"
    },
    "language": "singular"
}
$ which sage
/ext/bin/sage
$ sage --version
SageMath version 8.6, Release Date: 2019-01-15
$ sage --python
Python 2.7.15 (default, Jan 15 2019, 23:15:18) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jupyter_kernel_singular
>>> jupyter_kernel_singular
<module 'jupyter_kernel_singular' from '/ext/sage/sage-8.6_1804/local/lib/python2.7/site-packages/jupyter_kernel_singular/__init__.pyc'>
```

**Comment by slel** [comment]
Workaround for now is to use SageMath's Singular and the latest PySingular, as follows:
```
$ export PATH=/ext/sage/sage/local/bin:$PATH
$ pip install PySingular --upgrade --user
```
Then the kernel works.

**Comment by haraldschilly** [comment]
ok, I think I finally understand. Installing `PySingular-0.9.7` in Sage's python environment. 

That "PATH=..." line above is pointless for the kernel. that way you just change which pip you use. Instead, just run `sage -pip install ...` :peace_symbol:

**Comment by haraldschilly** [comment]
nope, sorry, I still don't get it.

what I did: update PySingular from 0.9.6 to 0.9.7 in the Sage environment. confirmation:

```
$ sage --python
Python 2.7.15 (default, Jan 15 2019, 23:15:18) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.get_distribution("PySingular").version
'0.9.7'
```

ok. but this still fails:

```
~/smc-build$ jupyter console --kernel=singular
/usr/local/lib/python3.6/dist-packages/jupyter_console/ptshell.py:95: UserWarning: No lexer found for language 'singular'. Treating as plain text.
  warn("No lexer found for language %r. Treating as plain text." % name)
Jupyter console 5.2.0

Singular Jupyter Kernel


In [1]: 1/3;

In [2]: 3+3;
Out[2]: 
6
```

**Comment by sebasguts** [comment]
The `PATH` is actually to make `libsingular-config` available to the setup.py file.

I do not really get it, in the notebook it works. 
```
ring r;
1/3;
```
gives you `0` for me.

**Comment by haraldschilly** [comment]
So, I don't know much about Singular, sorry, and I have the impression we talk about at least two different things.

When I run Sage's Singular, I get this (I removed some lines to make it obvious):

```
~$ sage -singular
> 1/3;
   ? no ring active
   ? error occurred in or before STDIN line 1: `1/3;`
> Auf Wiedersehen.
~$ sage -singular
> ring r;
> 1/3;
10668
> Auf Wiedersehen.
```

when I run it in the jupyter console, I get this:

```
~$ jupyter console --kernel=singular
/usr/local/lib/python3.6/dist-packages/jupyter_console/ptshell.py:95: UserWarning: No lexer found for language 'singular'. Treating as plain text.
In [1]: 1/3;

[NO OUTPUT !!!]

~$ jupyter console --kernel=singular
In [1]: ring r;
// ** Could not find dynamic library: p_Procs_FieldZp.so (path /ext/sage/sage-8.6_1804/local/bin/../libexec/singular/MOD:/ext/sage/sage-8.6_1804/local/libexec/singular/MOD)
// ** Error message from system: /ext/sage/sage-8.6_1804/local/bin/../libexec/singular/MOD/p_Procs_FieldZp.so: undefined symbol: omAllocBinFromFullPage
// ** Singular will work properly, but much slower.
// ** See the INSTALL section in the Singular manual for details.

In [2]: 1/3;
Out[2]: 
10668
```

I tried to update PySingular, with setting the path as samuel mentions, but that just led to stacktraces about pexpect not being able to read something, etc. 


question: What does anyone here mean by "does not work" ? William and I refer to the missing warning output. See first message here, far above. That's the scope of the ticket.

I'm curious about what needs to be installed to see these warning messages. (which packages, at exactly which versions.) I assumed updating PySingular in Sage does this, what's why I wrote about installing it in the sage env above.

**Comment by sebasguts** [comment]
I think @slel and me messed up two different problems here.

I will try to clarify a bit, as I think people might have messed up in different ways. The warning
```
// ** Could not find dynamic library: p_Procs_FieldZp.so (path /ext/sage/sage-8.6_1804/local/bin/../libexec/singular/MOD:/ext/sage/sage-8.6_1804/local/libexec/singular/MOD)
// ** Error message from system: /ext/sage/sage-8.6_1804/local/bin/../libexec/singular/MOD/p_Procs_FieldZp.so: undefined symbol: omAllocBinFromFullPage
// ** Singular will work properly, but much slower.
// ** See the INSTALL section in the Singular manual for details.
```
does not appear in the notebook, but in the jupyter console and in Singular because Singular prints it directly to stderr, and not, like for most of the output, into a buffer. There is no way I can actually fix this in PySingular (the jupyter_kernel_singular Python/Singular communication layer) as I only intercept the buffer, and not the standard streams (which is actually the right thing to do I think, Singular is simply inconsistent here about its printing behaviour). It comes from a bad linking I still have to fix, though.

The second warning
```
   ? no ring active
   ? error occurred in or before STDIN line 1: `1/3 + 4/3;`
```
I am not sure where it is lost, it needs to be investigated. It says it is an error message, but might actually be a warning. Errors should be returned by the kernel (and are, mostly). I have a handler for warnings in `PySingular`, but it is not used. So maybe it is something I wanted to implement but never got to. I will check.

**Comment by haraldschilly** [comment]
Ok, I see, thank you @sebasguts 

ad 1) it did still show up something, so that error is there but it wasn't breaking everything. ok.

ad 2) Yes, that's what this is about, and this confirms the "upstream" tag. I think the best way forward is to actually create an upstream ticket about this and link to it :fireworks:

**Comment by sebasguts** [comment]
@haraldschilly 
1.) Yes, it is not breaking anything, but Singular says it might run slower (couldn't confirm though). Needs to get fixed, but might be terrible to do so.

2.) Upstream means my repo?

**Comment by williamstein** [comment]
We do not support the Singular kernel anymore, so i'm closing this.
