### ISSUE TITLE
course: do not change the shared project name after the shared project is initially created.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3073]
Typically the title/desc of the course is already set and correct when the shared project is created.  Some people are confused that whenever the course runs it's "set state of all associated projects properly" loop, it resets the title of shared project to the title that is a function of the course title.

So... let's just not modify the shared project title/desc, after the shared project is initially created.

REQUESTED BY: Thomas Graf

**Comment by novoselt** [comment]
Whatever the current state is, it does not seem to cause issues.
