### ISSUE TITLE
ideas for display of list of published files on the share server

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3076]
Add these and allow sorting the list of published files by any of them:
- allow subscribers to upvote published files
- show access count for published files
- remember when I last visited published files

Consider also, subscribing to publishing events: 
- subscribe to author
- subscribe to project

**Comment by williamstein** [comment]
I like these ideas, but this feels way to general to be an issue.  I've copied this to our internal markdown doc of ideas and closed.   One issue for now is that the share server currently **can't** be signed into, due to security concerns...
