### ISSUE TITLE
add calendar support for courses, e.g. CalDAV

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3082]
Requested by William Kronholm. Context: teaching classes with CoCalc.

> I was wondering if there has been any thought given to granting users access to a CalDAV (or similar) calendar which includes the due dates for assignments, etc.

**Comment by DrXyzzy** [comment]
Specifics on the feature request from William Kronholm:

> It would be great if students in a class could view a calendar which 
showed assignment due dates. If they could also subscribe to that 
calendar to view elsewhere (Google calendar, iCal, or whatever else they 
might use), that would be terrific. The students in a class would only 
need read access to that calendar.
>
> It would also be great if the instructor for a class could add other 
events to that same calendar, so it becomes more of a course calendar, 
rather than just an assignment calendar.

**Comment by novoselt** [comment]
Closing as stale, we can open a new issue if there will be demand.
