### ISSUE TITLE
jupyter2: add "Shutdown" menu entry in "Kernel"

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3094]
Below "Restart and eval all..." add a "Shutdown" entry.

![screenshot from 2018-08-17 16-26-06](https://user-images.githubusercontent.com/207405/44271383-4426da80-a23a-11e8-9ad5-bfe49e52b979.png)

**Comment by williamstein** [comment]
This exists now-a-days:

<img width="418" alt="image" src="https://github.com/user-attachments/assets/1220b071-f936-4f36-a9ca-e3503f5e9909">
