### ISSUE TITLE
jupyter2: eval button next to code cell

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3096]
On the left of a code cell, add some sort of non-obtrusive button to evaluate it. We don't want this to be on hover like the classical one has.

![screenshot-cocalc com-2018 08 17-16-30-43](https://user-images.githubusercontent.com/207405/44271625-ed6dd080-a23a-11e8-9066-e6300417c277.png)

**Comment by williamstein** [comment]
We have a nice run button now, which even has a dropdown option for some common run-all cases that are relative to a particular cell:

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/8eb9cabd-9bf4-460f-80b2-649fdc099356">

Of related interest, there was discussion about bringing a run button to JupyterLab today https://github.com/jupyterlab/jupyterlab/pull/16602
