### ISSUE TITLE
Error encountered when trying to use the handout option in cocalc

### ISSUE THREAD

**Issue by subhamghosh** [sagemathinc/cocalc#3097]
I am using a cocalc docker image in Ubuntu 16.04 server. When I am trying to handout a document present in handout folder to Students I am getting the below error.

copy to student: Project(project_id=3d9bd9e7-26d7-4245-8f35-70736c01ad18).cmd(...): 
rsync --update --backup -zaxs --omit-link-times --chown=50869217:50869217 --ignore-errors --exclude=.sage/cache --exclude=.sage/temp --exclude=.trash --exclude=.Trash --exclude=.sagemathcloud --exclude=.smc --exclude=.node-gyp --exclude=.cache --exclude=.forever --exclude=.snapshots --exclude=*.sage-backup --exclude=*.sage-history -e 'ssh -o StrictHostKeyChecking=no -p 22' /projects/3d9bd9e7-26d7-4245-8f35-70736c01ad18/take/ localhost:/projects/9c3b6073-9e53-406e-9237-0895aac295bd/take/
Project(project_id=3d9bd9e7-26d7-4245-8f35-70736c01ad18).copy_path(...): rsync error: [Errno 2] No such file or directory
Traceback (most recent call last):
File "/usr/local/bin/smc-compute", line 12, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1076, in main
args.func(args)
File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 943, in g
result = getattr(Project(project_id=project_id, dev=args.dev, projects=args.projects, single=args.single, kucalc=args.kucalc), function)(**kwds)
File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 915, in copy_path
raise RuntimeError(mesg)
RuntimeError: [Errno 2] No such file or directory

**Comment by haraldschilly** [comment]
Hi, I'm closing this ticket because there is https://github.com/sagemathinc/cocalc-docker/issues/25
