### ISSUE TITLE
Loading cocalc on older browsers is broken -- provide better feedback

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3098]
Sequoia tried to load CoCalc on his laptop, thinking he was running the latest version of Chrome (since it didn't offer to upgrade). In fact, he was running Chrome 54.x, which is from 2016, so pretty old. In any case, our source code couldn't load, failing with a syntax error.

It would be better for us to give an error and say "use a modern browser", rather than having the sign in page mysteriously just fail to load after a minute!

Alternatively, maybe we can add more options to webback/typescript so cocalc works on slightly older browsers (or at least compiles).

He had the same problem with Safari on his laptop.

This could be a common issue for students.

**Comment by williamstein** [comment]
I at least updated our troubleshooting page:

https://github.com/sagemathinc/cocalc/wiki/Troubleshooting#the-10-step-process-for-debugging-connectivity

**Comment by haraldschilly** [comment]
Closing, because https://github.com/sagemathinc/cocalc/pull/3129 is merged. As of writing this we check for minimum browser versions before any code of the main application runs.
