### ISSUE TITLE
update jupyter kernel for sagews python3 mode

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3104]
Sagews uses the anaconda3 jupyter kernel for [%python3 mode](https://github.com/sagemathinc/cocalc/blob/master/src/smc_sagews/smc_sagews/sage_salvus.py#L1853) at present, but the latter is no longer preferred.

We should change the kernel to `Python 3 (Ubuntu Linux)` or `Python 3 (Anaconda 5)` and notify users.

**Comment by haraldschilly** [comment]
Is this closed because https://github.com/sagemathinc/cocalc/issues/3114 is resolved?

That's how it looks now:

![screenshot from 2018-08-30 16-56-08](https://user-images.githubusercontent.com/207405/44860122-db961f80-ac75-11e8-87f5-c34644359815.png)
