### ISSUE TITLE
Add anaconda and python3 modes to the Modes dropdown in Sagews

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3114]
Followup to https://github.com/sagemathinc/cocalc/pull/3112

**Comment by haraldschilly** [comment]
I'm closing this, the PR is merged, and just for the record, here's how it resolves right now:

![screenshot from 2018-08-30 16-56-08](https://user-images.githubusercontent.com/207405/44860017-a1c51900-ac75-11e8-851e-c36fee2fd44a.png)
