### ISSUE TITLE
drag and drop upload of folders can fail

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3121]
1. Reported by Karl-Dieter Krisman with Safari 10 on OS X 10.12 (Sierra).

> When I click on the + button and then try to drag and drop folders (not individual files), not only does it not upload them (image with red x button) but it gives a weird error message "Server responded with 0 code". That isn't really helpful; instead maybe it should say "uploading folders not allowed" or something like that. This is on Safari 10, if it matters 

2. Reported by @williamstein:

> I tried folder upload on my Chromebook with ChromeOS 70 (so dev channel) and it did NOT work; in fact, there's no error -- it just silently fails.

> This test site also just silently fails on folders for me... https://www.dropzonejs.com/examples/simple.html
so I guess it is just not supported for chrome 70.

> In any case, probably an issue needs to be created to better support folder upload. We could switch from dropzone to something else too...

3. I [hal] was not able to get any folder uploads to fail using drag and drop with macOS 10.13.6 and Safari 11.1.2 (13605.3.8), but noticed that the effect of dragging and dropping multiple folders into the upload dropzone is that all file in all folders are copied to the current directory in the project. I would have expected the folders to appear at the destination with their contents copied into the separate folders.

**Comment by mforbes** [comment]
Some of my colleagues also pointed this out.  We expected that dragging a folder would preserve the folder structure. For those stumbling on this, workarounds include uploading a tarball, which, you can double click and it will extract the folder.

```bash
tar -zcvf my_folder.tgz my_folder
```

or to use `scp` or `rsync` as [discussed in the docs](https://doc.cocalc.com/howto/upload.html).

**Comment by williamstein** [comment]
I'll give fixing this a quick look right now
