### ISSUE TITLE
automatically open account sign up page with email pre-filled for invited non-user

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3128]
When inviting a non-cocalc user to cocalc, make a single link to click on, which initiates the account creation process with the email address already filled in with the proper one for the user they are creating.

This will be especially helpful for setting up courses. A frequent cause of support issues is students logging in with different email than what the instructor used to add them to a course.

**Comment by williamstein** [comment]
Could also include metainformation in the sign up (URL) to ensure that the user gets added to the right projects when they sign up, even if they change their email or use an SSO link.   Ideas/thoughts?

**Comment by DrXyzzy** [comment]
How will this work for a professor who pastes in a list of e.g. 40 student emails if many of them are non-users?

Agree it is important to allow for changes of email address. Prof might enter a misspelled email address. A student might have to change email address, so for courses this might not be just an issue at time of account creation.

**Comment by novoselt** [comment]
I can see how this can be useful, but students can change a prefilled email, so it won't completely solve the problems. And for students who already have a CoCalc account with a different email address, it would make more sense to allow easy switch of the invitation to that different account.
