### ISSUE TITLE
task list pre format markdown mangled

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3131]
In CoCalc tasks lists this gets mangled:
```
def fib : ℕ → ℕ
| 0 := 1
| 1 := 1
| (n+2) := fib (n+1) + fib n

#eval fib 50
```

![image](https://user-images.githubusercontent.com/1276278/44765489-c3a18d00-ab09-11e8-929d-23a14e90c394.png)

**Comment by slel** [comment]
Note: this mangling happens both when the code block is marked as such
by being indented or by being surrounded by triple-backquotes (contrary to
the dollar issue at #2863 where things work well with triple-backquotes).

**Comment by williamstein** [comment]
fixed :-)  No more mangling...
