### ISSUE TITLE
cocalc becomes unresponsive on multifile latex documents

### ISSUE THREAD

**Issue by tscholl2** [sagemathinc/cocalc#3134]
Steps to reproduce:

1. Clone [ENT](https://github.com/williamstein/ent)
2. Open `ent.tex` (this takes a moment, but works fine and gives a nice preview)
3. Open `body.tex`

Expected: A working latex editor (bonus: working preview).

Actual: It looks like its loading a preview, and the editor works for a moment, but soon the whole page stops responding.

**Comment by williamstein** [comment]
Dupe of https://github.com/sagemathinc/cocalc/issues/904
