### ISSUE TITLE
empty time in project_log entries

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3140]
in our kucalc project, I saw a strange entry in the project log table

![screenshot from 2018-08-31 16-32-40](https://user-images.githubusercontent.com/207405/44918538-86bcdc80-ad3b-11e8-9aa7-4090f29405a8.png)

looking at the database, there are such entries without a time, like the first one … the second one is fine (I ordered by time)

`select * from project_log where project_id ='f8cf98ed-299e-4423-a167-870e8658e081' order by time desc limit 50;`

```
-[ RECORD 10 ]----------------------------------------------------
----------
id         | 016ae27c-d699-4194-b646-c2e1e28bf77a
project_id | f8cf98ed-299e-4423-a167-870e8658e081
time       |
account_id | 3c40513b-7e7c-450c-aa13-bf4f3411cf33
event      | {"time": 42706}
-[ RECORD 11 ]----------------------------------------------------
----------
id         | 364a5a89-53c5-4244-a40a-e56c905e58e2
project_id | f8cf98ed-299e-4423-a167-870e8658e081
time       | 2018-08-31 14:29:22.628
account_id | 3c40513b-7e7c-450c-aa13-bf4f3411cf33
event      | {"event": "open", "action": "open", "filename": "post ...
```

**Comment by williamstein** [comment]
I'm not seeing this sort of thing anymore. Not really worried about it.  I think they get filtered out if there are some old ones anyways...
