### ISSUE TITLE
provide feedback when a user verifies their email -- right now there is NOTHING, though it works

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3147]
I just tried verifying the email for one of my accounts on prod and it worked fine... though the UI is **really "bad"** -- you click the linked and are logged into CoCalc with no feedback at all about having just verified your email address.  Checking account settings, I saw that the verified state changed at least though.

Marking this as a bug, since the expected behavior of clicking a "verify email" link includes ending up at a page, or seeing a message, which says "You have successfully verified your email".  Even an `alert_message` notification would be better than nothing (and one easy line of code).

**Comment by haraldschilly** [comment]
dup of #2506
