### ISSUE TITLE
if you click the email verification link and are taken to cocalc, but are not ALREADY signed in, then it does not work at all.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3148]
Often in a mail client when you click a link, you visit that link in possibly a different browser or session then you might normally use.  If you visit the "verify email" link and don't happened to be signed in, then... you are just asked to sign in and the email verification part of the url is removed.

Is it ever going to work?  I don't know.

**Comment by williamstein** [comment]
I've pushed a change to master to disable email verification until this is properly implemented.

**Comment by haraldschilly** [comment]
why is it broken in this case? I don't remember any of the code, though.

**Comment by haraldschilly** [comment]
I still don't understand this. It was always the case that you could verify your email by visiting the provided link. No matter if you're already verified or signed in.  The only case where it doesn't work if there are several tokens floating around. Only the most recent one will work. I'm closing this.
