### ISSUE TITLE
Improve rmd Codemirror mode to properly syntax highlight code blocks

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3153]
In RStudio, the code blocks in rmd files are properly syntax highlighted:
<img src="http://r4ds.had.co.nz/rmarkdown/diamond-sizes-notebook.png" width=600>

In CoCalc, they are not:
<img src="https://user-images.githubusercontent.com/207405/45224277-dbbb9e00-b2b9-11e8-9fef-78606b6378f2.png" width=600>

Fix this by defining a Codemirror multimode for rmd files, like the sagews multimode.

**Comment by haraldschilly** [comment]
Rmd is covered, and I'm aware of https://github.com/sagemathinc/cocalc/issues/3047 being still open

![screenshot from 2018-09-13 16-28-15](https://user-images.githubusercontent.com/207405/45820289-bc276b00-bce6-11e8-8d96-b514a65c98b9.png)
