### ISSUE TITLE
add student project indicator to projects listing

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3155]
when looking at the list of projects, a "course project" looks like any other project. the goal of this ticket to show additional information in the entry, such that it is clear that this is a project part of a course, and maybe explain which course it is.

in practice, make some optionally available data from the "course" column visible to the user.

**Comment by novoselt** [comment]
This is too vague and assumes that the project is dedicated to a single course, not that it just happens to have a .course file, which is not necessarily unique.
