### ISSUE TITLE
support pythontex3

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3160]
goal: the cocalc latex editor should "automagically" support pythontex ... just like sagetex

details: unclear, but we were able to make this work for sagetex!

**Comment by profbrady** [comment]
I was able to make it work with a `.latexmkrc` file that I found [here](http://mirror.hmc.edu/ctan/support/latexmk/example_rcfiles/pythontex-latexmkrc) and modified as shown below. I put the `.latexmkrc` file in the same folder as the LaTeX file that includes pythontex and it worked perfectly. Where should I put the `.latexmkrc` file so it works regardless of where I make my LaTeX file? 

```
# This shows how to use the pythontex package with latexmk
# This **present** version (1 April 2018) it only works when
#   the operating system and the file system support symbolic
#   links (e.g., linux, OS-X and other unix implementations with their
#   usual file systems).  It is **not** tested on MS-Windows, but
#   **may** work on recent versions.
# In the future, a version of latexmk may provide better support
#   without the restrictions.

# This version also has a restriction that on initial runs pythontex
#   is not invoked.  Later runs after a modification of the source
#   file in the invoked python code do trigger the invocation of
#   pythontex. The planned future enhancements of latexmk should
#   remedy this.

# This latexmkrc is an example of a style of configuration that may be
#    useful for other packages.

# This version has a fudge on the latex and pdflatex commands that
#    allows the pythontex custom dependency to work even when $out_dir
#    is used to set the output directory.  Without the fudge (done by
#    trickery with symbolic links) the custom dependency for using
#    pythontex will not be detected.

push @generated_exts, 'pytxcode';
add_cus_dep('pytxcode', 'tex', 0, 'pythontex');

sub pythontex {
    # This subroutine is a fudge, because it from latexmk's point of
    # view, it makes the main .tex file depend on the .pytxcode file.
    # But it doesn't actually make the .tex file, but is used for its
    # side effects in creating other files.  The dependence is a way
    # of triggering the rule to be run whenever the .pytxcode file
    # changes, and to do this before running latex/pdflatex again.
    return system("pythontex3 \"$_[0]\"") ;
}
```

**Comment by haraldschilly** [comment]
@profbrady you might find my screenshot about showing pythontex errors right in the editor interesting:

https://github.com/sagemathinc/cocalc/pull/3175#issuecomment-420777329

it's still in development, though

**Comment by profbrady** [comment]
Looking good. I look forward to using pythontex for generating course materials for a Python and CoCalc-based computer applications (programming) course I teach in the spring as well as creating tests and assignments for other classes. I am fiddling with it now just to feel out the capabilities.

**Comment by haraldschilly** [comment]
the outcome of this ticket is a direct integration of a pythontex step into the build heuristic. it also parses and shows errors in the editor panel.
