### ISSUE TITLE
gracefully handle case where a student deletes their account, then creates a new one with the same email address

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3168]
I'm pretty sure we never even worried about this situation, and nobody has ever once had it happen and complained.  But here's the scenario, and when we have the resources to work on fun bugs, we should fix it:

REPORTED BY: Christopher Chudzicki

```
MAIN = christopher.chudzicki@xxx
SECOND = cchudzicki@xxx before deleting cocalc account 
THIRD = cchudzicki@xxx after recreating cocalc account

1. MAIN created a course and invited SECOND 
2. MAIN deleted SECOND from course 
3. SECOND deleted account. 
4. THIRD created account (same email address as SECOND) 
5. MAIN undeleted SECOND/THIRD email from course 
6. course does **not** appear in THIRD's cocalc view.

I doubt this will cause any issues for my students, but I thought it was worth reporting.

Expecting: I was expecting to be able to re-add a user to a course after they deleted their account.

```

**Comment by novoselt** [comment]
I am guessing that still nobody has complained.

**Comment by williamstein** [comment]
One thing is that there is now a big red warning to students NOT to delete their account, explaining that it will not help solve whatever their problem is.  I added that, and it seemed to greatly reduce problems.
