### ISSUE TITLE
it should not be possible to enable student pay and institute pay at same time

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3178]
We probably don't want to allow this:

<img width="516" alt="upgrade-2ways-bug" src="https://user-images.githubusercontent.com/528072/45492248-6fb1bd80-b731-11e8-9980-ccd098ffa6c7.png">

It raises questions, for example
* When the second payment method is enabled, whichever that one is, does it cancel the first (freeing allocated upgrades), or not? 
* What about new students, or students whose projects have not been upgraded? Do they get an error or warning banner telling them to upgrade, or no banner, presuming the instructor will soon upgrade their student projects?

**Comment by DrXyzzy** [comment]
Discussion: radio buttons are common for mutually exclusive choices. In this case, switching between payment alternatives after student projects are upgraded requires making decisions about existing resources and payments. During initial setup, we want to allow instructors to explore the UI and switch payment options. After students are added and projects upgraded, we probably want to prevent casual switching between selected payment modes, at least requiring confirmation of the choice.

**Comment by DrXyzzy** [comment]
Also, if you enable student pay, then come back later and uncheck the first checkbox "Students will pay for this course", the box shows as unchecked, but students still see the banner saying payment is required.

**Comment by novoselt** [comment]
It is still possible to check both boxes at once. One can also argue, that once a choice is made, it should not be possible to uncheck either box, there has to be a commitment. However it obviously does not cause a lot of problems and being able to play with the options is convenient. Can an instructor come to class on Monday and say "We will pay!" then on Tuesday "You should pay!"? Of course. Is it a good idea to say such contradictory things? No. Should we implement a procedure that makes instructors incapable of doing it?..

**Comment by williamstein** [comment]
>  Should we implement a procedure that makes instructors incapable of doing it?..

No.  I think a fundamental design principle of CoCalc is to **enable freedom**.  It's an "open world", not a closed one, like some course management systems.  It allows all kinds of things, but at the same time -- with snapshots and timetravel -- you have a good safety net.  So my philosophy is just leave this as is.
