### ISSUE TITLE
courses: add a panel that lets you run a single command line in all student projects

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3184]
This would be sort of like the miniterminal.

Basically add an action which is "exec this command/args or bash command line in all student projects". It would ensure each project is started, then run the code.  The timeout might be 30s?

Some issues: this would work by making a websocket connection to each project - can the browser handle potentially 100+ of these at once?  If not, maybe do async.mapLimit and be sure to close the websocket for the project.

**Comment by haraldschilly** [comment]
I think we should close this one. Basic serial-execution of commands is supported.
