### ISSUE TITLE
there might be an issue with appear.in video chat support (HARD DEADLINE: Sept 23, 2018)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3185]
> Johan Commelin: @William Stein I did get some banner on top of the appear.in chatroom, saying that the free chatrooms would no longer be available after the 24th of this month.

> William Stein: @Johan Commelin -- crap, that's really unfortunate. We will have to remove this functionality, or try to find another provider (e.g., google?) that still makes random video chat available. Their pricing last I checked for non free was ridiculously high, much higher than we charge for cocalc, so paying them wasn't an option.

**Comment by haraldschilly** [comment]
this announcement says something about claiming a room: https://blog.appear.in/2018-product-updates/claiming

where is the announcement about removing free usage?

**Comment by jcommelin** [comment]
No, I was confused. I was reproducing the warning from memory.

**Comment by jcommelin** [comment]
Still, it might mean that you'll have to change things a bit.

**Comment by johan** [comment]
FWIW, each time you use @ names without using the autocompletion to pick the _github_ account you are talking to, someone else probably gets notifications.

**Comment by williamstein** [comment]
> FWIW, each time you use @ names without using the autocompletion to pick the github account you are talking to, someone else probably gets notifications.

Thanks. In this case I was just pasting a session from a Zulip chatroom.  Sorry about that.  I guess I'll use 
```
a pre block @johan blah
```
to avoid this in the future.

**Comment by williamstein** [comment]
Solved via switching to a competitor, namely the excellent https://meet.jit.si
