### ISSUE TITLE
junk metadata in .ipynb files

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3191]
I'm opening this issue for data collection. I haven't found a way to reproduce the problem.

We've seen two instances Jupyter notebooks that load and run slowly if at all. Both are over 3 MB in length, while on the basis of text content, you'd expect files to be a few KB. Both notebooks show abnormal proliferation of metadata, with JSON showing repeating nested objects with keys that are not seen in a selection of other notebooks:
  - \__altered
  - \__hash
  - \_root

Details, including copies of the notebooks, are in this [non-public directory](https://cocalc.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/IPYNB-BUG/?session=default).

**Comment by williamstein** [comment]
Can you look at TimeTravel for the originals and provide a way to *reproduce* getting them in this state?

**Comment by williamstein** [comment]
I wonder why that metadata appears ever at all?  It would be relatively easy to just delete/trim it before save...

**Comment by haraldschilly** [comment]
my 2 cents: these attribute names are from immutable.js. watch:

```
coffee> m = require("immutable").Map()
Map {}
coffee> Object.keys(m)
[ 'size', '_root', '__ownerID', '__hash', '__altered' ]
```

**Comment by DrXyzzy** [comment]
I haven't found a way to repeat the problem yet, but added a third notebook to the [directory with bad notebooks](https://cocalc.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/IPYNB-BUG/?session=default). It uses the Haskell kernel.

**Comment by DrXyzzy** [comment]
This may be relevant: [Using Map method with React causes infinite recursion](https://github.com/rtfeldman/seamless-immutable/issues/73#issuecomment-152584517)
