### ISSUE TITLE
svg image appears as broken link in shared jupyter notebook

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3197]
Examples:

- [R notebook](https://share.cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/ir-display.ipynb?viewer=share)
- [python notebook](https://share.cocalc.com/share/db982efa-e439-4e2d-933b-7c7011c6b21a/SHARETEST/pyplot.ipynb?viewer=share)

Doing right-click and View Image on the broken image icon in FF shows an error like this:
```
XML Parsing Error: unclosed token
Location: data:image/svg+xml;utf8,<svg height="400px" ...
Line Number 1, Column 607:
<svg height="400px" version="1.1" ...
```

**Comment by DrXyzzy** [comment]
Explanation: Firefox is more strict about url encoding '#', as [noted on SO](https://stackoverflow.com/a/30676203).

For example, this compute cell with hex color code prefixed by '#' shows the broken-image error when the notebook is viewed on the share server in FF:
```
from IPython.display import SVG, display
s="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle r='50' cx='50' cy='50' fill='#0f0'/%3E%3C/svg%3E"
display(SVG(url=s))
```

And live-editing the shared page source in FF using "Inspect Element" and changing `#0f0` to `%230f0` causes the broken image icon to be replaced by a green circle.

**Comment by haraldschilly** [comment]
With Chrome 73 this is also broken.

My example worksheet is [svg-plot.ipynb](https://share.cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/svg-plot.ipynb?viewer=share)

The source code looks like that, where I'm suspicious about all those html encoded `&quot;` and so on...

```

<span>[&lt;matplotlib.lines.Line2D at 0x7f6c00feb2e8&gt;]</span></div><img src="data:image/svg+xml;utf8,&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
--
  | &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot;
  | &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
  | &lt;!-- Created with matplotlib (http://matplotlib.org/) --&gt;
  | &lt;svg height=&quot;252pt&quot; version=&quot;1.1&quot; viewBox=&quot;0 0 381 252&quot; width=&quot;381pt&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
  | &lt;defs&gt;
  | &lt;style type=&quot;text/css&quot;&gt;
  | *{stroke-linecap:butt;stroke-linejoin:round;}
  | &lt;/style&gt;
  | &lt;/defs&gt;
  | &lt;g id=&quot;figure_1&quot;&gt;
  | &lt;g id=&quot;patch_1&quot;&gt;
  | &lt;path d=&quot;M 0 252.018125


[...]
```

**Comment by williamstein** [comment]
@hal, your python test file is currently incomplete.   This works fine for me with Chrome 71:

https://share.cocalc.com/share/13a5ca5a-dac9-44e1-8a14-1a93f28b7698/flag-test.ipynb?viewer=share

When I try to open your example the flag doesn't show up, but I think that's because you didn't properly save the file in the first place.    The above link I show of course does NOT work with Firefox, and shows an explicit "broken image" icon.    I also get an explicit broken image icon with Chrome 73 when viewing [the link I posted](https://share.cocalc.com/share/13a5ca5a-dac9-44e1-8a14-1a93f28b7698/flag-test.ipynb?viewer=share)

**Comment by williamstein** [comment]
In any case, I'm really glad you found and reported this bug!

**Comment by williamstein** [comment]
Now fixed and fix is live.
