### ISSUE TITLE
sometimes jupyter2 kernel randomly resets to default (=sagemath)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3201]
Occasionally, the jupyter2 notebook kernel resets back to sagemath. I witnessed this when evaluating one which was opened in a tab for a while, but not running. Others reported it did happen for students using newly distributed notebooks. So, my hunch is there is a slight race condition between selecting a default kernel vs. reading it from disk.

**Comment by williamstein** [comment]
Setting to high priority.   If anybody can replicate this somehow, it'll be easy to fix...  Otherwise, I'll stare at code, then **add some fake delays** to hopefully force it to be replicated every time.

**Comment by williamstein** [comment]
Assigning myself, but happy to get any data here.

**Comment by haraldschilly** [comment]
Interesting detail: I scrolled back in my JS console and found that exception (I was exactly that python3.ipynb notebook, which should be for testing ubuntu python3, but it was running sagemath ... hence that's why I noticed it)

![screenshot from 2018-09-22 18-05-40](https://user-images.githubusercontent.com/207405/45919228-48c25c80-be92-11e8-95a0-a06f407eaf2f.png)

**Comment by williamstein** [comment]
That is **extremely** useful.  The code that is trying to reach that endpoint should just retry_until_success, since once the backend side has loaded then the endpoint will respond properly.

**Comment by DrXyzzy** [comment]
This problem was also reported by Lauren Shareshian.
