### ISSUE TITLE
make the "Software and Programming Libraries Details" section of the info page require a button click (or something else) to be displayed

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3203]
Any time I switch to the "i CoCalc" page to check stats or follow a link the load time is actually pretty long/heavy... especially on mobile.  Why?  Almost surely because of the absolutely MASSIVE "Software and Programming Libraries Details" section you added... with thousands (?) of entries even in the default tab.     I don't know why I didn't complain about this when it was a PR, but there should be a toggle button or something.

I'm making this a bug because the expected behavior upon clicking on that tab is that it appears very quickly, since it's mostly simple.

**Comment by haraldschilly** [comment]
what about optimizing the table? e.g. https://bvaughn.github.io/react-virtualized/#/components/Table looks like a solution to mitigate the slow rendering

**Comment by williamstein** [comment]
I'm working on fixing this bug now.

**Comment by williamstein** [comment]
long long gone.
