### ISSUE TITLE
chat preview md → html processing partially broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3206]
expected: the "preview" bubble shows the chat message 100% as it would be when sent.

reality: there is at least some escaping of `>` characters going on, which  prevents the markdown formatter to show quoted text correctly. Also, partially typed in html appears to be mangled (it should usually be sanitized and rendered as html)

exhibit A

![screenshot from 2018-09-25 09-52-48](https://user-images.githubusercontent.com/207405/46000550-34a47800-c0a9-11e8-8ed2-33e11a843d70.png)

exhibit B

![screenshot from 2018-09-25 09-54-47](https://user-images.githubusercontent.com/207405/46000558-3a01c280-c0a9-11e8-9c5a-2c7a7779e268.png)

**Comment by williamstein** [comment]
Just hit me again:

![image](https://user-images.githubusercontent.com/1276278/99981379-2cfebd80-2d5e-11eb-9b90-f7af81fd028a.png)
