### ISSUE TITLE
improvements for bulk deleting student projects

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3211]
1. create course, with one student
2. student has a project in a course, open it in a tab
3. course is done, teacher issues "delete all student projects" in course config
  * confirmation: the student project in your other tab says "Warning: this project is deleted"
4. going back to student list, there is still the student (I think it should actually be "deleted", because the teacher wants to get rid of everything from last year!) and a button to create a project. that's fine, because there is no project (it's deleted)
5. close the course file
6. open course file: what happens is a new project for that student is created. ... you can open that project and can see that it is empty.

Ok. Here are my thoughts:

* I'm pretty sure the procedure above is useful in some cases, e.g. to (sort of) reset all projects of students during a course. But: I would expect that the student is removed as a collaborator from that deleted project. Otherwise, he or she still has access. (I confirmed that, and I regard that as an oversight)

* In case a teacher wants to reset a course to use it again next year, the student should also be marked as being deleted in the course file. that should probably be an option or additional button in the configuration/delete projects panel.
   feedback:
   > Yes exactly, I wasn’t sure how to interpret “delete student projects”, whether it would remove the students from the course or not. Having both options would certainly be useful, e.g. “delete all student projects and keep students on course” and “delete all student projects and remove students from course”.
   * my thoughts: there could also be a notion of "reset student project" (i.e. create a new project for the student and remove student from the existing project, but keep access around for teacher (is it enough to mark it as deleted, and no longer be referenced from the course file?))

* for **deleted** students, who do not have an associated project, no project should be created (I did not test this, due to another bug, see below)

* when I try to delete a student from the list of students without a project, I get

   ![screenshot from 2018-09-27 12-22-06](https://user-images.githubusercontent.com/207405/46139979-29d81780-c250-11e8-9a95-01ec86981fad.png)

* and finally, the original stupport discussion behind this also mentions, that these newly created projects (after deleting all student projects) aren't hidden. I wasn't able to confirm that, but this is something to also watch out.

**Comment by schwartzjmc** [comment]
Agreed, in general I want to "delete all student projects" at the start of a new year, therefore I would also like all the students to be removed from the course before uploading a new list of students. But it may be useful to offer both options for some cases, e.g. “delete all student projects and keep students on course” and “delete all student projects and remove students from course” (although that makes pretty long buttons!)

**Comment by novoselt** [comment]
It seems like there are many issues here and at least some of them were addressed, e.g. having two buttons for deleting students/projects, and their description seems to be pretty clear to me. There are no steady support requests on the topic.
