### ISSUE TITLE
when adding multiple students to a course, sometimes not all student projects are hidden

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3214]
Seen 1 time out of 3 tests.

- create a .course file
- in "Add student by name or email address", enter 3 students by first and last name, separated by commas, then click "Add all students", see all 3 names added to student list
- open Projects list to look for the 3 new student projects; see one new student project when Hidden box is not checked, and the two other student projects when Hidden box is checked

Seen with [non-public course file](https://cocalc.com/projects/db982efa-e439-4e2d-933b-7c7011c6b21a/files/TESTING/demo6.course?session=default)

**Comment by haraldschilly** [comment]
have you seen any exceptions in your js console?

**Comment by DrXyzzy** [comment]
> have you seen any exceptions in your js console?

Not around that time, no.

**Comment by DrXyzzy** [comment]
I'm closing this because I have tried about 5 more times to evoke the bug and not succeeded. Tried with course file in free server as well as in member server.
