### ISSUE TITLE
"Replace student files" option is ignored when updating a handout

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3215]
- Create a .course with some students.
- Create a handout folder with two files, say `Handout/H1/a.txt` and `Handout/H1/b.txt`
- Distribute the handout folder, say `Handout/H1`, to all students.
- In the instructor project, remove `a.txt` and modify `b.txt`.
- In the .course file under Handouts, select `Handout/H1`.
- Click `Distribute...`
- Click the red button `All x students...`.
- Observe the notice that says *... Select "Replace student files!" in case you do not want to create any backups and also delete all other files in the assignment directory of their projects.*
- Click `Replace student files!`.
- Enter `OVERWRITE` in the text area.
- Click `Confirm replacing files`.
- Open a student project and view file listing. Note the following. The second and third items seem to contradict the notice about replacing student files.
  - new contents are distributed for `b.txt`
  - a backup has been made, `b.txt~`
  - the removed file `a.txt` is still there

**Comment by novoselt** [comment]
Both deletion and replacement work as described now!
