### ISSUE TITLE
latex: filenames with more than one consecutive space broken?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3230]
1. create a file like `3   spaces.tex` with  – well  – 3 spaces in the filename
2. cocalc is able to open it, etc., but breaking failing latexmk down to pdflatex reveals that it fundamentally fails. In particular, even running this in a terminal

       $ pdflatex 3\ \ \ spaces.tex

   throws an error. (hence upstream and unclear)

   ```
   ~/latex-tests$ pdflatex 3\ \ \ spaces.tex
   This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
    restricted \write18 enabled.
   entering extended mode
   ! I can't find file `"3 spaces.tex"'.
   <*> "3   spaces.tex"
   ```

My thought is to add a clear warning to the latex editor about that, e.g. `Latex files do not work with more than 1
one consecutive space character in their filename`

**Comment by kevinywlui** [comment]
This issue is similar to using `\include` on files with spaces in them. You have to escape them with `\space`. https://stackoverflow.com/questions/2444385/include-a-tex-file-with-spaces-in-the-filename

So `$ pdflatex "3\space\space\space spaces.tex"` should work.

**Comment by haraldschilly** [comment]
Hmm, I tested this, played around with various variations and searched for solutions, but I am not able to get this to work in any way. This workaround might be specific to one or a few latex distributions. I'm all for showing a warning to the user that the filename isn't going to work.  That also helps with portability from cocalc to another environment.
