### ISSUE TITLE
in cocalc classic jupyter notebook, filename is displayed too high

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3237]
1. Open a .ipynb file.
1. If using modern notebook, under `File` (not `Files`), click "Switch to classical notebook..."

Seen with Chrome 69.0.3497.100 (Official Build) (64-bit) macOS 10.13.6, and Safari on iPad Pro with iOS 12.0.

Not seen with Plain Jupyter Server.

<img width="330" alt="classical-name" src="https://user-images.githubusercontent.com/528072/46365852-3d63f380-c63f-11e8-9635-35432f1739e4.png">

**Comment by williamstein** [comment]
@haraldschilly fixed this.
