### ISSUE TITLE
allow line break as delimiter when adding multiple students to .course

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3238]
I think we should support the following: when adding students to a .course, allow pasting names that are delimited by line breaks in the copy/paste buffer.

Suppose we have a text file with the following:
```
John Doe
Mary Roe
Richard Smith
```

If you copy this text and paste into a .course file under the `Students` tab in the text area "Add student by name or email address", you see the names run together, and matches against existing students do not succeed, as they would if the names in the original list had been comma-delimited.

This feature is helpful if someone has a column of names or email addresses in an Excel or LibreOffice Calc spread sheet. If you select a column (or columns) and paste into a text area in another app, the default seems to be to delimit rows in the destination text with line breaks.

**Comment by haraldschilly** [comment]
My thought is that this should be a text area, which should preserve line breaks, right? I'll give it a try.

**Comment by novoselt** [comment]
It is possible now. John Doe is a very popular name, apparently...
