### ISSUE TITLE
cannot copy selected text in edit frame of .md file with vim keybindings in chromeos

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3241]
Seen on Pixelbook with ChromeOS version Version 69.0.3497.95 (Official Build) (64-bit). Not seen with Chrome, Firefox, or Safari on macOS.

On Pixelbook:

1. Set editor keyboard bindings to vim and refresh browser.
1. Open a .md file and type some text.
1. Highlight some text in the edit frame and try copying with ctrl-C.
1. Try pasting copied text into the edit frame somewhere else with Ctrl-V. Previous contents of the paste buffer, if any, will be pasted, not the text that just selected.
1. Highlight the same text in the rendered view and click Ctrl-C.
1. Paste into edit frame with Ctrl-V. It works.

**Comment by williamstein** [comment]
This (1) has nothing to do with markdown, and (2) is the desired behavior of CodeMirror and the vim mode because control+c has a special meaning in vim (it switches mode).

Try it in https://codemirror.net/demo/vim.html

**Comment by williamstein** [comment]
(to copy in vim mode, use vim's copy or the context menu)
