### ISSUE TITLE
implement keyboard shortcut customization for cocalc jupyter

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3242]
It's in classical jupyter, but not cocalc jupyter.

**Comment by williamstein** [comment]
(Note -- I mostly wrote code for this a year ago, but it was not quite done, and I never finished it.)

**Comment by DrXyzzy** [comment]
Requested by Robert Indik for "Toggle whether cells are deletable" and "Toggle whether cells are editable".

**Comment by williamstein** [comment]
Further comments by Robert about those two commands:
```
I didn't find those particular functions in classic Jupyter.  What I was trying to say is that in classic Jupyter notebooks, there is an option to edit the keyboard shortcuts. 

As for what keys I might bind to the two toggle functions, if it were just for me, I would use P and ctrl P (protect), but I think P is already in use for command palette. Maybe ctrl T (toggle deletion) and ctrl E (toggle edit)?  (or meta or alt  instead of ctrl). 

The way I see using it, I would usually want both protections, so I would be happy with a single key shortcut that toggles the pair.  I don;t know if that would be useful for others though.
```

**Comment by williamstein** [comment]
I implemented Robert's request: https://github.com/sagemathinc/cocalc/commit/bb5f468cd74376ce5e2ea7b016239385eee72318

**Comment by williamstein** [comment]
![image](https://user-images.githubusercontent.com/1276278/82845866-0f2dca00-9e9b-11ea-8e6b-79064efed5a3.png)

**Comment by jkitchin** [comment]
I would like to be able to add custom keybindings to cocalc. The main application is in grading notebooks, where I would write a command that lets me press ESC C (for example) that would prompt for a comment, and then insert a markdown cell with the input wrapped in "<font color="red">input</font>" for example, or ESC G that would prompt for letter grades and then compute a grade and store it in the notebook metadata. I did this with Jupyter notebooks and liked it a lot.

**Comment by williamstein** [comment]
I'm closing this since nobody has requested such customization in many years, and it can be problematic regarding conflicts with the browser and other keyboard shortcuts.   

That said, the problem of making a sequence of actions easier to automate is interesting, and it would be nice to have a way to define such things and run them via some  standard keybindings...  But that's another ticket.
