### ISSUE TITLE
courses: do something sensible when a student deletes their account

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3243]
Deleting an account is not something a student could accidentally do - there's a huge warning, etc.  However, students sometimes do it in a panic.  In fact, in just one single recent class 17 students deleted their accounts and over 60 accounts were deleted in the last week.  So it happens.

In our course code, I think we assumed that people don't delete their accounts on whim; in fact, much of the course code was written before there was account deletion functionality.  If they do delete their account, it's going to take some manual work to fix things.  Once they make their first account, that is the one associated to the course.  If they then delete their account and make a new one with the same email address, they are going to be in big trouble and probably the only possible fix right now is for them to get added as  a new student with a *different* email address.

Honestly, I'm not even sure what the semantics for this should be.

**Comment by mforbes** [comment]
I ran into this warning today when I tried to delete a test account I made for myself to see what students see.  As far as semantics go, my expectation would be that if a student deletes their account, then they would be "de-registered" from the course, removed from the shared project, and have their student project deleted so that everything is returned to the prior state.

Probably not the best sementics though for students who accidentally delete their account and don't want all their work lost etc. though.

**Comment by novoselt** [comment]
It does not seem that we have to deal with 60 accidentally deleted projects per week anymore, so the current behaviour is reasonably sensible.

**Comment by williamstein** [comment]
We also have a big message right in the delete box about this which points to this issue:

<img width="769" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/534c51af-6897-4094-a952-60b7a86056b5">

Evidently, people do read it.

**Comment by williamstein** [comment]
Crazy -- just a few minutes after I posted my comment a student opened a support request in which they deleted their account to "To try to fix it", and now they are locked out from their course, etc.    We haven't had this happen in months (or years), and it happens moments after discussing it.

**Comment by williamstein** [comment]
The feedback from the student was basically: "I saw and read the above message, but the TA told me to delete my account anyways."   

Obviously this issue needs to stay open.

**Comment by williamstein** [comment]
How to fix this:

- figure out the new account_id of the student
- close the .course file in cocalc
- edit the .course file (e.g., using vim) and replace the old account_id with the new one
- open the .course file

This fixes the problem.

A user can basically change their account_id at any time as follows:

- delete their account thus freeing up their email address
- create a new account with the old email address

The "Reconfigure all students" button (i.e., action) should also have a step where it queries an api endpoint with a list of all known email addresses of students for the corresponding account_id's.  If any change, then it changes them in the .course data.  Anyway, I think that's the best we can do for a longterm fix for this problem.

**Comment by novoselt** [comment]
Will it affect students who change their emails associated to the account after being enrolled in a course?

**Comment by williamstein** [comment]
> Will it affect students who change their emails associated to the account after being enrolled in a course?

If they change their email address, then make another new account with the old email address, it would impact them.   I mean, what should happen in that scenario?  

An alternative would be to add a new api call which allows the frontend to ask: "which of the following account_id's do not currently exist (presumably due to being deleted)?" For each such address it would just do the standard thing to add the user with the corresponding email to the course.  A problem with that strategy though is that students can be added to a course by name without knowing their email address ever (or maybe they don't even have one), so there is no way to add them at this point.

Also, one I'm proposing here to solve this problem only works if the student got added to the course by email address so maybe this whole solution is wrong.  Another approach would be the following:

- assume a student gets added to the course in any way, and their account exists, so we know the account_id.
- the student then deletes their account.
- we could just completely delete the student from the course and purge them entirely from the course file (so they can't even be undeleted, etc.)
- then the instructor can easily add the actual student again, since the old record isn't there.  

This seems pretty horrible though.  E.g., imagine this happens halfway through the course -- suddenly you don't have the ability to view the students homework and other records, which is ridiculous.  So this is not a solution at all.

Here's another idea:

- the student is added to the course somehow
- the student deletes their account
- the .course detects this via an api that, given an account_id, tells whether or not that account still exists
- it then explicitly removes the account_id from the student's record in the .course file.  Hopefully the old student name is still in there so there is some way to identify the student.
- the UI then shows what we know about the student and has an alert that says "this student deleted their account; would you like to add them again?" 
- the instructor can then manually add the student again via an entirely new UI element, and this could involve adding the student by searching for them via name or email.  If an account exists they get added.  If there's no account, an email invite gets sent out, the student makes an account and eventually the .course notices and sets the account_id with this new account.

I think the above would at least work in general. but it's quite a lot of work to implement, and unlike all the other ideas, it involves explicit action by the instructor.

**Comment by williamstein** [comment]
@mforbes wrote:
> As far as semantics go, my expectation would be that if a student deletes their account, then they would be "de-registered" from the course, removed from the shared project, and **have their student project deleted** so that everything is returned to the prior state.

What if the student were accused of cheating?   They might then delete their account, and having their project (and your access to their work) disappear could be a problem for you as the instructor?

**Comment by williamstein** [comment]
Here's another crazy idea:

1. student in class creates an account with email foo@bar.edu.  
2. for unknown reasons they ignore all the big red warnings to not delete their account, and delete it.
3. Immediately, they create foo@bar.edu again.  

This is the sort of student that things a standard debugging step when something doesn't seem right is to just delete and create an account.  We *could* actually just give them back the account they just deleted.   That would work because we don't immediately purge deleted account records, and we do store the email address they had before.  So if you try to create a new account using the email foo@bar.edu, we could just give you the account you had before.  Basically it's just an "undelete".  

This would be a very simple way to solve every single case of this bug we've seen with students, and it instantly solves it (no need to "reconfigure student projects", etc.).  

A problem with this approach, because we don't require email verification before giving you access to your account:
  - person A deletes their account
  - person B knows about this and then creates a new account using person A's email address, and gets access to person A's old data.

That said, if we just totally change cocalc and absolutely require all users to verify their email (or use SSO) before they get access to anything, then the above issue goes away.  And we are planning to require email verify anyways.

**Comment by williamstein** [comment]
I guess they could make a new account with a different email, then change their email to arvill26@colby.edu  and that breaks this.  Many this is a hard problem to solve in general.

I guess the only general solution is the hard one outlined at the end of https://github.com/sagemathinc/cocalc/issues/3243#issuecomment-2339398169, where there is a new UI element to add the student again.

**Comment by novoselt** [comment]
- We should not delete accounts completely immediately, unless there was a manual request and it is done by admin.
- "Undeleting accounts" does seem like a dangerous idea to me even with email verification - what if it is a some generic email and the user has actually changed?
- In general it feels perfectly natural that I got enrolled in a course and then changed my email for the account. Why should my link with the course be broken as a result?
- I think that automatic fixing of problems is not a good idea in this case at all, rather there should be a straightforward way to fix the problem. Bonus point for indicating that it exists.

I think for me as an instructor the ideal behaviour would be this:
- If the student updates the email, update the email in the course file.
- If the student deletes the account, the student record and connection to the account are preserved, but the record is highlighted in some very obvious way, like red background.
- Now if there was cheating, I still have access to all materials.
- If it was a mistake and the student wants to regain access to the same project, the account must be undeleted in a regular way (if we have one ;-)).
- Perhaps creating a new account for an email that is still connected to a deleted account just should not be possible without admin intervention to either undelete the old account or completely remove it and free up the email.

**Comment by williamstein** [comment]
> what if it is a some generic email and the user has actually changed?

That remind me of a reason why email verification is so difficult to require: we can't allow for generic "fake" emails if we require email verification!

> In general it feels perfectly natural that I got enrolled in a course and then changed my email for the account. Why should my link with the course be broken as a result?

It's not right now, and it wouldn't be with any of the suggestions I've made so far.   

> I think that automatic fixing of problems is not a good idea in this case at all, rather there should be a straightforward way to fix the problem.

I agree.  Of all the solutions, the only one that works in *all cases* and has no scary security implications is the one that does not involve automatic fixing of the problem. 

> If the student updates the email, update the email in the course file.

No. This violates a core requirement of our privacy model, which is that user A cannot get the email address of user B.  

> If the student deletes the account, the student record and connection to the account are preserved, but the record is highlighted in some very obvious way, like red background.

Agreed.

> Perhaps creating a new account for an email that is still connected to a deleted account just should not be possible without admin intervention to either undelete the old account or completely remove it and free up the email.

I think we should just allow this and it should work.  That's what we do now.  However, this won't fix any issue related to the course.  The instructor will see that the account was deleted and can explicitly decide what to do: 
   - switch the course to use the new account with the same email as before
   - search for and add a user to take over that slot in the course
   - leave things alone


> Now if there was cheating, I still have access to all materials.

Strongly agree.

> If it was a mistake and the student wants to regain access to the same project, the account must be undeleted in a regular way (if we have one ;-)).

This conflicts with your remark that **"Undeleting accounts" does seem like a dangerous idea to me**.   I agree.  It's dangerous.  I hate dangerous.

I think courses should have an option about whether or not students must have a verified email address when joining the course.  If the instructor is using fake random emails (for privacy), they would *NOT* want verified emails.  If they are using real emails, then they definitely do want them. This is now https://github.com/sagemathinc/cocalc/issues/7826

**Comment by mforbes** [comment]
> @mforbes wrote:
> 
> > As far as semantics go, my expectation would be that if a student deletes their account, then they would be "de-registered" from the course, removed from the shared project, and **have their student project deleted** so that everything is returned to the prior state.
> 
> What if the student were accused of cheating? They might then delete their account, and having their project (and your access to their work) disappear could be a problem for you as the instructor?

I retract my expectation.  I was under the (false) assumption that the students owned their project rather than the instructor owning their project.

I must admit, I can't figure out what was exactly the problem here.  After deleting my account as a student (pushing past the warnings), I was able to recreate it and still be connected with the course.  Is that what you mean by **undeleting**, or is that something else.  These do seem to generate new accounts, so that there are new 4 new users in the student project:

<img width="884" alt="image" src="https://github.com/user-attachments/assets/7cf9fb7c-d478-4928-8022-90e122471d7d">

Is this intended?  (I did not re-add the deleted student to the course.)  Does this not introduce the backdoor you did not want where a malicious actor now has access to the student's work?  I did not expect this to happen without the new student being explicitly re-added to the course.

One option for a "soft" reset of a deleted project might to reset all of the files, but keep the older snapshots for recovery if needed.  Not sure how needed this is, but it might be a generally useful feature if someone fubars their account.  (Maybe it exists?)

**Comment by williamstein** [comment]
Here's another idea.  If the student deletes their account then when browsing the students, they get an info box that the student deleted their account, and they get a button to "delete the student from the course", which deletes *and purges* the student from the course (so no trash).  After the instructor does this, they could then add the student fresh if they want... or not.  Or they could elect to not delete the student.

**Comment by novoselt** [comment]
I think this is the best option from all points of view based on my recent experience! No automation that potentially can create more problems than to solve, and no real new functionality, just allow purging one student instead of everybody. I think it also should be "intuitively clear" to instructors that a student with a deleted account should be removed, but then it is possible to add the student again.

**Comment by mforbes** [comment]
This seems reasonable to me.

**Comment by williamstein** [comment]
https://github.com/sagemathinc/cocalc/issues/3243#issuecomment-2344600455 is now implemented.

**Comment by williamstein** [comment]
I'm reopening this. What usually happens is:

- student is added to class just fine
- for mysterious reasons the student deletes their account
- student creates a new account with the same email address

Fixing this situation regarding the .course file can definitely be automated, since I manually fix it regularly.  The steps are:

- observe that an account_id of a student corresponds to a deleted account (e.g., via a periodic check)
- if the email address of that deleted student is known in the course file, search cocalc to see if there is a new account with *that* email address
- if yes, set the account_id in the course file to that new account_id and reconfigure projects.

The above would be easy to automate and would transparently handle such problems.

**Comment by novoselt** [comment]
In the recent support request the concern was also to preserve prior work. Is it feasible to move the "old project" to the "new account"?

**Comment by williamstein** [comment]
> In the recent support request the concern was also to preserve prior work. Is it feasible to move the "old project" to the "new account"?

YES.  The solution I outline above does exactly that.  It just sets the user for that project to be the new user instead of the old deleted user.
