### ISSUE TITLE
thickness has no effect in 3d parametric plots

### ISSUE THREAD

**Issue by ChristopherChudzicki** [sagemathinc/cocalc#3245]
The value of `thickness` keyword argument seems to have no effect in CoCalc 3d parametric plots:

```
t = var('t')
parametric_plot((cos(t), sin(t), t/pi), (t, -2*pi, 2*pi), thickness=10)
```

**Note**: If this is a Sage issue and not a cocalc issue, feel free to close this, but ... it seemed reasonable to think this might be issue with CoCalc renderer

**Comment by williamstein** [comment]
1. Are you using a Sage Worksheet or Jupyter notebook?

2. If a Jupyter notebook, precisely what kernel?

**Comment by ChristopherChudzicki** [comment]
This is using sagews.

**Comment by williamstein** [comment]
> So the issue might be that the 3d renderer in sagews is three.js.

CoCalc indeed also uses three.js.   We use a completely different 3d plotting library than plain sage, which also uses three.js under the hood... so maybe three.js has a bug or API change or something.

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.

WORKAROUND: Create a Jupyter notebook with the Sage kernel.
