### ISSUE TITLE
double quotes in comments in assignment grade should be doubled in exported csv

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3249]
In a .course file, enter Comments for the grade with some double quotes:

![abahd](https://user-images.githubusercontent.com/528072/46559739-d6507400-c8b6-11e8-8036-0a8dd0786c6e.png)

Select course Configuration / Export grades / CSV file... and the following is generated:

```
"student","xxx-xxx-xxx",,"","","","100%","100% ","","",""a boy","and his","dog"","you're on a roll"
```

The above CSV does not import properly. According to e.g. the [Edoceo CSV reference](http://edoceo.com/utilitas/csv-file-format):

> Embedded double-quote characters must be doubled, and the field must be delimited with double-quotes.

When the line above is corrected to the following, the content imports to Excel as expected.

```
"student","xxx-xxx-xxx","","","","100%","100% ","","","""a boy"",""and his"",""dog""","you're on a roll"
```

**Comment by haraldschilly** [comment]
the merged patch addresses exactly that. further CSV export problems should be reported as new tickets.
