### ISSUE TITLE
editor appears to have focus but does not accept input

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3269]
Seen with Chrome 69.0.3497.100 (Official Build) (64-bit) on macOS 10.13.6, with Vim and with Standard Editor keyboard settings:

1. Open a .md or .py file and enter some text; if using vim keybindings, leave editor in input mode for next step.
1. Split the window horizontally or vertically and drag the separating line to change the split ratio.
1. The cursor appears to be active in the edit pane. You can also click in the edit pane at this step, without changing the effect.
1. Observe that typing does not cause additional text to appear in the edit pane.

**Comment by williamstein** [comment]
Interesting!  This is NOT a new bug at all, so far as I can tell.  I've noticed it periodically for months now... but never could figure out how to reproduce it or what caused it.  Your steps nail down a way to reproduce it.  THANKS!
