### ISSUE TITLE
rethink the html editor live preview pane -- at least have a mode that can show style tags, has its own CSS, etc.

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#327]
I'm editing an html page with `<style>` inside the document and yet the viewer on the right side doesn't show this.

**Comment by williamstein** [comment]
What is "per styling"?

On Sunday, December 13, 2015, timothyclemansinsea <notifications@github.com>
wrote:

> I'm editing an html page with inside the document and yet the viewer on
> the right side doesn&#39 <https://github.com/sagemathinc/smc/issues/39>;t
> show this. </p>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/327>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by timothyclemansinsea** [comment]
The inline style inside `<style>` block

**Comment by williamstein** [comment]
To do this we should very likely switch to rendering the right side in an iframe.

**Comment by williamstein** [comment]
Is a bug since it doesn't match expected and reasonable behavior.

Another workaround would be to call it a preview and have a popout (to raw) that gives full version that is exactly as it would be live.  See https://github.com/sagemathinc/smc/issues/328

**Comment by williamstein** [comment]
https://github.com/sagemathinc/smc/issues/137 may have further examples and comments.

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/smc/issues/327

Note that forward/inverse search type stuff may be much harder with an iframe (?).

**Comment by williamstein** [comment]
Ryan McFall  also wants this, as he is using SMC's latex editor a lot for organizing his course html page, with custom style.  So, I'm increasing the priority.

**Comment by haraldschilly** [comment]
I assume, you mean SMC's HTML editor. I'll think about this, maybe it's not really hard to do at all.

**Comment by williamstein** [comment]
> maybe it's not really hard to do at all.

There are a whole bunch of tricks needed to get iframes to work with:

- react mount/unmount
- dragging to resize chat/editor/etc.

So don't expect things to "just work".  They might appear to, but test with multiple tabs, and dragging to resize.

**Comment by haraldschilly** [comment]
I tried this in `_editor.sass`

```
.salvus-editor-html-md-preview-content
  all: initial
  *
    all: unset
```

but tables aren't working, etc. I'm not sure how to use those `all` tags correctly.

https://www.w3.org/TR/css3-cascade/#initial and #unset

**Comment by zeigerpuppy** [comment]
This would also be useful for preview of .Rmd files, I am trying at the moment to change the default CSS of the live preview to have `img {max-width:400px}`, it would be great to be able to define a custom CSS for the preview.

**Comment by zeigerpuppy** [comment]
for others looking, I think I've found where I may be able to insert some CSS...

from line 482 of `/cocalc/src/smc-webapp/editor.html`
```
    <!-- Template for the HTML-MD editor -->
    <div class="webapp-editor-html-md smc-vfill">
        <div class="webapp-editor-html-md-editor-buttonbar">
        </div>
        <div class="webapp-editor-html-md-textedit-buttonbar">
        </div>
        <div style="display:flex; flex-direction:row; height:100%" class="webapp-editor-html-md-content">
            <div class="webapp-editor-html-md-source-editor" style="flex-basis:70%; display: flex; flex-direction: $
            </div>
            <div class="webapp-editor-html-md-resize-bar">
            </div>
            <div class="webapp-editor-html-md-preview" style="flex:1">
                <a href="#disable-preview" class="pull-right btn btn-default"><i class="fa fa-check-square-o"></i> $
                <a href="#enable-preview" class="pull-right btn btn-default btn-lg hide"><i class="fa fa-square-o">$
                <div class="webapp-editor-html-md-preview-content">
                </div>
            </div>
        </div>
    </div>
```

**Comment by haraldschilly** [comment]
well, there is an iframe to see the rendered html 🤷🏻
