### ISSUE TITLE
plots in assigned notebooks may not be visible in collected assignment

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3276]
1. In a .course with at least one student, create and distribute a Jupyter notebook with `Python 3 (Ubuntu Linux)` kernel with a single compute cell with this *unexecuted* code:
    ```
    import random, math
    x = sorted([random.uniform(0.0, math.pi) for _ in range(20)])
    y = [math.sin(xval) for xval in x]
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(14,4))
    ax.plot(x,y)
    ax.axis('tight')
    ax.set_title('demo')
    ax.set_xlabel('x')
    ax.set_ylabel('sin(x)');
    ```
1. In a student project, execute the cell, observe that the plot is there, and save the notebook.
1. In the instructor project, collect the saved student notebook and open the collected .ipynb file.
1. Observe that the plot appears as a broken image icon.

**Comment by profbrady** [comment]
I ran into this a lot in the spring. I was using the Anaconda Python3 kernel.

**Comment by DrXyzzy** [comment]
Fix tested ok in production.

**Comment by profbrady** [comment]
Is this issue actually fixed? So far this spring all student notebooks I collect do not show plots they created and I have to re-execute all cells.

**Comment by williamstein** [comment]
Yes, this is fixed. 

> So far this spring all student notebooks I collect do not show plots they created and I have to re-execute all cells.

Create a support request with **exact** details so we can reproduce the problem (links, etc.)

**Comment by profbrady** [comment]
Will do. I have an assignment with plots that is due Thursday night. When I collect that assignment to grade I will open a ticket if the problem persists.

**Comment by williamstein** [comment]
> When I collect that assignment to grade I will open a ticket if the problem persists.

Thanks.  It should be easy to reproduce if it happens, since you can point us at the ipynb file that the student has, and I can try copying it to another project manually, and see what happens (that's the same thing collect does).
