### ISSUE TITLE
xterm.js terminal -- control code corruption

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#3277]
It seems the problem from #1269 is back with the new xterm.js terminal -- hopefully the
same fix can avoid any unsolicited `;1R` from appearing?

**Comment by williamstein** [comment]
Sometimes back again -- I saw this after returning to a session after having had my laptop closed for a while.  It's so annoying how restoring the history causes this!

![screenshot 2018-10-11 at 4 16 14 pm](https://user-images.githubusercontent.com/1276278/46839102-232dc200-cd71-11e8-9f0a-7b644d1ac3b6.png)

**Comment by williamstein** [comment]
Non screenshot version:
```
~/cocalc/src$ :0+r436f^[\^[P0+r6b75^[\^[P0+r6b64^[\^[P0+r6b72^[\^[P0+r6b6c^[\^[P0+r2332^[\^[P0+r2334^[\^[P0+r2569^[\^[P0+r2a37^[\^[P0+r6b31^[\^[P0+r6b32^[\^[P0+r6b33^[\^[P0+r6b34^[\^[P0+r6b35^[\^[P0+r6b36^[\^[P0+r6b37^[\^[P0+r6b38^[\^[P0+r6b39^[\^[P0+r6b3b^[\^[P0+r4631^[\^[P0+r4632^[\^[P0+r2531^[\^[P0+r2638^[\^[P0+r6b62^[\^[P0+r6b49^[\^[P0+r6b44^[\^[P0+r6b68^[\^[P0+r4037^[\^[P0+r6b50^[\^[P0+r6b4e^[\^[P0+r4b31^[\^[P0+r4b33^[\^[P0+r4b34^[\^[P0+r4b35^[\^[P0+r6b42^[\^[[2;2R^[[>0;276;0c^[P0+r436f^[\^[P0+r6b75^[\^[P0+r6b64^[\^[P0+r6b72^[\^[P0+r6b6c^[\^[P0+r2332^[\^[P0+r2334^[\^[P0+r2569^[\^[P0+r2a37^[\^[P0+r6b31^[\^[P0+r6b32^[\^[P0+r6b33^[\^[P0+r6b34^[\^[P0+r6b35^[\^[P0+r6b36^[\^[P0+r6b37^[\^[P0+r6b38^[\^[P0+r6b39^[\^[P0+r6b3b^[\^[P0+r4631^[\^[P0+r4632^[\^[P0+r2531^[\^[P0+r2638^[\^[P0+r6b62^[\^[P0+r6b49^[\^[P0+r6b44^[\^[P0+r6b68^[\^[P0+r4037^[\^[P0+r6b50^[\^[P0+r6b4e^[\^[P0+r4b31^[\^[P0+r4b33^[\^[P0+r4b34^[\^[P0+r4b35^[\^[P0+r6b42^[\
```

**Comment by williamstein** [comment]
Re-opening. This *only* happens when reconnecting (so it's not extremely annoying like it used to be), often after not using the terminal for a while.  It may be impossible to avoid this without a major change in architecture, due to not having "infinite history"....

Options:
 
- do not store the history at all.  Pretty sad.
- Maybe store way *more* history?   That could help a lot.  It's worth a try.
