### ISSUE TITLE
jupyter lab&notebook aren't aware of stopped service

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3282]
1. start lab or notebook via settings button
2.
  * notebook, top right, click on "Quit"
  *  in lab: "file → quit" & confirm "quit"
3. back to the settings page, click on notebook or lab server again

Problem is, in both cases the UI thinks the server is running and you end up with a 504 gateway timeout page.

What should happen is a startup of the service.

Workaround is to tab away from the settings page and back to it.
Hence I think what is necessary is to reset the state of the button right after it opened a new tab.
At the same time, starting again while the service is already running shouldn't cause it to run twice.

**Comment by williamstein** [comment]
Not really an issue anymore, imho.
