### ISSUE TITLE
path with slash fails to match in search for assignment & handout folders

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3283]
Searching for "a/b" in upper right search field of Assignments tab of a .course yields "No matching folders were found", even if path "a/b/" exists and is not in list of Assignments. Same thing for Handouts.

**Comment by DrXyzzy** [comment]
Searching for just "b" will match any of the following, assuming they exist and the last name in the path is a folder:
- b
- a/b
- a/s/d/b
- Assignments/B12

but not these:
- a/b/c
- b/c

**Comment by williamstein** [comment]
> Looks as if assignment/handout search is doing case-insensitive search on the basename.

This was exactly the intention when the code was written (I think by me).  I.e., it is doing what I wrote it to do.  However, I can see why you might find this confusing. 

It may be better though to put the work into a directory tree browser, rather than this issue.

**Comment by DrXyzzy** [comment]
Closing, because code is working as designed. I agree with putting effort into directory tree browser.

**Comment by williamstein** [comment]
Upon further reflection, I'm re-opening, since maybe it was "as designed" (by me) but maybe my design was confusing.  If people expect the behavior you mention (and it is consistent and doesn't hurt), it is probably very easy to change code to work.

**Comment by novoselt** [comment]
People don't seem to invest time into making their opinion on the topic, but when prompted, I expect the search to be the search for the assignment itself, not for a part of hierarchy. So I am reclosing reopening.
