### ISSUE TITLE
editor: show count and cursor position

### ISSUE THREAD

**Issue by stats-matt** [sagemathinc/cocalc#329]
It may be helpful in LaTeX documents to have a word count option.

**Comment by haraldschilly** [comment]
Sounds like a nice idea. For now, you can open up a terminal and run a counter. For example:

```
$ texcount -inc -incbib -sum -stat <filename.tex>
```

**Comment by mthomas7** [comment]
Definitely! I am also thinking of a "click button" option for a class where coding is still a new idea, so that word counts could be part of the requirements (without having use page lengths when margin size might vary).

**Comment by williamstein** [comment]
Could also display the row/column cursor position...

**Comment by williamstein** [comment]
See https://github.com/sagemathinc/smc/issues/1273

**Comment by mforbes** [comment]
Also for Markdown files: it would be helpful to be able to select a chunk of text, and then count the words in this region.

Use case: Brainstorming for a grant submission, resulting in several character-limited responses.

**Comment by williamstein** [comment]
There is a wordcount feature now (just change the frame type or make a new frame):

<img width="466" alt="image" src="https://github.com/user-attachments/assets/7898e5a6-e59b-4f6c-aaef-fa0c978c5896">
 
<img width="452" alt="image" src="https://github.com/user-attachments/assets/1ca2d9ae-c40a-473f-a128-7de727c681d0">
