### ISSUE TITLE
%latex mode in sagews is broken

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3302]
Make sure there is no local `~/bin/sage` file. Create a sage worksheet with these cells and run them:

```
%md
hello
---
%latex
world
```

The second cell produces error output:
```
An error occurred.
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex 2018.10.13)  18 OCT 2018 20:32
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
...
Package etexcmds Info: Could not find \expanded.
(etexcmds)             That can mean that you are not using pdfTeX 1.50 or
(etexcmds)             that some package has redefined \expanded.
(etexcmds)             In the latter case, load this package earlier.
)))
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty
Package: pdftexcmds 2018/01/21 v0.26 Utility functions of pdfTeX for LuaTeX (HO
)
...
Output written on tmpELv5zW.pdf (1 page, 9625 bytes).
PDF statistics:
 13 PDF objects out of 1000 (max. 8388607)
 8 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

Next, under Project Settings > Project control > Software Environment, select `Previous` image and click `Save and Restart`. Rerun the cells or make a new .sagews with the same cells. Normal LaTeX ouput appears from the second cell.

**Comment by haraldschilly** [comment]
Well, sounds like a normal linux update of packages caused this. What I don't understand at all is: `Output written on tmpELv5zW.pdf (1 page, 9625 bytes).` in the output. 

 However, to figure this out, I've boiled this down to that sage command sequence:

```
sage: s = 'hello'
sage: sage.misc.latex.Latex.eval(sage.misc.latex.latex, s, filename="sage-latex.png", locals={}, globals={})
```
There is also a way to switch the engine, i.e. `engine='xelatex'` as an alternative. What's weird is that both do not produce any output file, either (at least I can't find it)

**Comment by haraldschilly** [comment]
aha, peeking into sage's code, this is plain stupid. it should use the exit code of running any tex processing engine ... not look for the occurrence of `Error`

```
    if e.find("Error") == -1:
            shutil.copy(os.path.join(base, filename + ".png"),
                        os.path.join(orig_base, filename + ".png"))
            shutil.rmtree(base)
            return ''
        else:
            return
```

**Comment by DrXyzzy** [comment]
Reported by Maria Hempel.

**Comment by haraldschilly** [comment]
After changing the actual sage code, I found out where the temp files are and what sequence of commands are being run. It's the `convert` command:

```
$ convert -density 161x161-trim sage50.pdf sage50.png
convert-im6.q16: not authorized `sage50.pdf' @ error/constitute.c/ReadImage/412.
convert-im6.q16: no images defined `sage50.png' @ error/convert.c/ConvertImageCommand/3258.
```

no clue what this is about, but at least we're a step closer. Regarding latex processing in sagews, I still suggest to switch to the `xelatex` engine because of its improved unicode handling. Not sure if that works, though, because of that involved macro and other preamble code injected by sage.

**Comment by haraldschilly** [comment]
Interesting, that above looks like a side effect of protecting web services using `convert`.

https://stackoverflow.com/questions/42928765/convertnot-authorized-aaaa-error-constitute-c-readimage-453

**Comment by haraldschilly** [comment]
ok, tweaking that permission file helps. I'll have to write a test for that, though.Do you know all usages of `convert` in our codebase? That one is `pdf` → `png`.

![screenshot from 2018-10-19 13-31-38](https://user-images.githubusercontent.com/207405/47215935-79b78380-d3a3-11e8-96b0-514c2c186c4c.png)

**Comment by DrXyzzy** [comment]
I don't know other uses of `convert`. Do you want me to write pytests for this issue?

*Side note: ImageMagick 7 replaces command name "convert" with "magick".*

**Comment by haraldschilly** [comment]
ah, yet another detail to be careful with image magic 7. and well, if at all, I'm adding that test to the integration tests. I guess it doesn't hurt to test if `%latex` works, though...

**Comment by haraldschilly** [comment]
a fix for `convert` is deployed (project restart required) and there should be an internal test catching that problem earlier next time.  hence I'm closing this ticket…
