### ISSUE TITLE
when selecting text in timetravel changes, highlighting is vertically displaced from cursor in second and later change blocks

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3306]
- open a .term
- create a file `foo.txt` with 200 or so lines of text, for example
    ```
    openssl rand -out foo.txt -base64 10000
    ```
- open editor tab for `foo.txt`
- change a line near the top and a line near the bottom e.g. insert "HELLO" at start of line 5 and "WORLD" at start of line 130.
- wait a few seconds for sync
- open timetravel view of `foo.txt` and select Changes
- position scrubber so that two change blocks are shown
- try selecting text in the lower change block with mouse
- note that highlighted text is a couple lines above cursor
- note that selected text is what was under the cursor

![screenshot 2018-10-24 12 30 28](https://user-images.githubusercontent.com/528072/47449646-c7a7ff00-d788-11e8-89d1-77b2a8c105a7.png)

May be related to #1292

**Comment by johnjeng** [comment]
Fixed by @williamstein
