### ISSUE TITLE
some users cannot create account because `@` in email address is rejected

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3327]
When email address is entered during account creation, in some rare cases`@` is not recognized. One report was using Chrome 70.0.3538.77 with Win 7, resolved when user switched to a different computer using Win 10.

Reported by Nicole Bausch (help req 5880) and Scott Steele (help req 5883). Screenshots were included with those requests.

**Comment by DrXyzzy** [comment]
see #3329 probable fix

**Comment by williamstein** [comment]
See https://github.com/facebook/react/issues/1159#issuecomment-431877049

Fixed via https://github.com/sagemathinc/cocalc/commit/6930b54d9ff10dc82050582b64d6b73dc6d1a793
