### ISSUE TITLE
improperly indented code in sage worksheet is ignored

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3331]
This in a sagews compute cell:
```
print(1)
    print(2)
print(3)
 print(4)
print(5)
```
produces this output, and no error message:
```
1
3
5
```

**Comment by williamstein** [comment]
No longer broken:

<img width="906" alt="image" src="https://github.com/user-attachments/assets/a1fa43d4-aac6-4843-9def-d02176ea3274">
