### ISSUE TITLE
The X11 project doesn't work in Ubuntu 18.04 Firefox 62.0.3

### ISSUE THREAD

**Issue by certik** [sagemathinc/cocalc#3338]
I tried the new X11 support, I created a new project, and the terminal doesn't show any text (!), but it seems to work otherwise, as a blind terminal. I launched `xclock &`, and a new window title xclock appeared, but no clock. So something is broken.
![screenshot_2018-11-07 test 3 - cocalc](https://user-images.githubusercontent.com/20568/48142118-63e20380-e269-11e8-97ca-328fff94ecbf.png)

This is on cocalc.com.

**Comment by haraldschilly** [comment]
did you explicitly click on the "xclock" tab? it might not have focused properly.

the terminal is not ok, obviously. which font have you set in your account settings? (there is something about terminals). try setting it to default, maybe that helps.

**Comment by williamstein** [comment]
Thanks for trying this.

> a new window title xclock appeared

You currently have to explicitly click on the xclock tab to show it.  

I'm going to close this.  If there is a specific terminal bug with that version of Firefox and your font settings, please open a ticket about that.  You can make a new terminal by clicking +New --> Terminal.  The terminal for X11 desktop is exactly the same as with +New -> Terminal.

All that said, it's much better to use CoCalc with Chrome than Firefox.  We have even have to completely not allow firefox on cocalc several times over the years.

**Comment by certik** [comment]
Clicking on the window shows it, I didn't know I had to do that. So X11 works.

Regarding the terminal, I couldn't find any font settings in my settings, sorry about that.

New -> Terminal creates a terminal that works for me.

**Comment by williamstein** [comment]
@certik -- you likely have Droid Sans Mono as your terminal font in account settings.  This bug is 

https://github.com/sagemathinc/cocalc/issues/3304

What happens is that font is loaded from the web at the same time as the terminal is being opened.  It's a race condition.

**Comment by certik** [comment]
I can't find the settings font option, but by refreshing the page a few times, the font suddenly appears in the terminal. So that's that.

**Comment by williamstein** [comment]
> Clicking on the window shows it, I didn't know I had to do that. 

That is pretty confusing -- I'll fix it now.

> I can't find the font settings option

Click on account in the upper right, then Preferences and it is in  Terminal settings.   

> font suddenly appears in the terminal. So that's that.

It's now cached.  We'll either fix this caching issue, or disable alternative fonts...

**Comment by williamstein** [comment]
> long time ago. 

You made your account long long long ago!
