### ISSUE TITLE
xterm.js -- for cocalc, either disable linkify (the thing that turns links into clickable) or fix it being VERY buggy

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3343]
Just crashed for me, and I'm sick of it causing trouble:

![screenshot 2018-11-10 at 9 55 38 pm](https://user-images.githubusercontent.com/1276278/48309642-7b541180-e533-11e8-94a7-2146df72ae43.png)

**Comment by slel** [comment]
One reproducible annoyance about active links in the CoCalc terminal
is that selecting them seems to additionally click them.

To reproduce:
- open a CoCalc terminal
- type `echo https://doc.cocalc.com`
- with the mouse, select the url, either in the echo command or in its output

Then the link opens in another tab. Workaround for the link not to open:
select extra characters, for instance a space character after or before the link.

**Comment by williamstein** [comment]
If this is also a problem with xterm.js in general, maybe you could report it upstream too.

**Comment by slel** [comment]
Possibly related: https://github.com/jupyterlab/jupyterlab/issues/5489

**Comment by williamstein** [comment]
I can't reproduce the problem @slel added about selecting in the current xterm.js we're using, and I also haven't seen any linkify issues in a long time either.  So closing this.
