### ISSUE TITLE
markdown (and other) printing is broken in Chrome version 70

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3354]
1. Create a Markdown file.
2. Click print on the preview (or the source code).
3. The preview appears for a moment in Chrome, then vanishes.  This is surely probably due to some recent security change in the behavior of Chrome, since I think the code hasn't been touched in a long time.  Also it works fine in other browsers like latest Firefox.

WORKAROUND: Use Firefox for printing.

REQUESTED BY: Emmanuel Garcia

![screenshot 2018-11-20 at 9 47 30 am](https://user-images.githubusercontent.com/1276278/48792588-7ae11680-eca9-11e8-9cd3-75cc4a602967.png)

**Comment by DrXyzzy** [comment]
I am seeing different behavior, but still a bug, with macOS 10.13.6 and Chrome 70.0.3538.110. When I click Print in the rendered View, the preview appears and does not vanish. If I then click in the source pane while the preview is up, labels for the buttons in the source disappear:

<img width="569" alt="print-chrome" src="https://user-images.githubusercontent.com/528072/48793888-fe0c6780-ecbd-11e8-8a95-77cedf68a6c4.png">

I'm able to print, and when I close the pdf view, the button labels in the .md source return to normal.

**Comment by williamstein** [comment]
I was testing with Version 70.0.3538.76 (Official Build) (64-bit) on ChromeOS.

I can't reproduce your "missing button icons".   If you can systematically reproduce that behavior, make a new issue about it.  Since the icons are font-awesome and rendered using SVG/javascript, my guess is that is just a side effect of an uncaught exception, which you could see in your console.

I've never seen missing font-awesome icons in any situation ever, except when refreshing to load a new version of the page and hitting caching confusion (probably caused by cloudflare).

**Comment by haraldschilly** [comment]
so, unless someone can disprove my claim for 71, all we can really do is to add a warning banner for version 70 only …

**Comment by williamstein** [comment]
It's probably a race condition in coming I wrote.  I should rewrite it
better to be robust.
