### ISSUE TITLE
markdown source pane button icons vanish during print preview 

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3355]
Seen with macOS 10.13.6 and Chrome 70.0.3538.110 (Official Build) (64-bit).

1. Open a .md file with some source text in it.
1. Split the edit window so that Source Code and Rendered View panes are both visible.
1. Click in Rendered View and click the Print button. Print dialog pops up.
1. Click in the Source Code and notice that the toolbar appears, but button icons are missing.
1. Close the print dialog window and Source Code button icons return.

<img width="569" alt="print-chrome" src="https://user-images.githubusercontent.com/528072/48797643-5d6f7500-ecc8-11e8-86a7-7c02fdcf1734.png">

This is 100% repeatable on my computer. I have refreshed Chrome, restarted the project, and closed and reopened the file. Doing the steps above with Javascript console open does not show any errors.

See #3354 for another Chrome printing issue.

**Comment by williamstein** [comment]
Can you make a screencast illustrating this?  It's really odd!

**Comment by williamstein** [comment]
long since gone...
