### ISSUE TITLE
Saving file with same name overwrites existing file without warning

### ISSUE THREAD

**Issue by sbiancaj** [sagemathinc/cocalc#3356]
It seems that when saving a .ipynb file that has the same name as an existing file in the same directory, the original file is simply overwritten without warning. Can this be changed? We are hoping to use cocalc for teaching purposes but can see this becoming a problem with many students saving their work.

**Comment by haraldschilly** [comment]
Could you please expand why and how this happens? What's the workflow and what would you expect to happen instead?

For teaching, the basic idea is that each student has their own project, where each of them receive a copy of a file. When collecting from students, their files are sorted into individual directories for each student in the master project of the course. At no point there is an overlap.

https://doc.cocalc.com/teaching-instructors.html

**Comment by sbiancaj** [comment]
For example, I create a file called "test.ipynb" in my working directory, work in this notebook for a while, then save and exit. If I then have another *different* file called "test.ipynb" in a different directory, and I move this file into my working directory, it appears that the first "test" file remains, but the second one is gone - I can't find it in either directory. What I would expect to have seen instead is a warning prompt that says something along the lines of: "The destination directory already contains a filed called "test.ipynb", are you sure you want to replace it?". 

I understand that there shouldn't be any overlap between students' projects when collecting their work, but I'm more concerned about accidental overwriting of work due to lack of experience with the cocalc environment. Myself and other instructors have already encountered this problem ourselves while trying to write a set of test projects in preparation for teaching.

**Comment by williamstein** [comment]
We have frequent snapshorts *and* timetravel that records all edits, so it is easy to recover from this.
