### ISSUE TITLE
after entering payment info, customer has to select subscription a second time

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3363]
Seen in current Chrome on macOS. Also reported by Kyle Kelley.

1. Open an account that has no prior credit card entered.
1. Click `Account` > `Subscriptions/Course Packages`.
1. (Note: there is still no way to enter payment info without selecting a plan.)
1. Select $14/mo Standard Plan.
1. Enter valid credit card and click "Add Credit Card".
1. The surprise is that, instead of continuing with plan selection dialog, customer is taken back to the first subscriptions screen. See screenshot below. Payment method has been stored, but now customer has to click `Add Subscription or Course Package...` and select a subscription again

<img width="1029" alt="order-bug" src="https://user-images.githubusercontent.com/528072/48986507-a3b74080-f0db-11e8-9de2-48b655933b7a.png">

**Comment by williamstein** [comment]
@johnjeng fixed this -- now live.

**Comment by rgbkrk** [comment]
Thanks! Happy to see this get fixed so your sign up funnel leads to conversions with minimal user interaction.
