### ISSUE TITLE
jupyter2: autocomplete stays active when switching cells

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3366]
that's mainly a weird and confusing behavior. Watch the short a screencast. I press the tab key and then normal mouse clicks ... not really "exotic".

https://share.cocalc.com/share/b9bacd7b-6cee-402c-88ed-9d74b07f29a1/jupyter2-weird-autocomplete.webm?viewer=share

**Comment by williamstein** [comment]
video no longer exists, and anyways my guess as to what you meant by this is no longer broken.
