### ISSUE TITLE
make jupyter classical and modern (cocalc) notebooks coexist

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3367]
We have a [BIG Warning](https://github.com/sagemathinc/cocalc/wiki/JupyterClassicModern#big-warning) to users about risks of running Jupyter notebooks in Classical and Modern modes at the same time. Still, it is possible for users to inadvertently create that situation, then need TimeTravel to recover.

We need to prevent unwanted side effects when both modes of notebook are running. Also consider:
1. be more explicit about which mode is in use or about to be used (when viewing Files list)
1. add warnings in `Plain Jupyter Server` and `JupyterLab Server` sections in Settings page
1. be explicit that choosing modern/classical while in a notebook affects the account setting, not just the notebook in use

**Comment by williamstein** [comment]
My only goal with classic is to delete it.
