### ISSUE TITLE
course: skip "collecting & return", but still allow to grade

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3375]
grading an assignment in courses first collects the files, then creates a file in the collected files, and sends them back to the student.

there are situations where the student files use up a lot of disk space and it isn't feasible to collect and return all these files. instead, replace the collect & return operations by a way to write the grade-file directly into the student's assignment directory.

Req: Stuart Littlefair

**Comment by sj-graves** [comment]
I second this motion.

**Comment by novoselt** [comment]
It seems to be a very rare issue...
