### ISSUE TITLE
LaTeX editor, features request

### ISSUE THREAD

**Issue by JCBustamante** [sagemathinc/cocalc#3378]
I've been working with the LaTeX editor, here are features that I find might be useful.

- Globally change the language setting for the editor. As things are right now, one has to change it for every single file. I have projects in French and also in English, and it is quite cumbersome to change this setting each time. Also, the LaTeX editor color theme could be made independent of the sageworksheet color theme.
- Have some kind of "assistant" to include figures that one may have locally in a latex document. Something like what one gets through Alt + I + G in Kile. One could either chosse a file that is already on the project, or browse to the local computer, upload, and do everything automatically.

- Being able to prevent compilations : from time to time, when coding, I know that some environment, or equation is not finished, so an attempt to compile would result in several fatal errors. Yet CoCalc tries to render the documents, resulting in all those errors. This takes time, and freezes things in an non necesary way.

**Comment by williamstein** [comment]
> Being able to prevent compilations 

This is implemented, but off by default.  Go to account preferences, and uncheck the box next to "Build on save: build LaTex file whenever it is saved to disk".  There is a separate shortcut and button to explicitly build, and it won't build on save by default with that unchecked.

For the other three issues can you, make three separate GitHub issues and close this one?

1. Global language setting for the editor, by default.

2. Independent color themes for different file types (e.g., latex, sage, .py, etc.)

3. Latex figure inclusion wizard.  (Incidentally, it is now possible to actually use Kile in CoCalc via the new X11 Desktop support... just in case you want to do so for including a figure.)

Thanks!!
