### ISSUE TITLE
webapp/jupyter2: safari $element.offset

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3381]
safari: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15`

smc_git_rev: c38fc660dfacc0bf5c90939782309a0689264c7f

Date: 2018-11-30 06:27:41.440806

`undefined is not an object (evaluating 'r.left')`

```
window_click@https://cocalc.com/static/smc-cabe8419b5c4ee4a26ad.cacheme.js?cabe8419b5c4ee4a26ad:5:813155
dispatch@https://cocalc.com/static/1-cabe8419b5c4ee4a26ad.cacheme.js?cabe8419b5c4ee4a26ad:6:405549
_wrapper@https://cocalc.com/static/smc-cabe8419b5c4ee4a26ad.cacheme.js?cabe8419b5c4ee4a26ad:5:890137
```

---

This is Safari, maybe because old (?), and I think the error itself (window_click + <something>.left) points to `smc-webapp/jupyter/cell-list.tsx` → `CellList::window_click`

Is there something known about Safari and jquery's `offset()`?

The obfuscated code is around here, though:
```
t.scroll_cell_list=function(e){
var n=$(t.cell_list_ref);if(n.length>0){var r,a=void 0;
if("number"==typeof e)return void n.scrollTop(n.scrollTop()+e);
if("cell visible" ...
```

That's only nearby, not exactly there. Could be off due to slightly wrong parsing of the browser, IDK...

**Comment by williamstein** [comment]
no clue.  ancient and not relevant anymore.
