### ISSUE TITLE
can't scroll terminal

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3389]
there is a vertical scrollbar next to each terminal. I can't use it, because there is somehow another div in front of it (it's the one which displays the terminal content, because when I try to scroll, it selects the text).

Below is a screenshot, where I changed the selected `div`'s z-index to 1 and background to transparent. with these changes I can use the scrollbar again, while I can still mouse-wheel scroll and select terminal text. I don't know if these changes actually make sense, though, or if there is a better solution. That's just what did work for me by editing the DOM directly.

![screenshot from 2018-12-03 13-59-18](https://user-images.githubusercontent.com/207405/49375211-f8724100-f703-11e8-83c5-7c94709a0da8.png)

my browser is chrome 71

**Comment by williamstein** [comment]
I see the same thing in Chrome 70 on ChromeOS Stable.  This was likely caused by switching to the DOM renderer (from canvas).  It's an upstream issue, but I'm fine with us trying to fix it somehow.
