### ISSUE TITLE
banners for 'timeout' and 'saving' linger until closed manually by clicking 'x'

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3390]
Reported by Mark Quinn, when working with an .ipynb file:

![](https://sagemathcloud.zendesk.com/attachments/token/TPYY8nCv9aGRaM4n0KlxgaPCI/?name=PastedGraphic-2.png)

![](https://sagemathcloud.zendesk.com/attachments/token/Lb0JJ3WvZufOebVureWAPwavy/?name=PastedGraphic-1.png)

In general, such alerts should go away when the problem is resolved.

**Comment by williamstein** [comment]
Duplicate of https://github.com/sagemathinc/cocalc/issues/3557

**Comment by williamstein** [comment]
> In general, such alerts should go away when the problem is resolved.

Actually the alert should not happen at all unless it really is important and requires manual intervention.
