### ISSUE TITLE
please install CERN Root data analysis software

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3398]
I found the latest binary release of CERN Root for Ubuntu 18 here: https://root.cern.ch/content/release-61406 - file `root_v6.14.06.Linux-ubuntu18-x86_64-gcc7.3.tar.gz`.

The archive extracts to a single directory, `root`, and is designed to run anywhere you install it, including read-only filesystems, for example:

> You can execute the scripts in $ROOTSYS/tutorials (or sub-directories) by setting your current directory in the script directory or from any user directory with write access. Several tutorials create new files. If you have write access to the tutorials directory, the new files will be created in the tutorials directory, otherwise they will be created in the user directory.

-- from https://root.cern.ch/root/htmldoc/guides/users-guide/ROOTUsersGuide.html#installing-root

To test the install:

1. Start an x11 CoCalc session.
1. In the terminal pane, cd to a user-writeable working directory, and do
    ```
    export ROOTSYS=path/to/root
    . $ROOTSYS/bin/thisroot.sh
    $ROOTSYS/tutorials/root
    ```

You will then get a GUI for using the tutorials. Try hsimple and you should get a bell curve.

**Comment by slel** [comment]
Oh I see, the new X11 support opens the way for more than
what could be worked on at #239.
