### ISSUE TITLE
please install libpostgresql-jdbc-java

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3400]
Here is one link to an rpm: [libpostgresql-jdbc-java](https://packages.debian.org/sid/libpostgresql-jdbc-java)

To test the install, there is this [command-line CoCalc demo of postgresql with JDBC](https://share.cocalc.com/share/4cf9a82a-5e50-4ccb-b693-e71722be780e/pgjar/README.md?viewer=share) that works in user land. It requires postgresql running on a TCP port. It needs to be modified for different installed path of the JDBC connector, of course.

This install will get us a step closer to supporting LibreOffice Base with postgresql.

**Comment by haraldschilly** [comment]
ok, I'll end up installing:

* libmysql-java: Java database (JDBC) driver for MySQL
*  libpostgresql-jdbc-java: Java database (JDBC) driver for PostgreSQL
*  + libpostgresql-jdbc-java-doc
* **sqlline: JDBC command-line utility for issuing SQL** ← maybe interesting to see what this does?
* libjline-java-doc: some dependency ...
