### ISSUE TITLE
Latex preview with \include

### ISSUE THREAD

**Issue by mthomas7** [sagemathinc/cocalc#3403]
I don't think this is in another issue - apologies if it is and I couldn't find it.

In a document with \include commands (one master file with a bunch of included other tex files) there doesn't seem to be a nice way to keep a preview of the main document while editing a tex file which is included in the master document. Either being able to preview only the piece being edited or preview the entire document while still being able to edit the piece being included would be a nice feature.

**Comment by williamstein** [comment]
This is https://github.com/sagemathinc/cocalc/issues/904

The current suggested workaround is here: https://doc.cocalc.com/latex.html#how-to-deal-with-large-documents-across-multiple-source-files

That said, I've laid the foundations for properly implementing this, but just haven't had the time to do it yet.
