### ISSUE TITLE
jupyter2: sanitize or encapsulate included CSS styles

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3410]
There are jupyter notebooks which do contain html and css code. Here is a stripped down version of such notebook, which is part of the bayesian for hackers online book: [Ch6_Priors_PyMC2.ipynb](https://share.cocalc.com/share/20e4a191-73ea-4921-80e9-0a5d792fc511/Ch6_Priors_PyMC2.ipynb?viewer=share)

Opening in cocalc looks like in the screenshot below, which is bad. I don't know what to do either, though. Removing all style tags from html output? Encapsulating all HTML output in an iframe?

![screenshot from 2018-12-12 17-57-43](https://user-images.githubusercontent.com/207405/49885588-f6149300-fe37-11e8-8890-a6447ec0d30b.png)

**Comment by williamstein** [comment]
This is too vague.  Also, maybe the user is happy with being able to change the CSS of all of cocalc.
