### ISSUE TITLE
Instructor upgrades to course projects doesn't respect global maximums

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#3424]
An instructor can add arbitrary upgrades to their student's projects up to what they own. So they could allocate 32gigs of ram per student project if they have a sufficient amount.
<img width="626" alt="screen shot 2018-12-17 at 11 33 05 am" src="https://user-images.githubusercontent.com/618575/50081759-8a437900-01ef-11e9-9d10-4f14c3512c01.png">

**Comment by novoselt** [comment]
Upgrades are deprecated.
