### ISSUE TITLE
latex (etc.) spell checker: provide a way to show suggestions for correct spelling

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3461]
Here's the obvious motivation:

> Hi, I'm testing currently cocalc an am really fond of it so far.  I enabled the spellchecking for my doc, and it is showing some red markings, but I don't know how to get suggestions for how i should write the word. Is this not a feature or am I missing something? 

This is not yet implemented.  A stupid workaround is to copy and paste the word into google and let it suggest spellings.

We really need to implement this!

**Comment by ml1nk** [comment]
In addition, a text field to define 'tex-command' of [aspell](http://aspell.net/0.50-doc/man-html/4_Customizing.html) in the settings would be helpful [spell-check.ts](https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/frame-editors/code-editor/spell-check.ts).

**Comment by williamstein** [comment]
Codemirror now support the browsers native spellcheck, which does this, is far more configurable, and can really be setup how your browser supports or extended with plugins, etc.  Will be live soon.
