### ISSUE TITLE
add assignment react warning "Can't perform a React state update on an unmounted component."

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3462]
I just saw this traceback on my dev server right after doing a search for assignment folders:

![screenshot 2019-01-14 at 6 13 54 pm](https://user-images.githubusercontent.com/1276278/51154323-452f5880-1828-11e9-8c8c-9a6b74762634.png)

**Comment by novoselt** [comment]
@williamstein Should this still be addressed somehow or got obsolete?

**Comment by williamstein** [comment]
> right after doing a search for assignment folders

We don't even have a "search for assignment folders" anymore. The functionality for adding an assignment got rewritten about 2 years ago to instead be a directory tree browser.
