### ISSUE TITLE
project log: restricting log by searching results in log with entries out of order (at least in production)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3465]
For many of my projects, if I do a search of the project log, it shows the results NOT in reverse chronological order.  This makes no sense.  For example, look at searching for .term in our omnibase project:

![image](https://user-images.githubusercontent.com/1276278/51156011-86c30200-182e-11e9-984a-a51fce34ed21.png)

I have NOT been able to reproduce this in my cc-in-cc dev project.  So I wonder if the issue is some subtle problem involving JSON and Date types and optimizations for fast database querying with less load...  I.e., totally my fault.

**Comment by haraldschilly** [comment]
here is a screenshot from my cc-in-cc dev project (for the record: `https://cocalc.com/14eed217-2d3c-4975-a381-b69edcb40e0e/port/56754/projects/bc6f81b3-25ad-4d58-ae4a-65649fae4fa5/log`)

![screenshot-cocalc com-2019 01 15-10-08-47](https://user-images.githubusercontent.com/207405/51170099-e01e4600-18ad-11e9-8e0a-6df4ef228b5e.png)

**Comment by haraldschilly** [comment]
we confirmed that this works
