### ISSUE TITLE
project mintime upgrades stored as float (should be int)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3472]
I don't want to disclose the project ID or user ID publicly, but this is from the DB:

```
psql> select users from projects where project_id = 'xxxxxxxxx';
```

```json
{
  "<other user ids>": {},
  "xxxxxxxxxxx": {
    "hide": true,
    "group": "owner",
    "upgrades": {
      "cores": 0,
      "memory": 22.5,
      "mintime": 972.0000000000001,
      "network": 1,
      "cpu_shares": 0,
      "disk_quota": 45,
      "member_host": 1,
      "memory_request": 0
    }
  }
}
```

This is a problem, because mintime is expected to be an integer. There were implications on the backend, and I thought it is the DB acting up. But well, the problematic value is actually there. … it's also not the only one, so, there must be some systematic issue.

and btw, this is a student project. hence this must come from the upgrade dialog in courses...

**Comment by williamstein** [comment]
Why don't we just write our code that depends on this (I guess the postgresql queries) so it doesn't matter?   After all int is just a *subset* of float in Javascript and JSON.   There's no real need for mintime to be an int, is there?

**Comment by haraldschilly** [comment]
Do we really need sub-second idletimes? I don't know which parts of the code assume integers, do you? IMHO it is more safe to keep this as it was before.

**Comment by williamstein** [comment]
> Do we really need sub-second idletimes? 

No.

> I don't know which parts of the code assume integers, do you? 

Isn't it only that complicated PostgreSQL query you wrote?

**Comment by williamstein** [comment]
Upgrades are deprecated so we won't fix subtle issues like this with them.
