### ISSUE TITLE
splitting a .term in one browser can cause output truncation in another browser window on the same term

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3473]
Seen with `Chrome 71.0.3578.98 (Official Build) (64-bit)` and Safari `11.1.2 (13605.3.8)`, on macOS `10.13.6 (17G65)`.

1. Open the same .term with two browser windows. They can be the same or different sessions. For different sessions, you can use anonymous/incognito for one of them, or use Chrome for one and Safari for the other.
1. Do `ls` or something else that gives a full screen of output.
1. Split the screen into upper and lower frames in the first browser window. 
1. In the second browser window, close the .term using the "x" at upper right of the tab for its file.
1. In the second browser window, find the .term file just closed in the project log and reopen it.
1. Observe that text is limited to the upper half of the second window.
1. Recover full window use by splitting the second window into upper and lower halves and then closing the lower half.

NOTE: With Chrome as the first browser and Safari as the second one, I have seen output shifted to the upper half in Safari immediately, without closing and reopening the terminal tab, but this is not repeatable.

**Comment by DrXyzzy** [comment]
Full screen of output:

![bug-1](https://user-images.githubusercontent.com/528072/51280245-cf9cc700-19a4-11e9-9412-4c4f439d4fd9.png)

Browser window 1 after split into upper and lower panes:

![bug-2](https://user-images.githubusercontent.com/528072/51280274-dcb9b600-19a4-11e9-91e4-e9760f5e9a4b.png)

Browser window 2 after closing and reopening the .term:

![bug-3](https://user-images.githubusercontent.com/528072/51280282-e3e0c400-19a4-11e9-84fc-9dc6c957576d.png)

**Comment by williamstein** [comment]
> NOTE: With Chrome as the first browser and Safari as the second one, I have seen output shifted to the upper half in Safari immediately, without closing and reopening the terminal tab, but this is not repeatable.

Safari's flexbox implementation is non-existent/broken, so we have to use a Javascript shim.  I guess this could cause that sort of behavior.

**Comment by williamstein** [comment]
Wait, this is 100% intentional, since the size of the terminal *must* be defined on the backend.  There's no good way around this.  A terminal has a number of rows and columns, which is the MIN of all viewers.
