### ISSUE TITLE
jupyter2: restart & eval skip cells with Sage and Julia kernels, at least.

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3480]
I don't understand what's going on, and I'm very confused. A jupyter2 notebook (cocalc one), selecting restart and eval all or clicking the :fast_forward:  button evaluates the first cell, does nothing (?) with the ones in the middle, and then the last one as third. see screenshot. It **does** work for a python3 (ubuntu) kernel, but **not** for sagemath, sage 8.6, or julia 1/0.7. I didn't try this in all kernels, and I was able to reproduce this in a test project which runs the "default" software, and well, I discovered this in "experimental". Could someone else also test this?

## sage 8.6 (only in "experimental")

![screenshot from 2019-01-18 22-14-02](https://user-images.githubusercontent.com/207405/51413256-91eb9a00-1b6e-11e9-9253-d78dee7c15a2.png)

## julia 1.0

![screenshot from 2019-01-18 22-21-15](https://user-images.githubusercontent.com/207405/51413473-65844d80-1b6f-11e9-81ca-8786dacc427a.png)

## sagemath (in "default")

![screenshot from 2019-01-18 22-23-15](https://user-images.githubusercontent.com/207405/51413584-bbf18c00-1b6f-11e9-8bc3-96fa23108466.png)

![screenshot from 2019-01-18 22-23-24](https://user-images.githubusercontent.com/207405/51413591-beec7c80-1b6f-11e9-8e87-0b5c7df41c5d.png)

**Comment by haraldschilly** [comment]
... and also interesting. refreshing the browser doesn't help at all.

**Comment by williamstein** [comment]
My guess is that it's trying to run the code slightly before the kernel has truly started running -- so probably it'll fail when kernels take a long time.  Python3 is fast but Sage is slower.  I'll likely fix this tonight.

**Comment by williamstein** [comment]
It's a problem mainly because sync is now much faster for this sort of control.

**Comment by williamstein** [comment]
(and it probably happened before, but with lower probability.)
