### ISSUE TITLE
Sharing unlisted defaults to listed

### ISSUE THREAD

**Issue by edgarcosta** [sagemathinc/cocalc#3485]
This might be related with #2885.

In short, I tried to list a file unlisted (that doesn't have internet access), and even though it says it can share it publically, it changes to that when I click update and shows up on the public shared notebooks.
Here is a gif:
![unwantedshare](https://user-images.githubusercontent.com/322822/51445190-5a94fe80-1cd0-11e9-9500-930a5d9f5708.gif)

**Comment by haraldschilly** [comment]
hmm, yes, this could be  #2885

**Comment by haraldschilly** [comment]
ok, I think I know what's going on.

**Comment by slel** [comment]
Fixed by #3486.
