### ISSUE TITLE
project list in Juno iPad app might not match CoCalc project list

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3496]
Reported by Michael Moortgat.

Project list can be shorter in Juno than with web browser using CoCalc. Probably related to recent change to default view showing most recently active (past 3 weeks) projects in project list. But also Juno lists 2 projects for me that are not in my CoCalc list with Chrome.

In an account with 101 projects, 23 are listed when I use Juno, with no option to see the rest. When I use Chrome on my laptop, the list of projects in the past 3 weeks has 21 projects. Juno shows two projects that I don't see in my CoCalc project list, even when selecting "Load projects older than 3 weeks..." and then "Show 51 More Matching Projects..." or when searching for them by name. The two phantom projects that show up in Juno and not in Chrome have names
- JMM 2019 A - courses/math-173-a
- JMM 2019 B - courses/math-173-a

I'm going to review & test the API for listing projects in the account that gave the result above. Labeling this a possible API bug for now. May also have upstream issue with Juno.

**Comment by DrXyzzy** [comment]
The two projects that appeared in Juno and not in Chrome were both hidden, and showed up in Chrome when I selected the Hidden checkbox. So that problem is solved. Changing project title accordingly.

**Comment by williamstein** [comment]
If upstream Juno uses our api, the need to change `project` somewhere to `project_all` -- that would be a quick fix to restore the previous behavior.

Relevant code: https://github.com/sagemathinc/cocalc/blob/master/src/smc-util/db-schema.js#L1200

**Comment by williamstein** [comment]
A quick workaround for now, which @haraldschilly suggested when somebody reported this, is to open cocalc in safari, show all old projects, then click on them to make them not old anymore.

We could also put a hack in the API server so projects = project_all only there, but that may cause other bad surprises.

**Comment by navoshta** [comment]
Thanks for letting me know @DrXyzzy, @williamstein — I will update the endpoint I use in Juno so that it displays all projects. This change will be released with Juno 1.3.0 in the next week or so.

**Comment by williamstein** [comment]
I think we have basically no juno users, or certainly no revenue from it.
