### ISSUE TITLE
Support for architecture ppc64le 

### ISSUE THREAD

**Issue by marcoaleixo** [sagemathinc/cocalc#3499]
Hello,
I'm using a machine with this architecture: ppc64le
Is it possible to compile in some way in my architecture?

Thank you.

**Comment by haraldschilly** [comment]
what exactly do you try to compile? cocalc is an online service, so, you must mean something else. or well, unless you want to cross-compile something...

**Comment by haraldschilly** [comment]
@marcoaleixo I'm closing this ticket,since you didn't clarify what this is actually about.
