### ISSUE TITLE
cocalc auth api issue

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3501]
From Alex (Juno developer):

Looks like CoCalc auth page doesn't kick off the https://authenticated?api_key=... call anymore at the end of OAuth authentication (Juno is relying on that call to get CoCalc API key). It does load it when authenticating with the password though. OAuth authentication itself seems to working fine, and I can see GitHub reporting back to CoCalc with the auth code, for instance, same for Twitter etc — but CoCalc doesn't send the API key to Juno afterwards unfortunately. 

Could you please check if there has been any changes recently that could prevent the https://authenticated?api_key=... call from loading in case of OAuth authentication?

**Comment by navoshta** [comment]
Thanks for creating the issue @williamstein — I now started receiving more reports from users failing to authenticate through OAuth. I'm suggesting to setup a password in their CoCalc account preferences for now, and use that to log in.

**Comment by williamstein** [comment]
It actually never worked at all on a skinny screen. Also, it wouldn't work if you enabled "confirm before leaving the page".  So maybe Juno changed to use a skinny screen for sign in or certain people hit that.

**Comment by navoshta** [comment]
Thanks @williamstein, it works perfect now!
