### ISSUE TITLE
ephemeral projects

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3503]
Create a notion of ephemeral projects, which would be a critical foundation for public websites -- no login required -- that actually allow for computation using our massive software stack *and* data and code from a particular project.

This will also involve implementing things in kucalc (our kubernetes backend). But there also needs to be a fully working version of this in cocalc for dev/testing, and some UI thoughts also.

Basically what this should provide is an ephemeral read-only clone of the latest version of a project (or maybe better -- of a publicly shared path), which dies after $n$ minutes, has very constrained usage (both locally and globally across all such ephemeral projects), and there is some API for creating such a thing.  It might also be that resources are less constrained if somebody is willing to pay (with a quota of course, to avoid paying too much).

REQUESTED BY: indirectly, by many people.

**Comment by JavaFXpert** [comment]
This would be a very useful capability, with the most recent and relevant use case from my perspective being the ability to have a headless Python kernel with which ipywidgets, perhaps embedded in a web page, may communicate. This would facilitate developing web-based user interfaces for applications that use Python frameworks.

**Comment by williamstein** [comment]
We could also learn a lot from the recent explosion in so called "serverless" programming, which really should be "functions as a server".  In our case, it would be more of a jupyter kernel as a service, with data.

**Comment by williamstein** [comment]
I think this is still worth doing, they maybe just by better auto deletion of non ephemeral projects...

**Comment by williamstein** [comment]
I'm never doing this...
