### ISSUE TITLE
too many sage servers

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3506]
In my test project (well, it's the newer "experimental" software, but I mention it), I had a sagews tab opened in the background. I was restarting my project rather frequently, and ran tests. Hence I was definitely running a recent version of the project.

Well. In any case. I suddenly noticed that I was no longer able to start a Jupyter Kernel (I guess because everything was slowed down a lot) and that's the process tree. I'm assigning this to william, because I know you did fix a very similar problem a few days ago. 

![2019-01-26-many-sage-server](https://user-images.githubusercontent.com/207405/51790947-14daa900-219c-11e9-92bf-701450f0ccf3.png)

**Comment by haraldschilly** [comment]
Ohh, I see! Glad I made that aspect clear with the screenshot. There was only one sagews editor tab, and it must have happened right after a project restart. I'll watch out if I see this again, maybe I can find a way to reproduce it.

**Comment by haraldschilly** [comment]
just taking note that this happend again

**Comment by williamstein** [comment]
> just taking note that this happend again

Can you post a log file?  So far you've noted it happening like four times, but there's no log files...?

**Comment by haraldschilly** [comment]
In this case, I only saw the processes, but I don't know which project.

**Comment by williamstein** [comment]
fixed via https://github.com/sagemathinc/cocalc/commit/16ff2b0ea675be2b40477a037c271949c4411fb1
