### ISSUE TITLE
webapp session: "error restoring session" → timeout

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3507]
I've changed some code recently, so I should check this. Today I saw there are some tabs missing, and well, the console just tells me there was a timeout "warning" (yellow, not an error). This means wherever it waits for something,the timeout must be increased...

**Comment by haraldschilly** [comment]
Added heisenbug. Refreshed several times, and sometimes it takes a bit longer to load while the network connection indicator is blue and the page (overall) is not responsive. But most of the time it loads really fast. I wasn't able to reproduce the behavior above, though.

**Comment by williamstein** [comment]
> This means wherever it waits for something,the timeout must be increased...

A lot of those unhelpful timeout style error messages are "my fault".  Last week I improved many of them, though many useless ones remain...
