### ISSUE TITLE
jupyter2 → classical: process not halted

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3512]
1. in your settings, you're using cocalc's jupyter
2. open an ipynb file and click in the menu to switch to the classical one
3. the process isn't stopped, while the classical server starts up. i.e. see screenshot...

expected: "switching to classical" terminates the running kernel instance in the same way as the "Halt" button does.

**EDIT** and what about classical → jupyter2 ? I haven't checked, but that's probably an even harder case (one would have to call the "close + halt" method (that's how it is called in the menu) prior to changing the editor)

![screenshot-cocalc com-2019 01 29-12-02-37](https://user-images.githubusercontent.com/207405/51904112-1aafd480-23be-11e9-972c-89371040dff2.png)

**Comment by williamstein** [comment]
I'm closing this.  See https://github.com/sagemathinc/cocalc/issues/7706
