### ISSUE TITLE
f-string auto close quotation marks

### ISSUE THREAD

**Issue by profbrady** [sagemathinc/cocalc#3514]
Since Python implemented f-strings in version 3.6 and CoCalc notebooks can run versions 3.6+, I would like to have auto closing quotation marks and syntax highlighting when using f-strings. Currently typing `f'` does not automatically close the quote like it does for standard strings.

I just realized this happens for `r''` and `u''` representations as well.

**Comment by haraldschilly** [comment]
To me this looks like that issue: https://github.com/codemirror/CodeMirror/issues/2344

**Comment by williamstein** [comment]
I'm labeling this wontfix, since it's upstream in an editor that is not under active development anymore, so nothing is going to happen.
