### ISSUE TITLE
entering text for due date or time for course assignment with unrecognized format fails silently

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3516]
Reported by Larry Langley.

1. Create a .course file and add an assignment.
1. Under Assignments, expand the assignment so that due date is visible.
1. Modify the due date. *Do not use the calendar and clock widgets to the right of the text area.* Edit the text string to make a change and introduce a format error. For example, change the time and delete the space before "AM" or "PM", for example
    `Jan 29, 2019 8:00PM` instead of `Jan 29, 2019 8:00 PM`
1. You may see the due date field revert to its previous value while you are editing. That is one form of the bug, but is hard to reproduce.
1. Click outside the revised Due date. The altered date vanishes and the field appears to be blank.
1. Close the asssignment dialog by clicking the disclosure triangle to the left of the assignment name, and reopen it.
1. Observe that the Due date has not changed from its original value.

**Comment by novoselt** [comment]
I saw the behaviour in 4 and overall the problem is still there, but in reality it does not seem to cause issues. What if somebody enters a wrong date in the correct format? How should we address that?
