### ISSUE TITLE
LaTeX code folding bug

### ISSUE THREAD

**Issue by edemaine** [sagemathinc/cocalc#3522]
Context: `page/misc_page.coffee` registers a CodeMirror fold helper for stex, which you may recall I [use in my project Coauthor](https://github.com/edemaine/coauthor/blob/master/client/codemirror/latex-fold.coffee). 

Bug: I recently noticed some client-side errors in the code, specifically in [these lines](https://github.com/sagemath/cloud/blob/master/page/misc_page.coffee#L508-L534): each instance of `return cm.lastLine()` should be `return [cm.lastLine(), 0]` (I believe).

Essentially need to apply [this commit from Coauthor](https://github.com/edemaine/coauthor/commit/a920aab46d2766a2673edf8547c1bc1f79b511b5).

**Comment by williamstein** [comment]
@edemaine  -- THANKS!  I've made this change to our repo too.

**Comment by edemaine** [comment]
Great! Happy to help.
