### ISSUE TITLE
files: when showing library. check-all at wrong position

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3527]
Uhm, after [c691ee4f38](https://github.com/sagemathinc/cocalc/commit/c691ee4f382db79073195ad3dfff8644da877ae5), when showing the library the check-all box is suddenly above the library. it should be below.

![screenshot-cocalc com-2019 02 01-09-01-55](https://user-images.githubusercontent.com/207405/52110179-1f63cb00-2600-11e9-8096-4dba27f220eb.png)

**Comment by williamstein** [comment]
I disagree -- the current behavior of not moving check all or any other buttons, when showing the library, makes sense to me.

<img width="1523" alt="image" src="https://github.com/user-attachments/assets/99118772-b22c-44b5-9ddf-00fd8fa3c996">
