### ISSUE TITLE
jupyter: implement equation number extension in cocalc jupyter

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3535]
See https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/equation-numbering

REQUESTED BY: Phil Austin

This extension doesn't change or use anything special about the ipynb file or kernel.  I think all it does is slightly change how math typesetting in markdown cells in the notebook is rendered.  That's it.   To make this work in cocalc-jupyter:

- add a new menu option for now that toggles (or resets) the numbering -- probably not a button, since we don't want to have too many buttons and most people may not want this
- actually implement it in the renderer.  HOW?   We use katex mostly instead of mathjax, so we can't do it at all the way this extension does.   Also, we wouldn't want to change global mathjax options.      But I'm sure it can be done...  It'll be a bit harder.  

- Katex does not have equation numbering: https://github.com/KaTeX/KaTeX/issues/350

- It's hard to tell, but is it possible to refer to the equation by some label with the mathjax extension?  I can't tell, but obviously that would be critical... 

- It would be nice to make this something that would work more generally than just in jupyter.  E.g., also have it work in markdown, sagews, etc.

**Comment by williamstein** [comment]
WORKAROUND: Use Jupyter classic and install the extension:

```
pip3 install --user jupyter_contrib_nbextensions

jupyter contrib nbextension install --user

jupyter nbextensions_configurator enable --user

jupyter nbextension enable equation-numbering/main
```
From the little terminal window for that project  seems to have made equation numbering available...

**Comment by haraldschilly** [comment]
I added this example with some context here: https://doc.cocalc.com/howto/jupyter-extension.html

**Comment by williamstein** [comment]
I actually implemented this!  Using label and ref now just work.   This was needed for the Fluid Dynamics course by Eric and Scott...
