### ISSUE TITLE
change courses so that any TA's/instructors must be *explicitly* invited in a panel in Course configuration, *instead* of just adding all project collaborators to all student projects.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3546]
Right now all collaborators on a project containing a .course are added to all student projects associated to that course.   The idea is that TA's and people co-teaching a class are implicitly also the collaborators on the project that contains the .course.   However, sometimes this causes confusion.  E.g., if an instructor mistakenly adds their entire class as collaborators on their project that contains the .course file (and the removes them...).    Instead, these "Ta's and people helping with teaching" should be added in two steps:

1. they must be collaborators on the project, and
2. they must *also* be explicilty added in the course configuration.

**Comment by novoselt** [comment]
It is a somewhat reoccuring issue, but I am skeptical that it will help eliminate confusion, it will replace one type of confusion with another while making the process more complicated ;-) We have added a note that students should not be added as collaborators.
