### ISSUE TITLE
project log: cursor keys scrolling breaks easily

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3549]
**updated bug description:**

up/down keys should scroll the log entries, but clicking once on the log page or clicking on the previous/next page buttons unfocuses and those keys just move the page. This means the listener to keystrokes should listen on the whole log page. Additionally -- stretch goal -- make page up/down keys flip through the log pages.

![screenshot from 2019-02-06 23-37-59](https://user-images.githubusercontent.com/207405/52378567-5145b900-2a68-11e9-952b-aec196cfc4a5.png)

**Comment by williamstein** [comment]
It's a cursor.   Try hitting the up and down arrow keys on your keyboard and you'll understand. You can select any log entry with your keyboard, then hit return to open the corresponding file.

Our file listing page has a very similar behavior with the cursor, except that it looks visually **completely different** and works slightly differently...  That's inconsistent.

In any case, for the log, should we add a little it of grey text somewhere, like "Use cursor keys to select a log entry. If it is opening a file, you can hit return and open that same file."   ?

**Comment by haraldschilly** [comment]
Ahh! That's what I thought, but I tried the cursor keys, but they didn't work. I even speculated if it scrolls via j/k (vim style).

The bug is this: clicking once on the page (e.g. in my case, I can replicate it by clicking on the area on the right hand side of the listing, maybe row 10 or so) the focus is lost and key commands are ignored.

Or even more striking: clicking once on "next page/previous page" removes the focus and keystrokes are ignored as well.

**Comment by williamstein** [comment]
I'm closing this, since those buttons are gone, and I think the behavior isn't that confusing...
