### ISSUE TITLE
allow hiding files generated during latex compilation in Files listing

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3569]
Requested by David Jeschke.

> Also, it would be nice to have an option to see just the files that users created in the Files tab (this should be the default) and not all the .out, .log, .fls, .aux, .fdb_latxmk, synctex.qz, etc.

**Comment by haraldschilly** [comment]
Yes, this is something I would like to have, too. Shouldn't be hard to implement, although I'm not 100% sure how. My first thought would be a toggle button next to the "eye" (for showing linux-hidden files), but maybe a [broom](https://fontawesome.com/icons/broom?style=solid) for "cleaning up"?

**Comment by williamstein** [comment]
Wasn't this done long ago? via this:

<img width="477" alt="image" src="https://github.com/user-attachments/assets/c29c86af-ae86-432f-94c0-4b0ffc932049">

  Also in most cases we generate these files in /tmp now instead.
