### ISSUE TITLE
Add SPARQL Jupyter kernel

### ISSUE THREAD

**Issue by zerline** [sagemathinc/cocalc#3573]
I would like to query data sources in SPARQL. Please consider installing

https://github.com/paulovn/sparql-kernel

Thanks in advance

**Comment by haraldschilly** [comment]
Just the kernel? I think it's best to install it just locally in your project. Besides that I only know very little about SPARQL and well, what's missing is the actual database instance. Which one do you use, how did you set it up in your project, is this something we could think about deploying globally? Or do you query a remove endpoint?

**Comment by zerline** [comment]
Yes, just the kernel would be perfect, as you can query any SPARQL endpoint like (for example http://query.wikidata.org/sparql or any of the endpoints setup by universities and other organizations)

**Comment by haraldschilly** [comment]
I've added the kernel and [here is a demo I ran on cocalc](https://share.cocalc.com/share/90f8367cb17c65281567edcc3922c03741151a7c/sparql-vanGogh.ipynb?viewer=share)

It's currently in the "experimental" software environment (in the project settings, you can switch). ... and that will be the "default" soon. Hence I'm closing this ticket.

**Comment by zerline** [comment]
Great thank you!
My own example (with _Wikidata_ endpoint) is [here](https://cocalc.com/projects/97c5b94c-a9e3-48a7-98c6-be9f324a2b8d/files/women_scientists.ipynb)
