### ISSUE TITLE
weird safari error: promiseReactionJob pointing to source code (?)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3576]
This affects Safari **only** (also Safari/604.* variants)

safari: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15`

smc_git_rev: 3ea97e67f0d86c843add1b321d7be68adffb1e6d

Date: 2019-02-13 16:05:07.219866

`{"0":{"line":5,"column":2052136,"sourceURL":"https://cocalc.com/static/smc-e1738c1e0eea31cfaf1f.cacheme.js?e1738c1e0eea31cfaf1f"}}`

```
<generated>
s@https://cocalc.com/static/smc-e1738c1e0eea31cfaf1f.cacheme.js?e1738c1e0eea31cfaf1f:5:682798
m@https://cocalc.com/static/smc-e1738c1e0eea31cfaf1f.cacheme.js?e1738c1e0eea31cfaf1f:5:685435
https://cocalc.com/static/smc-e1738c1e0eea31cfaf1f.cacheme.js?e1738c1e0eea31cfaf1f:5:685516
oe@https://cocalc.com/static/smc-e1738c1e0eea31cfaf1f.cacheme.js?e1738c1e0eea31cfaf1f:5:2279
promiseReactionJob@[native code]
```

---

```
get_file_use_map=function(){
return null==this._cache&&this._update_cache(),null!=this._cache?
this._cache.file_use_map:void 0},
t.prototype._update_cache=function(){
var e,t,r,a,s=this,c=this.get("file_use");
if(null!=c&&(this._cache_init||(
this._initialize_cache(),    <<<<<<<<<<<<<<<<<<<<<
this._cache_init))&&null==this._cache){null==this._account_id&
```

**Comment by haraldschilly** [comment]
ok, I finally figured out how to trigger this on browserstack and see the JS console in safari 12 :roll_eyes: 

seems to be no huge drama

![screenshot from 2019-02-13 17-17-57](https://user-images.githubusercontent.com/207405/52726376-61532080-2fb3-11e9-959b-cf6fd0c23f6b.png)

**Comment by williamstein** [comment]
I noticed this and fixed it already...
