### ISSUE TITLE
separate cocalc's realtime sync out as a standalone library that can be used by other projects

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3582]
- This is mainly the code in `src/smc-util/sync`.
- The license would be something that is very liberal (e.g., MIT?)
- The motivation is to help ensure that the quality of realtime sync is very high, that there are no bugs, and to generally improve and give back to the open source ecosystem.

@rgbkrk

**Comment by rgbkrk** [comment]
> The license would be something that is very liberal (e.g., MIT?)

BSD-3-Clause would be great, if only to make the Jupyter folks not have too much consternation. (that's what the rest of the project uses)

> The motivation is to help ensure that the quality of realtime sync is very high, that there are no bugs, and to generally improve and give back to the open source ecosystem.

💯 

As outlined on our video call, the likely start to the project is:

* increasing code coverage for tests (likely beyond line coverage 
* providing documentation, both in API form and as narrative usages

Would you want to host this repo within `sagemathinc`, a new org, or as part of `nteract`?

**Comment by rgbkrk** [comment]
Additional areas that will be needed to be extracted (editing this list as I go along):

* `smc-util/dmp` -- the internal fork of [diffmatchpatch](https://github.com/google/diff-match-patch)
* `cmp_array` from `smc-util/misc` (looking at where its used in `editor/generic/util.ts`, could probably just get re-written)
* Portions of `smc-util/schema`
* `cmp_Date, endswith, filename_extension, keys` from `smc-util/misc`

**Comment by rgbkrk** [comment]
cc @captainsafia

**Comment by rgbkrk** [comment]
@williamstein -- would you welcome me submitting a typescript version of `diffmatchpatch`?

I noticed it fairly closely matches [upstream's uncompressed js](https://github.com/google/diff-match-patch/blob/master/javascript/diff_match_patch_uncompressed.js) pretty closely. Are there unique patches from you to be aware of, or is it a separate file because google doesn't publish the package reliably on npm?

On a similar note, there are typings on DefinitelyTyped for diffmatchpatch -- I could incorporate those.

**Comment by rgbkrk** [comment]
Went ahead and posted an issue in the google repo about converting to typescript in upstream -- https://github.com/google/diff-match-patch/issues/58

**Comment by rgbkrk** [comment]
Have you run into this issue? https://github.com/google/diff-match-patch/issues/39

**Comment by williamstein** [comment]
> BSD-3-Clause would be great, if only to make the Jupyter folks not have too much consternation. (that's what the rest of the project uses)

Whatever is most compatible with Jupyter is fine with me for the sync library.

**Comment by williamstein** [comment]
> Have you run into this issue? [google/diff-match-patch#39](https://github.com/google/diff-match-patch/issues/39)

Yes, I ran into it and worked around it [right here](https://github.com/sagemathinc/cocalc/blob/master/src/smc-util/sync/editor/generic/util.ts#L18)

**Comment by williamstein** [comment]
> I noticed it fairly closely matches [upstream's uncompressed js](https://github.com/google/diff-match-patch/blob/master/javascript/diff_match_patch_uncompressed.js) pretty closely.

It is now **identical**, except for prettier formatting.   Switching to upstream + npm is the way to go.


> ... sagemathinc ... 

Let's do it there.  I can make you part of our org (we have a paid slot left).

**Comment by williamstein** [comment]
New repo: https://github.com/sagemathinc/sync

**Comment by williamstein** [comment]
Heh, I actually did this already:   https://www.npmjs.com/package/@cocalc/sync

It's not a separate git repo, but it is a separate library.   It probably won't get used by anybody else until:
1. The dependence on other @cocalc/* libraries is reduced,
2. The license is changed to something like MIT.
3. There are some small examples (e.g., a chat server) to illustrate how to use it.

**Comment by rgbkrk** [comment]
Woo!
