### ISSUE TITLE
upgrade xterm.js

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3605]
Right now xterm.js is hard coded to stay at an old version forever.  Change it to upgrade again once

https://github.com/xtermjs/xterm.js/issues/1932

is addressed properly in a release.

Note that we no longer get the "text reflow" feature due to this downgrade.  People who need that will have to use tmux or screen, which reflow automatically.

**Comment by slel** [comment]
The upstream ticket asks for a way to reproduce the issue, do you have one?

**Comment by williamstein** [comment]
> The upstream ticket asks for a way to reproduce the issue, do you have one?

It happens randomly and consistently, I think when resizing the terminal.  It certainly happens enough to be VERY annoying (e.g., your terminal suddenly just hangs), but not so much to be easy to reproduce.

**Comment by slel** [comment]
It seems xterm.js is now kept up to date in CoCalc, see https://github.com/sagemathinc/cocalc/issues/4921#issuecomment-705545054

So this can be closed.
