### ISSUE TITLE
sagetex errors should also be shown in the margin

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3609]
I just noticed that if you're using sagetex with latex and there are errors, they are nicely displayed in the build log, but NOT in the margin of the codemirror editor.  They should also be shown there.  Users think they compiled their doc with no errors, but there were errors, so this is confusing and unexpected, hence a bug.

REPORTED BY: Gerardo Zelaya

**Comment by haraldschilly** [comment]
this is fixed. there was even a follow-up fix to bubble-up actual errors of such processing tools like sagetex on top of the other error status messages. that way, such problems are more visible. it's not possible to show these messages in the margin, though. there is no reconciliation information. This could be another "upstream" ticket, hence I created https://github.com/sagemathinc/cocalc/issues/4684
