### ISSUE TITLE
make copy between projects robust against modified .bashrc files

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3644]
Starting a `.bashrc` with `exec zsh` breaks copy operations. This was observed in kucalc, but it is probably a general problem. The primary focus is to fix this in kucalc, though.

**Comment by williamstein** [comment]
> Starting a .bashrc with exec zsh breaks copy operations. 
  
What does this even mean?  

There's always going to be infinitely many ways to break copying between projects, so long as the project having to run at all is happening...

I'm closing this, but with wontfix, since there are much more important issues.
