### ISSUE TITLE
project settings may report "NaN MB dedicated RAM"

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3656]
In project settings, I have projects open that show NAN and one that shows 0 for amount of Dedicated RAM. Refreshing browser changes NaN to 0. I don't know how to trigger the NaN display, other than (possibly) returning to browser window for project that has been open for a few hours.

![nanmbdedicated](https://user-images.githubusercontent.com/528072/53822041-8abcf780-3f34-11e9-8b0b-1e0176d0fd1a.png)

**Comment by DrXyzzy** [comment]
After refreshing browser and confirming that dedicated RAM shows as 0 MB, wait 30 seconds with project settings tab open. The value displayed reverts to **NaN MB** without further user action.

**Comment by williamstein** [comment]
Reopening -- it seems this fixes *causing* the problem, maybe, but doens't fix.

**Comment by williamstein** [comment]
I noticed another problem, which is that if you click "Admin edit", then change Dedicated RAM, it sometimes does not make the Save button get enabled.

**Comment by williamstein** [comment]
vague, old, and not reported again in years.
