### ISSUE TITLE
intermittent loss of syntax highlighting with jupyter notebook & ubuntu python 3

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3657]
Reported by Daniel Abrams.

Jupyter notebook with Python 3 (Ubuntu Linux) kernel occasionally fails to display code with syntax highlighting. Customer reports seeing it 1/8 of the time while grading assignments. 

I (Hal) haven't been able to replicate it, so far.

**Comment by williamstein** [comment]
I have seen this sometimes, and despite it being random and hard to reproduce, I bet I can fix it anyways (by studying the code).

**Comment by norru** [comment]
Just seen this in Julia.

**Comment by williamstein** [comment]
I've raised the priority.  Any details about how/when you saw it?

**Comment by williamstein** [comment]
Fixed via #3890
