### ISSUE TITLE
sagews: indented blocks are silently ignored

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3658]
I'm not sure what exactly is going on, but running

```
x = 1
    y = 2
```
 or  (with or without a blank line)
```
print 'x'

    print 'y'
    x = 3
```
causes only the first line to run and the ones below are ignored. I don't know if this is intentional or not. I think it's confusing, because code appears to do nothing.

**Comment by williamstein** [comment]
Not the case now:

<img width="944" alt="image" src="https://github.com/user-attachments/assets/86eca8c9-18f0-4f6c-9e65-0989ceea1167">
