### ISSUE TITLE
plot is not displayed in copy of jupyter notebook

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3660]
Reported by Prof. Brady.

1. Start a CoCalc Jupyter notebook `n1.ipynb` with kernel "Python 3 (Ubuntu Linux)"
1. Add a code cell and execute:
    ```
    import matplotlib.pyplot as plt
    import numpy as np
    x=np.arange(0,3*np.pi,0.1)
    y=np.sin(x)
    plt.plot(x,y)
    ```
1. Copy the notebook to a new file, e.g. `cp n1.ipynb n2.ipynb`.
1. Open the new notebook n2. You will see a blue button, "Fetch additional output...".
    <img width="447" alt="screen shot 2019-03-06 at 2 33 41 pm" src="https://user-images.githubusercontent.com/528072/53912112-d3041480-401d-11e9-84fe-faa1ea8cdcd1.png">
1. Clicking the button produces a broken image graphic and the blue button is still there.
    <img width="735" alt="screen shot 2019-03-06 at 2 33 49 pm" src="https://user-images.githubusercontent.com/528072/53912136-e3b48a80-401d-11e9-9437-7df9fc71c576.png">

The copy and the original notebook both (of course) contain the output plot as an image/png object.

A workaround is to execute the copy, but this can be a problem when grading collected homework that consists of copied notebooks, especially when several cells of the notebook pause for manual input.

**Comment by williamstein** [comment]
1. Between steps 2 and 3, did you click "Save" and wait for the green button to dim?  Just curious.    I still want this to work in any case, and consider this a valid bug.

2. Is this ONLY a problem when the "Fetch additional output" button appears?  I.e., what about smaller plots?

**Comment by DrXyzzy** [comment]
@ws:

1. Clicking Save in the original notebook and waiting for green button to dim before copying does not change the behavior.
2. The original plot in the example above is small enough that the "Fetch additional output" button does not appear. The blue button only appears when opening the copy.
3. Making the plot very small causes no button to appear in the copy, just the broken image:

    original notebook:

    <img width="376" alt="screen shot 2019-03-06 at 4 30 12 pm" src="https://user-images.githubusercontent.com/528072/53918681-3e091780-402d-11e9-9be7-d10e5ea5920d.png">

    copy:

    <img width="414" alt="screen shot 2019-03-06 at 4 30 31 pm" src="https://user-images.githubusercontent.com/528072/53918712-5416d800-402d-11e9-9237-cd134290b5d9.png">

**Comment by williamstein** [comment]
What if you copy only the ipynb file using the `cp` command line tool, and not the underlying sync file.  It seems like you're saying that every possible use of embedded images in **ipynb files** is completely broken, which is surprising, since that would also break them in the share server in all cases.

**Comment by DrXyzzy** [comment]
I have been doing the copy using `cp`  in a .term, applied only to the .ipynb file.

In other tests, I manually copied the `.sage-jupyter2` file as well. And I tried the GUI with "Duplicate" or "Copy". Same result every time.

**Comment by DrXyzzy** [comment]
There is a difference between original and copy in object view.

The output of the compute cell looks like this in the original:

<img width="551" alt="screen shot 2019-03-06 at 4 57 17 pm" src="https://user-images.githubusercontent.com/528072/53919957-2764bf80-4031-11e9-8d59-ce840f1d46ba.png">


And it looks like this in the copy:

<img width="591" alt="screen shot 2019-03-06 at 4 58 32 pm" src="https://user-images.githubusercontent.com/528072/53919962-2df33700-4031-11e9-9119-95a07613c67a.png">

**Comment by williamstein** [comment]
Got it.  This is a really weird/serious/new bug.  Interestingly, the ipynb file is just fine, in that if you open it using jupyter classic you get the file.  So there is something genuinely new and kind of unrelated to the old bug (though with similar symptoms).

I wish I had the time to fix this...  Thanks for at least reproducing it clearly.

**Comment by williamstein** [comment]
This should now be fixed!!

**Comment by williamstein** [comment]
(Project restart required)
