### ISSUE TITLE
some obvious bugs with @mentions

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3662]
1. (minor) On mobile it doesn't work at all.  It's totally disabled.  At least on Pixel 2xl.  However, the hint text still tells you to use @.  (Either make it work, or remove the hint text on mobile.)
  
2. (**major**) If the number of collaborators is at all large (more than 4) then, they all scroll off the bottom of the screen and there is no way to even see them!  Since most people will use this in courses, etc., where they could easily have many collabs (all the TA's), this could be a major problem. 

![image](https://user-images.githubusercontent.com/1276278/53935116-0ebccf80-405a-11e9-8a16-66b2becb5b16.png)

(I can't scroll down to see the last few entries making this super frustrating...)

3. What is the order of the names in the list?  Totally random?

**Comment by haraldschilly** [comment]
IMHO the owner of the project should be on top and highlighted.

**Comment by williamstein** [comment]
I'm going to close this because: 
- bug (2) is now completely fixed,
- bug (1) is actually probably impossible to fix on mobile, and I'm wrong -- if you type `@[some letter]` then it works.  Probably due to how mobile browser input works, there is no way to do anything in general after the first @.
- bug (3) isn't so bad, since if you start typing the search name it works.  Github doesn't offer much help here, since it seems to give me a mysterious list of like 4 random options, then when I type some more text new options appear out of nowhere.  Weird.

**Comment by johnjeng** [comment]
Major issue fixed. Minor issue doesn't seem to be a problem anymore.
