### ISSUE TITLE
VS Code server - support it in the same way we support Jupyter Classic and JupyterLab?

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3671]
See https://github.com/codercom/code-server

We could have this pre-installed in cocalc, and make launching it a one-click in +New, just like with JupyterLab.  Should we?  Any reason not to?

**Comment by haraldschilly** [comment]
We don't have websocket proxy forwarding (which is also a blocker for some other webapps). In its code, I found  it  creates the websocket for `location.host`, see https://github.com/codercom/code-server/blob/96175d36eaa49a032c252b6c1dba4860ad057890/packages/ide/src/fill/client.ts#L95

Maybe I'm reading this wrong, or there is also some other code to configure this, but this could be a blocker.

**Comment by williamstein** [comment]
What is "websocket proxy forwarding"?

**Comment by haraldschilly** [comment]
I don't know how to describe this. There needs to be a proxy server to properly forward the websocket connection.

**Comment by williamstein** [comment]
Um, we have had that forever - it is used eg by jupyter.  So maybe you mean something else?

**Comment by haraldschilly** [comment]
One example I remember is the dashboard for a dask distributed computing cluster. Everything loads, except for the websocket.

**Comment by haraldschilly** [comment]
Well, it works for jupyter, but not for that dask dashboard. Maybe we should just test it here? I haven't figured out why exactly it doesn't work for that dashboard.

**Comment by williamstein** [comment]
Maybe the issue is "base_url" support.   E.g., that's something that Jupyter has excellent support for.

**Comment by likulogy** [comment]
I second this enhancement! While I relying all "code" related activities on remote server, powerful IDE support will be great feature <3

**Comment by rholland** [comment]
I would really like to see this.

**Comment by williamstein** [comment]
Now done!  See https://github.com/sagemathinc/cocalc/issues/4479
