### ISSUE TITLE
when mentioned, email the whole chat message

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3692]
I get emails which are kind of repetitive and have low information content.

The message itself should contain the chat message (mentions are sent when the message is submitted, so we know the full content at that point). I should probably make a test to see how this looks, but some minimal html could be enough and we should be fine -- html-emails aren't full html! `<div style="font-size: 14px;  font-style: italic;  padding: 10px;   border: 1px solid gray;  color: #444;> message </div>`

additionally, the subject could be more unique, I would suggest to add the time. i.e. `[ ... ] <filename> @ <short iso timestamp>`.

**Comment by williamstein** [comment]
@haraldschilly do you still think we should do this, after having used what we have now for 4 users?
