### ISSUE TITLE
jupyter2: support "from x import _" tab completion (more precisely -- align our completion heuristic with JupyterLab's)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3714]
This is a special case for "tab-completion". In classical, type in `from sys import ` ← i.e. just one or more space  chars after `import`, no other character or anything else! Then press the tab-key:

![Screenshot from 2019-03-27 14-31-42](https://user-images.githubusercontent.com/207405/55079784-2f96a480-509d-11e9-974a-f08a2608f3df.png)

In CoCalc's Jupyter, it isn't aware of "import" and inserts a few tab-space  chars. I'm not sure what exactly the heuristic is, though.

---

what's working is `from sys import  v` + TAB, for `version*`

**Comment by williamstein** [comment]
Changing to a bug, since if jupyter-classic has "basic functionality" and cocalc-jupyter doesn't, it's a bug.

**Comment by williamstein** [comment]
Still not implemented, and indeed it would be good to do so.  We'll need to look in the source code of JupyterLab to see what the later heuristic is for doing a completion versus tab, and switch to that.

<img width="595" alt="image" src="https://github.com/user-attachments/assets/9e924d45-3f45-41e5-9d47-f4a4cf2d271e">

Also, as you can see JupyterLab puts some extra info about statement or function, which would should add too, maybe.

**Comment by williamstein** [comment]
Note -- the kernel is what returns the actual completions, so the only work for us is deciding *when* to request them, versus when to just send spaces/tabs.
