### ISSUE TITLE
make the autosuggested name be valid for the given language

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3715]
See this:

![Screenshot 2019-03-28 at 8 23 13 AM](https://user-images.githubusercontent.com/1276278/55169891-d0836f00-5132-11e9-8074-8f0eb003fa76.png)

However, -'s in a .py file are BAD, since you can't import the file.  Underscores and starting with a letter would be better for python, etc. etc.,

**Comment by haraldschilly** [comment]
fixed in https://github.com/sagemathinc/cocalc/pull/3729 in the `NewFilenames` class in project/utils
