### ISSUE TITLE
frame editor toolbar buttons relocate badly on resize with safari

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3718]
Seen on macOS 10.14.3 with Safari 12.0.3 (14606.4.5). Also seen on iPad Pro with both Chrome and Safari with iOS 12.1.4.

1. Open an .md file with focus in edit pane and set browser width so that full edit toolbar is visible. (You could also open a .py file and see the same thing.)

    <img width="689" alt="md-bug-1" src="https://user-images.githubusercontent.com/528072/55176570-5c0af900-514f-11e9-8f59-2e74eadb7c5a.png">

1. Shrink browser window horizontally until the first block of 3 buttons (search, replace, go to line) are removed from the edit toolbar. Instead of vanishing, as they do with Chrome and Firefox on macOS, the buttons jump down and obscure part of the edit pane.

    <img width="594" alt="md-bug-2" src="https://user-images.githubusercontent.com/528072/55176595-66c58e00-514f-11e9-874d-5cc3175c38c8.png">

1. Shrink horizontally again until the next 3 buttons (cut, copy, paste) also jump down.

    <img width="561" alt="md-bug-3" src="https://user-images.githubusercontent.com/528072/55176628-7ba22180-514f-11e9-8560-056d18b8a964.png">

1. As you continue to shrink the browser window horizontally, more buttons jump into the edit pane and shift down into multiple rows.

    <img width="305" alt="md-bug-4" src="https://user-images.githubusercontent.com/528072/55176650-852b8980-514f-11e9-96ae-4e9cdfdc95fe.png">

**Comment by williamstein** [comment]
This is no longer an issue in Safari Version 14.0.2 .   I think @haraldschilly fixed this already.
