### ISSUE TITLE
Increase limits on memory and CPU upgrades that can be applied to a project

### ISSUE THREAD

**Issue by brianfields** [sagemathinc/cocalc#3720]
For context:

We are expanding the number of students that can be in our classroom from 20 to 200 (we'll go to 400 later). We use breakouts frequently as part of our approach. If there are four students per breakout group, the number of groups grows from 5 to 50.

(A likely activity would be to create a pre-populated CoCalc worksheet with tasks for the students to accomplish in the 50 breakout groups. The class is scheduled to start this summer.)

We have a technical issue when increasing the number of breakout groups. In our current implementation, all the CoCalc worksheets for all of the breakout groups are in the same project. The means they all share the same upgrades. This has been ok with 5 breakout groups, but 50... The 8 GB limit on memory upgrades is probably going to be insufficient. We'd love if we could just allocate more memory to a project. That way, we maintain the advantage of having one project per section of a course, where a student can find all their worksheets for the course. Is this possible or is there a hard limit on your end?

From William:

It is definitely not a hard limit on our end -- we could in theory have projects that use up to 1TB, since Google Compute Engine has large memory machines.   This is something that is basically just a matter of money.

**Comment by haraldschilly** [comment]
Hi @brianfields … is this ticket still valid? I think the actual issue was scaling up the number of simultaneous users per project and not so much memory usage. It's more than a year, so, my memory might be wrong.

**Comment by brianfields** [comment]
😍
