### ISSUE TITLE
spaces in filename break jupyter notebook pdf conversion

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3722]
Reported by Alvin Ong.

1. Upload or create an ipynb file with images, for example [here](https://share.cocalc.com/share/618508ec-6aad-4269-867d-062df6963ef8/SageManifolds/Worksheets/v1.3/SM_Euclidean_plane.ipynb).
1. Rename the file to "a b c.ipynb" and open in CoCalc.
1. Select file-> download as -> pdf via LaTeX.
1. Open the pdf file and notice that it is truncated before images would appear in the file.

This seems due to upstream jupyter/nbconvert#633

**Comment by williamstein** [comment]
> This seems due to upstream jupyter/nbconvert#633

Yes, though we could still workaround the bug using a temporary file...

**Comment by williamstein** [comment]
(We can also put a line in our dialog to warn our users.)

**Comment by MSeal** [comment]
This should be fixed with nbconvert 5.5 here in a wekk or so fyi -- I've got a fixed PR'd at https://github.com/jupyter/nbconvert/pull/986

**Comment by haraldschilly** [comment]
@MSeal cool, thank's for letting us know!

**Comment by williamstein** [comment]
Works fine now.  
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/32eb8230-5bd0-4fdd-bcaa-07b4c670d25f">
