### ISSUE TITLE
Keyboard Shortcuts for sagews

### ISSUE THREAD

**Issue by jpedroan** [sagemathinc/cocalc#373]
- A button for "Keyboard shortcuts" could be visible inside the (i) button at left.

**Comment by williamstein** [comment]
This should NOT go in the (i) button, since that's "file actions".  However, having such info is important.  It should really be accessible via the help button, somehow.

**Comment by kcrisman** [comment]
In the mean time the help button does have a keyboard shortcut link.  However, the link is to a separate web page rather than to an overlay that can be Esc-ed away.

**Comment by williamstein** [comment]
Not going to fix this, due to deprecation, and decision to merge this with jupyter support.
