### ISSUE TITLE
weaken our security model to make course administration more robust

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3730]
The following is how things work now:

1. Create a project "Teaching Project"
2. Create a .course in that project
3. Add a student to the course, which creates another project called "Student Project".
4. Close the .course project
5. Add a second user "My TA" as collab to "Teacher Project".
6. Observe that "My TA" is NOT a collaborator on "Student Project".
7. Open the .course project.
8. Observe that now "My TA" is a collab on "Student project".

We store in the database the fact that "Student project" was created by "Teacher project".  We should probably (?) change our security model so that all collabs on Teacher project are *automatically* collabs on corresponding student projects, without this needing to be done manually in step 7, which introduces confusion in some cases.

**Comment by DrXyzzy** [comment]
To illustrate the confusion that is possible, if "My TA" tries to apply upgrades to student project(s) from his/her account at step 6 (call this step "6b") via the Configuration tab of the .course file in "Teacher Project", the screen will display a spinner and "Adjusting upgrades on 20 student projects...", then remove the message. But no upgrades are applied and no error message is displayed.

When the owner of "Teacher Project" opens the .course *file* in step 7, "My TA" is instantly added as collaborator on "Student project". When I tested Steps 1-8 above, the browser session with "My TA" logged in was not able to apply a student upgrade after step 8 above until refreshing the browser.
