### ISSUE TITLE
only include students who did the homework in peer grading

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3737]
REQUEST: "I have an assignment that I would like to have peer reviewed. Unfortunately, not all students complete their assignments. I would like to assign the peer grading only to those who completed the assignment."

REQUESTED BY: Fanny Shum

---

comments: We need a way to define whether or not a student "completed an assignment", which we currently don't have.  That's probably by far the hardest part of this issue.

**Comment by novoselt** [comment]
One can also be concerned about "not really completed anyway" when some kind of automatic check is OK. I suspect it is too much effort to implement well and not much demand.

**Comment by williamstein** [comment]
I don't know if anybody ever uses peer grading anyways...
