### ISSUE TITLE
owner cannot delete project while collaborator views it in project list

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3739]
This setup uses two browser windows, signed in as users Owner and Collaborator C1.

1. In browser window A, sign in as Owner and open settings for project P owned by Owner. Add  Collaborators C1 and C2. You will not sign in as C2, but a second collaborator is needed for the bug to appear.
1. In browser window B, sign in as C1 and bring up P in the project list.
1. In window A (settings for P), click "Delete Project" and "Yes, please delete this project". Observe the red "Warning: this project is deleted!" banner at the top of the settings window.
1. In window B, observe that P is still in the (undeleted) project list for C1.
1. Refresh window A and observe that the red "deleted" banner is no longer in project settings for P.

**Comment by DrXyzzy** [comment]
Possibly significant: I've only tested this setup where Owner, C1, and C2 are all NOT admins.

**Comment by williamstein** [comment]
This is way too vague.
