### ISSUE TITLE
Support for base_url in on-premise docker image.

### ISSUE THREAD

**Issue by likulogy** [sagemathinc/cocalc#3740]
When the cocalc docker container comprised with custom domain, some links and text still displayed 'cocalc.com' strings.

In example, ssh keys and cocalc webservice url. 

![ssh keys](https://user-images.githubusercontent.com/10000685/55670043-4c5f8300-58ba-11e9-8441-7eac0ec5bdc2.PNG)
![webservice](https://user-images.githubusercontent.com/10000685/55670044-4c5f8300-58ba-11e9-8f80-0a535b7a6aa0.PNG)

If possible, it is really great when base url setting through admin panel support comes true!

**Comment by haraldschilly** [comment]
Hmm, I'm not sure what to make of this ticket any more. There is much more customized and the domain and site name is used in many places.

Ad example 1: the SSH panel shouldn't be there at all. (admin → site settings → kucalc ui → "no")

Ad example 2: this looks like the domain is in the `main.py` python file? What exactly is its content?!

In any case, I'm happy to work on further customization, but please just one detail per issue and complete context.
