### ISSUE TITLE
CPU and Memory Usage Tooltip Popovers Obscure Each Other

### ISSUE THREAD

**Issue by rljacobson** [sagemathinc/cocalc#3743]
The popovers for the CPU and Memory Usage exhibit strange behavior, including the "Kernel CPU and Memory Usage" obscuring the "CPU % | Memory: " box. I have attached a screenshot of this last behavior:
<img width="469" alt="thumbnail_Screen Shot 2019-04-02 at 12 17 36 PM" src="https://user-images.githubusercontent.com/1412598/55689721-06f09380-5956-11e9-903a-54afb10b0113.png">

This screenshot doesn't capture all of the weirdness, so I did a screen recording (unlisted):
https://www.youtube.com/watch?v=R6uAuUGebGo&feature=youtu.be

Chrome: Version 73.0.3683.86 (Official Build) (64-bit)
27" iMac, hi dpi.

**Comment by williamstein** [comment]
long gone...
