### ISSUE TITLE
new projects are created showing 2 Shared CPU cores

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3748]
Reported by Oliver Braunling.

1. Create a new project.
1. Open project settings for the new project. Observe under "Project usage and quotas" that Shared CPU reports "2 cores, 1 core given by free project".

    <img width="506" alt="two-cores" src="https://user-images.githubusercontent.com/528072/55925757-357ba200-5bd4-11e9-82f9-0a40304324e0.png">
 
1. If you have upgrades available, click "Adjust your quota contributions" and observe that Shared CPU shows "Shared CPU (current: 2 cores, max allowed: 2 cores)". 
1. Note that typing a "1" into the form for Shared CPU cores results in an error, "Value too high: exceeding limit".

    <img width="431" alt="value-too-high" src="https://user-images.githubusercontent.com/528072/55925785-5643f780-5bd4-11e9-93ce-624c62618eb8.png">

1. The problem is persistent across browser refresh, project restart, and account sign out & back in.
1. If a quota adjustment is made, for example adding an hour of idle time, the Shared CPU count drops to 1.
1. I don't know if there is a way to clear the phantom allocation for users who have no upgrades.

**Comment by haraldschilly** [comment]
ah, that's still there, I first wrote about this in our `2019-03-21.sage-chat`.

**Comment by williamstein** [comment]
It's much, MUCH worse than reported above.   The disk space and shared ram are also misreported [for me](https://cocalc.com/projects/2acb68e0-f6c4-4582-8fe2-2460da48d7c0)!

![Screenshot 2019-06-12 at 6 12 34 AM](https://user-images.githubusercontent.com/1276278/59354369-d91f2680-8cd9-11e9-8a3d-99fa8a9b7c42.png)
