### ISSUE TITLE
latex hyperref link boxes in pdf preview are off

### ISSUE THREAD

**Issue by tscholl2** [sagemathinc/cocalc#3750]
The boxes that highlight links/urls when using the hyperref package do not get updated when the source gets recompiled.

Steps to reproduce:
1.
![image](https://user-images.githubusercontent.com/8905985/56003498-7f6b9300-5c7b-11e9-80d8-c132e19caa82.png)

2.
![image](https://user-images.githubusercontent.com/8905985/56003514-8c888200-5c7b-11e9-9ba6-2a5c66e2d3cc.png)

The box around "a" did not move after it recompiled and displayed the new preview. So the box is showing up on "b" but it should be on "a".

**Comment by williamstein** [comment]
Probably also reported by Heinz Bauschke.

**Comment by crockeea** [comment]
This is extremely annoying.

**Comment by williamstein** [comment]
> This is extremely annoying. Would love to get this fixed.

Coincidentally, I started working on this bug 30 minutes ago!

**Comment by williamstein** [comment]
@crockeea -- it took about 4 hours total, but I fixed this and also upgraded everything to the latest version of pdfjs, which had a massive amount of API changes.  I also found and fixed another edge case where clicking wouldn't quite scroll the right part of the document into view.

Oh, and I fully implemented support for multifile latex documents (that took over a week of work). 

This should all be live hopefully later today.

**Comment by crockeea** [comment]
Thanks for implementing these two fixes. They will dramatically improve the TeX-writing experience in CoCalc! Is this feature in the docker images yet? If not, when can I expect that?

**Comment by williamstein** [comment]
Not yet.  The socker image is updated weekly...

**Comment by DrXyzzy** [comment]
@crockeea - the agpl image has been updated for multi-file LaTeX. If all goes well, the no-agpl image will be published within a few hours.

**Comment by DrXyzzy** [comment]
@crockeea , the [no-agpl image at dockerhub](https://hub.docker.com/r/sagemathinc/cocalc-no-agpl) has been updated for multi-file LaTeX now.
