### ISSUE TITLE
jupyter2: sympy formulas ("rendered output"?) is too tight

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3752]
see screenshot below. there is almost no spacing around the output (looks off compared to normal text output) and a pointless scrollbar on the right hand side shows up. something must be a bit off with margins and padding...

![cocalc-jupyter2-formulas-too-tight](https://user-images.githubusercontent.com/207405/56081722-b8893c00-5e10-11e9-8c37-5116ad0a45b5.png)

**Comment by williamstein** [comment]
I wish I could copy/paste something to reproduce this...

**Comment by williamstein** [comment]
```
from sympy import symbols, diff, sin, exp
x, y = symbols('x,y')
f = (x+y**2+1)/(sin(x)+exp(-x)); f
```

and

```
diff(f,x)
```

**Comment by haraldschilly** [comment]
It's any sympy formula output

```
from sympy import symbols, sin, cos, exp, diff, limit
x, y = symbols('x, y')
ex = (x + y**2 + 1) / (sin(x) + cos(-x))
ex
```
```
limit(limit(ex, x, 1), y, 0).n(123)
```
```
ex2 = diff(ex, x, 3)
ex2.expand().simplify()
```

**Comment by williamstein** [comment]
`x/y` is particularly bad since the top is cut off:

![image](https://user-images.githubusercontent.com/1276278/92633392-9145d100-f287-11ea-9955-ea4479772279.png)

**Comment by haraldschilly** [comment]
yes, and the scrollbars
