### ISSUE TITLE
output cell jumps back to left margin after scrolling right in sagews with python 3 bridge

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3758]
Seen with Firefox 66.0.3 and Chrome 73.0.3683.103 (Official Build) (64-bit) on macOS 10.14.3.

1. Open a sagews file.
1. Enter the following cells:
    ```
    %default_mode python3
    --- new cell ---
    import pandas as pd
    cols = ['date_creat', 'time_creat', 'created_us', 'idpct', 'idpct_txt',
           'date_last_', 'time_last_', 'last_edite', 'name', 'name_tmp', 'num',
           'shape_area', 'shape_len', 'town_no', 'geometry']
    data = {c:['xyz'] for c in cols}
    df = pd.DataFrame(data=data)
    df
    ```
1. Observe that the output is displayed as a table too wide for the browser window and a horizontal scrollbar appears under the table.
1. Scroll to the right to see the rightmost column and wait a few seconds.
1. Observe that the output jumps back to showing the leftmost column of the table.

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.
