### ISSUE TITLE
no new data in file_access_log

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3770]
There is a problem with recording entries in `file_access_log`. Querying for the most recent entries via `select * from file_access_log order by time desc limit 100;` gives only entries for one project and one user account. active yesterday and 3 days ago. That's weird.

Doing some detective work, here is the number of unique account IDs per day:

```
select count(distinct(account_id)), date_trunc('day', time) AS d from file_access_log  where time >= '2019-01-01'::TIMESTAMP group by d order by d;

count |          d          
-------+---------------------
   859 | 2018-12-24 00:00:00
   694 | 2018-12-25 00:00:00
   829 | 2018-12-26 00:00:00
   952 | 2018-12-27 00:00:00
   877 | 2018-12-28 00:00:00
   801 | 2018-12-29 00:00:00
   789 | 2018-12-30 00:00:00
   787 | 2018-12-31 00:00:00
   656 | 2019-01-01 00:00:00
  1010 | 2019-01-02 00:00:00
  1171 | 2019-01-03 00:00:00
  1131 | 2019-01-04 00:00:00
   951 | 2019-01-05 00:00:00
  1016 | 2019-01-06 00:00:00
  1432 | 2019-01-07 00:00:00
  1980 | 2019-01-08 00:00:00
  2232 | 2019-01-09 00:00:00
  2458 | 2019-01-10 00:00:00
   968 | 2019-01-11 00:00:00
   245 | 2019-01-12 00:00:00
   176 | 2019-01-13 00:00:00
   142 | 2019-01-14 00:00:00
    80 | 2019-01-15 00:00:00
    65 | 2019-01-16 00:00:00
    46 | 2019-01-17 00:00:00
    29 | 2019-01-18 00:00:00
    26 | 2019-01-19 00:00:00
    18 | 2019-01-20 00:00:00
    17 | 2019-01-21 00:00:00
    17 | 2019-01-22 00:00:00
    13 | 2019-01-23 00:00:00
    10 | 2019-01-24 00:00:00
    13 | 2019-01-25 00:00:00
     9 | 2019-01-26 00:00:00
     6 | 2019-01-27 00:00:00
     8 | 2019-01-28 00:00:00
     8 | 2019-01-29 00:00:00
     8 | 2019-01-30 00:00:00
    10 | 2019-01-31 00:00:00
     9 | 2019-02-01 00:00:00
     4 | 2019-02-02 00:00:00
     4 | 2019-02-03 00:00:00
```

Christmas-break explains the drop, but I think the real issue starts January 10th/11th. 

My best bet is: https://github.com/sagemathinc/cocalc/pull/3433 i.e. the "Sync TS" rewrite.

Regarding the code, I only found this path:

1. `smc-util/syncstring_schema.js` → `user_query` → `on_change: ... db._user_set_query_syncstring_change_after`
2. `_user_set_query_syncstring_change_after` in `smc-hub/postgres-user-queries.coffee` calling `@log_file_access` 
3. which in turn does `INSERT INTO file_access_log`

So, I think the new sync mechanisms lacks a way to report back that the current file is being edited. My understanding of the "expected behavior" is to have entries for each user/project/filepath everything 10 minutes (at most, there is throttling in the hub) when a file is actively being edited. Without knowing all the details, I think a  debounced (1 minute or more?) call to the backend from the project or webapp needs to be added.

**Comment by williamstein** [comment]
@haraldschilly yep, you're right. This would have been inadvertently disabled by me with the new sync implementation.

**Comment by williamstein** [comment]
OK, fixed, but I won't deploy until a low-activity period (tonight or tomorrow night) since it's a hub restart.

**Comment by haraldschilly** [comment]
confirming fix:

```
     1 | 2019-04-17 00:00:00
     1 | 2019-04-18 00:00:00
     1 | 2019-04-19 00:00:00
     1 | 2019-04-20 00:00:00
     1 | 2019-04-22 00:00:00
  1124 | 2019-04-24 00:00:00
```
