### ISSUE TITLE
add a warning about connection issues with Firefox 66

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3771]
See also: #2875.

We may want to add a warning for Firefox users (again). Sample wording:

> If you are having trouble connecting to CoCalc with Firefox, please try using Google Chrome.

I see occasional disconnects and failure to reconnect to CoCalc from Firefox 66. It happens a couple times a week. Generally when it happens, I also have Chrome open and Chrome continues working normally. I'm always able to reconnect Firefox eventually by hitting reload and waiting a few seconds, although sometimes it takes several attempts. It's an intermittent issue and not as severe as what we saw with FF 59 and 60.

This is with Firefox 66.0.3 on macOS 10.14.3.

We've had a three recent customer connectivity issues with Firefox 66 that are possible instances of this problem.

**Comment by haraldschilly** [comment]
I see, this confirms my suspicion. We could easily block OSX + FF 66.0.3 like we did with 59+60. That's a bit harsh, though.
