### ISSUE TITLE
Autofocus on side open side chat retains Jupyter keybinds

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#3772]
### Reproduction steps:

1. Create a Jupyter notebook
1. Open side chat
1. Close the Jupyter notebook
1. Reopen the notebook
1. DO NOT CLICK ANYTHING
1. Notice how the chat is focused
1. Type 'h'

### What happens:

The Commands and Keyboard Shortcuts dialogue appears.

### What should happen:

'h' should appear in the chat box.

**Comment by williamstein** [comment]
The problem is that I just haven't implemented anything for maintaining focus on chat.  It's just not implemented yet...  But that doesn't make it not a bug.

**Comment by williamstein** [comment]
I can't reproduce this now; I must have fixed it with the chat rewrite...
