### ISSUE TITLE
sometimes opening a file gives blank cocalc tab (in the project)

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3773]
This is like the first bug reported in #3693, except I'm seeing it in an active project and I haven't found a way to reproduce it.

The project where I'm seeing this was restarted 4.5 hours ago, around 10:20 a.m. PST 4/23, so well after #3693 was merged.

- Open a project with two browsers on the same computer and two accounts that are owner/collaborator on the project. I used Chrome and Firefox.
- In one browser window, open file `test.term` and type `open foo.rst`.
- In the other browser window, try to open `test.term` by clicking on it in the Files list. Once in awhile, you get a blank window. I have seen this with **both** Chrome and Firefox coming up blank. Console log capture from the FF instance is shown below.
- ~~One time when I tried it, I typed `open filename.rst` from FF and the Chrome browser, which was logged in with different account but open to the same project, suddenly **opened a browser tab on the same file**.~~ (Different issue, see #3774.)

```
FATAL creating initial changefeed mentions FATAL: account_id must be given smc-0874b1093d028f478581.cacheme.js:5:712847
synctable: failed to connect (table=mentions), error=FATAL: account_id must be given
Object { mentions: (1) […] }
smc-0874b1093d028f478581.cacheme.js:5:712847
[1.39s Δ 0.09s] Signed into hub-websocket-ccd5759f6-dwsgj:5000 at Tue Apr 23 2019 14:37:20 GMT-0500 (Central Daylight Time) smc-0874b1093d028f478581.cacheme.js:5:41896
```

**Comment by williamstein** [comment]
The error indicates that this is a bug in @johnjeng 's new mentions page.   I disabled the visible link to it, but I didn't disable initialization of the underlying table.  I can try to do that now.

**Comment by williamstein** [comment]
We think https://github.com/sagemathinc/cocalc/pull/3775 fixes this.

**Comment by williamstein** [comment]
It still happens and has nothing to do with mentions.  That was a red herring.

**Comment by williamstein** [comment]
> Once in awhile, you get a blank window.

What **exactly** does that mean?  You wrote " blank browser tab" in the title, which is completely different to me than "blank window"... I'm confused.

**Comment by DrXyzzy** [comment]
I will grab a screenshot next time it happens. I believe what I saw is what @haraldschilly describes this way:

> main area is blank, but there are still the two top rows for projects and editor tabs. For me, that happens maybe once a week when I open a file. No js-exceptions.

**Comment by haraldschilly** [comment]
I see. Screenshot helps. in case it is what I wrote, I experienced that with md or yaml files. i.e. I'm pretty sure this has nothing to do with the file-type.

**Comment by williamstein** [comment]
I finally saw this for the first time ever.  It's just that **NO TAB IS SELECTED**.  Probably what happens is that there is a race condition and simultaneously something tries to select a newly opened tab, and that tab is being created.  Somehow nothing valid ends up getting selected, or some additional render needs to happen.

WORKAROUND: select a tab.

**Comment by williamstein** [comment]
I just hit this again with an ipynb file.  I also fixed the title since it is NOT a blank browser tab, it is a blank tab inside a project.  If only there were a simple way to reproduce this.

**Comment by williamstein** [comment]
Haven't seen this in a very long time.
