### ISSUE TITLE
open file from .term causes multiple sessions to open the file

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3774]
1. Log into CoCalc with 2 browsers, from a different account in each.
1. Open the same project in both browsers and close all file tabs in both sessions.
1. Open file `foo.term` in both browsers.
1. Type `open xyz.txt` in one browser. Observe that it is opened in the second browser at the same time.

**Comment by williamstein** [comment]
This is not a bug.

**Comment by DrXyzzy** [comment]
Ok. I wondered, because it only happens if both browsers have the .term open. I'll close it now.

**Comment by williamstein** [comment]
It would be reasonable to add something to the docs about expected behavior for `open` here https://doc.cocalc.com/terminal.html.   I think that page doesn't even document our `open` command, which might even be not documented!?
