### ISSUE TITLE
switch from react-bootstrap to antd.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3782]
@johnjeng claims this is hard... and gave up for now.  But we have to do this.

**Comment by williamstein** [comment]
Oops wrong commit message.

**Comment by williamstein** [comment]
We did a bunch of testing and:
1. The number of changes from react-bootstrap-0.x to react-bootstrap-1.x is *utterly daunting*.  The API has massively changed.  It's totally overwhelming.  I feel like just reading through the changes is more content than I've ever read total about bootstrap... and then some.
2. Unfortunately, there is no sane way to run react-bootstrap-0.x (=bootstrap 3) in the same project as react-bootstrap-1.x (=bootstrap 4).    Thus iteratively upgrading is impossible.  It's all or nothing.   And as mentioned in 1, doing "all" is hard.
3. Surprisingly, what is possible is going sideways.  We can switch to another UI framework iteratively!?  Somehow the very design of upgrading from  react-bootstrap-0.x to react-bootstrap-1.x makes it so that for big projects it's actually easier to just quit using react-bootstrap entirely and switch to a completely different ui library.  Isn't that stupid?
4. @johnjeng and I spent much of the day testing options, and we like antd the best for a bunch of reasons: a very rich collection of components, a clean easy-to-use and well documented API, it works very well with react (unlike a bunch of other primarily css frameworks where using them with react results in weird friction), and the code of antd is easy to read partly because it is actually written in typescript.   Antd is certainly not perfect, and there are some genuine concerns about keyboard support and accessibility.  (Material-ui was second place.) Also, with antd, one has to take **great care** not to import all of antd.  One false import and you nearly double the size of cocalc minified bundle!

So the current plan to resolve this issue is:

- create a new module called ui, e.g., `smc-webapp/ui/index.ts` (and other files as we need them)
- iteratively rewrite all code in cocalc that uses react-bootstrap (and more -- our alerts, mentions, datepickers etc) to import components from ui instead.  Inside this ui module, we'll be very careful to get stuff out of antd properly so as to avoid any big imports (or we'll get tree shaking to work, or the webpack plugin).  Also, by having all components go through our ui module, we can uniformly replace any component by a wrapper version of it if need be (e.g., if antd makes an api change, we can revert it easily, rather than rewriting all our code).

**Comment by williamstein** [comment]
OK, we have **officially decided** to switch from bootstrap to antd, "ASAP".

**Comment by haraldschilly** [comment]
Well, this ticket has some historic and general information, but I'm closing it. We use the `antd-bootstrap` file to help with compatibility and everything else is still ongoing, but the direction is clear.

**Comment by williamstein** [comment]
I keep wittiling away on this!  Current status:
```sh
~/cocalc/src/packages/frontend$ git grep react-bootstrap|wc -l
37
```

**Comment by williamstein** [comment]
Now everything but antd uses "antd-bootstrap". HOWEVER, antd-bootstrap has a number of components that are just imported from react-bootstrap still:
```
  ControlLabel,
  Form,
  FormControl,
  FormGroup,
  InputGroup,
  ListGroup,
  ListGroupItem,
```

Each of these still has to get converted to antd or the client code rewritten to not use them.
This is still nontrivial.

**Comment by williamstein** [comment]
totally done!!!!!!
