### ISSUE TITLE
jupyter: gracefully recover when .sage-jupyter2 file is deleted

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3792]
1. Work with a jupyter notebook foo.ipynb in cocalc.
2. Delete .foo.sage-jupyter2.
3. Open foo.ipynb.  Things should behave in a sensible way; evidently they don't.

REPORTED BY: Michelle Isenhour

**Comment by haraldschilly** [comment]
isn't this a dup of #2693 ?

**Comment by williamstein** [comment]
> isn't this a dup of #2693 ?

No, because the ipynb file is NOT deleted in step 3 above.  In #2693 both files are deleted.

**Comment by williamstein** [comment]
Heh, this is fixed :-)...

**Comment by williamstein** [comment]
Heh, this seems to work now.
