### ISSUE TITLE
update chromedriver to v. 74

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3801]
I think chromedriver needs to be updated.

Try the following in a CoCalc terminal with `python3`:
```
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
d = webdriver.Chrome(options=chrome_options)
```

It fails with a stacktrace:

> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73 (Driver info: chromedriver=73.0.3683.86,platform=Linux 4.15.0-1026-gcp x86_64)

Then download chromedriver for Chrome 74 from here and unzip into current directory: https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip

Run the same code as above, but start Python with ``PATH=`pwd`:$PATH python3``. The error goes away.

**Comment by haraldschilly** [comment]
is this how it is supposed to look like? I think it's worth to develop an integration test for this. e.g. can we extend your snippet with a few lines to check if e.g. "CoCalc" is in the cocalc.com/index.html page? 

![Screenshot from 2019-05-03 21-17-04](https://user-images.githubusercontent.com/207405/57160386-e72f7c80-6de8-11e9-8275-8f03e0bf7a4f.png)

**Comment by DrXyzzy** [comment]
Production CoCalc's Cloudflare setup would require the test to use IP address. Here's an integration test using another test site:
```
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
d = webdriver.Chrome(options=chrome_options)
d.implicitly_wait(10)
d.get("https://www.google.com")
assert d.find_element_by_name("btnI"),"No button for I'm feeling lucky."
print("ok")
```

**Comment by DrXyzzy** [comment]
Short answer to your question is, yes, `d = webdriver.Chrome(options=chrome_options)` should produce no output and return you to the REPL prompt.

**Comment by haraldschilly** [comment]
I'm closing this, please check if it works for you
