### ISSUE TITLE
ipywidgets -- support many third party extension widgets (such as ipyvolume)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3806]
WORKAROUND: Use Jupyter classic or JupyterLab.  See https://doc.cocalc.com/jupyter.html

**Comment by williamstein** [comment]
# Top priority TODO list:

- [ ] [bqplot](https://github.com/bloomberg/bqplot)
- [ ] ipyvolume

**Comment by mforbes** [comment]
[PyVista](https://www.pyvista.org/) support would be very nice too, which needs [itkwidgets](https://github.com/InsightSoftwareConsortium/itkwidgets).  Maybe this should be a new ticket?  (Let me know, and I can open one.)

**Comment by mperreir** [comment]
It seems that the workaround (using jupyter classic) no longer holds. On cocalc.com ipympl is missing (no paid account to test if it also fails after installing that package). Using cocalc docker, after installing ipympl, there is still a problem because requirejs fails to load jupyter-matplolib.js

So for now it seems interactive plots are not possible with matplotlib :-(

**Comment by haraldschilly** [comment]
I just tried one of my old test files for ipyvolume. I does show something in the classical notebook, see screenshot below. Regarding ipympl, that's not installed and well, it will fail in the same way as ipyvolume in cocalc itself. 

![Screenshot from 2020-09-18 17-11-24](https://user-images.githubusercontent.com/207405/93614237-23f61680-f9d2-11ea-996b-05de7bc0ddd4.png)

**Comment by mperreir** [comment]
You are right. I works...
I just reinstalled my cocalc docker with a fresh copy and now it works with the classical notebook. No idea what caused the  jupyter-matplolib.js to fail loading this morning.
I'll delete my comments so that it does not cause any misunderstanding related to the workaround.

**Comment by blois** [comment]
Colab is now supporting most third-party widgets by loading the widget implementation from jsdelivr. A rough explanation and the implementation of the widget manager is in https://github.com/googlecolab/colab-cdn-widget-manager. 

It's not the most elegant system but it seems to be working. I'd be happy to fill in any details if there's interest.

**Comment by belonesox** [comment]
Request: https://github.com/mito-ds/monorepo  «Excel inside Jupyter»

**Comment by haraldschilly** [comment]
> Request: https://github.com/mito-ds/monorepo «Excel inside Jupyter», «Mito is a spreadsheet that lives inside your JupyterLab notebooks. It allows you to edit Pandas dataframes like an Excel file, and generates Python code that corresponds to each of your edits.»

interesting, and well, more general there is also https://github.com/sagemathinc/cocalc/issues/1644 … so, in general, ways to edit columnar CSV data or some other storage format would be great.

**Comment by williamstein** [comment]
@blois 
> Colab is now supporting most third-party widgets by loading the widget implementation from jsdelivr. A rough explanation and the implementation of the widget manager is in https://github.com/googlecolab/colab-cdn-widget-manager.
> 
> It's not the most elegant system but it seems to be working. I'd be happy to fill in any details if there's interest.

We followed this approach, even based on some of your code:  https://github.com/sagemathinc/cocalc-widgets

mpl, bqplot, and ipyvolume all now work.

pyvista doesn't.  I tried with the pythreejs backend and it doesn't generate even a widget as output:

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/b779225b-dba4-4f8c-b7ef-3eb3025818fb">

```py
import numpy as np
import pyvista
pyvista.set_jupyter_backend('pythreejs') 

# Make the xyz points
theta = np.linspace(-10 * np.pi, 10 * np.pi, 100)
z = np.linspace(-2, 2, 100)
r = z**2 + 1
x = r * np.sin(theta)
y = r * np.cos(theta)
points = np.column_stack((x, y, z))

spline = pyvista.Spline(points, 500).tube(radius=0.1)
spline.plot(scalars='arc_length', show_scalar_bar=False)
```

Note that pythreejs *does* work now:

```py
from pythreejs import *
ball = Mesh(position=[-2,0,0],geometry=SphereGeometry(widthSegments=20,heightSegments=16),
            material=MeshLambertMaterial(color='red'))
dodeca = Mesh(position=[2,0,0], geometry=DodecahedronGeometry(radius=1, detail=0, _flat=True), material=MeshLambertMaterial(color='green'))

key_light = DirectionalLight(color='white', position=[3, 5, 1], intensity=0.5)
c = PerspectiveCamera(position=[0, 5, 5], up=[0, 1, 0], children=[key_light])
scene = Scene(children=[ ball,dodeca, c, AmbientLight(color='#777777')], background=None)
Renderer(camera=c,
                    scene=scene,
                    alpha=True,
                    clearOpacity=0,
                    controls=[OrbitControls(controlling=c)], width=600, height=600)
```

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/d03b0942-3e29-4c90-abe9-429cb3d0f2a5">


NOTE that pyvista **DOES WORK** nicely in X11 Desktop on CoCalc:

<img width="1599" alt="image" src="https://github.com/user-attachments/assets/91ad226f-ef54-4240-a14f-33c69fee2a66">

You could I think copy the DISPLAY env var into a notebook:

```sh
~/scratch$ echo $DISPLAY
:103808424
```

Then in the notebook:

```py
import os
os.environ['DISPLAY']=':103808424'
from pyvista import examples
mesh = examples.download_st_helens()
warped = mesh.warp_by_scalar('Elevation')
surf = warped.extract_surface().triangulate()
surf = surf.decimate_pro(0.75)  # reduce the density of the mesh by 75%
surf.plot(cmap='BrBG')
```

and this DOES work - it uses the X11 server as a framebuffer, and draws a static plot:

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/e016634a-be79-48f4-a747-6ee78badc66e">

Anyway, I'm closing this ticket.
