### ISSUE TITLE
Done!

### ISSUE THREAD

**Issue by electron2302** [sagemathinc/cocalc#3812]
Done!

More precisely, something pretty usable is now live, though I'm sure there will be some bugs, which will be new issues.  I'm closing this.

_Originally posted by @williamstein in https://github.com/sagemathinc/cocalc/issues/1930#issuecomment-487231691_

**Comment by electron2302** [comment]
I'm very sorry,
that was not on purpose please delete this issue

**Comment by williamstein** [comment]
No worries -- thanks for participating in cocalc.
