### ISSUE TITLE
terminal goes blank bug (easy to reproduce)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3819]
1. Open a file foo.r
2. split vertically (so split bar is vertical)
3. make right side a terminal
4. split left side horizontally, so split bar is horizontal
5. make bottom left a terminal
6. close terminal in top right.
7. lower left terminal is BLANK.

This happens every time.  No clue why, but it's reproducible and a very annoying bug.

WORKAROUNDS: 

- 1. close and open the file tab
- 2. OR, split the terminal again, then delete the new terminal

**Comment by haraldschilly** [comment]
dup of #3471 ?

**Comment by williamstein** [comment]
Yes, this is the same as #3471, though with different (simpler) steps to reproduce. You don't have to type anything in any terminal.
