### ISSUE TITLE
better guide new users to try what cocalc is uniquely good at

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3823]
First, come up with a minimal list of things any new user to cocalc should do, which involve some things CoCalc is perhaps uniquely good at:

- 1. Create a project if you aren't a collab on one already
- 2. Open a project
- 3. Edit a file.
- 4. View TimeTravel for that file.
- 5. Invite a collaborator.

Each day we do a query through the database for new users who haven't done step 1, and email them explaining how.  Or, instead of email, have an in-app banner with a link to how, depending on the step and testing.   And same for steps 2 and 3, etc.

For example, in the last 24 hours, we have had 448 new accounts created (yeah!).  How many of these 448 new users are collabs on at least one project?  How many have actually opened that project?  How many have edited a file in that project?  Of those, how many viewed TimeTravel?  How many added a collaborator to a project?       We might naively assume "all of them, of course!"  but there is an actual answer to this question.  I wonder what it is.

I did a spot check of 2 of those 448 accounts, and it was two students and one created a project called "final project" for a CS class and added a classmate, and they then worked together, so for those 2 no guidance is needed.

**Comment by williamstein** [comment]
I spot checked more, and a ton are from one of our api users that automates account creation and just uses cocalc jupyter notebooks in an iframe -- it would make no sense to send those users the same sort of emails about how to use cocalc functionality as mentioned above.

**Comment by novoselt** [comment]
What are current expectations for this ticket? Creating the first project is automated, creating new files is easy to discover and now it has AI integration too. Adding extra collaborators and TimeTravel are awesome, but guiding every user to them is not necessarily desirable, e.g. I think a lot of students may not need to add collaborators manually. And TimeTravel is more interesting once you have "raw material" for it or, even better, a real life use case.

**Comment by williamstein** [comment]
Good point -- this is an old ticket and we already long since dealt with it.
