### ISSUE TITLE
Show size and number of files for collected assignments

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#3829]
In the assignment tab of a CoCalc .course file, column 2
("collect from student") has a "collect" button for each student.

For students whose assignment has been collected, the "collect" button
is orange and has the date and time of collection displayed under it.

It would be nice to also display the size and number of items of
the corresponding assignment folder.

That would save instructors time when some students have not completed
the assignment. Currently one needs to open all assignment folders;
with the proposed change one could skip visiting empty assignment folders.

**Comment by williamstein** [comment]
It could also show the most recent modification timestamp of any collected file, so you know when the student last worked on the assignment.

**Comment by novoselt** [comment]
I surely hope that most instructors do not have to fish for non-empty assignments in a vast sea of empty ones... Let's not complicate the user interface!
