### ISSUE TITLE
with "classical" notebook, cannot scroll kernel menu to access out-of-frame options

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3830]
Seen with macOS 10.14.3, Safari 12.0.3 (14606.4.5). Similar problem on pre-2018 iPad Pro with iOS 12.2.

After switching to CoCalc notebook, the Kernel menu scrolls down ok, allowing access to all options, on both devices, with Safari.

<img width="1014" alt="cannot-scroll-down" src="https://user-images.githubusercontent.com/528072/57792670-2fae3a80-7705-11e9-86a6-f77c0786e269.png">

**Comment by DrXyzzy** [comment]
Not a problem with Chrome.

**Comment by williamstein** [comment]
> Not a problem with Chrome.

I just tested right now and exactly this is a problem with Chrome and Safari still.

I have absolutely no idea how to fix this or if it is even possible.

**Comment by williamstein** [comment]
I'm removing the safari tag, since this isn't safari specific as far as I can tell...

**Comment by williamstein** [comment]
Closing due to https://github.com/sagemathinc/cocalc/issues/7706
