### ISSUE TITLE
in cocalc notebook with firefox, other user's cursor at top of cell is partly hidden

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3831]
With Firefox 66.0.5.

1. Open a CoCalc (not Classical) notebook in Firefox (session 1) and another browser (session 2).
1. Create a compute cell with a few lines of comments.
1. In session 1 (Firefox), move focus to another cell.
1. In session 2 (other browser), put the cursor on first line of the compute cell with the comments.
1. Observe that in session 1 (Firefox), the top part of the other user's cursor is not visible.

![ff-other-user-cursor](https://user-images.githubusercontent.com/528072/57794283-e7911700-7708-11e9-8c43-1817a198bd20.png)

**Comment by williamstein** [comment]
Can you be clear with this and other browser specific tickets if this is NOT a problem with Chrome?

**Comment by DrXyzzy** [comment]
Not a problem with Chrome.

**Comment by williamstein** [comment]
No longer a problem on firefox.

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/de276778-3539-4f57-8bdd-ea97559c59ed">
