### ISSUE TITLE
ctrl+I for split view is confusing and inconsistent

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3846]
account page states:

> Split view in any editor: `control+I`

but in reality

* for yaml files it inserts `<em></em>` for italic html (which should be an issue on its own, i guess)
* for sagews, it splits horizontally and is stuck there (I would assume clicking ctrl+i repeatedly toggles through its states)

So, maybe this is just for sagews, actually, and personally I'm for removing that keyboard shortcut. It makes a lot of sense to have it for formatting text as italic (if applicable). … or come up with a better shortcut for the frame editor infrastructure later.

**Comment by williamstein** [comment]
> So, maybe this is just for sagews, actually, and personally I'm for removing that keyboard shortcut.

I am fine with that.  It should be a one-line change somewhere, hence tagging as "easy".

**Comment by williamstein** [comment]
> So, maybe this is just for sagews, actually,

This is a "react rewrite" issue... it used to be for all editors, when they were non-react; now they all got rewritten, except sagews.

**Comment by williamstein** [comment]
> it splits horizontally and is stuck there (I would assume clicking ctrl+i repeatedly toggles through its states)

No, it cycles through... if you refocus.  See, it **loses focus**, which can cause confusion.
