### ISSUE TITLE
share server: breadcrumb navbar overlaps with a "banner"

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3856]
see screenshot below ... this looks quite bad.

Maybe we should move that "banner" a div-row below to avoid overlaps.
![Screenshot from 2019-05-28 19-36-49](https://user-images.githubusercontent.com/207405/58499290-2058d380-8180-11e9-8a20-ff918a16a9a9.png)

**Comment by williamstein** [comment]
> this looks quite bad.

I know.  I did this **on purpose**, since it's much better than not having any general link at all to cocalc, and we really need to kick the share server dev back into gear.

Click for the Embed version if you want something clean to share for now.
