### ISSUE TITLE
zip extractor (and maybe similar ones?) → scrollbar missing

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3858]
Issue this sequence of commands

```
mkdir longzip
cd longzip
touch file-{1..100}.md
zip files.zip file-*.md
open files.zip 
```

and you end up with

![screenshot-cocalc com-2019 05 30-11-55-13](https://user-images.githubusercontent.com/207405/58625129-18a94400-82d2-11e9-9558-f9eef6124891.png)

**Comment by williamstein** [comment]
This was fixed long ago.
