### ISSUE TITLE
Shutting down a specific jupyter notebook by a terminal command

### ISSUE THREAD

**Issue by quantumFlame** [sagemathinc/cocalc#3884]
Scenes where this feature might be useful:
1) Admin might want to manually shutdown jupyter notebooks which are idle for a while
2) Starting Jupyter notebooks where there is an idle timeout parameter (from William)

Attention:
We would have to define exactly what "idle" means (which is not obvious) -- does it mean explicit user initiated action on the frontend? What about output from the kernel on the backend (but nothing from the user), etc. It would definitely make sense to have this as another feature. (from William)

In my opinion:
If I were a user, I would like the notebook keeps running even nothing input from the frontend, since I might have some big loops in the code.
However, if I were the admin, I would like to shutdown the notebook if no input from the frontend for a while. Because if the user is not active, it is also possible that the output from the backend is just a dead loop and we should protect the server. We could allow for different duration of idle time for different users.
Therefore, we might want to call functions to monitoring the frontend and backend separatedly and then make different dicission based on different scenes.

Thanks!

**Comment by williamstein** [comment]
I'm closing this since it is so specific and got no traction.  However, we may add to our API ability to control specific Jupyter notebooks.   https://cocalc.com/api/v2

@schrodingersket
