### ISSUE TITLE
jupyter2 tab completion sometimes inserts in the wrong line

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3885]
case 1: `from IPython import get_ipython` and then `get_ip[TAB]` → inserts `ython` in the first line

case 2: `from numpy import empty_like` and then `emtpy_li[TAB]` → I needed to press TAB twice, and then it was inserted correctly.

I've no idea what's going on, and after my second attempt I recorded it since it is so weird.

![cocalc-jupyter-tab-completion-wrong-line](https://user-images.githubusercontent.com/207405/59266115-2ef6be80-8c47-11e9-9162-5fa73dba9130.gif)

**Comment by haraldschilly** [comment]
update, I tested this today. the first cell completes this way:

![Screenshot from 2019-07-31 10-20-19](https://user-images.githubusercontent.com/207405/62195820-11a7bc00-b37d-11e9-9c20-4b41ab8c257a.png)

and the second one not at all. `empty_li[TAB]` works when it is on its own cell.

**Comment by haraldschilly** [comment]
I've debugged the first `get_ipython` case. What I noticed is, its important to try this in a new cell. Once it is edited, it seems to work. Second, it also breaks if there is just `get_ip` in a cell, and then the tab key.

Here is where it gets funny: the `merge_cell_input` behaves differently, at least it looks like. I thought that `set_cell_input` should replace the content of the cell with the new content (after tab completion is done) but it isn't. In the first (broken) case, it's less than what it should be (just `python`), and in the second (working) case, it is more. 

**broken** this completes `get_i` to `pythonget_i`

![Screenshot from 2019-07-31 10-45-55](https://user-images.githubusercontent.com/207405/62197882-f8087380-b380-11e9-945c-9dfa428b451a.png)

**working** this completes `get_i` to `get_ipython`

![Screenshot from 2019-07-31 10-47-00](https://user-images.githubusercontent.com/207405/62197902-05256280-b381-11e9-99f4-ae9da4dd7049.png)

**Comment by williamstein** [comment]
Thanks for these additional examples.    You have to understand that there are many different places where the input of the cell is stored, in different states, and this makes things complicated.  Properly one part of the tab completion code is using the wrong version.   Probably the right fix is to move, as much as possible, the tab completion code to codemirror-editor.tsx...

**Comment by williamstein** [comment]
Same as https://github.com/sagemathinc/cocalc/issues/3978
