### ISSUE TITLE
sagews2pdf: specify xelatex as the default engine

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3910]
sagews2pdf produces a temporary tex file and runs it via xelatex (in order to deal with special characters better, etc.). however, when opened in cocalc's latex editor, it uses the default pdflatex engine. the goal of this ticket here is to improve the out of the box situation, by adding a note in the tex file to use xelatex and also improve the latex editor to actually understand it.

my approach would be to support the annotation "standard" introduced by texstudio – see #2839  –  i.e. in this case here, the export script should start the output file with this comment:

```
% !TeX program = xelatex
```

the point is, this is compatible with texstudio and various other editors.

Step two is to enhance the latex editor to parse this and map the found program command to a menu selection (a simple heuristic should be fine) – and if the command is not found, report an error once after opening the file and choose the default as usual.

**Comment by williamstein** [comment]
I think you did it.
