### ISSUE TITLE
support an X11 desktop as a frame in Jupyter

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3922]
The goal is to make it so one can use any X11 graphical output or spawned window from any Jupyter notebook.   

You can kind of simulate this now by starting an X11 desktop, typing `echo $DISPLAY`, then typing `import os; os.environ.DISPLAY=":number"` in Jupyter, and using X11. 

Probably the way this will work is that if you open an X11 desktop frame, you'll have a chance to start it (a big button).  Starting it will assign the DISPLAY number, and *restart* the Jupyter kernel, with the DISPLAY environment variable properly set.  Then X11 output will just work, for any kernel.  This should work for R, etc.

REQUESTED BY: Patrick Watson

**Comment by williamstein** [comment]
One application of this is that [the standard Python turtle module](https://docs.python.org/3.3/library/turtle.html?highlight=turtle) will work. 

One other thing -- we should parse some of the error message from some kernels to see if they suggest a need for X11 support, and if so, suggest to the user to open an X11 frame.

**Comment by SolarisYan** [comment]
@williamstein  This will be  a cool feature

**Comment by williamstein** [comment]
This is a cool idea, but it will never ever happen in "mainstream JupyterLab" or the rest of the jupyter ecosystem, and our goal is to make CoCalc Jupyter very good, but also FULLY COMPATIBLE with the broader ecosystem.  Having lots of features in notebooks that work nowhere else violates that principle.  It's also possible to do this right now by just using the DISPLAY environment variable:

Start X11 desktop.  In the terminal type "export DISPLAY".   In a notebook do os.environ['DISPLAY'] = '...value output before ...' and now windows pop up in the X11 desktop session.  

The cool thing about the above directions is they also work on any Linux computer -- it's just standard UNIX, and nothing specific to cocalc.
