### ISSUE TITLE
add extra jupyter  kernel environment variables 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3929]
the goal of this ticket is to give users the ability to add one or more environment variables to the kernel instance. this  is possible to do by copying the `kernel.json` file for a custom kernel and setting/modifying the `env` key. it would be much easier to have this in the UI itself and saved on a per-file basis, probably in the `cocalc` namespace of the metadata info.

**Comment by williamstein** [comment]
> the cocalc namespace of the metadata info.

Is that a field in the projects table?   What is the scope that we want for this -- per *project*, per *file*, per *user*.  I thin per file is the easiest to implement - it would just be an entry in the syncdb file -- this would be fairly easy to implement...

**Comment by haraldschilly** [comment]
This is meant to be per file. I would save it in the ipynb file itself, in `"metadata" : {"cocalc" : ... }`. That way it is preserved when the file is moved/copied (I'm thinking about a course). It's also cocalc only, hence it makes sense to me to stuff this into its own key/namespace.
