### ISSUE TITLE
jupyter: unfocus frame editor buttons after a click?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3931]
I'm wondering if those buttons in the frame editor should not stick to be focused when they're clicked. E.g. 

1. eval jupyter cell (focused with blue border) via shift return, ok
2. click on magnification glass +, font is a bit larger, ok
3. type shift-return again.

what happens is it increases the font even more.

alternatively, clicking any button in that editor bar should remove the focus of a cell. then, it would be clear that my next keyboard action isn't going to impact the supposedly focused cell.

PS: I added the bug label, because I was briefly puzzled about exactly this.

**Comment by williamstein** [comment]
I agree, and I agree with making this a bug.

**Comment by williamstein** [comment]
These buttons no longer exist.
