### ISSUE TITLE
make @mention completion consistent with Jupyter notebooks and command line python

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3938]
In chat, if you start an @-mention by typing e.g. `@h`, the list of choices includes all names that include the letter 'h'. It should be limited to choices that begin with 'h.

![mention-h](https://user-images.githubusercontent.com/528072/60748417-55acca00-9f53-11e9-8d5f-fe5068578225.png)

**Comment by DrXyzzy** [comment]
Current implementation is also inconsistent with Facebook.

@-mention search in a github issue appears to put matches for the first character typed first, followed by names that contain a match to the first character typed anywhere

additional notes from @williamstein:
Checked https://signavio.github.io/react-mentions/master/ and this [present behavior] is the default react-mentions behavior. The docs say you can pass a function in to do the filtering, so this will be easy to fix.

**Comment by williamstein** [comment]
I don't agree with this.
