### ISSUE TITLE
with safari, upper toolbar area is not visible in Files view

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3939]
Seen with Safari 12.0.3 on macOS 10.14.3 and on iPad Safari with iOS 12.3.1. Also seen on Chrome on the same iPad Pro.

NOT seen with Chrome 75.0.3770.100 (Official Build) (64-bit) on same macOS.

Here is the (normal) top of the Files page in Chrome on macOS:

<img width="898" alt="chrome-files-top" src="https://user-images.githubusercontent.com/528072/60750378-2acf6f80-9f6d-11e9-8f4d-3cd0d13e4bb9.png">

Here is the Safari view - note search box & other controls are not visible:

<img width="899" alt="safari-files-top" src="https://user-images.githubusercontent.com/528072/60750381-3ae74f00-9f6d-11e9-81de-62c56e522bca.png">

**Comment by williamstein** [comment]
Probably caused by https://github.com/sagemathinc/cocalc/pull/3936 which I've reverted.
