### ISSUE TITLE
open assignment stalls if assignment folders are removed

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3940]
Seen with Chrome 75.0.3770.100 (Official Build) (64-bit) on macOS 10.14.3.

1. Start a new project. This is to ensure that a large Files list isn't adding to the file search time.
1. Open a terminal. Do `mkdir -p ASSIGN/AS1`.
1. Open a new .course file. Open the Assignments tab.
1. In the upper right "Add assignment by folder name..." blank, enter `AS1` and add the assignment folder.
1. In the terminal, do `rm -rf ASSIGN`.
1. In the .course Assignments tab, click the disclosure triangle to the left of "ASSIGN/AS1" and then click "Open" to view the assignment folder.
1. Observe that the view stalls at "Loading" for several minutes.

![spinning-assign](https://user-images.githubusercontent.com/528072/60750989-2eff8b00-9f75-11e9-95dc-33438e668b49.png)

**Comment by DrXyzzy** [comment]
Eventually (apparently after 15 minutes) the Loading screen times out with an error message in a red box:

Directory listing error
maximum time (=900000ms) exceeded - last error {}

**Comment by williamstein** [comment]
Thanks for finding this; it's easy to reproduce, and important (since users feel like they suddenly don't have access to their work), so I assigned myself to this.

**Comment by williamstein** [comment]
This might be the same thing as https://github.com/sagemathinc/cocalc/issues/3915
