### ISSUE TITLE
LaTeX macros in Markdown cell do not render properly in CoCalc Jupyter notebook

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3941]
Reported by Özlem Salehi Köken.

1. Open a Jupyter notebook with Python 3 system-wide kernel.
1. Enter the following in a Markdown cell:
    ```
    $\newcommand{\ket}[1]{|#1\rangle}$
    $\ket{hello}$
    ```
1. Run the cell in CoCalc Jupyter and see incorrect output:

    ![ket-bad](https://user-images.githubusercontent.com/528072/60837759-99d7de80-a18e-11e9-960d-d0897acedee4.png)

1. Select `File` > `Switch to classical notebook...` and run the cell again to see correct output:

    ![ket-good](https://user-images.githubusercontent.com/528072/60837765-a0feec80-a18e-11e9-8a93-1cbda05eb37a.png)

See also: #2834.

**Comment by williamstein** [comment]
This is probably caused by our katex rendering not falling back to mathjax when it should.
