### ISSUE TITLE
clicking on anchor with hashtag is not handled correctly in CoCalc Jupyter

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3942]
Reported by Özlem Salehi Köken.

1. Create notebook `src.ipynb` with Python 3 system-wide kernel and put the following into a Markdown cell. Run the cell, but don't click the link yet:
    ```
    <a href="dst.ipynb#come_here">Jump to another notebook</a>
   ```
1. Create notebook `dst.ipynb` with Python 3 system-wide kernel and put the following into a Markdown cell. Run the cell:
    ```
    <a id="come_here">Arrived at destination</a>
    ```
1. Return to `src.ipynb` and click the "Jump to another notebook" link.
1. **Observe that CoCalc opens a new tab to new file `dst.ipynb#come_here`.**
1. Click `Halt` in both notebooks.
1. In project settings, launch `Plain Jupyter Classic Server`.
1. Open `src.ipynb` and click the link. Observe that a tab opens onto `dst.ipynb`. So the bug is not present with Plain Jupyter Classic Server.

**Comment by williamstein** [comment]
Thanks for the excellent steps above.  I'll make this my "warm up bug" for today.

**Comment by williamstein** [comment]
NOTE: this has less to do with ipynb than we might think, e.g., it also happens with two markdown files.
