### ISSUE TITLE
Add Scala kernel for Jupyter

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#395]
Add a Scala kernel for Jupyter. Possibly one of these:
- https://github.com/mattpap/IScala
- https://github.com/alexarchambault/jupyter-scala

**Comment by haraldschilly** [comment]
I would like to have one, too. But I don't know how to roll them out globally for a multiuser environment :family:

**Comment by williamstein** [comment]
On Tue, Jan 26, 2016 at 4:58 AM, Harald Schilly <notifications@github.com>
wrote:

> I would like to have one, too. But I don't know how to roll them out
> globally for a multiuser environment [image: :family:]
>
>
So far what I've done is very lame but has worked: install locally, figure
out what got installed, create a folder in /usr/local/share/jupyter based
on an existing working one, and then debug it.

A lot of the software on SMC is not designed to be multiuser friendly yet,
unfortunately.  (Sage itself included, and definitely Jupyter.)


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/395#issuecomment-174999844>.
>



-- 
William (http://wstein.org)

**Comment by slel** [comment]
Closing as a Scala jupyter kernel seems to be present system-wide now.

**Comment by slel** [comment]
Reopening as the Scala Jupyter kernel no longer seems to be present.

**Comment by haraldschilly** [comment]
see [notes here](https://github.com/sagemathinc/cocalc/wiki/Ubuntu-18.04-project-image-upgrade)

you can switch back to the old image

**Comment by slel** [comment]
The Jupyter kernel for Scala called "Almond" is actively maintained
and might be a good replacement for "IScala".

- Almond
  - home: http://almond-sh.github.io/almond/stable
  - repo: https://github.com/almond-sh/almond

**Comment by hammer** [comment]
Hey @haraldschilly, as @slel notes Almond is actively maintained and an easy install. Would y'all consider re-opening this issue and restoring Scala notebooks to the CoCalc product?

**Comment by slel** [comment]
Hey @hammer is it easy to do a multiuser install of Almond?

**Comment by haraldschilly** [comment]
well, I can give it a try, but does output show up?

**Comment by hammer** [comment]
@slel I believe you just pass `global` as an [install option](https://github.com/almond-sh/almond/blob/master/docs/pages/install-options.md) as noted on the issue you opened: https://github.com/almond-sh/almond/issues/46.

@haraldschilly thanks so much!

**Comment by slel** [comment]
> @slel I believe you just pass `global` as an [install option](https://github.com/almond-sh/almond/blob/master/docs/pages/install-options.md) as noted on the issue you opened: [almond-sh/almond#46](https://github.com/almond-sh/almond/issues/46).


Oh I had missed the answers there.
 
When I had last tried installing in a CoCalc project,
installation went fine but when trying it out and
executing code, the output did not seem to show.

Have you tried installing in a CoCalc project?

I might give it a try during Sage Days 106 next week
if nobody beats me to it.

**Comment by slel** [comment]
According to this page:

- https://almond.sh/docs/install-versions

we need Almond 0.6.0 since CoCalc provides Scala 2.11.12.

Is there a plan to upgrade Scala to 2.12.x on CoCalc?
Or to provide several versions: 2.11.x, 2.12.x, 2.13.x?

Maybe @hammer can comment on what would be desirable.

**Comment by slel** [comment]
I tried again in the same CoCalc project, with the same result.

I documented my attempt here:

- https://cocalc.com/share/e67eb26b049ecba35ed4f58bdfafc3cec7726390/Install-Almond-Scala-Jupyter-kernel-in-CoCalc-2020.md?viewer=share

@hammer I added you as a collaborator on that project, can you have a look?

**Comment by hammer** [comment]
Shouldn’t `~$ ./almond --install` be `~$ ./almond --install --global`? I don’t know enough about CoCalc to know what kind of permissions you have on the host OS but when you say the install must be “multi-user” I presume that’s what you mean.

**Comment by slel** [comment]
I'm only a user, testing in a user project. Once it works there and we know
what to change to make a global install, @haraldschilly can install globally.
