### ISSUE TITLE
landing pages: fix offset in anchor links

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3953]
~~since the top row can have different heights, the anchor offsets need to take this into account. otherwise the anchor scrolls to far.~~

~~alternatively, tweak the bootstrap layout in such a way that this doesn't happen.~~

the original issue is fixed (change in CSS), but the problem remains. it's caused by lazy-loading the images.

also: #1983

**Comment by williamstein** [comment]
I can't tell what this is even about.
