### ISSUE TITLE
sometimes cocalc-jupyter tab complete inserts the completion in the wrong place

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3978]
Jupyter tab completion is sometimes not 100% robust.

REPORTED BY: John Sukup 

1. Try to complete something
2. It doesn't necessarily work 100%, e.g., nothing happens at all or the completion is placed in the wrong spot.

This is probably caused by something being slightly out of sync regarding the typed and visible cell content, versus what is actually sent for completion vs the cell content when the completion is inserted.  The best way to fix it is just to read the relevant code and think.

**Comment by haraldschilly** [comment]
reminds me of #3885

**Comment by williamstein** [comment]
I'm going to fix this.  I understand the root cause finally...
