### ISSUE TITLE
html editor: reload button doesn't reload the iframe view

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3984]
The reload button in the frame showing the embedded html doesn't refresh. 

feels like this button has no associated action. I wonder if it should remove the iframe view and add it again. That will trigger reloading everything.

**Comment by williamstein** [comment]
Reloading an iframe is a standard Javascript/html problem: https://stackoverflow.com/questions/4249809/reload-an-iframe-with-jquery

But yes, we should definitely fix this bug.
