### ISSUE TITLE
Opening a direct link to a cocalc file opens that file name + null

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#3987]
Using gmail, clicking the mention notification link results in a `.sage-chatnull` file
<img width="350" alt="Screen Shot 2019-08-02 at 9 31 04 AM" src="https://user-images.githubusercontent.com/618575/62384825-485e0d80-b508-11e9-9d10-3e884f9df1da.png">

**Comment by williamstein** [comment]
I'm seeing this too...

**Comment by haraldschilly** [comment]
sounds like a dup of https://github.com/sagemathinc/cocalc/issues/3894

**Comment by johnjeng** [comment]
Yup. Looks like it.
