### ISSUE TITLE
Account/Subscriptions list only shows latest 10 items

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3990]
We have one customer with 12 active subscriptions. Their `Subscriptions/Course packages` tab shows only 10, with no way to scroll down to see the other 2.

**Comment by DrXyzzy** [comment]
This is with `Chrome 76.0.3809.87 (Official Build) (64-bit)` on `macOS 10.14.3`.

**Comment by williamstein** [comment]
deprecated and rewritten etc.
