### ISSUE TITLE
parametric_plot3d menu choices do nothing in Jupyter with Sagemath kernel

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3991]
Seen with `Chrome 76.0.3809.87 (Official Build) (64-bit)`  and `Safari 12.0.3 (14606.4.5)` on macOS 10.14.3.

Reported by Ingo Dahn.

1. Run the following in a code cell in a CoCalc Jupyter notebook with Sagemath (stable) kernel:

    ```
    parametric_plot3d((sin(x), cos(x), x/10), (x,0,20))
    ```
1. Open the viewer. (Observe that the bottom of the plot is below the viewport. That is a different but possibly related issue from this one, #2662.)

1. Right-click near the top of the viewer. A menu of plotting options appears, but clicking on the options, such as "Zoom", has no effect.

    <img width="837" alt="plot3d-menu" src="https://user-images.githubusercontent.com/528072/62423608-2ee3cf80-b688-11e9-8803-a65dc19fef36.png">

1. Right-click near the bottom of the viewer. The bottom part of the menu of plotting options is below the viewport and cannot be brought into view.

**Comment by williamstein** [comment]
plotting has totally different menu options now (since it's threejs based) and that menu does work.
