### ISSUE TITLE
yapf python formatting integration doesn't show line number of error

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3992]
This is pretty frustrating (you just have to use the command line).  Here's a screenshot show that our yapf integration doesn't give the line number where the problem is, but yapf itself does.  What happened?

![image](https://user-images.githubusercontent.com/1276278/62429953-1943c980-b6cb-11e9-8fed-60df9e1ec163.png)

**Comment by haraldschilly** [comment]
I am closing this. Attached is a simple test as of today, correctly showing line number 7. 
![Screenshot from 2019-10-07 12-54-02](https://user-images.githubusercontent.com/207405/66306302-95dc6980-e901-11e9-93d7-8d4e6117e8ec.png)
![Screenshot from 2019-10-07 12-53-14](https://user-images.githubusercontent.com/207405/66306303-95dc6980-e901-11e9-81fc-7caa419fb9dd.png)
