### ISSUE TITLE
prevent flash of account settings page when logging in with token

### ISSUE THREAD

**Issue by benchun** [sagemathinc/cocalc#3994]
When using the `fullscreen=kiosk&auth_token=` query parameters, the user is presented with a "loading..." indicator, then their account settings page, and then the browser seems to automatically advance to the intended project page where they again see "loading..." before the notebook itself appears. It would be less confusing to the user if they saw nothing or a single "loading..." page while waiting for any necessary setup to take place.

**Comment by haraldschilly** [comment]
yes, absolutely. on top of that some loading indicator giving feedback what is missing to continue showing the intended page/open target file might also be a good thing to have.

**Comment by benchun** [comment]
That would be great. We are getting complaints from users (and @brianfields has also experienced) getting stuck at the account settings page when trying to load a notebook this way.
