### ISSUE TITLE
ipad: latex editor preview stuck loading

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4004]
on browserstack for OSX 12.1 (or I'm not sure, a recent ipad at least) the preview in the latex editor is stuck at loading. maybe related to #2216

![Screenshot from 2019-08-08 14-44-49](https://user-images.githubusercontent.com/207405/62704859-9ed9b900-b9ec-11e9-88fd-5bf1dcc380eb.png)

**Comment by williamstein** [comment]
It definitely works fine these days on a real iPad.
