### ISSUE TITLE
improve @mention email notification criteria

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4010]
See https://github.com/sagemathinc/cocalc/issues/3599#issuecomment-520352133

**Comment by matthew-brett** [comment]
Following on from the comment you linked.

You can imagine, I'm sure, but my workflow is that my students will at some point get onto Cocalc to do some work; sessions will be around a couple of hours.   I want them to be able to @ notify me that they are stuck.  If I see it, I'll join them in the Cocalc notebook.  When I'm online in Cocalc helping, I would be happy for @ mentions not to send email (although that wouldn't be too bad).    So, in order of preference:

* @ mentions send email unless I'm active in the shared notebook in the last e.g. 10 minutes or so.
* @ mentions always send email.

**Comment by williamstein** [comment]
As a possible workaround for now, you can at least periodically check

https://cocalc.com/notifications?session=default

and see all unread notifications.

**Comment by williamstein** [comment]
I think I fixed this a year or so ago.  I think now every mentions sends an email, up to some large per day limit (to prevent abuse).
