### ISSUE TITLE
jupyter notebook jumps vertically after manual scrolling

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4013]
Details to follow. I'm creating this issue as placeholder for now.

Seen on macOS 10.14.3 on
* Chrome Version 76.0.3809.100 (Official Build) (64-bit) 
* Safari 12.0.3 (14606.4.5)

Also seen on Firefox, not sure of version.

Workarounds - doing either of these has eliminated the problem in a couple tests.
* Put notebook into fullscreen mode.
* Shift-click on the file tab for the notebook, to pop out a window without toolbars above the project toolbar.

**Comment by williamstein** [comment]
I've pushed  a change to put the new windowing functionality behind a non-default feature gate for now.  There is an option in editor settings.  This should be live in a few minutes.

**Comment by DrXyzzy** [comment]
Reported (probably, although details are lacking) by Fouad Yousif.

**Comment by DrXyzzy** [comment]
Also possibly reported by Guilherme Kinzel.

**Comment by DrXyzzy** [comment]
With the following enabled (checked) in UI `Account` > `Editor settings`: *Jupyter window: use windowing to make rendering very large cocalc-jupyter notebooks much faster (WARNING: there are reports this makes scrolling jumpy)*,
here is a small example which I think is showing the problem in question:

1. Start a new Python 3 (system-wide) CoCalc Jupyter notebook with a screen resolution of about 1200x800.
1. Put the following in the first cell and execute. About 35 of the 50 lines of output should be visible:
    ```
    for i in range(50):
        print(f"line {i:03}")
    ```
1. Put the following in the second cell and execute:
    ```
    for i in range(50,100):
        print(f"line {i:03}")
    ```
1. Scroll to the top of the worksheet using two-finger scroll (not scrollbar), but leave the cursor in the bottom (third) cell.
1. Gently scroll - use a light flicking two-finger motion so that scrolling momentum is created - until the code of the second cell comes into about the center of the screen, and let go.
1. Observe that the **output jumps vertically** after you let go, so that the last lines of output are at the bottom of the viewable window. After the jump, the second code cell is no longer visible.
1. In `Account` > `Editor settings`, disable (uncheck) *Jupyter window: use windowing to make rendering very large cocalc-jupyter notebooks much faster (WARNING: there are reports this makes scrolling jumpy)* and refresh the browser.
1. Return to the sample notebook. The jumping is no longer visible.
1. After re-enabling Jupyter windowing, and refreshing the browser, AND clicking in the bottom (empty) third cell, jumping is again visible.

Note: this issue might be relevant: https://github.com/bvaughn/react-virtualized/issues/878

**Comment by DrXyzzy** [comment]
I'm not sure momentum is needed, as stated in step 5 above, for the problem to show. I'm also able to see the vertical jumping if I just scroll down slowly, keeping two fingers on the trackpad. Shortly after the second code cell comes into view, the jump happens to display the bottom of the output and hide the code above it.

**Comment by williamstein** [comment]
I can remove Heisenbug -- this is just that codemirror editor getting scrolled into view when it is created/focused, and is easily reproducible.  Good job.
