### ISSUE TITLE
create a sagews to ipynb converter with a button that does the export

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#402]
See also #401

**Comment by slel** [comment]
See also https://github.com/anteprandium/sagews2ipynb

**Comment by williamstein** [comment]
Very important for our target market -- avoids lock in and makes Sagews way more "viable".

**Comment by williamstein** [comment]
Done,  as a command line tool, e.g., 
```
smc-sagews2ipynb 
```
in the terminal.

**Comment by vit-tucek** [comment]
I've just spent good half an hour looking for this functionality. Please don't forget to expose it under some export button once it's finished. :)

**Comment by williamstein** [comment]
@bryantpq will create the button.

**Comment by bryantpq** [comment]
Done [#2250](https://github.com/sagemathinc/cocalc/pull/2250)
