### ISSUE TITLE
AsyncIO support

### ISSUE THREAD

**Issue by techdragon** [sagemathinc/cocalc#4028]
The IPython kernel now supports AsyncIO, https://ipython.readthedocs.io/en/stable/interactive/autoawait.html so it would be good to also support this in the default CoCalc interface.

**Comment by haraldschilly** [comment]
yes, this would be neat to have.

**Comment by techdragon** [comment]
I can confirm that having updated the system environment to a newer version of IPython, AsyncIO works in the Classic Jupyter Notebook Server... and the CoCalc UI still appears to function with these newer libraries installed, so thats a very small start.

**Comment by haraldschilly** [comment]
updating ipython is on my TODO. however ,I'm mainly concerned about cocalc's jupyter implementation. it doesn't use anything from ipython codebase, therefore there is no impact. this also means it requires to know what ipython is doing and implementing this. how exactly, I don't know.

If I understand their codebase correctly, they try to compile the cell and if it fails, wrap it. That's it?

see https://github.com/ipython/ipython/blob/master/IPython/core/async_helpers.py

**Comment by haraldschilly** [comment]
I just checked this in cocalc's system-wide python3 kernel and it works right out of the box. So, just a newer underlying kernel is all it needs. What's a bit behind is syntax highlighting the await keyword -- but that could be something for another issue ....

![Screenshot from 2020-06-20 22-30-01](https://user-images.githubusercontent.com/207405/85211053-bb9d8780-b345-11ea-88d6-b3bf267af220.png)
