### ISSUE TITLE
jupyter2: tab-completion window causes cell output to be very high

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4031]
This isn't a serious bug, but still a bit annoying and different than before the windowed render optimization. When the tab-completion menu shows up, the output of the cell expands all across the page. When selecting an entry or closing it, everything is back to normal. Hence there is something going on with cell heights when inserting that menu.

python related (long menu)

![Screenshot from 2019-08-22 19-25-55](https://user-images.githubusercontent.com/207405/63536016-09254a00-c513-11e9-8b9f-68487fef15cb.png)

julia related, i.e. it also happens for a short 2-entry menu 

![Screenshot from 2019-08-22 19-24-45](https://user-images.githubusercontent.com/207405/63535943-ec891200-c512-11e9-9804-c12c891ea8d0.png)

**Comment by williamstein** [comment]
This is 100% on purpose and intentional.  Sorry it annoys you.

**Comment by williamstein** [comment]
I've rolled this into #3781
