### ISSUE TITLE
sagews2html: export gif animations

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4036]
this code in  a sagews

```
sines = [plot(c*sin(x), (-2*pi,2*pi), color=Color(c,0,0), ymin=-1, ymax=1) for c in sxrange(0,1,.2)]
a = animate(sines)
a.save('sines.gif')
salvus.file('sines.gif')
```

generates and shows a .gif animation. exporting via sagews2html shows the axes of the graph, but no animation. weird.

PR: https://github.com/sagemathinc/cocalc/pull/4035

**Comment by williamstein** [comment]
This works now, fixed in #4035 , though it also shows the output twice.

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/16278e5a-195b-4e5c-8f5f-793ebef3a2c8">
