### ISSUE TITLE
enable enforcing idle timeout for cocalc-docker

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4041]
Right now in src/smc-hub/compute-server.coffee there's this code:
```
init_mintime = (cb) ->
    if program.single
        winston.debug("init_mintime: running in single-machine mode; not initializing idle timeout")
        cb()
        return
    setInterval(kill_idle_projects, 3*60*1000)
    kill_idle_projects(cb)
```

Cocalc-docker's compute server is indeed run with this single option:
```
root@ce336e8e1311:/var/log# grep init_mintime compute.err
2019-08-28T21:09:10.493Z - debug: init_mintime: running in single-machine mode; not initializing idle timeout
root@ce336e8e1311:/var/log# ps ax |grep compute
   117 ?        S      0:00 python /cocalc/src/smc-hub/scripts/compute --host=localhost --single start
   126 ?        Sl     0:01 node run/compute.js --host=localhost --single start
  4691 ?        S+     0:00 grep --color=auto compute
```

This means the idle timeouts on projects are not enforced.  This could be viewed as a "feature" -- no limits!  However, some customers of cocalc-docker would obviously prefer to have an idle timeout feature as an option.   So we should have a way of toggling this.  

This is a bug, since projects advertise having an idle timeout in the UI.

**Comment by crockeea** [comment]
Without an idel timeout, there's effectively a memory leak: as users create and open projects, those projects stay running forever. Eventually the server runs out of memory, and the web UI becomes unresponsive.

**Comment by williamstein** [comment]
Right now projects say " About 30 minutes from now project will stop unless somebody actively edits.".  However, without enabling "commercial" mode in admin settings, there's no way for an admin to increase the idle timeout of projects.  It would be very bad to have this idle timeout with no way to increase it.  So probably the right thing to do is:

- 1. make it so the idle timeout can be edited by admins in the docker image.
- 2. then re-enable it by removing the lines `if program.single [...]` mentioned above.

**Comment by williamstein** [comment]
I plan to work on this issue this week.

**Comment by crockeea** [comment]
What's the status on this?

**Comment by williamstein** [comment]
We haven't had time to work on this yet.

**Comment by williamstein** [comment]
I'm going to simple re-enable the idle timeout.  If you want a project to not idle timeout after 30 minutes, as an admin you can click "Admin Edit..." in project settings and set a different idle timeout -- users doing long computations will likely request this.
