### ISSUE TITLE
the zoom dropdown button is broken in x11

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4044]
1. Create an X11 desktop
2. Click the zoom button.
3. Nothing appears to happen, because the button is under the X11 frame.

This is some CSS/style issue.  Several other dropdown buttons like File work fine.  Probably @haraldschilly  can easily fix this.

**Comment by haraldschilly** [comment]
fixed. this should be in a list of manual checks or these puppeteer front end tests /cc @DrXyzzy
