### ISSUE TITLE
make it possible to set custom software environment for students

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4052]
At present the only way to specify a custom software environment (CSE) is in the "Create New Project..." dialog under "Advanced...".

Instructors need a way to specify CSE for students in a CoCalc managed course. This could be:

* student projects are created with the same environment as the instructor project, and/or
* .course "Configuration" tab allows setting a CSE for students (which would allow changing the environment after some projects have been created)

Reported by Stephanos Matsumoto.

**Comment by haraldschilly** [comment]
There is https://github.com/sagemathinc/cocalc/pull/3133 of which I thought is already merged and deployed. I don't know what it actually does, though.

**Comment by williamstein** [comment]
It was an attempt to implement it, but it is disabled.  Maybe it didn't work?

https://github.com/sagemathinc/cocalc/pull/3133/files#diff-286fc0733949d1ce58eb7d397ae1500eR178

@johnjeng disabled it for no apparent reason in this mysterious commit:  https://github.com/sagemathinc/cocalc/commit/ebae1546767799e3fc95ecdeb0c98e113c5d5f48

**Comment by williamstein** [comment]
We should enable and test :-)

**Comment by williamstein** [comment]
Also #3133 was for setting the "Software Environment" (as in project settings, which has been around for 1 year+), whereas here you are asking for setting the "3rd party software environments" (which is a new thing you only do when creating the projects, and can't change later).

**Comment by williamstein** [comment]
I'm sure this is already implemented and live for a long time.
