### ISSUE TITLE
Edge 18: cocalc doesn't load

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4056]
while testing in browserstack, I noticed that cocalc is broken on edge 18

---

**once this is solved** revert https://github.com/sagemathinc/cocalc/pull/4057

---

that's the version info from within the settings dialog

![Screenshot from 2019-09-02 16-10-20](https://user-images.githubusercontent.com/207405/64120507-ac405400-cd9c-11e9-9eb5-54f44495d212.png)

console

![Screenshot from 2019-09-02 16-12-05](https://user-images.githubusercontent.com/207405/64120516-b2363500-cd9c-11e9-9736-3c2727c20e5d.png)

and when I click on the line/char link to open where the error is, I get this

![Screenshot from 2019-09-02 16-12-54](https://user-images.githubusercontent.com/207405/64120538-be21f700-cd9c-11e9-9e55-b5b7440b4196.png)

we should at least adjust the preflight check...

**Comment by haraldschilly** [comment]
Feels like ages, but I think I found the offender: `smc-util/node_modules/url-regex/index.js`. This is used to check if text contains URLs, i.e. that spam protection. Is there a way to fix this right where the lib is imported?

**Comment by williamstein** [comment]
I'll fix this.
