### ISSUE TITLE
change payments to Stripe js and Elements for simplified PCI DSS compliance 

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4058]
See https://stripe.com/docs/security#validating-pci-compliance

> For users that have developed their own integration and are using either Checkout or Stripe.js and Elements to collect card details from customers, you are eligible for the simplest method of PCI validation: SAQ A. Stripe automatically creates a combined SAQ A and Attestation of Compliance (AoC) for you, available for you to download in your account’s compliance settings, and no action is required on your part to submit further proof of your PCI compliance.

Stripe Elements Overview: https://stripe.com/docs/stripe-js

**Comment by williamstein** [comment]
how to migrate: https://stripe.com/docs/stripe-js/elements/migrating
