### ISSUE TITLE
jupyter2: can't close help popup window

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4065]
when I run a cell with auch a question-mark for help, it creates such a 50% split window, but there is no "x" to close it.

(chrome 77, I didn't check other browsers)

![Screenshot from 2019-09-07 14-40-53](https://user-images.githubusercontent.com/207405/64475052-cbb0f580-d17d-11e9-91d8-4c8f0bb86240.png)

**Comment by williamstein** [comment]
This works fine for me in Chrome 76 (on Windows 10), though I can sort of see the scroll bar *under* the close X.  

Note that Chrome 77 is not a stable release yet.  The latest stable release is Chrome 76.

![image](https://user-images.githubusercontent.com/1276278/64479393-6d7b1700-d16b-11e9-9e70-e11e3a247671.png)

This might be related to recent scroll css fixes.

**Comment by williamstein** [comment]
At this point, the right fix is just to implement an introspection frame, and display help there (and make it appear automatically). This is also quite easy now.

**Comment by williamstein** [comment]
If I split the frame vertically (so two copies of jupyter next to each other), then the left hand side doesn't show the X to close the introspect display.  Thus this raises the priority of this bug for me a lot.  Plus it's a nice warm up thing to fix.
