### ISSUE TITLE
work through the dozens of `backend.js:1 Warning: componentWillUpdate has been renamed, and is not recommended for use.` messages that we get when loading cocalc after upgrading to react 16.9.0

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4075]
Just do what they say:

```
backend.js:1 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
```

I'm sure it's a good idea!

**Comment by haraldschilly** [comment]
In my other `npm-ci` branch I also updated to this version and additionally got

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Comment by williamstein** [comment]
This is harder than I thought, since the problem is not just deprecation in our code, but in every single package we depend on that uses deprecated code.  E.g., each of the following has componentWillUpdate, which is deprecated:

- react-bootstrap
- react-mentions
- react-redux

We are versions behind with all of them.  Probably react-bootstrap is very hard to upgrade, though the other two are maybe way easier.   

So I'm going to just ignore all these warnings until we upgrade react-bootstrap.    In any case, this is yet another reason to upgrade react-bootstrap.  https://github.com/sagemathinc/cocalc/issues/3782

**Comment by williamstein** [comment]
done long ago
