### ISSUE TITLE
jupyter2/toc: not all headers are included

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4085]
for a markdown cell like

```
x

## foo

### bar
```

only "foo" is part of the TOC. The actual `toc2` jupyter notebook extension includes all headers, such that the TOC is complete.

**Comment by novoselt** [comment]
I've just hit this issue - it seems silly that one has to put headers into separate cells and have lots of vertical space between them just to get table of content working "as expected" ;-) No idea how other systems are handling it, but it seems counterintuitive that headers from different cells are combined nicely, while headers in the same cell are not. And it is very natural to have a subheader right under header.

**Comment by williamstein** [comment]
JupyterLab's toc extension also parses out headers in the same cell, like you want:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/5711dfee-5d47-4ffa-9029-c7cc19cfe413">

Colab still does NOT:

<img width="838" alt="image" src="https://github.com/user-attachments/assets/30cbb009-46ba-4ee6-acd8-f8c69a58ad28">

Obviously, when JupyterLab and Colab make conflicting choices about the exact same design decision, we should go with JupyterLab.  Also, JupyterLab's choice in this case is obviously better.

**Comment by williamstein** [comment]
Oh, vscode also shows all headers like proposed here.  It doesn't distinguish between levels though, which is weird.

**Comment by williamstein** [comment]
Related discussion here about bugs in JupyterLab's parsing to create table of contents: https://github.com/jupyterlab/jupyterlab/issues/16401
