### ISSUE TITLE
Low vertical height windows break UI when file sharing

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#4098]
### Reproduction steps:
Using Chrome Version 77.0.3865.90 on MacOS
1. Open a directory
1. Change the window size to ~half your screen size
1. Check a file
1. Click share...
1. Check the "Public" radio button
1. Try to scroll

### What happens: 
All the stuff above the file listing disappears (actually it moves up???)
And you become stuck, unable to scroll.
<img width="1313" alt="Screen Shot 2019-09-23 at 2 29 52 PM" src="https://user-images.githubusercontent.com/618575/65464491-c656da80-de0e-11e9-86c6-510cd62b4eb1.png">

### What should happen:
Those things should stay where they are.
You should be able to scroll down and see your file listing.
<img width="1440" alt="Screen Shot 2019-09-23 at 2 30 23 PM" src="https://user-images.githubusercontent.com/618575/65464505-ce167f00-de0e-11e9-99ec-94622166d24c.png">

**Comment by DrXyzzy** [comment]
I see it with Safari, too. macOS 10.14.3, Safari 12.0.3.

**Comment by williamstein** [comment]
That share panel is now scrollable.
