### ISSUE TITLE
some rmd clean-up

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4112]
1. Remove the "reload" button from the main editor, which was incorrectly added by me (william) long ago.

2. Copy something from [here](https://bookdown.org/yihui/rmarkdown/pdf-document.html) to explain how to generate PDF output, and display that in the PDF output frame if there is no pdf output.

3. Fix this traceback:
```
Uncaught (in promise) TypeError: this.props.actions.update_pdf is not a function
    at t.<anonymous> (smc-0bc94895239bd2f83440.cacheme.js?0bc94895239bd2f83440:5)
    at smc-0bc94895239bd2f83440.cacheme.js?0bc94895239bd2f83440:5
    at Object.next (smc-0bc94895239bd2f83440.cacheme.js?0bc94895239bd2f83440:5)
    at o (smc-0bc94895239bd2f83440.cacheme.js?0bc94895239bd2f83440:5)
```

**Comment by haraldschilly** [comment]
bonus: adding a "build" button like for the latex editor, to trigger a build at any time would be cool, too.
