### ISSUE TITLE
jupyter2: lines next to TOC

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4115]
I guess this is antd related. Nothing, or just some nested numbering, is what I would expect here.

![Screenshot from 2019-09-28 12-57-08](https://user-images.githubusercontent.com/207405/65815427-98e3a580-e1ef-11e9-930a-d8ab15c6b0cd.png)

**Comment by williamstein** [comment]
I already implemented nested numbering - it's in master and test but not prod yet.
