### ISSUE TITLE
terminal/x11: tell matplotlib how to draw

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4120]
matplotlib has different backends to actually draw the plot.

In a plain terminal, one wants it to plot without a graphical interface (i.e. "Agg" for png plots). 

In the terminal for the X11 desktop, one would like to use "TkAgg", such that `plt.show()` actually opens up the interactive window.

This can't be solved by a global setting, as far as I can tell. So, the point of this ticket is to set the `MPLBACKEND`  env variable for the x11 terminal to `TkAgg` and to `Agg` for the usual terminal. ← **attn**, this isn't tested yet, but something like that should do the trick.

Ref: https://matplotlib.org/faq/usage_faq.html#what-is-a-backend

---

**workaround** before importing pyplot, you can explicitly tell matplotlib what to do. i.e. in a plain terminal, run this in a fresh python shell:
```
import matplotlib
matplotlib.use('SVG')
```

**Comment by haraldschilly** [comment]
ok, testing this in https://github.com/sagemathinc/cocalc/pull/4121 … I think that's actually a matplotlib bug. they try to be smart for desktop users, but that hurts cocalc as a remote service. anyways, the PR seems to fix this.

**Comment by williamstein** [comment]
I just tested #4121 and it works nicely for me!
