### ISSUE TITLE
sagews output blocks flicker/re-render quickly

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4126]
core issue: it is not possible to embed a video in a sagews document, because the output of a `%md` markdown cell re-renders all the time and hence the video starts fresh. more general, this means the output is not stable.

To reproduce this, it's actually enough to just eval this:

```
%md
foo

bar bar bar

baz
```

and then select a token like `bar` in the middle. one or two seconds later the selection is gone.

**Comment by williamstein** [comment]
WORKAROUND: Use a Jupyter notebook instead.

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.
