### ISSUE TITLE
ban specific sub release versions of chrome 77

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4136]
due to a bug with websocket in chrome 77 (which will be fixed by a new subrelease today or tomorrow), we have to ban 77 prior to a subrevision.

- [ ] which subrelease actually ?
- [ ] parse `navigator.appVersion` to get it as  an integer 

upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1006243

**Comment by williamstein** [comment]
When we decide to really ban this, we'll remove
```
(window as any).buggyCh77 = buggyCh77;
```
and  the `false &&` from `src/webapp-lib/preflight-checks.ts`.

**Comment by williamstein** [comment]
I'm just going to delete this code. Chrome 77 is ancient history and worst case, people will figure out to refresh their browser.  Also, I greatly reduced what would cause this in the first place.
