### ISSUE TITLE
text under course configuration collaborator policy is confusing

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4143]
Current text in Course > Configuration > Collaborator policy > Allow arbitrary collaborators:

> Every collaborator on the project that contains this course is automatically added to every student project (and the shared project). In addition, each student is a collaborator on their project. If students add additional collaborators, by default they will be allowed. If you uncheck the above box, then collaborators will be automatically removed from projects; in particular, students may not add arbitrary collaborators to their projects.

I don't think it's clear enough that the first 2 sentences describe what happens whether the box is checked or not. And I think we bury the lead, which is the last sentence.

Proposed new wording:

> If this box is checked (this is the default), the owner and any collaborator on this student project may add collaborators to this project. If this box is not checked, any collaborators on this student project will be removed, with the exception of the student, instructor, and TAs. Here "instructor and TAs" means any user who is owner or collaborator on the teaching project, i.e. the project containing the course file.

See also:
- #1490 (closed)
- #1494 (open)

**Comment by williamstein** [comment]
@DrXyzzy -- agreed.    Make a PR?  :-)
