### ISSUE TITLE
window.postMessage event when notebook is loaded

### ISSUE THREAD

**Issue by benchun** [sagemathinc/cocalc#4145]
When loading a CoCalc notebook in an iframe, it would be useful to know from the user's perspective when the loading is complete. This is a request to fire window.postMessage with the project ID when the notebook is loaded, based on the definition of "loaded" that's currently used to record times in the project log.

**Comment by williamstein** [comment]
I implemented this.  Type
```
window.addEventListener("message", x=>{if(x.data.source === 'cocalc-project-log') { console.log(JSON.stringify(x.data.payload))}})
```
in the Chrome dev console to watch the relevant messages.

If you open a Jupyter notebook, there are two messages:
```
{"project_log":{"event":{"event":"open","action":"open","filename":"2019-10-09-173048.ipynb"},"project_id":"ca317c14-18de-4df6-9b71-414c3a8ad462","time":"2019-10-10T00:30:51.630Z","id":"244155e7-003c-4e95-8803-c4c229981d6b"}}
```
and
```
{"project_log":{"event":{"time":1075},"project_id":"ca317c14-18de-4df6-9b71-414c3a8ad462","id":"244155e7-003c-4e95-8803-c4c229981d6b"}}
```
The first is fired when the file *starts* opening, and the second -- with the same id -- updates the result with the time in ms.  We have only ever used this timing information for rough analytics and nothing else, so it's possible it's not useful or what you really want, or you want more detailed information.

Right now every single event that is logged in the project log fires a message, including starting up projects, deleting files, terminal commands, etc.
