### ISSUE TITLE
dropzone bug → update it?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4165]
reason: the stacktrace below points to dropzone

safari: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15`

smc_git_rev: b612379cd2218f31d34a2eb1eab1255c436ffbb2

Date: 2019-10-16 17:05:22.096205

`null is not an object (evaluating 'e.hiddenFileInput.files')`

```
https://cocalc.com/static/0-75b1a24eaac3878d8530.cacheme.js?75b1a24eaac3878d8530:6:5806525
_wrapper@https://cocalc.com/static/smc-75b1a24eaac3878d8530.cacheme.js?75b1a24eaac3878d8530:5:698463
```

**Comment by haraldschilly** [comment]
**ATTN** do not update to react dropzone 3.2.0 because of https://github.com/sagemathinc/cocalc/pull/4197

if you update any of this, make sure to test uploading files with a size of ~50mb or more!

**Comment by williamstein** [comment]
I can also confirm that Dropzone 3.2.0 is definitely buggy.  More precisely, for me the upload never finishes (according to the frontend UI), though the actual file does finish uploading (as verified via sha1sum).   I tested by making this 80B file using Python:
```
open('big-file-80MB.txt','w').write('a'*80000000)
```
It works fine with the 2.x version of Dropzone, and fails with the 3.x version.
