### ISSUE TITLE
Add Mathics and the Mathics Jupyter kernel to CoCalc

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#417]
See

  https://github.com/mmatera/Mathics/tree/jupyter/mathics_kernel

This would provide the option of a very Mathematica-like experience for SMC users.  And it's all free and open source!

**Comment by sn6uv** [comment]
Hi @williamstein, there's also https://github.com/sn6uv/Mathics/tree/jupyter that I'm planning to integrate into the main Mathics project.

**Comment by williamstein** [comment]
Regarding your HN comment "I was planning to inquire about some hosting in a couple of weeks", please don't hesitate to email us at help@sagemath.com

**Comment by sn6uv** [comment]
Continuing our email discussion:

Mathics can be installed with pip:
```
pip install mathics
```
should work (although 0.9 is the first release which has been uploaded to PyPI so it hasn't been tested extensively yet).

Mathics is itself a library. The Jupyter kernel is written by importing the various parts (a parser, expression tree, etc.). The json kernelspec is stored in `setup.py`

```python
kernel_json = {
    'argv': [sys.executable,
             '-m', 'imathics',
             '-f', '{connection_file}'],
    'display_name': 'mathics',
    'language': 'Mathematica',
    'name': 'mathics',
}
```

Installing `imathics` with pip tries to install the kernel automatically (using some of the `jupyter_client.kernelspec` routines). It's a bit of a hack because we need to install `ipython` and `ipykernel` before installing imathics.

> From an SMC terminal you can do pip install --user imathics and also look at /usr/share/jupyter/kernels and maybe suggest what we should put there?

I tried to install mathics/imathics from a SMC terminal but it failed.
```
/$ pip install mathics
Downloading/unpacking mathics
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement mathics
Cleaning up...
No distributions at all found for mathics
Storing debug log for failure in /projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.pip/pip.log
```

Also, that directory appears to be empty? Are you referring to the json kernelspec?

**Comment by haraldschilly** [comment]
@sn6uv does your project have internet/network access? if not, you cannot access pypi.

I'll have a look at this tomorrow. It sounds quite simple to pull this off, actually :-)

**Comment by sn6uv** [comment]
@haraldschilly you're right, lack of network access was the reason.

**Comment by williamstein** [comment]
(1) I enabled network access for your project.

(2) Make sure to include the --user option to pip.

On Wed, Mar 2, 2016 at 12:34 PM, Angus Griffith <notifications@github.com>
wrote:

> Continuing our email discussion:
>
> Mathics can be installed with pip:
>
> pip install mathics
>
> should work (although 0.9 is the first release which has been uploaded to
> PyPI so it hasn't been tested extensively yet).
>
> Mathics is itself a library. The Jupyter kernel is written by importing
> the various parts (a parser, expression tree, etc.). The json kernelspec is
> stored in setup.py
>
> kernel_json = {
>     'argv': [sys.executable,
>              '-m', 'imathics',
>              '-f', '{connection_file}'],
>     'display_name': 'mathics',
>     'language': 'Mathematica',
>     'name': 'mathics',
> }
>
> Installing imathics with pip tries to install the kernel automatically
> (using some of the jupyter_client.kernelspec routines). It's a bit of a
> hack because we need to install ipython and ipykernel before installing
> imathics.
>
> From an SMC terminal you can do pip install --user imathics and also look
> at /usr/share/jupyter/kernels and maybe suggest what we should put there?
>
> I tried to install mathics/imathics from a SMC terminal but it failed.
>
> /$ pip install mathics
> Downloading/unpacking mathics
>   Cannot fetch index base URL https://pypi.python.org/simple/
>   Could not find any downloads that satisfy the requirement mathics
> Cleaning up...
> No distributions at all found for mathics
> Storing debug log for failure in /projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.pip/pip.log
>
> Also, that directory appears to be empty? Are you referring to the json
> kernelspec?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/417#issuecomment-191417658>.
>



-- 
William (http://wstein.org)

**Comment by sn6uv** [comment]
@williamstein Thanks.

I just installed imathics with pip (it took a while because everything got optimised with cython). The install ran fine however:
- `imathics` script didn't start because of jupyter console naming differences
- starting up a Jupyter notebook, the Mathics kernel appeared but the kernel failed to start

I'll do some investigating.

**Comment by sn6uv** [comment]
Update: it looks like pip is installing old versions of libraries (i.e. django 1.7.9, ply 3.7)

**Comment by williamstein** [comment]
On Wed, Mar 2, 2016 at 1:44 PM, Angus Griffith <notifications@github.com>
wrote:

> @williamstein <https://github.com/williamstein> Thanks.
>
> I just installed imathics with pip (it took a while because everything got
> optimised with cython). The install ran fine however:
>
>    - imathics script didn't start because of jupyter console naming
>    differences
>    - starting up a Jupyter notebook, the Mathics kernel appeared but the
>    kernel failed to start
>
> I'll do some investigating.
>

Also, in case you're running jupyter automatically through SMC, make sure
to look at the log file in ~/.smc/jupyter


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/417#issuecomment-191446554>.
>



-- 
William (http://wstein.org)

**Comment by sn6uv** [comment]
Manually upgrading ply and django with pip I got the imathics console to run.

The notebook is still crashing:
```
Traceback (most recent call last):
  File "/projects/sage/sage-6.10/local/lib/python/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/projects/sage/sage-6.10/local/lib/python/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/imathics/__main__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/imathics/kernel.py", line 6, in <module>
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/mathics-0.9/mathics/__init__.py", line 10, in <module>
    import sympy
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/__init__.py", line 37, in <module>
    from .core import *
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/core/__init__.py", line 8, in <module>
    from .expr import Expr, AtomicExpr
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/core/expr.py", line 7, in <module>
    from .evalf import EvalfMixin, pure_complex
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/core/evalf.py", line 9, in <module>
    import sympy.mpmath.libmp as libmp
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/mpmath/__init__.py", line 6, in <module>
    from .ctx_mp import MPContext
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/mpmath/ctx_mp.py", line 47, in <module>
    from sage.libs.mpmath.ext_main import Context as BaseMPContext
  File "sage/libs/mpmath/ext_main.pyx", line 34, in init sage.libs.mpmath.ext_main (/projects/sage/sage-6.10/src/build/cythonized/sage/libs/mpmath/ext_main.c:33254)
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/mpmath/__init__.py", line 6, in <module>
    from .ctx_mp import MPContext
  File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/mpmath/ctx_mp.py", line 49, in <module>
    import sage.libs.mpmath.ext_main as _mpf_module
AttributeError: 'module' object has no attribute 'ext_main'
```

**Comment by williamstein** [comment]
I've seen this before as an incompatibility between Sage's mpmath version
and sympy, I think...

You can make SMC kernels use *either* Sage's python or the Ubuntu system
wide Python (2 or 3).  Look at some of the other kernels in
/usr/share/jupyter for how.



On Wed, Mar 2, 2016 at 3:26 PM, Angus Griffith <notifications@github.com>
wrote:

> Manually upgrading ply and django with pip I got the imathics console to
> run.
>
> The notebook is still crashing:
>
> Traceback (most recent call last):
>   File "/projects/sage/sage-6.10/local/lib/python/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/projects/sage/sage-6.10/local/lib/python/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "build/bdist.linux-x86_64/egg/imathics/__main__.py", line 1, in <module>
>   File "build/bdist.linux-x86_64/egg/imathics/kernel.py", line 6, in <module>
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/mathics-0.9/mathics/__init__.py", line 10, in <module>
>     import sympy
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/__init__.py", line 37, in <module>
>     from .core import *
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/core/__init__.py", line 8, in <module>
>     from .expr import Expr, AtomicExpr
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/core/expr.py", line 7, in <module>
>     from .evalf import EvalfMixin, pure_complex
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/core/evalf.py", line 9, in <module>
>     import sympy.mpmath.libmp as libmp
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/mpmath/__init__.py", line 6, in <module>
>     from .ctx_mp import MPContext
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/sympy/mpmath/ctx_mp.py", line 47, in <module>
>     from sage.libs.mpmath.ext_main import Context as BaseMPContext
>   File "sage/libs/mpmath/ext_main.pyx", line 34, in init sage.libs.mpmath.ext_main (/projects/sage/sage-6.10/src/build/cythonized/sage/libs/mpmath/ext_main.c:33254)
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/mpmath/__init__.py", line 6, in <module>
>     from .ctx_mp import MPContext
>   File "/projects/e97fe694-3ded-4a87-be9b-c9917f4528db/.local/lib/python2.7/site-packages/mpmath/ctx_mp.py", line 49, in <module>
>     import sage.libs.mpmath.ext_main as _mpf_module
> AttributeError: 'module' object has no attribute 'ext_main'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/417#issuecomment-191490996>.
>



-- 
William (http://wstein.org)

**Comment by krishnakumarg1984** [comment]
I'd love to see `mathics` support being added to `cocalc`. Has there been any progress on this front?

**Comment by haraldschilly** [comment]
@krishnakumarg1984 do you know a working kernel? the one that's still available on github as a build error and is 3 years old.

**Comment by krishnakumarg1984** [comment]
@haraldschilly The `Imathics` kernel is not actively developed, but you could simply use [iwolfram](https://github.com/mmatera/iwolfram) kernel instead. `mathics` is just an implementation of the wolfram Language.

**Comment by haraldschilly** [comment]
ok, interesting, good to know!

**Comment by slel** [comment]
Installing Mathics is easy. How does one install iwolfram?

- https://cocalc.com/share/42ce241b-2380-4751-97a1-e47ad3145ce9/Mathics-in-CoCalc.md?viewer=share

**Comment by williamstein** [comment]
I'm closing this, since basically nobody uses mathics (I think Wolfram hired the lead dev or something, which killed the project), and nobody has requested it in support since 2016.

**Comment by slel** [comment]
Wolf Vollprecht now has maintainer rights for Mathics and development is picking pace again.
Massimiliano Matera is making it work with the IWolfram Jupyter kernel.

**Comment by slel** [comment]
Mathics 1.1.0rc1 is up at https://github.com/mathics/Mathics/releases

**Comment by slel** [comment]
Mathics 1.1.0 was released, and can now be pip installed:
```
pip install Mathics3
```
