### ISSUE TITLE
latex: make output-directory configurable

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4173]
generating plots tikz/pgf somehow doesn't work. it's running a command with shell escaping allowed, but it isn't able to find the file. error e.g.

```
Package pgfplots Error: Sorry, the gnuplot-result file 'ep3.pgf-plot.table' could not be found. Maybe you need to enable the shell-escape feature? 
```

removing the output directory from the build command works. The file `ep3.pgf-plot.table` is generated and found.

so, either we figure out how to make pgf plots always work (or anything that uses shell escaping in general) or we add a toggle beneath the build command to make this output dir configurable (and add a bit of explanation next to it)

**Comment by williamstein** [comment]
1. What is a minimal example to reproduce this bug?

2. A third option might be to detect if one of these unfortunate situations (where a package does 'bad/unsafe stuff') happens, and in that case don't use the output directory.

3. Presumably a workaround is to just manually edit the build line to remove the build path. That disables the build path.  Is that how you solved this problem?

**Comment by haraldschilly** [comment]
ad 1: I'll see if I can come up with something similar to above, but this snippet is probably explaining a piece of the puzzle – the `pwd` is the file's directory, not the output dir

```
\documentclass{article}
\usepackage{verbatim}
\begin{document}
\immediate\write18{pwd > shell-escape-out}
\verbatiminput{shell-escape-out}
\end{document}
```

It would be interesting to know if the directory where shell escape runs can be tuned.

ad 2: well, I've no idea how to do this in general. 

ad 3: yes

**Comment by williamstein** [comment]
Your example does not work even with the output-directory option removed from the command line.  The only way I can get it to work is to **also** select the "shell-escape" version of pdflatex (latexmk).  So... how about a completely different proposal:

**Let's make it so when shell-escape is enabled then there is no output-directory option. That's it.**

Is there ever a situation where this problem with output-directory that you're worried about comes up but shell escape doesn't have to be explicitly enabled anyways?

**Comment by haraldschilly** [comment]
well, the basic assumption for the initial case where this was a problem (gnuplot + tikz) and this is to enable shell escape. 

> Is there ever a situation where this problem with output-directory that you're worried about comes up but shell escape doesn't have to be explicitly enabled anyways?

I don't know a case, but I don't see why this could only happen with shell-escape enabled. Disabling it for shell escape mode certainly helps in more than one case.

**Comment by williamstein** [comment]
> I don't know a case, but I don't see why this could only happen with shell-escape enabled.

I could imagine that it is guaranteed (in theory) by the assumptions of the tex processor, as a security measure.  Shell escape could very well be the only allowed way for the language to write to random places in the filesystem...  It seems like it is exactly the sort of security thing that it was designed for.

More questions:

1. What is a minimal example with gnuplot + tikz?

2. If one of our users actually tried your example, it just totally silently fails right now, and it also would have silently failed months ago.  Thus the only way to get it to work is to specifically change the build command dropdown to select the shell escape variant.   Should we instead detect this situation somehow and explicitly suggest to the user to change to the shell escape variant?

**Comment by williamstein** [comment]
Here's a fun example to try in sharelatex to see how much random stuff is laying around:
```
\documentclass{article}
\usepackage{verbatim}
\begin{document}
\immediate\write18{find . > shell-escape-out}
\verbatiminput{shell-escape-out}
\end{document}
```
