### ISSUE TITLE
sagews Run and other buttons not visible if window is narrower than about 950 px

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4210]
Seen on macOS 10.14.3 with Chrome Version 78.0.3904.70 (Official Build) (64-bit).

1. Open a Sage worksheet with width >= 1000 px. Check that the Run button is visible:

    ![sagews-run](https://user-images.githubusercontent.com/528072/68102043-7b60c600-fe96-11e9-8735-e3e0b72d5f9b.png)

1. Narrow the browser window to 950 px width or so. Notice that the Run button disappear:

    ![sagews-no-run](https://user-images.githubusercontent.com/528072/68102066-99c6c180-fe96-11e9-9c3e-d8d53b82b756.png)

    Buttons for Stop, Restart, Toggle input display, Toggle output display, and Delete output also vanish. Some of them come back as large buttons when you narrow the display to 720 px or so, in what looks like the mobile device layout.

**Comment by williamstein** [comment]
This is intentional. It's called responsive design.  Whether it is a good UI is subject to debate...
