### ISSUE TITLE
chat: drag/drop image upload moves buttons up

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4220]
when I drag/drop an image on the chat input box, the buttons on the right suddenly move up, into the preview area. that's weird.

expected: buttons stay where they are.

![Screenshot from 2019-11-07 18-13-02](https://user-images.githubusercontent.com/207405/68411443-ca567600-018a-11ea-9621-27e62c7e2fca.png)

**Comment by williamstein** [comment]
fixed long ago...

![image](https://user-images.githubusercontent.com/1276278/88116979-c2026780-cb6e-11ea-8f10-d3f6272489e1.png)
