### ISSUE TITLE
in kiosk mode many options in the File menu of Jupyter just show a broken screen; these options should probably be hidden

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4229]
1. Shift+click on a jupyter notebook tab to open in a new kiosk popup window
2. Click File --> Download --> Notebook
3. See this forever:

![image](https://user-images.githubusercontent.com/1276278/68702022-de102c80-053c-11ea-8d77-432e326684ab.png)

**Comment by williamstein** [comment]
@haraldschilly any comments about this bug?

**Comment by haraldschilly** [comment]
not really. this banner shows up when something else is about to show up, e.g. in this case the files listing.
