### ISSUE TITLE
juypter2: clicking on collab's avatar should let you jump to their active cell

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4238]
with plain code text editors, you can jump to the line where a collaborator is currently active by clicking on the avatar

with jupyter notebooks, there is also an avatar, but clicking doesn't do anything

expected: jump & focus the cell where the particular collaborator was last active

(and while testing this, I discovered that the avatar never showed up for one of the two users. maybe there is yet another bug to report …)

**Comment by williamstein** [comment]
Yes, this is not implemented.  It will be easier now that we have id's for cell and jump to cell functionality (i.e., the url has id= tagging).
