### ISSUE TITLE
jupyter2: sel_ids.size lags behind actual cell selection

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4244]
I saw this while testing https://github.com/sagemathinc/cocalc/pull/4239/

tracking the value of `this.props.sel_ids.size` in `jupyter/top-buttonbar.tsx`/`render_select_cell_type` shows that it lags behind the actual selection. [edit: I should add I selected a cell by clicking on the left, then while pressing the shift key, pressed the arrow-down/-up buttons]

it's expected to change the type of the cell type dropdown to "multiple", when that size value is more than 1. however, when I select two cells, the size is still 0. selecting 3 cells it jumps to 2. ... and vice versa, shrinking from 5 to 4 and it says 5. So, something odd is going on.

**Comment by williamstein** [comment]
This is the sort of thing that could be caused by a shouldComponentUpdate mistake...

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/cocalc/issues/4250 which is my comment that the entire thing we're doing here is wrong anyways.

**Comment by williamstein** [comment]
This refers to functionality (showing the selected cell type) that no longer exists.
