### ISSUE TITLE
Jupyter notebook: do better showing cell type when you select several cells

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4250]
1. Open a jupyter notebook
2. Make two code cells.
3. Select *both* (e.g., click on one, then shift click the number on the other to select both).
4. What happens: The cell type dropdown shows "-".  What should happen: it should show "Code", since both are code cells.

What should happen in general: only show the "multi" (horizontal line) option when there really is more than one type of cell that is selected.     Otherwise, show the type that is actually selected.  This just gives strictly more useful information.

NOTE: the behavior of Jupyter classic is exactly like CoCalc now, and the behavior of JupyterLab is like what I'm requesting.  So this is a very reasonable change to make, since the JupyterLab devs made **precisely** this change.  Screenshots from JupyterClassic and JupyterLab below:

Classic:

![Screenshot 2019-11-25 at 8 16 07 AM](https://user-images.githubusercontent.com/1276278/69557762-fe3be480-0f5b-11ea-9653-0b8c2062e310.png)

Lab:

![Screenshot 2019-11-25 at 8 15 38 AM](https://user-images.githubusercontent.com/1276278/69557764-fe3be480-0f5b-11ea-891e-af76c0efb04e.png)
![Screenshot 2019-11-25 at 8 15 32 AM](https://user-images.githubusercontent.com/1276278/69557766-fed47b00-0f5b-11ea-814e-a4a307288815.png)

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/cocalc/issues/4244 which suggests a bug in the current code anyways (but this #4250 should be implemented rather than fixing the bug #4244).

**Comment by jasongrout** [comment]
Indeed, in JLab we first look at the active cell, then if any other selected cell is a different type, the value becomes `-`: https://github.com/jupyterlab/jupyterlab/blob/78e7bf2d6848fe22f2b59200c832e60f83b6ad22/packages/notebook/src/default-toolbar.tsx#L272-L284

**Comment by williamstein** [comment]
We do not show cell type info anymore.

**Comment by williamstein** [comment]
This sort of context sensitive menu far away from the cursor is a bit of an antipattern in 2024, imho.   It's the sort of thing one did due to overall UI limitations long ago.
