### ISSUE TITLE
in Safari, long chat window that contains an image bounces up a few lines when navigating to bottom

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4254]
1. Create a chat file with one screenful of content.
1. Insert an image.
1. Add another screenful of content.
1. Add a final line of chat.
1. Open the chat in a Safari browser on MacBook or iPad Pro and click `Bottom` or scroll to bottom.
1. Observe that window bounces up by a few lines and will not stay scrolled to bottom.

Example is [this non-public page](https://cocalc.com/projects/4cf7a503-e031-474c-82f4-cf46660067ec/files/TESTS/chat-bounce.sage-chat).

**Comment by williamstein** [comment]
Just to be clear, this does not happen with that test page using Firefox or Chrome?

A quick fix would probably be to just disable react-windowed for Safari for us. Safari traditional tends to be weirdly broken, so it would be slower but work to just fallback to non-react-windowed for now but only on safari.

**Comment by DrXyzzy** [comment]
Yes, it does NOT happen with Chrome or Firefox (on macOS).

**Comment by DrXyzzy** [comment]
This is still a problem. On iPad (with latest iOS as of 2020-09-03), as you'd expect, it occurs with both Chrome and Safari. So chat is unusable on iPad, once the file is long enough and has images.
