### ISSUE TITLE
default font size is different for normal text and blockquote in share server rendering of html

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4255]
See this shared HTML file:

https://share.cocalc.com/share/4cf7a503-e031-474c-82f4-cf46660067ec/TESTS/quote-sample.html?viewer=share

When I view it in Chrome, Safari, and Firefox, font size for ordinary text is 14px, but for blockquoted text it is 17.5. Is that intentional? It looks odd to me.

**Comment by haraldschilly** [comment]
funny, I was wondering the same today, for the preview in the markdown editor. I tracked it down to a css config, which we should probably override. well, different problem. the share server has its own css config.

**Comment by williamstein** [comment]
This is not a bug, both in the case @DrXyzzy is complaining about and in the case @haraldschilly is pointing out..  This is just one of hundreds of official bootstrap "typography" choices.   Look at the example in [the bootstrap3 docs](https://getbootstrap.com/docs/3.3/css/#default-blockquote) (https://getbootstrap.com/docs/4.0/content/typography/#blockquotes) or the source code:
```
blockquote {
  padding: 10px 20px;
  margin: 0 0 20px;
  font-size: 17.5px;
  border-left: 5px solid #eeeeee;
}
```

In [bootstrap4](https://getbootstrap.com/docs/4.4/content/typography/#blockquotes) they made block quotes even bigger!

![image](https://user-images.githubusercontent.com/1276278/70573586-1c5a3500-1b57-11ea-9627-e70fcffb0f12.png)

I think given any css style framework there will be hundreds of choices of parameters, which are supposed to be made based on some sort of global design thinking.  Taken in isolation, individual choices may seem weird.   But so long as we're using bootstrap, it is not a bug that some CSS is styled using bootstrap.

I am happy to report that it appears that antd leaves the font size of the html blockquote tag alone:

https://github.com/ant-design/ant-design/search?utf8=%E2%9C%93&q=blockquote&type=

So when we finish switching to antd and remove bootstrap.css, then this particular font size change goes away.
