### ISSUE TITLE
local images appear as broken image links in shared md and html files

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4256]
1. Create an image file `foo.png` and share it as `Public (listed)`.
1. Create a .md file in the same folder with the following line.
    \<img src="foo.png"\>
1. Note that the image appears in the rendered version of the .md file in the CoCalc editor window.
1. Share the .md file. Note that the image appears as a broken image link on the share server:
    <img src="nofile.png">
1. Repeat steps 2-4 with an .html file instead of .md.

**Comment by williamstein** [comment]
Do you have an example shared file where this is happening?

**Comment by williamstein** [comment]
I CANNOT reproduce steps 1-4 above.  When I do 1-4, in step 4 the image is not broken.  Maybe you made a typo or there was some weird caching issue.

**Comment by DrXyzzy** [comment]
I can't reproduce the problem now, either. One example was this file. But the local image link works on the share server now. https://cocalc.com/share/4cf7a503-e031-474c-82f4-cf46660067ec/TESTS/center-image.md?viewer=share

**Comment by williamstein** [comment]
> I can't reproduce the problem now, either. 

Maybe there was some confusion with when the share server gets updated...
