### ISSUE TITLE
jupyter2: improve plot.ly plotting

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4259]
This is a meta ticket for improving cocalc's support for plot.ly in jupyter notebooks.

* [ ] there should be a cocalc renderer, which is selected automatically. probably a clone of colab should work fine. ticket: https://github.com/sagemathinc/cocalc/issues/4258

emulating embedded plot.ly plots by switching to the colab renderer has two issues:
* [ ] there is a "load viewer..." button to load the iframe. I don't want to click it all the time. Just show the plot!
* [ ] the embedded iframe has a fixed height and we end up with up to three scrollbars. not pretty! the goal here is to somehow "extract" the supposed height of that iframe (backend, I guess) and propagate that information to the frontend. This is a more general issue than just plot.ly, because I think this applies to all embedded iframes with a given height. (alternatively, I was thinking about measuring the height of the embedded frame, but I'm not sure if this is possible ...)

example code:

```
import pandas as pd
import numpy as np
import plotly.io as pio
pio.renderers.default = 'colab'
import plotly.express as px
import plotly.graph_objs as go
data = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
px.scatter(data, x='A', y='B')
```

![Screenshot from 2019-11-28 19-39-37](https://user-images.githubusercontent.com/207405/69827253-d9bf6100-1216-11ea-82de-5397453be3e8.png)

**Comment by jkitchin** [comment]
This may belong in this issue. plotly widgets are not supported yet in cocalc.

![image](https://user-images.githubusercontent.com/1610070/107127097-cc255280-6881-11eb-8326-a95871249ce9.png)

**Comment by williamstein** [comment]
I just checked and none of the problems harald listed still exists.

@jkitchin cocalc-jupyter doesn't support third party widgets at all yet.  https://github.com/sagemathinc/cocalc/issues/5421
