### ISSUE TITLE
account/subscriptions: missing title in listing

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4260]
The list of subscriptions and course packages in the account subscription tab doesn't say which plan or subscription it is. I find that quite confusing... it's  good to show the price, but only the price? IMHO it should also spell out the name of what this is. It could be a two-liner: in the first column the name as the first thing, below the price and duration in brackets.

example:

![Screenshot from 2019-11-28 22-32-18](https://user-images.githubusercontent.com/207405/69832536-3dee1f00-122f-11ea-9954-5ed8f08d8787.png)

**Comment by williamstein** [comment]
deprecated
