### ISSUE TITLE
jupyter raw view sometimes gets stuck loading

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4299]
My fix for #4265 doesn't really work...

1. Open a jupyter notebook
2. Switch the frame to RAW Json editor (or split and show that)
3. You may just seeing loading until you actually change the live jupyter notebook in some way.   

I.e., the initial update doesn't seem to cause the loading to go away.  Ugh.

**Comment by haraldschilly** [comment]
works fine, IIRC you fixed this a while ago

**Comment by williamstein** [comment]
Yep it was fixed when rewriting with hooks.
