### ISSUE TITLE
limit the subject line of "help" support requests to ~200

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4303]
Long subject lines in the help interface a cut off. Limit it to 200 characters and if it exceeds, explain that the message should go into the message box below.

**Comment by williamstein** [comment]
As a workaround, you can see the full text by hovering over the subject line in the list of all open issues...

**Comment by williamstein** [comment]
I'm going to fix this but NOT by limiting the subject line.  People started making long subjects *ONLY* when I pre-filled in the body, which everybody now ignores.  So the solution is to not pre fill in the body.
