### ISSUE TITLE
PR 4304 breaks %auto

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4315]
https://github.com/sagemathinc/cocalc/pull/4304 breaks %auto.  Fix it.

Reported by users...

**Comment by williamstein** [comment]
Just to clarify:  I fixed that %auto bug. It was some really subtle race condition in some tricky code I wrote; in theory it could easily have been triggered with the old code. I think maybe the new code (PR #4304) is just faster or something, and it makes this race condition always get hit, but before it could have been hit sometimes.

6 minutes ago
This would have been very, very difficult for anybody but me to debug, because the code is pretty confusing/reactive...

**Comment by haraldschilly** [comment]
ah, that explains why sometimes it did work during my tests (I thought I was running the code that's live, not the newer one for testing)

**Comment by williamstein** [comment]
Now all fixed.
