### ISSUE TITLE
implement email address verification

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4318]
I disabled email verification for cocalc, since there seemed to be  [tons of bugs](https://github.com/sagemathinc/cocalc/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+verification),  and we didn't really, *really* need it for anything.

This  needs to be fixed since we now have limited site license functionality, which depends on an email address. 

Regarding how it works, I think we should:

- automatically count email addresses that come from single sign on (google, etc.) profiles as valid.
- only have the validation flow for other emails.

Also, a lot of attempts to validate will fail due to the messages being labeled as spam, since we know that happens already with password reset messages.  That said, lots of other sites have working email verification... so how does it work without being broken?

**Comment by haraldschilly** [comment]
>  tons of bugs

one of these is about a jupyter notebook? others apply to sending emails in general, not just email verification. I should probably edit the tickets. What I still don't know is why it was broken in the first place leading you to disable it and well, I also have to figure out how it was actually disabled.

**Comment by haraldschilly** [comment]
>  a lot of attempts to validate will fail due to the messages being labeled as spam, since we know that happens already with password reset messages. 

the main problem is that we do not verify email addresses and therefore send emails to invalid addresses. that harms the overall quality score of emails we send and that's causing our provider to bundle us with lower quality senders and at the side of email services, downgrade us as well. other sites proactively verify emails addresses very early to avoid this.

besides that, I'm curious what data you have to claim that there are a lot of password resets being classified as spam. I don't have that information.

**Comment by williamstein** [comment]
> besides that, I'm curious what data you have to claim that there are a lot of password resets being classified as spam. I don't have that information.

The only data I have is just that when I search zendesk/my email for "password reset", there are about 20 threads per month, sometimes complaining that they never received a reset message.  However, when we directly (using gmail or zendesk) interact with that same user they always get our messages. That's the only data I have; nothing else.

It could be that the entire solution to this problem is that you just re-enable email verification and it "just works".  It's possible.  

Also, I changed my site license code (and whole approach, in fact) to no longer involve the email adddress, so this is less relevant now.

**Comment by williamstein** [comment]
> I'm curious what data you have to claim that there are a lot of password resets being classified as spam.

They tend to just role in.  Here's one from a user today: 

> "I never got the email from the forgot password exercise (I have no spam filter) and so I am sending this email."

I don't know any way around this sort of problem, except setting up something that isn't sendgrid for password resets and account verification, at least.  We could have two different email providers, I suppose.
