### ISSUE TITLE
safari only: jupyter notebook jumps vertically after manual scrolling

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4320]
Seen on macOS with Safari Version 12.0.3 (14606.4.5). NOT seen with Chrome Version 79.0.3945.117 (Official Build) (64-bit) or Firefox 72.0.1 (64-bit).

Also seen on iPad Pro with Chrome 79.0.3945.73

- Open the following Jupyter notebook with Sage kernel, which has three cells with calls to `plot()`: https://cocalc.com/projects/77a92d07-c122-4577-9c4c-c051379cacfe/files/ISSUES/jump.ipynb?session=default

- Scroll manually to bottom of notebook. I am using trackpad on macOS and touchscreen on iPad to see the problem.

- Observe that notebook jumps from bottom of notebook up about half a screen.

This is similar to #4013, except that bug was seen with Chrome on macOS as well as with Safari.

Reported by Isaac Fisher.

**Comment by williamstein** [comment]
I think/hope that a quick fix for this would be to completely disable react-window on Safari, since it's purely an optimization....

**Comment by DrXyzzy** [comment]
Also reported by Cristina Callejon Maleno.

**Comment by DrXyzzy** [comment]
Note: I do NOT see this problem with Safari on macOS in CoCalc chat. No jumping after manual scroll to bottom of large chat file (past 3 monthly team chats), also not in lengthy side chat for a .term.

**Comment by williamstein** [comment]
Some users also see this on Firefox, so I'm also disabling it there.  If you want windowed very long jupyter notebooks you have to use Chrome.
