### ISSUE TITLE
Make active_file_sort in ProjectStore memo-izeable

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#4326]
`active_file_sort` returns new javascript object every time it's called. That means you can't check if it's the same value (without looking deeper), defeating any performance optimizations that using immutable.js is all about.

Related: #4325

**Comment by williamstein** [comment]
@johnjeng did your PR fix this?

**Comment by johnjeng** [comment]
This is fixed but #4325 is not.
