### ISSUE TITLE
chat preview is wrong -- it sometimes strips out more than will be rendered once submitted.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4329]
These two images show how to reproduce the problem.

![2020-01-17 11_31_31-🏡 😀 CoCalc Omnibase - CoCalc](https://user-images.githubusercontent.com/1276278/72640633-23761f00-391d-11ea-90b4-c217cd73a5ef.png)

![2020-01-17 11_31_45-🏡 😀 CoCalc Omnibase - CoCalc](https://user-images.githubusercontent.com/1276278/72640646-28d36980-391d-11ea-9a15-15ee25db9e68.png)

SOLUTION: Why not use **exactly** the same code to render the preview as actual messages?

**Comment by haraldschilly** [comment]
still the case as of today

![Screenshot from 2020-06-20 22-17-24](https://user-images.githubusercontent.com/207405/85210862-dcfd7400-b343-11ea-82c2-1594f87bce04.png)

**Comment by williamstein** [comment]
This is #3206.

The right way to fix it will be to make the new markdown editor component do the preview, and do it correctly.

src/smc-webapp/editors/markdown-input/component.tsx
