### ISSUE TITLE
can't close jupyter error messages

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4330]
e.g. when this message pops up, the close-x is behind the text and there is no way I can close it. it would be much better if this is across the whole width (text doesn't stick out) and/or 
the text is pre formatted with wrapping, and of course, the close X is above and not below the text.

![Screenshot from 2020-01-18 10-51-12](https://user-images.githubusercontent.com/207405/72661952-f55a1300-39e0-11ea-91fd-75154e8df53d.png)

**Comment by williamstein** [comment]
This is actually our more generic `ErrorDisplay` component, which is used in many places.  So fixing this bug will be even more positively impactful.

> and/or the text is pre formatted with wrapping

The error display is pre because frequently errors must NOT get wrapped or they will be mangled (because the message must be displayed pre).

**Comment by williamstein** [comment]
Switched to using antd's Alert which has its own proper close x, a scrollbar if necessary (due to pre), and a margin to prevent overlap:

![image](https://user-images.githubusercontent.com/1276278/72671781-5e06b700-3a04-11ea-9a6a-2cceac711020.png)
