### ISSUE TITLE
Push all handouts/assignments to new students

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#4340]
When adding students to a course in progress, it would be useful to have a single button-push to "catch them up" by pushing out all handouts and assignments that have been pushed to at least one student so far.

**Comment by williamstein** [comment]
Now implemented via a button at the bottom of the panel for the student and also the bottom right in course configuration:

![2020-01-23 17_08_08-course support - CoCalc](https://user-images.githubusercontent.com/1276278/73037196-fafd9180-3e02-11ea-8cae-fd031554f968.png)

![2020-01-23 17_07_50-Weather](https://user-images.githubusercontent.com/1276278/73037197-fafd9180-3e02-11ea-8d01-da07a98294f4.png)

**Comment by kedlaya** [comment]
That looks great, thanks!

Kiran
