### ISSUE TITLE
Small generic CoCalc API wrapper?

### ISSUE THREAD

**Issue by matthew-brett** [sagemathinc/cocalc#4347]
Sorry if I missed it - I probably did - but I have need for a CoCalc API wrapper, and could not see one, and wrote my own:

https://gist.github.com/6da0d785e74644fd9cc3953a080aa027

Is it worth making something like this available in a repo somewhere?   With tests adapted to something that doesn't need my user details / assumes my project details?

**Comment by haraldschilly** [comment]
well, yes, I propose this could be in a repo like `sagemathinc/cocalc-python-api`

**Comment by haraldschilly** [comment]
ok, I created https://github.com/sagemathinc/cocalc-python-api ... at the moment zero content, but it's worth to start somehow :-)

**Comment by williamstein** [comment]
closing this; something based on the new openapi spec makes more sense: https://cocalc.com/api/v2

@schrodingersket
