### ISSUE TITLE
move smc-util/client.coffee to smc-webapp/client/[bunch of files] and rewrite it in typescript

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4350]
I've tried and failed to do this before, since smc-util/client.coffee (one of the first ever files I wrote) is a 2000-line monstrosity.    One thing I thought when I originally wrote it is, is that it would be used by both the frontend (browser) and backend (project), but this is NOT the case, which is why this should be moved to smc-webapp.     What is used is a common interface that they both have, but that is it, and that can be expressed as a typescript interface anyways.

I tried doing this once before, spending about a day on trying to do the whole thing at once, and it blew up in my face, and I gave up.   Thus I think the way to do this is to take bits of functionality in client.coffee and rewrite them as a standalone function/code in smc-webapp/client/, then call out from client.coffee to that new typescript code.    Do this until client.coffee gets small, and then do the actual removal.

MOTIVATION: @haraldschilly got totally stuck [here]( https://github.com/sagemathinc/cocalc/pull/4337#issuecomment-579972752),  in a situation involving code in client.coffee, and if client.coffee were in typescript, he would have instantly known what was wrong.  Typescript is just so damn good.

**Comment by haraldschilly** [comment]
hmm, I think that's done?

**Comment by williamstein** [comment]
Yes, I did exactly this!
