### ISSUE TITLE
API query for project status returns state "running" for stopped project

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4355]
I expect state for a stopped project to be reported as "stopped", per the project fsm diagram in [smc-util/compute-states.js](https://github.com/sagemathinc/cocalc/blob/3fcb3ede091807033df1b3eee10465c0c3d9442e/src/smc-util/compute-states.js#L25). But, the following query returns state "running", even when the project is stopped or archived:

    curl -u sk_....: \
      -H "Content-Type: application/json" \
      -d '{"query":{"projects":{"project_id":...","status":null}}}' \
      https://cocalc.com/api/v1/query
    ==>
    {
        "query": {
            "projects": {
                "project_id": "....",
                "status": {
                    "cpu": {
                        "usage": 10.654506361
                    },
                    "time": 1580332569553,
                    "state": "running",
                    "memory": {
                        "pss": 125010,
                        "rss": 0,
                        "uss": 124568,
                        "swap": 0,
                        "cache": 292,
                        "count": 3,
                        "limit": 1024000
                    },
                    "disk_MB": 10,
                    "assigned": null,
                    "raw.port": 36568,
                    "oom_kills": 0,
                    "processes": {
                        "count": 4
                    },
                    "secret_token": "....",
                    "local_hub.pid": 31602,
                    "local_hub.port": 36704,
                    "sage_server.pid": false,
                    "sage_server.port": false,
                    "console_server.pid": false,
                    "console_server.port": false
                }
            }
        },
        "multi_response": false,
        "event": "query",
        "id": "ce6de5f5-70c7-4d74-8c6b-a0e71fe25969"
    }

Note also that doing a query for just project state, without all the other status, as follows, returns an empty result:
 
    '{"query":{"projects":{"project_id":...","status":{"state":null}}}}'

**Comment by williamstein** [comment]
projects.state.state is what matters.  Annoyingly some thing do set projects.status.state, but ignore it.

**Comment by williamstein** [comment]
I'm closing this since the solution is to query for projects.state.state.

**Comment by DrXyzzy** [comment]
For future reference, for a project that is stopped, state.state is "opened":

    curl -u sk_....: \
      -H "Content-Type: application/json" \
      -d '{"query":{"projects":{"project_id":...","state":null}}}' \
      https://cocalc.com/api/v1/query
      ==>
      {
        "query": {
            "projects": {
                "project_id": "....",
                "state": {
                    "time": "2020-01-30T20:16:12.994Z",
                    "state": "opened"
                }
            }
        },
        "multi_response": false,
        "event": "query",
        "id": "67b18634-3a21-4269-84c6-38240c252e8d"
    }
  
Checking state.state at 2-second intervals shows the following transitions: When the project is started, `state.state` goes from "opened" to "starting" then "running". When the project is stopped again, `state.state` goes from "running" to "starting" then "opened".

    opened -> starting -> running -> starting -> opened

**Comment by williamstein** [comment]
> opened -> starting -> running -> starting -> opened

That's definitely a bug in KuCalc (but not in cocalc-docker/cocalc-kubernetes/cc-in-cc dev). Can you make an issue at https://github.com/sagemathinc/kucalc?

**Comment by williamstein** [comment]
Another point: there are several states that can be stopped, including "opened", "archived", "closed", "unarchiving", and "opening"....
