### ISSUE TITLE
add a way to enter basic/standard/premium resources to site license dialog

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4359]
To save time & reduce errors, add a menu to site license creation dialog to populate Upgrades section with per-student resources that are provided by our current course products for Basic, Standard, and Premium subscriptions.

**Comment by williamstein** [comment]
Note that it is not yet clear what the analogue will be.  It'll probably be similar, but without the disk space upgrade.

**Comment by williamstein** [comment]
done long ago
