### ISSUE TITLE
"Discourage" students from moving directories that contain assignments (courses)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#436]
John Perry requests

> e) Forbidding students from moving directories that contain assignments until they’ve been returned. I have a hyper-organized student who moves all his assignments into a directory so labeled, and I’ve been able to find & recover the assignments when this happens, but it’s still a hassle.

Forbidding would be very tricky due to the security model for projects.    However, _discouraging_  it would likely be pretty easy...   And I think that's fine for this particular problem.

**Comment by novoselt** [comment]
Not a popular request.
