### ISSUE TITLE
Improvements to drop-down menu for multi-file latex editing

### ISSUE THREAD

**Issue by crockeea** [sagemathinc/cocalc#4372]
Reopening #4224. I'm using a recent version of CoCalc, but this issue still exists.
![dropdownbug](https://user-images.githubusercontent.com/4899463/73972134-18d3f780-48d5-11ea-9a26-76ff70430218.png)

In the attached image, you can see that several open files appear in the dropdown list, and several others do not. All of these files are included in the main document.

**Comment by crockeea** [comment]
Re-confirmed that this is happening using the cocalc-noagpl image from 2/6/20. It shows some .tex files in the root directory, but not others.

**Comment by williamstein** [comment]
I'm closing this since probably we fixed it, but most importantly this issue does not include the relative files!
