### ISSUE TITLE
Support ijavascript Jupyter kernel (node.js)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4390]
@TylerT in Discord requested this be installed:

https://www.npmjs.com/package/ijavascript

It's a Node.js kernel for Jupyter.  Actually I think we would find this useful too, especially because the node.js command line isn't the best.  I suspect it is challenging to install... but we'll see.

**Comment by haraldschilly** [comment]
Ok, seems to work, I did some tests and the only real thing to learn about it is `$$.async()` and `$$.done()`.

more here: https://share.cocalc.com/share/2b6ef7cc0e2d7fe8c126e1901e44ecc57b1b98e2/javascript.ipynb?viewer=share

already available in "experimental"

**Comment by tylert** [comment]
@williamstein that must have been a different @tylert.  That wasn't me.
