### ISSUE TITLE
"Policies" and "Terms of Service" at bottom of landing page look like links, but don't go anywhere

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4404]
Seen with recent Chrome, Safari, and Firefox on macOS.

1. Open an Incognito/Private window.
1. Browse to cocalc.com.
1. Scroll to bottom.
1. Mouse over "Policies" and "Terms of Service". Note that cursor changes and underline appears, but that clicking does not go to the expected page.

![landing-bottom](https://user-images.githubusercontent.com/528072/74978323-f9b78880-53f1-11ea-8169-b8937eb315db.png)

**Comment by haraldschilly** [comment]
fixed with the new landing pages
