### ISSUE TITLE
jupyter: halt button confirmation

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4413]
the jupyter notebook's "Halt" button stops&closes the notebook without asking a question. Since it is at least as disruptive as restarting the kernel, I would suggest to add a confirmation dialog – or get rid of it for both cases.

**Comment by williamstein** [comment]
> or get rid of it for both cases.

We should not get rid of it because we want to maintain consistency with Jupyter Classic / JupyterLab.
