### ISSUE TITLE
upgrade to mathjax3... but only after they implement automatic line breaking

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4417]
Here is how in a Sage worksheet to get Mathjax to use automatic line breaking, which is definitely very much a key feature for us (with users outputing big expressions):

![image](https://user-images.githubusercontent.com/1276278/75279334-461f1180-57c0-11ea-9638-a5a3898bf379.png)

The input is
```
%md
$$
\newcommand{\abc}{1 x + {(-\frac{1}{6})} x^{3} + \frac{1}{120} x^{5} + {(-\frac{1}{5040})} x^{7} + \frac{1}{362880} x^{9} + {(-\frac{1}{39916800})} x^{11} + \frac{1}{6227020800} x^{13} + {(-\frac{1}{1307674368000})} x^{15} + \frac{1}{355687428096000} x^{17} + {(-\frac{1}{121645100408832000})} x^{19} + \frac{1}{51090942171709440000} x^{21} + {(-\frac{1}{25852016738884976640000})} x^{23} + \frac{1}{15511210043330985984000000} x^{25} + {(-\frac{1}{10888869450418352160768000000})} x^{27} + \frac{1}{8841761993739701954543616000000} x^{29} + \mathcal{O}\left(x^{30}\right)}
\abc
$$
```

The Mathjax page about Mathjax 3 not having automatic line breaking is [here](http://docs.mathjax.org/en/latest/upgrading/v2.html#not-yet-ported-to-version-3).

A big question is whether or not we could eventually switch from Katex (+mathjax as fallback) to just Mathjax 3.   The only functionality we need from Katex is *speed*; the sync support is not a hard requirement, since we fallback to async anyways in case katex fails.  Officially [they claim](http://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html#improved-speed): 

> "in tests that render a complete page with several hundred expressions, we see a reduction in rendering time of between 60 and 80 percent"

80 percent means reducing 10 seconds to 2 seconds, i.e., a speedup of a factor of 5x.
[This page](https://www.intmath.com/cg5/katex-mathjax-comparison.php?processor=MathJax) has a good demo comparing speed of Katex and Mathjax 2, and the speed difference for me is a factor of about 15x.  Thus perhaps katex is still significantly faster than even Mathjax 3.

**Comment by williamstein** [comment]
I've labeled this "upstream" + "blocked" to mean that this ticket shouldn't move forward until Mathjax3 implements automatic line breaking.

**Comment by williamstein** [comment]
Pasting this into a markdown file (ending in .md) renders the big formula in both Mathjax 2 and Katex:
```md
$$
\newcommand{\abc}{1 x + {(-\frac{1}{6})} x^{3} + \frac{1}{120} x^{5} + {(-\frac{1}{5040})} x^{7} + \frac{1}{362880} x^{9} + {(-\frac{1}{39916800})} x^{11} + \frac{1}{6227020800} x^{13} + {(-\frac{1}{1307674368000})} x^{15} + \frac{1}{355687428096000} x^{17} + {(-\frac{1}{121645100408832000})} x^{19} + \frac{1}{51090942171709440000} x^{21} + {(-\frac{1}{25852016738884976640000})} x^{23} + \frac{1}{15511210043330985984000000} x^{25} + {(-\frac{1}{10888869450418352160768000000})} x^{27} + \frac{1}{8841761993739701954543616000000} x^{29} + \mathcal{O}\left(x^{30}\right)}
\abc
$$

$$
1 x + {(-\frac{1}{6})} x^{3} + \frac{1}{120} x^{5} + {(-\frac{1}{5040})} x^{7} + \frac{1}{362880} x^{9} + {(-\frac{1}{39916800})} x^{11} + \frac{1}{6227020800} x^{13} + {(-\frac{1}{1307674368000})} x^{15} + \frac{1}{355687428096000} x^{17} + {(-\frac{1}{121645100408832000})} x^{19} + \frac{1}{51090942171709440000} x^{21} + {(-\frac{1}{25852016738884976640000})} x^{23} + \frac{1}{15511210043330985984000000} x^{25} + {(-\frac{1}{10888869450418352160768000000})} x^{27} + \frac{1}{8841761993739701954543616000000} x^{29} + \mathcal{O}\left(x^{30}\right)
$$
```

The output looks like this:

<img width="648" alt="Screen Shot 2022-01-26 at 9 16 18 AM" src="https://user-images.githubusercontent.com/1276278/151213159-50731827-1a26-4d07-a744-eed8a5fb0553.png">

**Comment by williamstein** [comment]
So... at least as things are configured in CoCalc, it seems KaTeX doesn't implement this line breaking functionality either.

**Comment by blois** [comment]
Possibly https://wordpress.org/support/topic/katex-block-doesnt-break-formulas-into-lines/? If I remove the `white-space: nowrap` from their demo then I do see wrapping.

**Comment by williamstein** [comment]
> Possibly https://wordpress.org/support/topic/katex-block-doesnt-break-formulas-into-lines/? If I remove the `white-space: nowrap` from their demo then I do see wrapping.

I just did this in CoCalc and it works very well: 

https://github.com/sagemathinc/cocalc/commit/e711faa447c31b18e2c4cff476cd7f91abf2b96f

**Comment by williamstein** [comment]
Closing. We've hitched our horse to katex at this point.
