### ISSUE TITLE
hub-api: client → project.read_file → Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4419]
mini stacktrace, from the uncaught exceptions in hubs:

```
TypeError: Cannot read property 'toString' of undefined
 at cb (/cocalc/src/smc-hub/client.js:1620:41)
 at async.series (/cocalc/src/smc-hub/local_hub_connection.js:1292:18) 
```

which happens in local hub connection's `read_file`, the final callback, `cb(false, data)`

then in client.js: `project.read_file` → `cb` → `content: content.blob.toString()`

**Comment by williamstein** [comment]
Sounds like a very old bug?

**Comment by haraldschilly** [comment]
timestamp is `2020-02-26 15:08:08`

**Comment by williamstein** [comment]
This is code that hasn't been touched for a long time, and is indeed an old bug.  Glad you found it.  Basically something times out after a minute, but the code doesn't properly check for an error condition.

**Comment by williamstein** [comment]
Fun fact -- looking at our sources this codepath is only used for showing the past history of a command line terminal when you reconnect and first start the terminal up.  E.g., if you restart your project and refresh your browser, you'll find the terminal history is still there.
