### ISSUE TITLE
disable the jupyterlab build recommended warning, since it is completely pointless and useless

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4424]
1. Try to use JupyterLab in CoCalc (e.g., +new --> JupyterLab server)
2. See

![2020-02-27 16_09_58-JupyterLab](https://user-images.githubusercontent.com/1276278/75499147-043bca00-597e-11ea-8ea7-0f7420b35d17.png)

or some other error.  There is always _something_ wrong like this.  

3. The user will *of course* click Build, and of course that can't possibly work, since it tries to modify files they don't have write access to.  This makes the JupyterLab experience in cocalc very poor.

SOLUTION: Don't show that dialog.  Ways to solve that?

1. The directions [here](https://github.com/jupyterlab/jupyterlab/blob/3d1e5ee94a2df3978018fe632217ad8a66675e28/docs/source/user/extensions.rst#disabling-rebuild-checks) say that we can add a config file somewhere  and the error will go away.   I tried naively in a cocalc project with ~/.jupyter and it didn't work at all. But maybe the version of jupyterlab that we run is too old.

2. The code that shows the dialog is [here](https://github.com/jupyterlab/jupyterlab/blob/869c2bc9a476183e1438ff4b061a54815f76860c/packages/application-extension/src/index.tsx#L179), so worse case scenario we fork or patch the code and remove that dialog.

3. Of course, there's also the possibility that we can get rid of that error, and make a standard part of our integration test to run a command line check that there will be no build recommended warnings.  

4. Make a PR to JupyterLab (or otherwise convince them) to not show the Build recommended dialog if the user does not have write access to their jupyter install.  That would be good for them too, right?

Of course option 3 is by far the best, and 2 is the worst...

@jasongrout

**Comment by haraldschilly** [comment]
5. make jupyterlab "build" work for files in the users home dir / the project.

**Comment by williamstein** [comment]
I haven't seen this in years.
