### ISSUE TITLE
firefox: collab cursor messed up

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4431]
I saw an offset of the cursor of someone else typing in the same markdown document.

**Firefox 73.0.1** in Linux, 100% zoom

![Screenshot from 2020-03-04 20-12-26](https://user-images.githubusercontent.com/207405/75914227-b11db780-5e54-11ea-94f2-023ee1183c31.png)

**Comment by williamstein** [comment]
Still broken in latest version.

**Comment by williamstein** [comment]
i've not seen this lately.
