### ISSUE TITLE
md/rmd preview: remove save and timetravel buttons

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4439]
I don't understand why there are save and time travel buttons in the preview frame of md or rmd files (and possibly others).

* "saving" in that context would mean to save the preview – not saving the sources. could be a different enhancement ticket.
* "time travel"  could only mean to show changes of the preview, not the sources.

![Screenshot from 2020-03-08 11-13-51](https://user-images.githubusercontent.com/207405/76160881-31cb0500-612e-11ea-9bf0-3690d391243e.png)

**Comment by williamstein** [comment]
I disagree.  It's saving the file to disk.  It's showing all versions of the file.  Also it's just "locked" not "preview" anymore, and we have slate so preview is an editor in locked mode.
