### ISSUE TITLE
install vpython-jupyter, if possible

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#444]
Requested by: Henri Girard

> They are two librairies I would like to use vpython :
> https://github.com/BruceSherwood/vpython-jupyter.git
> and ivisual  :
> https://github.com/jcoady/IVisual.git
> Then this public link should work and show an animation of a wave:
>    https://cloud.sagemath.com/projects/1e1bd552-1b18-46e2-841c-d4e34d53f383/files/waveivisualmatplotlib.html

**Comment by aishenri** [comment]
I tried in jupyter notebook input 
!pip install vpython 
or 
!pip install ivisual
but I can't get connected...
Response is connected out

**Comment by aishenri** [comment]
![vec](https://cloud.githubusercontent.com/assets/16356346/13545511/b7917fe8-e28e-11e5-9d32-092e9cbc634a.jpg)
This is the result of cartesian

**Comment by aishenri** [comment]
Following this message forget about it :)
Thanks anyway
Henri
https://groups.google.com/forum/#!topic/sage-support/FX1SDk70hHg

**Comment by aishenri** [comment]
First thanks for access granted.
vpython works fine in a notebook input ( !pip install vpython --user (and after --upgrade) 
ivisual seems to have a problem with a lib but I need further investigating.
!pip install ivisual --user (second time and after --upgrade
But publicly it doesn't display 
https://cloud.sagemath.com/projects/311e59ad-e8d5-4ecf-8eaa-a816aca57070/files/jup.ipynb
This is my project link
Best regards
Henri

**Comment by haraldschilly** [comment]
Hi, when you click "publish" in an ipynb file, you have to share the link to the generated .html file:

In your case, and without the embedding into the SMC UI, the file is this:

https://cloud.sagemath.com/311e59ad-e8d5-4ecf-8eaa-a816aca57070/raw/jup.html

Sill, the scene doesn't show up, so I assume that there is no support for html-rendered scenes.

**Comment by aishenri** [comment]
yes I don't think so too...

**Comment by haraldschilly** [comment]
That's a working link, the one from my previous comment is no longer there...

https://cloud.sagemath.com/projects/20e4a191-73ea-4921-80e9-0a5d792fc511/files/vpython.html

**Comment by zimmermant** [comment]
iVisual will no longer be developed because VPython is switching to Jupyter-only graphics, which makes iVisual redundant

**Comment by haraldschilly** [comment]
we have a vpython kernel and due to supporting the classical notebook (or starting its server directly) we do support vpython. hence closing this.
