### ISSUE TITLE
course: add a config to disable download elements for student projects

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4445]
* goal: hide download specific UI elements in student projects
* it's not possible to prevent downloads, but hiding obvious elements is a clear indicator to not do it
* implementation idea:
  1. course configuration → setting to disable downloads. without knowing any details, I assume this could be similar to the "Allow arbitrary collaborators" checkbox.
  2. this propagates to all student projects. 
  3. the files UI hides the download button on the right of a file and the download and copy button in the file action bar
  4. similarly, hide the download entry in the "file" menu of a frame editor (i.e. for sagews and ipynb files) 

REPORT BACK: ticket 7698

**Comment by williamstein** [comment]
- Should the elements be disabled for *everybody* or just the student or everybody except the owner of the project?  

- Regarding the implementation, this should be another field in the projects.course JSONB object.

**Comment by haraldschilly** [comment]
ad 1: I would implement it for everyone, because if a teacher checks the setting, it would be confusing if it is still there. But I see, there could be reasons to have it only for teachers. hmm...

ad 2: yes

**Comment by williamstein** [comment]
Requested again twice this week.

**Comment by williamstein** [comment]
I was thinking about steps to do this recently and will copy them here:

``
Specifically: customize the student’s IDE to remove certain features like the ‘Download’/’Toggle edit on/off’?

The tasks to do this are:

add a new customization panel to the course management UI for these features
add the two options you listed and ensure they are properly saved to the course
make it so the state of the options are also stored in the student's project course field
make it so each place in the project UI that involves downloading is aware of this new option to disable downloading: in Jupyter itself, in the file listing, in the file actions
make it so the the Jupyter client is aware of these options and disables functionality for editing locked cells
```

**Comment by williamstein** [comment]
OK, so thanks to consulting support from a customer (THANKS!), I've implemented this.  In course configuration it looks like this:

![image](https://user-images.githubusercontent.com/1276278/114499921-ee1db700-9bdb-11eb-89ba-564e3340de95.png)

Regarding the underlying implementation (which did involve quite a bit of code), now that this is done, it would probably be relatively easy to add additional checkboxes to remove additional functionality (e.g., hide certain document types, or maybe eliminate creating new documents entirely?; hide project settings entirely?).

It's also of course entirely possible I missed some edge case somewhere.  If anybody notices, let me know and it'll be easy to fix.
