### ISSUE TITLE
report of chat messages not appearing

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4458]
We have had this report:

1. "Trying to use the built-in chat feature to communicate with students remotely
2. While it often worked and we demonstrators were able to read the student's messages, and vice versa, *sometimes the messages would not appear at all for the other person*, although we do get a notification saying there has been a message
3. Of course, we'd expect to see all messages, not randomly some not being visible"

I don't know how to reproduce this or what causes it to happen (bad internet?  a certain browser? only side chat and react component just isn't updating?)

If anybody sees this and has any data about how to reproduce it or when it happens, please add a comment to this issue.  With any actual real data or hints, this probably won't be hard to fix.

**Comment by haraldschilly** [comment]
update today

> We've been using the service for the last couple of weeks now, and we don't seem to be encountering this issue anymore.
> I guess whatever was causing the problem at the time is probably fixed now by something else with it.
> Thanks again, please feel free to close the ticket.
