### ISSUE TITLE
cannot issue email invitation to collaborators from project list in project upgraded with site license 

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4464]
Reported by Martin Lichtman. Seen on macOS 10.15.3 with Chrome 80.0.3987.149 (Official Build) (64-bit).

1. Upgrade a project with Internet Access using a site license.
1. Open the Projects list.
1. Click the disclosure triangle for collaborators next to the upgraded project.
1. Under "Add people", add an email address that does not correspond to an existing cocalc account.
1. Hit Enter to search for the account.
1. After "Sorry, no accounts found", notice that there is a notice, "Enable the Internet Access upgrade to this project ..." instead of a button to send an email invitation.

![email-invit2](https://user-images.githubusercontent.com/528072/77241537-5957ae00-6bc1-11ea-8d96-ef4936efa1bc.png)

**Comment by williamstein** [comment]
It goes without saying that I'll fix this very soon...
