### ISSUE TITLE
jupyter/firefox: ctrl-shift-"-" doesn't work

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4467]
in a jupyter notebook with my firefox browser, ctrl-shift-"-" should split a cell – but it does nothing.

**Comment by williamstein** [comment]
Other data points:
 - I can reproduce this on Firefox on Windows 10.  Also Ctrl-";" doesn't work either there.
 - This shortcut works fine in Chrome
 - This shortcut works in Jupyter classic on Firefox, so it's not impossible (i.e., blocked by Firefox for something else).
 - And I have absolutely no clue why this doesn't work, but fixing it won't be that hard (just see what codes are emitted in Firefox and add those as another alternative).  The real question is: do any other shortcuts not work?

**Comment by haraldschilly** [comment]
I haven't checked other shortcuts … my feeling is that this is not the only one.  Bascis like "a/b", arrow keys, "x, v, ..." do work in my firefox. So, maybe it has something to do with the Ctrl key?

**Comment by williamstein** [comment]
Here are browser stats for the last week:

![image](https://user-images.githubusercontent.com/1276278/77565768-ecbf0680-6e81-11ea-9b4a-8bf8a2642c33.png)

Conclusion: 
 - We should double check similar things on Safari, since a lot of people use it.
 - Don't worry much about other browsers...

**Comment by williamstein** [comment]
> We should double check similar things on Safari, since a lot of people use it.

control+shift+- works fine in safari.

It is still broken in firefox.
