### ISSUE TITLE
Make SSH easier by generating key within SMC

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#447]
I went to use SSH for X11 forwarding for a quick thing I need a linux GUI for. I got scared off by needing a public key. With Amazon they generated a key for me.

**Comment by williamstein** [comment]
They generate a private key for you which you then put on your laptop???  That seems extremely insecure.    Are you sure?

**Comment by timothyclemansinsea** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#having-ec2-create-your-key-pair

**Comment by williamstein** [comment]
Closing — this is a security mistake, obviously.
