### ISSUE TITLE
incompatibility between ipywidgets in cocalc-jupyter and jupyter-classic

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4472]
1. Create a cocalc-jupyter notebook with a Sage kernel.
2. Create this interact
```
@interact
def f(a="1+1"):
    print(eval(a))
```
3. Save the file to disk
4. Open the same file with Jupyter classic.
5. See this sort of message:
```
Notebook validation failed: {'model_id': 'a75d5f34f775435b91796d35c26c5e66', 'version_major': 2, 'version_minor': 0} is not valid under any of the given schemas:
{
 "model_id": "a75d5f34f775435b91796d35c26c5e66",
 "version_major": 2,
 "version_minor": 0
}
```

![image](https://user-images.githubusercontent.com/1276278/77668415-9cf34480-6f40-11ea-979e-d3803e742287.png)

NOTE: I think this must be a result of upgrading Jupyter or some other dependency, since I was testing this sort of thing a lot when I implemented Jupyter widgets in cocalc-jupyter last year.  Also, we've started getting reports of this only this week.

WORKAROUND: for now, just dismiss the message, since it is harmless.

FIRST REPORTED BY: Valerie Monaco  on March 25, 2020.

**Comment by jasongrout** [comment]
This is from having an old notebook format specified. You're probably creating files with notebook format 4.1? Technically, notebook format 4.1 did not allow arbitrary JSON, so technically storing widget mimebundles was illegal in notebook format 4.1.

It's generating errors now because we recently upgraded the nbformat package to be more strict about checking compatibility according to the spec, where before we accidentally let a lot of non-compliant files through. However, I have a PR into nbformat to retroactively loosen the spec for 4.1, so that these files should be considered compliant (once a new version of nbformat is released).

For more information, see https://github.com/jupyter/nbformat/pull/167.

**Comment by jasongrout** [comment]
Short answer - if you change the notebook format version you are generating to 4.2 or later (most people are generating the most recent notebook format, version 4.4), you'll be good.

**Comment by jasongrout** [comment]
Or another short answer - I've asked for an nbformat 5.0.5 release, and people can upgrade to that, which acknowledges that in the real world, version 4.1 notebooks had this extra structure: https://github.com/jupyter/nbformat/issues/168

**Comment by williamstein** [comment]
Thanks!  Yes, indeed we are currently using:
```
 "nbformat": 4,
 "nbformat_minor": 0
```

**Comment by jasongrout** [comment]
So then the new nbformat release would not help you, as we only retroactively modified format version 4.1, not 4.0.

**Comment by williamstein** [comment]
Well I'm going to change "nbformat_minor" from 0 to 4 in the cocalc code that exports from our internal format to ipynb... and see what happens.     Newly saved notebooks will work fine for people, and all existing notebooks with widgets that people have ever saved with cocalc up until now will be "broken", unless you make a change.

**Comment by jasongrout** [comment]
Thanks. I've opened up the discussion on the issue above about possibly changing format version 4.0 to include this change as well.

When someone opens a notebook and then saves it again in cocalc, will it update the format version? Also, will cocalc itself complain about the technically-noncompliant 4.0 notebooks (I think no, based on the description above)? In other words, is a workaround for cocalc users to open and save this notebook in cocalc after you've made your change?

**Comment by williamstein** [comment]
> When someone opens a notebook and then saves it again in cocalc, will it update the format version? 

Yes.

> Also, will cocalc itself complain about the technically-noncompliant 4.0 notebooks (I think no, based on the description above)?

No cocalc doesn't do any compliance checking and just reads whatever is in the ipynb file on a "best effort" basis.  And if we ever did any checking, we would just automatically solve problems for people, rather than showing an error; we have different user philosophies, namely I want to minimize the number of support requests we have to deal with because they all cost us time...

>  In other words, is a workaround for cocalc users to open and save this notebook in cocalc after you've made your change?

Yes, that should work fine.

**Comment by williamstein** [comment]
That said, a lot of our users use or switch to "Jupyter classic mode", which means they are opening all notebooks in an iframe in jupyter classic and for them switching back to non-classic and forth again is pretty awkward (and could cause trouble for their collaborators).  So it's still awkward.

**Comment by jasongrout** [comment]
> So it's still awkward.

Thanks. We're trying to balance pragmatic considerations with the principles and technical documentation, so having feedback on what is happening with real users is very valuable.

**Comment by jasongrout** [comment]
For future readers - we're discussing this more at https://github.com/jupyter/nbformat/issues/170
