### ISSUE TITLE
make it easier and clearer to stop a project

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4482]
1. Make sure that during the state change from running to stopped, it says "Stopping..." not "Starting...", since that's confusing.

2. There are several events that cause projects to start running, and some are triggered automatically when a project is open at all by a client.  Eliminate **all** of them, making it so the project will not start unless there is an explicit manual click by a user to make it start.  Before doing this, it's critical to ensure the button or switch to start a project is visible at all times from any screen when that project is opened, in order to avoid confusion.

This didn't really matter much before site license codes; however, with licenses, it is important, since the number of projects that can run at once with a given license is limited.

**Comment by DrXyzzy** [comment]
+1. Completing this will make it easier to test license allocation situations. That will help serve customers who are buying several licenses & licenses overlapping in time.

**Comment by williamstein** [comment]
I did this, finally.
