### ISSUE TITLE
"Subscriptions and Course Packages" appears in two nearby places in the GUI

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4483]
One of the tabs under "Account" is labeled "Subscriptions and Course Packages". Inside this tab, one section of the display is labeled "Subscriptions and course packages". That creates ambiguity for documentation and support.

Can we rename the inner section to something like "Subscription list" or "Your subscriptions and courses"?

**Comment by williamstein** [comment]
deprecated
