### ISSUE TITLE
Emails not sending - From address not the configured one

### ISSUE THREAD

**Issue by Drachionix** [sagemathinc/cocalc#4486]
Hi,
I tried to setup email via SMTP - set everything in the admin panel. All the config is saved to the database but not actually used.
If I try to (re)send the verification email I get this error:

Problem sending email verification: error sending email -- {"code":"EENVELOPE","response":"553 5.7.1 <office@sagemath.com>: Sender address rejected: not owned by user *insert here my sender email*","responseCode":553,"command":"RCPT TO","rejected":["*insert here user email*"],"rejectedErrors":[{"code":"EENVELOPE","response":"553 5.7.1 <office@sagemath.com>: Sender address rejected: not owned by user *insert here my sender email*","responseCode":553,"command":"RCPT TO","recipient":"*insert here user email*"}]}

**Comment by haraldschilly** [comment]
looks like there is some setup missing. this configuration isn't fully tested yet. I moved this to the main cocalc repository, because this is not an issue with the docker setup.

**Comment by haraldschilly** [comment]
the patch above changes it so, that the theme's "organization name" and "email" are used for sending. I only tested this briefly, but at least changes there show up as the sender's email address. I don't know what you are running, the change was made yesterday …
