### ISSUE TITLE
iterative webpack building (when developing cocalc) is slow due to a mistake in the typescript fork plugin

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4487]
[this change](https://github.com/sagemathinc/cocalc/commit/d8084c607f33abc92323f0b7602448edc6bae963#diff-6d5e756cc942fd5f521d854dbb7bfe3bL701) made developing of the cocalc frontend via webpack slower by accidentally disabling the typescript for plugin.

WORKAROUND: 
```
git checkout c8c4e86cd7f368fe882a861401485414af0ba474 webpack.config.js 
```

**Comment by haraldschilly** [comment]
we have mid of june, I don't believe this ticket is still relevant
