### ISSUE TITLE
listing: stale after non-existing directory error 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4491]
I had the following situation

1. opened project at a path, which doesn't exists. It showed me a red "Project unavailable" message (I bet that's worth another ticket ...)
2. I created that directory via a course assignment
3. that directory was still showing "Project unavailable" (I guess it doesn't magically check that)

What's more worrisome: I tried that refresh button below, this didn't help. I also navigated back to the home directory and then back down to this directory. I even clicked the link in the files listing to open `assignment1`, but it still showed that error message.

What really helped was to refresh webapp in the browser. 

So, my assumption is there is something cached.

![Screenshot from 2020-04-02 13-36-37](https://user-images.githubusercontent.com/207405/78245316-90925d00-74e7-11ea-8157-9cec87351586.png)

**Comment by williamstein** [comment]
> So, my assumption is there is something cached.

Yes, and I think it will refresh properly after about 45 seconds or a minute. I'm assuming you didn't wait .  

I don't think the new listings code knows about that "Try again... " button.
