### ISSUE TITLE
Let me disable latexindent

### ISSUE THREAD

**Issue by seaneberhard** [sagemathinc/cocalc#4499]
latexident annoys me. On my mac, ctrl+cmd+F is the shortcut for full-screen, and cocalc shift+cmd+F is autoformat. The result is that I often accidentally autoformat my latex document. Since this is a shared document, I end up with lots of unnecessary diffs that I have to manually revert. Please can I have a tickbox that lets permanently disable latexident?

**Comment by haraldschilly** [comment]
this could be solved by being able to customize keyboard shortcuts in general. something that's not possible right now as well.

to undo this more easily, you might want to use [time travel](https://doc.cocalc.com/time-travel.html) and step back 1 step to undo the formatting.

**Comment by seaneberhard** [comment]
Good tip, thanks!

**Comment by williamstein** [comment]
> to undo this more easily, you might want to use time travel and step back 1 step to undo the formatting.

Or just hit control+z to undo, or click the undo button:

![image](https://user-images.githubusercontent.com/1276278/78842311-88896000-79b4-11ea-842d-cd08f77c4d40.png)

Context: it used to be that the formatting was done and attributed to the backend, so you couldn't just use undo.  That was confusing, and now the formatting is done by the user that requested it so undo works fine.   There is absolutely **no need** to use TimeTravel or manually revert diffs if you accidentally do a format operation -- just type undo.

**Comment by seaneberhard** [comment]
Oh, nice, I didn't notice that! Thanks! In that case, happy for this to be closed and subsumed by some more general keyboard shortcuts or latex editor improvements issue, e.g., #4455. (Not related to this particular issue, but I would love a way to inspect the section structure of my latex document and jump around more easily.)
