### ISSUE TITLE
nbgrader: configure some aspects

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4500]
the goal is to customize the behavior of cocalc's nbgrader functionality. the offical nbgrader configuration file uses traits' configuration mechanism. it should be possible to do this.

1. write a helper pyutil script to invoke nbgraders configuration step and encode the config in json
2. call this from where nbgrader runs to retrieve a customization
3. replace/tweak hardcoded behavior/values by config values

first use case is to change the default replacement of student code blocks. in particular, to not throw an `NotImplementedError` but just insert a `pass` statement.

Ref:
*  https://nbgrader.readthedocs.io/en/stable/configuration/config_options.html
* :point_right:  https://nbgrader.readthedocs.io/en/stable/configuration/student_version.html#changing-the-defaults

---

another approach is to tied this to the course configuration. we only implement the most important configurations. one that's being requested is the stub to replace for students, i.e. the equivalent of

```
c = get_config()
c.ClearSolutions.code_stub = {
"python": "# YOUR CODE HERE\n\n# END OF YOUR CODE"
}
```

(by Michael Falk)

**Comment by haraldschilly** [comment]
here is a POV of my idea:

1. `nbgrader_config.py` in the home directory:
```
~$ cat nbgrader_config.py 
c = get_config()
c.ClearSolutions.begin_solution_delimeter = "BEGIN MY SOLUTION"
c.ClearSolutions.end_solution_delimeter = "END MY SOLUTION"
c.ClearSolutions.code_stub = {
    "python": "# Hello student! Please code your answer here.\npass",
    "javascript": "// Hello student! Please code your answer here.\n"
}
```

2. this code in `extract_nbgrader.py`:
```
#!/usr/bin/env python3
# extract nbgrader configuration

import os
import json
from jupyter_core.application import JupyterApp
from nbgrader.apps import NbGrader

path = os.path.expanduser('~/')
cfn = "nbgrader_config.py"
grader = NbGrader()
super(JupyterApp, grader).load_config_file(cfn, path=path)
print(json.dumps(grader.config, indent=2))
```

3. that's the output:
```
~$ python3 extract_nbgrader.py 
{
  "NbGrader": {},
  "Exchange": {},
  "TransferApp": {},
  "ClearSolutions": {
    "begin_solution_delimeter": "BEGIN MY SOLUTION",
    "end_solution_delimeter": "END MY SOLUTION",
    "code_stub": {
      "python": "# Hello student! Please code your answer here.\npass",
      "javascript": "// Hello student! Please code your answer here.\n"
    }
  }
}
```

**Comment by williamstein** [comment]
I don't think I agree with this approach, since the customization options for "nbgrader in cocalc" are likely to be mostly different than the ones for the Python command line implementation of nbgrader.  The result will be lots of options in a config file that get ignored, and us having to add options that don't make sense in the config file.

**Comment by williamstein** [comment]
Closing because we now have configuration, and future configuration should go in the same place.
