### ISSUE TITLE
share vs. publish a file

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4502]
in the past few days I witnessed cases where users were confused about the meaning of "share". they assume it's like adding a collaborator, which is something different. renaming it to "publish" for "publishing on the web" would make a clearer distinction between the two.

example google docs:

*  share button top right opens a dialog to add collaborators.
* file → publish on the web makes the file public, like we do with the share server

**Comment by CalamariDude** [comment]
^^ Very much agree, I'm a native speaker and have some years of software experience under the belt, was still confused.

**Comment by williamstein** [comment]
It should be **public** not **publish**, since any change to the file immediately updates it, whereas publishing would make a point in time version public.

**Comment by williamstein** [comment]
And we **already** say "Public" in the listing, so this change you propose adds consistency.  Great idea:

![image](https://user-images.githubusercontent.com/1276278/78819391-046eb280-798b-11ea-8b73-86dd298b6962.png)

**Comment by williamstein** [comment]
And @haraldschilly points out the upper right "Share" button should say "Public" or "Private".

**Comment by slel** [comment]
For consistency the share.cocalc.com server
could also become public.cocalc.com then...

**Comment by williamstein** [comment]
I'm not planning to change share.cocalc.com since I don't want to have to worry about breaking tons of links and us having to maintain redirects forever.    Also, it's possible that other types of sharing on share.cocalc.com could get implemented besides just "public" sharing.
