### ISSUE TITLE
jupyter/firefox: cursor's name behind the background

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4503]
the name of a collab's cursor is behind the background of the cells. see screenshot below. 

this happens on firefox

future you: if you work on this, you might also want to fix #4431

![Screenshot from 2020-04-07 16-50-10](https://user-images.githubusercontent.com/207405/78683866-1b13fb80-78f0-11ea-9389-7023d7fe0c53.png)

**Comment by williamstein** [comment]
Still broken in latest version.
