### ISSUE TITLE
display of assignment list in course file sometimes breaks after deleting due date

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4506]
Reported by James P. Crutchfield. Seen on macOS 10.15.4 with Chrome 80.0.3987.163 (Official Build) (64-bit) and Firefox 75.0 (64-bit).

1. On command line, do `mkdir A1 A2` to create two empty assignment directories.
1. Open a new course file.
1. Add directories A1 and A2 to assignments.
1. Still in Assignment tab, expand A1, set due date of A1 to the 10th of the month, and collapse A1 again.
1. Expand A2, set due date of A2 to the 2nd of the month, and collapse A2. A2 will now be above A1 because it has an earlier due date.
1. Expand A1 and click "x" to delete the due date.
1. Observe that A1 is moved up, but that part of its display overlays that of A2.
1. Leaving A1 expanded, also expand A2 and observe that part of A1 is overlayed by A2.

![assignment-i7840](https://user-images.githubusercontent.com/528072/78947118-269b2a00-7a8a-11ea-8d2b-83a561fbe236.png)

Additional observation: whenever an assignment is expanded, the region for the student list (the space under the heading `Student ...  1. Assign to Student ... 2. Collect from Student...` etc.) seems to take up more height than is necessary. It's extreme in this example with 0 students, but also quite noticeable if there are 5 or fewer.

**Comment by williamstein** [comment]
Interesting.  This is a bug in our use of react-windowed, which makes it so we can efficiently display a large number of assignments...

**Comment by novoselt** [comment]
Gone.
