### ISSUE TITLE
fetch_olivetti_faces() is not working on cocalc

### ISSUE THREAD

**Issue by Abdulmalek97** [sagemathinc/cocalc#4515]
I'm doing `faces = fetch_olivetti_faces()` in a jupyter notebook inside cocalc and getting this result: 

`downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /home/user/scikit_learn_data` 

which then stays like that for hours even after restarting all again. This doesn't happen on my local juypter notebook.

How can i solve this?

**Comment by haraldschilly** [comment]
Hi, you didn't tell us much context. Is this a scikit learn dataset? Below is this in CoCalc.

I am speculating that you haven't upgraded "Internet Access" of the project you're working with. See https://doc.cocalc.com/billing.html#what-exactly-is-the-internet-access-quota

![Screenshot from 2020-04-16 15-28-33](https://user-images.githubusercontent.com/207405/79461869-0a057180-7ff7-11ea-91be-0ee969de4b04.png)

**Comment by Abdulmalek97** [comment]
Kindly wait for a response before closing the item. You are right, it is the no-internet access thingy. I looked into paying but there were no payment friendly methods for people who have no credit cards. I live in the Netherlands and never owned a credit card like most Dutch people

**Comment by slel** [comment]
@Abdulmalek97 CoCalc can offer PayPal payments if you email them.

**Comment by slel** [comment]
@Abdulmalek97 For a case like this you can also download to your
own computer from https://ndownloader.figshare.com/files/5976027
and then upload the file to your CoCalc project via the web interface,
and place it in the indicated folder `/home/user/scikit_learn_data`
(create that folder first if necessary).

**Comment by haraldschilly** [comment]
yes. the public list is for self serving customers and credit cards, there are several other ways to purchase a plan. email us at help@cocalc.com

**Comment by Abdulmalek97** [comment]
I have a deadline tomorrow, i don't want to sit waiting on an email. I found an alternative already ;)
