### ISSUE TITLE
Install TIDES

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#4522]
Install TIDES on CoCalc

TIDES solves ODEs numerically, working in large precision.

It would be nice to have it installed system-wide on CoCalc.

Related:

- "Differential equation solvers" page in the SageMath documentation
  http://doc.sagemath.org/html/en/reference/calculus/sage/calculus/desolvers.html

- sage-support question, 2020-04-16:
  Error using 'desolve_tides_mpfr'
  https://groups.google.com/d/topic/sage-support/a4vZQY4aajk/discussion

- sage-cell discussion, 2020-04-16:
  Install TIDES on SageCell?
  https://groups.google.com/d/topic/sage-cell/kR4R_HJDrms/discussion

- sage-cell pull-request, 2020-04-17:
  Add 'tides' optional package
  https://github.com/sagemath/sagecell/pull/531/files

**Comment by williamstein** [comment]
Make a support request, etc.
