### ISSUE TITLE
Make it possible move a project from being owned by an anonymous account to being owned by an existing an account

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4524]
The use case is:

1. Sign out of a normal cocalc account
2. Use an anonymous cocalc account
3. Get whatever you did in the anonymous account back into your old account

REQUESTED BY: @slel   

WORKAROUND: 
1. Add a temporary email/password to the anonymous account to make it a normal account
2. Add your other normal identity as a collaborator to the project
3. Delete your temporary email/password account.

Regarding priority, there has only been exactly one support request related to this in four months.

**Comment by williamstein** [comment]
Also, REQUESTED BY: Michael Falk

1. I would like to alter the default code stub for graded Python cells.

My nbgrader_config.py file looks like this:

```
c = get_config()
c.ClearSolutions.code_stub = {
"python": "# YOUR CODE HERE\n\n# END OF YOUR CODE"
}
```

**Comment by slel** [comment]
Related: #4561

**Comment by williamstein** [comment]
Anonymous accounts are basically deprecated.
