### ISSUE TITLE
split frame terminal or shell: always start terminal/shell in the same directory as the file

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4527]
If I have a file `~/foo/bar.py`  and I either split it to get the terminal or press that shell button, it should always run in `~/foo`. As far as I have checked, for python the shell is ok, but the split-terminal is in the home dir. For a `.ts` file, shell and slit terminal is in the home dir. Something is weird …

**Comment by williamstein** [comment]
I can't reproduce anything you claim in the description of this ticket.  I tried it all and in every case the shell and terminal were both in the same directory as the file.

If you can figure out steps to reproduce the problem, please put them here and re-open this ticket.
