### ISSUE TITLE
share: truncated notebooks

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4531]
the rendered view of a large notebook file is randomly truncated. I bet that's because an incremental rendering process times out or runs into a limit. I've a couple of ideas how to fix and improve this.

1. watch the rendering process and if it fails, insert a clear banner that this is truncated
2. upon each successful full render, cache the full output. my approach would be to make this a table in the database (we could create one called "cached_blobs"). the key is derived from the file's content or well, the usual, ID, path and last updated. Each time it is accessed, the "expired" timestamp is pushed somewhere into the future to avoid it being cleaned up. The reason why I think this helps is because [this example](https://share.cocalc.com/share/18c3b4248944bcea28f33da59c1e61c37073d4b6/Kerr-AdS-5D-string6.ipynb?session=) did render fine once, but failed several other times. that one successful render would have made it work for all other accesses.

this is similar to #4267, which seemingly doesn't solve the problem at all

**Comment by williamstein** [comment]
> . I bet that's because an incremental rendering process times out or runs into a limit.

Maybe.  I know that I put in a bunch of explicit limits on rendering sizes for various document types, similar to what github does.  

The best thing to do if the problem really is server side speed in this case is to explicitly put something at the bottom of the notebook saying it was truncated and include a link to either download or open the full document (e.g., via an anonymous account).

**Comment by williamstein** [comment]
We should also try just completely disabling "streaming rendering".  It's some "amazing advanced" feature of React, but obviously it has potentially bad side effects (like failing in confusing ways).  Instead, we could just either render the entire thing and then send it, or send a "it failed, sorry" message.

**Comment by williamstein** [comment]
>  I bet that's because an incremental rendering process times out or runs into a limit.

The was a kucalc-only situation where it was running into a limit; this was very similar to what happened with Eric Gourgoulhon's notebooks last time.  We were allocation 3GB reserved with a limit of 4GB for each hub-share.  However, node itself was being run with
```
node --max-old-space-size=1000 
```
so node was stupidly limiting itself to a VERY tight memory limit of only 1GB total.   Rendering all that mathjax in these notebooks from Eric Gourgoulhon can take around 1GB, so the limit would sometimes get hit and the node process would fail.  This closed the HTTP stream before finishing the render.

I've fixed this to use the full 4GB and haven't seen a problem.  

This could in theory still be a problem with a truly massive notebook that takes minutes to process.  The only solution I can think of that doesn't require major architectural changes to the share server (e.g., like storing rendered documents in a database, which would likely make the server a much more complicated application than it is now), is to display a "Loading" HTML div that is position:absolute'd to the bottom of the screen... and when loading finishes, to remove it with a tiny bit of javascript.  That way at least the user is informed that the load failed.

**Comment by williamstein** [comment]
I will close this, but we can re-open this if it ever becomes a problem again.  Also the discussion here should be useful.
