### ISSUE TITLE
Unable to use Interact.jl with Julia 1.4 notebook

### ISSUE THREAD

**Issue by dpsanders** [sagemathinc/cocalc#4533]
Running 

`using Interact` 

in a Julia 1.4 notebook gives

`Unable to load WebIO. Please make sure WebIO works for your Jupyter client. For troubleshooting, please see the WebIO/IJulia documentation.`

For a standard Jupyter notebook the fix would be to run

```jl
julia> using WebIO

julia> WebIO.install_jupyter_nbextension()
```

**Comment by williamstein** [comment]
@haraldschilly I'm not sure, but I think this is a request for you to install WebIO systemwide for Julia-1.4, since:
```
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0 (2020-03-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using WebIO
ERROR: ArgumentError: Package WebIO not found in current path:
- Run `import Pkg; Pkg.add("WebIO")` to install the WebIO package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:892
```

**Comment by haraldschilly** [comment]
this is installed. maybe restart your project, it could be new. however, WebIO injects some custom javascript code. Below is a screenshot showing what's going on in the output cell.

![Screenshot from 2020-04-25 21-17-32](https://user-images.githubusercontent.com/207405/80288780-89ebb400-873a-11ea-9e6a-c89d8eed5e04.png)
