### ISSUE TITLE
make it possible to load cocalc without it attempting to load anything from external network resources

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4534]
Example applications:

> Using CoCalc in an airgapped environment via cocalc-docker. Without internet access we have noticed a lot of lag with the application due to its inability to reach CDN sources for page content. A similar application might be using cocalc-docker locally on a laptop in an airplane or remote area with no network access. 

Another application is improving predictability of page loads.   By relying on numerous external CDN sources makes the initial load time for CoCalc less predictable and more subject to potential external outages.  

Here are some external URL's CoCalc tries to reach on load:

- https://cdnjs.cloudflare.com/ajax/libs/mocha/5.2.0/mocha.min.css
- https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css
- https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
- https://storage.googleapis.com/cocalc-extra/cocalc-screenshot-20200128-nq8.png
- https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap

Mocha should be just removed -- it was only for some frontend testing in development, and we don't use that anymore.   Bootstrap, katex, the screenshot should be in webpack.  The fonts... I don't know.

**Comment by williamstein** [comment]
REQUESTED BY: Kevin Bruner

**Comment by williamstein** [comment]
This should now be completely fixed for the main cocalc application, due to work of @haraldschilly .  I've updated https://cocalc.com so it uses this, and I always updated the docker image.

Note that the *share* server on the docker image is still not done.  For some reason it grabs these resources from cocalc.com, rather than the docker image:

bootstrap.min.css , codemirror.css, katex.min.css. analytics.js


![image](https://user-images.githubusercontent.com/1276278/81618664-b2131e00-939c-11ea-9c77-5e51c979a2f3.png)

**Comment by haraldschilly** [comment]
did you set the domain name? the reason the server needs it lies in production, where we cross the subdomain from share.cocalc.com to just cocalc.com … the server needs to know that, and that's why it uses a setting. So, in the settings, the domain name should be for all modes, which it currently isn't. 

In this case here, set kucalc mode to be no, and then it shows up.

![Screenshot from 2020-05-12 10-00-08](https://user-images.githubusercontent.com/207405/81657940-9bbaa000-9438-11ea-9b7c-ab5f925de552.png)

**Comment by williamstein** [comment]
> did you set the domain name?

I'll look into this. However:

> the domain name should be for all modes, which it currently isn't.

if that is needed for the share server to work properly on a default cocalc-docker instance, then it is a bug.  The default out-of-the-box configuration when visiting foo/share should be for it it just work, or alternatively for it to be **completely disabled** unless the user sets up a subdomain specifically for sharing files.   

Of course, serving the cdn files from cocalc.com instead of some random cdn's is certainly no worse than how it was until yesterday so no matter what your PR is a strict improvement.

**Comment by williamstein** [comment]
I should add, the rationale for disabling the share server completely unless it is on a different explicitly configured (sub-)domain (without explicitly enabling it) is for security reasons, to avoid XSS attacks.

**Comment by williamstein** [comment]
I'll close this as solved and possibly open a new ticket related to cocalc-docker.
