### ISSUE TITLE
jupyter: cell info for elapsed time overlaps with content

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4536]
see screenshot below. placing that info on top of the cell instead of inside of it would make this more readable.

![Screenshot from 2020-04-27 10-59-29](https://user-images.githubusercontent.com/207405/80354823-8c075d00-8877-11ea-849a-e3db2ed57bb5.png)

**Comment by williamstein** [comment]
> . placing that info on top of the cell

It doesn't fit and will overlap with the output of the previous cell... unless we increase the space between cells.  That's an option, of course.
