### ISSUE TITLE
typo "sematic" in two "Account/Preferences/Other/Default file sort" menu choices

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4543]
The word "Semantic" is misspelled in the `Generated filenames` menu in preferences, in two locations, without and with the date prefix. See https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/project/utils.ts#L32

<img width="345" alt="sematic-menu" src="https://user-images.githubusercontent.com/528072/80550488-e1319480-8985-11ea-9da2-d9b31dcd5189.png">

I'm not submitting a PR for this small change in case the file in question is part of current work by other dev.

Note there is also a comment couple lines down:

        // TODO iso is the "old way". Change it to "semantic" after a week or two…
        static default_family = DEFAULT_NEW_FILENAMES as NewFilenameTypes;

Is it time yet to switch the default family to "semantic"?

**Comment by williamstein** [comment]
Thanks, I fixed it!
