### ISSUE TITLE
project log does not record destination directory when a file is copied to a new project

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4548]
1. Open Files view and select a file using the checkbox at left.
1. Click ``Copy`` then ``A Possibly Different Project`` and select a different project from the current one and a directory in that project.
1. Click ``Copy 1 item``.
1. Open the project log. Observe that only the destination project is recorded, not the destination directory.

**Comment by williamstein** [comment]
Also, when it does record the destination directory (for copy within a project), the link to open the directory in the project log tries to open the directory as a file which gives an error:

![image](https://user-images.githubusercontent.com/1276278/80767085-ef092600-8afb-11ea-9fb0-e399ff7878ab.png)

![image](https://user-images.githubusercontent.com/1276278/80767092-f9c3bb00-8afb-11ea-9486-002948719169.png)
