### ISSUE TITLE
Could CoCalc offer VS-Code editor instances via code-server?

### ISSUE THREAD

**Issue by oschulz** [sagemathinc/cocalc#4553]
Not sure if this is feasible and how much effort it would be:

I was thinking that having a start-of-the are code-editor in CoCalc would be awesome. I stumbled onto [code-server](https://github.com/cdr/code-server), it serves a complete VS-Code as a web-page (VS-Code is web-based internally, after all). Maybe CoCalc could spawn that as a service, like it currently allows the user to start JupyterLab and Jupyter-Notebook server instances?

Not exactly a lightweight feature suggestion, I know. :-)

**Comment by williamstein** [comment]
I recently created this same issue!  #4479

**Comment by oschulz** [comment]
Sorry, didn't see #4479 - nice!
