### ISSUE TITLE
files: action area not scrollable – e.g. copy button disappears

### ISSUE THREAD

**Issue by JeanSebastienTurcotte** [sagemathinc/cocalc#4560]
In a project, using the GUI, it seems that if you filter for something, (say pdf or png), and the want to copy or move selected files, the copy and cancel buttons are not appearing. If you then clear your search filter and try to copy or move, it works.  Bug found on chrome browser  81.0.4044.129.

**Comment by haraldschilly** [comment]
I fear I don't fully understand. Could you maybe attach a screenshot? I tried this:
1. files
2. search for ipynb
3. select two files
4. click on copy...

screenshot below

I'm on Chrome 83/Linux though …

![Screenshot from 2020-05-04 16-47-06](https://user-images.githubusercontent.com/207405/80978930-ffd0d900-8e26-11ea-8ce3-9a38919dab4e.png)

**Comment by JeanSebastienTurcotte** [comment]
There's a screenshot attached. 
![Cocalcbug](https://user-images.githubusercontent.com/8136509/80979773-c633aa00-8df5-11ea-8578-06a5cbb8096b.PNG)

**Comment by haraldschilly** [comment]
Oh, I see, it's off screen and you can't scroll down. I adjusted the issue text.

A quick workaround is to press `Ctrl`+`-` key to zoom out. Then it should be visible again. Afterwards do `Ctrl`+`0` to reset the zoom again.

**Comment by JeanSebastienTurcotte** [comment]
Oh wow, right. Simple then. I tried panning the screen and it wouldn't so I figured there was nothing there.

**Comment by williamstein** [comment]
The copy button doesn't disappear. I don't think we should change the current behavior in a smallish way to fix this, since that has its own UI issues...
