### ISSUE TITLE
Jupyter markdown cells: apply zoom to quoted text too

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#4568]
To replicate:

- create a Jupyter notebook markdown cell containing:

  ```
  In Python

  > we count from zero
  ```

- render by hitting shift-enter

- hit the zoom-in button ("magnifying glass +" icon) a few dozen times

Expected: the whole text scales.

Observed: the words "In Python" scale but the words "we count from zero" don't.

[Observed on macOS 10.14.6 with Firefox 75.0 (64-bit) and Opera 67.0.3575.137.]

**Comment by slel** [comment]
To teach online, I often open a CoCalc window on a large screen
and share that window in BlackBoard Collaborate meeting tool.

I browser-zoom-out several times with "ctrl-minus" to make the
interface elements tiny, and then CoCalc-zoom-in a lot of times
to make the actual content big enough for students who might
be viewing it on tiny screens (laptops, tablets, phones).

I like to use markdown quoting style to recall definitions or
theorems and make them stand out, but this rendering bug
makes this impractical.

**Comment by williamstein** [comment]
Demo (internal use only): https://cocalc.com/projects/8e8660fd-b081-4823-8e87-d6e926d7dbfc/files/2020-05-05-quoted-text-will-not-scale.ipynb?session=

**Comment by slel** [comment]
Same problem in markdown files.

Create text including a quoted portion.

Use the "Increase font size" / "Decrease font size" buttons in the rendered view.

Font size varies for non-quoted text, but not for quoted text.
