### ISSUE TITLE
Display function fail to clear previous content.

### ISSUE THREAD

**Issue by erow** [sagemathinc/cocalc#4574]
```python
from IPython.core import display
a=display.display("a",display_id=True)
#display.clear_output()
a.update("b",)
```

The output of Jupyter is:

> 'a'
> 'b'

**Comment by haraldschilly** [comment]
is this https://github.com/sagemathinc/cocalc/issues/2520 ?

**Comment by erow** [comment]
I think so. Does tqdm call display?

**Comment by haraldschilly** [comment]
well, I am not sure what it does, but it has modes for the notebook and command line. my take is that there is a common low-level command (or character) that causes the output to clear completely. cocalc just doesn't know about that.

**Comment by williamstein** [comment]
This is a dup of #2132.

display generates an output that is "transient" and hence displaying it all by the frontend client is optional.    But we want compatibility with JupyterLab so this is a bug.
