### ISSUE TITLE
generated notebook above student folder causes nbgrader to fail

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4575]
Reported by Michael Falk.

1. Create a CoCalc course with at least one student.
1. Create assignment folder `~/A/A1` and add the folder as an assignment to the course.
1. Open `~/A/A1/Lab1.ipynb`. Select `View / Create assignment (nbgrader)`.
1. Add a code cell by selecting "Autograded answer" at right and leave the default contents.
1. Add a second code cell by selecting "Autograder tests" and leave the default contents.
1. Click `Validate` then `Generate student version`.
1. In course "Assignments" tab, distribute the assignment to the student project, collect it, and run nbgrader to get a score of "0 / 1".
1. Here is where the error is introduced. In a terminal, do this (the name of the destination file doesn't matter as long as its extension is .ipynb):
    ```
    cd ~/A/A1
    cp student/Lab1.ipynb x.ipynb
    ```
1. Back in the course "Assignments" tab, run nbgrader again. Observe that nbgrader fails with this message: "Error: Error: ENOENT: no such file or directory, open 'nbg2020-001-collect/Assignments/Assignment5/650a039a-c296-412f-ab24-db21a605306d/x.ipynb' - try running nbgrader again." Screenshot below.

<img width="265" alt="nbgrader-ENOENT" src="https://user-images.githubusercontent.com/528072/81360498-9c061480-90a1-11ea-9c73-0e824f244ab6.png">

**Comment by williamstein** [comment]
This is intentional.   Adding new ipynb files after the fact is going to break things, since the files to be graded depend on the notebooks that exist.
