### ISSUE TITLE
jupyter content panel unresponsive when opening

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4579]
when I open a jupyter notebook, which has the content panel opened (e.g. after refreshing the page), it uses a lot of cpu and makes the whole page unresponsive. the browser shows this bar:

![Screenshot from 2020-05-10 19-32-15](https://user-images.githubusercontent.com/207405/81506269-6d807780-92f5-11ea-832f-911132724e81.png)

the notebook itself has only ~20 cells, where there is 1 title in the first cell, and 4 subtitles. So, it's definitely not large...

**Comment by williamstein** [comment]
1. What is "the content panel"?  Is it the "Table of Contents"?  There's no panel called "content":

![image](https://user-images.githubusercontent.com/1276278/81511153-0b5f4c80-92cc-11ea-9dd2-9745c5c4afd9.png)


2. Assuming the "the content pane" is "Table of Contents", I was not able to reproduce this problem, so... can you provide your same notebook or steps to reproduce this?

**Comment by haraldschilly** [comment]
yes, it's table of contents. it happens every time I open it. I'll come up with something to reproduce it.

**Comment by williamstein** [comment]
I realize now that you clarified that you mean "table of contents", not raw, which was what the above commit partially fixed.

**Comment by williamstein** [comment]
I improved the code related to contents, but was never able to reproduce your issue (and you didn't either).  So closing.

**Comment by haraldschilly** [comment]
well, I opened a notebook with an opened ToC today and it was as stuck as usual. 100% cpu for a minute or more, yellow banner, etc. So, whatever the change was, had zero impact.

**Comment by williamstein** [comment]
What are the steps to reproduce this?

**Comment by williamstein** [comment]
Closing this, since no comment about it for years and nothing to reproduce it.
