### ISSUE TITLE
recent docker generates stripe error on the non commercial mode

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc#4583]
Hello,
I dont know if this was always the case, but I notices that in noncommercial mode the recent image gives an error on strpe is not enabled in the browser console: 
``
docker pull sagemathinc/cocalc
Using default tag: latest
latest: Pulling from sagemathinc/cocalc
Digest: sha256:62312d30e3de96da6e7aac7b2bbf7b33beaae271e45c4605f2bb3639df6c8588
Status: Image is up to date for sagemathinc/cocalc:latest
docker.io/sagemathinc/cocalc:latest

![image](https://user-images.githubusercontent.com/2283443/81936718-f0a21600-95f2-11ea-97ba-aa5f4e236157.png)

Thank you beforehand, Arman

**Comment by haraldschilly** [comment]
similar to #4584

**Comment by haraldschilly** [comment]
@arm2arm I've some problems reproducing this. Somehow my test setup must differ, or I don't know what's triggering this ... i.e. I'm missing something here. the site setting is `commercial == no` ?

**Comment by arm2arm** [comment]
yes it is following:
1) create an admin
2) using the chrome browser go to the admin panel
3) customize the theme: images, name,emailserver, etc
4) disable kubernetes and commercial options: "no"
open the chrome console check the errors

ps
firefox giving warnings only, hmm strange

**Comment by haraldschilly** [comment]
ok, thanks, good to know that it should be obvious. so it must be my configuration and setup here.
