### ISSUE TITLE
analytics.js not found on pressing the login button

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc#4584]
Hello, I am geeting following error on login page.
> GET https://my.domain.de/analytics.js?fqd=false net::ERR_ABORTED 404 (Not Found)

The server running with non commercial flag on.

Thanks,
Arman.

**Comment by haraldschilly** [comment]
similar to #4583

**Comment by williamstein** [comment]
I'm building a new Docker image with @haraldschilly 's fix right now, which if it all checks out I'll push to Dockerhub later today...

**Comment by williamstein** [comment]
OK, after testing @haraldschilly 's fix, that doesn't fix this problem.  It is actually a mistake with the haproxy configuration on cocalc-docker...  which was easy to fix.  I've fixed that and am building a new image now.    https://github.com/sagemathinc/cocalc-docker/commit/867de7041a78394166c0779f4f18f330e5397ca2
