### ISSUE TITLE
jupyter/sage9: large animations are not displayed

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4590]
this works fine

```
frames = [plot(sin(k*x)) for k in range(5)]
animate(frames).show(format='gif')
```

while this reveals: "WARNING: 1 intermediate output message was discarded."

```
frames = [plot(sin(k*x)) for k in range(20)]
animate(frames).show(format='gif')
```

![Screenshot from 2020-05-15 16-07-43](https://user-images.githubusercontent.com/207405/82059385-3e3b8300-96c6-11ea-914a-c0439b3d2d59.png)

I don't know what limits are imposed. In general, I would assume that such an animation is stored as a blob and the browser shows it. Thus such animations can be pretty large, actually.

**Comment by williamstein** [comment]
There are hardcoded parameters in cocalc-jupyter for when " intermediate output message was discarded" is triggered.   We've never had problems with things being too big since I set these, so maybe it is time to (significantly) increase them?

**Comment by williamstein** [comment]
WORKAROUNDS:
  - use a Sage worksheet
  - save to a.gif then display the gif in another cell

Both are illustrated here and work: https://share.cocalc.com/share/df81e09e5b8f16f28b3a2e818dcdd4560e7818ae/support/4590/?viewer=share

**Comment by williamstein** [comment]
REPORTED BY: Robert Indik

**Comment by williamstein** [comment]
I've increased the default output length cap from 10000 to 50000.  This makes it so 
```
frames = [plot(sin(k*x)) for k in range(30)]
animate(frames).show(format='gif')
```
works fine.  Of course there is some limit where things will still fail; however, it's much higher and you might hit other limits first (like patience).

**Comment by williamstein** [comment]
Project restart required, and this won't be live until probably a few hours from now.
