### ISSUE TITLE
Sign out button in Account tab vertically crowds horizontal menu for some widths

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4597]
Seen with recent Chrome and Firefox

1. Open Account screen.
1. Shrink width of browser window so `Sign out...` button is over `Support` or other buttons.

![signout-too-close](https://user-images.githubusercontent.com/528072/82108588-0861c300-96f5-11ea-8796-95b968934c81.png)

**Comment by williamstein** [comment]
@haraldschilly  #4679 fixes this.  At the same time, it breaks the problem that this button solves if the screen is somewhat narrow...  Maybe a new ticket should be opened about that.
