### ISSUE TITLE
latex multifile doesn't correctly detect all files

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4618]
the main problem is a latex file with many parts (included via `\include`), which doesn't build upon pressing the build button. 

to solve this ticket, a change in an included file or subfile and then clicking on build should trigger a build.

I don't have a public example yet.

**Comment by haraldschilly** [comment]
I tried to figure out what's going on, but I have no real clue. The first thing that surprises me that the logfile is parsed for filenames. I bet that can break randomly. Back when we discussed this I was proposing to use latexmk to list the dependencies, since I'm confident it can do this well.

**Comment by williamstein** [comment]
@haraldschilly fixed this -- yeah!  https://github.com/sagemathinc/cocalc/pull/4619
