### ISSUE TITLE
icons for stopwatch files are not rendering

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4620]
Seen with current Chrome on macOS.

Click (+)New, choose a basename, and click Stopwatch.

In the tab that opens, button names appear, rather than icons:

![stopwatch-buttons](https://user-images.githubusercontent.com/528072/83282477-43590180-a19f-11ea-8682-5e7de887154b.png)

**Comment by williamstein** [comment]
Nice catch. This was caused by the upgrade from antd3 to antd4, which change the Icon api.  I'll fix it.
