### ISSUE TITLE
Sage interact library doesn't seem to work within sagews files

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/cocalc#4626]
The command

    interacts.calculus.definite_integral()

should "just work", but doesn't appear to, in .sagews sheets.    The error is that it simply returns the html rather than said html being rendered.  It does seem to work in the Jupyter notebook.

**Comment by williamstein** [comment]
For some reason the interacts library is using the sagenb version of the interacts codes and widgets. This is controlled by this code, in `sage/interacts/library.py` which amusingly it seems that @haraldschilly and I wrote like a decade ago:

![image](https://user-images.githubusercontent.com/1276278/83456321-588a9600-a414-11ea-8a83-b53546d5f033.png)

I don't know if we ever modified Sage or patched Sage to make this work in CoCalc, and I don't know of any workaround to make this work, except "use Jupyter" instead.

**Comment by kcrisman** [comment]
> For some reason the interacts library is using the sagenb version of the
> interacts codes and widgets.
>

I think that was intentional at that time, yes.  It's not clear to me where
else these things live (I mean inside vanilla Sage).

> I don't know if we ever modified Sage or patched Sage to make this work in
> CoCalc, and I don't know of any workaround to make this work, except "use
> Jupyter" instead.
>

But interacts do work in CoCalc Sage worksheets, so  presumably there could
be a way to make this work.  How do these particular globals in Jupyter get
"known" by Sage?

**Comment by williamstein** [comment]
> so  presumably there could be a way to make this work.

Yes definitely.  One way would be to somehow patch the version of sage/interacts/library.py that is on CoCalc.com.  I can't remember if we every tried doing that, but it would work if done right.

**Comment by kcrisman** [comment]
Possibly also relevant is https://github.com/sagemath/sagecell/issues/385 where you mention monkey patching something in "Salvus".

**Comment by williamstein** [comment]
I'm closing this, since Sage worksheets have a completely different implementation and model for interactive widgets than Jupyter.  If you want to use the interact library from sage, you MUST use a Jupyter notebook, where things will work well already:

<img width="885" alt="image" src="https://github.com/user-attachments/assets/f89f27e3-9b5e-4f1d-bf3d-7037f1edc8d8">

Also, the future of Sage worksheets is that they will just be an alternate rendering mode for Jupyter notebooks.
