### ISSUE TITLE
Weird cutoff in tex view

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/cocalc#4638]
This is in FF 77.  Note how the bold and other buttons are cut off in the tex view.   I couldn't get that to go away no matter what the zoom level.  Closing other files didn't seem to affect this either.

![Screen Shot 2020-06-05 at 11 55 41 AM](https://user-images.githubusercontent.com/1775728/83897707-eb347900-a723-11ea-8717-a596836abcf2.png)

**Comment by williamstein** [comment]
I not able to reproduce this in FF 77 on Windows 10.  In all zoom levels I tested it works fine.  Do you have any extensions that could be messing with things?

**Comment by kcrisman** [comment]
> I not able to reproduce this in FF 77 on Windows 10. In all zoom levels I
> tested it works fine. Do you have any extensions that could be messing with
> things?
>
>
Not that I know of.  I also don't see it now (had closed and later
reopened.)  I guess I'll open a new issue if I can reproduce it more
consistently.

**Comment by williamstein** [comment]
> I guess I'll open a new issue if I can reproduce it more consistently.

Suggesting I should close this...

**Comment by haraldschilly** [comment]
Do you have any font related settings active? e.g. changes to the default font size or family?

**Comment by kcrisman** [comment]
> Do you have any font related settings active? e.g. changes to the default
> font size or family?
>
>
Not that I know of.

>
