### ISSUE TITLE
state where cocalc-jupyter notebook doesn't finish loading

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4641]
1. Make a jupyter notebook a.ipynb
2. close everything and restart the project.
3. Delete the hidden file .a.ipynb.sage-jupyter2
4. Try to open a.ipynb
5. It doesn't work.

What should happen -- it should work.   There may be other highly unlikely "race" conditions that lead to similar situations, but fixing the above is a good first step.  There's really no reason to *not* make it so the notebook loads, no matter what weird things are done to the hidden `.a.ipynb.sage-jupyter2` state file.

**Comment by haraldschilly** [comment]
is this a dup of https://github.com/sagemathinc/cocalc/issues/3792 or also slightly different?

**Comment by williamstein** [comment]
The motivation and goal is different since it is meant to recover from all
cases and file delete is just one.  I would say this is more general though.

**Comment by williamstein** [comment]
OK, I fixed the issue caused by "Delete the hidden file .a.ipynb.sage-jupyter2", which actually had to do with the new code for properly handling file deletion in general.   That's in 34c1dfd5135aec4257afced9e3cfd13e41df4eec

This isn't great though -- it makes it so the file loads again, but the kernel is confused/broken.  If you restart the project, then everything works fine again.

This was a completely new bug since the file deletion code is new.  It *used* to be that when you deleted the hidden .a.ipynb.sage-jupyter2, it would basically just reset the underlying state, which was what #3792 is about.  

The next interesting case is thus #3792 and the new steps to reproduce that are:

1. Make a jupyter notebook a.ipynb
2.  `echo "" >.a.ipynb.sage-jupyter2` to reset the state.
3. Try to open a.ipynp
4. It doesn't load

Note that if you restart the project, everything works again.

**Comment by williamstein** [comment]
In any case, a workaround is now "Restart the project".

**Comment by williamstein** [comment]
Basically same as https://github.com/sagemathinc/cocalc/issues/4621, probably.

**Comment by williamstein** [comment]
This seems to work now.
