### ISSUE TITLE
delete ancient ipython and jupyter directories from src/webapp-lib/

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4647]
There are two absolutely ancient ipython and jupyter directory trees in our source code for some mysterious reason.   I think (hope!) they are completely unused and an just be deleted.  The point of this issue is to delete them.

**Comment by haraldschilly** [comment]
I looked into this more deeply and found a few strange things.

**Comment by williamstein** [comment]
Fixed by pr #4666
