### ISSUE TITLE
files listing fails to open symlink to a directory

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4653]
1. In a terminal:
    ```
    cd
    mkdir TESTS
    ln -s TESTS tests-symlink
    ````
1. Open Files listing. Click on `TESTS` and verify listing of empty directory.
1. In Files listing, click on `tests-symlink`. See "Loading..." spinner and the following **EISDIR** error message:

<img width="945" alt="symlink" src="https://user-images.githubusercontent.com/528072/84521838-3954f980-ac9b-11ea-94a2-fb8abbde4499.png">

**Comment by mforbes** [comment]
I am having the same issue.  One slight variant I see is that when I first create the symlink, I get a message:

```
Open previously deleted file paper_gw170817_tmp?

After you open paper_gw170817_tmp, use TimeTravel to get past versions.
```
After clicking Open, I get the same EISDIR error.

**Comment by DrXyzzy** [comment]
Also reported by Praveer Tiwari.

**Comment by williamstein** [comment]
Fixed, but you have to restart your project if it is currently running right now to see the fix.
