### ISSUE TITLE
"Missing PDF -- Build or fix" when auto-compiling LaTeX to PDF (fails)

### ISSUE THREAD

**Issue by eduenez** [sagemathinc/cocalc#4655]
*Description:*
 A syntactically valid (1-page) LaTeX file is refusing to compile via the GUI.  It can be manually compiled from the command line to generate a PDF preview in order to "fix" the "Missing PDF" error.  However, on making changes to the TeX file, those changes are *not* automatically compiled on the GUI.  The PDF file is effectively static unless manually refreshed compiling from the command line!  If the PDF is deleted, the GUI refuses to re-create it, leading to the "Missing PDF -- Build or fix" error.

Issue was reproduced using CoCalc in both Chrome and Safari; likely the browser is not a factor.  I also re-started the project 3 or 4 times trying to troubleshoot the issue.  Apparently, the GUI is stuck referring to older version of the file, which has title "Stability of [...]" instead of the *current* version of the file, which has title "Stability and Definability of [...]".  The latexmk run in the GUI seems to get "stuck" after finding the bibliography files.  It's really quite puzzling, and not at all expected behavior. (I've been using CoCalc for a couple of years, but only recently started using the command line and Git there.  This behavior happened just after manually resetting the file to an earlier Git version, which compiles fine from the command line, but not from the GUI.)

[Link to TeX file](https://cocalc.com/share/4e8db8e1760902249d6a96a233beb86b395217bf/repos/DImanuscripts/SecondOrderDef/SecondOrderDefinability.tex)

Note: This seems to be an exact duplicate of the symptoms observed in issue #2909; however, the problem there was solved by simply renaming file to remove troublesome hash character '#'.  The current problem pertains to a file with a vanilla alphanumeric name.

**Comment by williamstein** [comment]
link no longer exists.
