### ISSUE TITLE
selecting text makes line numbers hardly readable

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4663]
when I'm editing code and select a few lines, the line numbers in the gutter are white on a bright gray color. hardly readable.

make this more readable, e.g. color them a bit darker than usual, etc....

![Screenshot from 2020-06-16 10-53-48](https://user-images.githubusercontent.com/207405/84753902-e4c5bd00-afbf-11ea-8ead-eb5f1eeb6abe.png)

browser: firefox 77

**Comment by williamstein** [comment]
This is a codemirror bug that is a side effect of using the render that supports spellchecking (which we are always using right now, even when spellcheck is off).   The best I can do is NOT use that renderer unless in-browser spellchecking is explicitly enabled.  Easy change, which I'll make now.

**Comment by williamstein** [comment]
We should check if there is an upstream codemirror bug about this...

**Comment by williamstein** [comment]
OK, I pushed a fix but it will only fix this for code.  It does NOT fix the bug for editing markdown files (say) though.

**Comment by williamstein** [comment]
I couldn't find this bug in the official codemirror issue tracker.

I found this QA which just said "it's buggy": https://discuss.codemirror.net/t/what-are-the-pitfalls-of-using-inputstyle-contenteditable-in-2020/2389/2

**Comment by williamstein** [comment]
OK, it's not upstream, but I was able to mostly workaround this with a CSS style...
