### ISSUE TITLE
migrate  to python 3.x print()

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc#4665]
https://github.com/sagemathinc/cocalc/blob/46c4e635f80a4e4ae5a40a1e948f6caf654f9caf/src/smc-hub/scripts/compute#L6
should be : `print(cmd)`

If the docker container does not contain the python 2.x  it is not able to start the `/cocalc/src/smc-hub/scripts/compute`

**Comment by haraldschilly** [comment]
I'm working on a cross-compatible pyutil lib [here](https://github.com/sagemathinc/cocalc/pull/4652) ... and thank you for pointing this out, which is clearly something that must be part of this as well

**Comment by haraldschilly** [comment]
is this fixed? I'm closing this. The PR was https://github.com/sagemathinc/cocalc/pull/4670
