### ISSUE TITLE
chat: my own avatar is way off

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4669]
firefox 77, which could be relevant. my blue avatar should be higher up and/or near my chat message, not bottom left. I think there is a linebreak happening, which even introduces an additional "new line" div in between ...

![Screenshot from 2020-06-16 18-57-56](https://user-images.githubusercontent.com/207405/84804688-71de3580-b003-11ea-8cb7-f7f9b89c7439.png)

**Comment by williamstein** [comment]
It's also like this on chrome and is fallout of me totally rewriting chat.

**Comment by williamstein** [comment]
(most likely causes by switching from bootstrap to antd incorrectly.)
