### ISSUE TITLE
improve error message when a user tries to use SSO to sign in and there is an account with the same email address (and password) in cocalc already

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4691]
1. Create account foo@gmail.com with some password
2. Have some sort of single sign on (say with google) that uses that email address.
3. Try to use that single sign on. 
4. Right now you'll receive this error: `postgresql Error: duplicate key value violates unique constraint "accounts_email_address_key"`
5. The error you should see might look like: "Please sign in using the password you created specifically for this site, then in the account preferences tab you can link this account with your single sign on provider.  If you can't remember your password, you can reset it."

Alternatively, we could automatically associate the SSO with the account, since if the person can authenticate using that SSO, then they have proved they own that email address (assuming, of course, that we trust our SSO's, etc.).  Making this change definitely reduces the security of our site a little though, due to the need to trust the SSO's a little more than we do now.

**Comment by haraldschilly** [comment]
well, for testing in "test", I unlinked one of my SSO google accounts (the email/pw account remains) and then signed in using SSO. I got 

> Error trying to login using google -- Error: There is already an account with email address xxxxxxx; please sign in using that email account, then link google to it in account settings.

which matches the supposed behavior in the code. I think there is some additional detail missing to figure this out. I'll try to come up with something to trigger this.

**Comment by williamstein** [comment]
I've added the HEISENBUG label...

**Comment by williamstein** [comment]
I think the current behavior is sufficiently clear.  We've never once got a complaint from a user about this too.
