### ISSUE TITLE
implement a way to set custom CSS in a single place in a Jupyter notebook so it won't be forgotten when the window is scrolled

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4695]
This is a problem because we use react-window.  I think that sometimes people create a single cell with custom CSS in it; this cell is then scrolled off the screen and removed from the DOM (at least if the notebook is sufficiently large), and then that custom CSS is gone.

One solution might just be to run some javascript that appends the HTML to the entire page....

REQUESTED BY: StevenXC on Discord - https://discord.com/channels/492290642832130048/674327031948902415

**Comment by williamstein** [comment]
Ways to run javascript:

One way is
```
%%javascript
```
but Jupyter seems to have no cell magic that is like "%auto" in Sagenb and sage worksheets, which lets you autorun a cell on notebook open. So that's not an option.

Second would be to use a script tag in a markdown cell... but we sanitize the html and strip them.  But Jupyter classic maybe doesn't, so maybe this is reasonable to do?  This may also be related to "trust".

**Comment by williamstein** [comment]
Upon investigating jupyter classic:

- Markdown cells explicitly discard script tags.
- %%html output does render script tags...

In CoCalc we discard script tags in both cases. So if we just change our behavior to render script tags for html output, then there is a partial way to solve the problem.   Unfortunately, if a user scrolls to the bottom of a long notebook, closes the notebook, refreshes their browser, and opens the same notebook, maybe the top cell doesn't get rendered, and they don't get the style until scrolling around.  Or maybe it always works.  I'm not sure.

**Comment by williamstein** [comment]
Unfortunately, this approach probably won't work due to "untrusted versus trusted" notebooks.  I.e., it'll appear to work for you and when you test, but when you autogenerate notebooks or share them, they start out untrusted, and hence script tags get skipped.  So this is also a problem for Jupyter classic.  Conclusion: I should fix this, but it's not going to help you, and I can't think of any possible single solution to your problem.     Instead, we'll probably have to come up with some solution using ipynb metadata, and you can just repeat the same css twice (once in a cell for Jupyter classic, and once in the ipynb metadata).

**Comment by jasongrout** [comment]
> Unfortunately, this approach probably won't work due to "untrusted versus trusted" notebooks.

Yes. In general, in Jupyter we try to not execute "untrusted" javascript automatically for security reasons.

**Comment by williamstein** [comment]
@jasongrout it turns out I tried to implement the same thing as jupyter classic, so "untrusted ==> sanitized out script tags" whereas trusted ==> keep them.  But maybe something changed in React.js (or we didn't test enough) because script tags still don't get rendered via our html react renderer, due to this issue: 

https://stackoverflow.com/questions/35614809/react-script-tag-not-working-when-inserted-using-dangerouslysetinnerhtml

Fortunately, people have made components that nicely solve this problem, so I'll look into changing this now to make cocalc-jupyter more compatible with official-jupyter.

**Comment by williamstein** [comment]
However, our plan for solving this will be to add a new metadata tag to the ipynb file. Can somebody suggest what to use in a way that is unlikely to break anything?  The docs are here:  https://nbformat.readthedocs.io/en/latest/format_description.html#metadata

The goal is to store a string of CSS, which we'll include in the dom between style tags whenever the notebook is displayed (and remove otherwise).

**Comment by williamstein** [comment]
So maybe
```
nb.metadata.css_style = '.editable{margin:1em;color:#ccc;font-size:2em;text-align:center;}'
```

**Comment by StevenClontz** [comment]
I'll note that this example for styling editable cells is a hack I used by injecting `<div class="editable">` into all my generated editable Markdown cells. I don't think CoCalc has classes on cells that could be hooked into with CSS. Then again, this might be a feature, and I've recently made the design decision to only style the non-editable cells anyway, where I can inject whatever HTML classes I want without it bothering the user.

**Comment by jasongrout** [comment]
> However, our plan for solving this will be to add a new metadata tag to the ipynb file. Can somebody suggest what to use in a way that is unlikely to break anything? The docs are here: https://nbformat.readthedocs.io/en/latest/format_description.html#metadata
> 
> The goal is to store a string of CSS, which we'll include in the dom between style tags whenever the notebook is displayed (and remove otherwise).

Is your goal here to propose a Jupyter standard, or to have something that works in cocalc? If you just want something that works for cocalc, you can just claim a namespace sufficiently unique (like 'cocalc' :). If you want to propose a Jupyter standard, opening an issue in https://github.com/jupyter/nbformat would be a good way to start discussion.

**Comment by williamstein** [comment]
> Is your goal here to propose a Jupyter standard, or to have something that works in cocalc?

I want something that works in CoCalc and doesn't *break* using the same ipynb file in Jupyter classic.   So maybe:
```
nb.metadata.cocalc = {"css_style":".editable{margin:1em;color:#ccc;font-size:2em;text-align:center;}"}
```

Thanks for the suggestion to keep it under "cocalc"!

**Comment by williamstein** [comment]
> I don't think CoCalc has classes on cells that could be hooked into with CSS. 

It (probably) doesn't, but it would be easy to add if there were an application for this.

**Comment by jasongrout** [comment]
> Thanks for the suggestion to keep it under "cocalc"!

No problem! That's what we meant in the [docs that you linked to](https://nbformat.readthedocs.io/en/latest/format_description.html#metadata):

> Because it is a shared namespace, any custom metadata should use a sufficiently unique namespace, such as metadata.kaylees_md.foo = “bar”.

**Comment by williamstein** [comment]
I've decided to revert the change to process script tags since:
  - it greatly complicates using katex since it asynchronously adds content into the DOM
  - it's a really worrisome security risk anyways.
  - just use %%javascript in jupyter notebooks.

@jasongrout why is there nothing like %%auto for Jupyter notebooks?  That seems like a huge oversite, and was one of the first things we implemented for Sage Notebook and Sage worksheets.  I'm really surprised.  Is there a proposal for it or have you thought about this?

**Comment by jasongrout** [comment]
> @jasongrout why is there nothing like %%auto for Jupyter notebooks? That seems like a huge oversite, and was one of the first things we implemented for Sage Notebook and Sage worksheets. I'm really surprised. Is there a proposal for it or have you thought about this?

Good question. When it has come up in discussions about Jupyter notebooks, I've always considered it a security precaution to never execute code automatically when opening a notebook. I suppose we might be able to do something for trusted notebooks, though. Note that technically the solution in Jupyter would probably involve cell-level metadata rather than a kernel magic, given that the feature is driven by the frontend and not by the kernel.

**Comment by williamstein** [comment]
> When it has come up in discussions about Jupyter notebooks, I've always considered it a security precaution to never execute code automatically when opening a notebook. 

I agree that perhaps this can be addressed by the "trust" model.  If the notebook isn't trusted, then the auto cells are NOT executed.  If the notebook is trusted, or when the notebook *becomes* trusted, then they are.  I think (?) exactly this already happens with Javascript script tags in %html cells in Jupyter classic.    I also agree that using cell metadata is preferable.   In any case, the fact that Jupyter doesn't have a notion of auto cells and has got this far is surprising to me, and maybe suggests that problems that auto would solve can better be solved in other ways...

(That said, I ended up disabling script takes in html in all cases anyways in cocalc, since enabling it led to a lot of subtle issues with our code paths (starting with use of katex), and we never had any complaints.)

**Comment by williamstein** [comment]
Now fixed by https://github.com/sagemathinc/cocalc/commit/a8e078b2a2ac89e8cb6ac86ff6c60b8b3f6f9a99 ; solution is to just do exactly what you do in jupyter classic, since we're no longer using windowing at all with Jupyter, so all cells stay in the DOM.
