### ISSUE TITLE
missing gap between project tabs and editor tabs

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4710]
there should be a gap for the tabs between these two rows, but it is suddenly missing.

![Screenshot from 2020-06-26 16-38-13](https://user-images.githubusercontent.com/207405/85869130-91c3e500-b7cb-11ea-8cfd-479535c2505d.png)

**Comment by williamstein** [comment]
Why _should_ there be a gap?  It seems like a waste of space.  For what it is worth, I intentionally removed it.

**Comment by williamstein** [comment]
Closing since I think it would be better to just have an option for more layouts or do something significantly different.
