### ISSUE TITLE
wrong "main page" link

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4711]
For mysterious reasons that don't matter, I'm seeing this page in my cc-in-cc dev server:

![image](https://user-images.githubusercontent.com/1276278/85872326-6c5fb880-b784-11ea-973c-941d18f47da6.png)

However, the surprise to me is that the "main page" link goes to `https://cocalc.com`, not `https://cocalc.com/10f0e544-313c-4efe-8718-2142ac97ad11/port/8000/`

The other links at the top all work fine.

**Comment by haraldschilly** [comment]
Since it says "Features" at the top right, this must be the separate server for the landing pages  for cocalc.com.

**Comment by williamstein** [comment]
I'm closing this since it probably doesn't matter or it was me misconfiguring things.
