### ISSUE TITLE
side chat division bar "above" the notification panel

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4712]
open a frame editor with several divisions. then the notifcation bell dropdown.

whatever caused this, the notification root element needs more z-index power :muscle: 

manually in debug: I can see it is at `z-index: 10`, but it needs to be at least 21 (maybe we are generous and set it to 100).

So, wherever it is defined, this is what fixes it:

```
<div style="z-index: 21; margin-left: 0px; position: fixed; 
box-shadow: rgb(170, 170, 170) 0px 0px 15px;
border: 2px solid rgb(204, 204, 204); top: 34px; 
background: rgb(255, 255, 255) none repeat scroll 0% 0%;
 right: 2em; overflow: hidden auto; 
font-size: 10pt; padding: 4px; 
border-radius: 5px; width: 50%; height: 90%;" 
class="smc-vfill">
```

**Comment by haraldschilly** [comment]
reopening this: the bug I saw is definitely fixed, but now I also noticed that the side chat division bar has z-index 100 as well. So, to fix this, increase it again to 1000. ... or are there any other elements that would show up?

**Comment by williamstein** [comment]
I'll fix this properly this morning.
