### ISSUE TITLE
extra border around text boxes

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4714]
I saw this in admin → site settings:

![Screenshot from 2020-06-27 14-35-47](https://user-images.githubusercontent.com/207405/85922437-8e8c3000-b883-11ea-924a-b4f90875c6f7.png)

there is an outer border, but also a second inner one with the actual content. something is not ok.

**Comment by williamstein** [comment]
It's not just this -- the actual functionality of admin --> site settings is completely and totally broken.   Any click on those boxes that look wrong just closes site settings and there is a big traceback in the console.  I haven't touched any code related to this in a while, but you have touched it a lot, so I suspect you broke something, @haraldschilly .    I'll take a quick look, in case there is an easy fix.

**Comment by williamstein** [comment]
OK, my conclusion is that antd is broken !?   I just rewrote your code to directly use HTML select/option and commented out your code.    Please look into this when you get a chance.
