### ISSUE TITLE
opening a deleted file shouldn't record an open event

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4720]
this is more or less just a cosmetic, but still worth to write down: 

when I open a deleted file, I get a warning box about that this file is deleted. if I click cancel, I didn't really open it – this was just an attempt to do so.

still, in the project log there is an entry as if I opened that file...

**Comment by williamstein** [comment]
We can have an additional field added to the even when you make the choice, which says whether you opened and canceled or opened and restored.  We do the same thing with setting how long it took the file to open...
