### ISSUE TITLE
Symlinks break Notebook Synchronization

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#4732]
When two users access the same notebook through different symlinks, then synchronization/collaborative editing becomes a problem.

1. Cells sometimes are suddenly deleted etc.
2. The notification system that shows which users are collaboratively editing is broken.

This could probably resolved by resolving symlinks to their true path somehow under the hood.

**Comment by williamstein** [comment]
NOTE: This is a problem with editing of **all** files, not just Jupyter notebooks.  It is probably even worse with notebooks, since their is an auxiliary file .foo.ipynb.sage-jupyter2 in addition to the original file.
