### ISSUE TITLE
Bumping dark reader

### ISSUE THREAD

**Issue by Gusted** [sagemathinc/cocalc#4736]
https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/package.json#L50 It's stating 4.7.15 while the latest is 4.9.15

Since than it has a lot of improvements and performance upgrades.
I'm happy to hear if their is anything needed to implement the never version of Dark Reader(I'm from the Dark Reader team)

**Comment by williamstein** [comment]
Done.  And @Gusted  thanks for Dark Reader!!   It made it ridiculously easy to support a dark mode in CoCalc, which is very, very important for "accessibility" for many people.

**Comment by Gusted** [comment]
👌

**Comment by Gusted** [comment]
Thank you from using it 😃

**Comment by williamstein** [comment]
I also just made it so one can configure the parameters from within cocalc, and made the link color match yours:

![image](https://user-images.githubusercontent.com/1276278/87356539-15ddd280-c517-11ea-9074-bf5db271dcbe.png)

**Comment by Gusted** [comment]
👀 Those are fancy. Note that we have a lot of parameters so not sure which you implemented

**Comment by williamstein** [comment]
Where are the parameters listed and documented?  Is it what is listed here?  brightness, contrast, sepia, grayscale, etc.?  Are the valid range of values for each parameter listed somewhere?

https://github.com/darkreader/darkreader/blob/a17456902388b515f83bc78256c1b806b83943d7/src/definitions.d.ts#L35

**Comment by Gusted** [comment]
Woops we don't have the latest parameters listed and documented into the API yet.... 
Btw don't use a commit but `master` https://github.com/darkreader/darkreader/blob/master/src/definitions.d.ts#L39 We have a lot more parameters. I will make a PR to add the remaing parameters with their Info.

**Comment by williamstein** [comment]
Thanks!    I implemented only brightness, contrast, and sepia, because that's what's in the example in the README.md.  And I just guessed at valid values for now...  Thanks.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/3106

Have a look at https://github.com/darkreader/darkreader/blob/master/index.d.ts 
For default values https://github.com/darkreader/darkreader/blob/master/src/defaults.ts#L16 If it has something like `auto` it means somewhere in the code it wanders the real value

**Comment by Gusted** [comment]
To have a feeling what all those settings all you can temporary install dark reader(as extension) 
And enable the new UI (https://darkreader.org/blog/v4-9/) to know what the range of values are.
