### ISSUE TITLE
R package vegan won't work without package ‘permute’ 

### ISSUE THREAD

**Issue by jesseseeem** [sagemathinc/cocalc#4742]
Hi, it looks like the popular ecology R package "vegan" is installed, but one of its dependencies "permute" is not. Got the following error message: 
Error: package ‘permute’ required by ‘vegan’ could not be found
Traceback:
1. library(vegan)
2. .getRequiredPackages2(pkgInfo, quietly = quietly)
3. stop(gettextf("package %s required by %s could not be found", 
 .     sQuote(pkg), sQuote(pkgname)), call. = FALSE, domain = NA)

I was able to successfully execute code from the ggplot2 library, so it seems to be an issue specific to vegan. 
Thanks!

**Comment by haraldschilly** [comment]
hmm, weird thing, it is installed, but not really recognized. I guess reinstalling it will fix it. in any case, thx for reporting this, should be available with the next update. I'll report back.

**Comment by jesseseeem** [comment]
Looks like it works now! Thanks very much!
