### ISSUE TITLE
[Suggestion] start page = a new empty notebook

### ISSUE THREAD

**Issue by NicoJG** [sagemathinc/cocalc#4766]
Hi,

I'd love to make CoCalc my WolframAlpha replacement, but I find it quite annoying that I always have to create a new notebook and give it a name, before I can start typing in code.

It would be a very welcome feature if there is a page you could bookmark where every time you enter the is a new empty notebook.
Maybe even with a few default lines of code such as `x=var('x')`.
It doesn't have to save everything. (only if you want to)

If I just want to check an integral or an equation WolframAlpha is still faster, because of the extra steps in CoCalc. 
Even though I find CoCalc (SageMath) way more productive and usable.

**Comment by slel** [comment]
For a Wolfram Alpha replacement, you might be interested in SageCell:

- https://sagecell.sagemath.org

**Comment by slel** [comment]
In CoCalc, a fast way to create a file, once logged in to a project,
is via the "Search or create file" box.

Type `integral.ipynb` (or any other name ending in `.ipynb`) in that box
and hit the "Enter" or "Return" key. This creates the file and opens it.

**Comment by NicoJG** [comment]
Thanks for the quick response.
I guess SageCell is a good Wolfrom Alpha replacement.

But personally I prefere the looks of CoCalc and the features of a Jupyter Notebook.
Also to be able to set a default Notebook with a few default lines of code already written would be awesome.

I guess it's not worth the effort, because there already exists SageCell and It's enough for simple calculations.
Then I guess my suggestion is not really CoCalc related and has more to do with the design of SageCell.

**Comment by haraldschilly** [comment]
I'm just curious, but why not use the same notebook from last time you worked on something? e.g. call one `scratch.ipynb` and bookmark it. To clean it up, either once you're done or when you come back, type in `Esc` key, then `Ctrl+a` and then `dd`. This selects all cells and deletes them.

**Comment by haraldschilly** [comment]
Oh, and to keep one or more cells across sessions, select the ones that should not be deleted: then in the "edit" menu, "toggle delete proection". Then, this esc→ctrl+a→dd won't delete them.

**Comment by NicoJG** [comment]
@haraldschilly That's an excellent suggestion. I just didn't know this is possible.

The only thing I imagined different: 
If I'm not on my computer (so I'm not logged in)
or if I want to suggest CoCalc to someone as a Wolfram Alpha replacement
then it would be awesome to have a short (memorizable) link (like wolframalpha.com)
where you don't have to first manouver to a new notebook. (With a bad internet connection this may take a while)
For new users of SageMath this would be more appealing.

It's just a luxus problem, that's not necessary to solve. :D

**Comment by slel** [comment]
One solution: prepare a template notebook with the setup lines you want,
publish it on share.cocalc.com, and share the link, or a memorable
redirection link from your website or using a service such as tinyurl.
That link will get people to the template notebook you prepared, and
they can click "Open in CoCalc" to open a copy of the notebook in CoCalc.

**Comment by haraldschilly** [comment]
If you're not signed in and just want to quickly do something in Sage, you could open https://cocalc.com/app?anonymous=sagews ... this gives you a sage worksheet. I mean, it doesn't fit what you want to do, but for someone else it's also a possibility. It's also not as quick as sagecell or WA, since it basically initializes everything you need to run sage in a project. It also keeps the data for a while.
