### ISSUE TITLE
use BALLOT BOX WITH CHECK instead of BALLOT BOX WITH BOLD CHECK for checked boxes in md, etc

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4772]
This is how the two characters appear with Verdana on macOS 10.1.5 with Chrome configured to use Verdana as the default font.

<img width="493" alt="ballot-box-checked-verdana" src="https://user-images.githubusercontent.com/528072/88844231-fba72400-d1a7-11ea-9e2a-5c4db148c485.png">

**Comment by williamstein** [comment]
Instead of an image, can you paste the actual characters here...?

**Comment by williamstein** [comment]
I now remember why I did NOT do what you want by default. For me, this is what your suggestion looks like:

![image](https://user-images.githubusercontent.com/1276278/88849039-23918a00-d19e-11ea-94c7-97e105c1a174.png)

I don't know why it looks so weird in the rendered view.  In codemirror it looks fine.  I'll leave this for now, but it is weird for me, very weird.

![image](https://user-images.githubusercontent.com/1276278/88849171-5a67a000-d19e-11ea-8139-8da8515d223f.png)
