### ISSUE TITLE
deleted files in assignment continue to be pushed to students upon request to republish with OVERWRITE despite forced purge by student

### ISSUE THREAD

**Issue by grouptheory** [sagemathinc/cocalc#4776]
1) restart teacher and student projects
2) On the teacher side, make an assignment directory assignments/01-Datastructures/
        containing 2 files: Assignment_01.ipynb and Assignment.ipynb
3) Assign this to the student
4) On the student account, observe everything is as expected for student (there are 2 files in the assignment directory)
5) On the teacher account, delete 1 of the 2 files in the assignment folder (e.g. delete Assignment.ipynb)
6) Optional (Makes no difference to the issue being reported): On the student account, in a shell, issue rm -rf all files inside  /assignments
7) From the teacher account: republish assignments/01-Datastructures/ to all students, choose the replace without backup option by typing OVERWRITE
8) Observe that from the student account that student's directory has been recreated, but has 2 files even though (a) the teacher's directory has just 1 file and (b) there was an rm -rf on the student side prior to (c) re-publishing of the assignment.

**Comment by williamstein** [comment]
As you describe things above, this seems impossible.  File copying just uses rsync, and it sounds like right before the copy the file doesn't exist on disk anywhere.   Are you sure the file isn't being created in some other way?  

Of course, we'll eventually find time to try to reproduce this.

WORKAROUND: Note that you can easily always run a terminal command in ALL students projects if you need to via the panel for running a command in course configuration.

**Comment by grouptheory** [comment]
Please close this issue. I am retracting it as operator error.

My expectation would be that if I ask to re-publish an assignment and **replace** what students have, the system would:

1) on the teacher's account, destructively update the contents of
         assignments/01-Datastructures/student/
    to agree with the contents of
         assignments/01-Datastructures/ (albeit excluding student/ subdirectory) 

2) Rsync the contents of 
         assignments/01-Datastructures/student/
    out to all students

In actuality, I believe what happens is that step 1 is implemented as:

1) on the teacher's account, non-destructively ***merge*** the contents of
         assignments/01-Datastructures/ (albeit excluding student/ subdirectory) 
    into the contents of
         assignments/01-Datastructures/student/ 

2) Then Rsync the contents of 
         assignments/01-Datastructures/student/
    out to all students

I'm no longer sure if my inference is accurate. Even if it is, I don't know if this is a bug or just wrong expectations of system behavior on my part (I think the whole "OVERWRITE" exchange at the UI led me down this path).  If my expectation is off, please mark closed and let me know.

I realized this after you mentioned rsync -- I went to look at the student/ subdirectory and found the pesky file that kept re-appearing in there.

**Comment by williamstein** [comment]
> I don't know if this is a bug or just wrong expectations of system behavior on my part

It is wrong expectation.  All that happens is that the student/ directory is pushed out.  The directory above that is just a staging area.  Nothing except explicitly clicking "Generate student version" does anything to change student/.     Basically there is no step 1 above at all.     Pushing out an assignment just pushes the student/ subdirectory and that is it.
