### ISSUE TITLE
popout current tab to window

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#478]
sometimes, I want to see two things at the same time. until we have a split window (which might not be flexible enough since it isn't across projects), I want to have a way to "popout" a tab to its own window. This `window.opener` function might allow to even do this in a lightweight fashion, such that a connection to the main smc window is still there.

**Comment by haraldschilly** [comment]
there is shift-tab click … which is more or less what I was thinking back then? well, closing this here.

**Comment by williamstein** [comment]
shift-click on a tab is **undocumented**, so it would at least make sense to come up with a way to document this.  One idea:
 - assign a keyboard shortcut for this action and document that keyboard shortcut where doc the others (in the account page now), and
  - mention the mouse action next to the keyboard shortcut. 

At least then there is some hope to find out about this.

Also, obviously, doc.cocalc.com.
