### ISSUE TITLE
support OpenModelica 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#479]
Trevor Clark requests:

> I am a master's student in electrical engineering. I just had a suggestion for the sagemath project. I know that the project's goals are to provide an alternative to Mathematica, Matlab, Etc. I think for most basic undergraduate things it is already there. However, one area where it is lacking is in simulation of physical systems, like in Simulink or wolfram system modeler. An open source package that could close and potentially eliminate this gap is OpenModelica. It is basically an open source implementation of the Modelica language with a compiler to simulate projects. Wolfram System modeler uses the modelica  language https://openmodelica.org/. I think there would be a fair amount of interest in being able to sign up for a sagemathcloud project and be able to use cloud computing to do simulation of complex physical systems systems.

And then

> Thanks for the reply. While you can use it in a GUI, you can just as easily use it from the command line. In fact there is already a program, OMNotebook, that the OpenModelica project maintains, that is similar to the notebook interface of sage or jupyter. The tutorials for OpenModelica are in in this notebook type interface. OMNotebook is a standalone application and not a web application so there may be some work that needs to be done to use OpenModelica in the sagemathcloud in that capacity. However, being able to call the OMCompiler and be able to run simulations, even if just from the command line, and then be able to do data analysis/plots in sage or python seems like it would be useful.  Another option that seems like it would be more useful is that there is already a python interface to OpenModelica, https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/ompython.html. So it seems that this could be used in jupyter notebook.

Indeed, we should look into installing this; I think they make it easy for Ubuntu.

**Comment by tkuraku** [comment]
As of OpenModelica 1.11.0
https://openmodelica.org/newss/179-february-6-2017-openmodelica-1-11-0-released
There is now a Jupyter Notebook mode available.

**Comment by haraldschilly** [comment]
This is a teaser for OMEdit in CoCalc's upcoming X11 emulation

![screenshot from 2018-10-25 11-28-52](https://user-images.githubusercontent.com/207405/47490530-364c9180-d849-11e8-92ee-95a702a1d44a.png)

**Comment by tkuraku** [comment]
that looks great!
