### ISSUE TITLE
sometimes creating a folder in home directory with the UI stalls at "Loading..."

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4790]
Seen with macOS 10.15.5 on Chrome Version 84.0.4147.105 (Official Build) (64-bit) and Firefox 79.0 (64-bit).

1. Open a project. It can be stopped or running. (If stopped, wait for it to start before proceeding.)
1. Open Files tab and set path to home directory.
1. In "Search or create file" blank, type some new folder name followed by a slash, for example `TEST123/`, and hit Enter.
1. Note that screen appears stuck spinning at "Loading...". This lasts for at least a minute.
1. Click refresh to see the Files view in the new folder.

Also appears using "(+)New", enter folder name, and click "Folder" at right.

Does NOT appear when creating folders below level of home directory.

**Comment by williamstein** [comment]
Is this something you see every time in any project?

**Comment by DrXyzzy** [comment]
yes, every time

**Comment by DrXyzzy** [comment]
I'll try a new project

**Comment by DrXyzzy** [comment]
No. I'm only seeing it in specific projects. It did not appear in a new project

**Comment by williamstein** [comment]
I'm guessing this would go away if you:
 - restart the project
and maybe refresh your browser.

**Comment by DrXyzzy** [comment]
1. Refreshing the browser always cleared the stall for the ongoing directory creation.
1. I just tried restarting a project that had the repeatable stall, and did not refresh my browser. Indeed, **the bug is gone**.

**Comment by williamstein** [comment]
I just observed:
  - a person sitting next to me create a subfolder of a folder (via +New -> type name --> click "folder")
  - See a spinner saying "Loading".

I then looked in my cocalc browser and I immediately saw the new folder they created and could get a listing.  However, they didn't see it until explicitly moving up one directory then back to that folder when everything then worked fine.

**Comment by williamstein** [comment]
The followup is in #0d1f64e8781b520b372e1663c42af65111075fd4

**Comment by williamstein** [comment]
Reopening since @DrXyzzy reports this happened again for him.  

I have not experienced this (or anything like this) when using CoCalc heavily every day in at least month, so it might be related to the operating system or network or some other factor.

**Comment by williamstein** [comment]
- I've put in what *might* be a fix, so closing this... unless it gets reported again.
- I improved the error message in the console.log
