### ISSUE TITLE
lean: unresponsive UI when opening large file

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4799]
get a copy of exactly this file at the referenced revision https://github.com/ImperialCollegeLondon/british-natural-number-game/blob/128f3e2dcbd09ccddce5ae44fe878de5861fa619/src/pos_num.lean

then open it in cocalc via a  click.

for me, with firefox, everything freezes up and I get the yellow warning bar that the page is unresponsive.

when I wait, it's also interesting to share: it resolves to show some intermediate state, but it seems like it is getting stuck. in the situation I'm in right now, it says " [spinner] Parsing at line 698  (Processing lines 698-1268)" … but the lean process is idle. it's like that for at least a minute. no error in the js console.

**Comment by williamstein** [comment]
I consider our lean support deprecated and see no point in fixing or maintaining it further.  Instead, use vscode via a compute server or in a project. 

I especially don't care about scalability issues for this old lean stuff.
