### ISSUE TITLE
course: python exporting grades does not sanitize fields

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4808]
a name like `First L'ast`, i.e. with an `'`, will end up as 

```
students = [
    {'name':'First L'ast', 'id':'1ea6 ...
```

and email addresses as well, e.g. `'email':'hsy+apo'stro@cocalc.com'`

and hence break the python code. This means there is no sanitization for backslashes and apostrophes.

**Comment by williamstein** [comment]
The fix isn't to "sanitize", but just tuse JSON.stringify instead of some horrendous dumb hack that is so bad I hope I didn't write it...
