### ISSUE TITLE
Rmd: optionally, only build upon explicit request

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4821]
don't build Rmd automatically on save, but rather only when requested via build button or keyboard shortcut

**Comment by slel** [comment]
In user preferences, there is a checkbox setting:

- [ ] Build on save: build LaTex file whenever it is saved to disk

which allows the user to choose whether CoCalc will "automatically
typeset on save" (including auto-save); I think the default is "on"
which likely makes it attractive to new users but basically means
it's continually typesetting when you edit a document.

The preference could be changed to

- [ ] Build on save: build LaTeX or Rmd file whenever it is saved to disk

It would also be nice if unchecking this setting also disabled
"Build on opening new .tex (or .rmd) document". So far, even
with the setting unchecked, opening a new .tex document
triggers a build.
