### ISSUE TITLE
Jupyter / nbgrader: batch conversion of cell types

### ISSUE THREAD

**Issue by gabindu** [sagemathinc/cocalc#4846]
In large notebooks, it _could_ be useful to batch convert **all** cells of a particular type into another, for example all "auto-graded" cells into "manually-graded" cells - without touching the other cell types.

In other words, a **"Convert all (selected) type A cells to type B"** function.

**Comment by williamstein** [comment]
This is pretty vague and the UI could be complicated. Presumably this can also be solved in a cocalc-agnostic way using a Python (or other) script.
