### ISSUE TITLE
jupyter fails to start if file "calendar.py" in home dir

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4847]
For some reason, starting the jupyter kernel picks up a file `calendar.py` in the home directory (or well, maybe in the same directory where the notebook is, because that's where it is started?)

In any case, to replicate:

`~/calendar.py`:

```
x = "foo"
```

and then a `file.ipynb`, select python3  kernel, and nothing will work.

Running the console in the terminal shows this error:

```
~$ jupyter console --kernel=python3
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 5, in <module>
    from jupyter_console.app import main
  File "/usr/local/lib/python3.8/dist-packages/jupyter_console/app.py", line 22, in <module>
    from jupyter_client.consoleapp import (
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/consoleapp.py", line 30, in <module>
    from .session import Session
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/session.py", line 47, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/jsonutil.py", line 11, in <module>
    from dateutil.parser import parse as _dateutil_parse
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 39, in <module>
    from calendar import monthrange
ImportError: cannot import name 'monthrange' from 'calendar' (/home/user/calendar.py)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/local/lib/python3.8/dist-packages/requests/__init__.py", line 120, in <module>
    from . import utils
  File "/usr/local/lib/python3.8/dist-packages/requests/utils.py", line 27, in <module>
    from ._internal_utils import to_native_string
  File "/usr/local/lib/python3.8/dist-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/local/lib/python3.8/dist-packages/requests/compat.py", line 60, in <module>
    from http import cookiejar as cookielib
  File "/usr/lib/python3.8/http/cookiejar.py", line 39, in <module>
    from calendar import timegm
ImportError: cannot import name 'timegm' from 'calendar' (/home/user/calendar.py)

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 5, in <module>
    from jupyter_console.app import main
  File "/usr/local/lib/python3.8/dist-packages/jupyter_console/app.py", line 22, in <module>
    from jupyter_client.consoleapp import (
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/consoleapp.py", line 30, in <module>
    from .session import Session
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/session.py", line 47, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/jsonutil.py", line 11, in <module>
    from dateutil.parser import parse as _dateutil_parse
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 39, in <module>
    from calendar import monthrange
ImportError: cannot import name 'monthrange' from 'calendar' (/home/user/calendar.py)
```

**workaround** rename the file to `_calendar.py`

**Comment by williamstein** [comment]
Oh Python!

**Comment by williamstein** [comment]
It looks like the Python path for the system-wide Ubuntu Python3 starts with '':
```
~/cocalc/src$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/cocalc/lib/python3/site-packages']
```

This documents '' in sys.path:  https://docs.python.org/2/library/sys.html#sys.path

The correct calendar module is at: /usr/lib/python3.8/calendar.py

This is part of the Python standard library: https://docs.python.org/3/library/calendar.html

You can make an empty file for anything that is part of the standard library and written in py and it imports the local version first:

```
~$ touch datetime.py
~$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.__file__
'/home/user/datetime.py'
```

Honestly this behavior is really disturbing.  For example, imagine I'm hard at work on some serious coding and I've written dozens of .py files.  At some point, I just randomly happen to name a file ` shelve.py`.  Now boom, my Python3 install is potentially completely broken.  Absolutely any package out there (installed systemwide) could break during load if it happens to (directly or indirectly) import shelve.   That's just ridiculous.

This is definitely not a mistake in how you installed Ubuntu, as the following happens on my laptop:
```
wstein@wsl:~$ more a.py
import calendar, sys
print(sys.path)
print(calendar.__file__)
wstein@wsl:~$ python3 a.py
['/home/wstein', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
/home/wstein/calendar.py
```

I'm tagging this "upstream", but probably the right fix is to change *our* implementation of Jupyter to at least clearly expose the error in starting a kernel, if possible.  Is that possible though?  That's probably the very best we can hope for here.

---

Other posts about this same "feature" of Python:

- https://groups.google.com/g/apscheduler/c/LfraOqipYJw
- https://stackoverflow.com/questions/39496987/i-am-having-trouble-using-or-importing-matplotlib-this-is-the-first-line-of-my

---

**Comment by haraldschilly** [comment]
Yes, what you wrote is exactly what I think is going on. Thanks for checking. My idea is to use our `/ext/bin/python3-nosite` wrapper, but well, it has this empty dir in `sys.path` as well. So, that means I have to tweak it a bit, but at least we have something to tweak under our control. Once it behaves as we want, we can use it instead of python3 in the kernel spec. It will be interesting to see how the actual python environment in the kernel instance will look like, though. I hope it's not too distorted.

Exposing the kernel startup error is certainly a good idea (not just python specific, for all kernels). I don't know if there is a ticket for this – if not there should be one.

**Comment by haraldschilly** [comment]
Oh well, after reading the documentation ... hmm… not sure if my plan works. Running the kernel in an empty temp dir is my only other thought, but that's obviously bad – unless we have a way to switch the working dir after the kernel started. We might be able to hack this for python, but there is probably no universal way.

**Comment by williamstein** [comment]
It's not clear to me that we should fix or workaround this bug, since it is a general Python issue that anybody would hit on any platform, and the python devs chose not to change python for some reason to behave differently.   Anyway, not clear...

But +1 to  exposing the kernel start error.

**Comment by williamstein** [comment]
I wouldn't worry too much about it, given the frequency of this sort of support request.  Also, when I google searched for this sort of error, it does come up periodically... but NOT that much.

**Comment by williamstein** [comment]
I also think if people could see the error produced when attempting to start the kernel, they would likely be able to solve the problem for themselves.

**Comment by haraldschilly** [comment]
well, something similar happens for sage and `code.py`.

IMHO the real solution is to surface such jupyter kernel startup errors. The associated stacktrace  immediately shows that a local file is picked up. Beyond that, for python we could even show an explanation, mentioning that local files with "common names" in the home directory can cause issues...

**Comment by williamstein** [comment]
> IMHO the real solution is to surface such jupyter kernel startup errors. 

I agree, and I'm working on this now.  Basically we just need to get the stdout and stderr from the subprocess that execa spawn... then do something useful with them.  Not only will this surface the error, but it will also provide other useful information, since stdout gives the options necessary to get a command line terminal connected to the same kernel.

**Comment by williamstein** [comment]
Here's what I mean by the terminal remark:

![image](https://user-images.githubusercontent.com/1276278/100830697-153bcf00-3419-11eb-85bc-202cab272e6b.png)

Note that the left is a notebook and the right is a command line, and they are interacting with the *same* Jupyter kernel.

**Comment by williamstein** [comment]
This should also make it relatively easy to have a frame with a Jupyter classic server pointed at the exact same kernel.  This could be very useful as an escape hatch to use any extension or obscure classical functionality... just a little bit.
