### ISSUE TITLE
cocalc nbgrader does not insert code stubs for octave kernel

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4857]
1. Open a jupyter notebook and set the kernel to Octave.
1. Choose "View" / "Create assignment (nbgrader)".
1. Start a new cell and select "Manually graded answer", "Autograded answer", "Autograder tests", etc.
1. Note that no code stub is inserted.

Reported by Taweesak Samanchuen.

**Comment by haraldschilly** [comment]
I'm happy to add something, but what's the "canonical" test/assert function/statement in octave?

**Comment by haraldschilly** [comment]
this looks good: https://octave.sourceforge.io/octave/function/assert.html
