### ISSUE TITLE
terminal: mouse clicks are ignored

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4880]
I just noticed that clicking on a terminal no longer issues click commands to a running app, like htop. I don't know when this broke ... a few weeks ago it was certainly working.

**Comment by williamstein** [comment]
We recently upgraded to the latest xtermjs, so maybe something changed.

**Comment by williamstein** [comment]
Since I don't use this functionality at all, can you post examples steps to reproduce it?

**Comment by williamstein** [comment]
@haraldschilly ping

**Comment by haraldschilly** [comment]
I don't know what to do to reproduce it. If you click somewhere it should register that there is a click. 

I found [this](https://stackoverflow.com/questions/5966903/how-to-get-mousemove-and-mouseclick-in-bash) and well, if I run `echo -e "\e[?1000h"` in  a local linux terminal, I see some codes being echoed back. if I do that in cocalc, nothing appears. An example application is htop.

**Comment by williamstein** [comment]
@haraldschilly  -- Is there any chance you mean "mouse clicks" even though you wrote "keyboard clicks"?

**Comment by haraldschilly** [comment]
oh yes, lol

**Comment by haraldschilly** [comment]
Funny thing: today I accidentally clicked in a terminal with `htop` and it recognized my click. That's a surprise! I should try to figure out which version brought this back, such that we at least know what could have been the cause for fixing this.

**Comment by williamstein** [comment]
I upgraded us to xterm 5.x recently, so maybe that's what helped?

**Comment by haraldschilly** [comment]
I tried to go back in time. All versions of static I could test have this working. I.e. the oldest release I know to work is `app-1.110.4.html`. I'm closing this ticket. … and unrelated to this, we should clean up those old app versions.
