### ISSUE TITLE
hub/email: recreate smtp server instance when config changes

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4881]
In https://github.com/sagemathinc/cocalc/blob/master/src/smc-hub/email.ts `init_smtp_server`, record the settings (as a hashed key?) that were used to instantiate the server and recreate it if the settings change.

**Comment by williamstein** [comment]
Alternatively, add a message to the frontend UI saying "you must restart the server".

Or alternatively only cache the setting for a minute.
