### ISSUE TITLE
properly handling opening cocalc server urls

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4889]
E.g.,
```
https://cocalc.com/[project_id]/server/8888/
```

Requested by:  Steven Clontz

**Comment by mforbes** [comment]
Not sure exactly what this issue refers to, but it would be really nice if there was an easy way to get the `[project_id]` from a script (so I can tell users where to point their browser when running a server... which may be the point here:-)

**Comment by williamstein** [comment]
```
echo $COCALC_PROJECT_ID
45f4aab5-7698-4ac8-9f63-9fd307401ad7
```

**Comment by mforbes** [comment]
`COCALC_PROJECT_ID` is not defined in my project for some reason.  Note: I am ssh'ing in.

**Comment by StevenClontz** [comment]
@mforbes if this is still helpful for you, you may be interested in the solution we use at https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/utils.py#L166

**Comment by williamstein** [comment]
@mforbes yep -- project_id is defined in `~/.smc/info.json`, which will exist anywhere you are in a cocalc project...
