### ISSUE TITLE
can't save a tex file, can't clean auxiliary files

### ISSUE THREAD

**Issue by rholland** [sagemathinc/cocalc#4897]
I just purchased a standard subscription.  I am trying to edit and build a simple tex file I uploaded.  It builds and displays fine.  

1. The save button is green but when I mouse over I get the prohibition symbol.  I can't save the changes.

2.  When I try to clean auxiliary files the clean operation never finishes.  It sticks on "running"

Is there a file permission issue?  Where do I set that?  Do I have to use the terminal?

note:  I checked and the file has read write permissions

**Comment by williamstein** [comment]
> The save button is green but when I mouse over I get the prohibition symbol. I can't save the changes.

That means the file is already saved.    You can confirm this by downloading the file or viewing it directly using vim (etc.) in a terminal, or by looking at the output.

If you want to trigger a build and the file is already saved, there is a build button as well.

> When I try to clean auxiliary files the clean operation never finishes. It sticks on "running"

I'm not able to reproduce this with a tex file in my project.  Please open  your tex file and click the Help button in the upper right to create a support request.
