### ISSUE TITLE
in certain widths, the "run" button in a sage worksheet is hidden

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4900]
workaround: "ctrl + minus" to zoom out or convert to ipynb (jupyter) button

![Screenshot from 2020-09-30 10-45-23](https://user-images.githubusercontent.com/207405/94663569-1746bc00-030a-11eb-92e6-50da6d135ddf.png)

**Comment by williamstein** [comment]
workaround: type "shift+enter" instead of using the run button.

**Comment by williamstein** [comment]
no longer true...
