### ISSUE TITLE
Toolbar sometimes can't be viewed on iPad, bottom lines of notebook can't be viewed.

### ISSUE THREAD

**Issue by johnarmstrong5** [sagemathinc/cocalc#4907]
1. If I view a Jupyter notebook in CoCalc using Safari on an iPad, then the last cell of the screen cannot be viewed correctly. I can scroll the screen so that I can see the cell briefly but when I stop the scrolling gesture and the scroll bar moves back to the bottom of the screen the last few lines of text disappear again. I think it could be fixed by automatically adding a margin at the bottom of the body in the CSS for notebooks. This would have the additional advantage that sometimes the bottom of the screen is hidden on an iPad with a keyboard attached by an autocomplete bar that appears when you are typing and you would be able to scroll so that this autocomplete bar doesn't obscure the text you are editing.

2. Although I do not know how to reproduce this, I find that when working on an iPad the cocalc controls (e.g. the browse and save buttons) at the top of the screen are not always visible. Sometimes pressing refresh fixes this, but not always. On Safari I can work around the issue by zooming the screen in and out (Using CMD - and CMD +) but I cannot work around the issue on Google Chrome.

You can install the Google chrome app on an iPad - I have done. I admit that it might be an unusual thing to do - I'm personally not that bothered that chrome doesn't work compared to Safari, but thought it was perhaps useful info for your developers.

It actually happens with different kinds of files. My main concern is with Jupyter notebooks where I can confirm that it definitely occurs as I've seen it today, but I've also experienced the problem when viewing pdfs and (i think) when editing tex files. I say "I think" for the last one as its been a few weeks since I did this and my recollection is a bit hazy.

I have found a way to (sort of) reproduce the problem. If you press CMD - and then CMD + to change the zoom setting when viewing things on an iPad using Safari, you will see that the top menu becomes accessible. I say this "sort of" reproduces the problem because when the problem happens spontaneously the display is slightly different but the effect is similar in that I cannot access the browse menu. One important difference is that refreshing the display fixes the problem when one uses this sequence of events to produce the problem. I don't know if this is truly related to the issue I am experiencing or is a different if visually similar bug. I thought it might be a useful clue as to what was going on.

**Comment by johnarmstrong5** [comment]
![IMG_0185](https://user-images.githubusercontent.com/72192993/94795222-fac38600-03d4-11eb-95e7-5e902b114896.png)

Here's a screenshot showing the issue happening today - you can see there is no option to browse files. It just happens to be an HTML file that I was looking at. Similar issue with other types of file.

**Comment by johnarmstrong5** [comment]
A related issue that may be helpful to look at is that if you create a terminal window and execute a large number of commands you have to scroll all the way back up to the top of the screen to be able to see the file menu and file tabs again. (I currently work round this by using the Jupyter Lab view in a separate tab as it works fairly nicely)

**Comment by williamstein** [comment]
I finally figured out the root cause of this and fixed it in this commit: https://github.com/sagemathinc/cocalc/pull/5674/commits/fe2954afc8188eb72c930a4501ca3e2976afee40
