### ISSUE TITLE
jupyter: global search across all cells

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4912]
Implement a mechanism to search across all cells in the entire notebook.

**Comment by williamstein** [comment]
This is already implemented via:

- switch to command mode
- hit control+A to select all cells
- hit f to bring up the find dialog

I'm not saying it's very good, but it does exist:

![image](https://user-images.githubusercontent.com/1276278/95099588-e937f200-06e4-11eb-86fd-ed66abd95a4c.png)

**Comment by williamstein** [comment]
dup of #3976
