### ISSUE TITLE
Add customizable snippets/text expansion/macro functionality for LaTeX

### ISSUE THREAD

**Issue by totte** [sagemathinc/cocalc#492]
Somewhat related to #1, #428 and #475 - I'd like to be able to define shortcuts such as `!eq` or `%eq` or similar which expand into `\begin{equation}\end{equation}`. There are an abundance of snippets solutions for Vim, have a look at [UltiSnips](https://github.com/sirver/ultisnips) for an example.

**Comment by williamstein** [comment]
One approach:
1. Make the button bars like in %latex mode on Sage worksheets also work in latex docs (planned).
2. Add a way to customize those menus.

**Comment by williamstein** [comment]
No other requests for something like this in 7+ years...  I don't think it really fits the sort of needs of cocalc users.
