### ISSUE TITLE
admin user search: email address shouldn't be case sensitive

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4920]
when I search for an account via an email address, it is case sensitive. it should convert by input to lower-case or ignore the cases.

**Comment by slel** [comment]
Seconded. I think it should be case-insensitive and diacritics-insensitive.

For instance one should get the same results when searching

- Erdős, erdős, Erdös, erdös, Erdos, erdos, ...
- Lelièvre, lelièvre, Lelievre, lelievre, ...

**Comment by williamstein** [comment]
For what @slel wants this might be helpful: https://stackoverflow.com/questions/13596638/function-to-remove-accents-in-postgresql

**Comment by williamstein** [comment]
I just checked and much of the backend converts email addresses to lower case, e.g., when creating the account or when setting a new email address.  Somehow there are 46 (out of over 1 million) accounts with a non-lower case email address, but those appear to have never been used and have no creation date, so maybe they are very old.  So I think the only thing to do for this ticket is convert the email address to lower case when doing the search and that's it.

Regarding removing accents, that could be a different feature request, but I don't want to mix that up with this.

**Comment by slel** [comment]
See #4967 for improving search regarding accents and case.
