### ISSUE TITLE
Terminal on Chrome: AltGr no longer working

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4921]
Im using a German keyboard. To type in some characters like `[` and `\`, I need to press the `AltGr` modifier key and then key 8, 9 ß, etc. This works fine in Firefox (hence a workaround), but stopped working with Chrome, beta version `86.0.4240.72` (and I should mention, I'm on Linux). I don't have a previous chrome version at hand, though.

This is exactly like #2939 … which was solved by updating xterm.js. I'm not reopening this old ticket, though.

**Comment by haraldschilly** [comment]
maybe @slel you can confirm or deny that this issue is back?

**Comment by slel** [comment]
I don't have a machine with Chrome or with Linux to test.
No problem with macOS 10.14.6 Mojave and Opera 70.0.3728.178.
I'll report here if I find the issue resurfaces for me.
Is CoCalc's xterm.js at 4.9.0 (released 2020-09-09)?

**Comment by haraldschilly** [comment]
yes, 4.9.0 https://github.com/sagemathinc/cocalc/blob/ee5a1a47a5f7fd7248dad0d6b7ad8885c07ca11a/src/smc-webapp/package-lock.json#L13332

**Comment by slel** [comment]
Then #3605 is ready to be closed.

Regarding inputting characters which require modifier keys,
I'll try to test on more platforms and browsers with French keyboards.

**Comment by williamstein** [comment]
This is an upstream bug:  https://github.com/xtermjs/xterm.js/issues/3129

**Comment by williamstein** [comment]
Upstream says that Chrome introduced this bug in 86, then **reverted their bug** a few days ago.  So this is a bug in Chrome that has been fixed.

I'm going to close this as there is nothing for us (or even xterm.js) to do.  Reopen if there is.
