### ISSUE TITLE
Add newline before shell prompt when reopening terminal

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#4922]
Often when launching an already existing something.term terminal in CoCalc,
the shell prompt will be displayed without a newline first, and thus end up
on the same line as the prompt from last time the terminal was open.

For example suppose one did `cd` last time that terminal was open,
then restarted the project, and reopened that terminal, one might see:
``` bash
SP cd
SP SP
```
instead of
``` bash
SP cd
SP 
SP 
```
where `SP` above stands for "shell prompt" and  would really be `~$`.

I'm using `SP` above because when using `~$ ` in these code blocks,
GitHub's markdown renderer (at least in the preview) renders both as
``` bash
~$ cd
~$ 
~$ 
```

[Now I need to file an issue to GitHub about this problem when filing
an issue to CoCalc. Where do I do that? ... And what rabbit hole am I
getting into? I need to set a careful recursion bound.]

**Comment by williamstein** [comment]
This doesn't seem to be an issue anymore.  Or, I don't understand the question.
