### ISSUE TITLE
improve nbgrader *regrading* process

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4925]
>  It is useful that when you run nbgrader you can now see the counter in the green box to see how it is progressing (for large classes).  However if you rerun it, it just stays on eg 'Autograded 247/247 assignments'. It would be useful if it reset to 0/247 and counted again as there's no way of knowing how its progressing or estimating how long it will take. An additional thought is that if the user asks to grade 'all' again, that the grades from the last run be reset to empty or dash or (ideally) '-/5' or something to show which ones have been successfully re-marked (number instead of a dash). This would also give confidence that if something went wrong during marking, eg timeouts or system errors' that one wouldn't be collecting an old mark. Especially if you are collecting and processing with a script from the json or csv and therefore not going through them on-screen.

**Comment by novoselt** [comment]
I am tempted to just close it as stale, but overall the point is valid. I think the real missing functionality is "Reset grades" which would set the state "as it is after collecting and before nbgrading". I suspect this can be done entirely in the instructor project, so it can be very fast, while grading 247 assignments takes a very long time regardless of the assignment itself.

**Comment by novoselt** [comment]
Some kind of state reset actually does happen in case of errors, all of these assignments were graded correctly, then I regraded them:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/1a5b97ad-bd81-418c-a531-b89396889ba8)

**Comment by williamstein** [comment]
Closing as unclear.
