### ISSUE TITLE
create a first very basic API to make automating some tasks in SMC possible

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#493]

**Comment by haraldschilly** [comment]
My first ideas towards implementing that:

1. my first question is, if this should be project-centric or around users. The answer is probably, that it should be both. So, my first step would be to use a token-based authentication model. In the project settings and in the user account settings is a box, where you can click and you get a token for the API. 

  * The user token does implicitly follow the security constraints that any normal user has.
  * The token for the project is different ... it can be shared across the collaborators, but it doesn't cross the boundaries of a project. 
  * to make it easier to distinquish this, maybe add a prefix to the tokens...

2. The most natural way to implement the endpoint would be the hub. There, create a versioned entry point for the API. I propose `/api/1/` for version 1 -- below that, a rest api does its usual job. The authentication token is sent in the request header of the http request, i.e. a mapping like `X-SMC-AUTH: s7fa97ezfw9e7f`

Finally, the most interesting question is, with which verbs to start. I think, the first step could be to just list all projects of a user.

**Comment by williamstein** [comment]
I created this issue for Paul of Datasift who -- after several years -- is the only actual user ever to serious request an API.    Rather than guess at use cases, I think we should just see what his minimal requirements are, and start by implementing something that satisfies them.

**Comment by williamstein** [comment]
Here's a private google doc about this from Paul: https://docs.google.com/document/d/13mRnSCyQ-EyKgbcM3fGZXekUlwJglnIA4eBxWDRD-z4/edit#heading=h.rx7p3no585vj

**Comment by paulsmart** [comment]
Allow me to elaborate...

I suggest endpoints are provisioned to allow automated course creation and assignment. Modifications and other tasks continue to be completed in the UI.

Possible endpoints:
### Course

- /v1/course/create
  - Send JSON object containing:
    - name,description, quota, invite text
  - Receive JSON object containing:
    - course identifier
- /v1/course/list
  - Send no payload
    - Receive JSON object of all courses
  - Send course identifier
    - Receive JSON object with details of specified course
- /v1/course/delete
  - Send course identifier

### Assignment

- /v1/assignment/add
  - Send JSON object containing:
    - Folder name
  - Receive JSON object containing:
    - Assignment identifier
- /v1/assignment/remove
  - Send JSON object containing:
    - Folder name
- /v1/assignment/list
  - Send JSON object containing:
    - Course identifier
  - Receive JSON object containing:
    - List of assignments for the course
- /v1/assignment/assign
  - Send JSON object containing:
    - course identifier, email address, assignment identifier

### Student

- /v1/student/add
  - Send JSON object containing:
    - Course identifier, email address, send email (boolean)
- /v1/student/remove
  - Send JSON object containing:
    - Course identifier, email address
- /v1/student/list
  - Send course identifier
    - Receive JSON object of all students
  - Send course identifier and email address
    - Receive JSON object with details of student’s assignments

## Zapier Alternative
Zapier connects multiple web applications. For example, when someone registers for a training event on Eventbrite, Zapier notices and creates the same registration in GoToTraining.

My training administration system will soon be integrating with Zapier. If you could also integrate with Zapier, it removes the need for an API, lowers the barriers to automation for all your customers and would accelerate commercial adoption of SMC.

**Comment by haraldschilly** [comment]
also found https://github.com/sagemath/cloud/issues/60 from a long time ago …

**Comment by timothyclemansinsea** [comment]
I'd like the ability to modify files via the API. A use case for this is having a Chrome plugin that can modify a browser history file for me. Using this history I would be able to a sync a worksheet with a Udacity url.

**Comment by williamstein** [comment]
See https://github.com/sagemathinc/smc/issues/1524 for a specific case of API use.

**Comment by brianfields** [comment]
Hi @williamstein ! It's Brian from Minerva. We've created a [google doc](https://docs.google.com/document/d/13pepq9x6LQpF1dLZGkAXRcwZ9HSG7kFpIMUBfh1CVnM) with what we'd love to see from a SMC API. Please make any comments/ask any questions.

**Comment by haraldschilly** [comment]
@brianfields I've looked at it, and well, we have to work this out in more detail to realize it. It's also a bit of an overlap with existing capabilities of SMC (i.e. your course feature, of distributing files via copying them around, is identical to how SMC courses copy files). Other points, like such an access token for any files, doesn't exist in SMC. I'm wondering how we should proceed best. Probably I should start writing down comments and questions in that file, which might lead to confusion on your side but should have the effect of clearing up how SMC work for you. I also have to figure out what Minerva is actually doing and what its technical "primitives" are and how they're combined together.

**Comment by brianfields** [comment]
Hi @haraldschilly. Our overall goal is to embed SageMathCloud into our real-time learning seminar platform. We are flexible as to exactly how it works, but the key requirement of the API is that we can create, copy, and share files without the user interacting with SageMathCloud's interface. That way (for example), the professor could place a particular Jupyter notebook on-screen and everyone in class will also see that notebook on-screen. One way to visualize it is Google Hangouts with a lot of classroom/learning features.

We've met a couple of times with @williamstein, and I see how the document I provided might be confusing without that context.  We'd be happy to meet to discuss with you.

**Comment by williamstein** [comment]
Work in progress here: https://github.com/sagemathinc/cocalc/tree/json-api

**Comment by williamstein** [comment]
we now have an api -- it's live...

**Comment by haraldschilly** [comment]
Over night I had the thought this should be at first a "private beta". I.e.
admins have a checkbox in the UI to additionally confirm that the token is
active and users have to contact email support to enable it. That way we
know who uses this and we can collect feedback for the purpose of how this
is used.

**Comment by williamstein** [comment]
> That way we know who uses this and we can collect feedback for the purpose of how this
is used.

We already know who has a token.   If we want to know exactly how this is used, we should record all API calls in the database - want to implement that? -- it would be a good ticket.

In any case, nobody is going to use this without contacting us, as the first thing it says in the UI when you create an api key is "this is completely undocumented; contact us."...

Regarding security/etc., the html API is more restrictive than the existing websocket api.
