### ISSUE TITLE
cocalc crash

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4937]
Heh, I finally got one:

![image](https://user-images.githubusercontent.com/1276278/95762773-0465ad00-0c63-11eb-9f10-11dcba2f2443.png)

**Comment by williamstein** [comment]
@haraldschilly this is in new code you just introduced, which starts out like this:
```
export function useProjectStatus(actions) {
  const project_id: string = actions.project_id;
```
I'm not surprised this randomly crashes, since actions can be null.

**Comment by haraldschilly** [comment]
ok, interesting. Shouldn't then `useActions` say its return value could be nullish? or is this just in that case here possible and not in general!?
