### ISSUE TITLE
autocomplete bibtex

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/cocalc#494]
ShareLaTeX just announced this:

> We've done a lot to improve the citation and references workflow in ShareLaTeX. The first thing is auto-completion of keys from your .bib files:
> 
> More recently we've also added the ability to search through your bibliography files by author, title, year or journal to help you find the reference you want:

Seems like this could be useful here too, though if there is more than one .bib file in a project could be challenging to decide which one...  hth.

**Comment by williamstein** [comment]
> Seems like this could be useful here too, though if there is more than one .bib file in a project could be challenging to decide which one... hth.

Just use the ones that are referenced in the latex build log (or the latex file itself!).

**Comment by williamstein** [comment]
Closing in favor of #49.
