### ISSUE TITLE
course: heuristic scan of content before assigning it to prevent nbgrader mistake

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4949]
CoCalc courses are very general, and can be used without Jupyter or nbgrader at all.  E.g., they could be used for LaTeX files, or markdown, or C programs.  However, one common special case is using a course with nbgrader, and in that case the instructor must explicitly click "Generate student version" first; otherwise, they could accidentally assign their instructor version of the assignment.

The point of this issue is to make this mistake less likely.  When sending out an assignment, do the following:

1. If there is a student subdirectory in the assignment, do nothing further, since the instructor has clearly not made this mistake.  (We already scan for a student/ subdir, so this requires no extra work.)
2. Do a recursive grep for nbgrader metadata in ipynb files. This will require some tricky Linux command line (maybe with xargs and find and some pipes).   If anything is found, display a warning message.  If not, assign as usual.   Displaying a warning message after doing an asynchronous check is going to complicate the UI and is a good opportunity for bugs, so be careful with implementing this.  Also, this will slow down (in random ways) the generic non-nbgrader usage of course assignments, so again make so there is something clear in the UI that indicates what is happening.

Is there anything else to scan for.

**Comment by haraldschilly** [comment]
I wrote a python and jq one-liner to check for an nbgrader metadata field. In both cases, the return value is 0 if it has nbgrader somewhere. I think the python solution is better, because jq might not be installed. It's also just for one file, but it is easy to extend this to all ipynb file in a directory.

```
python3 -c "import json, sys; has_nbgrader = lambda cell: 'nbgrader' in cell.get('metadata', {}); cells = json.load(open(sys.argv[1])).get('cells', []); sys.exit(0 if any(filter(has_nbgrader, cells)) else 1)" nbgrader.ipynb
```

```
jq -e '.cells[].metadata | select(.nbgrader?)' nbgrader.ipynb > /dev/null
```

**Comment by williamstein** [comment]
@haraldschilly thanks.  I was looking at the course code and realized it already has functionality to read all the ipynb files with nbgrader metadata, since it needs that for determine the instructor ipynb files for the purposes of autograding.
