### ISSUE TITLE
widget callbacks not working

### ISSUE THREAD

**Issue by SerhiiPok** [sagemathinc/cocalc#4977]
Hi, I cannot find online whether this is intended behavior but widget callbacks are not working for me.

code 
```
ticker_input = widg.Text(value = 'AAPL')
display(ticker_input)
def reload_quotes(ticker):
    display(request(ticker.value, 'compact').head())
ticker_input.on_submit(reload_quotes)
```
displays a pandas dataframe (return by request()) in the classical notebook but not in the cocalc notebook

Best,Sergey

**Comment by williamstein** [comment]
this should now be implemented.
