### ISSUE TITLE
jupyter: kernel selector headers off

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4981]
the headers in the jupyter kernel selection panel are no longer full width paragraphs. something strange must have happened with div/col/row/whatever :thinking: 

![Screenshot from 2020-11-01 10-16-48](https://user-images.githubusercontent.com/207405/97799028-89713000-1c2b-11eb-9e34-6926889124b9.png)

**Comment by williamstein** [comment]
This was surely caused by me trying to port this code to antd (from bootstrap)...

**Comment by haraldschilly** [comment]
I fixed this
