### ISSUE TITLE
allow license managers to dump raw license utilization data to a file

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4987]
For license managers, under "Account" / "Licenses", allow download of raw data for license utilization for projects. Something like the following:
- offer a dialog to select license and date range
- provide a table (csv) of e.g. all project sessions using the license that started within the selected date range:
  - total duration
  - project title
  - project id
- for student projects, provide a table with the fields below in addition to those above
  - teacher project
  - teacher project id
  - course_file

Default date range could be from the timestamp when the license was first active until the present day. For license subscriptions, replace first active date with start of current period.

This could be similar in operation to requesting the student file use data for an assignment under [Export student file use](https://doc.cocalc.com/teaching-tips_and_tricks.html#export-student-file-use).

**Comment by novoselt** [comment]
It does not seem to be requested often.
