### ISSUE TITLE
matplotlib.animation.ArtistAnimation.to_jshtml() output does not appear

### ISSUE THREAD

**Issue by cmichal2** [sagemathinc/cocalc#4992]
The `to_jshtml()` method for making animations with matplotlib doesn't seem to work. When executed, a new button that says "Fetch additional output..." appears. When this button is clicked the control widgets for animation playback appear, but the actual animation content is missing.  A minimal example that shows this behaviour is pasted in below. The example works fine in classic Jupyter, but doesn't work in cocalc. Ideally the animation and playback controls would appear as the cell output, without having to "Fetch additional output..." 

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML
fig = plt.figure()
ims = []
for i in np.arange(10):  # create 10 images, store them in ims
    base = np.random.randn(20,20)
    ims.append((plt.pcolormesh(base), ))

imani = animation.ArtistAnimation(fig, ims, interval=50,repeat=False)
plt.close()
HTML(imani.to_jshtml())
```

**Comment by cmichal2** [comment]
I spent a little bit more time looking at this, I think the javascript is being sanitized out. There seems to be something not quite right with the html sanitization generally because when a notebook with other inserted HTML is "Halt"ed and reopened, it seems that even the HTML that did display properly before is then sanitized away. My understanding is that shouldn't happen if the notebook is opened by the same user that created the output.

**Comment by williamstein** [comment]
This example now works for me, after installing ipympl, though maybe it is slow:

```py
%matplotlib widgets

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

stepsize = 0.5
num_steps = 20
num_trials = 5

final_position = []

for _ in range(num_trials):
    pos = np.array([0, 0])
    path = []
    for i in range(num_steps):
        pos = pos + np.random.normal(0, stepsize, 2)
        path.append(pos)
    final_position.append(np.array(path))
    
x = [final_position[i][:,0] for i in range(len(final_position))]
y = [final_position[j][:,1] for j in range(len(final_position))]

fig = plt.figure(figsize=(10,6))
ax = fig.add_subplot()
fig.subplots_adjust(left=0.1, right=0.85)

cmap = plt.get_cmap('tab10')

def animate(frame):
    step_num = frame % (num_steps)
    trial_num = frame//(num_steps)
    color = cmap(trial_num % 10)
    if step_num == num_steps-1:
        label = f"Trial = {trial_num+1}"
    else:
        label = None
    ax.plot(x[trial_num][:step_num], y[trial_num][:step_num], color = color, ls = '-',linewidth = 0.5,
            marker = 'o', ms = 8, mfc = color, mec ='k', zorder = trial_num, label = label)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title(f"Number of trials = {trial_num+1} \nNumber of steps = {step_num+1}")  
    if step_num == num_steps-1:
        ax.legend(fontsize=10, loc='upper left', bbox_to_anchor=(1, 1))
    ax.grid(True)
    
    return ax

fig.suptitle(f"2D random walk simulation for {num_steps} steps over {num_trials} trials.")
ani = FuncAnimation(fig, animate, frames= np.arange(0, (num_steps * num_trials)), interval = 100, repeat = False)
# ani.save('2Drandom_walkfinal.gif', writer = 'pillow')
plt.show()
```

**Comment by williamstein** [comment]
In any case, I can't get this to work.  Running arbitrary javascript from third parties not in an iframe is so dangerous, it has become more and more frowned on.  The script tags in that js that you're rendering just get removed.
