### ISSUE TITLE
course: if you try to add a deleted student, provide a big button to explicitly undelete them

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5002]
Right now you see this message: "Already added (or deleted) student or project collaborator: x@y.z".  However, the problem is that it is not at all obvious how to actually undelete the student.  Adding a big button would make it obvious.

![image](https://user-images.githubusercontent.com/1276278/98765609-62390200-2393-11eb-8870-9b6f84145f48.png)

WORKAROUND: Click "(show 1 deleted student)" right below that message. The deleted students are then at the bottom, and you can undelete them.

**Comment by novoselt** [comment]
#4061 is about improving the message and button visibility too
