### ISSUE TITLE
password reset: wait until websocket connection is established

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5004]
opening the link for a password reset redirects to the webapp, where you see a dialog to enter a new password. however, if the websocket connection isn't established yet, that wont work. 

so, either delay/retry setting the password until the connection works or  block the flow a little bit by showing a loading banner for that dialog box until connected.

**Comment by williamstein** [comment]
Not relevant anymore since we use nextjs now for this and there is no websocket there.
