### ISSUE TITLE
Sage vs Python expressions inside f-string (e.g. ^ = XOR)

### ISSUE THREAD

**Issue by gabindu** [sagemathinc/cocalc#5005]
Using python3's f-strings with a Sage kernel can have surprising results:

```
print( f'4^2= {4^2}' )
```
results in `6`, since it actually uses Python's XOR operator for `^`, instead of Sage's exponentiation.

I'm suspecting that this might also affect other things that SAGE changes versus "vanilla" Python - so I think this should be looked into.

**Comment by haraldschilly** [comment]
I would say this is clearly an upstream issue and I've marked it as such. The issue tracker is here https://trac.sagemath.org/ I didn't check if this is already an existing ticket.

**Comment by gabindu** [comment]
ah, sorry about that, didn't think about checking upstream first.  There is indeed already a ticket for this which just barely missed the 9.2 milestone, so I guess it'll be part of Sage 9.3:   https://trac.sagemath.org/ticket/28974
