### ISSUE TITLE
Pre-install nnn file manager from apt

### ISSUE THREAD

**Issue by romor001** [sagemathinc/cocalc#5006]
Miniscule feature request: 

Would be nice to have a light weight file manager on the terminal. `ranger`, `lfm` and `nnn` come to mind. 
Personally I'd prefer nnn. It is only 135k on disk, has very few dependencies and can easily be installed via apt .

**Comment by haraldschilly** [comment]
they're installed. `nnn` is quite confusing for me and `lfm` reminds me of those good old MS DOS days :-)
