### ISSUE TITLE
Allow negative search in notification view

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#5010]
When one clicks the bell icon, the notification view pops up,
featuring a search box which allows to filter notifications.

If one types `abc def` in that box, then only notifications
matching both `abc` and `def` are displayed. Very useful.

It would be nice if, by typing `abc -def` in the search box,
only notifications matching `abc` but *not matching* `def`
were displayed.

Current behaviour: by typing `abc -def` in the search box,
only notifications matching both `abc` and `-def` are
displayed. Of course it's nice to also be able to get that;
once negative search is implemented, one would expect
to get that by typing `abc "-def"` in the search box.

Use case for the requested feature: teaching with CoCalc.
When a course has several groups and a colleague is teaching
their group, there can be a lot of notifications related to that
teaching activity, which one may want to filter out in order to
be able to focus on notifications not pertaining to that course.

**Comment by williamstein** [comment]
This is a good idea, probably easy to implement, and is related to https://github.com/sagemathinc/cocalc/issues/4968

**Comment by williamstein** [comment]
I did this.  I also did it in such a way that applies uniformly to basically all searches everywhere (e.g., on the project listing page, file listings, tasks, students in a class, etc.)
