### ISSUE TITLE
nbgrader: make triggering failure on a special string (e.g., "error") in stdout be optional and configurable

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5014]
To support the R Jupyter kernel with nbgrader, we made it so that if stdout contains the string `error`, then autograding considers that answer to be wrong.     This is very confusing because for most kernels (e.g., python) this isn't needed, and sometimes people put "error" in legitimate output.  

Solution: 
1. move this behavior to a configurable default-off option in nbgrader configuration.
2. Put a message in the R template code reminding the instructor that they have to enable this option.

Alternatively, is there any way to get R to write to stderr instead of stdout in the autograder template examples?  I only assumed it is hard because I think @haraldschilly  said so, but I didn't really try for myself.   If we can change the template and get rid of this hack, that would be better.     (This may inconvenience one teacher using R.)

**Comment by haraldschilly** [comment]
another idea: check for the kernel language – i.e `if ("language" == "r") → check for "error" in stdout` ?

and no, I have no idea how to test for this. a minimal example for a failed nbgrader test is `testthat::expect_equal(1, 2)` which produces

```
"outputs": [
    {
     "ename": "ERROR",
     "evalue": "Error: 1 not equal to 2.\n1/1 mismatches\n[1] 1 - 2 == -1\n",
     "output_type": "error",
     "traceback": [
      "Error: 1 not equal to 2.\n1/1 mismatches\n[1] 1 - 2 == -1\nTraceback:\n",
      "1. testthat::expect_equal(1, 2)",
      "2. expect(comp$equal, sprintf(\"%s not equal to %s.\\n%s\", act$lab, \n .     exp$lab, comp$message), info = info)",
      "3. exp_signal(exp)",
      "4. withRestarts(if (expectation_broken(exp)) {\n .     stop(exp)\n . } else {\n .     signalCondition(exp)\n . }, continue_test = function(e) NULL)",
      "5. withOneRestart(expr, restarts[[1L]])",
      "6. doWithOneRestart(return(expr), restart)"
     ]
    }
   ],
```

**Comment by williamstein** [comment]
Thanks.  That output message above might be very helpful!

**Comment by williamstein** [comment]
@haraldschilly believe it or not it gets labeled as traceback if you run that command at the top level but NOT if you run it as part of a test_that block!   R is weird:


![image](https://user-images.githubusercontent.com/1276278/99574423-42559f80-298c-11eb-857f-bc858f5ef85b.png)

**Comment by williamstein** [comment]
Wow, check this out, `error` doesn't even appear in the output when this fails:

![image](https://user-images.githubusercontent.com/1276278/99574665-88126800-298c-11eb-82c2-68dc35a060f1.png)

so the current code doesn't even work in general.

**Comment by haraldschilly** [comment]
hmm, that's very strange. seems like we have to unpack everything in the expression (the curly  brackets in `test_that`) and warn users to not use `test_that` ?

looks like a bug to me that such a test swallows the error in the wrapped expression.

**Comment by williamstein** [comment]
I'm looking at the testthat source code and there seem to be many different "labels" for when things go wrong -- not just "Error" and "Failure", and also the ANSI codes to set the color look like they are used maybe in non-fatal situations.  I don't know enough about R to do much with this mess.   

But we can do what you suggest, which is to only use testthat at the top level and put in a comment telling users not to mess with it.

**Comment by williamstein** [comment]
Then there is an explicit traceback field in the output, which gets properly checked for.

**Comment by williamstein** [comment]
That's what I'll do.

**Comment by williamstein** [comment]
Crap I looked at my code and there is a comment about why we check for "error":
```
      // With Octave assertions output text that contains the word "error".
```

.... so this isn't just a problem with R:

![image](https://user-images.githubusercontent.com/1276278/99576287-a24d4580-298e-11eb-9ca1-e8d68a9827b2.png)

**Comment by williamstein** [comment]
I also tested this with jupyter classic -- same output.

**Comment by williamstein** [comment]
For the record, official nbgrader definitely won't work with Octave -- see the sources https://github.com/jupyter/nbgrader/blob/master/nbgrader/utils.py
```
    elif cell.cell_type == 'code':
        # for code cells, we look at the output. There are three options:
        # 1. output contains an error (no credit);
        # 2. output is a value greater than 0 (partial credit);
        # 3. output is something else, or nothing (full credit).
        for output in cell.outputs:
            # option 1: error, return 0
            if output.output_type == 'error' or output.output_type == "stream" and output.name == "stderr":
                return 0, max_points
            # if not error, then check for option 2, partial credit
            if output.output_type == 'execute_result':
                # is there a single result that can be cast to a float?
                partial_grade = get_partial_grade(output, max_points, log)
                return partial_grade, max_points

        # otherwise, assume all fine and return all the points
        return max_points, max_points
```

OK, official nbgrader indeed does not support octave at all. Here's the open-since-2018 upstream issue: 

https://github.com/jupyter/nbgrader/pull/1038

There is a massive bitrotten PR to add support here: https://github.com/jupyter/nbgrader/pull/1038/files

Interesting code in that PR:
```
def is_validate_error(cell, lang = None, cutoff = 100):
    errors = []
    if lang == 'octave':
        for output in cell.outputs:
            if output.output_type == "stream": 
                if hasattr(output, "text"):
                    if re.match("error: ", output.text): 
                        errors.append(True)
                        if len(errors) >= cutoff:
                            return errors
                    else:
                        errors.append(False)
    else:
        for output in cell.outputs:
            if output.output_type == 'error':
                errors.append(True)
                if len(errors) >= cutoff:
                    return errors
            else:
                errors.append(False)
    return errors
```

So new plan:
  - add in special crappy heuristic hacks for R and octave **only**.
  - since official nbgrader doesn't even work 

Also, there is an example here of R + nbgrader, but I **bet you** it silently fails to mark wrong answers as wrong:  https://github.com/ttimbers/nbgrader_r_demo

**Comment by williamstein** [comment]
See also this PR https://github.com/jupyter/nbgrader/pull/1173 around nbgrader + octave, which was rejected by the nbgrader project.  They just consider this a bug in the octave kernel.  Oh boy.
