### ISSUE TITLE
why does Xpra (x11 desktop) take so long to start?

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5033]
1. Click +New --> X11 desktop
2. In the terminal see that xpra is up and running immediately.
3. Using top see that it is using no cpu
4. Type xclock and see that it still isn't ready.
5. After a minute, type xclock and see that it is working.

I _think_ xpra startup was very fast when I first released X11 desktop, and that there is a regression.  I could be wrong.  Maybe there is a ton of disk IO causing it to be slow.   In any case, it would be nice to understand *why* it is slow.

**Comment by totaam** [comment]
As long as you use the packages from xpra.org and not from downstream, your xpra server should be up and running within 2 to 3 seconds (depending on which options are enabled) - that is, excluding the times it takes to start the vfb, which is beyond xpra's control.
For more details see [faster server startup](https://xpra.org/trac/ticket/2341)

**Comment by williamstein** [comment]
Thanks!! I'll study the logs and try to figure out what happens.  My recollection is that it was seconds, then we upgraded something, and now the overall process takes a minute, which is ridiculous.

**Comment by williamstein** [comment]
I just did a test in cocalc-docker and everyhign fully starts up in **less than 5 seconds**.

I then tried the same thing in a newly started upgraded project on cocalc.com and it took **just over 1 minute**.

Since the actual cocalc part of the software is identical in both cases, the problem might involve:
  - different version of xpra, or
  - very slow high latency disk issues

Any thoughts @haraldschilly ?

**Comment by williamstein** [comment]
On cocalc-docker:
```
xpra --version
```

On cocalc.com:
```
~/tmp$ xpra --version
xpra v4.0.4-r27557
```

Without first using x11 desktop, I just tried this in a cocalc.com project -- 50s just to get the version number!
```
~$ time xpra --version
xpra v4.0.4-r27557

real    0m49.848s
user    0m1.114s
sys     0m4.399s
```

So clearly we are hitting some issue with whatever initialization happens when xpra is imported into python3 (?).  It might not just be a "filesystem is slow issue", since I tried again a minute later in the same terminal and got 35 seconds:
```
~$ time xpra --version
xpra v4.0.4-r27557

real    0m34.367s
user    0m1.049s
sys     0m5.149s
```

Sagemath is another python3 program that stats hundreds of thousands of files on startup, and can be notoriously slow to start, so for comparison:
```
~$ time sage </dev/null
...
real    0m15.235s
~$ time sage </dev/null
...
real    0m6.678s
```

This is really a kucalc issue (not cocalc itself), so maybe I should move the discussion there....

**Comment by williamstein** [comment]
OK, this is way weirder than I thought.

In the source code xpra-4.0.5/xpra/os_util.py of xpra is this code:
```
def find_lib_ldconfig(libname):
    libname = re.escape(libname)

    arch_map = {"x86_64": "libc6,x86-64"}
    arch = arch_map.get(os.uname()[4], "libc6")

    pattern = r'^\s+lib%s\.[^\s]+ \(%s(?:,.*?)?\) => (.*lib%s[^\s]+)' % (libname, arch, libname)

    #try to find ldconfig first, which may not be on the $PATH
    #(it isn't on Debian..)
    ldconfig = "ldconfig"
    for d in ("/sbin", "/usr/sbin"):
        t = os.path.join(d, "ldconfig")
        if os.path.exists(t):
            ldconfig = t
            break
    import subprocess
    p = subprocess.Popen([ldconfig, "-p"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
    data = bytestostr(p.communicate()[0])

    libpath = re.search(pattern, data, re.MULTILINE)        #@UndefinedVariable
    if libpath:
        libpath = libpath.group(1)
    return libpath
```

and running it is VERY slow.  In particular this `p.communicate()` takes 20s+ usually.  And if this is run more than once...

It's just running `ldconfig -p` via the shell and for some reason this locks everything for a LONG time which you can also see directly... and also **doesn't work** (there is no useful output).
```
~/xpra-4.0.5$ time /bin/sh -c /sbin/ldconfig -p
/sbin/ldconfig.real: Can't unlink /lib/x86_64-linux-gnu/libtachyon-mt-thr.so.0
/sbin/ldconfig.real: Can't unlink /lib/x86_64-linux-gnu/libmpichfort.so.12
/sbin/ldconfig.real: Can't unlink /lib/x86_64-linux-gnu/libmpichcxx.so.12
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Read-only file system

real    0m15.773s
user    0m0.533s
sys     0m3.947s
```

Running the exact same thing without /bin/sh works quickly and gives the proper output:
```
~/xpra-4.0.5$ time /sbin/ldconfig -p |wc -l
2907

real    0m0.009s
user    0m0.004s
sys     0m0.006s
```

Thus I suspect this problem would be completely solved by changing this one line of code with subprocess to not use a shell!
```
 p = subprocess.Popen([ldconfig, "-p"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False)
```

Crazy, isn't it?

**Comment by haraldschilly** [comment]
that's super weird. what is ` /sbin/ldconfig.real` actually? some black magic diverts the fast variant to the slow one, when run interactively? 

oh wow, you can run `cat /sbin/ldconfig` to see this. I have no idea what this script does. 

fun fact: `time /sbin/ldconfig.real -p | wc -l` is quick as well … so this is caused by these other commands in the wrapper script.

**Comment by totaam** [comment]
You're hitting this bug: [package fake xinerama](https://www.xpra.org/trac/ticket/2546).
What's weird is that the changeset in that ticket is meant to disable fakexinerama on Debian and Ubuntu, just to avoid this problem. Here's the commit message: _finding the libfakeXinerama library can take a very long time because of 'ldconfig', so don't bother enabling on Debian or Ubuntu_

**Comment by williamstein** [comment]
@totaam maybe official Ubuntu 20.04 doesn't have the fix yet (where we are running).  But thanks for the hint.  I copied /usr/bin/xpra to a local script and added a line to monkey patch the xinerama check as follows:
```
#!/usr/bin/python3

# See https://github.com/sagemathinc/cocalc/issues/5033
import xpra.x11.fakeXinerama;  xpra.x11.fakeXinerama.find_libfakeXinerama = lambda : None

import sys

from xpra.platform import init, set_default_name
set_default_name("Xpra")
init()

from xpra.scripts.main import main
sys.exit(main(sys.argv[0], sys.argv))
```

With this 1-line change, suddenly:

```
~$ time ./myxpra --version
xpra v4.0.4-r27557

real    0m0.228s
```

I then did
```
cp myxpra ~/bin/xpra
```
and starting an X11 Desktop and using it in CoCalc was much faster.

So @haraldschilly can you make a new image and just put this patched xpra startup script somewhere ahead of /usr/bin/xpra in the path?  e.g., it looks like `/ext/bin` would work.   Then when we get a newer Ubuntu package with this bug fixed, we can just remove this workaround.

**Comment by totaam** [comment]
This was caused by a bug in xpra: all subcommands (even including `--version`) generate a default configuration object, and this ended up calling `find_libfakeXinerama`. (not sure when this was changed)

The [fix](https://xpra.org/trac/changeset/28021/xpra) is to use `auto` as a default value on the Linux platforms that should have `libfakeXinerama.so` installed - but those should also have the correct library path already set in `/etc/xpra/conf.d/55_server_x11.conf` (this is done at build time) which shortcuts the `find_library` logic completely.

**Comment by williamstein** [comment]
@totaam Thanks!   It sounds like the fix you're describing will take a while to percolate into official Ubuntu packages?   For now, we're using the above patched xpra startup script, and that is working well for us.  I'm closing this issue as solved.

**Comment by totaam** [comment]
> It sounds like the fix you're describing will take a while to percolate into official Ubuntu packages?

Correct, Debian and Ubuntu packages [never ever have any important bug fixes applied](https://www.xpra.org/trac/wiki/Packaging/DistributionPackages).

**Comment by williamstein** [comment]
Got it.  (I very much understand the difficulty of dealing with packagers and bugfixes from my work on SageMath...).  Thanks for documenting how bad things are with xpra in that table.  I'll put on our todo for cocalc to switch to building xpra from source...
