### ISSUE TITLE
\b in stdout is handled differently in CoCalc Jupyter versus in Jupyter Classic

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5044]
```
big = 999.999999
small = 666.666666E-19
number = 33
string = 'letters'
print("Big is",big,"\b, small is",small,"\b, number is",number,"and string is",string,"\b!")
```

![image](https://user-images.githubusercontent.com/1276278/100629830-9cd0f300-32de-11eb-98a6-2b91b91debb4.png)

**Comment by haraldschilly** [comment]
reminds me of https://github.com/sagemathinc/cocalc/issues/2520

**Comment by williamstein** [comment]
> reminds me of #2520

Yes, and unfortunately the conclusion there is that the only reason this doesn't already work in CoCalc (and nteract?) is that ansi-to-react for some reason doesn't implement \b support.  So the main thing to do here is to double check this now, either upgrade or create an upstream ticket, and mark this issue "upstream".

**Comment by williamstein** [comment]
I checked and this is indeed also broken in nteract v 0.24.1, which also ansi-to-react.  There have been no new releases since mid 2017: https://github.com/nteract/ansi-to-react/releases

And yes this is upstream https://github.com/nteract/ansi-to-react/issues/36

**Comment by williamstein** [comment]
In nteract, note the checkboxes:

![image](https://user-images.githubusercontent.com/1276278/100679822-2e635380-3325-11eb-94d4-c534ceb4fc93.png)

**Comment by williamstein** [comment]
Here's the code in upstream jupyter classic: https://github.com/jupyter/notebook/blob/ebd2b5701c36465bb3ee290797ebca09a6141347/notebook/static/base/js/utils.js#L490

```
    // Remove characters that are overridden by backspace characters
    function fixBackspace(txt) {
        var tmp = txt;
        do {
            txt = tmp;
            // Cancel out anything-but-newline followed by backspace
            tmp = txt.replace(/[^\n]\x08/gm, '');
        } while (tmp.length < txt.length);
        return txt;
    }
```

I'm just going to copy it with a citation into our codebase so that our users will be happy.  I think most people only use a single `\b`, so that should be enough.

It might be better to put this code in ansi-to-react though...

**Comment by williamstein** [comment]
OK, I fixed this in upstream.  Blocked, waiting on somebody to push to npm...
