### ISSUE TITLE
sync/handle patch update queue: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5053]
while doing some development, and in particular, I think was was closing/halting a jupyter notebook and deleting the directory where it is at almost the same time – or a similar kind of edge case like that – I saw this:

![Screenshot from 2020-12-01 19-32-10](https://user-images.githubusercontent.com/207405/100781956-0bf83580-340c-11eb-8ed7-933ec55e1b73.png)

and 

![Screenshot from 2020-12-01 19-32-17](https://user-images.githubusercontent.com/207405/100781965-0f8bbc80-340c-11eb-8b8e-6cb13cacd5da.png)

**Comment by williamstein** [comment]
This makes perfect sense (to me), since it's an async/await loop but there are no tests in it for the object being closed. Fixed.
