### ISSUE TITLE
fix smc-webapp/jupyter/_jupyter.sass

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5059]
* the disabled code must be kept disabled → breaks katex
* the `img svg` selector can't work

IMHO the only good solution here is to explicitly tag img and svg's with an explicit class. the `:not` selector is always matching, because there are elements (like `span` which have no class at all). going with an explicit parent/child selector could theoretically work, but fails if formulas appear in a more deeply nested element, which wasn't anticipated by that exclusion.

**Comment by williamstein** [comment]
Your suggestion is not an option because we need to maintain compatibility
with jupyter classic...

I'll look into this again today.
