### ISSUE TITLE
Fix "Stop Project" acting like it will restart the project

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#5064]
In a running project, visit project settings and press
the "Stop Project" button.

Towards the top of the CoCalc window, CoCalc displays

    Starting...

and occasionally displays this:

    [ Pending ]  Finding a place to run your project.
    If nothing becomes available, reduce dedicated RAM or
    CPU, pay for members only hosting, or contact support.

This seems wrong.

In the worst case it means CoCalc is setting up to start
the project and maybe wasting resources. Or maybe it's
just a display quirk, which would be nice to fix anyway.

**Comment by williamstein** [comment]
I just want to note that this isn't a bug with https://github.com/sagemathinc/cocalc/, but with our kubernetes backend "KuCalc".  It's also purely a display issue (no resources are being wasted).   I don't know how to fix it (yet), though I have looked into a few times.

**Comment by slel** [comment]
Good to know no resources are being wasted.

Stopping the project still displays "Starting..."
for a while before displaying "Stopped".

Not a big deal but hope this gets sorted out.  : )

**Comment by williamstein** [comment]
This is finally properly fixed in the basepath branch now :-)
