### ISSUE TITLE
course: managed assignment directory

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5079]
There is a general need to more tightly control the student's assignment directories. 

* prevent renaming/deleting/etc. of the directory itself
* prevent renaming/deleting of files in the given directory
* optionally, prevent downloads (can't be bullet proof, but removing buttons from the files listing and certain entries from the jupyter notebook and other editors could be done)
* optionally, also prevent uploading files (i.e. students replace a file in the directory)
* ... more ideas?

Conceptually, this could be similar to "published" files, where certain paths are recorded and surfaced in the files listing. Of course, this is not about publishing files but adding additional configuration for specific directories.

**Comment by bermeitinger-b** [comment]
The most pressing issue for us is students uploading locally modified assignment notebooks. Disabling the upload functionality for all these _locked_ folders would be enough for now.

I can see an attack scenario, although it didn't happen yet, that a student would upload a  specially crafted `nose` module which would always return the correct value. A read-only folder (only allowing modifying a file) would circumvent this.

**Comment by haraldschilly** [comment]
Regarding the attack, one option is in the course config, for nbgrader, which is "Grade assignments in a project of your choice". That makes it possible to run the collected notebook (+ the hidden test code) in a different project (i.e. you would create a new empty one + apply the license there). I'm not sure [ /cc @williamstein ] if it just copies the notebook or all files from the assignment, but well, this at least helps with isolating the grade-run from everything else that's in the student's project.

**Comment by bermeitinger-b** [comment]
It copies the whole folder which makes sense because sometimes we distribute multiple files (csv, pkl) with the assignment. They must be copied.

**Comment by novoselt** [comment]
It looks to me like substantial development effort, while problems do not seem to be very common. From the security point of view grading in student projects should be quite good and if students deliberately circumvent the system, it is a very strong ground for disciplinary actions.
