### ISSUE TITLE
Disable file editing when project not running or start project when editing begins

### ISSUE THREAD

**Issue by realtimclemans** [sagemathinc/cocalc#5101]
I lost code because I edited a Jupyter Notebook when the project wasn't running. Maybe start the project when editing begins.

**Comment by williamstein** [comment]
Here's what I see when I try to edit a file and the project isn't running:

![image](https://user-images.githubusercontent.com/1276278/102385383-a450f700-3f82-11eb-9715-5d3b54f7a00c.png)

There's already right now a big red "NOT saved" and a button to start the project.

If there are certain file types that don't properly show "not saved", that would be good to flag...
