### ISSUE TITLE
latex: make it so one sees the output of the process doing the compiling and can control+c it

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5105]
Right now:

1. Create a tex file
2. Build it (let's say it is big, so this takes 10 seconds)
3. See the output

What would obviously be much better is to (a) be able to see the output while 2 is happening, and (b) if there is any interaction be able to participate, and (c) be able to hit control+c and interrupt the run.

This is all possible and probably even quite easy to implement in cocalc using xterm.js...  So let's do it, since it would be cool.

**Comment by haraldschilly** [comment]
same for Rmd. sounds like a dup of https://github.com/sagemathinc/cocalc/issues/4379

**Comment by williamstein** [comment]
> same for Rmd. sounds like a dup of #4379

Yes, it is.  I searched pretty hard before creating this issue, and I didn't find #4379 because it is not labeled with A-LaTeX.  I'll add that label now.
