### ISSUE TITLE
Undo "paste" separately from other typing

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#5110]
To replicate:

Copy some text to the clipboard; type some text;
then hit Ctrl-V to paste; then hit Ctrl-Z to undo.

Example:

Say "differential" is copied in the clipboard; typing without
large pause `pseudo[Ctrl-V]` results in "pseudodifferential";
then hit Ctrl-Z.

Expected:

- only the pasting is undone; we are left with "pseudo";
  this is what happens in most editors

Observed:

- both the pasting and all the previous typing (since the last
  typing pause longer than some threshold) are undone;
  so all of "pseudodifferential" gets removed

**Comment by williamstein** [comment]
Labeling hard and easy, since it depends on the approach which it is :-)

**Comment by williamstein** [comment]
This is now fixed "the easy way" -- refresh your browser.  Hopefully there aren't too many bad side effects....
