### ISSUE TITLE
latex: causes changing parent dir name problems?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5111]
this is something to investigate, I didn't check yet. change the parent dir name, or, maybe even 2 parent dirs and change the grandparent's name, and see if there are issues building the document. also, if synctex works, etc. my suspicion is that this temporary dir for the build directory get's out of sync with the build command. i.e. the build command' temp dir points to an outdated directory or something like that.

**Comment by williamstein** [comment]
I closed my #5173, but note that I#5173 might be clearer, since it had a sequence of steps and a workaround explicitly given.

**Comment by haraldschilly** [comment]
yes, absolutely

**Comment by williamstein** [comment]
too vague...
