### ISSUE TITLE
install and support K3D-jupyter in Jupyter classic (at least)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5125]
This K3D-jupyter https://github.com/K3D-tools/K3D-jupyter looks pretty amazing.  Let's install it systemwide, and also make sure it actually works... at least in Jupyter classic (and maybe JupyterLab?).  Even if integration with cocalc-jupyter might be too hard, it's still very valuable to support Jupyter classic.

**Comment by jasongrout** [comment]
> Even if integration with cocalc-jupyter might be too hard, it's still very valuable to support Jupyter classic.

IIRC, it's an ipywidgets-based package, so if you don't have custom widget support, it may be hard.

I think it works in JupyterLab too - at least there are installation instructions for jlab.

**Comment by williamstein** [comment]
Harald has now installed this in JupyterLab and it works there.  We don't plan to support it in Jupyter classic.

I do plan to support it in CoCalc-Jupyter, and that means I have to implement support for custom widgets.  That's https://github.com/sagemathinc/cocalc/issues/5889
