### ISSUE TITLE
Sample for loop from control dropdown bar of Sage Worksheet is formatted incorrectly

### ISSUE THREAD

**Issue by tomgrubbmath** [sagemathinc/cocalc#5144]
If I select "For-Loop" in the "Control" drop down menu of a Sage Worksheet, it provides:

for i in range(5):
    print i 

as a sample for loop. This fails because the print statement has no parens. A similar problem exists with the while loop and for loop over a list. Photos related:
![image](https://user-images.githubusercontent.com/53013402/103493343-8b9b6a80-4de5-11eb-8dce-e3efd66eb46f.png)

![image](https://user-images.githubusercontent.com/53013402/103493348-92c27880-4de5-11eb-8c6d-cc5c69d1226b.png)

**Comment by williamstein** [comment]
Thanks!
