### ISSUE TITLE
warn about a large jupyter notebook

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5145]
there is already a warning about opening a file that has a large size. beyond that, jupyter notebooks are also getting problematic if they have a large number of cells or a lot of content. the goal of this ticket is to give the user a warning as a feedback, that this is starting to be a problem. one approach is to introduce a harcoded limit, when to show a warning. a more sophisticated one might be to time how long rendering takes. I'm not sure how, but should be more accurate and on point.

**Comment by williamstein** [comment]
I am also willing to re-implement windowing again.  I completely deleted it from our code, but if this is really a problem, I should bring it back.  It would be completely disabled, and exactly when we show this warning message, we could provide some options, one of which is to enable windowing just for this notebook (with a list of caveats).

**Comment by williamstein** [comment]
> problematic if they have a large number of cells or a lot of content.

This is much less the case due to virtualization.  500+ cells works fine, of course, depending on the content.  Also, this ticket is way too generic/vague.
