### ISSUE TITLE
URL links to any cell in a notebook with a copy link button you can hover on to copy it

### ISSUE THREAD

**Issue by jkitchin** [sagemathinc/cocalc#5156]
You can make url links to Markdown headings, and to named anchors that will open the notebook to those locations. I haven't found a way to make url links to code cells though.

I would like to be able to make a url to a code cell that opens the notebook to that cell. This has a few uses:

1. you can reference cells in other notebooks with precision
2. In a notebook chat (or other communication channel) you can make a reference to precisely the cell that you are talking about

This is a feature in colab that is pretty helpful and is implemented by adding this to a notebook URL:
#scrollTo=WF7KTMczLM17&line=3

That would open a notebook to line 3 of a cell with an id of WF7KTMczLM17. I would probably implement it as:

#id=WF7KTMczLM17&line=3

and the line number isn't super critical (but useful for large cells)

I think it would mean assigning a unique ID to each cell, and then a url handler/resolver to open it.

Notes:
I know you can manually add a markdown cell above a code cell  with something like `<a id='some-uuid'></a>` and then later refer to it as `[that Cell](#some-uuid)`, but that is more work than needed in my opinion, I think clicking on a button to get the link and pasting somewhere is about right.

It is true that these links are not super robust, e.g. the cells can disappear, and the line numbers would not point to the same things if the cells are changed. I think that is fine as long as the url resolver fails gracefully.

This doesn't appear to be a feature in Jupyter notebooks or jupyter lab though so I guess it might only work in cocalc.

**Comment by williamstein** [comment]
Fragment link to specific cells now full work. Look at the `#id=...` url fragment whenever you focus a cell. You can then use that as a link like this: `[that Cell](#id=some-uuid)`
