### ISSUE TITLE
Make markdown cells automatically render when you leave them

### ISSUE THREAD

**Issue by jkitchin** [sagemathinc/cocalc#5157]
I think it would be convenient if markdown cells automatically rendered when you leave them while they are in edit mode. This is a behavior from Google colab my students seem to like.

**Comment by williamstein** [comment]
We aim for compatibility with JupyterLab unless there is a good reason not to.   JupyterLab doesn't automatically switch to rendered mode whenever the markdown cell is not focused.

We do have WYSIWYG editing now for markdown cells, which is new since 2021 though.
