### ISSUE TITLE
support the ipycanvas widget in cocalc-jupyter

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5159]
See https://ipycanvas.readthedocs.io/en/latest/

**Comment by williamstein** [comment]
Probably this involves:

1. Installing all the relevant code for the upstream project, and 
2. Porting the frontend code to cocalc-jupyter, since it probably (?) uses the generic widget extensions feature, which we don't support.

**Comment by sheinb** [comment]
I'd add that this would provide a very convenient way to incorporate turtle graphics in a notebook for teaching, along with efficient graphics for games and visualizations like 'game of life'.

**Comment by williamstein** [comment]
This is a custom widget, and our goal with jupyter now is that ALL custom widgets be fully supported.  I just tried this and something mysterious does go wrong:

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/f83efc96-caf9-4cab-9de3-23bcdb7150cb">

This also does not work for my in JupyterLab 3.6:

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/fa698845-6e5c-44ca-8830-74df255222db">

Ipycanvas is also broken for me in a fresh install with JupyterLab 4.2.3:

<img width="1515" alt="image" src="https://github.com/user-attachments/assets/c739b1d1-8bb3-490f-946d-b792f5060df3">

It does work in colab, though you have to do something special to enable it (for security reasons):

<img width="517" alt="image" src="https://github.com/user-attachments/assets/d019e018-0e7f-4f33-9f60-cd8534f7d1fa">

but I think colabs widgets setup is several years old (?), so it's maybe more likely to support something that used to work:
<img width="299" alt="image" src="https://github.com/user-attachments/assets/3e820b00-a09b-4ac2-a690-87ce59c63960">

In any case, it's very likely a bug that this doesn't work, and we should support it.

Upstream issues saying this is broken on mybinder:

- https://github.com/jupyter-widgets-contrib/ipycanvas/issues/343

**Comment by williamstein** [comment]
```py
!pip install ipycanvas
```

```py
from ipycanvas import Canvas

canvas = Canvas(width=200, height=200)

canvas.fill_rect(25, 25, 100, 100)
canvas.clear_rect(45, 45, 60, 60)
canvas.stroke_rect(50, 50, 50, 50)

canvas
```

**Comment by williamstein** [comment]
This DOES work in JupyterLab 4.2.4. Definitely a bug to be fixed:

<img width="606" alt="image" src="https://github.com/user-attachments/assets/8426c98c-8b9f-4e5d-a93c-61cc17511f08">

**Comment by williamstein** [comment]
The basics work, but something else goes wrong with this example from the docs:

```py
from ipycanvas import Canvas

canvas = Canvas(width=100, height=50)

def perform_drawings():
    canvas.font = "32px serif"
    canvas.fill_text("Voilà!", 10, 32)

canvas
```

then in another cell

```py
perform_drawings()
```

It works the first time.  If you then refresh the browser, it crashes and further evaluation does not work.

**This is also broken in the same way when used with JupyterLab.**

This is an upstream bug that has been opened 1.5 years with no comment: https://github.com/jupyter-widgets-contrib/ipycanvas/issues/322

I'm going to make one small change in cocalc, which is to not show the big cocalc crash warning 
in this case, thus matching the current broken jupyterlab behavior.

**Comment by williamstein** [comment]
I'm going to close this; it's not our bug and I don't know what to do about it.
