### ISSUE TITLE
idle timeout: make it so activity over ssh updates the idle timeout

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5160]
1. Start a project with a 30 minute idle timeout
2. ssh into that project from your laptop
3. Do stuff over ssh, but don't do anything with the cocalc web ui.
4. The project idle timeouts at 30 minutes anyways.

Related to this is that ssh'ing to a project should start it running if it isn't already running.

WORKAROUND: Get an API key and use the API key to periodically do `touch_project` (see https://doc.cocalc.com/api/touch_project.html), which should trigger an update of the idle timeout.  You can also start the project via the API (rather than by initiating an SSH connection).

**Comment by haraldschilly** [comment]
this is implemented, and the note about auto start is https://github.com/sagemathinc/cocalc/issues/4213
