### ISSUE TITLE
Create a way to get the filename of a cocalc notebook from Python

### ISSUE THREAD

**Issue by jkitchin** [sagemathinc/cocalc#5165]
It would be very useful if there was a way to get the path to the current notebook inside the notebook.

`path = current_notebook()`

There are some good reasons why this is not currently possible, as not all kernels are associated with a file, and more than one file may use the same kernel. I regularly use emacs to communicate with a kernel in a way that is not associated with a notebook, but which takes code from a text file, runs it in a kernel, and then puts results in the text file. The kernel is unaware of the file, but emacs is, and I can do useful things with that. By analogy, it seems like the browser must know what file is associated with the notebook file, as it must eventually write it to disk.

There are good reasons to be able to do this however, and in some contexts it makes sense to do it. The main use case I have at the moment is to be able to compute the name of a database to store notebook specific data in that can be reloaded later.  e.g. for a notebook called assignment-1.ipynb the data would be stored in assignment-1.db. Alternatively I could use the filename in my db to differentiate between files.

Potential solutions:
1. use a constant db name. I currently do this, and it works fine when there is only one notebook in a directory. With multiple notebooks however, the risk of collisions goes up. It is pretty common to have multiple notebooks and I think it would be better to have a db per notebook, or, to be able to use the notebook filename as a key in the db to differentiate them. 
2. Put some kind of uuid in each notebook. This is certainly doable, and could be done at the point where the code that does the saving is imported. Generating uuid's is a little tedious in a notebook, and if you copy a notebook then there will be two uuids that are the same, and then there will be inconsistency in the db.

Other applications include exporting from a cell, where you want to derive the output filenames from the current file. I know you can use a menu for this, or a shell command, but a nice export magic would be nice, e.g.

%export pdf

or being able to calculate relative paths to the current notebook.

I could probably be convinced that this isn't a good idea^{TM}, but it has come up as an unsolved problem for many years for me! 

In Google colab, this is possible with https://github.com/airesearch-in-th/kora/blob/master/kora/drive.py#L80.

**Comment by williamstein** [comment]
@jkitchin  adds elsewhere: 

> "An env variable could be fine, as long as it points to something different in each notebook (these presumably operate in different kernels). I would be happy look at something like
``` 
import os
os.environ.get('COCALC_CURRENT_NOTEBOOK', None)
```
> to get the path to the current notebook."

**Comment by haraldschilly** [comment]
I've just deployed a small fix, that exposes more info in the env variables. You need a recently started project to get the update. You can see screenshots in the referenced PR above. In particular, these are new:

```
COCALC_JUPYTER_FILENAME = assignment1/foo2.ipynb
COCALC_JUPYTER_KERNELNAME = python3
```

The filename is a path relativ to where the project's home directory is.

**Comment by jkitchin** [comment]
Great! is it implied that this is relative to ~/?

**Comment by haraldschilly** [comment]
yes, the project's home directory

**Comment by williamstein** [comment]
Why is this still open?  closing.
