### ISSUE TITLE
inconsistency between cocalc and Jupyter notebook in creating a new cell

### ISSUE THREAD

**Issue by jkitchin** [sagemathinc/cocalc#5170]
In a Jupyter notebook, I can use  a function that will create a new cell with contents, e.g. 
![image](https://user-images.githubusercontent.com/1610070/104486122-50452c80-5599-11eb-8bdb-888f4216839c.png)

In cocalc though it appears that the replace argument is ignored and running it replaces the content in the current cell.

**Comment by williamstein** [comment]
This is too vague.  E.g,. what is `get_ipython`?
