### ISSUE TITLE
In the course file, when you add a handout, there is a window that pops up to Create assignment

### ISSUE THREAD

**Issue by jkitchin** [sagemathinc/cocalc#5171]
I think this is confusing, and should read  "Create handout"

![image](https://user-images.githubusercontent.com/1610070/104496816-7a055000-55a7-11eb-9c77-75b76cb19ae2.png)

**Comment by williamstein** [comment]
Fixed long ago:

<img width="820" alt="image" src="https://github.com/user-attachments/assets/53435d8a-d36a-44d5-8230-50495e107d77">
