### ISSUE TITLE
bug: markdown preview stops appearing

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5172]
To reproduce:

1. Open a new markdown file
2. Type a little in the source code on the left and see that things work
3. Maximize the preview view on the right
4. Unmaximize the preview view.
5. Now type in the source.  The preview likely does not update except when you save the file (when it definitely does).

IDEAS: This same bug could presumably cause some other issues.  It's caused by the recent changes in  https://github.com/sagemathinc/cocalc/issues/5110, and in particular probably an onChange isn't getting properly reconfigured when the relevant react component is unmounted and remounted.

**Comment by DrXyzzy** [comment]
This is like what I was seeing several days ago, but there are differences.
1. I don't use the maximize button in the preview pane, haven't for months.
2. The preview did not update immediately when I clicked Save. But it often did update automatically within a minute or less of latest update to source.

**Comment by williamstein** [comment]
> I don't use the maximize button

That's just one way to cause the react component to unmount and remount.  Other things could cause that.

> The preview did not update immediately when I clicked Save. But it often did update automatically within a minute or less of latest update to source.

That sounds completely different than this bug.
