### ISSUE TITLE
moving a tex file can break building it

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5173]
1. Create a .tex file in a directory
2. Rename or move that directory.
3. We've had reports that this can make it so the pdf file doesn't build.  I haven't confirmed this yet.

WORKAROUND: Change the build engine to something else, then change it back to PDFLatex, thus resetting it to the correct value.  This seems to fix the problem.

**Comment by haraldschilly** [comment]
i think that's what https://github.com/sagemathinc/cocalc/issues/5111 asks for
