### ISSUE TITLE
performance issue when displaying Jupyter notebook

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5185]
1. Open cocalc fresh and view the Files page.  Also open the Chrome Task Manager.  Observe that the cpu usage of the cocalc tab viewing the files page is **low** (e.g., single digits).
2. +New --> Jupyter to make a new blank Jupyter notebook.
3. Look at the cpu usage in the chrome task manager, and observe that it stays relatively high (over 20%), which is weird given that you're not doing anything at all and the notebook is empty.
4. Switch back to the Files page and observe the CPU goes back down to single digits.  (When doing this the notebook still exists and is mounted in the DOM, but it is hidden (via CSS); the show/hide state is different in the store for the notebook, but I don't think this is used anywhere.  This strongly suggests the problem is with a third party Javascript library.)
5. Open a plain text file, and CPU usage stays single digits.  This is something specific to rendering Jupyter notebooks (I tried a few other file types and didn't see this problem, though I didn't try all of them).

It can be even worse with bigger notebooks, e.g., this one seems much worse in terms of cpu usage (much more clearly demonstrating the problem):
```
https://bitbucket.org/hrojas/learn-pandas/raw/master/lessons/01%20-%20Lesson.ipynb
```

Joe Bogner who reported this says it is definitely caused by font-awesome, which provides our icons:

> I used the javascript profiler and found it seems to be linked to fontawesome. I commented out this line https://github.com/FortAwesome/Font-Awesome/blob/fcec2d1b01ff069ac10500ac42e4478d20d21f4c/js/fontawesome.js#L1512 and the performance improves to be similar to the old version. Of course, that's not a proper fix because it causes some other rendering issues.  The older version also has this same code. Perhaps it's getting called more frequently in the new version?
> I've successfully 'improved' the performance on two instances by commenting out that line above in /static/css-7ba8cd4efb9614574e75.cacheme.js on the new version ...

**Comment by williamstein** [comment]
Additional info: the problem is a function of the number of cells.  If you just make a blank notebook with say 100 cells it's much worse.

**Comment by williamstein** [comment]
Another note: this is a speed regression in that some time in the past this was not a problem at all.

**Comment by williamstein** [comment]
Another note: using chrome dev tools to just delete the part of the DOM showing the cpu usage (by selecting and hitting backspace), immediately fixes the problem, and my own laptop's cpu usage drops from like 60% to single digits.  So the problem _appears to be_ the new cpu/memory bars that @haraldschilly recently added.  They ironically happen massively increase the cpu usage of the user's browser.  I should be able to fix this now.

Confirmed -- this one change completely fixes the problem:

```
~/cocalc/src$ git diff smc-webapp/jupyter/status.tsx
diff --git a/src/smc-webapp/jupyter/status.tsx b/src/smc-webapp/jupyter/status.tsx
index 492a3723c..e2a6443e1 100644
--- a/src/smc-webapp/jupyter/status.tsx
+++ b/src/smc-webapp/jupyter/status.tsx
@@ -321,7 +321,7 @@ export const Kernel: React.FC<KernelProps> = React.memo(
 
     function render_usage_graphical() {
       // unknown, e.g, not reporting/working or old backend.
-      if (usage == null) return;
+      if (true || usage == null) return;
 
       const style: CSS = is_fullscreen
         ? { display: "flex" }
~/cocalc/src$ 
```

The usage thing is just implemented using the Progress component from antd, so maybe it is horribly broken.  I'll try updating and if that doesn't fix it, open an issue and switch to something else.

**Comment by williamstein** [comment]
Fixed.  It's definitely an antd bug because my cpu usage goes up way too much when I visit the [Progress component page](https://ant.design/components/progress/) on the antd website!  Other random pages I tried on that same site don't cause the cpu spike.

**Comment by JoeBognerINSIGHT** [comment]
Fix is confirmed. Thank you very much!

**Comment by joebo** [comment]
Fix is confirmed. Thank you!
