### ISSUE TITLE
the antd date/time selector for the due date/time of an assignment no longer lets you set the time (the option is just missing)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5188]
Since we didn't change anything in our code, this must be due to upgrading antd at some point.

WORKAROUND: You can still manually edit the time in the box and that works fine (just ignore the popup, which might require scrolling or scaling in case it covers the text).

**Comment by DrXyzzy** [comment]
Also reported by Sean Raleigh.

**Comment by novoselt** [comment]
Seems to work fine!
