### ISSUE TITLE
jupyter: when saving a.ipynb to disk, don't consider save successful until both .a.ipynb.sage-jupyter2 **and** a.ipynb both successfully save to disk

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5197]
I have seen at least one instance that looks like this:

```
~/.$ ls -lhta
total 12K
-r--r--r-- 1 user user 5.1K Jan 26 00:43 .Quiz1.ipynb.sage-jupyter2
-r--r--r-- 1 user user 6.1K Jan 26 00:33 Quiz1.ipynb
```

Note the timestamp of `Quiz1.ipynb` is 10 minutes behind that of ` .Quiz1.ipynb.sage-jupyter2`.  Looking at the actual file, indeed Quiz1.ipynb represents the state of the file from 10 minutes earlier.

The point of this issue is mainly to re-read the relevant code in cocalc which writes out the ipynb file.  Also, in case this doesn't yield anything obviously wrong (e.g., maybe this happening is a side effect of an uncaught exception in some distant code or even resource allocation exhaustion), put in some additional state information that tells the frontend if the ipynb file is not definitely properly saved to disk successfully, so the frontend UI can warn the user that something may be wrong.

**Comment by tomgrubbmath** [comment]
Thanks for opening this report. Now that I know what to look for I was able to reproduce it in two other student projects. If it would be useful for me to keep a log of where this is happening or if there is any other way I can try to help, just let me know.

**Comment by slel** [comment]
> The point of this issue is mainly to re-read the relevant code in cocalc
> which writes out the ipynb file.

Can you point to that code?

I have sometimes discovered, when opening a notebook I thought had
been saved, that the last few changes had not been taken into account.
Sometimes it happened after sending it as an assignment to students.

**Comment by williamstein** [comment]
This might be closely related to https://github.com/sagemathinc/cocalc/issues/4715

@slel your pointing at the code that runs in the web browser...

I'll likely address this problem this week.

**Comment by williamstein** [comment]
No issues like this for many years.
