### ISSUE TITLE
license info text: 1GB dedicated CPU

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5199]
It makes no sense to have `1GB dedicated CPU` in the license info text.

**Comment by williamstein** [comment]
I have absolutely no idea what this ticket means.  Please include a screenshot or further details.

**Comment by haraldschilly** [comment]
I don't have a screenshot. The license info text is the one below the license key in the info box about it. I assume it's easy to recreate if you have a license for 1 dedicated cpu core.

**Comment by haraldschilly** [comment]
I'm reopening this, since I saw exactly that wording again.

![Screenshot from 2021-06-30 14-01-13](https://user-images.githubusercontent.com/207405/123957073-aa9d4280-d9ab-11eb-97c5-2209327b0c38.png)

**Comment by williamstein** [comment]
deprecated -- there is no dedicated anything anymore.
