### ISSUE TITLE
"open with one click" shared folder whose name does not have extension gets "Unknown file extension"

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5212]
Try this when not signed into a CoCalc account that is admin or a collaborator on the API Tutorial project:

1. Browse to https://share.cocalc.com/share/6eec7a75ce704502e2d557f44c316bf75c5c6ce7/Public/?viewer=share I'm sharing the folder "Public" so that `Open with one click!` picks up all the files.
2. Click `Open with one click!`.
3. See the following "Unknown file extension" warning:

<img width="1324" alt="share-folder" src="https://user-images.githubusercontent.com/528072/108135173-45405900-707d-11eb-9d3f-eea428c96aeb.png">

**Comment by williamstein** [comment]
Wow, this is a really major bug because this applies to all shared folders.  I assume clicking the button to open the directory with the Code editor is a disaster too...

**Comment by williamstein** [comment]
I can't reproduce this.  Here's what I see in signed out incognito mode when I browser to that share and click the green button:

![image](https://user-images.githubusercontent.com/1276278/108138527-fb527580-7072-11eb-8533-63313b55fc71.png)

That is -- everything works perfectly for me.  I'm using Chrome on OS X.

**Comment by williamstein** [comment]
Did you really do something slightly different, or use a slightly different URL or something else?   I mean, it seems possible that such an error could occur in theory... but I'm not seeing it in practice.

**Comment by DrXyzzy** [comment]
When I saw the problem, I was using Firefox on macOS with my personal (non-SMI) account. I just tried again after restarting Firefox and logging into CoCalc with the same (personal) account as before, and did **not** see the problem.

It's possible the first time the URL was subtly different. I'll try exactly reproducing my navigation steps later and note results here.

**Comment by williamstein** [comment]
Can you check your browser history to see if "It's possible the first time the URL was subtly different"?

**Comment by DrXyzzy** [comment]
The full link is in the original screenshot that I cropped (bad) above. Here it is: https://cocalc.com/projects/21da59bb-5af8-4652-8860-164c69518cbb/files/Public?anonymous=true&session=default but visiting there now from a private FF window does not reproduce the bug.

This might matter or not: When I opened the API tutorial original project, it was on Ubuntu 18.04. I upgraded the project to Ubuntu 20.04, then made several edits, then visited the link from the Files / Public display for the README.md file and clicked "Open with one click". I saw that my new edits to the README.md were in the copied project, but the compute environment in the copied project was still on Ubuntu 18.04. I also saw that there were not other files from the tutorial, so I made the parent PUBLIC folder shared and visited that share link and clicked to open a copied project. That's when I saw the bug.

Then I stopped sharing PUBLIC from the original API tutorial project and re-shared it. That resolved the compute environment issue in the copied project (now 20.04) and may have cleared whatever issue was causing the "Unknown file extension" warning as well.

I guess this issue can be closed, unless any of the above is helpful for finding a real problem.

**Comment by DrXyzzy** [comment]
FWIW, I saw the bug 2 more times out of about 8 tries today. All in Firefox on macOS while logged into personal (non-admin) CoCalc account in another tab.

1. Click on link https://cocalc.com/projects/21da59bb-5af8-4652-8860-164c69518cbb/files/Public?anonymous=true&session=default
2. Click on "Open with one click" when the shared folder is displayed on the share server.
3. While the project is starting as soon as project toolbar appears, click project settings, scroll down to license dialog, then go back to Files.
4. Sometimes the "Unknown file extension" warning appears.

**Comment by williamstein** [comment]
To reproduce the root problem, make a directory `directory, then type this in the Javascript console of cc-in-cc dev (with your project_id):
```js
a = cc.redux.getProjectActions('8d304d73-6544-47e2-993b-6060fae84763')
await a.open_file({path:'directory'})
```
