### ISSUE TITLE
issue when saving an ipynb jupyter notebook file

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5216]
This is rare but happened with the following steps:

1. Just running very simple code in a Sage worksheet (say).  In particular, assume there are no issues with memory or cpu or anything else like that.
2. It locks up, the green save line says "not saved" and the circle is spinning.
3. I figured, ok, I can restart the file or the project and it will fix it, but no, even after restarting the project, the file is still totally locked up.
...
4. What fixed it was closing the file tab that was locked and then restarting the project. It is working now.

WORKAROUND: If you hit this and nothing seems to work, refresh your browser and restart the project.

Since this is very difficult to reproduce, for starters the idea of this ticket is to record any hints or other observations related to this happening.

**Comment by williamstein** [comment]
I may have fixed this bug.  Some notes:

- I've personally never seen this and it was not reproducible.
- It was only reported indirectly by students.
- There was a TODO in the code about an error at some step needing to be reported.  That said, that very error could be easily simulated by making the ipynb file read-only and then the error did get reported in some cases... but maybe not others?  By banging on the save button enough I got the error to not get reported and the button to go dim.  It looks like there were two code paths that involved saving, so probably one of them (maybe related to autosave) could make it seem like the file had saved even if it didn't.  I thus cleaned up the code using async/await (instead of callbacks) and ensuring both paths reports errors.   Here's a screenshot showing me breaking things via permissions, but getting the green button to go dim thus making me incorrectly think I saved the file. Note that nothing is actually saved according to more:
![image](https://user-images.githubusercontent.com/1276278/109079550-f1082b00-76b3-11eb-9de6-9c3ae865b04c.png)

OK, thinking about this, the first commit d14132e doesn't fully address the autosave codepath, so I'm re-opening.

In any case, let's just say a reproducible case of this is:

1. Create a file a.ipynb
2. `chmod a-w a.ipynb` in a terminal
3. Try to save with button and it gives the right error.
4. Wait for autosave.  That makes it seem the file is saved, but it isn't.

This exact sequence problably isn't the true source of the random problem.  However, something similar could be, e.g., running out of disk space, a temporary network error, or something else that prevents the actually file save **but** then still considers the file as having no unsaved changes, so you can't actually do the proper save without making an additional change.   Note that in the cases this was reported, is was just the very last thing the student did that was not saved.

One other note is that students tend to sometimes try to work in the read-only .snapshots directory, or copy files out from there, and that can result in them hitting a situation with read-only permissions.

**Comment by williamstein** [comment]
Wait, I just realized what is going on is very clear.   Steps to truly reproduce this problem and it'll open happen for Jupyter (and nothing else).
1. In account preferences, set your autosave to a very large value, e.g., 900.
2. Open a Jupyter notebook file a.ipynb.
3. Change it and do NOT click save.
4. There is a backend autosave that happens in a project. It runs once ever 45 seconds, so wait about that long.  
5. Your file a.ipynb will appear to have been saved according to the frontend UI (the save button is dimmed). The file ` .a.ipynb.sage-jupyter2 ` on disk will indeed have been saved.  However, `a.ipynb` has not been saved... because the backend autosave functionality is very generic and doesn't even know about ipynb files or the mechanism that also exports to ipynb.
6. You can't click save to save the .ipynb file, since the frontend thinks everything is saved already.
7. However, if you just make a change to the ipynb file and click save, everything is properly saved to disk.

So my guess is that people who just have a habit of actively saving (by clicking the save button or hitting control+s), or people who manually reduce their autosave interval would never ever see this bug.  But people who don't ever think about saving to disk and whose projects have a relatively short idle timeout (i.e., students) are more likely to.

This shouldn't be hard to fix now that I 100% understand what is going on.

**Comment by tomgrubbmath** [comment]
Sorry to bring this back up but I am currently getting the following error message on a student project after trying to save the file: 
![image](https://user-images.githubusercontent.com/53013402/109898335-ec5dec80-7c48-11eb-8c34-96c51617c901.png)
The .ipynb file is still not being saved: 
![image](https://user-images.githubusercontent.com/53013402/109898382-039cda00-7c49-11eb-9140-93c6ee393d61.png)
Is there something I can recommend that they do in this situation?

**Comment by williamstein** [comment]
This can always be resolved by restarting the project (or possibly refreshing the browser), unless it is a permissions issue.

**Comment by williamstein** [comment]
How to reproduce this with a notebook open (in dev mode):

1.  `a = cc.redux.currentEditor().actions`
2. `a.jupyter_actions.syncdb.has_unsaved_changes = ()=>true;`
3. `a.jupyter_actions.syncdb.save_to_disk_user()`

This causes the user to incorrectly set the save state to `requested` even though there are no unsaved changes. This could happen in nature very rarely due to a delay in updating the save state (especially with multiple collaborators at once).    This problem isn't restricted to Jupyter notebooks, in theory.

On the backend this code then runs:
```
    dbg("initiating the save");
    if (!this.has_unsaved_changes()) {
      dbg("no unsaved changes, so don't save");
      // CRITICAL: this optimization is assumed by
      // autosave, etc.
      return;
    }
```
and that does NOT set the requested save state to done.      Everything is always fine if sync were instant... but of course it isn't.   Yeah, the fun of reasoning about distributed data structures... 

Fortunately this is easy to robustly fix now that I can fully reproduce it.

**Comment by williamstein** [comment]
Just a note that all indications are that this bug is now definitely and completely fixed.
