### ISSUE TITLE
warning for non-upgraded student-pay projects - don't send students to subscription purchase page

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5218]
At present if a student opens a student project without upgrades and visits Settings, they see this message:

![image](https://user-images.githubusercontent.com/528072/108904459-1fb6d080-75e4-11eb-9c37-41be44dd5a0e.png)

but if it's a student project in a student-pays course, following that link may lead them to mistakenly purchase a monthly plan instead of a student plan. In that case the wording should refer the customer to the link in the red banner above.

**Comment by williamstein** [comment]
Also, the plans start at about $3/month...
