### ISSUE TITLE
Equation numeration fails when a label is reused (mathjax shows an error rather than silently allowing label reuse)

### ISSUE THREAD

**Issue by a7p** [sagemathinc/cocalc#5220]
We are trying to enumerate our LaTeX-formulas in an jupyter-notebook.
```
\begin{equation}
 \Phi_{h} = \Phi_{a} = \Phi_{l} \tag{1.2} \label{eq2}
\end{equation}
```
As soon as a label is reused some internal state breaks and any cell having a label that's evaluated afterwards fails.

![EquationNummeration](https://user-images.githubusercontent.com/112350/109026080-a4c2e800-76bf-11eb-9846-aa743c9f4034.png)
 
Halting the Kernel, clearing the outputs and un-cached reloading sometimes fixes the issue.

Sadly at the moment I'm unable to provide a better bugreport.

**Comment by williamstein** [comment]
What are the exact steps to reproduce this?    In particular:

1. What did you do exactly? 

2. What happened? 

3. How did this differ from what you expected?

**Comment by williamstein** [comment]
Also, if you completely disable katex by unchecking the box next to "KaTeX: attempt to render formulas with KaTeX if possible (much faster, but missing context menu options)" in account preferences, then refresh your browser (etc.), what happens?

**Comment by a7p** [comment]
1. upload this jupyter notebook to a fresh project
[equations.zip](https://github.com/sagemathinc/cocalc/files/6072054/equations.zip)
2. wait for the cells to be evaluated - some fail with the error screenshotted above - not always the same ones.
3. I expected the equations to be properly enumerated or to get an error message if I try to redefine a label (don't know the LaTeX behavior here).

> Also, if you completely disable katex by unchecking the box next to "KaTeX: attempt to render formulas with KaTeX if possible (much faster, but missing context menu options)" in account preferences, then refresh your browser (etc.), what happens?

This changes nothing.

**Comment by williamstein** [comment]
Here's what happens in Jupyter classic:

![image](https://user-images.githubusercontent.com/1276278/109721962-e7257280-7b60-11eb-871b-715876f6edf9.png)

And in CoCalc:

![image](https://user-images.githubusercontent.com/1276278/109722013-f4daf800-7b60-11eb-852d-d49d1bbae6bc.png)

**Comment by williamstein** [comment]
My best guess is that we configure Mathjax differently, run it differently, or the version of Mathjax is different and things changed (either fixing or introducing a bug).  Checking, MathJax is 2.7.7 in both of them.

I'm curious -- Why do you want to reuse labels?   Isn't that a standard error in LaTeX?   "There were multiply-defined labels"

**Comment by williamstein** [comment]
Note that this is also easily reproduced in a single markdown cell or markdown (.md) file.

**Comment by williamstein** [comment]
This input in markdown with jupyterlab breaks:
```md
\begin{equation}
  2 + 3 \label{one}
\end{equation}

\begin{equation}
 3 + 5 \label{one}
\end{equation}
```

<img width="496" alt="image" src="https://github.com/user-attachments/assets/1337a7e5-d374-4803-a406-f2866f041795">

In cocalc now, you can't use labels at all.

Labels don't actually work though in jupyterlab either:

```md
This

\begin{equation}
 \Phi_{h} = \Phi_{a} = \Phi_{l} \label{blahblah}
\end{equation}

and this again: $\ref{blahblah}$.
``` 

outputs

<img width="629" alt="image" src="https://github.com/user-attachments/assets/c3ce199e-184c-4a68-81f2-655105eb7640">

I'm going to close this issue as wontfix.   There are other tools (like sagetex and pytex) that are better for writing latex with code and references.
