### ISSUE TITLE
cocalc-jupyter ipywidgets: fully implement GridBoxModel and other layouts

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5228]
1. Put this code in a notebook:
```
from ipywidgets import Button, GridBox, Layout, ButtonStyle

header  = Button(description='Header',
                 layout=Layout(width='auto', grid_area='header'),
                 style=ButtonStyle(button_color='lightblue'))
main    = Button(description='Main',
                 layout=Layout(width='auto', grid_area='main'),
                 style=ButtonStyle(button_color='moccasin'))
sidebar = Button(description='Sidebar',
                 layout=Layout(width='auto', grid_area='sidebar'),
                 style=ButtonStyle(button_color='salmon'))
footer  = Button(description='Footer',
                 layout=Layout(width='auto', grid_area='footer'),
                 style=ButtonStyle(button_color='olive'))

GridBox(children=[header, main, sidebar, footer],
        layout=Layout(
            width='50%',
            grid_template_rows='auto auto auto',
            grid_template_columns='25% 25% 25% 25%',
            grid_template_areas='''
            "header header header header"
            "main main . sidebar "
            "footer footer footer footer"
            ''')
       )
```
2. It should look like this (in jupyter classic):

![image](https://user-images.githubusercontent.com/1276278/109725596-3ae68a80-7b66-11eb-88f4-dd487fc07884.png)

3. But in CoCalc it looks like this:

![image](https://user-images.githubusercontent.com/1276278/109725643-4cc82d80-7b66-11eb-9e5c-c05aad28fa03.png)

This is not surprising given the code in src/smc-webapp/jupyter/output-messages/widget.tsx which explicitly says this isn't fully implemented.

**Comment by williamstein** [comment]
WORKAROUND: Use JupyterLab or Jupyter Classic in CoCalc. 
  https://doc.cocalc.com/jupyter.html#classical-versus-cocalc

**Comment by williamstein** [comment]
Better link to the code  -- https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/jupyter/output-messages/widget.tsx#L419

It's probably not hard to actually implement this properly...  I should really do it soon.

**Comment by williamstein** [comment]
@jasongrout check out how I fixed this via 4dfb08a if you want to be really annoyed!  :shrug:

**Comment by haraldschilly** [comment]
I'm reverting this, this breaks those controls.

**Comment by jasongrout** [comment]
> @jasongrout check out how I fixed this via [4dfb08a](https://github.com/sagemathinc/cocalc/commit/4dfb08af223897872e8e3fb38eef0a6658a9277d) if you want to be really annoyed! 🤷

Ouch :).

**Comment by williamstein** [comment]
> > @jasongrout check out how I fixed this via [4dfb08a](https://github.com/sagemathinc/cocalc/commit/4dfb08af223897872e8e3fb38eef0a6658a9277d) if you want to be really annoyed! 🤷
> 
> Ouch :).

https://github.com/sagemathinc/cocalc/commit/3405032b676c644b8c94962f833ad9c46c700ed2

**Comment by williamstein** [comment]
I disabled the ipywidgets thing again since it evidently subtly broke something -- no clue why.  In any case, another approach is instead of moving the widgets up one level in the DOM (thus replacing their parents), I can copy the CSS and styles up one level, so that the parents enforce the right layout. Maybe that is enough. I don't know.   My guess is that the current approach confuses cleanup the phosphor widgets and causes a crash.

**Comment by williamstein** [comment]
This is fixed by https://github.com/sagemathinc/cocalc/pull/7687
