### ISSUE TITLE
Table of contents with a smaller font

### ISSUE THREAD

**Issue by vdtoorn** [sagemathinc/cocalc#5240]
In larger notebooks the table of contents is very helpful in navigating around. Unfortunately the fonts that are used are large (header text in HTML) so that a lot of artifacts like word wrap and stretching the TOC takes place.

It would be very nice if with some simple css it would become less big and more useful.

**Comment by haraldschilly** [comment]
There are magnification glass +/- buttons at the top of the TOC. Do they help? Or should long titles be truncated? By truncating I mean to not do line wrapping, but instead ending with ellipses dots "foo ba ...".

**Comment by vdtoorn** [comment]
Hi Harald,
I'm basically referring to the font size. This is an R kernel, and there the titles are <h1> and therefore rather large. I don't know how this is for other languages. I think wrapping is perfect, since you can resize the side panel to your needs, but now if you would like to have everything on the same line, it is just too big. Here's what I mean:

![cocalc_TOC_example](https://user-images.githubusercontent.com/320079/110822796-b85e7900-8291-11eb-8826-153e16e00219.png)

**Comment by haraldschilly** [comment]
yes, I agree, and those dashes aren't nice. What I was referring to are the magnification glass icons for the font size. If you focus the TOC frame and maybe resize it a little bit, they show up, see screenshot below. My idea would be to try clicking a couple of times on the minus-glass and see if that helps. I could imagine adding a "no line wrap" toggle button as well.

![screenshot-cocalc com-2021 03 11-18_10_30](https://user-images.githubusercontent.com/207405/110826348-4720c500-8295-11eb-870e-48fdd4bf5686.png)

**Comment by vdtoorn** [comment]
Ok, this is clearly user error: I never realized that these panes can have focus and that you get these options.. Thank you a lot for pointing this out... 😊

**Comment by haraldschilly** [comment]
well, I keep it open, because I think this can be improved. and yes, I also don't like that the buttons disappear. maybe this should be at least configurable.

**Comment by DrXyzzy** [comment]
- Longer items in table of contents have strange indent.
- Text for sub-items is not indented relative to parent items

![image](https://user-images.githubusercontent.com/528072/113814258-f6d34080-9736-11eb-99ff-c23d22d744b0.png)

**Comment by vdtoorn** [comment]
Responding just to give kudos, it looks much nicer now.
