### ISSUE TITLE
ihaskell (jupyter kernel for haskell) is broken on cocalc.com

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5248]
1. In the default Ubuntu 20.04 image in a Terminal, type `jupyter console --kernel=haskell`:
```
~/tmp/gitahead-2.6.3/src$ ~$ jupyter console --kernel=haskell
/ext/ihaskell/ihaskell: error while loading shared libraries: libHSstrict-0.3.2-8rwMsowQiZqFRQ6mPJVsPX-ghc8.8.3.so: cannot open shared object file: No such file or directory
```
2. As you can see, it's broken due to a library conflict.

WORKAROUND: In project settings, change the Software Environment to "Ubuntu 18.04".  Then it works fine:
```
~$ jupyter console --kernel=haskell
Jupyter console 6.1.0

IHaskell 0.9.0.3 GHC 8.4.2
In [1]:                                                                                                                                                                    
Do you really want to exit ([y]/n)? y
Shutting down kernel
~$ cat /etc/issue
Ubuntu 18.04.5 LTS \n \l
```

**Comment by haraldschilly** [comment]
hmm, strange. no idea how that happened. I've disabled the kernel  for now.

**Comment by williamstein** [comment]
We no longer support any haskell kernels.

**Comment by mforbes** [comment]
Just a comment: I have never tried this, but it would be awesome for students to be able to easily play with Haskell (and other languages) on CoCalc.  Just curious: What is the nature of the problem? Is it just that the kernel is not well written, or something else?  I might look into it if I have the time.
