### ISSUE TITLE
allow customers to undo subscription cancellation

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5249]
Under "Account" / "Purchases" / "Subscriptions", when a customer clicks "Cancel" the plan is canceled and the button disappears. We have had requests by customers to undo cancellation. At present that can only be done by CoCalc support.

Suggestions:
- When a subscription is canceled, replace the "Cancel" button with a "Resume" button and explanatory text, for example **Clicking this button will cause your plan to be renewed on (date) at a charge of (price)."**
- We might make this change only for renewing licenses and personal upgrade plans, not the legacy course packages, due to possible confusion over whether the latter are subscriptions or not.
- The "Resume" button could have background color of green or blue or such, to indicate positive or forward motion.
- The "Cancel" button could have background color of orange or red or such, to indicate stopping something. Some customers are unaware that it is there. Support gets occasional requests to cancel a plan that could be canceled by the customer.

**Comment by williamstein** [comment]
Now done!
