### ISSUE TITLE
jupyter: multicursor: tab or shift+tab works only for last cursor

### ISSUE THREAD

**Issue by meugr** [sagemathinc/cocalc#5256]
Tab (4 spaces) or shift+tab hotkey works incorrectly in multicursor mode. In Jupyter classic all works correctly.
![demo](https://user-images.githubusercontent.com/24723197/112166195-770a8980-8c00-11eb-9233-a874d96bef72.gif)

**Comment by williamstein** [comment]
The relevant code to fix is in here:  

src/smc-webapp/codemirror/extensions/tab-as-space.ts

It just handles one cursor, but needs to iterate through all of them...

```
CodeMirror.defineExtension("tab_as_space", function () {
  // @ts-ignore
  const cm : any = this;
  const cursor = cm.getCursor();
  for (let i = 0; i < cm.options.tabSize; i++) {
    cm.replaceRange(" ", cursor);
  }
});
```

**Comment by williamstein** [comment]
The code for shift+tab (unindent) is here:

src/smc-webapp/codemirror/extensions/unindent.ts

and interestingly it is the full implementation that *does* work properly for multiple cursors.
