### ISSUE TITLE
jupyter: ipywidgets/Output markdown links aren't processed properly to work with cocalc

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5258]
Certain "localc" Markdown/HTML links are processed to work well inside of CoCalc. That's not the case for "Output" widgets in jupyter. Code to reproduce for a relative subfolder `./asdf`:

```
from IPython.display import display, Markdown
import ipywidgets as widgets

output = widgets.Output()
with output:
    display(Markdown('[Widget link to asdf sbfolder](asdf)'))
display(output)
```

it works fine for just `display(Markdown('[Code cell link to asdf subfolder](asdf)'))` or a markdown cell, of course.

**Comment by williamstein** [comment]
I can confirm that this is still a problem today:

<img width="929" alt="image" src="https://github.com/user-attachments/assets/bfc77588-4362-4f8d-b79c-d26321e0837c">

One difference is that I had to do a lot of work with improving output widgets and their context, and I think I know exactly how to fix this in a few lines of code now.

**Comment by williamstein** [comment]
And fixed.
