### ISSUE TITLE
course: creating a handout/assignment with the name of an already existing directory gives a confusing error message

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5261]
msg:

> `error creating assignment: Error: command 'mkdir' (args=-p /[NAME]) exited with nonzero code 1 -- stderr='mkdir: cannot create directory ‘/[NAME]’: Permission denied`

goal: tell the user that the directory already exists and offer a button to add the directory with the given name as handout or assignment.

**Comment by novoselt** [comment]
I have a feeling that the interface has changed, since I don't understand the steps to reproduce it.
