### ISSUE TITLE
customize jupyter code snippets

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5267]
the goal of this ticket is to add a section for "custom snippets". in particular, there could be a notebook in `$HOME` called `cocalc-snippets.ipynb`, which is parsed upon opening the snippets panel. each combination of a single markdown cell + consecutive code cells will be one snippet.

stretch goal: also check if there is a "local" snippets file in the same directory, and parse it as well.

**Comment by williamstein** [comment]
It's very important that this also support system-wide snippets, for using in cocalc-docker.   This should be something in /projects/.

**Comment by williamstein** [comment]
didn't happen. closing.
