### ISSUE TITLE
Support Pluto notebooks

### ISSUE THREAD

**Issue by lahvak** [sagemathinc/cocalc#5270]
[The Pluto project](https://github.com/fonsp/Pluto.jl) provides reactive notebook for Julia. The main difference between Pluto and Jupyter (aside of the fact that Pluto only works for Julia) is that Pluto maintains a dependency graph of cells, and when a cell is modified, all cells that depend on it also get modified, so it is much less likely to have a notebook in which outputs are inconsistent with each other. 

I can install `Pluto.jl` and run Pluto on CoCalc, there does not seem to be a way to access the notebook though. I think CoCalc does not allow port forwarding, and anyway, port forwarding would not be a viable solution for teaching.  Ideally Pluto notebooks could be accessed in similar way Jupyter notebooks are accessed now, just by opening a notebook in the UI.

**Comment by williamstein** [comment]
>  I can install Pluto.jl and run Pluto on CoCalc, there does not seem to be a way to access the notebook though. [...] Ideally Pluto notebooks could be accessed in similar way Jupyter notebooks are accessed now, just by opening a notebook in the UI.

Any webserver can be fully used from CoCalc **if** it has an option to set a "base url" (or "base path").   Pretty much all "mature" web servers (e.g., Jupyter notebook, Jupyter Classic, CoCalc itself, and many others) have full base url support.

Does Pluto have support for this?   

You can see the code here for how we start Jupyter classic, and explicitly set the base_url options:

https://github.com/sagemathinc/cocalc/blob/master/src/smc_pyutil/smc_pyutil/jupyter_notebook.py

Similar for JupyterLab

https://github.com/sagemathinc/cocalc/blob/master/src/smc_pyutil/smc_pyutil/jupyter_lab.py

There are a number of interesting web services out there for which the authors don't care about or even understand what base_url support is, so they don't support it.   A good (or rather horrible) example is vscode, and you can see my analysis of this here: https://github.com/sagemathinc/cocalc/issues/4479#issuecomment-623150833

**Comment by lahvak** [comment]
Pluto has a `root_url` option which seems to do what `base_url` would do for Jupyter server.  I tried to use it on CoCalc (I tried to imitate the way jupyter server url is constructed from the project id), but when I try to connect, I keep getting 5xx errors (timeout).

If I run Pluto as

```
Pluto.run(launch_browser=false, root_url=baseurl)
```

with `baseurl` set to `/<project_id>/port/pluto/` it responds with 

```
Go to /<project_id>/port/pluto/?secret=<secret> in your browser to start writing ~ have fun
```

where `<project_id>` is my project id from `info.json` file, and `<secret>` is some random secret that Pluto gives you.  I would like
to have fun, but so far I am unable to connect to the server. One thing I noticed when testing on my laptop is that Pluto does not seem to accept https connection, and times out when trying to connect.

Unfortunately the Pluto documentation is rather sparse at the moment, and I could not find any debugging or logging options, so it is hard to figure out what is actually going on.

**Comment by williamstein** [comment]
> Pluto has a root_url option which seems to do what base_url would do for Jupyter server. I tried to use it on CoCalc (I tried to imitate the way jupyter server url is constructed from the project id), but when I try to connect, I keep getting 5xx errors (timeout).

Did you ensure it is listening on all network interfaces, and not just localhost?   You can test this by using `google-chrome` in an X11 Desktop session (+New --> X11 Desktop, then type "google-chrome" in the terminal and wait about 15s), then put the URL in the bar of the external network address.   This is "external" to for the Docker container where your project runs, but not external to the outside network.  You can see that address using `/sbin/ifconfig eth0` (it will start with 192.168).

You don't need https support at all from pluto to get it from cocalc automatically.  In fact, pluto should be listening on normal http.

**Comment by lahvak** [comment]
There is a `host` parameter that I can set, and when set to `0.0.0.0`, it listens on all interfaces.  I can connect to it from both the terminal using localhost and from the X11 session using the 192.168 IP address, but neither way it works when I try to set `root_url`.  It seems that either `root_url` is not supposed to be the same as `base_url`, or  it is broken in some way.

I do not have time to mess with it, the documentation is too sparse and it seems to be in too much flux at the moment, but it does look like an interesting project to keep an eye on.

Thanks for all your help!

**Comment by williamstein** [comment]
I'm going to re-open this, since I would like to support Pluto notebooks out of the box on cocalc.  If you want to share any terminal commands you used or links to docs, feel free.

**Comment by lahvak** [comment]
Ok, here is what I have.  The documentation is very sparse.  Running `?Pluto.run()` gives a very brief description of three parameters: `launch_browser`, `host` and `port`.  From the code there also is a `root_url` parameter, but it is not clear to me how it is supposed to work, I could not make it work at all. The config options are sort of described in [Configuration.jl](https://github.com/fonsp/Pluto.jl/blob/main/src/Configuration.jl).

When I run
```julia
Pluto.run(launch_browser = false, require_secret_for_access = false)
```
I can access Pluto with lynx at `http://localhost:1234/` from the terminal.

```julia
Pluto.run(launch_browser = false, require_secret_for_access = false, host="0.0.0.0")
```
is supposed to listen on all interfaces, and lets me access Pluto from the X11 session, at the port 1234. 

When I try
```julia
using JSON
open("/tmp/.cocalc/info.json", "r") do f
          global jsdata
          jstext = read(f, String)
          jsdata = JSON.parse(jstext)
end
baseurl = "/" * jsdata["project_id"] * "/port/pluto/"
Pluto.run(launch_browser = false, require_secret_for_access = false, host="0.0.0.0",
               root_url = baseurl)
```
it tells me to go to `/<my project id>/port/pluto/` but when I try to access
```
http://localhost:1234/<my project id>/port/pluto/
```
the server responds with a 404.  The same when I try to access it on the project external IP from an X11 session.  The same happens when I try to run it with `root_url` on my laptop.

I tried to submit an issue about  `root_url` not working and/or not being described very well but I think I was not very clear and it was closed right away.  I also tried to submit a comment about it through the builtin feedback, but I am not sure if that went through as there does not seem to be any way to see any response to it. I will try to push more using the github discussions.

**Comment by lahvak** [comment]
Here is a discussion about it at pluto github: #https://github.com/fonsp/Pluto.jl/discussions/1084#discussioncomment-620623

One think I don't understand: how do I tell CoCalc that a particular URL should be redirected to a port on my project?  If I was setting the whole thing up on a server, I would just set up a reverse nginx proxy as described in the linked comment, but how do I do that in CoCalc?

**Comment by haraldschilly** [comment]
Are you working on cocalc.com, another cocalc instance, or one running locally on your own machine? I wonder, because `http://localhost:1234/<my project id>/port/pluto/` looks like you want to access a server running on port 1234 on your own machine. Rather, I would expect to see `https://cocalc.com/<my project id>/port/1234/`  if you're on cocalc.com.

**Comment by lahvak** [comment]
I am working on cocalc.com. The `localhost` was used from a terminal running inside the cocalc project session.  The ip address was used from an X11 session in the same project.  What I did not understand was what URL to use to access a server running inside a cocalc project from the outside.  The example I was looking at, which was jupyter server, used `.../port/jupyter/` which confused me.  I suppose `jupyter` must be harcoded to point to whatever port the jupyter server listens on.

When I go to `https://cocalc.com/<my project id>/port/1234/` the Pluto server does respond. However, it responds with "Not found!" and http headers indicate a 404 error.

**Comment by haraldschilly** [comment]
ok, well, at least some progress. `jupyter` is hardcoded, yes. 

there are two variations:

* `https://cocalc.com/<my project id>/port/1234/`
* `https://cocalc.com/<my project id>/server/1234/`

and well, combine that with trying to set set that `root_url` accordingly, e.g. `<my project id>/port/1234/` or `/<my project id>/port/1234/` could be a valid choice for the `port` variation.

**Comment by lahvak** [comment]
Unfortunately, although the Pluto authors claim that Pluto can listen on any URL, that does not seem to be the case.  It seems that the `root_url` parameter does not do anything at all, except change what is printed out.

**Comment by williamstein** [comment]
I figured this out.  I'm copying this from the [Pluto discussion](https://github.com/fonsp/Pluto.jl/discussions/1084).

On CoCalc is there is a different mechanism for using a server that does what Pluto does, and it DOES work.  Here's how:

1. Run Pluto via `Pluto.run(launch_browser = false, require_secret_for_access = false, host="0.0.0.0")`.  In particular, you will not even use the `root_url` option at all.
2. In your web browser, visit `https://cocalc.com/[PROJECT_ID]/server/1234/`.
3. See this:
![image](https://user-images.githubusercontent.com/1276278/115065248-c0b65f00-9ea2-11eb-98fa-2ba8f5361a34.png)
4. Click "New Notebook" and do a test and see this:
![image](https://user-images.githubusercontent.com/1276278/115065295-cf9d1180-9ea2-11eb-85d0-d4e47a3a7393.png)

Note that in CoCalc it's necessary right now to install Pluto. To do that:
```sh
export JULIA_DEPOT_PATH=$HOME/julia_depot
$ julia
julia> ]
pkg> add Pluto
# wait a few seconds
```

However, I'm sure @haraldschilly will add Pluto it to the pre-installed software stack in a few days...

**Comment by williamstein** [comment]
I'm leaving this open, since we should add a button (like with +New --> Jupyter server) to do the above with one click...

**Comment by lahvak** [comment]
Beautiful!  I am testing this and it works great, except that I am getting a lot of timeouts when first opening a notebook, and some low RAM warnings, and Julia just got killed for running out of memory.  I am running it with member hosting, but with just the basic RAM and basic CPU, it may need more than that.

**Comment by williamstein** [comment]
Julia is memory intensive.  I'll email a trial license code to you...

**Comment by DrXyzzy** [comment]
I added an article on launching Pluto from a project to the CoCalc online docs: https://doc.cocalc.com/howto/pluto.html

**Comment by AronT-TLV** [comment]
I followed the instructions,and when I go to the link I see the page below, and its stuck on the _Loading_ If I click on `new notebook` I get the gateway timeout error. I am running this is a licensed project with shared memory, 3 CPUs/16gb) Is this a bug or just not powerful enough VM?

![IMG_0170](https://user-images.githubusercontent.com/22121571/119388679-48c62a80-bcd3-11eb-85dc-8209a0ea8e00.jpeg)

**Comment by haraldschilly** [comment]
Hi, I just tried the howto, i.e. started julia and ran the commands -- those depot path export wasn't necessary, not sure why it is there.

In any case, it's a bit slow loading pages, so, when you see a timeout (cocalc themed), you have to refresh the page 1 or 2 times. I think it compiles some packages. With that, I was able to start a getting started notebook, do changes, cells run, etc. So, right now it is working.

Your project quotas are definitely good enough. I just checked, julia is a few forked processes using ~330mb ram.

What exactly is the URL? Maybe contact us at help@cocalc.com with more details about your project and we can have a look. Also, maybe it's worth cleaning up the `~/.julia` dir, where all the compilation happens.

**Comment by AronT-TLV** [comment]
hi @haraldschilly 

There is nothing in the `.julia` Directory except a log, and I refreshed multiple times. I contacted help with all the details, which isn’t a whole lot since I just followed the instructions and ran this in an empty project
