### ISSUE TITLE
jupyter cell content may collide with run time and right-margin cell number

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5280]
Seen with latest Chrome and Firefox on macOS 11.2.3.
1. Paste the following _single line_ into a python Jupyter notebook code cell and execute it.
    ['Lorem','ipsum','dolor','sit','amet,','consectetur','adipiscing','elit,','sed','do','eiusmod','tempor','incididunt','ut','labore','et','dolore','magna','aliqua.','Ut','enim','ad','minim','veniam,','quis','nostrud','exercitation','ullamco','laboris','nisi','ut','aliquip','ex','ea','commodo','consequat.','Duis','aute','irure','dolor','in','reprehenderit','in','voluptate','velit','esse','cillum','dolore','eu','fugiat','nulla','pariatur.','Excepteur','sint','occaecat','cupidatat','non','proident,','sunt','in','culpa','qui','officia','deserunt','mollit','anim','id','est','laborum.']

1. Observe that, by adjusting the window width, you can get the cell contents to collide with timing and cell number at far right.
2. The same sort of collision is observable with a markdown cell, although there is no execution time displayed.

![image](https://user-images.githubusercontent.com/528072/114656234-4ffd2000-9cb3-11eb-8fc3-5a5d2b178248.png)

Reported by Sean Raleigh.

**Comment by williamstein** [comment]
It moved so no longer a problem:

<img width="962" alt="image" src="https://github.com/user-attachments/assets/69ea832a-62ca-4a7c-8782-ec8531a79c99">
