### ISSUE TITLE
Support formatting IPython magics

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#5284]
Clicking `Format` on a cell with

```
%pylab
```
results in

```
Error: Error: Python formatter "yapf" exited with code 1:

  File "/tmp/tmp-71qjxfBx4Uhki.tmp", line 1
    %pylab inline
    ^
SyntaxError: invalid syntax
```

This is related to [issue 218 with yapf](https://github.com/google/yapf/issues/218), and makes some ense since this is not valid python code, but it is annoying when working with notebooks.  The [Black jupyter-notebook extension](https://github.com/drillan/jupyter-black) deals with this by [explicitly filtering out magics](https://github.com/drillan/jupyter-black/blob/master/jupyter-black.js).

**Comment by haraldschilly** [comment]
I don't think this has anything to do with black.

This extension comments out percent-lines, runs the formatter, and substitutes those lines back. See https://github.com/drillan/jupyter-black/blob/dd01285bf7bca65a939309727a3a4b95743c9439/jupyter-black.js#L26 calling `re.sub( ... )` twice.

I can imagine we could implement this for jupyter as well.
