### ISSUE TITLE
jupyter: the format button often does nothing

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5289]
WORKAROUND: `Cell --> Format selected cells` in the menu always works.

---

My guess is that this is a "race" involving focus and the definition of "selected cells", but it won't be hard to fix, hopefully.

**Comment by haraldschilly** [comment]
I wonder if this is somehow a focusing issue. What about switching places of Halt ←→ Format? I could try if that fixes it.

**Comment by williamstein** [comment]
I looked into this more.  It's not special to the format button.   To reproduce (in chrome at least):

1. Focus a cell in edit mode
2. Click on *any* button in the same row as Format and no click happens.
3. Then click that same button one more time and it works fine.

What's happening is that when the codemirror editor for the cell loses focus, jupyter switched from edit mode to command mode, which has a bunch of side effects, and one of them prevents the click handler for the button from being triggered.
