### ISSUE TITLE
course: sorting by project status doesn't work

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5292]
if one project is "licensed (running)" and others "licensed (opened)", sorting by status has no effect.

**Comment by williamstein** [comment]
I can't reproduce this.   Look:

![image](https://user-images.githubusercontent.com/1276278/115172818-e007e480-a07a-11eb-987f-cd3d205ea8a6.png)

and

![image](https://user-images.githubusercontent.com/1276278/115172833-e72ef280-a07a-11eb-8e64-00c392f591d2.png)

**Comment by haraldschilly** [comment]
well, for the record, here is a screencast me reproducing this. it's sorting once when I click, but then alternating the direction does nothing. the one that's opened stays in the middle, that's all it does. I assume you tried it in Chrome? I'm using Firefox here.

![Peek 2021-04-19 10-02](https://user-images.githubusercontent.com/207405/115202329-9826a300-a0f6-11eb-9468-069edc15de02.gif)
