### ISSUE TITLE
sagews: jupyter mode can't handle 'text/latex' messages

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5293]
originally reported at https://github.com/sagemathinc/cocalc-example-files/issues/21

fix running this in a sagews:

```
p3 = jupyter("python3")
---
%p3
from IPython.core.display import HTML
HTML('<iframe src="https://en.m.wikipedia.org/" width="95%" height=350>')
```

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.
