### ISSUE TITLE
Julia packages -- current situation is a mess

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5295]
@Harald Schilly It seems that with current Julia:

1. There is no analogue of https://doc.cocalc.com/howto/install-python-lib.html in our docs for how to install a Julia package
2. Doing what Julia says (as below) just fails with a several page error about permissions (since it tries to use a systemwide install).  It does mess with ~/.julia, but that doesn't work.
```jl
julia> using JSON;
ERROR: ArgumentError: Package JSON not found in current path:
- Run `import Pkg; Pkg.add("JSON")` to install the JSON package.
```
3. But just doing `export JULIA_DEPOT_PATH=$HOME/.julia/depot` first and everything works fine...  However, I don't know if this makes it so all the packages you installed systemwide are no longer available.  Doing `export JULIA_DEPOT_PATH=$HOME/.julia/depot:/ext/julia/depot` does NOT work.

Anyway, the solution to this problem might be just seeting JULIA_DEPOT_PATH by default in all cocalc projects everywhere, and that's it.  

OK, I just grepped and discovered that right now we  setup cocalc.com so that JULIA_DEPOT_PATH is busted:
```
/etc/bash-smc.bashrc:export JULIA_DEPOT_PATH="$HOME/.julia:$EXT/julia/depot/"
```
The impact of the above is that it's definitely impossible to install anything as a normal user.  Also it seems that no system-wide packages work at all in Julia right now by default.  I think Julia packaging must have changed dramatically.

I just trued setting `JULIA_DEPOT_PATH=/ext/julia/depot`.  Now just starting up julia blows up with permissions errors in one project.  In another, I can start, but still absolutely no systemwide packages can be imported.

The following would be better than the current mess:

1. We should probably just delete all the systemwide package, since they don't work anyways.
2. Set JULIA_DEPOT_PATH to $HOME/.julia only.
3. People who use Julia can install any packages they need to $HOME/.julia. 

My guess is everything used to just work with that JULIA_DEPOT_PATH, but it got all broke with some new Julia version.

**Comment by haraldschilly** [comment]
I think if you want to install something, you have to define a julia "project" first. That's at least my take away from the online documentation back then when I looked into this the last time. Surely, things could have changed since then, and I don't know when I looked this up. Somewhat when 1.0 came out.

I tested julia in a brand new project (no upgrades, no internet) and I can do plots in a notebook, use sympy, etc. also, in the terminal, sympy works in julia, etc. I really wonder what's going on. Next, I tried manually deleting the `~/.julia`, restarting the proejct, then not deleting it, restarting, all ok. Removing system-wide packages implies dropping the out of the box notebook support, because IJulia is gone. I recommend against doing that.

![Screenshot from 2021-04-17 10-11-43](https://user-images.githubusercontent.com/207405/115106514-8feb2e00-9f65-11eb-9ce8-9b40fba602c6.png)
![Screenshot from 2021-04-17 10-10-40](https://user-images.githubusercontent.com/207405/115106517-911c5b00-9f65-11eb-8c1a-e2647e064d7b.png)

**Comment by williamstein** [comment]
To be clear, right now here is what happens:
```
~$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using SymPy;

julia> using JSON;
ERROR: ArgumentError: Package JSON not found in current path:
- Run `import Pkg; Pkg.add("JSON")` to install the JSON package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:871

julia> import Pkg; Pkg.add("JSON")
   Resolving package versions...
ERROR: SystemError: opening file "/ext/julia/depot/environments/v1.6/Project.toml": Read-only file system
Stacktrace:
[2 pages deleted]
julia> 
~$ export |grep JULIA
declare -x JULIA_DEPOT_PATH="/home/user/.julia:/ext/julia/depot/"
~$ export JULIA_DEPOT_PATH=/home/user/.julia
~$ julia

julia> import Pkg; Pkg.add("JSON")
  Installing known registries into `~/.julia`
       Added registry `General` to `~/.julia/registries/General`
   Resolving package versions...
   Installed JSON ──── v0.21.1
   Installed Parsers ─ v1.1.0
    Updating `~/.julia/environments/v1.6/Project.toml`
  [682c06a0] + JSON v0.21.1
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [682c06a0] + JSON v0.21.1
  [69de0a69] + Parsers v1.1.0
  [ade2ca70] + Dates
  [a63ad114] + Mmap
  [de0858da] + Printf
  Progress [========================================>]  2/2
2 dependencies successfully precompiled in 6 seconds

julia> 

julia> using JSON;

julia> using SymPy;
ERROR: ArgumentError: Package SymPy not found in current path:
- Run `import Pkg; Pkg.add("SymPy")` to install the SymPy package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:871
```

This is an epically terrible user experience, to put it mildly.  The fact that you try to use a package and are told "type this to install it", then get a huge error... but in fact you could install it by changing one env variable which is I guess clearly wrong right now.  Except, if you change that variable, then you loose access to all pre-installed packages.  WTF Julia?  Seriously? 

Also, once you successfully install something locally (by changing the JULIA_DEPOT_PATH temporarily), then you can't use any system-wide packages anymore, even after you reset JULIA_DEPOT_PATH to its default:
```
~$ exit
~$ julia
               _
julia> using SymPy;
ERROR: ArgumentError: Package SymPy not found in current path:
- Run `import Pkg; Pkg.add("SymPy")` to install the SymPy package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:871

julia> 
```

Things work again if you do `rm -rf ~/.julia/` though.

**Question:** Is this really the best they can do with Julia?  You either have access to systemwide packages or local ones, but there's no possible way to have both?   Really?!   If Julia really is this weird, then that's good to know, and at least we can add a section to doc.cocalc.com explaining how to install Julia packages, and that the moment you do so, you no longer have access to anything systemwide.  It would also be very good if there were some way to change or augment the "Run 'import ... to install" error message, at least when using Julia in a cocalc-Jupyter.

I did Google for about an hour or two about this and every result I got was some sort of Julia forum Q/A site with tons of conflicting out of date answers. The env variables are documented [here](https://docs.julialang.org/en/v1/base/constants/#Base.DEPOT_PATH).   Based on that, maybe Julia 1.6's package system just has a major bug in it?

I'm going to mark this issue as upstream and close it.   Based on scanning a bunch of related issues on the Julia issue trackers, it's clear that packaging in Julia is a huge can of worms...
