### ISSUE TITLE
Format for adding student details in bulk

### ISSUE THREAD

**Issue by h00gs** [sagemathinc/cocalc#5302]
When adding students to the course file, the Instructor Guide currently advises to paste a comma separated list into the text box.  It would be great to process this data so that the user can provide a csv list of students including, say First Name, Second Name, Email Address etc.  Maybe automatically recognise field structure, or else require its specification.

**Comment by novoselt** [comment]
One can easily take an arbitrary CSV, read it using pandas, extract fields, create new fields, and eventually output something copy-pasteable into CoCalc. This is as flexible as can be without any complications to the interface.
