### ISSUE TITLE
jupyter: customize environment variables

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5305]
Currently, environment variables for a jupyter kernel are composed of the global variables, the project settings, and the kernel's `env : { ... }` configuration.

The goal of this ticket is to customize them even further via some UI. I think the values should be stored specific to the notebook in  `{metadata: { cocalc: env: { ... }}}`.

One use case is to overrule the `JULIA_*` env vars of the default julia kernel without having to create a new kernel configuration file. Another use case could be to tune the `PYTHONPATH` somehow.

WORKAROUND: copy and modify an existing `kernel.json`'s `"env": { ... }` configuration.

**Comment by williamstein** [comment]
no interest in several years; closing.  maybe this just makes things too complicated.
