### ISSUE TITLE
course: in Configuration --> "Restrict student projects", add a new option "Disable arbitrary collaborators"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5316]
1. As in the title, add yet another option to Restrict student projects called "Disable adding or removing collaborators". 
2. Implement it so that it hides all options from the UI for adding or removing collaborators from the student project.  This includes: in the projects list, in project settings, and in chat.
3. Make a note in the panel labeled "Allow arbitrary collaborators" that the "Disable adding or removing collaborators" option below may be of more use.  

Worry/caveat: Note that a highly motivated student could still create an API key and use the API to get around this.   We can add yet another restriction to the list which is "Disable all use of API keys", which would make it so API keys don't work for student projects.  That's now: #5317

**Comment by haraldschilly** [comment]
this overlaps a bit with the "Collaborator policy / Allow arbitrary collaborators" setting. Maybe both should be consolidated, such that if this collab policy is disabled, the student restriction is set as well?
