### ISSUE TITLE
latex: multi-file dropdown offset + doesn't list the main document

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5320]
this is what I see when there is an `\input{ ... }` in chrome 90:

![Screenshot from 2021-04-28 15-06-09](https://user-images.githubusercontent.com/207405/116411578-235e1200-a836-11eb-903b-728e3f9bb796.png)

apart from that, if I select a file, how do I get back to the main file? I expect to see the main file in that dropdown list as well, but it isn't there.

**Comment by williamstein** [comment]
@haraldschilly I think you fixed this.  If so, please close.
