### ISSUE TITLE
clipboard copy of word with embedded underscore has backslash when using wysywyg editor in .md file

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5323]
1. Open a .md file.
2. In Source view, type `foo\_baz`.
3. In Locked view, select `foo_baz` and copy. Paste somewhere, e.g. into text input on local computer, to view clipboard contents. Verify that `foo_baz` was copied.
4. In Editable view, select `foo_baz` and copy. Paste and view clipboard contents. Observe that `foo\_baz` was copied.

**Comment by williamstein** [comment]
This is intentional.  Copy from editable and paste to something that doesn't know about slate will paste the underlying markdown.   It should get documented though.

**Comment by williamstein** [comment]
OK, I'm convinced otherwise...

**Comment by williamstein** [comment]
Note that it may be impossible to fully support this in safari.

**Comment by williamstein** [comment]
I fixed it and the fix does also work for Safari :-)
