### ISSUE TITLE
webapp crash when removing the last license on a project

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5329]
Seen with latest Chrome and Firefox on macOS 11.2.3.

1. Make a test license (or use anything handy).
2. Make a test project that has no upgrades.
3. Add your test license to the project and restart it.
4. Verify that the project is fully restarted by running a `date` command in the miniterminal.
5. Open project Settings and remove the license. As soon as you confirm by clicking the `Remove` pop-up, you will see a webapp crash.
6. If a project has several licenses, the crash only happens when the last license is removed.

<img width="1223" alt="last-license-crash" src="https://user-images.githubusercontent.com/528072/116963549-c2d43800-ac6e-11eb-82ba-11163a383e1a.png">

**Comment by haraldschilly** [comment]
I think I know what's going on, it's one of these quota calculation functions, which is getting some odd input or so. Certainly fixable.
