### ISSUE TITLE
option to not automatically include chat files when copying directories

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#535]
This should probably be an option when copying files. I imagine that most of the time, people do want to copy the chat. However, for example, if you want peer grading to be anonymous, it should **not** copy the chat.

**Comment by novoselt** [comment]
I suspect it would be a confusing option for people who don't know the underlying implementation. It also should not depend on the implementation, if the question is about preserving or not preserving chats. Rather there should be an option to easily delete chats, if desired. BUT it does not seem to be an issue that comes up.
