### ISSUE TITLE
agplv3 and Commons Clause incompatibilities

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [sagemathinc/cocalc#5351]
Commons Clause terms were added with this commit
https://github.com/sagemathinc/cocalc/commit/edc398702e648e8665531649830ecdd28aa16114
those terms put some restrictions on sales but section 7 of the AGPL let you disregard any additional terms voiding completely the Commons Clause

```
If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.
```

See also https://opensource.stackexchange.com/a/10046

Said this, I'll hope to see cocalc shifting away from the Commons Clause (and re-become fully free)

**Comment by williamstein** [comment]
Cocalc has completely switched to " MICROSOFT REFERENCE SOURCE LICENSE (MS-RSL)", so this problem goes away.
