### ISSUE TITLE
jupyter notebook does not recover from faulty kernelspec

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5358]
The symptom of this is that you can open/see a notebook in CoCalc, but you're not able to evaluate any cells.

 I don't know how this problem happened in the first place, though. It must be related to uploading a notebook from the local computer, and well, some detail is slightly off and then the data is discarded or not set properly.

 To reproduce this, I did the following.

1. new notebook, selected sage 9.3, ran `version()` in a cell and closed/halted it.
2. I edited the ipynb file via vim, and removed all lines inside of `metadata.kernelspec`, i.e. now there is  basically` "metadata": {  "kernelspec": {},  "language_info": { … } , ...` … because that's what I saw in other broken notebooks.
3. after opening the notebook again, it says "sage 9.3" in the top right corner, but I can't run the cell. also, the file on disk still shows the empty kernelspec after trying to save it (the save button stayed active, though)
4. the sage-juypter2 file starts with 
```
{"backend_state":"running","connection_file":"/tmp/xdg-runtime-user/jupyter/kernel-09321e59-020e-4c88-ba65-e102f325b37e.json","kernel_error":"","kernel_state":"idle","kernel_usage":{"cpu":0,"memory":0},"metadata":{"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.2"}},"trust":true,"type":"settings"}
```

expected behavior: if the kernel is not set or invalid, ask the user about the kernel. Furthermore, if there is some inconsistency, properly clear it or synchronize the ipynb file properly with the metadata state. 

workaround: change the kernel back and forth, that somehow resets it properly

**Comment by williamstein** [comment]
I don't think we need to support people arbitrarily corrupting ipynb files.  Closing.
