### ISSUE TITLE
make licensing of instructor project optional

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5360]
When a license is applied to a course under the Configuration tab, that license is also applied to the project containing the course file. This should be optional, e.g. add a checkbox when a license is added in course Configuration to apply the license to the present project. The checkbox could default to checked if there is no license already applied to the teacher project that is not from the present course, and default to unchecked if there is already a license applied to the teacher project that is not from the present course.

**Comment by haraldschilly** [comment]
I just saw a similar case, where the instructor project was already upgraded. I.e. I would extend the above in a way, where that optional checkbox for applying the license is only checked, if the underlying project has no license. If it already has a license, especially when it is active right now, it's usually not necessary to add the license for the course to the instructor project.

**Comment by haraldschilly** [comment]
I just saw yet another even more confusing case, where several licenses were used to upgrade a course student by student, but each of these licenses upgraded the instructor project (lengthy list) and no upgrades were left for the student projects.

**Comment by williamstein** [comment]
@haraldschilly did this.
