### ISSUE TITLE
show projects configured for, and using, each license

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5361]
At present, if you have more than one license, it is time-consuming to see which licenses are in use in which projects.

Suggested changes under "Account" / "Licenses" / "Licenses that you manage":

1. Move the line "License can be used with up to _n_ simultaneous running projects" up one place, so that number of projects applied and using the license are logically grouped, i.e.:
    
      <img width="621" alt="lic-info" src="https://user-images.githubusercontent.com/528072/119696395-c04fa300-be14-11eb-9ae4-931e23c4adbf.png">

    becomes

      <img width="621" alt="lic-info-2" src="https://user-images.githubusercontent.com/528072/119696461-d198af80-be14-11eb-83ba-e1a36a646d32.png">

2. Add a button for a dropdown list of configured projects next to "License is applied to _n_ projects."
3. Add a button for a dropdown list of running configured projects next to "License is being actively used by _n_ running projects."

**Comment by DrXyzzy** [comment]
Additional note:

The feature request to view information about which projects are using or are configured to use a given license is complicated by the possibility that the user who is viewing the Licenses tab might not be owner or collaborator on some of these projects. What information could be displayed in this case?

**Comment by williamstein** [comment]
This is now covered by https://cocalc.com/licenses/how-used and neighboring pages.

**Comment by mforbes** [comment]
It would still be very nice if a link to https://cocalc.com/licenses/how-used could be provided in this location, and in https://cocalc.com/settings/licenses.

It would be even better if `License applied to 1 project (<project name>)` or something similar could be displayed.

(I could not find the how-used page from the CoCalc interface, even though I knew it existed... I had to search on Google.)
