### ISSUE TITLE
terminal causes issues with garbled binary output in history

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5369]
The problem I experienced were piling up hub websocket messages, i.e. the hub connection status indicator turned red and maxed out at 17 messages. this causes me to no longer be able to open more files, etc.

the root problem seemed to be a terminal of a python file (frame editor → split  → terminal), whose history was full of binary output -- I accidentally ran `cat <elf binary>`. 

I don't know the actual chain of problems, but I fixed this by overwriting the history with this silly script: `while true; do echo ok; done` (and ctrl-c after a second or two, of course). deleting the hidden history file itself didn't work, because it was restored immediately.

the webapp console showed some warnings when opening that terminal with the problematic history (unable to parse). I assume the the error handling isn't working properly.

**Comment by haraldschilly** [comment]
IIRC @williamstein fixed this

**Comment by williamstein** [comment]
> IIRC @williamstein fixed this

Confirmed, I did fix this.  I got really annoyed one day by it, and I also had a good reproducible test case.
