### ISSUE TITLE
name in filename tabs is cutoff

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5375]
the top is cutoff, see:

![Screenshot from 2021-06-14 09-36-22](https://user-images.githubusercontent.com/207405/121855926-2e8cd480-ccf4-11eb-9e0d-3f7a5e474d38.png)

Firefox 88

**Comment by williamstein** [comment]
I don't see this on any MacOS browsers.  I should try on Windows later...  It might be a platform specific issue?

**Comment by haraldschilly** [comment]
Well, I should compare Chrome vs. FF on my desktop. Seems like somewhere a detail is slightly off and pushing this upwards. 

… or well, maybe we have to de-bootstrap this first.

**Comment by williamstein** [comment]
I'm looking at the code right now and there's a suspicious -5px marginTop style in there.  So at least I'll try to rewrite it in a way that isn't so suspicious looking.
