### ISSUE TITLE
sticky file tab's close x in hover state

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5382]
I've not seen this before, prior to the upgrade. one of these "x" to close a file tab suddenly got stuck in the hover state (hovering over it again didn't clear it). … but well, after a brief period, I hovered over it again and it went away. So, maybe just some detail with memoizing/re-rendering. Certainly not a high priority issue.

![Screenshot from 2021-06-16 15-52-42](https://user-images.githubusercontent.com/207405/122231995-3185f180-cebb-11eb-8f0a-5d83569bc999.png)

**Comment by williamstein** [comment]
This stickiness still happens, though now it seems much, much less likely.
