### ISSUE TITLE
Install Flipper for mapping class group computations

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#5386]
Flipper is a program for computing the action of mapping classes
on laminations on punctured surfaces using ideal triangulation coordinates.

- https://github.com/MarkCbell/flipper

Would it be possible to install it system-wide on top of Sage on CoCalc?

```bash
$ sage --pip install flipper --upgrade
```

**Comment by haraldschilly** [comment]
ok, it's installed
