### ISSUE TITLE
missing icon: Dockerfile

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5388]
it's `fa-ship` in `file-associations.ts` … and well, ideally it's the docker logo 🤷🏻 

![Screenshot from 2021-06-18 17-24-09](https://user-images.githubusercontent.com/207405/122584028-2917ed00-d05a-11eb-9c86-62f3e27831b0.png)

**Comment by williamstein** [comment]
Now it looks very dockery:

![image](https://user-images.githubusercontent.com/1276278/122590790-e123a680-d016-11eb-8e02-3e1bc0fe0e76.png)
