### ISSUE TITLE
jupyter: crash when clicking undo (I think)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5409]
I think I accidentally "fat finger" clicked on the undo button in a jupyter notebook, right when I switched to it … it wasn't loaded and well, that should be a good explanation why I see this error.

What I would expect: don't see that error. Just don't do anything while the notebook loads.

… and I'm pretty sure it's more than just the undo button.

![Screenshot from 2021-07-08 16-06-31](https://user-images.githubusercontent.com/207405/124936114-8c1bf480-e006-11eb-97bd-80c434315d5e.png)

**Comment by williamstein** [comment]
not reproducible
