### ISSUE TITLE
cocalc icon in share server

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5414]
Reported by Samuel:

> "On the CoCalc share server at https://share.cocalc.com/share/  there is a missing image on the top left,
where the indicated image location is https://share.cocalc.com/share/cocalc-icon.svg"

This is fixed in my half-done share server rewrite, which I'll be reviving soon: https://github.com/sagemathinc/cocalc/pull/5313
I'm making this ticket though just to make sure this is fixed soon (or maybe just push a temporary fix immediately).

**Comment by haraldschilly** [comment]
I'm closing this, it's clearly fixed by a version 2.0 of the share server
