### ISSUE TITLE
slate: update ToC → this._syncstring undefined

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5415]
I just saw this when I tabbed back to open a slate md editor with an opened ToC

![Screenshot from 2021-07-13 10-38-37](https://user-images.githubusercontent.com/207405/125420123-8d1fd79c-ee45-4993-ba28-943622439b77.png)

**Comment by williamstein** [comment]
Looking at the code, this makes perfect sense.
