### ISSUE TITLE
the clang formatter (for c/c++) is evil -- it re-arranges the order of #includes.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5419]
Create the file sample.c from https://www.mpfr.org/sample.html, which starts with
```c
#include <stdio.h>

#include <gmp.h>
#include <mpfr.h>

int main (void)
{
```

Hit the format button in cocalc, which runs clangformat as defined in this code: src/smc-project/formatters/clang-format.ts

It reformats the above code to start like this:
```
#include <gmp.h>
#include <mpfr.h>
#include <stdio.h>

int main(void) {
```

This is semantically **totally different** (!).  In fact, [the MPFR docs say](https://www.mpfr.org/mpfr-current/mpfr.html#Input-and-Output-Functions)

> "When using a function that takes a FILE * argument, you must include the <stdio.h> standard header before mpfr.h, to allow mpfr.h to define prototypes for these functions."

WOW.   Yes, I was pretty frustrated by this for quite a while...

Solution ideas:
 - is there an alternative formatter that isn't wrong?
 - is there an option to at least not try to alphabetize imports?  That seems nuts.  It's way beyond the sort of thing that prettier would do, and it's really trivial to think of up ways to break things by doing this as the C preprocessor is really powerful.

**Comment by haraldschilly** [comment]
interesting, who would have thought. flag `--sort-includes=0` disables this.
