### ISSUE TITLE
Links in terminal react to hover but cannot be clicked

### ISSUE THREAD

**Issue by StevenClontz** [sagemathinc/cocalc#5423]
I think this was an issue in the past as well, but as of at least last week, links displayed in the terminal could be clicked to open in a new tab. Today they do react to mouse hover, showing an underline and a cursor change as though they can be clicked, but clicking does nothing:

![image](https://user-images.githubusercontent.com/1559632/127165971-9e718fe8-ac1f-483f-bb77-5b742f034437.png)

**Comment by StevenClontz** [comment]
Update: this seems to be specific to cocalc.com links. The GitHub and clontz.org links below clicked just fine.

It seems https://cocalc.com itself is clickable, but https://cocalc.com/[FOO] is not.

![image](https://user-images.githubusercontent.com/1559632/127170452-09039ce6-65f0-43de-a37f-3451cb7e2d8e.png)

**Comment by williamstein** [comment]
Thanks.  I suspect I introduced this bug over the weekend in rewriting how base url's are handled in cocalc itself.  I'll fix it soon.

**Comment by williamstein** [comment]
I've fixed it -- fix should be live in an hour or so after a browser refresh.  Thanks for reporting this.   You can see a link above to the commit that fixes this...
