### ISSUE TITLE
Vim keybindings periodically break while in insert mode

### ISSUE THREAD

**Issue by StevenClontz** [sagemathinc/cocalc#5424]
I'm not sure what the trigger is exactly, but I find that when I'm using Vim keybindings in Insert mode, I often find myself in a strange situation where my cursor appears to go back to Normal mode, but I'm still editing like I'm in Insert mode, but I'm limited in what I can type (e.g. I cannot backspace beyond the position where the bug was triggered).

My workaround is just to escape to Normal mode then reenter Insert mode, which is why I let this go on for a few weeks before finally getting around to reporting it. (I don't remember when exactly this bug cropped up.) So this is annoying, but obviously not urgent.

**Comment by williamstein** [comment]
If you find a way to reproduce it, I'm curious if it happens upstream in codemirror:  https://codemirror.net/demo/vim.html

The vim mode bindings aren't something we wrote, hence the upstream label.

**Comment by StevenClontz** [comment]
I'll be mindful of what the trigger might be and report back if I find it. FWIW I used the CodeMirror demo for a few minutes to rewrite some lines where I hit the bug in CoCalc, and didn't trigger it in the demo. 🤷
