### ISSUE TITLE
allow applying the same license to all courses in a project

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5428]
Customer reports that, for large courses, they create a project for each class, then a course file for each lab section. Configuring the license for all the course files at the start of each term is laborious and time-consuming.

Feature request:
It would be great if there was a way to apply a license to all courses within a project when it is applied to the project.

Note: It may also be useful to allow apply the project license to courses that are added after the license is configured for the teaching project.

**Comment by novoselt** [comment]
This is a relatively rare situation and doing it correctly may be tricky, while it may also be easy to do with a script for a particular university setup.
