### ISSUE TITLE
webapp shows pluto or vscode server launch buttons, despite potentially not installed

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5430]
only show those buttons depicted in the screenshot below, if the associated software is installed – or show them in a disabled state explaining that it isn't installed. this involves extending the project configuration in `smc-webapp/project_configuration.ts` and also the capabilities calculated in the project itself, in `smc-project/configuration.ts`.

then, once the information is in the project configuration in the webapp, update the UI accordingly.

What I don't know is how to check for Pluto in Julia. `using Pkg; haskey(Pkg.installed(), "Pluto")` looks fine, but it's deprecated. Why shouldn't a package manager no longer tell a user, if a package is installed? Weird.

![Screenshot from 2021-08-02 11-42-18](https://user-images.githubusercontent.com/207405/127840952-44b80371-421f-4473-a578-541d7fcd2a0f.png)

**Comment by williamstein** [comment]
- For pluto we could just check for some files in the DEPOT location that indicate Pluto is installed?

**Comment by haraldschilly** [comment]
yes, a rough test is to see if `/ext/julia/depot/packages/Pluto/` exists could be good enough. in python:

```
from os.path import exists, join
from os import environ
import sys
sys.exit(any(exists(join(_, 'packages', 'Pluto')) for _ in environ['JULIA_DEPOT_PATH'].split(":")))
```
although, exit 1 means OK and 0 missing. could be improved 😁

**Comment by haraldschilly** [comment]
This is a project setting. I think for Pluto it just checks if julia executable exists – which is not ideal, but better than nothing.
