### ISSUE TITLE
cocalc frontend crashes with ipynb and timetravel changes

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5442]
Seen on macOS 11.4 with Chrome 92.0.4515.131 (Official Build) (x86_64) and Firefox 90.0.2 (64-bit):

1. Create a new project.
2. Create a jupyter notebook and select python3 system-wide kernel.
3. Enter `print("hello")` in the top compute cell and execute it. Wait for output.
4. Use menu at upper right to switch from Notebook to Timetravel view (do not split the screen).
5. Click the checkbox for "Changes" at upper left.
6. Get immediate crash screen, sample below.
7. Clicking "reload this browser tab" causes the crash screen to return.
8. Clicking "hide this error" gives you a blank browser tab.
9. You can remove the error by signing in with `?session=null`, but trying to open the file with that browser will bring back the crash, i.e. you can't return to Notebook view, until cookies are cleared for cocalc.com.

![tt-crash](https://user-images.githubusercontent.com/528072/128414231-b92e856c-bcad-491c-a3bb-2d5824c43069.jpg)

**Comment by williamstein** [comment]
I can't reproduce this the first try.  But the fromTextArea part of the error makes me think it is related to https://github.com/sagemathinc/cocalc/issues/5440, which is of course related to async loading, probably, or CodeMirror somehow being structured in a way that doesn't fit assumptions of modern bundlers like webpack.

**Comment by DrXyzzy** [comment]
The crash happens 100% of the time for me, on Chrome and Firefox, for every Jupyter notebook I open and select Timetravel in the pulldown menu at right and then check Changes.

- I just tried with Safari Version 14.1.1 (16611.2.7.1.4) on the MacBook Pro. The crash happens there, too.
- The crash also happens running the latest CoCalc Docker image on the Pixelbook and browsing with Chrome on the MacBook Pro.
- And it happens when I run ChromeOs on the Pixelbook and browse with Chrome to https://cocalc.com.

**Comment by williamstein** [comment]
Got it and now I can reproduce it!   This is great news, since hsy and I have been seeing these "fromTextArea" issues, but haven't been able to 100% reproduce them.  Thanks!
