### ISSUE TITLE
kiosk mode: cocalc banner no longer visible

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5451]
when opening a file in kiosk mode, by appending `&fullscreen=kiosk`, the loading banner/status indicator no longer shows up. It's just white with a little bit of text on the left hand side.

Expected is the cocalc loading banner with maybe the customized square icon. Below, the status text and indications about cocalc having loaded and started up properly.

**Comment by williamstein** [comment]
I'm sure I caused this bug in my rewrite of things.

**Comment by williamstein** [comment]
works fine these days:

<img width="1834" alt="image" src="https://github.com/user-attachments/assets/d4ca5492-9df8-42e6-b865-21e5b2f2f847">
