### ISSUE TITLE
admin tab: license edit: json info front end crash

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5459]
Seen with macOS 11.4, Chrome Version 92.0.4515.131 (Official Build) (x86_64).

1. Open admin tab.
2. Select a license and click Edit.
3. In "Structured JSON information", enter part of a key value pair, for example just the start of a key without the closing quotes: `"foo`.
4. Click away from the JSON info field.
5. Get "CoCalc Crashed" pop-up.
6. Clicking "Hide this error" allows you to resume editing.

<img width="1059" alt="admin-license-json-crash" src="https://user-images.githubusercontent.com/528072/129957486-c3472237-7dbe-4473-8098-55d7ca5316dd.png">

**Comment by haraldschilly** [comment]
I'm closing this. There must be a wrapper around this, because in that case and similar ones, no parsing happens … the json string just stays invalid without a warning about being invalid.
