### ISSUE TITLE
Jupyter Custom Kernel in CoCalc

### ISSUE THREAD

**Issue by Hex-commits** [sagemathinc/cocalc#5466]
What we are trying to do is implementing a custom kernel in a CoCalc-Jupyternotebook, testing it with a simple echokernel. 

This kernel works completly fine in the terminal, aswell as the JupyterLab-Server, but **not** in a CoCalc-Jupyternotebook. 

1. We are using [this ](https://jupyter-client.readthedocs.io/en/stable/wrapperkernels.html)version of the echo-Kernel with the respective kernel.json file.
```
from ipykernel.kernelbase import Kernel

class EchoKernel(Kernel):
    implementation = 'Echo'
    implementation_version = '1.0'
    language = 'no-op'
    language_version = '0.1'
    language_info = {
        'name': 'Any text',
        'mimetype': 'text/plain',
        'file_extension': '.txt',
    }
    banner = "Echo kernel - as useful as a parrot"

    def do_execute(self, code, silent, store_history=True, user_expressions=None,
                   allow_stdin=False):
        if not silent:
            stream_content = {'name': 'stdout', 'text': code}
            self.send_response(self.iopub_socket, 'stream', stream_content)

        return {'status': 'ok',
                # The base class increments the execution count
                'execution_count': self.execution_count,
                'payload': [],
                'user_expressions': {},
               }

if __name__ == '__main__':
    from ipykernel.kernelapp import IPKernelApp
    IPKernelApp.launch_instance(kernel_class=EchoKernel)
```

```
{"argv":["python","-m","echokernel", "-f", "{connection_file}"],
 "display_name":"Echo"
}
```
2. We are using jupyter kernelspec install --user {dir with kernel.json}

After selecting the Echo-Kernel we are not getting outputs from the notebook, but with every other tested method.

**Comment by Hex-commits** [comment]
Update: 
I have not yet been able to fix this issue as this behaviour does not only occur for the echokernel, but for a Custom-Python-Kernel aswell in which only the display_name is changed to something distinguishable. 

It seems that the CoCalc-Jupyter-Notebook cannot communicate with the custom kernel(?), while the terminal and JupyterLab-Server are able to use the terminal perfectly fine.

**Comment by haraldschilly** [comment]
@Hex-commits hi, I just started to go over stale tickets.

What I once noticed is this: when running a "python" kernel via jupyter lab, it actually runs python3 – presumably the python interpreter which is running jupyter lab itself (although, I've no clue how jupyter lab actually spawns python kernels). That's really odd. In CoCalc, if your kernel spec says `"python"` it's whatever `python` really is, and that could be python2. 

So, my first idea here is to use `"python3"` in the spec or even be more precise and use the full abs path.

**Comment by Hex-commits** [comment]
You are indeed right! Thanks for the answer!

I forgot to close this ticket, but your solution is exactly what was needed.
