### ISSUE TITLE
with firefox, underscore in terminal is invisible or nearly so

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5469]
Seen on macOS 11.4, Firefox 91.0.2 (64-bit). 

1. Open a CoCalc terminal in Firefox. Use preference in CoCalc of 14 px font size and default monospace font size of 14 in Firefox. 
2. Type or otherwise display text with underscores. Notice that they are hard to see. Examples below.
3. Open Account / Preferences and view the editor sample text that starts with `def is_prime_lucas_lehmer(p):` and note that the underscores are clearly visible.

I copied the editor sample text to file _foo_ and displayed it in a FF terminal. Here are the results.

FF monospace font: Menlo:

<img width="409" alt="menlo-underscore-firefox" src="https://user-images.githubusercontent.com/528072/131268647-091e3baa-b84b-4225-9b37-a021392d9dcd.png">

FF monospace font: Courier:

<img width="410" alt="courier-underscore-firefox" src="https://user-images.githubusercontent.com/528072/131268657-fefe5485-1240-4841-b8d0-698d8ee3c3eb.png">

**Comment by williamstein** [comment]
Looks fine to me today.
