### ISSUE TITLE
jupyter HBox/VBox widget broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5477]
The widget produced by this code in cocalc's jupyter doesn't look ok. The buttons suddenly overlap, certainly when you click on one of them. This did work, although I can't remember exactly how it should layout. The snippet is probably from the official docs.

```
from ipywidgets import Button, HBox, VBox

words = ['correct', 'horse', 'battery', 'staple']
items = [Button(description=w) for w in words]
left_box = VBox([items[0], items[1]])
right_box = VBox([items[2], items[3]])
HBox([left_box, right_box])
```

it happens with FF and Chrome.

![Screenshot from 2021-09-02 09-52-26](https://user-images.githubusercontent.com/207405/131804739-99d39e0f-6141-490e-b39d-b47232a58b40.png)

**Comment by jasongrout** [comment]
It is from the official docs: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html#Natural-sizes,-and-arrangements-using-HBox-and-VBox

<img width="440" alt="Screen Shot 2021-09-02 at 10 22 32 AM" src="https://user-images.githubusercontent.com/192614/131889001-e1ff55ed-df62-411b-bb5d-889c80e514e9.png">

**Comment by williamstein** [comment]
#7687 fixes this.

**Comment by williamstein** [comment]
Now fixed!
