### ISSUE TITLE
Course-Management file structure

### ISSUE THREAD

**Issue by Hex-commits** [sagemathinc/cocalc#5485]
It appears that you can only select the top-directory for the course-management handout/application selection. 

This was unclear from the documentation/reference regarding the [course-management,](https://doc.cocalc.com/teaching-course-management.html) as it is also pretty unintuitive to only being able to select the top folder to share with students.

Example: If we have five assignments in the /assignment-directory, it is impossible for the course to distribute each assignment separately. It is just possible to distribute the entire directory at once.

**Comment by williamstein** [comment]
This is not correct.   However, you cannot select a **subdirectory of an existing assignment**.  My guess is that you made an assignment, then tried to make another assignment inside of that one.

**Comment by Hex-commits** [comment]
Alright, that worked., thanks. 

Would be a neat little feature to hinder people from doing a similiar mistake, especially as there is no error prompt or anything to indicate this behaviour.

**Comment by Hex-commits** [comment]
I am not quite sure if I am understanding you correctly, because this doesn't seem to work without complications.

It appears that you can only distribute exercises/assignments/handouts in a subfolder, if that subfolder already exists in the student files. 
If, for example, the directory 'assignments' does not exist in the students files, but it exists in the filestructure for the course-management, it does not work and does not give an error prompt in any way.

**Comment by vdtoorn** [comment]
I'd like to confirm that this indeed appears to be a problem. In the past this would not pose a problem, so I'd think this is a bug indeed.
