### ISSUE TITLE
Course-Management adding users by name

### ISSUE THREAD

**Issue by Hex-commits** [sagemathinc/cocalc#5488]
If you are adding the student in the course management by searching for a name, **the e-mail address will not be displayed.**

To display both e-Mail and name it is needed to search via the e-mail address.

**Comment by williamstein** [comment]
I don't understand your question here at all.  Can you elaborate?  (Your questions are usually very clear.)

**Comment by Hex-commits** [comment]
You currently have two ways of adding students to a course: 
1. Searching by name,
2. Searching by e-mail

They both work, but if you are adding a student via the name, the e-mail address is not being displayed in the overview. 

Example: The second student was added via an e-mail, while the first one was added through a name. The first one does not have its e-mail displayed.
![image](https://user-images.githubusercontent.com/52512431/132756279-97fb532c-2879-49d9-93d2-e1d90e2f591e.png)

**Comment by williamstein** [comment]
Thanks for the clarification.  This is intentional.  It is a security/privacy issue if you can discover the email address of a cocalc user just knowing their name, and that's exactly the functionality you're asking for.
