### ISSUE TITLE
missing first letter, "ettings" when opening a help request from project settings

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5489]
Reported by Karl-Dieter Crisman. Confirmed with current Chrome and Firefox on macOS.

1. Open the Settings tab for any CoCalc project.
2. Click the Help button to start a support request.
3. See the typo, "ettings":

<img width="412" alt="ettings" src="https://user-images.githubusercontent.com/528072/132719219-9206d4ed-ecc4-4e76-8f03-5903882765e1.png">

**Comment by DrXyzzy** [comment]
Also reported by Travis O'Brien.

**Comment by haraldschilly** [comment]
I think this is no longer the case, since a new tab opens with a different page altogether. Please re-open if there is something else I'm missing about this.
