### ISSUE TITLE
Error when uploading an avatar image

### ISSUE THREAD

**Issue by zuphilip** [sagemathinc/cocalc#5492]
I try to upload an avatar image in my account and receive there an error, which points to ["Element type is invalid"](https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=). After reloading the page, I can continue but there is no avatar image uploaded.

**Comment by williamstein** [comment]
Confirmed.

**Comment by zuphilip** [comment]
Thank you @williamstein for fixing it.
