### ISSUE TITLE
email settings vanish

### ISSUE THREAD

**Issue by dennmuel** [sagemathinc/cocalc#5493]
Hi!

When you enable email sending in the site settings, additional mail settings appear. However, if you change "Email backend type" to "none", all additional email settings (including backend type) immediately disappear.

I saw no way to make them reappear other than reloading the site without saving the form or (if you've already saved the form) manually change the setting in the db, e.g.:

`update server_settings set value = 'smtp' where name = 'email_backend';`

(Encountered this in a Docker instance.)

**Comment by williamstein** [comment]
Thanks.  The admin settings page is admittedly really bad from a usability perspective compared to the rest of CoCalc.

**Comment by williamstein** [comment]
@haraldschilly did actually fix this recently, but it's not live in production...
