### ISSUE TITLE
"Cocalc Crashed" - from client-side JS

### ISSUE THREAD

**Issue by cmielke-vir** [sagemathinc/cocalc#5497]
Got the crash popup, which requested that I file a bug report. So here goes :

```
Application Error: Uncaught TypeError: $(...).popover is not a function @ 2/4542757 of https://redacted-on-prem.dns/cocalc/static/app-e3c976199188485e4c9f.js?9f7665cc6670fb8e7abf
```

Why did this happen? Well, Im trying to get a widget working. Specifically, py3dmol : https://nbviewer.jupyter.org/github/3dmol/3Dmol.js/blob/master/py3Dmol/examples.ipynb

This notebook works in the classical Jupyter Notebook, but I was curious why it doesn't in the Cocalc notebook. After executing the cell, a message appears (from the widget) saying that Javascript wasn't loading. I found the "trust notebook" button in the menu, and clicked it, but can't tell if that feature turned on or not.

I then used the chrome inspector to inspect this warning, and found that the script tag is indeed injected into the page. I then manually copied that javascript code, and executed it in the developer console.

When I do this, the applet successfully renders! But shortly after, the CoCalc backend crashes, which surprises me!

The following JS code is what leads to the crash when executed on the client. Its indeed quite hacky. Evidently they implemented the widget by finding the first script tag on the page, and then inserting a script right above this. I'm not familiar with React, but maybe that can break it?

Anyways, this is clearly a niche problem caused by user (me!), but I'm concerned about the security implications that the client is able to crash the backend.

```

var loadScriptAsync = function(uri){
  return new Promise((resolve, reject) => {
    var tag = document.createElement('script');
    tag.src = uri;
    tag.async = true;
    tag.onload = () => {
      resolve();
    };
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
});
};

if(typeof $3Dmolpromise === 'undefined') {
$3Dmolpromise = null;
  $3Dmolpromise = loadScriptAsync('https://3dmol.org/build/3Dmol.js');
}

var viewer_16321176129882169 = null;
var warn = document.getElementById("3dmolwarning_16321176129882169");
if(warn) {
    warn.parentNode.removeChild(warn);
}
$3Dmolpromise.then(function() {
viewer_16321176129882169 = $3Dmol.createViewer($("#3dmolviewer_16321176129882169"),{backgroundColor:"white"});
$3Dmol.download("pdb:1ubq", viewer_16321176129882169, {}, function() {
viewer_16321176129882169.zoomTo();
	viewer_16321176129882169.render();
viewer_16321176129882169.render();
})
});

```

**Comment by williamstein** [comment]
> I'm concerned about the security implications that the client is able to crash the backend.

It sounds to me like the client is crashing the **frontend**, not the backend.  That message you saw popup is entirely a frontend thing -- it's basically triggered by any uncaught error coming from client Javascript.

Certainly most anything that manipulates the DOM can confuse React, which assumes that only it changes the DOM. This is one reason browser extensions sometimes break web applications.

> I then used the chrome inspector to inspect this warning, and found that the script tag is indeed injected into the page. I then manually copied that javascript code, and executed it in the developer console.

I think any attempts to run Javascript by injecting it into the page are likely to fail in CoCalc.  You have to really jump through hoops these days to implement such insecure behavior, and the components (such as React) that CoCalc builds on just make that really hard.

> When I do this, the applet successfully renders! 

Maybe you can rewrite the Javascript and use 

https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Javascript

unless that's already what you're talking about above?

**Comment by cmielke-vir** [comment]
Glad to hear its not affecting anything on the backend! I was mistakenly believing that the specific project kernel was rebooting.

Thats a million for this pointer into the Ipython docs. Im pretty new to the Jupyter world, having spent years primarily living in PyCharm, but CoCalc is enabling some great team collaboration! This is an awesome resource.

Im not the developer of py3dmol, but I'll see if I can retrofit it to work better with jupyter without relying on weird hacks.

Thanks again!

**Comment by williamstein** [comment]
> Im pretty new to the Jupyter world, having spent years primarily living in PyCharm, but CoCalc is enabling some great team collaboration! 

Thanks -- please continue to tell us your thoughts and ideas.  If you want to video chat sometime, just let us know.  help@cocalc.com.
