### ISSUE TITLE
Autocomplete for words that have been entered by user

### ISSUE THREAD

**Issue by mchandra** [sagemathinc/cocalc#55]
Suppose one is working on a latex document and you enter the word "differential". Now suppose you want to use the same word elsewhere in the document after it has been entered for the first time.

Currently, if you do:

"diff ctrl+spacebar": nothing happens

The feature request is for a dropdown menu where you can choose the word to complete.

**Comment by mkarakoc** [comment]
As an example, it is already an existing feaure in Jupyter notebooks. 

It works with the following  "[word] + TAB " 

See the pic. below:
![image](https://cloud.githubusercontent.com/assets/8684932/9114428/80f0c066-3c62-11e5-80cd-6f3936955a12.png)

**Comment by williamstein** [comment]
Merging into #49
