### ISSUE TITLE
wrong URL accessing analytics.js endpoint

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5506]
when opening cocalc, I saw:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://analytics.js/. (Reason: CORS request did not succeed).
```

because actually, it should access `https://{host}/analytics.js`

**Comment by haraldschilly** [comment]
well, I don't understand for sure what's going on. I  tried to reproduce it, but no luck – neither deleting cookies nor incognito mode.

A weird detail I spot is in the `analytics.js` script, where without `?fqd=false` it sets `var PREFIX = '//cocalc.com/';` (two slashes at the start) … but by default, with `fqd=false`, `PREFIX='/'`. That shouldn't hurt.

So, what breaks in a reproducible way is across domains, i.e. in incognito without cookies, https://doc.cocalc.com/ → post request to `https://cocalc.com//analytics.js` causes `Access to fetch at 'https://cocalc.com//analytics.js' from origin 'https://doc.cocalc.com' has been blocked by CORS policy`. Not sure if this is related. The CORS check should only look at the domain, not the path with double slashes. Weird.

**Comment by williamstein** [comment]
> when opening cocalc, I saw: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://analytics.js/. (Reason: CORS request did not succeed)."

1. Where do you see that?  I've never seen it.
2. What exactly does "when opening cocalc" mean?  In Chrome or Firefox?  Just cocalc.com or signing into your account and  opening the app?

**Comment by haraldschilly** [comment]
hmm, something must have changed. I'll look into it to get a better understanding.

> What exactly does "when opening cocalc" mean? 

no cookies and on any page, e.g. the landing page for terminal or doc.cocalc.com. browser doesn't matter.
