### ISSUE TITLE
distribute handouts/assignments to the Shared class project.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5507]
Add two not-on-by-default options to the configuration of the shared project:

- [ ] also distribute handouts to the shared project
- [ ] also distribute assignments to the shared project

If checked, when clicking to distribute to *all* students, a copy would also go to the shared project.

Alternatively, provide an extra button next to each assignment or handout that distributes just that
assignment or handout to the shared project.    This might clutter the UI a little bit, but would provide
more control and be more discoverable.

**Comment by mforbes** [comment]
Has there been any progress on this?  It would be very helpful for us in an upcoming course.

**Comment by williamstein** [comment]
No progress because I forgot about it.   However, it seems like it would be easy to do.  I'll prioritize it.

**Comment by novoselt** [comment]
What's the point of this?.. If all students already have their own copy, why do they need another one shared?

**Comment by williamstein** [comment]
Also, this could actually cause a lot of confusion with the students having two similar projects with the SAME files.
