### ISSUE TITLE
distributing Handouts and Assignments to > 100 students can take minutes

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5509]
Reported by Jon P Barker.

Discussion:

1. One solution is a completely different approach to distributions (i.e., put files in a queue somewhere and only copy them in when the project actually gets started). 
2. Another solution is moving the distribution process to the backend and using that -- Harald wrote half of this, but there's a nontrivial frontend component to it that isn't done at all.  
3. Another idea is to copy files out of the student project when it is stopping and record when this successfully happened -- but have a fallback to grab any files that didn't get successfully saved due to pre-empt madness.

**Comment by novoselt** [comment]
Still true, but no easy solution is anticipated.
