### ISSUE TITLE
Deleting projects

### ISSUE THREAD

**Issue by Hex-commits** [sagemathinc/cocalc#5512]
Hello!

Is there a way to efficiently delete users from a project? 

If you delete a user from a project, it is just set to a "deleted" state, but you wouldn't be able to add this user to the same project again. 
Is it possibly to delete every user set to "deleted" from the project?

**Comment by williamstein** [comment]
I don't understand your question.   There is no notion of deleting a user from a project in CoCalc.   You can remove collaborators in project settings, but that is immediate and there's no "deleted" state, so I'm guessing you're using the word "project" to refer to something else, though I have no idea what...

This seems more like a discussion - https://github.com/sagemathinc/cocalc/discussions

Can you move this there, and make your question more precise with screenshots.
