### ISSUE TITLE
jupyter: rewrite export to html and pdf to completely avoid using nbconvert

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5541]
Our motivation comes from #5539.  The shortcomings with using nbconvert are:

- It takes around 5 seconds (on cocalc at least) to convert a trivial ipynb file to html.  This should take 1 seconds at most.
- Convert to html without a template is unsable since it truncates long lines.
- Convert to pdf via latex truncates long lines as well, and I don't know how to get around this.
- The exported html seems much too heavy, e.g., a trivial ipynb file results in a 500KB html file.
- There are subtle differences in "fidelity" with the cocalc-jupyter experience, e.g., the syntax highlighting colors are different than the default in codemirror. 

If we instead base our conversion on what we use for the share server, then it should be possible to fix all of these problems except the "conversion via latex" (which I just wanted to list).  It should take fraction of second to do the conversion, we can ensure the output is much more lightweight, etc.

**Comment by bitsnaps** [comment]
I get an error in the first project trying to export a PDF from a jupyter notebook:
```
 Save and Download as PDF
Error
Running nbconvert failed with an error less than a minute ago. Read the error log below, update your Jupyter notebook, then try again.
killed command 'bash /tmp/cocalc-XJJBPA/a.sh'
```

**Comment by williamstein** [comment]
> I get an error in the first project trying to export a PDF from a jupyter notebook:
> 
> ```
>  Save and Download as PDF
> Error
> Running nbconvert failed with an error less than a minute ago. Read the error log below, update your Jupyter notebook, then try again.
> killed command 'bash /tmp/cocalc-XJJBPA/a.sh'
> ```

You might want to open a support request if we didn't already fix this.  In any case, there are a million ways to break nbconvert...

**Comment by williamstein** [comment]
I'm closing this issue because I actually did "rewrite export to html and pdf to completely avoid using nbconvert" as an option long ago, e.g., the "Save and download as...HTML [and PDF]" option doesn't use nbconvert at all. Instead it uses our own notebook renderer in a chromium headless mode running in the project.
