### ISSUE TITLE
Handouts: allow display full path for long file names

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5553]
In the Handouts tab of a course file, long paths are abbreviated, although there is ample room for them. For example, suppose there is a Handouts folder `HandoutLongPathNameQwerty/HandoutSubLongPathNameQwerty`. This is displayed in the Handouts tab as:

![image](https://user-images.githubusercontent.com/528072/140522729-3b6e63d4-ecbf-4fce-bbe1-e28bdaa5d17b.png)

Two possible solutions:

1. Allow adjusting the width of the leftmost column in the Handouts tab, e.g. by dragging the divider between handout path and the Distribute button, OR
2. Wrap the path name, as is done with Assignments.

Requested by Jean-Marc Schwartz.

**Comment by novoselt** [comment]
Definitely 2. and #1152 may address it
