### ISSUE TITLE
List public files in a project

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#556]
https://cloud.sagemath.com/projects/091c876f-c64e-44b3-95e4-fabae565fc8a/files/01_Online_database_assignment/Online_database_in_class.html is public but going to https://cloud.sagemath.com/projects/091c876f-c64e-44b3-95e4-fabae565fc8a/files/ doesn’t show any files

**Comment by williamstein** [comment]
Note to who looks at this -- this is currently like standard unix behavior.  You can't get a directory listing on a directory that you don't have read access to.

**Comment by timothyclemansinsea** [comment]
Would an acceptable fix to this be to have a separate listing using "public_paths" table.

**Comment by williamstein** [comment]
I think it would be fine to list all the public files in all subdirectories -- just as you want.  I just wanted to mention what motivated the current behavior.

**Comment by williamstein** [comment]
done long ago, right?
