### ISSUE TITLE
nbgrader: implement "hidden" tests (where hidden is in quotes, as explained below)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5579]
Provide an easy intermediate version of "hidden" tests.  The idea is that these are not visible to the student, but they do technically have them in their project, which makes it very easy to run them.  In particular, we are not concerned with serious security here!  E.g., if a student opens the ipynb file in a terminal using vim, they could see the hidden tests.  However, as they go through and use the notebook, they will not see these hidden tests.  This provides value to them, similar to "answers in the back of the book for the odd numbered problems". 

Concern: I'm not sure if this will introduce further divergence from upstream nbgrader...

**Comment by mforbes** [comment]
Perhaps related: is there any way for students to request for their notebooks to be "officially" graded, running against the full tests in the course account, then getting a report?  There are potential issues, including overloading the course account (maybe limit how frequently students can request this), but it should be possible to implement without introducing upstream nbgrader divergence.

**Comment by williamstein** [comment]
Closing because diverging from upstream sucks.
