### ISSUE TITLE
broken jupyter kernels cause the UI to hang

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5582]
A broken kernel isn't properly handled and reported as an error in the UI. It is specific to such cases, where the executable exists – and gets launched by `execa` in `jupyter/launch_jupyter_kernel.ts` – but immediately returns without anything further. The Jupyter UI of CoCalc then waits for the kernel to start, but that never happens – neither an error happens.

The solution must be to improve how `execa`'s spawn object is handled in `jupyter.ts`.
* check if there is still a process and it didn't immediately exit.
* maybe there are events that have no listener yet
* other ideas?

Here is a snippet for the terminal to create a faulty configured kernel. After refreshing the kernel list,  select the one called "broken" in the python section and try to run 1+1. The UI shows a spinner, no error message appears.

```{bash}
mkdir -p ~/.local/share/jupyter/kernels/broken
cat <<EOF > ~/.local/share/jupyter/kernels/broken/kernel.json
{
  "argv": ["/bin/false", "-m", "ipykernel_launcher", "-f", "{connection_file}"],
  "display_name": "broken",
  "language": "python"
}
EOF
```

**Comment by haraldschilly** [comment]
PS: maybe a possible solution is to [listen for `close` events of such a child process](https://nodejs.org/docs/latest-v14.x/api/child_process.html#child_process_event_close). I only see one for `'exit'`.

**Comment by williamstein** [comment]
As of today the behavior in the console, JupyterLab and Cocalc in this example are all the same.  Basically wait about a minute, then they fail.

```sh
~$ time jupyter console --kernel=broken
```
<img width="970" alt="image" src="https://github.com/user-attachments/assets/6eadf6c2-1a94-4a79-acc0-ef0dc6249785">


JupyterLab also hangs for a while, then does this:

<img width="1346" alt="image" src="https://github.com/user-attachments/assets/34e15ee2-7b38-4991-a847-986ef794886a">

Finally cocalc does this after about a minute:

<img width="1323" alt="image" src="https://github.com/user-attachments/assets/54959a30-75c9-49ba-b238-cbc28d436c92">

I think cocalc's current behavior is BETTER than JupyterLab -- at least there is an error message.  Closing this.
