### ISSUE TITLE
setting custom env variables in course configuration

### ISSUE THREAD

**Issue by sheinb** [sagemathinc/cocalc#5606]
In the Settings configuration it's possible to setup custom environment variables for a project, and these propagate to kernels that run in the project as well as terminal sessions.  For a course, it would be nice to be able to set environment variables for all the students from the course configuration settings.  Currently, that doesn't seem possible?

**Comment by williamstein** [comment]
There is something now, and it seems like the right way to go:

<img width="659" alt="image" src="https://github.com/user-attachments/assets/31cccbd4-a9a7-40e4-b18b-0b4970064ed1">
