### ISSUE TITLE
howto configure email sending

### ISSUE THREAD

**Issue by szazs89** [sagemathinc/cocalc#5607]
I think it would be useful to write some lines about the suggested email settings (sendgrid, smtp).
I use the docker image for a while (mainly as single user), and I have recently realized that the email sending (to invite for new users or to reset password) does not work. Upgrading the image did not change the situation...
The _Site Settings_ configuration section where emailing is mentioned is also not very clear to me.
(There is an option _Email sending enabled_ and a seemingly independent _Email Configuration_ section.)

Anyway, I enabled email sending and configured SMTP with port 25 and no user auth (because our smtp server accepts such connections on the local network). But no luck and any sign of the connection trials. (It is also not clear whether this setting modification requires a server restart or not. I restarted the docker image but it did not help.) I can connect with telnet to port 25 of our smtp server from the docker image prompt.

When I click on the _Tests: Email: my@addre.ss [Forgot Password]_ nothing happens, not even an error or success message. However, if I try to get a password reset email after a failed login, it writes a message:
> Error: Sending password reset email failed -- TypeError: Cannot read property 'value' of undefined

What do I wrong?

**Comment by szazs89** [comment]
Some progress: I have found some log in `/var/log/hub/out` - at least the errors can be debugged w.r.t. password reset at the login page.

1. It seems that if I set up SMTP then I also need to set up SMTP to _Override email backend_ for password reset email sending.
2. There is no way to use SMTP without authentication data (empty username field).
3. Using secure SMTP through port 465 did not work for me (possibly different ssl version):
```
sending password reset via secondary smtp server failed; trying sendgrid. [Error: 140383091120000:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
```
our SMTP server logs:
```
SMTP protocol synchronization error (input sent without waiting for greeting): rejected connection from ...
```
4. finally, **I was able to get password reset email using unsecure SMTP 25 and a dummy authentication.** Hopefully, these settings as primary Email sending will also work.

**Conclusions**
1. IMHO for _Override emailbackend_ there should be the foloowing options:
  * no/default: to use the primary settings (sendgrid/smtp)
  * sendgrid(?)
  * smtp: to set up secondary SMTP
2. for unsecure SMTP setting if there are no auth data (username, etc.) given then unauthenticated smtp connection should be enabled (I admit, that it may be a rare situation nowadays)
3. The _Tests: Email: ... [Forgot Password]_ still doesn't do anything, no log, etc.

**Comment by szazs89** [comment]
Oops, I have submitted it to wrong project. Reposted to [cocalc-docker](https://github.com/sagemathinc/cocalc-docker/issues/145)

**Comment by williamstein** [comment]
deprecated
