### ISSUE TITLE
behaviour of manually graded task (and answer) differs from original nbgrader

### ISSUE THREAD

**Issue by szazs89** [sagemathinc/cocalc#5611]
_(Maybe it is a documentation issue)_
 EDIT: this report is false, the behaviour is _quite_ the same as described in the last column -- see the comments in the follow up

The [Teaching with nbgrader](https://doc.cocalc.com/teaching-nbgrader.html#create-questions) section refers to the [nbgrader documentation](https://nbgrader.readthedocs.io/en/stable/user_guide/creating_and_grading_assignments.html#developing-assignments-with-the-assignment-toolbar) about creating different question type. However, I found the following major dfferences:

| Cell type                         | `nbgrader`              | CoCalc                  | 
|----------------------------------------|--------------------------------|------------------------------|
| Manually graded answer | emptied, editable    | emptied*, editable |
| Manually graded task      | editable*                | locked                   |

where
* _emptied*_ means, that CoCalc makes fully empty this cell, if there is no `=== BEGIN SOLUTION ===` / ` === END SOLUTION ===` snippet in that (in the latter case Cocalc removes only that snippet)
* _editable*_ means, that `nbgrader` enables to edit this cell only  if there is a `=== BEGIN MARK SCHEME ===` / `=== END MARK SCHEME ===` snippet, which is removed from the student version. (CoCalc totally discards any kind of _markings_ end shows the original content but locked in the student version.)

It is quite confusing... (I hope I did not make any mistakes above.)

**Comment by williamstein** [comment]
Regarding "Manually graded tasks", the nbgrader docs say 

> "manually graded tasks cells are not edited by the student.", 

so it seems confusing to me that nbgrader actually makes manually graded tasks editable in some cases.  Is there documentation wrong or confusing?

**Comment by szazs89** [comment]
Hm... it seems I was wrong. Really, the _manually graded task cells_ are not editable either. What confused me is the _MARK SCHEME_ section which is removed by `nbgrader` but not by CoCalc. (I guess this is because of the CoCalc special _Intructor only_ cells, which can be used for the same purpose, i.e. helping the grading.)

(I am trying to migrate collected assignments in CoCalc to submissions in `nbgrader`. Thus, I could use Formgrader and its generated html feedback. And the notebooks use `octave` kernel... :-) )

**Comment by szazs89** [comment]
> In addition to this issue, feel free to create a precise issue related to adding an equivalent to "formgrader and its generated html feedback" to CoCalc. I would be very likely to implement that if it was thought through in a way that makes sense for CoCalc.

As far as I see, there is already a similar issue: #4723 (I continue there...)
