### ISSUE TITLE
Add a new tab to courses that contains the non-configuration panels in the Configuration tab

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5615]
In a course there's a Configuration tab, and most of the panels there are indeed "configuration".  However, a couple aren't:

- Export grades
- Start or stop all student projects
- Run Terminal command in all student projects
- Delete all student projects
- Delete all students
- Copy missing handouts and assignments

All other panels really are "Configuration".  Move the above panels to a tab called maybe "Actions".

I'm not sure if "actions" is the best name.  Any other ideas for what to call this?

I'm labeling this as a bug, since it's a violation of user expectations to call the above things "Configuration".

**Comment by novoselt** [comment]
I immediately thought of "Actions" reading the item list!

I do think that it would be a nice improvement and hopefully reasonably easy. "Configuration" is something to do in the beginning and likely forget. "Actions" are used on a regular basis (hopefully not "Delete all student projects" ;-) - maybe such "actions" can actually stay in configuration tab).

**Comment by williamstein** [comment]
done, we now have "Actions".
