### ISSUE TITLE
server settings' "index_info_html" field does not show up

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5625]
as far as I can tell this is missing

Reference:
* [pug file](https://github.com/sagemathinc/cocalc/blob/fdd55be14e2e17ce29b2a84b53f0e65d83e22841/src/webapp-lib/index.pug#L84)
* [open cocalc server](https://github.com/sagemathinc/cocalc/blob/fdd55be14e2e17ce29b2a84b53f0e65d83e22841/src/smc-hub/open-cocalc-server.ts#L81)

**Comment by williamstein** [comment]
Just an FYI that I have no idea what this is, so without further explanation I won't be able to fix it.  Of course, that's fine if you're planning to fix it.
