### ISSUE TITLE
weird effect when saving disabled latex compilation command

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5641]
1. I have a file `tex.tex`
2. Editing the file +  saving causes a compilation
3. in the build control dropdown I select `<disabled>` in order to prevent those compilations to happen.
4. "false" is set, doesn't compile. ok.
5. However, if I put my cursor into the text field and hit return (or press the save button), it changes the content to `fals 'tex.tex'` 
6. this now causes a "command not found" error to appear

expected: what's the heuristic behind changing the command? Something is off in that case.

**Comment by williamstein** [comment]
I can't reproduce this anymore.
