### ISSUE TITLE
LaTeX problem publishing files in Docker-CoCalc

### ISSUE THREAD

**Issue by ingodahn** [sagemathinc/cocalc#5675]
[This is a minimal notebook](https://cocalc.vcrp.de/share/public_paths/3906cf3bf1f7c2094c6caac13fe1e946c722c0fe) that  throws a KaTeX error of missing 'EOF' in the preview when published in Docker-CoCalc. It uses a SageMath kernel. In markdown cells the LaTeX output is OK. 
The preview is also ok when published on cocalc.com.

**Comment by williamstein** [comment]
deprecated
