### ISSUE TITLE
jupyter/sage: nag users about updating sage (and julia etc.)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5676]
just saw a case where a user was working with sage 9.2 and experienced a problem (problematic latex output) … which is fixed in 9.4. I suspect user didn't realize using an old version of sage.

goal of this issue is to introduce a nag banner, telling the user that a newer version is available. 
1. "update" → newest kernel is selected.
2. "keep" → record this in the metadata, e.g. `{"cocalc": {"ask_update" :false}}` or something like that.

Note: I'm not sure what to do if the kernel version is changed by the user. maybe reset that field, maybe not. Probably just keep it as it is.

**Comment by williamstein** [comment]
Don't show this for student projects.   Assume decision made already.

**Comment by williamstein** [comment]
I'm closing this since it's vague and really needs to be thought through before being implemented.  Also nobody ever asked for it.
