### ISSUE TITLE
Jupyter: Mask final newlines in code cells

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#5680]
Consider not rendering final newlines in a Jupyter code cell
except when editing it.

If not as a global feature, then as an optional setting.

### Rationale

In Jupyter code cells, code cells typically lack trailing newlines,
as they would result in extraneous rendered blank lines,
"wasting vertical space".

The result is "missing newlines" at the end of code cells.

Ideally, trailing newlines in Jupyter code cells would not be rendered
as extra blank lines unless the cell is being edited.

Note that text cells already have that feature.

### Examples

Say I have a code cell containing

```python
def last_first(a):
    r"""
    Return a list similar to `a` except the last
    element of `a` becomes the first element.

    EXAMPLES::

        sage: last_first([3, 4, 5, 6])
        [6, 3, 4, 5]
    """
    return a if not a else [a[-1]] + a[:-1]

def first_last(a):
    r"""
    Return a list similar to `a` except the first
    element of `a` becomes the last element.

    EXAMPLES::

        sage: first_last([3, 4, 5, 6])
        [4, 5, 6, 3]
    """
    return a if not a else a[1:] + [a[0]]
```

The missing trailing newline makes some copy-pasting more cumbersome
than needed because of the need to take care of adding or removing
newlines before and/or after copy-pasting.

For instance

- reorder my functions in the same code cell to have
  `first_last` before `last_first`
- move one of the functions to a separate cell
- copy-paste code snippets inside a Jupyter sheet
  or back and forth between a Jupyter sheet and
  a `.py` or `.sage` document:
  - copy a function from .ipynb to .py/.sage
    so it can be used from other Jupyter sheets
  - copy an example from its own code cell
    to becoming part of a docstring
  - copy an example from a docstring to a code cell
    to test it or to rework it

**Comment by williamstein** [comment]
I don't get this at all.

Also, what does JupyterLab do?
