### ISSUE TITLE
(slate) markdown editor: support reference links

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5684]
```md
This is a link to [CoCalc].

[CoCalc]: <https://cocalc.com>
```

should render like this:

This is a link to [CoCalc].

[CoCalc]: <https://cocalc.com>

In CoCalc, here is what happens:

1. With the static "Locked" view, things work perfectly.  You get a link and it looks and works fine.
2. With the editable view, the links are *converted* to inline link notation:

```md
This is a link to [CoCalc](https://cocalc.com).
```

This appears and works identically in terms of what is rendered.  However, it's annoying if you're trying to work with
the .md file to have such a drastic conversion happen.

The solution is to add a bit of metadata to the link object saying if it is inline or a link whose target is declared elsewhere in the document.  Hopefully it will be possible to modify our markdown-it parser to get this extra info. Here's the official spec  https://daringfireball.net/projects/markdown/syntax#link.

REPORED BY: Michael Forbes

**Comment by williamstein** [comment]
I recently fully implemented caching for the slate rich text markdown editor in CoCalc, which means that a block of markdown is *unchanged* when you use the WYSIWYG editor, unless you explicitly edit that block.  Unfortunately, this currently makes this very problem *MUCH* worse!

1. Start with this document:
```md
This is a link to [CoCalc].

# foo bar

[CoCalc]: <https://cocalc.com>
```
2. Edit the "foo bar" header in the WYSIWYG editable side.  You have thus not in any way touched the line with the link.
3. Get this:
```md
This is a link to [CoCalc].

# foo bar
```

The target of the link is gone!  Thus right now if you opened a document with such references, made any edit anywhere, they would all get deleted.  This is because of caching.  The actual reference is even still there, e.g., if you:
4. Edit the line with the link in it, you then get:
```md
This is the link to [CoCalc](https://cocalc.com).

# foo baz
```

**Comment by williamstein** [comment]
This is caused by the new caching algorithm.  First, Markdown\-it by default parses 

```md
This is a link to [CoCalc].

[CoCalc]: <https://cocalc.com>
```

and

```md
This is a link to [CoCalc](https://cocalc.com).
```

in **exactly the same way.**  They are not distinguishable as output by markdown\-it.   The problem is that the caching code thinks that `This is a link to [CoCalc].` was the input that generated that line, not all three lines, including `[CoCalc]: <https://cocalc.com>` .

**Comment by mforbes** [comment]
I am not sure if it helps, but ultimately I would really like to be able to keep one master list of references for use in all files... but I am not sure if this makes sense outside of a context like Jupyter book.  For Markdown, though, I think that the expected behavior does need to be supported.

**Comment by williamstein** [comment]
> For Markdown, though, I think that the expected behavior does need to be supported.

I've decided to fully support it ASAP in markdown files, since silently corrupting files isn't good.  This might not make any direct difference for you, since you're using a separate file for now... but it is a key step in the right direction (e.g., it would be easy later to add a step into our markdown processing pipeline that includes the contents of your file).

<img width="1243" alt="Screen Shot 2022-05-15 at 7 34 08 PM" src="https://user-images.githubusercontent.com/1276278/168510366-aa718fc6-748e-434b-be3c-6856908ba017.png">.   Already close...
<img width="1310" alt="Screen Shot 2022-05-15 at 7 34 32 PM" src="https://user-images.githubusercontent.com/1276278/168510358-95cb26c4-aeac-4a27-8fae-17bda6b6ea50.png">

**Comment by mforbes** [comment]
@williamstein This looks good (sorry, just got back to trying to edit these).  One suggestion: maybe add a toggle to the "Insert Link" UI to allow inserted links to be added to the reference list.  Maybe something like:

* [ ]: Insert link as a Reference at the bottom of the file.

One other comment: when you move the cursor over the link, you can edit the URL up in the status bar, but you can't edit the title.  I was expecting the link button up their to open the "Insert Link" UI rather than taking me to the website (since it looks the same as the icon immediately above which does this

![Image 7-5-22 at 11 07 AM](https://user-images.githubusercontent.com/1028433/177389348-db15ad98-a22f-4715-a9e4-87a8d3b8d4a8.jpg)

Let me know if I should open new issues for any of these minor suggestions.

**Comment by williamstein** [comment]
> Let me know if I should open new issues for any of these minor suggestions.

YES, please do!

And yes I strongly agree with ".... I was expecting the link button up their to open the "Insert Link" UI rather than taking me to the website ...", i.e., CoCalc should behave like say Gmail's editor regarding links. The main issue is that I just haven't implemented this yet, but haven't a ticket is always a good step.

**Comment by mforbes** [comment]
Done: https://github.com/sagemathinc/cocalc/issues/6037

**Comment by DrXyzzy** [comment]
Added to docs: https://doc.cocalc.com/markdown.html#reference-links
