### ISSUE TITLE
allow automatic collecting & grading of homework at the due date & time

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5690]
This might be two options for a homework assignment:
1. Collect from students when due.
2. If 1) is enabled and assignment uses nbgrader, auto grade after collecting

Questions:
- what to do if work was already collected / graded by instructor before due date
- what to do if instructor wants to manually collect again after auto collection
- what to do if instructor wants to manually augment or override auto grading

Requested by Alan Levy and Siqi Jiao.

**Comment by williamstein** [comment]
dup of #109
