### ISSUE TITLE
student pay option: rewrite to use customizable license rather than fixed one-time $14 subscription

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5702]
- This will make things much more flexible for the instructor, e.g., do students need more RAM or CPU than the minimum? 
- Also students will only pay for the actual dates they need, hence the price will be less for the minimal base plan.

**Comment by novoselt** [comment]
Done!

**Comment by novoselt** [comment]
Um... no idea what that bot is doing...
