### ISSUE TITLE
stripe error when purchasing a license that is at least 1000 days long

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5712]
> Everytime I try I receive an error "Error placing order: The statement descriptor must be at most 22 characters. COCALC LICENSE 1096DAYS is 23 characters long."

Solution:

1. Replace LICENSE by "LIC" in our backend code, and
2. *Also* truncate whatever license description we're going to send to 22 characters, just in case something else happens.  This is mainly for the credit card statement, so this is fine.

**Comment by slel** [comment]
Or use `COCALC 2048DAY LICENSE` (22 character message).  : )
