### ISSUE TITLE
sign-up code for courses

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#572]
Introduce a mechanism for joining a course, such that a user, who is about to become a student in a course, is able to join by entering a code in the account settings. This code is generated as part of the course, and it's enough if it is just a randomly generated temporary string.

This code could be then be displayed in large letters with some minimal instructions in a dedicated tab in the course editor.

The goal is to ease the boarding process for new students, without having to know their email address, etc.

**Comment by timothyclemansinsea** [comment]
What about a generic referral code system? This could be used for course sign up, an affiliate program (think Uber's free ride for giving someone else a free ride), as well as say setup user with a clone of a particular project.

maybe have a table of codes mapping to some action.

{"code": "8ZAD", "action": "enroll_in_course", "course_id": "87530985892"},

**Comment by haraldschilly** [comment]
Sounds like too many things at once. We don't have a clone project ability in the first place, etc. 

Also, for referral links, you would have to be able to email those links to the participants. In my case that motivated the above, I didn't have any email addresses.

**Comment by novoselt** [comment]
Does not seem to be requested frequently.
