### ISSUE TITLE
report error for meaningless interact slider params

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5722]
e.g. this slider makes no sense, because the increment is zero.

```
@interact
def _(r=slider(-3,3,0)):
    print(r)
```

An exception occurs, inside of jquery-ui, which is just confusing. Instead, there should be an error that this is a problematic config.

I mark this upstream, because IMHO right at the moment when `slider(...)` or underneath `IntSlider`/`FloatSlider` are instantiated, these libs should throw an error in the Python world.

**Comment by williamstein** [comment]
To be clear (1) you are talking **ONLY** about Jupyter notebooks and upstream ipywidgets / interact.  For comparison, here's the way I implemented the slider widget for Sage Worksheets:

<img width="1039" alt="Screen Shot 2022-02-09 at 7 13 01 AM" src="https://user-images.githubusercontent.com/1276278/153230156-de735ac1-ee3e-4c80-9379-a0f3536f9414.png">

**Comment by williamstein** [comment]
I'm closing this as unclear, and you didn't answer my question, so it probably doesn't matter.
