### ISSUE TITLE
Add status feature to task editor

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#576]
I'd like to easily share what my status is in connection with my tasks. 

For example I have these tasks:

```
Git editor
* [ ] Make a GitTab component to eliminate the need for @render_[[ tab ]]\_header and @render_[[ tab ]] and port existing code to it
* [ ] Make checkboxes for the changed tracked files and have git commit only commit the selected files
* [ ] Add a configuration to set Github username and personal access token
* [ ] Add tab for accessing/modifying issues. This needs to be able to automatically show me upstream issues if I have an upstream set. 
```

I'd like a "Working on this" button to the right of each one or some other way to select what I'm working on. Then at the top of the tasks display this status. I envision that this status could be displayed elsewhere such as chat or a dedicated project editor showing current status of each project member.

**Comment by williamstein** [comment]
I use hashtags for exactly this.    We could add some extra UI support for such special use of tags.  Should wait until after task list is rewritten in react.
