### ISSUE TITLE
docker version: implement inheriting env vars in courses

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5797]
The kubernetes based versions can manage the env variables of projects and also those of student projects in courses. There is no reason why this shouldn't also work for the stripped down docker version. It's probably a matter of implementing one or two missing details to pass on the env var information of the instructor project to the student projects. (and I don't know, but does customizing the env variables of a project via project settings work in docker? this is obviously a prerequisite for this)

**Comment by vdtoorn** [comment]
I can confirm this works in docker, we use it to link 'guix' profiles to courses so we can control the available software. Thank you for caring about this!

**Comment by novoselt** [comment]
docker version is deprecated.
