### ISSUE TITLE
extract and postgresql 14

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5824]
As explained here: https://github.com/sagemathinc/cocalc/pull/5818#issuecomment-1086039789

we need to make some changes to our code to support PostgreSQL 14, due to changes in how the `EXTRACT` command works in PostgreSQL.

**Comment by williamstein** [comment]
There are I think 5 uses of this in our codebase...

**Comment by haraldschilly** [comment]
yes, I'll look into this
