### ISSUE TITLE
Jupyter&R: keyboard shortcuts for various operators

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5827]
implement these keyboard shortcuts, as defined by RStudio:

- `Ctrl+Shift+M`: `%>%` pipe operator
- `Alt+- | Option+-`: `<-` assignment operator

**Comment by haraldschilly** [comment]
good idea!

**Comment by williamstein** [comment]
Never heard of any interest in this.  This isn't supported by JupyterLab, so we would just be adding something sort of different that people learn and doesn't work in any other Jupyter environment.  I'm closing this, but reopen if you seriously think this is worth the effort.
