### ISSUE TITLE
Rewrite Tasks Editor in React

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#583]
Part of #582.
Relevant issues:
- [ ] #559 
- [ ] #576

**Comment by williamstein** [comment]
Don't forget to add drag-n-drop to lists... like Gigthub now has!  https://github.com/blog/2179-drag-and-drop-tasks-in-markdown-task-lists

**Comment by williamstein** [comment]
will be done in new tasks2 (about to be released)
