### ISSUE TITLE
cocalc-jupyter completion loses focus

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5833]
1. In Jupyter (with python kernel), type `i[tab]`.
2. Hit enter to select the first result using the keyboard.
3. The result is properly inserted and the cell stays green (edit mode), but...
4. The focus is lost.

WORKAROUND: Click to focus the cell again, or hit escape and then enter.     

This is of course an annoying waste of time that is inconsisent with jupyter classic and tab completion expectations, so I need to fix this.

**Comment by williamstein** [comment]
Code cells in the new whiteboard also have the same annoying "loss of focus" bug.

**Comment by haraldschilly** [comment]
dup of https://github.com/sagemathinc/cocalc/issues/5371
