### ISSUE TITLE
frontend: text copy bubble is stuck

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5847]
almost whenever I click on the copy to clipboard icon, e.g. where a license ID is shown, I see a small black "copied" info, which does not disappear. This is certainly new, maybe a few days or a week. I'm on Firefox, maybe relevant.

![Screenshot from 2022-04-09 09-53-07](https://user-images.githubusercontent.com/207405/162562802-f77ba60b-a23e-4e59-a8d0-3664d416df84.png)

**Comment by williamstein** [comment]
I upgraded antd recently, and that's likely the cause of this.
