### ISSUE TITLE
frontend: <code> in hover text is white on white

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5848]
I saw this in the hover box for the memory information. The fixed width formatted parts are not readable any more. This was certainly fine a few days ago...

![Screenshot from 2022-04-09 09-55-13](https://user-images.githubusercontent.com/207405/162562859-bc1b3da1-b28f-4418-8c44-4272acc65870.png)

**Comment by williamstein** [comment]
You wrote a component "CodeWhite" that I think worked around our hacks working around react-bootstrap:
```

export const CodeWhite: React.FC = ({ children }) => (
  <code style={{ color: "white" }}>{children}</code>
);
```
I suspect the fix is just to NOT use that component, and directly use code, since I removed/changed the hacks to workaround react-bootstrap.
