### ISSUE TITLE
New markdown + latex parsing issues as a result of switching to a proper parsing plugin.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5879]
If possible, fix some issues with math detection caused by switching to a proper markdown plugin (instead of *ad hoc* parsing before using markdown).

From Ingo Dahn:
> "https://cocalc.com/share/public_paths/9ed0b3dc5d54079076818e95038cf487b2d2934d contains small examples of 4 different LaTeX related errors on [cocalc.com](http://cocalc.com/)
The notebook - exported from CoCalc -  is available at https://1drv.ms/u/s!AtbWaVSlne64iucuTTHKZ7laKNG2JQ?e=yrog9Z - note the many superfluous backslashes-"

NOTE: There are limits on what is possible using a proper markdown plugin, and I'll do the best I can within those constraints.  However, there is absolutely no possible way I will ever switch back to not using a proper plugin for extracting math from markdown.

The relevant code for all this is here: https://github.com/sagemathinc/cocalc/blob/master/src/packages/frontend/markdown/index.ts#L22

We now use [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath) with some additional rules.

Note that this report gives examples using a Jupyter notebook, but doesn't actually have anything to do with Jupyter; it's really just a general issue with Markdown.

**Comment by ingodahn** [comment]
Correction: The backslashes in the exported files are correct.

**Comment by ingodahn** [comment]
The second error (vanishing content) occurs because the vanishing lines start with expressions in `(..)`.
