### ISSUE TITLE
latex/build: strange white background in stdout 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5885]
in the latex build panel, where it shows the output of running latex, each line has a bright (white?) background. this line-highlighting should be transparent.

![Screenshot from 2022-04-27 14-42-33](https://user-images.githubusercontent.com/207405/165520645-3392e293-e53d-4359-9aa0-f0cfdc15aedb.png)

**Comment by williamstein** [comment]
I don't see that anymore:

<img width="691" alt="image" src="https://github.com/user-attachments/assets/c55b9a03-441a-41f9-be4b-f9f823c0a482">
