### ISSUE TITLE
\sageplot graphs are not displayed in a sagews file

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5901]
This is with SageMath version 9.5, Release Date: 2022-01-30.

<img width="493" alt="sageplot-sagews" src="https://user-images.githubusercontent.com/528072/166553492-aa469f8c-b8f7-47ab-aad7-a5f4df17b61b.png">

**Comment by williamstein** [comment]
For the record, I bet this never worked.  I don't think that %latex cell decorator even knows about sagetex, which would be required for this to work, since it would need to run sage after running latex...

**Comment by williamstein** [comment]
I don't intend to support this ever.
