### ISSUE TITLE
Impossible to get nicely formatted output from sage in jupyter notebook

### ISSUE THREAD

**Issue by lahvak** [sagemathinc/cocalc#5903]
When using sage kernel in a jupyter notebook, I cannot find any way to show nicely formatted output.  I tried all of the the following:

```
eq = (x -1)^2 + (y-1)^2 == 4

show(eq)
```

and

```
eq = (x -1)^2 + (y-1)^2 == 4

pretty_print(eq)
```

and

```
%display latex
eq = (x -1)^2 + (y-1)^2 == 4
eq
```

and all of them show empty output.

This is on the CoCalc.com server with the SageMath 9.5 kernel

**Comment by williamstein** [comment]
Should be fixed after you refresh your browser.

**Comment by williamstein** [comment]
(this was broken for just a few minutes)

**Comment by lahvak** [comment]
Awesome! Thank you!
