### ISSUE TITLE
jupyter: pandas table too dense

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5917]
I'm not 100% happy with how pandas tables look in a jupyter notebook. I'm generally ok to have it more compact to see more entries at once, but as it is right now, it's IMHO too dense.

My first idea is to add just a bit of padding around td/th tags for the dataframe table. 

some code to get a table:

```
import numpy as np
import pandas as pd

xx = np.linspace(-10, 10, rser.size)

rdf = pd.DataFrame({
    'rser': rser,
    'xx': xx,
    'yy': np.sin(xx),
})
rdf
```

look right now:

![Screenshot from 2022-05-08 20-59-26](https://user-images.githubusercontent.com/207405/167311568-d84c4748-a583-4276-b5bc-1be91b99891e.png)

and by manually setting

```
table.dataframe td, table.dataframe th {
    padding: 2px 5px;
}
```

![Screenshot from 2022-05-08 20-59-40](https://user-images.githubusercontent.com/207405/167311617-6aa4cea9-ad96-4c61-aeb0-7bd651e59fb9.png)

of course, this should only be in the output cells of the notebook, and there are certainly other tables as well. So, this ticket is also a bit of experimenting and research. I also wonder what the output of R data.frame's is and how it looks...

**Comment by williamstein** [comment]
What exactly does default upstream JupyterLab/Jupyter Classic do?

I wonder if the above style is a side effect of react-bootstrap or antd or some other global CSS styles?

**Comment by williamstein** [comment]
This is caused by excessive XSS stripping that I recently introduced.

**Comment by williamstein** [comment]
```
import numpy as np
import pandas as pd

xx = np.linspace(-10, 10, 1)

rdf = pd.DataFrame({
    'xx': xx,
    'yy': np.sin(xx),
})
rdf
```

**Comment by williamstein** [comment]
I thought maybe this has to do with sanitization or something else, but it doesn't.   The extra style that is injected in the html is really minimal -- it's just:
```html
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
```

which doesn't do anything interesting related to padding.

I think all that is happening is "nothing special".  In contrast:

- Jupyter classic: it has this special css that provides nicer (but totally arbitrary) style to tables -- https://github.com/jupyter/nbclassic/blob/5b8dd37bdc82ed6cbb8050d1ff14daf0d8951ff3/nbclassic/static/notebook/less/renderedhtml.less
- JupyterLab: something similar with its own special CSS, which looks basically copied from jupyter classic.  It looks the same.
- Deepnote: they have their own custom dataframe viewer, which is always shown
- Colab: looks like JupyterLab, but you can click a button to get their own custom dataframe viewer

Anyway, I dont think this is a new bug.  It's probably been just like this in cocalc for the last 8 years.

Note that none of the other systems appear to do something specific to dataframe.  They just make all tables look nicer, generically.

What I did to fix this is just copy some CSS from Jupyter classic.  Obviously, we should also create a nice renderer/navigator for dataframes, and the approach colab takes seems optimal (normal, but you can optionally do something complicated).

I could NOT figure out how to get the row colors to alternate like in Jupyter classic, so @haraldschilly if you're better at CSS/SASS than me, maybe you would find this a fun puzzle.
