### ISSUE TITLE
jupyter: plotting rdkit chemical formulas in dataframes is broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5939]
this broke very recently. somehow, the embedded image in a dataframe is escaped. this is not an external resource, hence there is no reason to escape it.

notebook: https://cocalc.com/share/public_paths/78baea25947270b18b7297be5df3cc9c7ea3d511

:warning: it only works in anaconda 2021

… and well, I don't know which ones, but I can imagine embedding graphics like that is also used by other libs.

![Screenshot from 2022-05-20 11-03-42](https://user-images.githubusercontent.com/207405/169494393-b90d6db5-45ea-4d09-9ed8-6cc1803cf28e.png)

and that's how those graphics should look like, roughly

![Screenshot from 2022-05-20 11-03-57](https://user-images.githubusercontent.com/207405/169494533-3cedf3fa-c6fa-4b28-ad8e-3e88eca0fa2b.png)

**Comment by haraldschilly** [comment]
also, there are two lines that change the plot type. I made this comment in the notebook:

```
# optionally, comment these two lines & restart kernel, to get another type of plot which does not show up either
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG=True
```

**Comment by williamstein** [comment]
There's multiple things going wrong here:

1. CoCalc not rendering `<img data-content="rdkit/molecule" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUg ...>` is a bug that I can probably fix.  It's probably something simple related to how the base64 encoding is given that doesn't match a heuristic for detecting it.

2. The html escaping seems to be **an upstream bug** having nothing to do with cocalc-jupyter.  I see it when I open your code in JupyterLab then run it *twice*.  I was easily able to reproduce this many times.  The first time running the code the images are fine, and the second time the img tags are all mangled. This is just what jupyter/pandas/rdkit is outputing.  No clue why. This is the second run in JupyterLab:

<img width="1692" alt="Screen Shot 2022-05-20 at 10 11 31 AM" src="https://user-images.githubusercontent.com/1276278/169578822-a4a9f61c-4c5b-4a24-b988-1c6796077f07.png">

**Comment by williamstein** [comment]
I'll make a new ticket for the html manging.

**Comment by williamstein** [comment]
That's now https://github.com/sagemathinc/cocalc/issues/5940
