### ISSUE TITLE
typing in the dev console in chrome always shows the error reporter the first time

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5963]
1. Open cocalc
2. Open the dev console and type anything
3. See a big popup error/crash warning.

This is caused I think by this new bug in the latest version of Chrome, which I guess will be fixed in a few days or weeks: https://stackoverflow.com/questions/72396527/evalerror-possible-side-effect-in-debug-evaluate-in-next-js/72402135

That said, we could whitelist the error message probably to get rid of this.

**Comment by haraldschilly** [comment]
I tried this and at least in `Version 102.0.5005.61 (Official Build) beta (64-bit)` it doesn't exhibit this behavior
