### ISSUE TITLE
table of contents: remove margin to make more efficient use of space

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6017]
Feedback on it:

> "Thank you for implementing the Table of Contents feature [for LaTeX]! I think it is a great idea. I tested it out. Feedback on it: There is a blank white space at the left that decreases workable screen territory, it would be good if it came almost right up to the edge as in this screenshot attached. The Errors & Warnings dialog also eats up screen space."

**Comment by IsaacDodd** [comment]
Thanks for accepting my feedback!
