### ISSUE TITLE
make latex autocompletion more useful

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6018]
Here are some suggestions, with discussions of related tools and their relative value:

> "Yes, the completions showing in a dialogue as one types is the best default feature, in my opinion. I use Vim and use coc.nvim to get this option as do many modern vim users. On Neovim one can use Treesitter or one of the other language-server-based plugins to achieve the same thing. With TeXstudio, autocompletion is also a main feature: whenever I type \cite, it fills in {} with a list of all the citations keys (e.g., dodd_paper_2022, stein_paper_2021, etc.) in the .bib files specified in the \addbibresource{} commands in the file. On Overleaf, the autocompletions are also automatic and the same as TeXStudio. This makes adding citations much easier than any other system and one main feature of the available LaTeX tools of why a lot of people still use LaTeX. It's also in VSCode's intellisense feature which has been around forever in Visual Studio (I don't use VSCode). Both VSCode and coc.nvim accomplish this via a language server. I also have a Ctrl+space capability in other editors but never use it, but I tried this CoCalc method and it doesn't compare to how this feature works in other tools, and the auto-completions aren't as useful. The new commands added for autocompletion also increase/depend on which packages are included in the preamble of the file, the best editor of which that features this being TeXstudio (which is not as good in Overleaf)."

Basically there are two suggestions:

1. ability to show completions automatically without having to type control+space
2. make the actual completions more useful.

Probably the best approach for cocalc is to implement LSP support for latex.

**Comment by IsaacDodd** [comment]
Thanks for posting my feedback. I think it would really be a game-changer if LSP support were added for LaTeX in CoCalc! I wonder what other TeXnicians using CoCalc's LaTeX features think; I'm certain many would agree.

**Comment by williamstein** [comment]
Here is the LSP implementation for latex:  https://github.com/latex-lsp/texlab

Note -- it is GPL licensed, so like with Sage/Pari/etc., we could only use it via a non-binary link. That's likely perfectly fine for an LSP implementation.

**Comment by williamstein** [comment]
From IsaacDodd:

Hello William Stein,

No problem! Also, I want to share with you sir some resources on the Language Server Protocol for LaTeX auto-completions:

# Language Server Protocols (LSP) & Clients

## Why LSP's:
- https://langserver.org/
- https://www.kieranbamforth.me/post/vim-lsp
- https://kichwacoders.com/2017/07/28/what-about-a-common-debug-protocol/
- https://invidious.snopyta.org/watch?time_continue=547&v=O970hPeMrwM
- https://joereynoldsaudio.com/2020/03/17/ctags-lsp.html

## Definition
- https://en.wikipedia.org/wiki/Language_Server_Protocol
- https://microsoft.github.io/language-server-protocol/specification
- https://microsoft.github.io/language-server-protocol/
- https://github.com/Microsoft/language-server-protocol
- https://docs.microsoft.com/en-us/visualstudio/extensibility/language-server-protocol?view=vs-2019

### Language List
- https://microsoft.github.io/language-server-protocol/implementors/servers/
- https://langserver.org/

#### Setup
- [NeoVim + LSP Setup From Scratch - Daniel Duan (3:06:43)](https://invidious.snopyta.org/watch?v=ZrySdB6pUCA)
- https://www.vimfromscratch.com/articles/vim-and-language-server-protocol/
- https://www.reddit.com/r/neovim/comments/grrxli/start_to_finish_example_of_setting_up_built_in/

## LSP's for LaTeX

### TeXLab
- https://texlab.netlify.com/
- https://github.com/latex-lsp/texlab
- https://github.com/neoclide/coc.nvim/issues/730
- Dependencies: latexmk, kpathsea (kpsewhich)

### Digestif
- https://github.com/astoff/digestif
- https://github.com/astoff/digestif#installation-and-set-up

### Resources:

- https://www.reddit.com/r/vim/comments/rfaukz/how_vim_completers_work_ycm_coc_etc/
- https://github.com/neoclide/coc.nvim/wiki/Language-servers#example-configuration-for-custom-language-servers
- https://www.reddit.com/r/neovim/comments/8ejfg0/state_of_lsp_servers/
- https://www.reddit.com/r/vim/comments/b3yzq4/a_lsp_client_maintainers_view_of_the_lsp_protocol/

## Vim Plugins

coc.nvim
- https://github.com/neoclide/coc.nvim
- https://github.com/MaskRay/ccls/wiki/coc.nvim

LanguageClient-neovim
- https://github.com/autozimu/LanguageClient-neovim
- https://github.com/MaskRay/ccls/wiki/LanguageClient-neovim
- *Pros*: Written in Rust (fast)

Vim-LSP (VimL)
- https://github.com/prabirshrestha/vim-lsp
- *Pros*: Asynchronous; Pure VimL/VimScript
- https://github.com/bfredl/nvim-lspmirror
- [Servers](https://github.com/prabirshrestha/vim-lsp/wiki/Servers)
- [Articles](https://jonasdevlieghere.com/vim-lsp-clangd/)

Vim-LSC
- https://github.com/natebosch/vim-lsc
- https://github.com/MaskRay/ccls/wiki/vim-lsc
- https://bluz71.github.io/2019/10/16/lsp-in-vim-with-the-lsc-plugin.html ***

ALE
- https://github.com/dense-analysis/ale
- https://github.com/MaskRay/ccls/wiki/ALE

**Comment by williamstein** [comment]
Regarding LSP, this may also be useful: https://github.com/jupyterlab/jupyterlab/pull/12534

**Comment by williamstein** [comment]
Another idea (from hamza bodor):

> "Autocompletion for include commands (mainly \includegraphics, which could suggest folders/files from the project). An easier way to browse files. I find that clicking on the browser each time is slightly less user-friendly."

I don't know if LSP would help with that or not.

**Comment by williamstein** [comment]
Now dup of #49
