### ISSUE TITLE
raise the timeout until the red "Something bad must have happened."

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#603]
I'm testing in various coffeeshops as a I travel.  It is quite "reasonable" for 3MB to take  a minute  so I think we should raise this to 60s.

**Comment by williamstein** [comment]
Further remarks, which might argue for not doing this.  Basically if it takes 30s per MB, due to crappy internet, then the rest of SMC won't work anyways.

> "I just spent 3 hours on this problem. I did tweak some parameters, which may improve things a little. However my only conclusion is that with VERY limited bandwidth SMC just can’t work. The websocket gets saturated - for users with many projects (!) – by downloading all the initial query results! That’s potentially several MB of data and with coffeeshop wifi like I have here, will take several minutes. In that time the ping/pong websocket heartbeat fails (I did raise it a bit) and it’s game over. Client reconnects, tries again, fails. So bandwidth is critical.
I want to build something into the client that for now makes it clear if SMC isn’t working due to bandwidth that the user can’t use SMC. That's all I can think to do for now. Sorry. Maybe later multiple websocket channels could help, or something else...."

**Comment by haraldschilly** [comment]
no longer applicable
