### ISSUE TITLE
Feature Request: IDE-esque file browser split panel view.

### ISSUE THREAD

**Issue by jt0dd** [sagemathinc/cocalc#6046]
This seems like it would be a common ask, sorry if duplicate.

I was pretty happy with CoCalc with the exception of one formatting issue we've had a discussion here about, but my collaborators were resistant to using it. When I made them articulate exactly what it was they disliked, I found eventually I agreed with them:

There doesn't seem to be a way to keep the file panel open on the side like traditional IDEs, like:

![img](https://i.gyazo.com/31552841a2044ecac13f9357dc6ccc76.png)

This actually gets pretty annoying. I tried just opening a separate browser windows with the panel open, side by side, but it's not the same - the opened files just open in that window or you have to create new windows. I agree with my colleagues. It's frustrating in my opinion.

This seems like it would be pretty easy to add as a feature, from a web design perspective. Is there some significant challenge to it, or do you just genuinely think it's better not to have it, or unhelpful?

**Comment by williamstein** [comment]
This is now fully implemented via the flyout panels, and in fact it is MUCH more powerful than just the file listing.  You also get a log of all files opened, a vertical tab with stared items, a terminal below the files, etc., etc.:

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/58d72d09-54b4-477b-b6c2-d6a7c85c2f0c">
