### ISSUE TITLE
jupyter: editing cell metadata causes cursor to jump

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6062]
`EditCellMetadata` → `JSONEditor` helps editing the json structure associated with a juypter cell. However, each time it saves the content – which is debounced at 1 second – it does not preserve the cursor position: this is very annoying!

A possible **workaround** is to introduce a syntax error (e.g. start by "x" before the first bracket), edit the content, and then remove the extra x and wait a second if an error appears.

**Comment by williamstein** [comment]
I do not see this problem at all.
