### ISSUE TITLE
cannot enter description in create project dialog

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#6079]
Seen with latest Chrome and Firefox on macOS 12.5.

1. Click "Projects" in the top toolbar.
2. Click "Create New Project...".
3. Observe that there is no input element in the dialog for project description. See screen capture below. This has not always been the case. See the screenshot in the docs at https://doc.cocalc.com/teaching-create-course.html#creating-the-course-project 

<img width="961" alt="create-proj-no-desc" src="https://user-images.githubusercontent.com/528072/184212798-cf2c730f-f019-4db7-9946-4e076021acd6.png">

Is this a deliberate change (feature) or an inadvertent omission (bug)?

**Comment by haraldschilly** [comment]
This was intentionally changed 5 years ago: https://github.com/sagemathinc/cocalc/commit/b8ba036cfe3fe76f103fb24bb3fb5838d2e357c9

**Comment by DrXyzzy** [comment]
Ok, I will update the docs text and screenshot at the link above.
