### ISSUE TITLE
if you put a lot of weird characters in your terminal history that crash xterm.js's renderer, then you get basically locked out of cocalc whenever you open that terminal

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6108]
Sadly, I don't have good steps to reproduce right now, though I saw this when accidentally displaying random invalid memory.

The symptom is pretty confusing - every time you open a terminal in cocalc the red network icon in the upper right goes red and you can't do anything.  The root cause, as the console log shows, is the xterm.js renderer throwing an exception.  

A workaround is to delete foo.term and .foo.term.* and restart the project.  Or, just don't open that terminal.

**Comment by haraldschilly** [comment]
I think this is a dup of https://github.com/sagemathinc/cocalc/issues/5771

**Comment by williamstein** [comment]
Agreed.  I should fix this though it's presumably a bug in xterm.js.  Note that for #5771 you didn't understand how to fix the problem.  The workaround I mention above definitely does fix the problem.  It's critical to restart the project because the history of the terminal is in memory.  Also, one must delete all relevant .term files from disk.
