### ISSUE TITLE
consider various quota presets in the licence purchase dialog

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#6111]
These are the current quota presets at https://cocalc.com/store/site-license

|Name|CPU|RAM|disk|idle t.o.|member|
|-|-|-|-|-|-|
|Standard|1|2|3|30m|y|
|Student|1|2|3|30m|y|
|Student+|1|4|6|2h|y|
|Instructor|1|6|15|2h|y|
|Research|1|6|10|1d|y|
|Development|2|8|10|2h|y|
|Budget|1|1|3|30m|n|

Here are my suggested changes:

- Omit "Standard" as redundant.
- Merge "Research" and "Development" to reduce number of choices.

|Name|CPU|RAM|disk|idle t.o.|member|
|-|-|-|-|-|-|
|Student|1|2|3|30m|y|
|Student+|1|4|6|2h|y|
|Instructor|1|6|15|2h|y|
|Research|2|8|10|1d|y|
|Budget|1|1|3|30m|n|

I initially wanted to add member hosting to Budget. I have changed my mind but suggest rearranging the wording so that the **member hosting is disabled** warning comes immediately after the initial sentence, "Preset 'Budget' is the cheapest option."

Let's discuss this.

**Comment by williamstein** [comment]
this was implemented long ago
