### ISSUE TITLE
CoCalc links with code are not visible. (Should be colored or shaded).

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#6125]
Rendered links in Markdown with code do not visually look like links:

```markdown
* Regular text links: [google.com](google.com).
* Code-formatted links: [`google.com`](google.com).
* Just code: `google.com`.
```
<img width="301" alt="image" src="https://user-images.githubusercontent.com/1028433/190006447-6c6eef74-5a96-46f9-b168-499b803c6b7e.png">

Note that the code-formatted link is not colored, making it not look like a link, but instead, the same as regular code.

For comparison, this is what they look like here on github:

> * Regular text links: [google.com](google.com).
> * Code-formatted links: [`google.com`](google.com).
> * Just code: `google.com`.

**Comment by mforbes** [comment]
This is also an issue in the CoCalc Jupyter Notebook interface.

**Comment by williamstein** [comment]
> This is also an issue in the CoCalc notebook interface.

Thanks. The exact same markdown renderer is used everywhere, so that's why.

**Comment by williamstein** [comment]
>  this is what they look like here on github:

Design wise I would like to copy what Github does for this.
