### ISSUE TITLE
jupyter: splitting markdown cells does not work

### ISSUE THREAD

**Issue by startakovsky** [sagemathinc/cocalc#6132]
I am unable to split a markdown or text cell with ctrl + shift + -. This command, however, works for code cells. In my view this is a bug because it works for both types of cells in Jupyter Classic.  This is for the cocalc website, I am using the latest version of chrome with the latest Mac OS on a MacBook Pro 15" late 2021 model.

**Comment by haraldschilly** [comment]
confirmed, the menu doesn't work either.

if you're on firefox, don't mix this up with https://github.com/sagemathinc/cocalc/issues/4467

**Comment by novoselt** [comment]
Hit this bug as well.
