### ISSUE TITLE
x11/ubuntu 22.04: weird popup messages and windows

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6148]
This is something I noticed just now with cocalc cloud / onprem install. With xpra 3.1 on Ubuntu 22.04, the x11 emulator starts up and works – but there are two strange "windows" popping up right after startup. An error in a script and a terminal.

This applies to "docker" and "onprem" as well.

first (without doing anything)

![Screenshot from 2022-09-30 11-18-20](https://user-images.githubusercontent.com/207405/193245324-8cd8b6d1-4996-40a1-845e-69ff0ed1a2fd.png)

then after closing the above, this pops up:

![Screenshot from 2022-09-30 11-18-38](https://user-images.githubusercontent.com/207405/193245429-9a1566a3-c7ba-4915-814c-6acb12743cca.png)

**Comment by haraldschilly** [comment]
Today I spent some time on this, for the 22.04 release. A lot is unclear to me, especially the second terminal is very weird. But for the first popup, I have a hint: the log says this:

    started command '/etc/X11/Xsession true' with pid 12892

and this looks like a good match to the error. However, I have no idea where this originates from.

**Comment by williamstein** [comment]
What happens if you replace /etc/X11/Xsesssion with a no-op script?
```sh
!#/bin/sh
echo "I'm Xsession"
```

**Comment by haraldschilly** [comment]
Well, I searched the wrong files, I think this is the interesting part. Xpra's own configuration:

```
root@7460ff61dbb9:/etc# grep Xsess xpra/conf.d/60_server.conf
# Xsession can take care of initializing dbus, keyring-daemon
start = /etc/X11/Xsession true
```

So, tweaking this, and maybe some other stuff in /etc/xpra/ will help.

**Comment by williamstein** [comment]
Oh, yes, just don't try to start it.

**Comment by haraldschilly** [comment]
Wow, commenting this out is the solution. I'll see if there are other things to tweak, but so far so good. I'll close this ticket with a note about how to script this properly...

**Comment by haraldschilly** [comment]
magic command to fix this:

    sed -i 's/\(^start = .*$\)/#\1/' /etc/xpra/conf.d/60_server.conf

**Comment by williamstein** [comment]
# 👏
