### ISSUE TITLE
Tab code completion when there are multiple matches

### ISSUE THREAD

**Issue by VectorPosse** [sagemathinc/cocalc#6155]
When I hit tab to use code completion in a Jupyter notebook code cell, if there are multiple matching possibilities, a box opens with those possibilities. When I select the one I want and hit Enter, the code successfully completes. But then my cursor is nowhere to be found. I have to click back in the code cell to keep typing.

I would expect that after selecting the code choice I want and hitting enter, the cursor would appear right after the code and allow me to keep typing. (In fairness, I don't know if this is a Jupyter notebook issue or a CoCalc implementation issue.)

**Comment by DrXyzzy** [comment]
See also: #5833 and #5371.

**Comment by VectorPosse** [comment]
Thanks. Sorry for the duplication.

**Comment by williamstein** [comment]
Sorry for not already fixing this with three tickets about it.

**Comment by williamstein** [comment]
Works fine for me right now.
