### ISSUE TITLE
Better UX for adding authorized SSH key

### ISSUE THREAD

**Issue by marks** [sagemathinc/cocalc#616]
"like github's, except better in that it automatically removes newlines!" - @williamstein

**Comment by williamstein** [comment]
@haraldschilly and I talked a huge amount about this at sage days 81.  This is needed for the k8s backend, since that uses a central ssh gateway server.

**Comment by johnjeng** [comment]
I think this is done?

**Comment by williamstein** [comment]
Indeed, it's done, live and very nice!
