### ISSUE TITLE
"Validate and clean": Validate all cells and delete empty code cells

### ISSUE THREAD

**Issue by binary10** [sagemathinc/cocalc#6194]
Hello CoCalculators,

One of the things I find myself doing regularly when I'm ready to publish/share a notebook is to go through and delete empty code cells that I accidentally leave behind after pressing Cmd-Enter to execute other cells. I would like to suggest a feature in the notebook interface to both "Validate and Clean" when preparing a notebook for export and publication.

The scope of this request is to delete empty code cells or those with only whitespace, not markdown or raw cells, although that may be useful too. Again, the main issue is leftover code cells that are automatically created after running another cell. If a code cell is empty and has nonempty output, then I would want it to be left alone since it could be a case where code was intended to be in the cell and had been run once already.

I do not see this feature in JupyterLab Version 3.2.4 (the closest I could find is "clear all output"). In the vanilla Jupyter notebook interface, Version 6.3.0, there is an option to "Restart and Clear Output", however this is still different than this feature request that is designed to clear empty input code cells.

**Comment by binary10** [comment]
This is a comment by W. Stein on a separate support ticket:

> Yes, I think this is a good idea. The first thing would be to add a command to the command palette (what you get when you click the keyboard icon).
> 
> Can you think of any subtleties regarding deleting empty cells?
> 
> what if the input is empty but the output is not?
> what about markdown/text cells
> is the definition of "empty" really "whitespace only"?
> I'm going to close this ticket and strongly encourage you to make a new github issue here, where there can be further public discussion: https://github.com/sagemathinc/cocalc/issues
> 
> Also, is there a feature like this in the broader Jupyter ecosystem (e.g., JupyterLab, extensions, etc.)?
>

**Comment by williamstein** [comment]
This is now implemented!   There's a new menu option "Edit --> Delete all blank code cells".

Also, if you click the keyboard button in the middle to bring up the command palette you will also find this command.

**Comment by binary10** [comment]
Thank you! This will  make my editing tasks that much simpler.
