### ISSUE TITLE
Names of unpublished folders are not released

### ISSUE THREAD

**Issue by ingodahn** [sagemathinc/cocalc#6199]
This is a continuation of #6172, the fix of whitch enabled a more detailed analysis:

Trying to rename the nice URL https://cocalc.com/ingodahn/mathtrek/Bupyancy of a file /Release/Buoyancy.ipynb (shown during publishing in address bar as  https://cocalc.com/projects/50e2a41e-54a7-4e87-a2ef-9e0edf8015aa/files/Release/) to Buoyancy I get the error

_There is already a public path "Release" in this project with the name "Buoyancy"._

In fact, I had earlier published the complete folder /Release and had later either revoked publication or deleted the folder and created a new unpublished folder Release. But, contrary to the error message, there is currently no published folder Release in the project.

**Comment by williamstein** [comment]
I did implement exactly this "Names of unpublished folders are not released".  However the releasing only happens *after* I implemented it.  I.e., if you unpublished something last week or before, then it isn't released.  You have to publish, then immediately unpublish it to release it.

**Comment by ingodahn** [comment]
Confirm it works. Thanks a lot.
Ingo
