### ISSUE TITLE
Request: "Validate" button will also render Markdown cells

### ISSUE THREAD

**Issue by binary10** [sagemathinc/cocalc#6207]
If markdown cells are in "Markdown" mode, then pressing the validate button does not render markdown cells into "Text" mode. I suggest that the "Validate" button should not only restart the kernel and execute all code cells, but also render all markdown cells (similar functionality to pressing `Esc > Ctrl-A > Shift-Enter`). 

In a more general sense, I believe "Validate" should present the notebook in a final, publishable form. I don't really care if "Validate" is the name of the button or not. This functionality is what matters, and one workflow I consistently go through is:

1. Restart the kernel
2. Run all code cells to verify there are no errors and to renumber all input/output cells.
3. Render all markdown cells.
4. Delete all stray empty cells (code or markdown). 
5. Commit to git, export, share.

The first two steps are currently handled by "Validate". 

Is this write-up a real issue? Maybe not sine all the functionality is available in CoCalc as is if I am willing to do it manually. This suggestion has more to do with the usability of the tool.

**Comment by binary10** [comment]
Oops:
https://github.com/sagemathinc/cocalc/issues/6206

**Comment by williamstein** [comment]
Still thanks for the additional clarification.   Just to be clear there are three modes:

- text, markdown, rendered

and you want rendered.

Also, just a note to people reading this, but "Delete all stray empty cells (code or markdown)." for code is now implemented via "Edit --> Delete all blank code cells".  See https://github.com/sagemathinc/cocalc/issues/6194

Maybe I should also add "Edit --> Delete all blank cells (code and markdown)"?
