### ISSUE TITLE
Blank lines cause CoCalc rendering issues.

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#6210]
In a CoCalc notebook, the following does not properly render the math definitions because of the blank line.  This works in the classic Jupyter notebook backend after trusting the notebook.

```python
%%HTML
<script id="MathJax-Element-48" type="math/tex">
\newcommand{\myA}{A}

\newcommand{myB}{B}
</script>
```

If there is no blank line, this works fine

```python
%%HTML
<script id="MathJax-Element-48" type="math/tex">
\newcommand{\myC}{C}
\newcommand{myD}{D}
</script>
```

(I use this to inject a common set of math macros with `import mmf_setup;mmf_setup.nbinit()`

<img width="512" alt="image" src="https://user-images.githubusercontent.com/1028433/201269887-b78b0584-9108-4a86-9ea9-75f45f8dfceb.png">

**Comment by williamstein** [comment]
For what it is worth, this is now broken much worse in Cocalc Jupyter, because the above will get rendered in an iframe (due to the script tags), and hence have no global effect.

**Comment by williamstein** [comment]
Labeling unclear and security, since maybe we should never render script tags not in an iframe, except possibly for plotly (?).

**Comment by williamstein** [comment]
I've decided to close this.  There is also a javascript mime type with Jupyter, i.e.,
```py
from IPython.display import Javascript
```
