### ISSUE TITLE
disable Pluto.jl upgrade message

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6212]
See https://github.com/fonsp/Pluto.jl/discussions/2364#discussioncomment-4119565

Basically the current message doesn't convey the right information to users of Pluto.jl in a managed service, since they don't have the ability to upgrade anyways.

We have had (and maybe still have) this same problem with JupyterLab and JupyterLab extensions.  Frederic Collonval (QuantStack | @fcollonval ) just demoed in the last JupyterLab meeting a new feature that will *definitely introduce* exactly this problem in the future as well for JupyterLab.  So keep an eye on that as well.  I wish I could tag @fcollonval  on this message somehow.

**Comment by williamstein** [comment]
They are very open to a PR that stats the files where Pluto.jl is installed and if the user doesn't have write permissions maybe doesn't show the upgrade dialog.

**Comment by fcollonval** [comment]
Thanks William for the ping. For JupyterLab, the request to the third party service will be done by the server. That part of the server is customizable and an alternative plugin not looking for updates will be available (although it won't be the default).

Regarding privacy, the server will do the request following a request from a plugin frontend. Administrators can disable that specific plugin if they want. And the user must explicitly agree for the frontend to trigger the request chain that will interrogate the third party service.

**Comment by williamstein** [comment]
@fcollonval Thanks!!

**Comment by williamstein** [comment]
for now, probably the easiest way to "fix" this for pluto is just to upgrade pluto.  @haraldschilly  ?

**Comment by jasongrout** [comment]
Also, IIRC, the url to check for updates is customizable in the settings, which means that a site administrator can configure the default url with site overrides for the default plugin settings. Is that right, @fcollonval?

**Comment by fcollonval** [comment]
> Also, IIRC, the url to check for updates is customizable in the settings, which means that a site administrator can configure the default url with site overrides for the default plugin settings. Is that right, @fcollonval?

Yes indeed - the configuration available is described in the [documentation](https://jupyterlab.readthedocs.io/en/latest/user/announcements.html#configuration)

**Comment by williamstein** [comment]
I'm closing this since users just ignore such messages and it seems they don't care.
