### ISSUE TITLE
Autocorrect switching back to incorrect version when using markdown editor in whiteboard

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#6217]
## Whiteboard Spelling Autocorrect Bug
When using the whiteboard, whenever I misspell a word and select the suggested autocorrect version, it at some point (relatively quickly) reverts to the incorrect version. 

However, when the process is repeated, it is no longer an issue and the new change is retained.

**Comment by williamstein** [comment]
I just tried with both Text and Markdown mode and it worked fine.
