### ISSUE TITLE
Application error when viewing license store

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#6240]
Seen with recent Firefox and Chrome, on MacOS 12.5.1.

1. Open an incognito window in Chrome.
2. Browse to https://cocalc.com/
3. Click "Store" in upper horizontal navbar.
4. Click the big link for "Site License Upgrade".
5. Get a white browser window with the message: `Application error: a client-side exception has occurred (see the browser console for more information).` Console shows 2 instances of `Error: unknown user undefined...`

**Comment by williamstein** [comment]
Oh, this is caused by trying to determine the user type (commercial or academic).
