### ISSUE TITLE
store/site-license undefined user crashes computing the cost of the license

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6241]
Somehow, the state of "user" is sometimes `undefined`. I don't understand why, but my best guess is it has something to do with a `useProfile` hook setting the initial value in `store/usage-and-duration` for the form item "user".

The error then happens in `util/licenses/purchase/compute-cost.ts` where `user` is `undefined` and hence throws an error:

> `Error: unknown user undefined`

**Comment by williamstein** [comment]
This was the exact same problem as #6240.
