### ISSUE TITLE
support variable inspector

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6245]
1. The upstream code is here: https://github.com/lckr/jupyterlab-variableInspector
2. For CoCalc we would make a new frame type.  We can probably run a chunk of the upstream code, but obviously need our own view layer.

Workarounds:

- Use %who and %whos, which are built into Jupyter:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/1276278/205741277-2feec6e2-bfa9-404d-876a-c606dfced6ac.png">

- You could use JupyterLab from CoCalc via +New --> JupyterLab Server, and then use [the variable inspector JupyterLab extension](https://github.com/lckr/jupyterlab-variableInspector) if it were installed.  It isn't right now, but maybe it will be soon.

**Comment by williamstein** [comment]
Also, due to realtime collaboration you can split the frame or open another popup by shift-clicking on the tab and update the variable inspector cell periodically by evaluating it:

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/1276278/205741607-ee19cc33-17b4-446d-9694-450d66782559.png">

**Comment by haraldschilly** [comment]
this is installed in the default 20.04 software environment. page name is `lckr-jupyterlab-variableinspector`.

**Comment by williamstein** [comment]
Closing this in favor of https://github.com/sagemathinc/cocalc/issues/5400
