### ISSUE TITLE
all (?) date selectors are broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6261]
for me, they just show "LLL" instead of a date

courses:

![Screenshot from 2022-12-07 10-55-43](https://user-images.githubusercontent.com/207405/206147444-2093c0a3-cb19-4d21-88bf-0183081bc83f.png)

admin/licenses:

![Screenshot from 2022-12-07 10-56-11](https://user-images.githubusercontent.com/207405/206147611-018cd996-b78e-4884-b22b-83c7bdd6f449.png)

**Comment by williamstein** [comment]
I think you fixed this now.
