### ISSUE TITLE
Student Assignments: Export only shows html

### ISSUE THREAD

**Issue by startakovsky** [sagemathinc/cocalc#6270]
This process of exporting student assignments seems incredibly slow. Not sure if it's because this is the free plan, but it also seems to only produce html files even though the text next to the export button says it will be exported to html and pdf.

![image](https://user-images.githubusercontent.com/689723/206521525-6c4ac607-49a1-468a-b695-c314222a7dc7.png)

**Comment by williamstein** [comment]
Create a support ticket by clicking the Help button (upper right) with your .course file open.  It's not possible to even begin to answer this question, since it's entirely dependent on the context of exactly what is in your assignment.
