### ISSUE TITLE
jupyter: support ipyleaflet widgets

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6272]
[ipyleaflet](https://ipyleaflet.readthedocs.io/en/latest/) let's you embed an interactive map of the world in a jupyter notebook, as a custom widget. As of writing this, the problem right now is

1. we're stuck at `ipywidgets<8` due to cocalc's compatibility requirement.
2. ipyleaflet is a custom widget on top of it.
3. Regarding using classical jupyter or jupyter lab as a fallback: I don't know what dependencies are actually relevant to make it work. I wasn't able to figure them out for our system-wide python3 environment. It's certainly also relevant, which version of the notebook is running vs. what python lib is installed. The only brief luck I had was after re-installing the classic notebook in connection an old anaconda environment. That's certainly not a robust long term solution.
4. I am pretty sure one source of problems is having that older ipywidgets library, because e.g. newer versions of jupyter lab have ipywidgets pre-installed and (my guess) they need version 8.

In any case, the goal it to make this code work:

```python
from ipyleaflet import Map, Marker

center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

marker = Marker(location=center, draggable=True)
m.add_layer(marker);

display(m)
```

producing an interactive map:

![Screenshot from 2022-12-09 17-10-28](https://user-images.githubusercontent.com/207405/206746303-b67e9906-b8a5-4718-b5d4-e8a2101ab5ad.png)

**Comment by williamstein** [comment]
Progress being made!

<img width="978" alt="image" src="https://github.com/user-attachments/assets/8fff93ee-089d-4db1-a650-7685eb08d29a">

**Comment by williamstein** [comment]
ipyleaflet is now fully supported in cocalc-jupyter!
