### ISSUE TITLE
creation and renewing of reseller codes 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6279]
Details to get filled in by Blaec.

**Comment by Blaec-CoCalc** [comment]
Here is the response we received from Marshall at Redshelf:

__________

> I don't have a "best practices" guide, but that would be a great resource to create. Currently, the codes that publishers use contain only letters, numbers, and hyphens ("-"). We don't have rules about 0 vs O, since we have a button on our shelf that copies the code for students to input. Letters can be capitalized or lowercase, it really just depends on how your website redeems codes.
__________

Essentially the restrictions are:
1. Codes can consist of letters, numbers and hyphens only.

2. Letters can be capitalized or lowercase.

3. There are no specified rules to prevent the use of 0 VS O etc. 

Note: The "copy" button seems as though it will make the codes easy to use (even if they are reasonably long).

**Comment by williamstein** [comment]
Maybe use -- https://www.npmjs.com/package/voucher-code-generator

**Comment by williamstein** [comment]
Questions:

- Who can create these codes?   Answer: Admins and (later?) code-generator.  Create a new table of "voucher organization" that contains: id, account_id's, how to invoice them, quota, parameters of pricing/payment, pattern of how to create voucher.
- New table in the database of all vouchers with columns: voucher unique integer id, "voucher org id", code, created, when_redeemed, who redeemed it (account_id), revoked
- Where does an org rep. go for this?  https://cocalc.com/reseller/codes
  - Enter a number, see that many newly created codes.   Everything else is for next version.
- Where does a customer go to redeem a code, e.g. "FR6bwx1q"?    https://cocalc.com/store/redeem
- In addition, make a "Redeem code" button right in the project.  For this, need to add a checkbox or something in the course.  Instructor controls this.  Etc.  But this is mostly for later.

**Comment by williamstein** [comment]
- License needs to have metadata pointing to the voucher that was used to create the license.
- User interface needs to have a way to revoke an existing license and the corresponding voucher.
- voucher org: store how long the "return period" is.   Basically don't invoice them until after it is too late to return the product.  Or we credit them and deduct from the next invoice.

**Comment by williamstein** [comment]
Too vague.  Open a more precise ticket if or when this becomes important again.  We have "credit" vouchers now, which are extremely flexible.
