### ISSUE TITLE
attempt to load Julia "Symbolics.jl" package failed

### ISSUE THREAD

**Issue by TimFH** [sagemathinc/cocalc#6290]
### Discussed in https://github.com/sagemathinc/cocalc/discussions/6286

<div type='discussions-op-text'>

<sup>Originally posted by **TimFH** December 21, 2022</sup>
Why did this fail?

[error.txt](https://github.com/sagemathinc/cocalc/files/10281566/error.txt)
</div>

**Comment by williamstein** [comment]
```sh
julia> using Pkg

julia> Pkg.add("Symbolics")
   Resolving package versions...
ERROR: SystemError: opening file "/ext/julia/depot/environments/v1.7/Project.toml": Read-only file system
Stacktrace:
```

See https://doc.cocalc.com/howto/install-julia-package.html or use a compute server.
