### ISSUE TITLE
jupyter: make css/style consistent between display/editing/download of jupyter notebook

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6305]
See the example here:

https://docs.google.com/document/d/1RpFMDOHKHHaqj02svmsTBdworWrZb6FT80WrIFlumNo/edit

**Comment by vossrf** [comment]
When creating HTML for an open Jupyter notebook using **Save and Download as... HTML**, the HTML file produced is missing the initial CSS Style section that would be appropriate for the notebook.

The use of **Save and Download as... HTML via Classic** or **JupyterLab nbconvert** DOES include the corresponding CSS Style section.

**Comment by williamstein** [comment]
Thanks.  I think this is a side effect of the antd libraries switch in version 5 from a CSS file to a generated CSS in Javascript.  There are still ways to fix this.
