### ISSUE TITLE
frontend/commercial: no internet access → always pop up a dismissable warning banner

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6314]
there are cases where a license is expired or some other situation is the case, where no banner is shown but there is no internet access. 

I propose to always show a dismissable warning – where the trial banner would be – just saying that there is no internet access + implications. (if there is a trial banner, this is not shown, just redundant)

**Comment by williamstein** [comment]
fixed via https://github.com/sagemathinc/cocalc/pull/6316 ?
