### ISSUE TITLE
add libhomfly  optional package to sage

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#632]
When we upgrade sage to sage-7.x, we should add libhomfy, which is an optional package.

REQUESTED BY: Karl Dieter Crisman

**Comment by slel** [comment]
Fixed as libhomfly and libbraiding were made standard in
[Sage Trac ticket 25705, merged in Sage 8.4.beta0](https://trac.sagemath.org/ticket/25705).
