### ISSUE TITLE
next pages: annoying flicker while css style is loaded the first time.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6320]
This is a bug in antd + nextjs caused by antd using css via Javascript and nextjs using server side rendering, and somehow both libraries blaming the other for messing things up.  

Some relevant issues:

- https://github.com/ant-design/cssinjs/issues/69 
- https://github.com/ant-design/ant-design/issues/39891

I did put in a workaround to keep things from being massively more broken (i.e., with it not loading the css at all), which is 

https://github.com/sagemathinc/cocalc/blob/master/src/packages/next/pages/_document.tsx

There may be a workaround once we are using next version 13.x, but that's blocked on other issues.

Fortunately this ONLY impacts the landing pages, share server, and sign in, and not the normal webapp, since it doesn't involve any server side rendering. 

This is just unprofessional and slightly annoying, but doesn't degrade any actual functionality.

**Comment by williamstein** [comment]
This is now solved.

**Comment by rolwin100** [comment]
how did it get solved facing the similar issue @williamstein

**Comment by EXPITC** [comment]
1+

**Comment by emilioaray-dev** [comment]
"I'm using the next app route, and I'm experiencing the same issue today.

https://github.com/sagemathinc/cocalc/assets/18273078/9531b97f-3681-4f85-9819-97f6b1c1a1f3

**Comment by emilioaray-dev** [comment]
Friends, I have achieved a solution. While the DOM is hydrating, I have observed that during this process, there are changes in the body tag:

```html
<body class="__className_6dae51" cz-shortcut-listen="true">
```

It's not displayed correctly until (cz-shortcut-listen="true") appears.
```js
cz-shortcut-listen="true"
```

Therefore, I have created a function to implement in the custom layout in Next.js 13 app router, and this solves the problem.

```JSX
'use client';

import { useEffect, useState } from 'react';


interface LayoutProps {
  children: React.ReactNode | React.ReactNode[];
}

export default function LayoutNameOfYoutComponen(props: LayoutProps) {
  // **ES** Inicialmente establecido en false
  // **EN** Initially set to false
  const [czShortcutListenValue, setCzShortcutListenValue] = useState(false);

  useEffect(() => {
    // **EN** Function to handle changes in the value of cz-shortcut-listen.
    // **ES** Función para manejar cambios en el valor de cz-shortcut-listen.
    const handleCzShortcutListenChange = () => {
      const czShortcutListenAttributeValue = document.body.getAttribute("cz-shortcut-listen");
      // **EN** Check if the value is 'true' to set the state to true, otherwise set to false.
      // **ES** Comprueba si el valor es 'true' para establecer el estado a true, de lo contrario, establece en false.
      setCzShortcutListenValue(czShortcutListenAttributeValue === "true");
    };

    // **EN** Run the function on start.
    // **ES** Ejecuta la función al inicio.
    handleCzShortcutListenChange();

    // **EN** Create a MutationObserver to observe changes in the DOM.
    // **ES** Crea un MutationObserver para observar cambios en el DOM.
    const observer = new MutationObserver((mutationsList) => {
      for (const mutation of mutationsList) {
        if (mutation.type === "attributes" && mutation.attributeName === "cz-shortcut-listen") {
          // **EN** The cz-shortcut-listen attribute has changed, run the handle function.
          // **ES** El atributo cz-shortcut-listen ha cambiado, ejecuta la función de manejo.
          handleCzShortcutListenChange();
        }
      }
    });

    // **EN** Start observing the body element for attribute changes.
    // **ES** Comienza a observar el elemento body en busca de cambios de atributo.
    observer.observe(document.body, { attributes: true });

    // **EN** Returns a cleanup function to stop observing when the component unmounts.
    // **ES** Devuelve una función de limpieza para detener la observación cuando el componente se desmonta.
    return () => {
      observer.disconnect();
    };
  }, []);

  if (czShortcutListenValue) {
    return (
      <>
        <main className="container">{props.children}</main>
      </>
    );
  }
}
```

**Comment by emilioaray-dev** [comment]
> how did it get solved facing the similar issue @williamstein

I just posted a solution. I hope it works for you. And give me your feedback. 👍

**Comment by emilioaray-dev** [comment]
> This is now solved.

I just posted a solution. I hope it works for you. And give me your feedback. 👍
