### ISSUE TITLE
Create a static subdirectory https://cloud.sagemath.com/why/  explaining what SMC supports, e.g., Jupyter, Latex, etc.  -- for SEO

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#638]
Searching Google for `Jupyter hosting` doesn't result in a link to cloud.sagemath.com Based on https://www.google.com/?ion=1&espv=2#q=site%3Acloud.sagemath.com it looks like the policy pages are getting indexed. So create a static page and link from footer titled "Free Jupyter notebook hosting" explaining why one should use Jupyter via SMC.  

Make another static page called "Teaching with jupyter" https://www.google.com/?ion=1&espv=2#q=teaching+with+jupyter

https://www.google.com/?ion=1&espv=2#q=jupyter+cloud
https://www.google.com/?ion=1&espv=2#q=jupyter+online
https://www.google.com/?ion=1&espv=2#q=jupyter+collaboration

**Comment by haraldschilly** [comment]
I propose to make this a more general ticket (not just about jupyter) and do this in a subdirectory called "why", i.e. https://cloud.sagemath.com/why/ ...

**Comment by timothyclemansinsea** [comment]
What about /why/_______/ where blank is some keywords and the page would have good title/content so we can try to get in Google index for common searches?

**Comment by haraldschilly** [comment]
yes, I think we mean the same thing? I meant this as an analog of /policies/*

**Comment by timothyclemansinsea** [comment]
Ah sounds good.

**Comment by GregoryBard** [comment]
This sounds like a great strategy.
---Greg

**Comment by haraldschilly** [comment]
I've again worked on this last week. Assigning issue to myself.

**Comment by haraldschilly** [comment]
I'm closing this. As of today, searching for `Jupyter hosting` shows cocalc as fourth result (in private browsing). So, that goal is reached, and the remainder of the discussion is rather unclear.

![screenshot from 2018-10-11 22-10-10](https://user-images.githubusercontent.com/207405/46831015-808e3700-cda2-11e8-95b9-bc47312106c7.png)

**Comment by slel** [comment]
> As of today, searching for `Jupyter hosting` shows cocalc as fourth result (in private browsing).

In the above, "searching" means "searching Google".

In case you're wondering about other search engines:

- http://msxml.excite.com/search/web?q=jupyter+hosting
- http://results.dogpile.com/search/web?q=jupyter+hosting
- http://search19.lycos.com/web/?q=jupyter+hosting
- http://www.baidu.com/s?wd=jupyter%20hosting
- http://www.info.com/serp?q=jupyter+hosting
- http://www.webcrawler.com/serp?q=jupyter+hosting
- http://www.yippy.com/search/?query=jupyter+hosting
- https://ask.com/web?q=jupyter+hosting
- https://duckduckgo.com/?q=jupyter+hosting
- https://scholar.google.com/scholar?q=jupyter+hosting
- https://search.aol.com/aol/search?q=jupyter+hosting
- https://search.daum.net/search?q=jupyter+hosting
- https://search.naver.com/search.naver?query=jupyter+hosting
- https://search.seznam.cz/?q=jupyter+hosting
- https://search.yahoo.com/search?p=jupyter+hosting
- https://www.bing.com/search?q=jupyter+hosting
- https://www.exalead.com/search/web/results/?q=jupyter+hosting
- https://www.qwant.com/?q=jupyter%20hosting
- https://www.search.com/web?q=jupyter+hosting
- https://www.startpage.com/do/search?query=jupyter+hosting
- https://yandex.com/search/?text=jupyter%20hosting

Not many have CoCalc near the top.

Of course the share of Google in many countries is what it is.

- https://www.statista.com/statistics/220534/googles-share-of-search-market-in-selected-countries/
- https://www.netmarketshare.com/search-engine-market-share.aspx

Baidu's webmaster tools seem to be available only in Chinese.

Studying the "Google Scholar" results might give insights into researcher's needs.

Other queries than [ Jupyter hosting ] might be relevant too...
