### ISSUE TITLE
latex: make reading build command from syncdb more robust

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6397]
saw this in testing

the problem is that `sanitize_build_cmd(cmd)` expects cmd to be an immutable List, but it's actually a Map of `{build_command: [the cmd list] }`. So, how come, there is this `build_command` key?

![Screenshot from 2023-02-03 11-15-36](https://user-images.githubusercontent.com/207405/216574501-2adf8ab3-5d90-4226-8eed-e926e1a02784.png)

**Comment by haraldschilly** [comment]
ok, this was extremely confusing. I don't know if this is just my dev project having faulty data or some backwards incompatibility issue. What's going on is that this is a multi-file latex project. For the main file and one of the tex files it's fine, but once I switch to another one, it fails. syncdb files:

```
$ cat multi/.a.tex.syncdb 
{"key":"build_command","value":["latexmk",....]}
$ cat multi/.b.tex.syncdb 
{"key":"build_command","value":{"build_command":["latexmk",...]}}
```

So, I wonder

1. how did that happen? I'll add a check to discard everything besides an array.
2. Why is the build command even recorded there? It should be in the main latex file's syncdb and that's it. I only edit the included file. The main file is what should be (and currently is) compiled.

**Comment by haraldschilly** [comment]
point 2 is now https://github.com/sagemathinc/cocalc/issues/6398

**Comment by williamstein** [comment]
Closing in favor of #2839
