### ISSUE TITLE
latex with included files: build command should be recorded in main file

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6398]
I have a 3 tex file project where multi/a and /b are included. The syncdb files of the included files have the build command set. That should come from the main file and also be set there.

```
$ cat multi/.a.tex.syncdb 
{"key":"build_command","value":["latexmk",...]}
$ cat multi/.b.tex.syncdb 
{"key":"build_command","value":["latexmk",...]}
```

**Comment by williamstein** [comment]
Closing in favor of #2839
