### ISSUE TITLE
chat: edited already sent messages -- text vanishes after scrolling (also, no undo/redo)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6415]
Prerequisite: a lengthy chat, where (I guess) windowing becomes relevant.

1. type in a message
2. edit it, and make a simple change, but don't save the change
3. scroll up
4. down again

chat is still in edit mode, but my changes are gone.

In case it's relevant, this is with a recent Firefox.

**Comment by williamstein** [comment]
I'll add to this that undo doesn't work when editing a past chat.  It's all because I didn't really fully implement editing of past chats in the same way as composing a new chat, so this is very much a "not implemented error" as well.

**Comment by williamstein** [comment]
Changing priority to high since this could cause data loss (of a few minutes or more work) and frustration.

**Comment by williamstein** [comment]
Related issue: if you are editing a past message while somebody else is actively typing a new message, the chat log scrolls to the bottom and you can't see the message you are editing (or you lose your work due to this very bug).  

Fix -- don't scroll while editing a past chat.
