### ISSUE TITLE
side-chat: slate editor buttons hidden by scrollbar

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6454]
there is somewhere an "overflow-x" that hides the buttons. instead, I guess, we need a "..." hidden button solution like there is with the frame editor buttons.

![Screenshot from 2023-02-17 15-46-04](https://user-images.githubusercontent.com/207405/219689119-4d8b3fcc-1f01-44b8-a86b-762116ca76c1.png)

**Comment by williamstein** [comment]
harald fixed this!
