### ISSUE TITLE
jupyter: clicking table of contents doesn't scroll to header after *double clicking* on a header once

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6457]
A user reported that clicking in the table of contents doesn't properly scroll to the section.  They are using Firefox on a Mac.  I couldn't reproduce this, so they sent me a video.  I still couldn't reproduce it, so I tried to record a video showing that it did work... and then it didn't work.  Literally the act of turning on screen recording is what breaks clicking on headers in the table of contents scrolling to a location!  That's very weird.  This is possible to reproduce every time.  So:

1. Open Firefox or Chrome pointed at a Jupyter notebook with a table of contents.
2. Enable dark mode.
3. Start Quicktime screen recording.
4. Clicking on the table of contents doesn't scroll the notebook properly (maybe it works once).

Any variation of this that I tried doesn't reproduce the problem.

WORKAROUNDS:  

Either of the following will workaround the problem:

- don't use dark mode
- disable Jupyter virtualization at https://cocalc.com/config/editor/jupyter

THOUGHTS:

- This might be impossible to fix.  It is a subtle interaction between dark mode, which is an intense CSS hack, and react-virtuoso's scrolling, which is itself very nontrivial code.  I.e., it's not in code I wrote.  Cocalc does scrolling by making a call to the react-virtuoso library, which is very complicated.  I doubt the author of react-virtuoso will consider "dark mode css hack breaks it while using a screen recorder" even to be a bug.  The only way to fix this issue might be introducing a whole notion of dark mode theming to cocalc itself (via ant'd theming, which exists), then getting rid of our current dark mode entirely.  That would probably require finishing rewriting all of cocalc in antd, which is a major project still.   Alternatively, maybe we could use some sort of other way of doing scrolling when dark mode is enabled.  Of course, this entire problem only seems to happen when recording the screen.  Ugh.

**Comment by binary10** [comment]
I updated the previous ticket with a video showing that the issue still occurs with dark mode deselected and without using screen recording to capture the evidence. It seems to me that this is a bug related to the UI update.

**Comment by williamstein** [comment]
Thanks for the additional information.  Did the problem go away in all cases when you disabled Jupyter virtualization?

**Comment by williamstein** [comment]
Hi -- again thanks for the additional followup.  I studied your evidence further and you're right, this has nothing to do using a screen recorder,  dark mode or Jupyter virtualization.  It's caused by basically *double clicking* on a section header (instead of single clicking).  If you do that it breaks exactly as you reported.    Sorry this was hard for me to realize from your original description and video (since clicking isn't clear in a video).   I should be able to fix this.

**Comment by williamstein** [comment]
Also, it takes a handful of double click attempts on headers to trigger this, for me. It's not caused every time.  Once stuck though, it stays stuck.

**Comment by binary10** [comment]
I appreciate your attention to this. It was fun to do a screen recording with my phone for a change!

**Comment by williamstein** [comment]
Yep, and thanks for so clearly reporting this.  It's been a bug for a long time, but nobody else had properly reported it before.
