### ISSUE TITLE
timeout unaccepted course invitations

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#646]
when someone is being invited to a course and does not accept the invitation, it is resent when the course is opened the next time (and after 2 weeks or so). this means, some are maybe getting spammed with course invitations for years! 

proposed solution: never ever resend a course invitation in the first place. instead, add a button for those who are still in status "invited", such that an invitation is only sent again when explicitly requested -- also keep some sane throttling in the hub (maybe 1 day instead of 2 weeks). then, only explicit actions to lead to such transactional emails, and no implicit actions like "opening the course editor" trigger emails.

(I've set this high priority, because this kind of "spamming" might have already started)

**Comment by williamstein** [comment]
We should also more generally make it so outstanding invitations to collaborate on a project can be cancelled until the person accepts.    A good example UI that does this is GCP's project invite system.

**Comment by williamstein** [comment]
> (I've set this high priority, because this kind of "spamming" might have already started)

For what it is worth, the recipient of said spam could 1-click exclude themselves from SMC emails, right? 

>  this means, some are maybe getting spammed with course invitations for years!

Only if the instructor is opening the course file for years, which makes no sense.

It is important to improve this, but I think the priority should be medium - e.g., never a complaint yet.

**Comment by novoselt** [comment]
>never a complaint yet
