### ISSUE TITLE
Create analytics tracked vertical tabs for landing page

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#647]
Where the video is on landing page make that vertical tabs for Course management, Jupyter in the cloud, etc. Get rid of the content under video/create account and put in tab based area.

**Comment by GregoryBard** [comment]
I can also provide "a second pair of eyes" on this one, if desired.
---Greg

**Comment by haraldschilly** [comment]
Hmm, I don't know what vertical tabs are. General point here is, there is a different landing page and the one it is talked about here is rather about to disappear (or be incorporated into additional static pages for the landing page). Hence I'm closing this.

note: If this idea is about extracting an interest sentiment from analytics data, we should rather have several additional pages at our landing page and then look at their view number and duration.
