### ISSUE TITLE
Insert Code Button broken for Snippets

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#6472]
The button to immediately "insert code" from the snippets tab does not appear to function any longer. I noticed this while giving my demo this morning and had to use the "copy" button instead.

<img width="1512" alt="Screenshot 2023-02-23 at 5 57 16 AM" src="https://user-images.githubusercontent.com/101306074/220928331-5b2f8dce-daf3-4c56-af85-96192eef0854.png">

**Comment by haraldschilly** [comment]
I just tried it, and it works. "insert" and "pick". Judging from your screenshot, maybe the issue is there is no notebook? I mean, it's hard to tell where to insert something, if the target is nothing. In any case, I'll try to replicate this and there should be a warning about no notebook.
