### ISSUE TITLE
Implement private chat, i.e., direct users-to-user chat, which is not associated with a project

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#648]
Christine has been using Facebook chat tonight to keep certain work related chats with me out of the view of co-workers. Slack has private chat which I've used many a time. I'd like private chat so I can have a private conversation about a file in SMC. I've had private chats with Hal as well. He got a hold of me via Facebook.

**Comment by williamstein** [comment]
This makes no sense given the current security and file model of SMC.  The only way to implement this would be via a new notion of chats or chatrooms that are outside of projects.    I have always planned to implement something like that eventually.  It's a lot easier now that sync is done via the database, but it is still a ways off.
