### ISSUE TITLE
frontend/chat/slate: plain URLs are mangled, causing problems

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6497]
This is easy to reproduce, but maybe hard to fix. It's also rather new, because I know it worked. There is also a subsequent crash, which is a follow up problem, but it could be seen as a separate issue.

1. text input in a chat, "text" mode
2. copy/paste the URL of the chat itself
3. send message

observations:
1. the link is broken, because dashes are escaped. I can fix it by editing the chat and the URL, but that's not so great. It's surprising to see the URL is broken.
2. the hover popup doesn't know the project, obviously
3. Clicking on the link crashes the frontend – in particular, it should never crash, rather stop trying to open that broken link

![Screenshot from 2023-03-01 10-10-39](https://user-images.githubusercontent.com/207405/222094753-1bb94226-d670-4e07-9420-fc24af52d4f4.png)

**Comment by haraldschilly** [comment]
@williamstein I'm tagging you on this one, because I know you recently made changes with URLs. Maybe this is a result of that, not sure.

**Comment by williamstein** [comment]
> copy/paste the URL of the chat itself

What does this mean?   Can you just make all your steps to reproduce this precise?  Thanks.

**Comment by haraldschilly** [comment]
1. click in the URL bar of the browser, url is selected
2. ctrl+c keys to copy
3. click in the chat input box with my mouse, to get the cursor there
4. ctrl-v to paste
5. click on the green send button

**Comment by williamstein** [comment]
> It's also rather new, because I know it worked.

The part I just fixed regarding https://github.com/sagemathinc/cocalc/commit/3f68d64716bc61db439ad6b3d7711d7d8d46fbfa 
is I think very old, so nice find.
