### ISSUE TITLE
next app: flicker on switching between certain pages

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6504]
1. Go to https://cocalc.com/features/python
2. Click on various of the subpages, and there is a slight flicker.  This also happens with https://cocalc.com/pricing/products and many other categories.  With network throttling it takes even a noticeable second or so for the cocalc logo to load.
3. Go to the store https://cocalc.com/store and click to change subpages.  It's perfectly smooth, with no refresh of the top bar.

Notice that there aren't full page loads, e.g., look at the bandwidth transfer when you flip through pages at https://cocalc.com/policies/accessibility -- very little data is transferred.  So we are properly using the Link component of next.

The problem is like a mistake in grabbing some information from the frontend via an API call, instead of computing it directly on the backend when creating the response to the query.  Or, alternatively, not using caching of information that was computed the first time via an api call.

Just the fact the upper left logo is being downloaded every single time (that's clear from network logs) and is rendered blank first, might be the entire problem.

**Comment by haraldschilly** [comment]
I looked into this, but haven't found anything yet. Regarding the last point about loading the logo, that's not really true. This is for the icon in the floating menu (when scrolling down) … but even when that floating menu is completely commented out from the code, the same overall behavior happens.

**Comment by williamstein** [comment]
> Regarding the last point about loading the logo, that's not really true. 

It's a different image that is loading every time, which you recently added?   I hope it's possible to fix that.

**Comment by williamstein** [comment]
OK, this flicker is caused by the account dropdown menu.  Since I wrote that, I'll fix it.

**Comment by williamstein** [comment]
There is major flicker caused by the Ask button as well, due to the Icon.  Fixed by making it fixed width.
