### ISSUE TITLE
jupyterlab: provide some sort of help for "XSRF cookie does not match POST argument"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6516]
For unknown reasons randomly people will see "XSRF cookie does not match POST argument" when they try to use the JupyterLab server in CoCalc.  The only fix I know is to delete the relevant cookies, which you can do by just deleting all private data (cookies, etc.,) for cocalc.com.   I even had this happen to myself once, and everything worked fine from other computers, but in one browser I had to clear my private data.

I don't know if we can directly deal with this, but if nothing else, maybe we can add a sentence about this to the panel for starting JupyterLab.

I searched google for `"XSRF cookie does not match POST argument"` and there are many hits -- mostly referring to Jupyter -- that go back 5 or 6 years.  People are mostly mystified and confused and get no good answer.  There are [5 issues](https://github.com/search?q=org%3Ajupyter+%22XSRF+cookie+does+not+match+POST+argument%22&type=issues) in the juypter org about this.  The [most recent one](https://github.com/jupyter/notebook/issues/6657) in Dec 2022 just dismisses the question out of hand "This has been discussed at length [...]" and closes it.

**Comment by haraldschilly** [comment]
See https://github.com/sagemathinc/cocalc/issues/6492

**Comment by williamstein** [comment]
Closing as dup, though there is some useful info about.
