### ISSUE TITLE
Improvement to boxes for deleting/moving files

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#6520]
One comment that I could make about the boxes associated with files in the CoCalc file system (it is fairly easy to accidentally click outside of a box when checking multiple items). This results in losing progress (i.e. boxes checked before accidentally triggering the file via click are unchecked).

**Comment by williamstein** [comment]
Despite this being vague, I 100% understand this ticket, since we discussed it in video chat ;-)
