### ISSUE TITLE
course restrictions: add something like "do not allow students to publish files from their project"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6527]
Right now in course configuration you can restrict many things, to better give exams or keep the students more focused:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/1276278/223763468-7475d7ee-5b1e-4a53-a22a-f7e40fef8f33.png">

It appears in practice that students sometimes get confused and accidentally publish their homework solutions, maybe thinking that is how they are supposed to submit them for grading (I'm possibly being overly generous here).   Those homework solutions then become very popular google search results on our share server, since other students are searching for help on their homework.   So let's add another option to remove public sharing for student projects, to avoid any confusion.  Obviously, a student could still just make another project, copy files there, share the file, etc., so this isn't some hardcore DRM type of thing, but just a gentle push in the right direction for honest (but confused) students.   There are likely a lot of well meaning but confused students.

**Comment by novoselt** [comment]
Done!
