### ISSUE TITLE
add a "Buy a Boost License" button in project settings

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6557]
When clicked, this will be very similar to the current "Buy a License" button, in that it sets the project id in the query parameter, and ensures the license is applied to the project once it is purchased.

However, obviously a significant value add is that we could make the UI in the store for the boost license only allow selecting a boost license that is compatible with the licenses on the selected project.   Also, we can configure business/student to be correct as well.

To me this seems like such a natural thing to do to massively decrease confusion that it should be a high priority.

**Comment by williamstein** [comment]
This is definitely not at all implemented now, since i can set all kinds of params on the boost license that make it incompatible according to the small grey print:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1276278/225959250-7455b0c1-a4a5-4ce8-a00a-65784ea9b803.png">

**Comment by DrXyzzy** [comment]
Suggestion: the UI should address the customer concern. Outsiders don't care what is "boost" or other jargon. They want to add RAM, CPU, disk, or something else. Let's lead with the use case, and not force people to understand a definition before they can figure out if it is what they want.

**Comment by williamstein** [comment]
That's ra great idea.   Of course, maybe we should just implement "pay for what you use" and let users set the RAM, CPU and disk when they start the project (like in every other cloud platform and admin mode).  That might just be a much better use of time.  That could replace boost as well, in that you pay for "the extra" that you use.

**Comment by williamstein** [comment]
Closing since editing licenses is probably easier for people to use.
