### ISSUE TITLE
jupyter: misleading state when opening readonly files

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6580]
1. create file `ro.ipynb`
2. enter something like 1+1, whatever, and save/quit/close it
4. terminal: `chmod ugo=r ro.ipynb`
5. check: `ls -l ro.ipynb` says `-r--r--r-- 1 user user ...`
6. when you open it, it looks fine. … but at the latest when I save, I see something is wrong:
   
   > Error: Error: error writing file: Error: EACCES: permission denied, open /home/user/ro.ipynb'

What I expect: I am not sure, I certainly want to read what's there, but I don't think it should run. Or we allow starting a kernel, with a warning (?), but all input cells should be marked as "readonly & delete protected" and we disallow switching the kernel. Certainly, we can't allow saving the file.

Note: the same works fine for markdown/code files.

**Comment by williamstein** [comment]
If only it were so easy.

**Comment by schrodingersket** [comment]
> If only it were so easy.

My bad - I referenced the wrong issue in my commit message, which implied this had been resolved. I'm still actively working this one.

**Comment by williamstein** [comment]
No worries, it took like 1 second to fix.

**Comment by williamstein** [comment]
Danger -- this could conflict with compute server refactoring...

**Comment by williamstein** [comment]
No longer "danger".

**Comment by williamstein** [comment]
If you open a jupyter notebook on a readonly filesystem (e.g., .snapshots) then everything works fine -- nothing can be changed etc.  I think the issue here is the hidden .ro.ipynb.sage-jupyter2 file is NOT read only.

**Comment by williamstein** [comment]
I was just testing this in production and it feels flaky still.  I'm re-opening it.  The backend detection needs to be totally robust and it isn't for some reason.  it's working on the backend to detect read-only only maybe half the time, which is odd.
