### ISSUE TITLE
Request: add /ext/anaconda_current symlink?

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#6593]
Would it be possible to add a symlink `/ext/anaconda_current` that points to `${ANACONDA_CURRENT}`?  This would make it possible to used the current python in scripts using a shebang:

```bash
#!/ext/anaconda_current/bin/python3
...
```

**Comment by haraldschilly** [comment]
I'll look into this. In general, I would recommend to be explicit, though. If you've activated an anaconda environment, it should be enough to just do `/usr/bin/env python3` to resolve the appropriate python interpreter, e.g.

```
~$ anaconda2022 
Starting Anaconda Python environment
Run 'exit-anaconda' to return to the standard terminal

(base) ~$ head anaconda_current.py 
#!/usr/bin/env python3
import sys
print(sys.executable)

(base) ~$ ./anaconda_current.py 
/ext/anaconda2022.05/bin/python3
```

**Comment by mforbes** [comment]
I am doing this for now, but would argue that this is less explicit: I.e. the behaviour of the script now depends on what the user has done before running it.  The script in question runs `pipx` to install various tools and, while I think it will be okay, I have had issues in the past.  (It seems that in 22.04, both the system python3 and that in anaconda2022 are the same which helps.)

It also used to be that running `anaconda2021` took something like 12 seconds, so it was much more responsive if I could simply run `/ext/anaconda2021.11/bin/conda` to create an environment, but had to know where it is.

With the new 22.04 image, `anaconda2022` is sufficiently fast that this issue no longer exists, so my needs are slowly evaporating.  However, I still think it might be useful for future proofing if there were a reliable way to start something from the current anaconda environment.

**Comment by mforbes** [comment]
Great!  Thanks.
