### ISSUE TITLE
jupyter: rendering while using raw json editor is not robust

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6605]
I made a small change and that broke everything. The change was this:

1. jupyter notebook, split, raw json editor
2. in a cell, `output: [ "" ] `. I.e. a string instead of an object.

… but despite that example, there are possibly many other tiny changes that could break in a similar way.

Expected result: rendering the notebook fails, but not that the UI is completely gone. I want to still have the raw editor around, to have a chance to correct my mistake.

**Comment by williamstein** [comment]
I just simulated some bad mangled json, and now it doesn't crash.  There might be something I missed in which case reopen this with an example...
