### ISSUE TITLE
set the kernel_name field when spawning a Jupyter kernel

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6615]
Right now:

```
import ipykernel
open(ipykernel.get_connection_file()).read()
```

in cocalc outputs an object but with kernel_name empty.  It would be nice if it was the name of the kernel. That is assumed, e.g., by this package: https://github.com/msm1089/ipynbname/blob/master/ipynbname/__init__.py

**Comment by williamstein** [comment]
It would also be easy and natural to set an environment variable to the kernel name.  it would be nice if that could match whatever JupyterLab does, but JupyterLab doesn't do this.  So I propose JUPYTER_KERNEL_NAME.

...

Wait, I see that somebody else already set COCALC_JUPYTER_KERNELNAME in the past.  So maybe I should just close this ticket.

I tried changing how the connection file is created, and the kernel_name gets unset.  It's very weird.  Also, e.g., we explicitly set a version and that is removed. So that connection file must get parsed by the kernel itself, changed, and written back.  

I'm closing this, since the answer is: COCALC_JUPYTER_KERNELNAME

**Comment by haraldschilly** [comment]
this was https://github.com/sagemathinc/cocalc/issues/5165
