### ISSUE TITLE
octave/xeus: error trying to plot using pyplot

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6638]
JupyterLab works fine, but in CoCalc's notebook I only get this:

![Screenshot from 2023-04-17 16-42-38](https://user-images.githubusercontent.com/207405/232520894-e11e6972-5af7-40b3-ae15-44cb7efa6689.png)

MIME is `application/vnd.plotly.v1+json` (assuming I interpret this correctly)

Expected: the plot show up and no funny "transient" (?) error message.

**Comment by haraldschilly** [comment]
Ok, I see, there is also a second "image/png" mime type, that's what's visible. So, the point here is, support the plotly plot. It is interactive, has nice mouse over extras, etc.

**Comment by williamstein** [comment]
Here is what happens now:

<img width="934" alt="image" src="https://github.com/user-attachments/assets/bfc8dc0b-ff0d-499c-9317-44e1a824f14a">

There's no transient message and the plot shows up, and that's what "Expected" says above, so I guess this is good?

Of course, the error also says "error: graphics_toolkit: plotly toolkit is not available", so presumably there's some sort of fallback behavior and plotly isn't being used at all.

I don't even know how to install plotly in octave anymore.  I did some google searches and just got things from 10 years ago.  Maybe it doesn't exist.

I'm closing this.  Reopen if you have actual steps to reproduce the problem.
