### ISSUE TITLE
make sure the content in the Library --> First Steps fully works

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6651]
The Jupyter notebook has a kernel that we don't support anymore!  It needs to be updated and fortunately the autosuggestion does work.

Everything else I tried seems to still work.

**Comment by williamstein** [comment]
Reopening this, since the first steps thing needs to actually be removed from the library at some point, since it's out of date and conflicts now with what is in https://github.com/sagemathinc/cocalc/tree/master/src/smc_pyutil/smc_pyutil/templates/first-steps

**Comment by williamstein** [comment]
I removed first-steps from here -- https://github.com/sagemathinc/cocalc-examples.   It's also part of cocalc and hal updated it.

@haraldschilly 
I'm not sure if I have to do anything else, or if it just won't be there next time I build an image or what...

**Comment by haraldschilly** [comment]
I looked into it. It will be removed with the next software update.
