### ISSUE TITLE
project/miniterm: make it easier to dismiss

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6680]
When running a command in the project explorer's mini terminal, the output is quite sticky. There should be an "X" to close it, which could be part of the input container (to avoid overwriting the output content). Defocusing doesn't dismiss it as well.

The only way I noticed to get rid of it is via the Esc key or running an empty command.

![Screenshot from 2023-05-02 19-22-48](https://user-images.githubusercontent.com/207405/235739508-84b37d50-5e0f-47d9-afbf-a75fc5da5d9e.png)

**Comment by schrodingersket** [comment]
Do we want this window to go away on defocus? For most modals, I'd think that's the way to go, but I could definitely see it being useful to let this one hang around (since terminal output could be helpful when editing e.g. a Python script in CoCalc).

**Comment by haraldschilly** [comment]
I think, if there is a good reason to keep it around – as you mentioned – then it should stay there until dismissed. It would be annoying if the output is gone, when someone expects it to be still there. (Also, given that there is no history, as there is with the full featured (mini) terminal)

**Comment by haraldschilly** [comment]
I'm closing this ticket as well. Future tweaks should better be in a new one :shrug:
