### ISSUE TITLE
jupyter/nbgrader:  the nbgrader metadata cell ID's should be unique

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6687]
Make an nbgrader autograder tests cell, it gets a random looking ID.

copy/paste that cell and the ID stays the same.

Should the ID be unique? If so, the paste operation has to take care of that. Or even more general, any time a new nbgrader cell appears, the uniqueness of all IDs must be established.

**Comment by williamstein** [comment]
Yes. Perhaps the same sort of code that periodically checks that cell ids are unique could also ensure that nbgrader ids are unique as well.  I agree that this is a bug.

**Comment by williamstein** [comment]
This is still not fixed.

**Comment by williamstein** [comment]
I just looked at the code - you can create dup id's when editing, but when you "Export Student Version" the notebook, it fixes the ids by a call to `this.ensure_grade_ids_are_unique()` in jupyter/nbgrader/actions.ts, and THEN makes the student version. 

So the id's are always ensured to be unique before they are used.
