### ISSUE TITLE
extra characters in md jupyter fenced code block octave output

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#6695]
1. Open a new .md file.
2. Enter the following in the Markdown Code(left) frame, including the triple backticks:
<pre>
```octave
 x = 71;
 x
 ```
</pre>
3. Run the cell by clicking "Run" in the Text (right) frame.
4. Observe the output is `714h`.
5. The number of extraneous characters will change with the length of the variable name and the length of the value assigned.

<img width="935" alt="image" src="https://github.com/sagemathinc/cocalc/assets/528072/b1f20c8c-8b55-431b-9e76-8e76f3896523">

**Comment by haraldschilly** [comment]
looks like https://github.com/Calysto/octave_kernel/issues/221

**Comment by haraldschilly** [comment]
see https://github.com/sagemathinc/cocalc/issues/7227#issuecomment-1932189857
