### ISSUE TITLE
course/nbgrader: frontend performance issue

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6698]
I'm currently running nbgrader for an assignment of ~250 students, where each have one fairly large notebook (10 pairs of question/test cells), in a separate project for grading. The UI is completely unusable. My impression is this causes way too many updates and re-rerenders.

Browser: chrome 114, incognito mode

**Comment by haraldschilly** [comment]
What seems to help is to enter "xxx" in the filter box for students, at the top of the assignment block. Then, no student is displayed in the table.

**Comment by williamstein** [comment]
Evidently the course management UI codebase currently doesn't use virtualization at all for rendering anything.   It should.  I think maybe (?) it used to, using some old approach.  I switched most of cocalc to use virtuoso, but evidently not courses, which means they would indeed likely have the scalability problem you describe here.
