### ISSUE TITLE
course/nbgrader: clean up temp files in separate project

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6701]
I'm running nbgrader for an assignment and told it to grade in a separate project. Once done, that extra project still holds all files.

I don't see a reason why, this should be cleaned up, because that "autograded ipynb" notebook in the course project holds the result.

**Comment by williamstein** [comment]
Seems easy to fix, and certainly we shouldn't litter the filesystem with pointless files.
