### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by 0dminnimda** [sagemathinc/cocalc#6703]
I got an error when visiting cocalc.com/.

Error code: 1020
Ray ID: 7c5e838709810c48
Country: RU
Data center: dme01
IP: 79.139.137.156
Timestamp: 2023-05-12 00:23:34 UTC

I used to access this site, but now doesn't work.

**Comment by williamstein** [comment]
CoCalc is not available in Russia.

**Comment by williamstein** [comment]
Except via https://github.com/sagemathinc/cocalc-docker
