### ISSUE TITLE
maxima jupyter kernel

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6711]
REQUESTED BY: Heinz Bauschke

"I wonder if you guys on cocalc could offer ipython notebook support for maxima:

This example https://nbviewer.org/github/calyau/maxima-tutorial-notebooks/blob/master/notebooks/Maxima%20Tutorial%20-%20Symbolic%20Integration%20-%20First%20Examples.ipynb

looks pretty darn neat. (Taken from https://github.com/calyau/maxima-tutorial-notebooks)
More on this project is available at    https://github.com/robert-dodier/maxima-jupyter
"

Another advantage of adding a maxima notebook is you could the run maxima code from our share server and landing pages without having to sign in or use sage's maxima.eval command...

WORKAROUND: 
Put this at the top of a Sage worksheet and it will then work as a Maxima notebook, as illustrated here: https://cocalc.com/wstein/support/maxima-notebook
 
```
%auto
%default_mode maxima
```

**Comment by haraldschilly** [comment]
I tried to follow the instructions, but quickly ended up with 

```
(%i1) load("load-maxima-jupyter.lisp");               
                                                      
loadfile: failed to load load-maxima-jupyter.lisp     
 -- an error. To debug this try: debugmode(true);     
```

**Comment by williamstein** [comment]
Rarely requested, and usable via sage in a sufficiently supported way.
