### ISSUE TITLE
LaTeX Interface

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#6766]
As we start writing some collaborative grants, I have a bunch of new users building LaTeX documents so am opening an issue to discuss UI issues we discover - especially from new users. *(Let me know if we should move this to a discussion.)*  For now I am just recording issues: we will circle back with suggestions if we have them later.

1. There is not a consistent and obvious "Build" button, especially if one's browser window is small.  For users coming from Overleaf, this might be confusing because they expect the PDF to be out of date.  Related confusions:
   1. The build button appears and disappears depending on which window has focus.
   2. The PDF previewer has no Build button.

   This is generally not an issue when people edit files online, but has been an issue when I edit a style file or similar offline (Emacs + TRAMP over SSH).

2. Said above, but deserves its own point.  The way buttons and functionality is hidden in smaller windows can be very confusing.  Perhaps when buttons are hidden, a "..." or hamburger could appear that could be clicked to give a full menu of options?

**Comment by mforbes** [comment]
Oops: Sorry, not sure how I posted to the docker repo by mistake.

**Comment by williamstein** [comment]
Refresh your browser and let me know what you think.   In particular:

> The way buttons and functionality is hidden in smaller windows can be very confusing. 

This is no longer the case.  Now there is a title for every panel, and the non-focused title (and control buttons in the upper right) are greyed.  All other buttons stay unchanged.    I'm going to close this issue here for now, but please open more.
