### ISSUE TITLE
jupyter: support syntax highlighting for Macaulay2

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6805]
Notebooks with the code language "Macaulay2" (used on CoCalc) or "text/x-macaulay2" (see [sources](https://github.com/rz-c/Macaulay2-Jupyter-Kernel/blob/master/m2_kernel/install.py#L18)) should be properly syntax highlighted.

Here is the kernel's [codemirror mode file](https://github.com/rz-c/Macaulay2-Jupyter-Kernel/blob/master/m2_kernel/assets/m2-mode/macaulay2.js) (MIT licensed)

**Comment by williamstein** [comment]
You did this and the PR is merged. Thanks!
