### ISSUE TITLE
flyout panels: several instances of side panel state inconsistency that leads to friction

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6808]
The state of the "Find" flyout panel is kept in sync with the main Find page.  I like this:

<img width="1146" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/02b346ad-dd20-4924-a475-3a0fdbd05a6b">

It means that when I hit an issue with using the side panel (maybe I just want more elbow room), I can switch to the main find application without any friction at all.

Unfortunately, the very similar Explorer side panel state is only half-way the same:

<img width="1463" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/bfe9d2ee-783d-4636-baf2-08804542dd55">

The directory and checkboxes are sync'd, but the search filter is not.

Regarding New and Log, nothing is synced at all.

None of the other panels matter regarding this issue.

**Comment by haraldschilly** [comment]
hmm, that's not true. did I already fix this? :man_shrugging: 

I'm closing it
