### ISSUE TITLE
flyout panel: make single click behavior for file explorer configurable in account settings (and add a checkbox column)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6809]
I really don't like single click behavior selecting, since it takes me almost twice as long to do the thing I usually do, which is navigate and open files.  See the explanation here: https://github.com/sagemathinc/cocalc/issues/6797.  In short, the probability that I want to select a file and do an action is like 1%, whereas the probability that I want to open a file or directory is maybe 99%, so click to select by default doesn't make any sense.   Operating system file browsers are solving **different problem**, since usually when you use them you're doing file management, and if you need to navigate to or open a file, you're doing that from an application.   

Either we change the behavior, or we make it an option in account settings to make it so single click opens a file or directory, like in the main file explorer (which is what I want).   I'm OK with having two different behaviors.

@haraldschilly

**Comment by williamstein** [comment]
Here's another point -- the flyout file manager was supposed to be inspired by IDE's and VS Code, to make something more familiar for people that use VS Code.   In VS Code's file flyout panel, files and directories are opened by a single click:

<img width="792" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/06ae8ff8-9e35-4965-9f1e-0265d7d5cc9d">

**Comment by haraldschilly** [comment]
I made a PR to address some aspects of this. VSCode is also different, because a single click only half-opens a file (not sure how they call it) and only a double click fully opens it. This avoids opening too many files when just clicking around. Also, file management is behind a context menu, which we don't have.

I wonder, just thinking out loud and long term: a single click is certainly better for navigating directories, but regarding files, a single click could open it in a more lightweight read-only mode, just to view the file. When you start editing, or double click, or whatever, ... it opens in full edit mode. But if not and you click on another file, it reverts to vscode behavior of replacing the semi-opened tab. i.e. the idea is you were "just looking" at the file, not committed to editing.

**Comment by williamstein** [comment]
> half-opens a file (not sure how they call it) and only a double click fully opens it.

The file is 100% fully opened.  It's just that it opens and replaces the currently opened tab.  That's still 100% fully opened.  I don't consider that "half opened". 

> a single click is certainly better for navigating directories, but regarding files, [...]

I just want to be able to click on a file and open it, just like in the main file explorer. That has worked really well for me for years, and also best fits how the web works, where a single click opens a link.    It would also be nice to have a preview mode, but that's a completely different problem.  MacOS solves this by hitting the space bar which shows a preview of the selected file, and I bet other OS's do different things.

Regarding consistency, it's important to record what Jupyter Classic and JupyterLab do:

- Jupyter Classic -- the file browser is exactly like our main file explorer, with a single click opening things.
- JupyterLab - the file browser is exactly like the new flyout file explorer you wrote, with a single click selecting, and a second click needed to open a directory or file.

In fact, in retrospect, I have always been annoyed by JupyterLab being that way.  Yes, it was obviously copying what local operating systems typically do.  However, I think it's not the best thing to do for a web application.    The fact that JupyterLab and OS's do work this way though strongly suggests not to  remove what you've implemented.  That's why this ticket is about providing an option to change the behavior, since no matter what longterm we need to have the behavior be consistent between the main explorer and the flyout panel, and I'm not going to waste my time clicking hundreds of times more a day for no good reason.

**Comment by williamstein** [comment]
OK, what you did in your latest PR seems pretty clever and best of both worlds.  It reminds me of how selection works in AirTable...

**Comment by williamstein** [comment]
fixed
