### ISSUE TITLE
flyout panels: somehow the latest changes broke the file explorer breadcrumb state

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6810]
1. Navigate to a directory four levels deep (say -- just to be concrete):

<img width="1219" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/370d4f33-eaa8-41c0-806e-77e7972ea9fb">

2. Click on the world "cocalc" in this case:

<img width="1124" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/9e257a8e-1af4-4394-a3e3-7a223dcc96cd">

It should be the case that cocalc/src/packages/frontend are all visible still, but with "src/packages/frontend" in grey. Instead only "cocalc/src" is visible.  My guess is somehow the recent flyout panels code results in something happening twice (?) and the breadcrumb state gets discarded.    I just noticed this today, but I'm not 100% sure this was caused in the most recent update, or if it was an older one.

**Comment by haraldschilly** [comment]
I'll look into this. I don't remember having done a conscious change with the breadcrumb history logic.

**Comment by williamstein** [comment]
I don't know for sure that flyouts broke this or how recent the bug was introduced. However, I haven't done much frontend code in weeks now so it's probably flyouts.
