### ISSUE TITLE
Project invite token links don't work without account.

### ISSUE THREAD

**Issue by ilyasdc** [sagemathinc/cocalc#6816]
Hello, thank you building Cocalc, I'm still starting to use it but I faced the following problem, I created an invite token, according to the documentation: 

> Using a Project Invitation Link[](https://doc.cocalc.com/howto/project-invitation-tokens.html#using-a-project-invitation-link)
> Anyone who clicks on the project invitation link will be added to the project as a collaborator. Persons who do not have an account will be signed in as anonymous users. They have the option of creating an account or continuing anonymously.

Even the web interface states that: 
> 
When they click the link, they will get added to this project (_this will even work without an account!_). You can also share the token above, which they can enter on the top right side of the projects page.

However I created a token, copied the link and when I attempt to open it in a private window, it asks for sign-in/sign-up

**Comment by haraldschilly** [comment]
This is clearly a bug. Those references to "anonymous users" and "without account" should not show up in the UI if anonymous accounts are disabled (which it is). Thx for pointing this out!

**Comment by williamstein** [comment]
The cocalc part is fixed.  The docs part isn't. That's now https://github.com/sagemathinc/cocalc-doc/issues/51
