### ISSUE TITLE
state of file explorer flyout panel filter gets badly messed up

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6832]
For me the state of the filter in the file explorer gets all messed up / stuck.  This is new with the latest PR.  I made a screencast illustrating the problem:

https://github.com/sagemathinc/cocalc/assets/1276278/dd205570-ef3d-4a98-b27a-596343422641

I don't know for sure how to reproduce it and it goes away for a bit if I refresh my browser.   @haraldschilly - Maybe if you think about it for a minute you might realize why it could be broken suddenly?

**Comment by haraldschilly** [comment]
I'll look into this

**Comment by williamstein** [comment]
Just to confirm -- I've hit this bug dozens of times in the last two days.  It's definitely new and makes the files flyout panel unusable for me.  It's also not a rare fluke.
