### ISSUE TITLE
our nextjs app: dev mode slow

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6839]
Basically, when developing the cocalc nextjs application, every time you load a new page it takes a **LONG TIME**.    This is incredibly annoying and frustrating, especially in comparison to our main webpack frontend single page app, where everything is comparatively massively faster.     The next dev experience is even almost unusably painful when I run all development locally on my M1 max laptop with a very fast SSD and tons of RAM.   This is of course a general problem that impacts other users of nextjs:

https://github.com/vercel/next.js/issues/48748

I don't know if this is a fundamental problem for large applications that is due to the architecture of nextjs, or if it is something that will eventually be fixed.  This was always a problem for us, even from the beginning of using nextjs when our use was pretty minimal.  It feels like it has got worse over time though.  Perhaps changes in antd are an issue (they are mentioned in the above linked thread).

The point of this issue is just to record my frustration with developing with nextjs.  It's so bad that if at all possible, I prefer to develop features as part of our "old fashioned" webpack single page app, if for no other reason than having a nice dev experience.  The one thing I really do like about nextjs is how the api routing works.       If we can't find a way to make dev with nextjs faster, I will likely want to use nextjs as little as possible, e.g., use it for sign in/sign up/share server/landing pages/news/support, and nothing else.

Am I just doing something wrong?

See also https://www.reddit.com/r/nextjs/comments/swciuj/next_dev_is_slow/

**Comment by williamstein** [comment]
Amusing anecdote.  I was listening to [this podcast](https://topenddevs.com/podcasts/javascript-jabber/episodes/bun-js-with-jarred-sumner-jsj-584) with Jarred Sumner about why he started Bun.js.  If you search the transcript for "nextJS" you'll see that his entire motivation for starting bun was because:

> "I was really frustrated with just how slow everything in front end is. That the iteration cycle
> time is just really long and that it's long enough that you check Hacker News while waiting for
> stuff to rebuild. "

He is talking about nextjs here.

**Comment by williamstein** [comment]
I just realized that a much more significant recent issue is that **hot module reloading** does not work at all anymore for our nextjs app for me, in multiple separate dev environments I have.  I don't know what broke it -- possibly a change to chrome?   The console log just does this:

<img width="1392" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/053d6d7c-cb0c-4239-b5e2-f790430a0705">

We haven't updated anything relevant in a while, but this suddenly broke maybe 2 weeks ago, so I wouldn't be surprised if it is some sort of change to something involving security.  But really I don't have a clue.  This makes working with nextjs (compared to our old fashioned webpack SPA) even more painful.

**Comment by williamstein** [comment]
@haraldschilly I'm curious if hmr with nextjs is working for you, wherever you do development?

**Comment by haraldschilly** [comment]
Well, I have no idea, for me it was always kind of the same. I see those invalid frame header errors when doing dev locally as well. Couldn't be chrome related, since this happens in Firefox as well. Are we using the latest version? Maybe it's fixed with an update?

Working on the frontend is fine, though. Sometimes the log says something about not being able to reload, but refreshing the page fixes it. What I also do is to clean up locally cached files in `/tmp` (nextjs and webpack) if the directory grows too large.

**Comment by haraldschilly** [comment]
My basic understanding is that the code to compile is too much. Maybe there are modules being loaded, accidentally, which could be circumvented to speed this up. I know somewhere we have this "bundle analyzer" for static, but does this also work for next.js? I found this: https://github.com/vercel/next.js/tree/canary/packages/next-bundle-analyzer ... maybe worth to look into

**Comment by williamstein** [comment]
> Well, I have no idea, for me it was always kind of the same.

Meaning?  It always was really slow each time you load a new page not previously visited in dev mode?   I think it was always bad, but now it is even worse.

> Are we using the latest version? Maybe it's fixed with an update?

I'm sure we're not using the latest version.

> Working on the frontend is fine, though.

So here you're not talking about nextjs at all????  Or you are?  I don't understand what "the frontend" means.

> My basic understanding is that the code to compile is too much.

I'm sure it would be fast if cocalc was tiny, but it's huge.  The basic problem is the core design of nextjs is to have a different entry point for each top level URL.  Thus basically webpack ends up getting run separately whenever you visit a new top level URL... and this takes a while.  In contrast, our frontend app just has essentially one entry point, so once that is built you're done, and new pages just involve loading new chunks.  It's a totally different approach.   

If there is no solution to this problem, I'll likely want to reduce our use of nextjs longterm to just things that really, really clearly benefit from it.

**Comment by timneutkens** [comment]
https://github.com/sagemathinc/cocalc/blob/c6fdbb2ce02d77bab11740aad46cbf25107085b8/src/packages/next/package.json#L78

Would recommend upgrading, you're on a much older version of Next.js, many patches and performance improvements have been landed.

If at that point you're still running into issues, we have provided a way for you to share the trace and cpu profile for the application you're working on in issue: https://github.com/vercel/next.js/issues/48748#issue-1680013792.

**Comment by williamstein** [comment]
> Would recommend upgrading, you're on a much older version of Next.js, many patches and performance improvements have been landed.

We just upgraded to the latest version.  It does feel better :-)

**Comment by timneutkens** [comment]
@williamstein glad to hear that, could you share the cpu profile / trace for the application? That will help us investigate further.

**Comment by timneutkens** [comment]
Not sure what you're trying to say with this message.

**Comment by williamstein** [comment]
I'm closing this.

**Comment by timneutkens** [comment]
This is a bizarre interaction.

**Comment by williamstein** [comment]
Just to be clear -- I'm closing this issue that I opened up saying that our nextjs app is slow.   
The point is that by upgrading, and so on, we no longer consider this a major issue.  We're happily using nextjs :-)

Does that make sense?

**Comment by timneutkens** [comment]
Thanks for confirming @williamstein, that's great to hear 🙏
