### ISSUE TITLE
refine configuration of course restrictions to be date-based

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6852]
> "It would be nice to be able to set dates to enable/disable ChatGPT features, rather having to turn them on or off manually. For example, we're thinking that we want XXX disabled entirely for the first 5 or 6 weeks while students are just learning to code, and then we would enable YYY for the remaining 5 or 6 weeks."

**Comment by novoselt** [comment]
The disabling interface is as simple and straightforward as can be now. Adding more controls to each element, making sure things happen on time, and dealing with resulting confusion when things stop/start working "for no reason" does not sound like a good idea to me and this does not seem to  be a popular request (unlike collecting assignments on a certain date).
