### ISSUE TITLE
option to persist pay-as-you-go upgrades of a project via checkbox

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6856]
> "When my project is restarted, it always starts in "free" mode with no internet access. I can upgrade the project using pay-as-you-go and then work on my project. After stopping and starting, the project reverts back to free mode. How can the upgrade be persistent? I can't find a checkbox or option to do this."

**Comment by novoselt** [comment]
I actually would expect persistent setting to be the default one, although giving a very visible option to make it a one-time purchase would be great.

**Comment by williamstein** [comment]
> I actually would expect persistent setting to be the default one, although giving a very visible option to make it a one-time purchase would be great.

Sure, I agree. The checkbox can easily be on by default.

**Comment by williamstein** [comment]
Now implemented.
