### ISSUE TITLE
Change Username for public links to something else to avoid confusing errors

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6868]
When I click on "Account" and focus on "First name" I get a banner along the top
![image](https://github.com/sagemathinc/cocalc/assets/1993227/69ea8f3c-cc93-4a57-9d0c-e1dfae5cadb2)
however the field content as far as I can tell is "Andrey", so definitely within those standards.

**Comment by novoselt** [comment]
Actually I was wrong - apparently the complaint was about my USERname, which was set to my email with "@". Then the problems are 1) why my email ended up in the username field if that is not an acceptable value and 2) the error message mentions "name" twice and "username" once, I think is should be "username" in all cases to avoid confusion with first/last names.

**Comment by novoselt** [comment]
One more point: "Username" tends to be associated with what you enter to login into the system. I've checked that the sign in page asks for "Email address", so there should be no confusion, but when I was leaving the settings page where I changed the "Username", LastPass has offered to update my info for CoCalc and if I agreed to it, would probably use it the next time I tried to sign in.

**Comment by novoselt** [comment]
Not completely sure, but perhaps the answer to how my email ended up in Username is LastPass - it tried to autofill a blank form field with the username for the site. It does not do it now with a manually set username, but shows its icon on the field. I suspect it may be a relatively common issue. Perhaps instead of "Username" it can be "Handle" or "Vanity URL" or something like that? Both for the user and in the code to avoid confusing password managers.

**Comment by novoselt** [comment]
It still happens - the "username" field gets auto-filled with the "login username".

**Comment by novoselt** [comment]
I keep hitting this issue every time I am going into Account with LastPass enabled. Given the purpose of this "username" I very much think that it has to be named differently:
![image](https://github.com/user-attachments/assets/2737375a-bb94-4ff3-b441-39f3d9a1057d)

Perhaps "Public handle:" will be more descriptive/less ambiguous and interfere less with password managers?

**Comment by haraldschilly** [comment]
Is there a way to mark fields as being ignored by lastpass and similar?  My thoughts

1. I don't want to change our code just because of a problem with a 3rd party tool
2. The label is probably irrelevant, what counts is the underlying html of the field itself
3. Even if we change the label based on a guess, we don't know if this fixes this for good or just drags the problem around – or maybe it then breaks this in a similar way with another tool of that kind

Ad my original intention I [found this](https://support.lastpass.com/s/document-item?language=en_US&bundleId=lastpass&topicId=LastPass/c_lp_prevent_fields_from_being_filled_automatically.html&_LANG=enus)
   > attribute `'data-lpignore'=true`

**Comment by novoselt** [comment]
I agree with not changing the code because of 3rd party tools in general, but password managers are particularly important and "Username" to me unambiguously means "the name that I use to login into the system", which is not the case at all here!

**Comment by williamstein** [comment]
We should do what Harald says no matter what, so let's do that.  Changing the name could be another ticket or discussion for later.  I'll do this right now (before going to some sand dunes!).

**Comment by williamstein** [comment]
@novoselt do you have similar issues at https://cocalc.com/config/account/name ?

**Comment by novoselt** [comment]
> @novoselt do you have similar issues at https://cocalc.com/config/account/name ?

No!
