### ISSUE TITLE
"Show All Frames" and "TimeTravel" button flashes with every keystroke in dark mode

### ISSUE THREAD

**Issue by p07707** [sagemathinc/cocalc#6880]
When a text editor window is fully expanded via the "Show only this frame" button, every keystroke in the editor causes the "Show all frames" button to flash. This happens only in the "dark mode"; "light mode" functions properly.  But in the dark mode it is especially distracting and annoying,  This happens in both up-to-date Chrome and Safari browsers on Mac OS and Chrome OS.

**Comment by williamstein** [comment]
I didn't know about this bug -- thanks for reporting it!

**Comment by williamstein** [comment]
I looked into this for a while, and unfortunately *for now* I'm stumped.

> with every keystroke

It's actually not on every keystroke, but when you type and then pause for about a second. 

It's also worse -- if I split the screen vertically in two when editing a text file and type, then pause, other buttons "flicker" for a moment.  What's happening, of course, is that darkreader is styling them again fro some reason, which suggests they are maybe being re-rendered and their darkreader style is going away for a moment.

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/cocalc/issues/5591 which means we can't upgrade darkreader ever, unless we stop supporting MathJax V2 (at least).

**Comment by haraldschilly** [comment]
This is reported to happen for the "TimeTravel" button as well.

**Comment by williamstein** [comment]
I just had an obvious idea how to fix this, which is that it is easy to tell whether or not dark mode is enabled, and when it is just DON'T use these colors (like for TimeTravel) at all when rendering in dark mode.  The colors are not at all critical to functionality of cocalc, and having no colors would be way better than flickering.
