### ISSUE TITLE
Notebook scroll or focus issue for cells with long output

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6889]
Create and execute a notebook with a cell that has short output and below it a cell with long output like
![image](https://github.com/sagemathinc/cocalc/assets/1993227/c58f1432-2db3-4dd3-861d-b12597f02a2f)
Go back to the first cell, press Shift-Enter to execute it - it is executed and the second cell is selected, but in such a way that the bottom of its long output is visible:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/7ad29bc5-8660-43bb-8608-48b9b9721f43)
What I would much rather see is the output of the first cell and the code of the second cell.

Perhaps a suitable behaviour is not to scroll anything if the border between the first output and the second code is still within the window and if not - make this border be in the middle of the window.

This is in Chrome on Windows 11.

Probably related: sometimes when the focus is on a cell with big output and I use arrow keys to move between cells, it is possible for the focus to go completely away from the screen. I can't reliably reproduce it and come up with a test example, but it seems that whenever there is a change of focus, definitely so for any keyboard operations, there has to be a check that the focused cell is visible on the screen at least partially. If not - scroll the window to the code. If yes - apply some sensible logic to see if any adjustment is necessary.

**Comment by williamstein** [comment]
> What I would much rather see 

Please try doing this test in both Jupyter Classic and JupyterLab and report on the results.  In CoCalc, it's usually only a bug if the behavior is different than Jupyter Classic/Lab...

**Comment by williamstein** [comment]
By the way, control+enter evaluates a cell without moving the cursor.

**Comment by novoselt** [comment]
JupyterLab: does not scroll the window at all after executing the first cell and selecting the second on Shift+Enter.

Jupyter Notebook: scrolls a little, the code of the first cell goes away, but its output is still visible.

I prefer JupyterLab behaviour and it is in agreement with my proposal ;-)

As far as Ctrl+Enter, it has a similar problem: no scrolling after executing the first cell, but when I press arrow down to select the second cell, it scrolls to the bottom of its output, even though the whole code was already visible and I'd much rather continue seeing it rather than old output which may change on re-execution.

**Comment by williamstein** [comment]
Thanks. I've changed this to a bug and removed "unclear".  Generally, it's better for us to match JupyterLab, since Jupyter classic version 7.x literally *is* JupyterLab these days...
