### ISSUE TITLE
Create New Vouchers goes to licenses

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6891]
On https://cocalc.com/vouchers clicking "Create new vouchers" goes to https://cocalc.com/store/site-license while it should be https://cocalc.com/store/vouchers

**Comment by williamstein** [comment]
This made sense when the only way to make a voucher was to add a license to your cart first.  Now that we have cash vouchers (which are probably superior in every way?), the link should change as you mention.
