### ISSUE TITLE
Indicate redeemed vouchers in the listing

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6893]
On https://cocalc.com/vouchers/created it would be nice to see which vouchers got redeemed. It feels that "Redeemed" belongs to Status column, which is used for other purposes now. "Expired" is another status that would be nice to see easily, perhaps.

**Comment by williamstein** [comment]
Note that each "voucher" has potentially thousands of codes, so for https://cocalc.com/vouchers/created maybe it shows a count of how many codes for a given voucher were redeemed (?).

**Comment by williamstein** [comment]
This is I think the same as #7590
