### ISSUE TITLE
Using the edit license panel inside a popover is broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6901]
1. View a license in the purchase log
2. Click "Edit license" from there
3. Key parts of the dialog are not visible on the screen.

Doing edit license in the full licensing page works fine since no floating popovers are involved.

**Comment by novoselt** [comment]
Still there. Hover over license edit shows details with a link to managing the license. I think hovering over a license purchase should behave in exactly the same way, i.e. instead of fixing editing from hover, eliminate it completely.

**Comment by williamstein** [comment]
Unclear because too different ideas for what to do.

**Comment by novoselt** [comment]
Remove the edit button from the popover! No side effects and presumably easy?..
