### ISSUE TITLE
license subscription: always expires?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6913]
I noticed that a license subscription says "will expire in X days". I assume this has been changed with the recent payment upgrade. For me, the wording is a bit confusing.

I suggest this should at least say "might expire in X days" and the text in the expanded license description: 

> Will expire X days from now depending on subscription status

should be

> Might expire X days from now depending on subscription status

At least, that's how I understand this. If this is different, the text should change a bit more to clarify what's going on.

**Comment by williamstein** [comment]
You can change the Will to Might if you want.

The right thing to do is to get the subscription information and write a better message there, but that's not implemented.

- if the subscription is active, say so.
- if the subscription canceled, say "Will expire X days from now unless you resume the subscription" if it is your subscription, or just ""Will expire X days from now" if it is not your subscription?
- Etc.

The main problem is that some people have dozens (hundreds?) of licenses, so you really have to be careful in getting additional information about subscription status from the backend...

**Comment by williamstein** [comment]
Instead of "Expires ..." it could say "Paid through ...", which is (a) less alarming, and (b) actually true.  Regarding (b), if the user renews the license or subscription, then it does NOT expire, so saying it will isn't correct.

**Comment by williamstein** [comment]
I only changed wording in one place in that commit, and (much) more is required.
