### ISSUE TITLE
Discrepancy in picked time for a license

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6917]
![image](https://github.com/sagemathinc/cocalc/assets/1993227/62d74ea0-7d74-4af2-b9ef-5933a7215893)
but the license description has 12:02AM:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/9e13436c-c848-40a3-be16-69b29cc26f22)
and it also has days with way too many decimals instead of days hours:minutes.

**Comment by williamstein** [comment]
Dup of #7571
