### ISSUE TITLE
Make the credit balance easily visible

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6919]
Perhaps it should not be on the screen all the time, but whenever the user is in the store, especially while configuring licenses, it would be very helpful to see the current balance. Maybe in some box in the corner.

**Comment by williamstein** [comment]
@schrodingersket this could be ideal for you -- not a bug fix, but fun to add.

**Comment by williamstein** [comment]
Scope -- this issue is just adding it in the https://cocalc.com/store
