### ISSUE TITLE
rewrite full SageMathCloud production site to run entirely in Kubernetes

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#692]
- [x] hub
- [x] database -- code done, but not switched to using it
- [x] haproxy
- [x] nginx (smc-webapp-static)
- [ ] projects (mostly Harald working on this)
- [ ] storage (mostly William working on this)

**Comment by johnjeng** [comment]
Done?

**Comment by williamstein** [comment]
Why yes it is done!!
