### ISSUE TITLE
Buy a license opens a new window but should not

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6932]
Clicking on "Buy a license..." button on https://cocalc.com/settings/licenses opens a new window and in general clicking links in the store and subscription/license management can create a whole lot of new windows without any need - using the same one usually makes more sense.

**Comment by williamstein** [comment]
I do not agree in this case.   

> and in general clicking links in the store and subscription/license management can create a whole lot of new windows without any need - using the same one usually makes more sense.

You could bring that up separately with specific details.
