### ISSUE TITLE
Allow adding/removal of a subscription to a license

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6935]
It is feasible that somebody with a license may want to switch it to being a subscription and when a license has been used already it may be a nuisance to replace it with a different one.

Also, since a subscription really is just a license with automatic renewal attached to it, I think the "Subscriptions" tab should be eliminated entirely. Those licenses are already listed on the "Licenses" tab, so any needed functionality should just be accessible from there.

**Comment by williamstein** [comment]
I agree and I think this would be fairly easy to implement, because I think the way a subscription for a license is made (in the code) when you buy one is (1) make the license, (2) make the subscription associated to it.

**Comment by williamstein** [comment]
Here's the exact code right now in the backend that purchases a subscription:

https://github.com/sagemathinc/cocalc/blob/master/src/packages/server/purchases/purchase-shopping-cart-item.ts#L125

To implement the backend part of turning a license into a subscription would involve (1) making some checks, e.g., that there isn't already a subscription, then (2) calling that same function linked to above.  That's probably about it.

**Comment by novoselt** [comment]
I feel the logic should be more complicated.

We should allow easy transition in this direction:
- Term License -> Monthly subscription -> Annual subscription

We should also store current percentage discount in the license record. When somebody tries to go the other way:
- Annual subscription -> Monthly subscription -> Term License

we should recalculate the cost of the past period, based only on percentage discounts, not taking into account any possible price changes. This increase in cost should be deducted from the potential refund, but the refund should not become negative as the result.

**EXAMPLE 1:** An annual subscription for $120/year is converted to a monthly one after 3 months. Cost of 3 months: $30. Refund: $90. Difference in discounts: 15% -> 10%. Increased cost: $30 / 0.85 * 0.9 = $31.76. So actual refund: $88.24.

**EXAMPLE 2:** An annual subscription for $120/year is converted to a term license after 11 months. Cost of 11 months: $110. Refund: $10. Difference in discounts: 15% -> 0%. Increased cost: $110 / 0.85 = $129.41. Actual refund: $0.

In the last case it kind of makes no sense to cancel the subscription and it would be nice to tell this to the user. But I think it is fair to refuse giving back a discount that was given on the assumption of sticking to the plan for the whole year. It is basically the model of "Pay monthly price for 10 months and then get the last 2 months for free, but you cannot take these free months as cash."

**Comment by williamstein** [comment]
I think this is too complicated to support and I'm closing this.  If somebody wants to switch from a non-sub license to a sub, just make a new subscription with the exact same parameters.  You can cancel a license at any time for a 100% refund, etc.,   

Also, given that we give a 10% or 15% discount with subscriptions, attaching a subscription to an existing license also introduces a bunch of headaches and potential bugs since the rate changes.
