### ISSUE TITLE
when resuming a subscription, if there isn't sufficient balance on the account, display the modal for adding credit to the account instead of an error message

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6942]
This is what happens when resuming a subscription if you have no credit:

<img width="376" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/b36aa636-c912-422a-bfb4-a2548a5bc3b0">

Instead a payment modal should pop up, etc. 

Alternatively, if you have automatic payments setup, maybe (?) you should just get billed, since you do clearly understand the amount.

**Comment by novoselt** [comment]
Just getting billed would make more sense to me!

**Comment by williamstein** [comment]
> Just getting billed would make more sense to me!

Except, if automatic payment isn't setup.  There will be many users (perhaps most at some point) that don't have automatic payments.  Also, even with automatic payments, it would be good to display a confirmation dialog.

**Comment by williamstein** [comment]
Now done.
