### ISSUE TITLE
the sshfs filesystem configuration box defocuses constantly, making it very difficult to use

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6946]
It's impossible to type in the sshfs configuration section of the flyout panels.  Probably similar issues with all the filesystems.

~~WORKAROUND: The non-flyout settings page works fine.~~

WORKAROUND: type very slowly and be very annoyed.  You get constantly defocused, but if you persist you can probably type something in.

<img width="698" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/a431b80d-7e30-4118-b258-a11c580417cb">

**Comment by haraldschilly** [comment]
What's interesting, on first try I wasn't able to replicate this at all. Then, after closing and reopening the panel with a different file opened to the right, I was. I can try to look into this, but I fear I have no idea how to fix this.

**Comment by williamstein** [comment]
> I fear I have no idea how to fix this.

I'll try at some point.  This symptom is usually caused by the component being recreated, which often happens when you define a react component by a function that is nested.  It's an "antipattern" that entered our code in rewriting from coffeescript and class components to functional components.  Basically this pattern below is VERY bad:

```tsx
function Foo({...}) {
    function Bar({...}) {
    ...
    }

   return ... <Bar .../>

}
```
It's tempting to write code like the above so that Bar can depend on the scope of parms to Foo, which you're
used to doing from class components.

The problem is every single time Foo renders, Bar is an entirely new react component.

Instead, move the definition of Bar out

```tsx
function Foo({...}) {
   return ... <Bar .../>

}

function Bar({...}) {
  ...
  }
```

But then you also have to clearly specify how Bar depended on the explicit scope from Foo.  This is usually a good thing for our code though.

**Comment by haraldschilly** [comment]
Yes, I see, I'll check if I can spot this.
