### ISSUE TITLE
show command doesn't like \ switch in Sagemath or Jupyter

### ISSUE THREAD

**Issue by pchemrules** [sagemathinc/cocalc#6953]
In Sagemath if you type show("$\int^a_b\psi(x)^2dx$"), you get "DeprecationWarning: invalid escape sequence '\i'" and then gives correct output.
If you type show("$\\int^a_b\\psi(x)^2dx$"), you get correct output without warning.

If you type either of those commands in Jupyter Notebook, you get 
<>:1: DeprecationWarning: invalid escape sequence '\i'
<>:1: DeprecationWarning: invalid escape sequence '\i'
/tmp/ipykernel_2788/2002252033.py:1: DeprecationWarning: invalid escape sequence '\i'
  show("$\int^a_b\psi(x)^2dx$")
$\displaystyle \verb|$\int^a_b\psi(x)^2dx
$\displaystyle \verb|$\int^a_b\psi(x)^2dx

**Comment by williamstein** [comment]
What if you do show(r”\int…

Note the r above.

-- William Stein

**Comment by williamstein** [comment]
Hi,

You should use a raw python string, e.g.,  `show(r"$\int^a_b\psi(x)^2dx$")`

https://docs.python.org/3/library/stdtypes.html#textseq
