### ISSUE TITLE
exiting a terminal causes 100% cpu usage and breaks restarting that terminal with node >= v18.18 but <20.11.1 and <21.6.2  (!)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6963]
With Node.js v18.18.0 on cocalc-docker (and also cocalc.com) the following steps result in the nodejs hub process getting stuck at 100% making the project almost unusably slow.  The following is 100% reproducible on cocalc-docker.  It's I think even worse on cocalc.com. 

1. Open a terminal in a CoCalc project and split it in half using the split button.
2. Run the `top` command in one frame.
3. Hit ctrl\+d to exit the other frame.
4. The first time, this works fine.  Now restart the project, open the same terminal and do 1-3 again. Every single time, the  cpu gets pegged at 100%.
5. Every time the terminal attempts to start again it fails immediately with "signal 1" (and exit code 0).

Switch to v18.17.1 and the problem goes away entirely.  

I noticed  a few things when working on this. 

- This is the upstream bug https://github.com/microsoft/node-pty/issues/630 !
- Here is what is happening in that 100% cpu loop, according to strace:
```
io_uring_enter(19, 1, 1, IORING_ENTER_GETEVENTS, NULL, 0) = 1
epoll_pwait(17, [{events=EPOLLHUP, data={u32=38, u64=38}}, {events=EPOLLIN, data={u32=40, u64=40}}], 1024, 0, NULL, 8) = 2
read(40, "read(40, \"read(40, \\\"read(40, \\\\"..., 65536) = 272
writev(36, [{iov_base="\201~\1m", iov_len=4}, {iov_base="[0,\"yw5so45vo29\",\"terminal:.2023"..., iov_len=365}], 2) = 369
```
- I have no clue if [this post](https://twitter.com/jarredsumner/status/1610925532945977344?lang=en) by Jared Sumner about something similar is relevant.
- Note that v18.18.0 is the next release after 18.17.1, and 18.18.0 was released on Sep 16, 2023.
- I haven't yet reproduced this bug outside of the complicated environment of "running a cocalc project" (so a daemon, etc.).
- It's not clear whether this is a bug in node-pty (perhaps the C extension code) or in nodejs itself.

WORKAROUND: Use node v18.17.1.

**Comment by williamstein** [comment]
NOTE: I've now pinned version 18.17.1 of nodejs everywhere, e.g., in the latest cocalc-docker image and on cocalc.com, so this issue is mitigated for now.

**Comment by louislam** [comment]
Thanks for the workaround, it saved my time. I also added your name in the release note, because I literally couldn't solve it without seeing your info here.

For your information, I was experiencing this on Node.js 20.10.0.

Instead of the `top` command, my project runs `docker compose start/restart/down` commands. 

Not sure if it is related, but they are also "interactive terminals". I don't know the exact name of this.

And also it doesn't seem to happen on Windows' Node.js 20.10.0.

**Comment by williamstein** [comment]
As explained upstream, doing 
```
UV_USE_IO_URING=0
```
definitely fixes this, and is currently the default with new versions of nodejs.
