### ISSUE TITLE
Schedule future license edits

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6975]
It may be involved to implement and maintain, but it would be handy to schedule license edits in advance, e.g. when a course starts and ends on a certain date and it is desirable to increase/decrease the number of running projects on a license which is used for multiple courses.

Of course, being able to get separate licenses that start and end with the courses accomplishes pretty much the same thing. So, maybe it is better not to implement this?..

**Comment by williamstein** [comment]
For what it is worth, actually implementing this is probably pretty easy.  I would just add one field to the database that contains the schedule, and a maintenance task that periodically runs and loops over licenses with a maintenance task and handles any tasks that need to get done, and probably also emails the license owner to tell them what happened.

**Comment by williamstein** [comment]
A big can of worms though, due to having to create an HTML editor for schedules.  It's unlikely I'll personally ever implement this.

**Comment by novoselt** [comment]
I have a feeling that it won't be used very often thus may have bugs that will be discovered on large cases only. So I take back the request to have this. The most important "schedule" is the end date of the license. The "start" makes it even better. That's enough.
