### ISSUE TITLE
Expired subscription licenses are not recognized as expired

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6990]
When one looks at their licenses at https://cocalc.com/settings/licenses or wants to apply a license to a course file, there are checkboxes to show expired licenses, which are off by default. However, when there are expired subscription licenses on the account, they are still listed.

**Comment by williamstein** [comment]
This is intentional.   Only the *OLD* expired licenses are omitted.  I've clarified the label.

**Comment by williamstein** [comment]
(this has nothing to do with being a subscription or not)
