### ISSUE TITLE
issue displaying more than 100 files in a directory

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6995]
If a directory contains more than 100 files (including hidden files starting with .), in some cases only the first 100 are displayed in the graphical file browser.

The listings table and backend have 100 as a parameter in src/packages/util/db-schema/listings.ts, and they also fill in the number of missing files in the listings table, when showing the listing.  In cases when missing > 0, the frontend is supposed to show the known files, then show a loading spinner and directly compute the complete listing and display it.  This worked correctly for years, but something recently broke it, either in the project or the frontend.

WORKAROUNDS:
- have less than 100 files in a directory (obviously)
- use the terminal to view and open files -- you can use "ls" to show files and "open filename" to open a file.

**Comment by williamstein** [comment]
This bug was introduced by @haraldschilly in 4ad5584f4ef two weeks ago.  In particular, these lines in packages/frontend/project/directory-listing.ts that don't make any sense (to me)
```
  if (opts.trigger_start_project === false) {
    return undefined;
  }
```
cause the crash.

I'll try to sort this out now.

**Comment by haraldschilly** [comment]
when `trigger_start_project` is set to true, the project must not start. otherwise showing the directory listing always triggered a project start.

**Comment by williamstein** [comment]
I don't think the one change I made here 

https://github.com/sagemathinc/cocalc/commit/18d4a50a77bd01c6576a4efb3d94c9859a8c63e3#diff-57c4e9887811fbf4b0951ff07748737ebdf6b3059fad54bdcab5f0966e3f6143L42

impacts the behavior of anything when trigger_start_project is true.

It just changes what happens when it is false.

**Comment by williamstein** [comment]
The real problem was returning undefined, since the caller of that code assumed it returned an object of shape {error:?, files:?}....

**Comment by williamstein** [comment]
While in the neighborhood I also made the message to the user more informative, telling them if some files are missing from the cached listing, since that info is knowable.
