### ISSUE TITLE
python 3.10: structural pattern matching syntax highlighting

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6998]
Essentially, highlight `case` and `match` keywords in a code like the following. currently, those words are treated like a variable (a default syntax styling).

```{python}
match x:
   case "foo":
       return 1
```

This is probably easy by adjusting `frontend/codemirror/mode/python.js`

**Comment by williamstein** [comment]
This is supported in the current version from codemirror 5: https://codemirror.net/5/mode/python/index.html

**Comment by williamstein** [comment]
fixed by https://github.com/sagemathinc/cocalc/pull/7032
