### ISSUE TITLE
Email all collaborators on a project

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#700]
This would be useful for a large project, e.g., to notify everyone that you made some changes. However, it might be prudent to allow the user to disable such emails, either on a project-by-project basis or globally (but allow them by default).

**Comment by williamstein** [comment]
This can't be allowed by default -- it would just make SMC a trivial spam machine.

**Comment by kedlaya** [comment]
Right, adding someone as a collaborator doesn't require their consent, so any setting involving email has to be "opt-in" (and local to the project).

Alternative suggestion: have an option (local to the project, disabled by default) to get email digests of chat sessions in that project (e.g., an email in case there has been any chat activity in the last 24 hours).

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/smc/issues/304

**Comment by novoselt** [comment]
This would be supported well with `@mentions` to everyone in chats.
