### ISSUE TITLE
Enlarge column in Handouts view

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7008]
Request from user: "it would be nice to be able to enlarge the first column in the Handouts view, because when we use long paths we can't see what they are without opening them. It's a small detail but one of these things that makes an interface more friendly, and there is plenty of empty space to the right of the page."

Discussion:
- we have drag-n-drop resizable columns in the admin CRM, so maybe that code could be copied over to the course management tables?

**Comment by novoselt** [comment]
Apparently Assignments do not have such a problem and #1152 is about unifying their interfaces.
