### ISSUE TITLE
Make Stripe invoices more informative

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7011]
Since people may need them for reimbursement etc. At the moment the statement shows "Credit Account to Complete Store Purchase" - can we list the actual items that were in the cart, ideally with separate prices?

**Comment by novoselt** [comment]
Relevant code: https://github.com/sagemathinc/cocalc/tree/master/src/packages/server/purchases/statements

There are also invoices for monthly charges that do not go through the card - those should be informative as well, not just state the total amount paid.

**Comment by williamstein** [comment]
Maybe do https://github.com/sagemathinc/cocalc/issues/7012 while you're in the neighborhood.

**Comment by schrodingersket** [comment]
Are we good to close this issue out, or is there more that needs to be done on this?

**Comment by williamstein** [comment]
I'm closing this.  I think there will always be more to add, but that can be a new ticket.
