### ISSUE TITLE
If DEBUG + DEBUG_FILE   is set for Hub in multi-user mode with sudo, Hub cannot start projects

### ISSUE THREAD

**Issue by belonesox** [sagemathinc/cocalc#7014]
When I try to debug cocalc, I set something like

```
  DEBUG=cocalc:*,cocalc:silly:*
  DEBUG_FILE=/var/log/colalc/cocalc-debugging.log
```
running Hub as sudo, with `--mode=multi-user`.

In such case it cannot start projects!

With 
* only DEBUG → OK
* DEBUG + DEBUG_FILE → Fail

So, then I should start Project from debugging Hub, (`server/projects/control/util.ts`, `launchProjectDaemon`), it failed with exit code 0. 
```
2023-10-29T11:04:39.508Z: cocalc:debug:project:BUG (uncaughtException) initializing uncaughtException handler
```

![image](https://github.com/sagemathinc/cocalc/assets/1609739/f9d548e8-faf0-4f1d-a3a2-fb61d9fd05ab)

Probably (I am not sure…), this is because it inherites from Hub environment `DEBUG_FILE`, and failed starting project, because Project, runned by unpriviliged user, tried to write to same DEBUG_FILE.

if we disable `DEBUG_FILE` setting for Hub, it creates project daemon without problems.

So may be better strip all `DEBUG_FILE` from env, running Project?
Because in `packages/project/client.ts` I see separate logic to enable debugging in projects

```js
const DEBUG_FILE = join(HOME, ".smc-DEBUG");
if (fs.existsSync(DEBUG_FILE)) {
  DEBUG = true;
```

**Comment by williamstein** [comment]
> So may be better strip all DEBUG_FILE from env, running Project?

Yes.  Do it!  Thanks.

> Because in packages/project/client.ts I see separate logic to enable debugging in projects

That's just a coincidence that the variable is named the same thing.
