### ISSUE TITLE
Displayed fee is wrong or unclear when editing a subscription

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7025]
When editing a subscription license, the "apply" button shows the difference in monthly price of the subscription before and after, but to me it reads as "this is how much you will have to pay right now". I think either the wording has to be clarified, or there should be two prices shown (maybe not on the button itself) - how much the monthly price will increase by and how much will be charged right now for the rest of the period.

Moreover, I have just edited a subscription license, then opened it again and I see without doing any changes:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/aebacdf3-215d-456b-8df4-028c0af3a480)
probably it is the difference between what was already paid for this month including the edit change and what would be the next month charge.

**Comment by haraldschilly** [comment]
Today, I saw something different with a dedicated VM license. Making it end now instead of in 4 days didn't gave a refund. Maybe I'm confused about what is charged when, though. It's at minimum very confusing.

**Comment by williamstein** [comment]
Fixed.
