### ISSUE TITLE
markdown/slate: hover claims double click, but single click does it

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7028]
A link in a markdown file, rendered in that slate editor, has a hover text claiming I have to double click. Actually, a single click works, though. I think the double click idea is only for URL links to external pages, but not for internal links to projects and files in projects. But maybe that's actually the bug and all kinds of URL links should be double click. In any case, there is a text/action discrepancy.

![Screenshot from 2023-11-02 12-18-05](https://github.com/sagemathinc/cocalc/assets/207405/f67ccd43-eec9-4ccd-8c8b-79a6ab85a23a)

**Comment by williamstein** [comment]
Confirmed, and yes this is definitely a bug.
