### ISSUE TITLE
Admin refund does not work for subscriptions

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7034]
I cannot reproduce it on the test server with a fake card, however it seems pretty consistent that I cannot refund automatic charges for users whose subscription renewed, but they didn't expect it. The error message is about missing invoice and includes `pi_...` which is an existing payment intent. It may be related to the fact that sometimes invoices are not generated in Stripe, so maybe the call to refund such charges should be a little different.

**Comment by williamstein** [comment]
I think these are for grandfathered subscriptions using the old payment method.  It's not clear we should implement this ever.  Instead, use stripe to do such refunds (like we always did before), since we will soon-ish completely delete all legacy cards on file anyways.  I'm closing this.

**Comment by williamstein** [comment]
followup ticket -- https://github.com/sagemathinc/cocalc/issues/7197
