### ISSUE TITLE
db: optionally support enforced encryption and SSL certificates

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7038]
If the Postgres DB enforces encryption, there is no way right now to add the SSL certificate. The two places in the codebase¹, where the `pg.Client` is instantiated, need a way to set the `{..., ssl:...}` parameter.

The goal of this ticket is to enable that, by e.g. setting an environment variable `COCALC_DB_CERT=/path/to/filename.pem` and then insert the content of that file, e.g. 

```js
new Client({host: ..., ssl:{ca:fs.readFileSync(process.env.COCALC_DB_CERT)}});
```

Background of this is [Azure's managed flexible Postgres DB](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-server-parameters). The work around is to disable this, by setting `require_secure_transport=OFF`.

¹ I know of pool.ts and postgres-base.coffee in the database package. Are there more?

**Comment by williamstein** [comment]
Some centrally important env vars are documented here, for what it is worth:

https://github.com/sagemathinc/cocalc/blob/master/src/packages/backend/data.ts

**Comment by williamstein** [comment]
https://github.com/sagemathinc/cocalc-docker/blob/master/docs/external-postgresql.md
