### ISSUE TITLE
Project hangs because loading of primus.js fails

### ISSUE THREAD

**Issue by chquix** [sagemathinc/cocalc#7043]
When I try to open a project, sometimes the project is stuck in "Connecting...". The Javascript console of the browser and the server logs reveal that CoCalc is trying to load raw/.smc/primus.js but gets a 404. 

This happened recently for different projects, a server restart fixes the problem for one project, but then the problem appears for another project.

**Comment by williamstein** [comment]
I'm closing this since it sounds like a network issue that isn't part of cocalc itself.
