### ISSUE TITLE
flyout panel: make one that just has a list of all open file tabs.  Basically it would be a vertical tab column. 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7045]
The order would match the open tabs.

This would be incredibly useful when you have way too many file tabs open.

We could have a filter at the top as well to quickly find tabs.

This is a pretty standard thing in web browsers...

If we had this, maybe we could also make the top tabs really tiny again (so you can barely see the text), like browsers do, since there would always be an easy second way to see tabs.

**Comment by haraldschilly** [comment]
I like that, but instead of a custom order, I would like to see them grouped by directory and for each group, sorted by name. That could be a toggle, of course. Such a filter could also be by popular type. I've assigned this to me. I had this on my mind since I created them.

**Comment by williamstein** [comment]
> I like that, but instead of a custom order, I would like to see them grouped by directory and for each group, sorted by name.

Sure it would be good to have a lot of options.  

Optimally, you would write this with those fixed sorts, plus whatever order the tabs are in.  Then I could improve it to make the items in the flyout panel "drag n drop" sortable, sync'd with the file tabs.    I just fixed a bug in our sortable list code a few days ago (when dragging an item above/below the list, it wouldn't work).

**Comment by williamstein** [comment]
@haraldschilly did it, and it's awesome!!!
