### ISSUE TITLE
Cancelling a subscription renewal should result in zero charges

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7047]
At the moment when a subscription is up for renewal and the user decides to cancel it "now", the result is
1) a pending charge for renewal with the start date in the past
2) the license is still active for 10 minutes
3) a refund to the account for an amount a bit less
4) presumably with a possibility to spend that balance before the pending charge hits
5) and a slightly negative balance when the pending charge posts

In the ideal world:
1) the pending charge is cancelled right away
2) the license becomes invalid right away
3) there is no refund, no balance to spend, no negative balance one the dust settles...

**Comment by williamstein** [comment]
+1

**Comment by williamstein** [comment]
this should all be fixed now.
