### ISSUE TITLE
Network charge is shown with a wrong sign

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7060]
![image](https://github.com/sagemathinc/cocalc/assets/1993227/b1eb1221-6ad9-48f4-8b0c-ae340cc56d84)
The network charge for the compute servers is correctly deducted from the balance, but it is shown as blue/positive, while it should be black/negative.

**Comment by williamstein** [comment]
Where is this **exactly**?

**Comment by novoselt** [comment]
In the transaction list of the project! Sorry, I zoomed in on the problem part too much!

**Comment by williamstein** [comment]
Strange.  I don't see this problem at all.

**Comment by novoselt** [comment]
I've rechecked the same transactions and don't see it now either. Although I did manage to screenshot it when there was a problem. No idea how it can be sporadic.

**Comment by williamstein** [comment]
It could be that I fixed the bug and you had not yet refreshed that browser
tab?

-- William Stein

**Comment by williamstein** [comment]
OK, I just saw this - it's for network data that is *active*.  For non-active data the sign is correct.

**Comment by williamstein** [comment]
Still wrong.
