### ISSUE TITLE
terminal/compute server: very first click opens/closes immediately

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7083]
Something is a bit off with the initial state of the dropdown. Upon my first click, it opens up the dropdown, but it immediately closes again. Next clicks work as expected. Here is a short screencast showing 3 clicks.

[screencast-cocalc.com-2023.11.29-18_17_36.webm](https://github.com/sagemathinc/cocalc/assets/207405/87e17e9e-0fab-49d7-859e-5be64947ad9d)

**Comment by williamstein** [comment]
I absolutely cannot reproduce this, and have never seen it in 2+ months of development and testing.  Thus you need to be very clear about **exactly how to reproduce it**.

**Comment by haraldschilly** [comment]
I can refresh the entire page and after it loaded, the first click behaves like that. Maybe it's related to the split frames.

**Comment by haraldschilly** [comment]
So, is there a way to store some data for each frame, just persistently across any changes to e.g. `active_id` ? I poked around and maybe `local_view_state` sounds helpful.

**Comment by williamstein** [comment]
> So, is there a way to store some data for each frame, just persistently across any changes to e.g. active_id ? I poked around and maybe local_view_state sounds helpful.

Yes, there is.  That's how cursor positions, scroll state, and a lot of other things are stored.  This is precisely the problem that local_view_state solves.  Look at cocalc/src/packages/frontend/frame-editors/code-editor/actions.ts and in particular set_frame_data and how it is used.   I don't remember exactly how it works, but I reread that code periodically to remind myself.

**Comment by williamstein** [comment]
Thanks for explaining so clearly how to reproduce the bug!  I implemented a simple fix.
