### ISSUE TITLE
Be more careful with discounts on subscription licenses

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7096]
I *think* that it is related to discounts, a follow up to #7037

I've cancelled and immediately resumed a subscription. Common sense suggests that I should be charged as much as I was refunded, unless we do penalize users for trying to use subscriptions as "pay-as-you-go", which is reasonable, but should be clearly explained. This is what I got:

![image](https://github.com/sagemathinc/cocalc/assets/1993227/1c6cdeb2-8d66-4cac-b4a4-935fa69ddb88)

and likely closely related to this - if I try to edit my active subscription, I am offered to pay **BEFORE DOING ANY CHANGES**:

![image](https://github.com/sagemathinc/cocalc/assets/1993227/680190c8-e56c-4953-8922-d14cf73c0c62)

These 20 cents do look like the discount on the remaining subscription period. While we can use some complicated logic for discounts here, it certainly should not penalize users who don't do any changes or want to upgrade their subscription rather than downgrade.

**Comment by williamstein** [comment]
Canceling and resuming subscriptions now works correctly.
