### ISSUE TITLE
support for ChatGPT in Sage Worksheets disappeared

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7125]
There was support for ChatGPT in Sage Worksheets before https://github.com/sagemathinc/cocalc/pull/7094, but with that merged, the ChatGPT support just disappeared.    It needs to get added back ASAP, since Sage Worksheets are extremely popular in CoCalc.

**Comment by haraldschilly** [comment]
Possibly relevant: 5b76b6131fef98bb0d42d3db2f8e91e4d53355b2

Workaround: convert to a jupyter notebook
