### ISSUE TITLE
chat/AI: the "regenerate response" button does not send the entire history

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7131]
So, if you have a thread like "user asks @AI" → reply → "follow up question" → "reply" and you click on the regerate response button, it clearly regenerates the first answer.

what it should do is to send the whole history, such that the last response is regenerated.

in the screenshot below, there was something with "is_prime" in the response, but now it's gone and looks like the first response

![Screenshot from 2023-12-14 18-14-06](https://github.com/sagemathinc/cocalc/assets/207405/ae15b911-72c8-41a0-b626-e6ebcc36899f)

**Comment by williamstein** [comment]
@haraldschilly I think you fixed this?

**Comment by haraldschilly** [comment]
yes, it's in the referenced PRs
