### ISSUE TITLE
csv file exported from course system doesn't get rendered properly with new csv table viewer

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7138]
1. Export grades from a course
2. Open the resulting csv file
3. Get this:

<img width="510" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/7e313533-0b32-4210-aa17-d7673025e2d9">

The "raw data frame" on the right does work fine.  This is probably an issue with missing on non-optimally formatted (or parsed) column headings...

**Comment by novoselt** [comment]
My guess is that it should be an easy fix, but it is also high priority - once somebody tries to export the grades, they hit this bug.
