### ISSUE TITLE
Relax precision for allowing purchases

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7142]
I think it is extremely confusing and annoying for a user when a transaction cannot finish because $125.03 received from Stripe is not enough to pay for a license that costs $125.03 in CoCalc, demanding the user to pay another $5 without any coherent explanation why...

Concrete implementation suggestion - when finalizing a purchase of the stuff in the cart, let it through if

 "current balance" - "cost of items" >= "minimum allowed balance" - "1 cent"

**Comment by williamstein** [comment]
I think all the bugs that lead to this may now be fixed.

**Comment by williamstein** [comment]
I'm closing this again since the plan "Relax precision" doesn't make sense to me.  Instead let's just get everything right from the beginning rather than having little errors get allowed.
