### ISSUE TITLE
Refund transactions are not handled properly for admin user view -- balance not displayed properly

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7150]
I have just refunded $5 on this account and now the running balance is off by $5, although it does show correctly in the user view. These are all the transactions for this user:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/8515908b-7334-41e1-a81a-87403b995cd0)
so the bottom one should bring the balance from $0 to $5, not to $10.

**Comment by williamstein** [comment]
Did you click refresh?   It is not supposed to be correct until you do.

**Comment by novoselt** [comment]
I did, then waited and clicked again! Also, if it refreshed enough to show the refund transaction, I would expect that the rest got refreshed too, i.e. what is shown should always be accurate at least for some point in time. In this screenshot we have correct list of transactions with incorrect balance as well as running balance. Not critical, since it is an admin view, but would be nice to fix and I imagine the fix is relatively simple.

**Comment by williamstein** [comment]
This may be a caching issue...

**Comment by novoselt** [comment]
I've just hit this issue again and forced-refreshed the page - the balance was then shown correctly, so it is a caching issue.

**Comment by williamstein** [comment]
I think the problem may just be that when you click the refresh button in the admin view it doesn't refresh the balance.  It does refresh the list of transactions.  I think this because I just did a refund and saw this, and then sniffed the network traffic and only the transaction list was updated when I clicked refresh.  I opened the same user in another browser tab and got the correct balance.

**Comment by williamstein** [comment]
So this is the easiest possible kind of caching issue.

**Comment by schrodingersket** [comment]
> I think the problem may just be that when you click the refresh button in the admin view it doesn't refresh the balance. It does refresh the list of transactions. I think this because I just did a refund and saw this, and then sniffed the network traffic and only the transaction list was updated when I clicked refresh. I opened the same user in another browser tab and got the correct balance.

Yep. Looks like the purchases table refresh function only refreshes the list of purchases, and doesn't re-query the balance. Incoming PR to fix this.
