### ISSUE TITLE
starting project clears terminal

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7151]
I have some output in the terminal. When the project (re)starts, that output is gone. I also can't scroll up to see what has been there before. This must have changed recently and I very much liked how it was before, where I was able to see the previous output. At least, I want to be able to scroll up and see the history.

**Comment by williamstein** [comment]
Definitely a bug.

BAD WORKAROUND: look at the hidden file on disk that has the full history still.

**Comment by haraldschilly** [comment]
this seems to be fixed
