### ISSUE TITLE
Clarify checkout interface

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7166]
# This is confusing:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/91be6a11-aadc-40f3-b4ee-d52f3ea59c65)
# the statement is that no payment is required, but then I am offered to add money to my account?
![image](https://github.com/sagemathinc/cocalc/assets/1993227/76f1d1fd-3f0b-4229-af90-51cd9b86ce7f)

Not sure what's the best solution is, but some ideas:
- get rid of the blue message box on the top entirely
- make the selector "Pay Total / Apply Account Balance" more prominent, I would prefer solid button with text for the selected option, although I get that it may be "fixed by style"
- we do put a number on the main button when we suggest making a payment, then instead of "Complete Purchase" let's use "Complete Purchase Using Account Balance"
- Perhaps be more explicit with the selector as well "Apply Account Balance ($xxx available)"

**Comment by williamstein** [comment]
Here's how Amazon.com solves basically this problem (but with credit card points).  They by default strongly encourage you to just pay the whole balance. However, they have an option to apply an amount of your choice from your  existing points.  Maybe it would make sense to revamp things to look more like this?

<img width="916" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/ea8bfbab-d536-4a78-932c-6db3884d86e4">

**Comment by novoselt** [comment]
I actually did think about Amazon interface as well - it obviously was used quite a few times ;-)

**Comment by williamstein** [comment]
> I actually did think about Amazon interface as well - it obviously was used quite a few times ;-)

To me their UI is kind of "ugly".  However, they are the most popular website in the world for "buying things", and the actual functionality of their purchase and checkout flow is very highly polished and optimized.   The cocalc store implementation is inspired by amazon's underlying design, so it's good to be aware of it.
