### ISSUE TITLE
Cancelling a subscription might be off by a factor of 100x

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7171]
Transaction 16877 cancels an erroneous subscription for a refund. It was $0.3391 less than purchasing price, so this was the cost for about 27 minutes. But with $5.43/month the cost of 27 minutes is $0.00339375, which is very close except for the two leading zeroes. Looks like a confusion in code between cents and dollars.

**Comment by williamstein** [comment]
> Looks like a confusion in code between cents and dollars.

Interesting.  All the cocalc code uses dollars as the unit, but stripe uses cents.   

I have unassigned @schrodingersket since this is high priority, and anything genuinely high priority can't be assigned to him as he is working very much part time, right?

**Comment by williamstein** [comment]
Also, changing the title to "might", since a factor of 100x would mean hundreds of dollars off for other cases that are more than a few minutes, and we haven't seen that, right?

**Comment by novoselt** [comment]
Makes perfect sense!

**Comment by williamstein** [comment]
There is absolutely no way that the refund is off by a factor of 100x.  E.g., I have a test $9.05/month subscription that was 4 days into it's period.   I just canceled it now and got a refund for $7.81, which seems almost exactly right.    There's clearly no way that things are just off by a factor of 100x in general.

I realize now that your title is very ambiguous and vague.  it is "Cancelling a subscription seems to be off by a factor of 100x".  I interpreted to mean "Cancelling a subscription refunds an amount that is off by a factor of 100x".     I think now you actually mean "Cancelling a subscription isn't exactly right, and I noticed one number is roughly 100x another number."

**Comment by williamstein** [comment]
I've moved this back to assigning to @schrodingersket since I don't really know what this ticket really means.  If it really were a clear case that we were charging 100x too much, then it would be a blocker to be fixed ASAP, but that's not the situation. Sorry for any noise.

**Comment by novoselt** [comment]
It is indeed an observation on a single transaction which I've mentioned. Perhaps with the exact details of that license-edit it is possible to track down where exactly the discrepancy is coming from by plugging in its parameters into some tests.

**Comment by schrodingersket** [comment]
FWIW: This difference between resume/cancel is exactly what I'm working on resolving since that needs to be fixed in order to resolve a couple of the other issues I'm working on.
