### ISSUE TITLE
flyout panels: the log panel doesn't provide any way to know *who* opened a file

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7198]
I realize this is intentional, since you want to dedup the files log. But it really reduces the value and functionality of the log, and means for a significant use case it is 100% essential to also use the main Log page.  

It would be nice to be able to see who did what in the flyout log, since it is a log after all.
In the activity tab/mode you can see who did other actions like created, copied, deleted.  But who opens is not available.

**Comment by haraldschilly** [comment]
as a result of https://github.com/sagemathinc/cocalc/pull/7209 I'm closing this
