### ISSUE TITLE
Be consistent with displayed decimals

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7210]
![image](https://github.com/sagemathinc/cocalc/assets/1993227/e0c5ee6c-68ae-40ee-8314-ffecd890e2ee)

The first zero is displayed with 3 decimals (while the hover over displays the 4th non-zero), the second has no decimals at all, and the last one - two decimals. Why?

Without some good reasons to do otherwise, I would strongly prefer to have dollars-dot-whole-cents everywhere, regardless of the actual amount and possibility to display fewer zeros. Higher precision on hover over makes perfect sense, and hopefully it is also consistent, so that it is easy to compare such numbers.

**Comment by williamstein** [comment]
> Without some good reasons to do otherwise, I would strongly prefer to have dollars-dot-whole-cents everywhere, regardless of the actual amount and possibility to display fewer zeros.

How is it rounded?    E.g., for this

https://github.com/sagemathinc/cocalc/issues/7207

you would want 352.511 to be rounded *up* to 352.52.

**Comment by williamstein** [comment]
Now they all just get truncated to 2 digits, which are always displayed:

<img width="1698" alt="image" src="https://github.com/user-attachments/assets/67ff2510-c89f-48d4-894d-aea5ac3fa36a">
