### ISSUE TITLE
Simplify section transfer for student pay

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7219]
There can be a button next to paying the course fee titled "Transfer from another section"

Possible actions:
1) Creating a support request, ideally with FROM and TO information.

2) Automatic replacement of a license from a paid for course with a license for the unpaid course. Potential issues: licenses for different sections may be very similar, but not identical, in particular in start/stop date (and especially time), which may create some discrepancy in price. That discrepancy is likely to be small, a few cents, unless the instructor has made a mistake. It feels right to give students a top up for free, but one should be aware of potential abuse via API.

3) Combination of 1 & 2 - automatically do license edits and top ups if necessary, but require human approval to finalize the transaction.

As an option to deal with potential price discrepancy - check that it is small enough, but then do NOT use the cost of the default new section license as the cost of the actual new license for the student - set it to exactly what was the old price. Then there is no way to play with iterated refunds. This may be related to #7218

**Comment by williamstein** [comment]
done!
