### ISSUE TITLE
Do not add extra cents to vouchers

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7220]
![image](https://github.com/sagemathinc/cocalc/assets/1993227/e09f49cd-d99e-43e7-b3dd-6c154b84dced)

The actual charge was for $4.74, one cent more than the voucher! It does not happen with $5, but I have just checked again - trying to make a voucher for $4.73 shows up as costing $4.74.

**Comment by williamstein** [comment]
Yeah, a real purchasing bug!

**Comment by williamstein** [comment]
It's a bug in the "round2up" function, so this will be very easy to fix:
```
> require('./dist/misc').round2up(4.73)
4.74
```
