### ISSUE TITLE
Bug in parsing Octave text output

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7227]
For some reason there are "l"and "h" added even to integer output, with vectors there is also "4":
![image](https://github.com/sagemathinc/cocalc/assets/1993227/6733d7a7-7c27-4c46-bf44-afebc5607849)

**Comment by haraldschilly** [comment]
essentially a dup of https://github.com/sagemathinc/cocalc/issues/6695 … worth checking the upstream issue, if there is any progress

**Comment by novoselt** [comment]
https://github.com/Calysto/octave_kernel/issues/215#issuecomment-1633204407 has a suggestion for a workaround, otherwise upstream tickets are open.

**Comment by haraldschilly** [comment]
Hmm, we could try setting this globally, to disable `enable-bracketed-paste` … but I don't really understand what impact this has. First, this sounds like a feature of bash to prevent users shoot them into their foot, but it's more like a convenience for vim and emacs. For vim, I do know about the `:set paste on|off` toggle.

**Comment by haraldschilly** [comment]
this is addressed by that inputrc option. Hopefully, the fallout is minimal. Ideally, they fix their kernel upstream, though.
