### ISSUE TITLE
Separate Compute Servers and Code Servers

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7236]
I always thought it is confusing, but I also see how users are confused by it. No concrete suggestion, but "Servers" tab should be split into two or there has to be a more clear indication that Compute Servers have very little if anything to do with other servers.

**Comment by williamstein** [comment]
I do not agree with this.  I of course do not think the current design is optimal, but I also don't think just adding more buttons to the already overcrowded action bar (where you haven't even made a concrete suggestion) is better.
