### ISSUE TITLE
Missing menu to toggle output scroll in new UI toolbar.

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#7260]
There should be a way to change the scroll properties of output cells through the menus, but this has gone missing.  It would be also nice if there were a way to enable or disable **all** scroll bars.  (Toggling can be confusing when some are scrolling and some are not - toggling is not usually what is wanted in these cases.)

WORKAROUND: "Help --> All Keyboard Shortcuts and Commands..." has all commands. Search for scrolled there and you can still run the command that way by clicking on it. Also the keyboard shortcut to toggle this for selected cells is shift+O.

<img width="880" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/e307e1d3-33b7-4384-9482-df3d2185e8ec">

(from #7244)

**Comment by williamstein** [comment]
>  (Toggling can be confusing when some are scrolling and some are not - toggling is not usually what is wanted in these cases.)

I strongly agree.  It's only toggle right now I think due to copying old Jupyter Classic.  I would prefer to implement in the menus just enable/disable of scroll for selected or everything.  Toggle would still be in the commands (from the screenshot), of course.

**Comment by williamstein** [comment]
I'm fixing this right now with four new menu items added to collapse and expand, as follows:

<img width="752" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/e9c76987-550b-418e-bdb0-94d8941046e7">

I'm not implementing toggle at all in the menus, but toggle is in the command list:

<img width="691" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/8dc542d7-e7ec-40ef-a0ab-1296963c13b2">
