### ISSUE TITLE
Disk subscriptions are broken

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7269]
An automatic disk subscription renewal didn't work. I am trying to do it manually and either nothing happens, or I managed to get
![image](https://github.com/sagemathinc/cocalc/assets/1993227/dd52b382-24e1-4c44-b986-972a2bd18cc7)
So I guess since one cannot edit disk licenses and renewing a subscription works by editing a license, disk subscriptions cannot work!

**Comment by williamstein** [comment]
Deprecated by fa6bce19e18677eb014733c7e7df20ea49a49bf5
