### ISSUE TITLE
Default New Folder gets recreated when adding an assignment

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7282]
1. Go to Assignments in a course and click "Add Assignment..."
2. Click "Create New Folder" - "New Folder (number)" gets created and unchecked (I would check it by default, actually)
3. Click on the newly created folder to check it - a pencil icon appears at the right.
4. Click it to rename it, say to "HW" - this folder now will be actually created in the filesystem. BUG: "HW" is NOT checked in the listing (it should), but at the top I now see "+ Add 1 Assignment".
5. BUG: clicking that button adds "New Folder (number)" assignment, not "HW", and this numbered folder get created in the file system.

Expected results:
- I want to see the name I have entered as the folder and assignment name, without extra directories
- checkbox value should be consistent and intuitive!

**Comment by williamstein** [comment]
Most of this is different (and fixed) now.
