### ISSUE TITLE
The name of the active flyout panel is "actively" misleading and confusing.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7287]
During the last demo Blaec was doing, I told him "open the Jupyter notebook I just opened in your project".  He immediately looked in the Active flyout panel, thinking that since the notebook is currently "Active", that it would be listed there.  Of course it isn't, because Active is actually mapped exactly to the open file tabs in a particular client.  The "Active" flyout panel has little to do with what files are actually "Active" in a project (it may be a subset, but only if each tab got clicked on at least once).  

I think either "Active" really needs to be renamed to, e.g., "Tabs" or it needs to actually have a list of the active files, i.e., files open by at least one person.  This would be a sensible and interesting feature to implement, where it would show each file open by at least one person, along with little avatars next to the filename with who has that file open.   The current active flyout panel could be split into another section, e.g., actual active files at the top (as defined here), then "Your Open Tabs" as a second section that works like the current active page.

Note that RTC JupyterLab does in fact have an "Active" thing that is I think much like what I just described in the above paragraph.

In the "Edge" browser, this thing is called "Vertical Tabs".

WORKAROUND: You can find files people recently opened by clicking on "Log".

**Comment by novoselt** [comment]
I think the confusion is about "whose" active - "my active" or "someone's active"? The current design gives access to files that I keep open or those that I have bookmarked, both states have some relation to being active, but only for me.

I can agree that "Active" is not necessarily clear and descriptive, but "Tabs" does not sound any better to me. I certainly would not associate bookmarks with tabs.

**Comment by williamstein** [comment]
Here's what "Tabs" looks like.  

<img width="581" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/f5703030-c989-441f-90d1-40e1c1b0934a">

> I certainly would not associate bookmarks with tabs.

Maybe "Bookmarks" shouldn't be part of that panel at all then?  Browsers always have a completely separate panel about bookmarks, and it's a big deal.

**Comment by williamstein** [comment]
Another major issue with "Active" as a name is that it is primarily an adjective:

<img width="615" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/6ebc9f54-ed95-4160-8a63-67dd03d5fafc">

Every other flyout panel name (except "New") is a noun.

Active could mean "Active Users" or "Active Homework" or "Active Processes" or something else.  As an adjective it massively leaves things up to the imagination, since it's half a description. 

The only other adjective is "New", and that is perhaps excusable since that tab is for creating all manner of new things.

**Comment by novoselt** [comment]
After thinking about it for a while - I do think that it would be indeed better to separate currently open tabs and bookmarks. In that case just "Tabs" would be a sensible fit for the list of opened file tabs, while "Starred" or something else ("Favs" ?) with a star icon could be just for access to bookmarks. This should be much easier for new users to understand and start using without any extra explanations and experimentations, compared to the current panel which is very powerful, but one may have to think how to apply all that power. I have realized that I actually use it primarily for bookmarks, so it would be easier if it was just that.

**Comment by williamstein** [comment]
>  I have realized that I actually use it primarily for bookmarks, so it would be easier if it was just that.

I basically never use it for bookmarks.

It would make sense (and fit using nouns) to call one thing Tabs and another thing Bookmarks. 
It would be ideal if we make ALL of these things items that can be selected in a dropdown menu,
with an easy way to add them as buttons optionally to the side bar, just like we did the menus for
editors.  That way you could just add Bookmarks, and I could just add Tabs, and other users 
might add neither.  

We should replace the Home icon by a dropdown menu with items:

- Tabs
- File Explorer
- Create New File or Folder
- Activity Log
- Find in Files
- Compute Servers
- Code Servers (?)
- Users
- Upgrades
- Processes
- Settings
- Show/Hide button toolbar.

Each will have its icon, and maybe 2 or 3 are visible in the toolbar below.  You can hide the toolbar, or remove all shortcuts from it.  You can add shortcuts that you care about (and they use a shorter name there).  I would add:

- Tabs
- Explorer
- New
- Log
- Find
- Compute
- Upgrades
- Settings

but other people might add completely different things.

**Comment by haraldschilly** [comment]
In the UI branch I'm working on there is no longer such an "Active" entry on the side, hence this somehow goes away as well. I like the idea to show files of other users as well. Avatars are shown right now already. I don't like the idea of dropdown selectors.
