### ISSUE TITLE
Notifications by email

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#729]
It would be great to have the option (either globally or project-by-project) to receive SMC notifications in the form of "external" notifications (email for one, but possibly also Twitter, SMS, WhatsApp, ...).

**Comment by haraldschilly** [comment]
there are already a couple of issues in that direction: #664 #274 #113 (html5 also has notifications, that could even work when you close the tab) and probably more. we would have to work out a plan how to implement this, such that these cases and probably more are covered properly.

**Comment by williamstein** [comment]
Too vague.
