### ISSUE TITLE
Change scrolling height to fit plots

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7293]
By default I now get
![image](https://github.com/sagemathinc/cocalc/assets/1993227/dfd932d5-a360-437f-b288-1cf13f6999ed)

i. e. I have just a default size plot as my only output and its bottom is cut off. In some cases, I had the cut go between the plot and the axis labels which made me puzzled for a bit since I didn't realize that I had to expand the view. I think it would be better to either increase the output size everywhere to fit default plots, or to detect that the plot is displayed and increase the height just for that cell.

**Comment by williamstein** [comment]
I made this to change to align with what current upstream JupyterLab/Jupyter classic does, as decided by their accessibility experts within the last year...  Do you think they got it wrong?  Did I misinterpret what they do?

**Comment by williamstein** [comment]
(Maybe we could add a configuration option to account prefs?)

**Comment by novoselt** [comment]
Yes, I boldly claim they got it wrong - I didn't care much about the switch for text/long output and perhaps even prefer when the default height is limited, but when I am trying to plot something and display that plot I definitely want to actually see that plot, all of it at once! If I generate something with unusual size, of multiple plots, or plot with some extra text - sure, I get that it may not fit. But having to do extra actions for every single plot does not improve the user experience. I've checked Colab - it seems that there is no way to turn off vertical scrolling for long output, BUT default plots fit into that fixed maximum heigh just fine.

**Comment by williamstein** [comment]
> Yes, I boldly claim they got it wrong

OK, after trying to believe in this decision for a few months... I can no longer take it!  In my current dev branch I have reverted this change, and soon it will be reverted in production.   You're right -- they got it wrong.
