### ISSUE TITLE
Deleting a chat using file explorer deletes the main file

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7297]
The user reported it for a tex file (following my instructions on how to delete a chat) and I have confirmed it on a tex file as well:
1. Create a tex document
2. Have a chat on it
3. Open file explorer, show hidden files, select just the chat file.
4. Press Delete button and confirm that you want to delete ONE file.
5. Both the chat and the main document are deleted.

While it may be a rare operation, I am concerned that there are other situations where the root cause leads to issues.

**Comment by williamstein** [comment]
The root cause is that we explicitly implemented cocalc so that if you delete/move one file, then all corresponding auxiliary files are deleted/moved.    This is a special case of that general rule.   I am not convinced that this is a bug.

**Comment by novoselt** [comment]
Most users do not know that these files even exist. So it makes perfect sense to remove them when "actual files" are deleted. But when a user explicitly selects an auxiliary file and tries to delete it, I think the most logical and easy to implement behaviour is to delete just that file. Another logical solution may be to ask for a confirmation deleting other files as well, but I really can't imagine a situation when this will be desirable. If I do want to delete my document, I will press a button to delete my document, NOT the associated chat!

**Comment by williamstein** [comment]
This is very similar to https://github.com/sagemathinc/cocalc/issues/7735

And again, I'm not sure what the right behavior is...

**Comment by williamstein** [comment]
Yes, just do what you're suggesting seems fine, i.e., change the "all auxiliary files" to not include the original file.
