### ISSUE TITLE
Collapse old long messages in chats

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7299]
A particular problem is having AI generated responses in chat that may be quite long, which makes it difficult to find "real chat" messages. A possible solution is to collapse some messages to use minimum of vertical space: name, date, and the beginning of the message. If it can fit on one line - great! If two lines are better to get some sense of the message it may be better, but no longer than that.

As far as what messages have to be collapsed - maybe those that are older than some time period, maybe those that are longer than a certain number of lines, maybe those that are specifically from AI.

It may be nice also to have controls like collapse/expand all.

**Comment by williamstein** [comment]
@haraldschilly implemented this recently too.
