### ISSUE TITLE
Editing a non-standard license shows wrong info about presets

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7301]
![image](https://github.com/sagemathinc/cocalc/assets/1993227/404d53c5-7491-4050-aebb-5b25ed37d6e6)

The text talks about preset "Standard" but uses values that were assigned to the license before trying to edit it again.

Solution: either check which preset matches the license (if any) or show immediately expert configuration with actual numbers.

**Comment by williamstein** [comment]
How exactly did you get this to happen?  When I try to reproduce it, I get a big warning that the preset has been changed:

<img width="867" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/45e02879-a5c7-4689-a7bf-be90dba7b28f">

**Comment by novoselt** [comment]
- I have a license in my cart.
- I click "Edit" button.
- I am back at the store with license parameters loaded correctly, but no orange message that they were changed compared to the preset.
- If I do change anything, the message appears, so it is just the original view which is misleading.
