### ISSUE TITLE
Generate call to AI should have an option to include the whole notebook

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7311]
It seems that it includes the last cell, but it may be just a print statement, while some other related variables and functions were defined above.

**Comment by williamstein** [comment]
The options should be:

- nothing
- everything
- just the previous cell
- all previous cells

The assistant button at the top has something similar for all documents...

**Comment by williamstein** [comment]
Also when including the whole document, we should also tell the LLM which cell is currently focused, so it doesn't assume code after the current point is evaluated already.

**Comment by williamstein** [comment]
it does now :-)
