### ISSUE TITLE
Repeated keystrokes required when pasting code into a Jupyter code cell

### ISSUE THREAD

**Issue by schrodingersket** [sagemathinc/cocalc#7330]
When pasting code into a code cell via keyboard shortcut (`Ctrl/Cmd+v`) _after hitting the `[Enter]` key_, it is necessary to hit that keystroke twice before text is inserted. In other words:

1) Open a Jupyter notebook which contains a code cell
2) Click to the end of any line of code
3) Hit the `[Enter]` key
4) Attempt to paste the desired text via `Ctrl/Cmd+v` (on this step, nothing happens)
5) Hit `Ctrl/Cmd+v` again, and note that text is now inserted.

Reproduced in Chromium Incognito mode and Firefox Private Browsing mode in both dev and prod with new and existing Jupyter notebooks.

**Comment by williamstein** [comment]
What a weird bug.  I've never hit this and nobody else has reported it, and yet there it is.  

Note that it doesn't happen when pasting via the context menu, so it's some issue with the keyboard handler.

**Comment by novoselt** [comment]
I had this problem all the time, got used to pressing Ctrl+V twice, but never realized that it has any relation to Enter before... Thank you for fixing it!!!

**Comment by williamstein** [comment]
It didn’t actually have any relation to enter.  But that was a nice clean way of reproducing it.  In any case I never saw this before because I guess I’m just too slow… but I fixed it!
