### ISSUE TITLE
disable some AI integration instructor course setting seems to disable everything now

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7341]
This setting:

<img width="685" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/37d1a9de-7a7d-4c0f-9205-1cdf53eb0e54">

seems to not work anymore and just disables everything.    Probably the extensive refactoring of the LLM integration code "forgot" about this subtle feature.

WORKAROUND: only workaround is to not use that feature.

**Comment by haraldschilly** [comment]
This should be fixed now.
