### ISSUE TITLE
add share to LinkedIn to cocalc news items

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7347]
See bottom of eg https://cocalc.com/news/compute-servers-anaconda-and-jupyterhub-40

<img width="844" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/1a144745-afd0-46f8-a138-a4989dc0a6c8">

There should also be a LinkedIn button.

**Comment by haraldschilly** [comment]
I just found some [pointers about this](https://stackoverflow.com/questions/33426752/linkedin-share-post-url)
