### ISSUE TITLE
Consistent placement for Delete button in chats and changing it to Edit

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7357]
![image](https://github.com/sagemathinc/cocalc/assets/1993227/658542fe-20ed-465a-a724-5e4ad3dd7b74)
This is a single screenshot - sometimes Delete is to the left, sometimes above Reply, sometimes in the same grey area, sometimes reply is in white, sometimes reply is not even present.

- The most natural thing to do with a chat message is to reply to it, so I think Reply should always be the top/left button.
- While I advocated for Delete, I think "Edit..." would make more sense and in the edit mode it would be nice to have "Cancel", "Save", "Delete"
- "Show history" can also be hidden unless Edit is clicked or "Last edited" can be a hyperlink that opens history. The point is to remove repetitive UI elements. To reduce clutter and waste of space. (In that regard even "Reply" can be reduced to an arrow icon in a corner instead of a dedicated row.)

**Comment by williamstein** [comment]
For now I'm going to just quickly revert adding the delete button.  I never use it, and it is a mess, as you explain.

**Comment by williamstein** [comment]
I got rid of delete entirely (just clear the message), so this is no longer relevant.
