### ISSUE TITLE
Cocalc Docker Depreciated

### ISSUE THREAD

**Issue by KenwoodFox** [sagemathinc/cocalc#7364]
Did i miss a memo? Im still using cocalc docker and had no issues! What can be done moving forward for cocalc and can we add new instructions anywhere?

**Comment by haraldschilly** [comment]
CoCalc Docker is discontinued. The [announcement was very recent](https://github.com/sagemathinc/cocalc-docker/discussions/225). There are several reasons why – ranging from the overhead maintaining it to inherent security concerns.

Regarding CoCalc on-prem in general, the way to go for forward is the maintained and supported [CoCalc Cloud](https://doc-cloud.cocalc.com/) setup.

**Comment by edgimar** [comment]
I hadn't noticed this issue until now because it was closed, but there's a related
  [discussion topic](https://github.com/sagemathinc/cocalc/discussions/7414) I added that could be a place to discuss this further.
