### ISSUE TITLE
fallout from https://github.com/sagemathinc/cocalc/pull/7309

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7387]
1. Click the blue "Generate" link in cell 1
2. TWO modals pop up

<img width="1138" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/53416a98-5f57-4f32-9591-bc1f10ea8e58">

**Comment by haraldschilly** [comment]
This is quite strange. I just tried this on the prod website, and I can't reproduce it. Here is a screencast. I'll try with a different browser, maybe there is something non-obvious happening, that I've missed.

[screencast-cocalc.com-2024.03.22-09_30_57.webm](https://github.com/sagemathinc/cocalc/assets/207405/fadceaa2-c365-4440-b85c-233f1da029db)

**Comment by haraldschilly** [comment]
ok, I got it, it's just the first cell. I made a PR
