### ISSUE TITLE
jupyter/python: altair stopped working

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7396]
There was a ticket a while ago: https://github.com/sagemathinc/cocalc/issues/4468 which was fixed by wrapping the output in an iframe. Somehow, this no longer works (only the text output shows up). Example code is the same as in that ticket. I'm guessing the heuristic detecting this no longer matches with what a newer altair does. Here is a screenshot:

![Screenshot from 2024-03-25 14-09-25](https://github.com/sagemathinc/cocalc/assets/207405/1200da02-3090-4fd9-ad12-9f9f8337064b)

**Comment by haraldschilly** [comment]
I can see, the relevant code changed recently. Maybe this is caused by 22ae0d8813b9d489b79f22ab3398afe31163cb41

**Comment by williamstein** [comment]
Altair works now.
