### ISSUE TITLE
BUG: regenerate response in LLM chat only uses the first input message

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7418]
<img width="603" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/674f9274-72b9-4d35-a140-f9332e968320">

**Comment by williamstein** [comment]
(I did regen response after the 2+3 and it didn't keep my last prompt.)

**Comment by haraldschilly** [comment]
dup of #7131
