### ISSUE TITLE
Redesign the footer of the landing and related pages

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7429]
This one:

CoCalc  –  [About](https://about.cocalc.com/)  –  Sagemath, Inc.  –  [Contact ](mailto:help@cocalc.com)  –  [Policies](https://cocalc.com/policies)  –  [Products and Pricing](https://cocalc.com/pricing)  –  [Software](https://cocalc.com/software)  –  [Status](https://cocalc.com/info/status)

- CoCalc and SageMath, Inc. are not linked to anything - why are they even present, especially with CoCalc logo below?
- About should be in sync with About in the header, or not there at all.
- Contact is a mailto link, which is fine if we have to have one there, but Support on the top is a better way to contact us
- Policies - **this is the main reason I opened this** They are hard to find! If we have to have them in the footer - fine, but can we also have a link from the header?
- Products and Pricing - seem quite random there, while the information is potentially useful, I would move it to something else.
- Software also seems a bit random there
- Status is maybe natural, but I suspect there is an even better place

So overall I would lean to "redesign" as in "get rid of" by moving half of the content to the top, but less drastic actions still can improve it.

**Comment by williamstein** [comment]
> CoCalc and SageMath, Inc. are not linked to anything - why are they even present, especially with CoCalc logo below?

They are customizable for on prem installations. 

I feel like this list of suggestions is pretty vague right now.  For example, for "Status is maybe natural, but I suspect there is an even better place" one could do research and see where other successful sites typically put a link to status information.  E.g., on https://github.com, status is in the footer (exactly like on cocalc):

<img width="850" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/9a024e51-2f1e-457f-8c03-ee6c750cd478">

I wonder if somebody copied Github for the first version of our footer...

**Comment by haraldschilly** [comment]
for me, a good footer is on deepnote, where columns structure pages by "target audience"

![Screenshot from 2024-04-15 20-28-34](https://github.com/sagemathinc/cocalc/assets/207405/d5949e0d-3d21-4709-928b-72e5f9d3554e)

**Comment by williamstein** [comment]
Similar for antd: https://ant.design/docs/react/faq (scroll down)

**Comment by williamstein** [comment]
We now have an official hosted (not on cocalc) status page: https://status.cocalc.com/   

This would be something that would make sense to link to from the footer...  Right now, nothing links to it.

**Comment by williamstein** [comment]
Good example -- https://vercel.com/
