### ISSUE TITLE
Confusing inconsistent rounding for display purposes

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7440]
These are all transactions on the account:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/c8f2b086-be5c-428b-a918-8f981d6b19b5)
Why is the starting balance -$0.01, while the "more precise" amount on hover is shown as exactly $0? What should the user think looking at such a page? That for some reason the balance is one cent lower, than required for the subscription to renew? And that it is still pending and not renewed because there are insufficient funds? And how did that cent get spent in the first place?

Since zero without doing any computations is an exact number, my guess is that $169.90 is not, the binary representation is a bit lower. Then the credit is shown rounded to the nearest cent (and it would be extremely weird to show any other rounding here!), but the available balance is shown rounded down, which is one cent lower. Then deduction from that amount somehow results in -$0.01 balance lower.

I tried to find out if there is some "standard money precision" and the answer is basically "no".  It is very difficult, however, to always do the consistent right rounding for computations and display purposes. I very much would favour the approach of dealing with exact cents for everything, including storying numbers as whole cents. Yes, we may overcharge somebody many times for running a compute server or LLM model when the charge is a fraction of a penny. We can call it "transaction fee" - it is applied to every single transaction and it is always a penny or less. How many transactions should one make before there will be a noticeable amount? If someone "lost" $10 due to such uprounding by doing 1000 transactions - surely there was some substantial value derived from those transactions?! If not - the loss of $10 is a great motivator to stop putting extra load on the database.

**ALL rounding issues will be resolved by switching to whole cents.** I know that LLMs charge with higher precision - maybe it is very relevant for auto-completion or something else where the amount of transactions is substantial and they tend to be small. Our transactions do tend to be bigger, fortunately! We definitely need to work with high/floating precision for computing cost per hour etc., but once we multiply it by the time period - reduce it to whole cents.

Yet another approach if customers feel ripped off - always round to the nearest integer, giving away for free those LLM transactions, which cost less than half a penny.

Side-benefit - less need in displaying exact amounts on hover, so they can be removed or repurposed.

**Comment by williamstein** [comment]
> Why is the starting balance -$0.01, while the "more precise" amount on hover is shown as exactly $0? 

You lobbied recently privately to ALWAYS round balancing down to 2 decimal places in all cases, and that's exactly why -$0.01 is displayed there.

>  the "more precise" amount on hover is shown as exactly $0? 

It is more precise.   The actual value might be -$0.00001, which would round to display as `$0`.

In any case, this entire issue is a direct result of something you specifically lobbied for earlier this week:

```js
~/cocalc/src/packages/util$ node
Welcome to Node.js v18.17.1.
Type ".help" for more information.
> a = require('./dist/misc')
> await a.round4(-0.00001)
-0
> await a.round2down(-0.00001)
-0.01
> await a.round2(-0.00001)
0
```

**Comment by williamstein** [comment]
Do you want to eliminate all rounding for the hovered values?  That would be a relatively easy change to make.  You might then see something like -0.000010939292 in a case like this...

**Comment by novoselt** [comment]
> You lobbied recently privately to ALWAYS round balancing down to 2 decimal places in all cases, and that's exactly why -$0.01 is displayed there.

It looked like the right solution for some problems, but it obviously causes others!

>I think the title of this issue is misleading, as the display is not inconsistent. Everything is consistent with the value being -0.00001 and the choices we've made for displaying numbers.

With background knowledge and history, it is possible to deduce what is going on and understand how it follows from choices made. But from the user point of view it makes absolutely no sense to see -$0.01 as the starting balance and $0 on hover is inconsistent.

>Do you want to eliminate all rounding for the hovered values? That would be a relatively easy change to make. You might then see something like -0.000010939292 in a case like this...

And that would be horrible too. I would much rather switch to whole cents everywhere. I do realize that it is likely to be substantial amount of work. But I am pretty sure that it is LESS work, than what was already spent on tracing down and fixing proper rounding. It would also completely eliminate such issues coming up, while otherwise I suspect it will continue to drag for a while if not forever.

One somewhat tricky issue with switching to whole cents is that past transactions are done as floats. They can either stay that way or be rounded down, in user's favour.
