### ISSUE TITLE
Copying read-only cells (assignments) produces cells that cannot be deleted.

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#7447]
If a student copies a read-only cell, they can paste it as a read-only cell for their own work, but then cannot delete it.

I suggest that when a student copies a read-only cell, that when they paste it, it should paste in an editable form.

Time Travel and undo provide work-arounds.

**Comment by williamstein** [comment]
I just checked, and I think the current behavior in cocalc (copy doesn't change cell metadata) exactly matches JupyterLab.  So unless there is a very compelling reason to change it, I'm closing this.

**Comment by mforbes** [comment]
I personally think it is a very compelling feature that a student should not be able to make unrecoverable changes in their work, but if this is also a JupyterLab issue, I can try to raise it there.  Since Time Travel works, I think it is reasonable to close until JupyterLab changes (if it does).

**Comment by williamstein** [comment]
> I personally think it is a very compelling feature that a student should not be able to make unrecoverable changes in their work, but if this is also a JupyterLab issue, I can try to raise it there. 

Please double check me, but I think JupyterLab and Cocalc do the same thing in this case.     If JupyterLab devs were to agree that metadata should be treated differently on paste, I would change cocalc.  I've not thought very hard about this, but there might be some hidden issues.

In any case, taking compatibility with JupyterLab seriously is I think something that cocalc cares more about than the other jupyter frontends (e.g., colab, deepnote, etc.).
