### ISSUE TITLE
Redesign prompt generation buttons

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7477]
I mean the row of buttons under the input box here:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/0f282143-bbd5-4343-a0d2-9f21102160b1)
Current problems:
- they are a bit intimidating and to me look like they will do what they say when I press on them, perhaps because they are actions like "Explain"
- in reality almost nothing happens: a little bit of text is added in the prompt and a somewhat similar explanation appears on the bottom
- it is even a bit disappointing that nothing at all happens if I press the second time ;-)

Suggested changes:
- get rid of the message on the bottom and instead make them hover tips.
- add a way to generate and insert the next cell, i.e. instead of creating a new empty cell and then clicking generate in it, I want to get access to the same functionality while a cell with code is in focus
- perhaps some functionality should be available as a dropdown from the main AI button, similar to "Regenerate | V" for chat replies? Such a dropdown can be used to collect all AI-functionality
- Have more involved samples/templates for code generation based on existing cell/notebook.

I think the last point is crucial, even though it is the least clear one regarding actual implementation. Nothing terribly useful is going to happen when AI generates the whole notebook based on description, the main advantage in day-to-day work is likely to be in developing existing code further. While we hopefully can't enumerate the next steps users will want to take, it may be possible to provide some inspiration for them to base detailed prompts on.

An attempt to come up with some examples:
- read a dataframe with some description of the format, e.g. some columns are dates, some can be used as indices, some contain currency that we want to get as numbers
- do some non-trivial transformation of a dataframe
- plots/modification of plots, that involve more than just calling plot

Blaec may be a great inspiration for inspirational examples since he actually talks to a lot of potential users!

**Comment by williamstein** [comment]
@novoselt prompt generation has been redesigned.  Is it good enough?

**Comment by novoselt** [comment]
It is fantastic!
