### ISSUE TITLE
sign up discards "role" if you use single sign on

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7489]
The current sign up page has a new "Select at least one role:" selector:

<img width="1070" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/9c9a21c6-c822-488c-8a7f-827459a3accd">

However, there's a MAJOR bug in that if after selecting roles you click on a single sign on box, then the roles are just completely discarded.

**Comment by haraldschilly** [comment]
Maybe the selection can be temporarily stored in a cookie and picked up and deleted when the callback happens. That's at least my first idea.
