### ISSUE TITLE
llm: ridiculously high spend limit

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7505]
today I noticed the possible spend limits for LLMs are very high. this only creates the impression that they're very expensive – which they're not.

![Screenshot from 2024-04-30 09-43-46](https://github.com/sagemathinc/cocalc/assets/207405/ca591d7a-cf5c-4024-8216-3217656af864)

**Comment by novoselt** [comment]
That was part of the solution to deal with too low limits (like $5 is not quite enough for large context models). I think the right solution is to get rid of these buttons completely AND have a sane default soft limit, like $20 for LLMs and $100 for compute servers.

**Comment by novoselt** [comment]
Related #7506

**Comment by williamstein** [comment]
Instead do #7506
