### ISSUE TITLE
Confusing error message "Project unavailable" for project non-members.

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#7533]
If a non-member of a project tries to open a link to a file in a project, they get the following message, which is very confusing and misleading:

> Project unavailable
> This project seems to not be responding. Free projects are hosted on massively overloaded computers, which are rebooted at least once per day and periodically become unavailable. To increase the robustness of your projects, please become a paying customer (US $14/month) by entering your credit card in the Billing tab next to account settings, then move your projects to a members only server. Error: you do not have access to this project

<img width="1313" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1028433/f567f6d0-42aa-41fe-bd7d-037d50d00b69">

Instead, the message should prompt to user to request access somehow.  Perhaps something like

> Private Project
> You are attempting to access a project for which you are not a collaborator.  If you feel that you should have access, please contact one of the owners who sent you the link you are trying to access, and ask them to add you as a collaborator.

Possibly with a button allowing them to request access that will send a message to the project owner.  (This is what some people expect from Microsoft, Google, etc. shared documents.)

**Use Case**
I sent an email out to a group of collaborators with a link to a file in the project, but forgot to add a couple as collaborators, or added them with a different email address/account (common if one has a couple of CoCalc accounts that they don't use frequently - i.e. former students who were part of a class, hence using their institutional email, but later who sign up with gmail etc.)

**Comment by williamstein** [comment]
This is #6753

**Comment by mforbes** [comment]
Oops.  I guess I should provide better titles for my issues:-)  I tried to find this, but forgot I had submitted one.

**Comment by williamstein** [comment]
> Oops. I guess I should provide better titles for my issues:-) I tried to find this, but forgot I had submitted one.

I think your title and description are actually better than #6753 and I appreciate you reporting this.  Also, when we fix #6753 we'll see the link here, and it'll still be useful.  No problem at all!
