### ISSUE TITLE
@ mentions are too aggressive

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7563]
See how mentions menu appears, then disappears, and then swallows what I have typed:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/fa53a1fc-9a9b-4ce8-88c3-a900404baf08)

![image](https://github.com/sagemathinc/cocalc/assets/1993227/159fbe8e-ff1c-4429-928e-587c4c172206)

![image](https://github.com/sagemathinc/cocalc/assets/1993227/0b6a37e1-d7be-477d-b067-daa3a60ffa39)

**Comment by novoselt** [comment]
An easy solution specifically for emails - do not attempt @-mentions if there is some text right before @ as it happens with email addresses.

**Comment by williamstein** [comment]
fixed
