### ISSUE TITLE
Licenses in the past can be purchased via a link

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7570]
- I've sent a link for a license in our store with specified dates.
- The start date is now in the past, but I could click on the link, add it to the cart, and then purchase it for the full price without any dates adjustment.
- When I went to "cancel immediately", I was shown that only prorated cost for the remaining period will be refunded.
- But actually I got the full purchase price back.

I think the correct solution here is to refuse adding such a license to a cart or going through a checkout if there is a license in the cart with start date in the past by more than 1 hour or so.

In addition something is off with the "promised refund" and "actual refund", although it may be triggered only in this situation which should never happen.

**Comment by williamstein** [comment]
> I think the correct solution here is to refuse adding such a license to a cart or going through a checkout if there is a license in the cart with start date in the past by more than 1 hour or so.

Other options:

- just truncate the start time to now,
- shift the time range so that it starts now.
- offer one of the above choices
- don't allow completing the purchase until the item gets edited manually to be valid.

It's annoying that there are so many options.

**Comment by novoselt** [comment]
I favour manual edit rather than automatic shifts.

Also a very important special case is "from now" which is selected as today's date with 00:00 time, which I have advocated for as the default and I am very happy with. Even better would be to eliminate the time field. I think it is perfectly reasonable to charge "for the whole day" without per-hour breakdown. So instead of 1 hour fuzziness I would check that the actual date is today or later, dropping the time.
