### ISSUE TITLE
Discrepancy in displayed time when buying a license

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7571]
![image](https://github.com/sagemathinc/cocalc/assets/1993227/07cf37f1-292a-4e7a-aa77-c72fa564645f)

We have 00:00 time in the period configuration, but in the "info box" the start time is 00:00 (which is actually in the past) while the end time is 12:39 which would be correct if the the start was shifted to current time keeping the duration.

Whatever is the logic, the displayed behaviour is confusing. The start selector should advance to a sensible "now" time if there was a past timestamp entered. The end selector should either stay the same, or get adjusted by the same amount. Both the selector and the info box should show the same time, and it should be the same time that goes into cart and invoices. Since "now" has no fixed value, we should allow start which is slightly in the past and avoid constant drift.

**Comment by novoselt** [comment]
Still there. Also when doing it, the URL has 00:00:00 as in the license term box. The price is computed based on whole days, so actually the long description is wrong.

**Comment by novoselt** [comment]
#7638 is related.

As for the solution - when the current date is selected with 00:00:00 as the starting time, I would keep this time on all labels, but when the license is actually purchased shift the time of both start and end by the same amount, i.e. the current time. This will avoid any kind of fluctuations with displayed and paid prices.

**Comment by williamstein** [comment]
OK, I think I just solved this one...
