### ISSUE TITLE
new generators: the "Pick an example" dropdown goes off the screen and can't be scrolled.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7574]
1. Open the "Generator..." for latex
2. Make sure your browser window isn't unusually high, e.g., maybe even make it fairly short.  I did notice this first on a rather large screen.
3. Click "Pick an example" and see a menu
4. There is no way to scroll the menu or select items not on the screen:

<img width="1197" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/7db5cb3f-0379-4141-a296-5b072f8eefe2">

(I can't scroll the above menu.  And this is on a rather high resolution 16" laptop with my browser fullscreen!)

I think this is a problem with not properly setting something about the modal.   

WORKAROUND: buy a bigger monitor, or zoom out to 50%

**Comment by williamstein** [comment]
This is very important to fix because it's frustrating.

Also, the select should be searchable!  Any dropdown, especially a long one, should be searchable unless there is a really good reason for it to not be.   There are many examples of making selectors searchable at https://ant.design/components/select and in our source code.

**Comment by haraldschilly** [comment]
I can try to fix this, when I figure out how to reproduce it, but making this searchable is something for another ticket.

**Comment by williamstein** [comment]
fixed by #7577
