### ISSUE TITLE
Rename "Generator..." to something else...

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7578]
In English I think this button label "Generator..." is not very clear.  I bet most people don't click on it at all because they don't know what it means.  That said, I uploaded a screenshot to GPT-4o and its first guess was that the button is an "AI Content Generator".

<img width="852" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/d086b11b-a438-4f32-908c-dd37c9c502d7">

GPT-4o then cam up with a bunch of ideas for label choices, but it claims that **by far** the best choice for a label for this button is "AI Document Creator".  Since we have the AI icon already, maybe "Document Creator"?   It seems clearer than "Generator...".

**Comment by novoselt** [comment]
I would call it "AI-icon Assistant" and make it orange, i.e. make it exactly the same as the menu bar button. That may be less fitting in general, but I think is very coherent for the overall interface. 

I dislike "Document ..." under buttons which already have pretty much the same word, like "LaTeX Document", and "Creator" after the question "What would you like to create?" is also a bit strange.

Also I would replace Sage worksheet without this button with a plain Markdown with this button.

**Comment by williamstein** [comment]
Thanks @novoselt.  Your suggestions are much different than I expected, would potentially look disconcerting (putting a big orange button there when no other buttons are colored), and possibly even more confusing due to it actually being a totally different thing than the other AI Assistant button.  Thus I would really like to hear what Harald and Blaec think.

The following is definitely not part of this issue, but I'll comment on it:

> Also I would replace Sage worksheet without this button with a plain Markdown with this button.

This is a dangerous move, given that **Sage worksheets (.sagews) are over 7x more popular** than Markdown documents.  You might argue that Sage worksheets are more popular than Markdown because Sage worksheets are in the first row.   I'm not convinced by this argument because RMarkdown is in the first row, and is over 25x less popular than Sage worksheets.   If we were to actually do what you suggest above verbatim, it would be very impactful on users, and probably in a very negative way.     Despite not being all "industry standard and modern" (like Jupyter or Markdown), Sage worksheets are very likely a much better user interface than Jupyter or Markdown for a lot of users.

**Comment by novoselt** [comment]
A paler version would work as well ;-) As far as using the same name for quite different functionality - I did think about it, but while functionality is different, the spirit is the same - "do something with the help of the AI Assistant, whatever that is". I don't think that in either of these two use cases the title of the button conveys much about what will happen, just that it will be some action involving AI. When the question is "What would you like to create?" and there is an "AI Assistant" button, I think it is quite natural to expect that it will result in "Create this document using an AI Assistant" and it is as complete description as can be in a short sentence.

Compared to "Generator" it makes it clear that the user affects the process, so it is not just something random as the second guess from ChatGPT.

On the side topic of Sage worksheets, I mostly wanted to include plain markdown button and it feels like something has to go. If plain markdown is more used that R markdown, maybe we can trade them?

**Comment by williamstein** [comment]
> If plain markdown is more used that R markdown, maybe we can trade them?

I like that idea, since indeed plain markdown is much more popular on cocalc than R markdown.

Regarding the button name... I'm looking forward to comments from other people too.   I think almost anything would be better than the current name.

**Comment by novoselt** [comment]
Another idea: "Help me start..." Similar to "Help me fix..."

**Comment by williamstein** [comment]
<img width="1410" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/bf00978d-ec41-4ae4-a291-3aff7d1f7f51">

**Comment by williamstein** [comment]
And the winner by vote of hsy, me, and andrey is ""Help me start..."

**Comment by williamstein** [comment]
You could easily also add a menu item called something like "New using AI..."

<img width="266" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/bab7a359-096b-43d7-8d4d-39e437c3ddc4">
