### ISSUE TITLE
Unable to delete files when disk quota is full, without having to write to support

### ISSUE THREAD

**Issue by tscrim** [sagemathinc/cocalc#76]
If a user has created a project and exceeded the disk quota (or a terminal), it seems files can not be deleted.

How I encountered this bug was I was trying to create project for Sage development on SMC, and I copied a project over. At which point my quota was exceeded. (It says on the [corresponding github page](https://github.com/sagemathinc/smc/wiki/SageMath-Development-on-SageMathCloud) that it is a little over 2GB and we have 3GB of disk storage, but Sage must have grown since then...?) However I couldn't move the copied files to the trash can as it tries to make a `.trash` folder, but can't because of the quota. I was able to move the files to a `.trash` if that had been created before.

I also tried this a second time on a second project where there was no `.trash` and so I couldn't move it. Thankfully I could delete this because I had a terminal already open.

Best,
Travis

**Comment by williamstein** [comment]
This will be solved by the new k8s project background...

**Comment by williamstein** [comment]
This is now fixed.
