### ISSUE TITLE
onprem/editor/latex: missing word list error pops up on each save

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7652]
This error pops up each time the source is saved:

> Error: No word lists can be found for the language "de_AT".

and you've configured the editor to use that particular language (german in my case) – while the word list is not installed.

Somehow, using the word list is the default, I think.

**Workaround:** editor configuration → spellcheck → browser

ideas to fix this:

1. IMHO the browser spellcheck should be the default.
2. Only popup that error once per edit session, such that dismissing it is firmly dismissing it and the next time it saves it does not come back.

**Comment by williamstein** [comment]
I think I fixed this during the summer, I think by doing your suggested 1.
