### ISSUE TITLE
chat: browser refresh opens editors of past messages

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7662]
This must be a fallout of the recent chat changes: if I send a message, then reply, then double click to edit the reply and cancel it (or something like that, i.e. nothing complex) → and then I refresh the entire page → I'm back into the chat but one of my past messages is shown in an additional edit box. This is weird, because the rendered message is also visible (I would assume either edit or render it, not both). In any case, something isn't quite right any more...

![Screenshot from 2024-07-04 17-24-57](https://github.com/sagemathinc/cocalc/assets/207405/439bf9a0-15cf-49ab-94f8-b093e10a8b84)

---

raw content of the file (redacting my account id):

```
{"active":1720106674603,"date":0,"event":"draft","input":" ","sender_id":"UUID"}
{"active":1720106674616,"date":-1720106660288,"event":"draft","input":"xxx","sender_id":"UUID"}
{"active":1720106678930,"date":1720106674584,"event":"draft","input":"xxx","sender_id":"UUID"}
{"date":"2024-07-04T15:24:20.288Z","editing":{},"event":"chat","history":[{"author_id":"UUID","content":"foo","date":"2024-07-04T15:24:20.288Z"}],"sender_id":"UUID"}
{"date":"2024-07-04T15:24:34.584Z","editing":{},"event":"chat","history":[{"author_id":"UUID","content":"xxx","date":"2024-07-04T15:24:34.584Z"}],"reply_to":"2024-07-04T15:24:20.288Z","sender_id":"UUID"}
```

WORKAROUND: click on "cancel" in all these edit boxes :man_shrugging:

**Comment by williamstein** [comment]
It's weird that the date is positive *and* negative for drafts, which is what is causing this.    I'll just have it delete both signs for now.

**Comment by haraldschilly** [comment]
So, this happens all the time for me, and it's not related to refreshing the page, but just scrolling up and down. If it happens, it's my own message I wrote either a minute ago, or a day ago, or whatever. 

What was the change that introduced this in the first place? For me this is really annoying.

**Comment by williamstein** [comment]
I found a way to reproduce this with two windows at once, which probably just makes it easier to see the root cause of the problem.
