### ISSUE TITLE
Limit author name and icon scope to a single thread in chat

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7671]
The current logic with multiple messages from a single author seems to be: put author's name above the first message and author's icon to the left of the last message. This may make perfect sense, but I strongly object to this logic crossing framed threads!

The frames make it easy to ignore groups of messages, but with current handling it is possible to have messages "between threads" without any markers related to who has written them.

If each top level message was labeled with author name/icon, it could be too much, but I think still better than the current situation. One can also try to group together "top level messages without any replies to them".

**Comment by haraldschilly** [comment]
I know what you mean, but replies were implemented exactly like that, and I didn't change this when I implemented collapsable threads. In any case, I know what needs to be done to fix this.

**Comment by williamstein** [comment]
I'm closing this.  Open it if you can make it much clearer, with screenshots, etc.  I feel at this point things work pretty well.  Also, maybe this was a side effect of how search used to work.
