### ISSUE TITLE
Too many JupyterLabs/VS Code buttons

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7678]
![image](https://github.com/sagemathinc/cocalc/assets/1993227/523ae579-8b6e-4d04-bc23-0e04b53a4167)
These 3 are in addition to mentioning them in the settings dialog. I would only have them as subitems of "Applications".

Maybe having an option for users to add shortcuts to the main tab would be good, but by default this seems overloaded.

**Comment by williamstein** [comment]
>  I would only have them as subitems of "Applications".

The last support request was from a user looking for X11 desktop and so totally failing that they made a support request.  That's the one that is ONLY a subitem of applications.   I think I should promote X11 desktop up and get rid of the application submenu.   These web launchers are very, very important.   I doubt there will be any others besides these 3.

**Comment by williamstein** [comment]
(note that X11 desktop actually isn't implemented -- it's on my todo list today!)

**Comment by novoselt** [comment]
If there will be only 3, I would definitely get rid of the application submenu (also if "Logs" contains only two items, I would not create an extra level).

Again - if there will be only 3, I would have them only as buttons on the left.  I would actually remove "Serial" from there since it is "for special purposes only", more special, than X11.
