### ISSUE TITLE
Jupyter, VS Code, Pluto, RStudio button on +New page goes to wrong "tab".

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#7684]
<img width="1505" alt="Screenshot 2024-07-11 at 6 13 00 PM" src="https://github.com/user-attachments/assets/3248fd08-d0c0-4810-8d97-0d61be6770c7">

1. Click on the Jupyter, VS Code, Pluto, RStudio button on the +New page shown above.
       - This takes you to the Compute Server tab shown below rather than the Notebook Server tab shown last.

<img width="1505" alt="Screenshot 2024-07-11 at 6 18 07 PM" src="https://github.com/user-attachments/assets/9d1a8f8e-8e50-4593-8a87-f9e6732893bf">

<img width="1512" alt="Screenshot 2024-07-11 at 6 18 19 PM" src="https://github.com/user-attachments/assets/38bfebc8-b859-4bd0-9a01-650d05451cba">

**Comment by williamstein** [comment]
This is still broken. Also, the same problem happens with the "Compute Server: GPUs and VM's" button.
