### ISSUE TITLE
Shift-Enter when generating a cell is used twice

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7712]
**Describe the bug**
In a Jupyter notebook with a cell focused I click "Generate using AI", enter my request, press Shift+Enter just because this seems to be natural to execute commands (and Enter by itself only creates a new line), surprisingly the cell is evaluated as well.

**To Reproduce**
1. Go to a Jupyter notebook
2. Click on 'Generate using AI' while a cell is in focus
3. Enter request and press Shift+Enter
4. See the error: Shit+Enter evaluates the AI request AND the cell where the focus was.

**Expected behavior**
Only the AI request should get any keystrokes.

**Comment by williamstein** [comment]
This seems like a reasonable request, and I could easily reproduce this.
