### ISSUE TITLE
sagews vs. sage 10.4

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7716]
Sage 10.4 runs on Python 3.12. Problems:

1. `imp` → `importlib`

> Deprecated since version 3.4, will be removed in version 3.12: The [imp](https://docs.python.org/3.11/library/imp.html#module-imp) module is deprecated in favor of [importlib](https://docs.python.org/3.11/library/importlib.html#module-importlib).

Ref: https://docs.python.org/3.11/library/imp.html

```
File "/cocalc/lib/python3.11/site-packages/smc_sagews/sage_salvus.py", line 20, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

---

a warning (also in 10.3)

> /cocalc/lib/python3.11/site-packages/smc_sagews/sage_salvus.py:3372: SyntaxWarning: invalid escape sequence '\s'

**Comment by williamstein** [comment]
this is already fixed.
