### ISSUE TITLE
files/jupyterlab: home directory causes a warning

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7717]
Since version 4: When clicking on the jupyter lab button in the file explorer, it should open in the corresponding directory.

For a directory in the project this works fine, unless it is the home directory. There, it somehow says it redirects to a default location.

The fix should be to not add that specific tree+path part to the URL if it is the home dir.

**Comment by williamstein** [comment]
I'll fix this, since it's constantly getting hit.
