### ISSUE TITLE
Sage 10.3: Python warning: pkg_resources is deprecated 

### ISSUE THREAD

**Issue by ilan-n** [sagemathinc/cocalc#7729]
When calling **find_root**, I get a warning that **pkg_resources is deprecated as an API in Python**.
(This does not happen if I downgrade the kernel to Sage 10.1.)

**To Reproduce**
- Open a new Jupyter notebook with Sage 10.3 kernel
- Type "find_root(x^2-1,0, 2)" in the first cell
- Run

**Expected behavior**
I don't understand Python's warning, but I guess it is something that should have been dealt with in the implementation of find_root (or maybe just silenced)

**Screenshots**
![image](https://github.com/user-attachments/assets/470080e0-4a78-4347-b8f7-ef0e8ca28626)

The full text of the warning:
/ext/sage/10.3/local/var/lib/sage

> /venv-python3.11.1/lib/python3.11/site-packages/scikits/__init__.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>   __import__("pkg_resources").declare_namespace(__name__)
> /ext/sage/10.3/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/scikits/__init__.py:1: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('scikits')`.
> Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
>   __import__("pkg_resources").declare_

namespace(__name__)

**Comment by williamstein** [comment]
This is an issue with Sage not CoCalc.  It should be reported here: https://github.com/sagemath/sage/issues
