### ISSUE TITLE
Pluto Server "Failed to Load" After Selecting from Notebook Servers Tab

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#7742]
**Describe the bug**
When I navigate to the Code Server tab and select "Pluto..." this results in an error (failed to load).

**To Reproduce**
1. Go to Servers
2. Click on Notebook Servers
3. Select Pluto
4. Launch the Server and notice that it fails to load.

**Expected behavior**
I would expect to have the Pluto interface appear in a separate tab.

**Screenshots**

<img width="1512" alt="Screenshot 2024-08-06 at 1 20 54 PM" src="https://github.com/user-attachments/assets/a2fd8357-184a-4b2c-bb3b-e03b4f6a6ec9">

**Additional context**
Tested in "My Project" https://cocalc.com/projects/0b8e4a77-555d-47e8-9512-9ff3375b25ee/servers using Incognito Mode and Google Chrome. Double Tested in Blaec (CSO) Tasks and Tools with the same result.

**Comment by Blaec-CoCalc** [comment]
I checked again after maybe 30 minutes and it works now.

**Comment by williamstein** [comment]
> I checked again after maybe 30 minutes and it works now.

How upgraded is your project?   Julia can be somewhat resource intensive and initially slow. It's the nature of Julia.   The first goal of Julia (at https://julialang.org/) is "FAST", which means that it's initially slow.  It's a tradeoff.   Without significant upgrades (e.g., probably at least 4GB RAM), I would expect problems using Julia.

**Comment by haraldschilly** [comment]
It often times out, but usually it works when you try again. This is on my list of things to fix with the asynchronous execution of tasks in a project – which will make it also possible to track "existence" (i.e. if a process still runs), terminate a running server, and memory/cpu usage. … but LaTeX first, which is way harder.
