### ISSUE TITLE
Overhanging Service Description into Amount Charged in the Purchases Section of the Upgrades Page 

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#7743]
**Describe the bug**
For each purchase, in the "Purchases" section of the upgrade panel, the service description visually bleeds into the Amount (USD) column if the name is long, "e.g., OpenAI GPT-4 Omni 8k."

**To Reproduce**
1. Use GPT-4 Omni 8k somewhere (like a notebook), or later, scroll down in your purchase history to find the last time you used it.
2. Go to the Upgrades Panel
3. Scroll down to "Purchases in My Project"
5. See the described phenomena.

**Expected behavior**
At normal zoom in Incognito mode via Google Chrome, the listed service description for each charge didn't tend to bleed visually into the amount charged (USD) column.

**Screenshots**
Project ID: https://cocalc.com/projects/0b8e4a77-555d-47e8-9512-9ff3375b25ee/upgrades

<img width="1507" alt="Screenshot 2024-08-06 at 2 37 08 PM" src="https://github.com/user-attachments/assets/3237038b-ef2d-43fe-98fc-8277516e4ea9">

Additional Note:
This would provide better purchase visibility.

**Comment by williamstein** [comment]
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/8241d396-15a8-4860-9f33-ded596bce426">
