### ISSUE TITLE
jupyter: inconsistent section numbering

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7746]
Create a Jupyter notebook with this one markdown cell:
```md
# Foo
## bar
````

Here's screenshots in JupyterLab and CoCalc Jupyter showing the rendered notebook and contents:

JupyterLab:
<img width="504" alt="image" src="https://github.com/user-attachments/assets/e8974752-e025-427c-a37c-853afcb6f051">

CoCalc:
<img width="403" alt="image" src="https://github.com/user-attachments/assets/ccfcd71a-5c08-4af0-bb9b-80dc381307e4">

There is an inconsistency, because our table of contents numbers the sections, but nothing else does.

To be consistent with JupyterLab, we would remove the table of contents numbering.  But at least one users wants the exact opposite change, which is to number the sections in the main document. 

On the web it is very unusual to number headings.  In latex it's very common.  Our table of contents has numbers because I wrote that component for latex first, where obviously numbers were needed.

If we number the headings in Jupyter notebooks, it also seems a bit weird, since they are not numbered when editing a markdown document.   So we would be adding more inconsistency.

**Comment by williamstein** [comment]
I suspect what most book like projects out there would do is just autogenerate ipynb files from some other source material, and they would likely put their own section numbers in as part of the name of the section.  As you can imagine, doing that combined with automatic section numbers would be really bad.  So very likely the right solution is to remove section numbers from the table of contents.

**Comment by novoselt** [comment]
Well, I kind of like to have numbers, I understand why they must be desirable, and recently you pointed out how convenient it is to refer to sections/items by numbers during discussions, especially written ones.

BUT: The markdown syntax does not support automatic numbering as far as I can tell, which is already a good reason to avoid numbers. If JupyterLab avoids them, it is another good reason. Those who are interested can always put a number in front of the heading and there are some advantages here - you may have some numbering throughout a collection of notebooks, whether they are autogenerated as you mentioned or not.

So I do like numbers, but I think that "the right way" is to drop them in all places.

**Comment by williamstein** [comment]
Harald also points out that we should get rid of the font size as well for perfect consistency with jupyterlab.  Only indicate sectioning by indentation for the table of contents for jupyter.

**Comment by williamstein** [comment]
Ironically, the latex implementation in cocalc doesn't have numbering!

<img width="251" alt="image" src="https://github.com/user-attachments/assets/a41663f9-cda4-4514-aa46-bb7602b7f404">
