### ISSUE TITLE
Vertical scrolling with HTML output is unintuitive

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7759]
**Describe the bug**
This is "a known issue" that to scroll through the HTML output, i. e. some widgets and dataframes, you have to put the cursor to the side, otherwise it does not work. Problems:
- How can a user learn about it???
- The behaviour actually depends on how fast you scroll - if you scroll fast enough, then there is no "focus capture" by the component and you can scroll through with your cursor in the middle. If you pause, scrolling stops working. It is easy to deal with it when you know what is going on, but otherwise it is annoyingly unpredictable, in my opinion.
- It is actually very strange when this scrolling stops working for short output that has no concept of scrolling on its own.

**To Reproduce**
Steps to reproduce the behavior by creating a long worksheet quickly:
- cell 1 ``for i in range(100): print(i)``
- cell 2 ``import pandas as pd; df = pd.DataFrame({'A': range(25)}); df``
- cell 3 ``for i in range(100): print(i)``

**Expected behavior**
- If there is no scrolling possible for the output, I expect the scrolling to work for the whole worksheet.
- If there is scrolling in the output, especially with a scrollbar visible for long output, it makes a lot of sense that the worksheet is NOT scrolled.
- The previous behaviour was to scroll the output to its end, then scroll the worksheet. I actually found THAT annoying... I would prefer if I could scroll only the output of one cell and had to move out of that output to scroll the worksheet. Or maybe if I had to explicitly focus on the cell output to be able to scroll it and then had to release this focus to scroll the worksheet.

I suspect it may be difficult to determine which output is scrollable. If so, perhaps it is possible to at least "whitelist" some known types? For example plain text and pandas dataframes?

Another random idea - scroll the worksheet and require the user to click on the output to scroll the output of a single cell. There can be some hover tip.

**Comment by williamstein** [comment]
- I put in some hacks to make it so often (?) vertical scrolling will work in general.
- I whitelisted pandas, since that's probably the most popular use case and doesn't need this stable html stuff at all.

**Comment by novoselt** [comment]
Thank you! Sooo much better!!!
