### ISSUE TITLE
CPU Warning Duplicated Under Processes Button in Action Bar

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#7767]
**Describe the bug**
When the CPU is maxed out by running something computationally intensive (e.g., plotting the 3-D wave equation), the CPU warning is duplicated underneath the "Processes" icon in the action bar on the left side of my project.

**To Reproduce**
1. Run a computationally intensive task (e.g., plotting the 3-D wave equation).
2. Go to "Processes" in the action bar located on the left side of the project.
4. Observe the duplicated CPU warning under the Processes icon.

**Expected behavior**
A single CPU warning should appear underneath the "Processes" icon.

**Screenshots**
<img width="1512" alt="Screenshot 2024-08-20 at 5 14 33 PM" src="https://github.com/user-attachments/assets/23c05816-fef5-47a3-82ec-c5e051159986">

**Additional context**
The bug is purely aesthetic-related. _Using Chrome and Incognito Browser._

**Comment by haraldschilly** [comment]
is this a dup of https://github.com/sagemathinc/cocalc/issues/7406 ?
