### ISSUE TITLE
Repeated explain in AI tools

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7789]
**Describe the bug**
![image](https://github.com/user-attachments/assets/5380eac2-4285-41af-8a8b-4e0e8d173fe2)

**Expected behavior**
The lower item is actually for fixing code, probably a result of i18n

**Comment by williamstein** [comment]
Nice find. This is exactly the sort of mistake Harald was worried about...

**Comment by williamstein** [comment]
The code in src/packages/frontend/i18n/extracted.json looks like this:

```js
...
  "jupyter.llm.dell-tool.actions.bugfix.label": {
    "defaultMessage": "Explain"
  },
  "jupyter.llm.dell-tool.actions.document.descr": {
    "defaultMessage": "Add documentation"
  },
  "jupyter.llm.dell-tool.actions.document.label": {
    "defaultMessage": "Document"
  },
  "jupyter.llm.dell-tool.actions.explain.descr": {
    "defaultMessage": "Gain some insight into the code in that cell."
  },
  "jupyter.llm.dell-tool.actions.explain.label": {
    "defaultMessage": "Explain"
  },
...
```

I've assigned this to @haraldschilly because fixing it involves:

- fix src/packages/frontend/i18n/extracted.json
- somehow also fix all the other languages
- compile everything...
