### ISSUE TITLE
Add a way to select all cells of a certain type in notebooks

### ISSUE THREAD

**Issue by math-sl** [sagemathinc/cocalc#7823]
The cell protection is very usefull when using notebooks as interactive class notes. From our experience, students unfamiliar with the interface often delete or move parts of the documents by error.

The problem is that while the protection mechanism is there, it is often time-consuming to use: we have to select all cells and protect them, but there is no way to select code cells to unprotect them to allow editing (or to protect only text cells to protect them, which would achieve the same goal.)

A simple solution would be to have the possibility to select all cells of a certain type: select all code cells, select all text cells, etc.

This is not possible in jupyter notebooks either.

**Comment by williamstein** [comment]
Hi,

Now that we have everything in menus (with submenus) in CoCalc, it's pretty easy to add exactly what you're requesting without overloading the UI.  Basically in this menu:

<img width="780" alt="image" src="https://github.com/user-attachments/assets/cd800cbb-d3ab-42e6-8243-4176ae8be78e">

I can add two more options "Select All Code Cells" and "Select All Markdown Cells".  Implementing is pretty easy.  You can then click to the left of "Select Cells":

<img width="633" alt="image" src="https://github.com/user-attachments/assets/d4e56f07-336b-4d66-8e6f-ec3df50b4821">

to get a shortcut in your toolbar, so you can quickly select code or markdown cells with two clicks (and later with one when we improve the shortcut functionality, which is planned).

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/cocalc/issues/7831 which is likely the real motivation for this...
