### ISSUE TITLE
Use different background color for messages and warnings.

### ISSUE THREAD

**Issue by lahvak** [sagemathinc/cocalc#7868]
In notebooks with R kernel, a cell can produce a message, for example:

```r
message("Blah blah blah")
```

or a warning:

```r
warning("Blah blah blah")
```

Currently, both of those show in the notebook with very visible pink background.  Interestingly, an actual error message:

```r
stop("Balh blah blah")
```
will show on much less visible, slightly pinkish, background.

This semester, several students contacted me, concerned that they are doing something wrong, since they are getting all those error messages from their cells.  It turned out they were only getting information messages sych as those produced by `message()`, but because of the bright pink background, they though these were errors.  This was never an issue before, but this semester several students already contacted me about that. 

I was thinking it would be nice to use different colors for messages, warnings, and actual errors, reflecting the different severity of those.
Perhaps green for messages, yellow for warnings, and red for errors?

**Comment by williamstein** [comment]
This seems out of scope for CoCalc.    I think there are two output streams: stdout and stderr.  CoCalc and JupyterLab are consistent in rendering stderr with a reddish background:

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/c15946ae-c12a-4cb2-ab54-b1ec472fcd4f">

This is what the output messages look like:
```js
"outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Blah blah blah\n",
      "\n"
     ]
    }
```

This seems like something to take up maybe with the developers of the R jupyter kernel?

**Comment by lahvak** [comment]
That makes sense.  R by default sends both messages and warnings to stderr.

--
Jan Hlavacek
Department of Mathematical Sciences, SVSU
(989) 964-2004 - https://space.lahvak.space/
________________________________

**Comment by williamstein** [comment]
closing as out of scope for cocalc.
