### ISSUE TITLE
automatically close environment

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#79]
Requested by: Juan Carlos Bustamante

In Kile, when I do someting like \begin{enumerate} it will automatically write \item in the next line, ant then  \end{enumerate} two lines downwards. Ending the environments one opens could be good. The other feature is partial compiling : one selects a piece of code and then it is compiled, without having to go through the whole document. This perhaps is not that useful, because in SMC one has the preview continuously.

**Comment by JCBustamante** [comment]
Some related features : 
- Beeing able to comment / uncomment several lines at once. Again in Kile this is done by selecting the code, and making Ctrl - D or Shift - Ctrl - D.
- Put some text in boldface / underline / emphasize...  Again selection of the relevant piece of text + a shortcut does the job.
- Having some templates avaible. For instance in ShareLaTeX one can start a LaTeX document using the style of specified journal. I don't want to use this, but some people might find it useful.

**Comment by williamstein** [comment]
E.g., if you type:

 \begin{enumerate}

then suddenly

 \end{enumerate}

appears. Also, when the cursor is in the \end{enumerate}, then the beginning and end would be highlighted.   CodeMirror has an XML environment that does all this very nicely, so it might just be an easy matter of modifying it, if it hasn't been done already.

**Comment by williamstein** [comment]
Already done, and also closing in favor of #49 for anything similar.
