### ISSUE TITLE
too many "Unread CoCalc messages (<N>)" emails

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#8065]
For my taste there are too many emails sent to me for a single day. I propose the strategy should be it emails me once if there is something new, maybe even immediately. But if I do not check in (i.e. my "last active" of my account stays in the past before the oldest unread message), I only get one email per day telling me about the unread messages.

![Screenshot from 2024-12-16 10-22-20](https://github.com/user-attachments/assets/4c306634-03a3-4c4a-adbf-64a21ebc6163)

**Comment by williamstein** [comment]
I already fixed this.

-- William Stein
