### ISSUE TITLE
purchasing: first month of subscription should charge the subscription rate (i.e. for 30.5 days)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#8079]
The first month is charged incorrect, e.g., I just tried adding the default subscription to my cart:

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/229dea09-d33b-4e41-8f32-8d2c6b5d868e" />

Then I click checkout and see \$6.72:

<img width="985" alt="image" src="https://github.com/user-attachments/assets/53b82475-a255-4a54-8edb-266abb7b3cea" />

My guess is it is recomputing the price but for the exact number of days for the first month starting now.  It would probably be less than \$6.40 if you tried the same steps in February!

**Comment by novoselt** [comment]
Just a note that 6.72/6.40 = 1.05 exactly and 5% is the current difference in monthly and yearly discounts. Without looking at the code it seems like a more likely coincidence than 31/30.5...

**Comment by williamstein** [comment]
> Just a note that 6.72/6.40 = 1.05 exactly and 5% is the current difference in monthly and yearly discounts. Without looking at the code it seems like a more likely coincidence than 31/30.5...

I looked at the code.  It's multiplying by 32/30.5 = 1.0491803278688525... then rounding up.  It's this code:
```
    const months = (end.valueOf() - start.valueOf()) / ONE_MONTH_MS;
    base_cost = round2up(decimalMultiply(cost_per_project_per_month, months));
```
