### ISSUE TITLE
billing: make it clear in the subscription list if it renews and when

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#863]
Also, make it much clearer in the subscription area that the subscription will renew (or that it ends at period end).

**Comment by haraldschilly** [comment]
well, we can close the main issue, because stripe sends out reminders for all renewals … which is probably the best way to do, keeps everyone informed about where their money goes, no matter what.

rephrasing the headline, though, since the text itself sounds like another issue.
