### ISSUE TITLE
Make it possible to exclude specific students from the peer grading shuffle

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#894]
to solve this situation

> I just ran into an issue where a student did not complete an assignment but they are involved in the peer grading shuffle, which means someone will get a blank assignment to grade. Also, I expect this student won't complete the peer grading so someone will end up not getting feedback. It would be nice if there was a way to exclude a student from the shuffle that occurs during peer grading.

**Comment by haraldschilly** [comment]
> My first thought is to have an 'Options' button under the student name in each assignment so you could do things like exclude from peer grading, extend due date, etc.

**Comment by williamstein** [comment]
Nobody requested or even mentioned this in 8 years.
