### ISSUE TITLE
add students in bulk 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#901]
besides the little box to add students by their email address, add some UI (larger text field, or even a dialog box) to enter an arbitrary long list of student email addresses -- i.e. they are separated by comma, space or newline. This feature should also be a bit clever on its own, such that processing 200+ at once is working well -- e.g. adding batches of 10 to the backend, waiting for proper creation, and giving visual feedback about how many parsed (and to be created soon) and how many are already created.

**Comment by williamstein** [comment]
I don't understand why this s a larger/different UI.  Everything it does should be done by the current UI, right?

**Comment by novoselt** [comment]
I am not aware of any issues with batch adding students at the moment and don't recall support requests, so it looks like this is done!
