### ISSUE TITLE
implement multifile latex editing (master document)

### ISSUE THREAD

**Issue by jasongrout** [sagemathinc/cocalc#904]
Working in a multi-file latex project, such as a book where each chapter is a separate tex file, is cumbersome in SMC:
- Reverse search will not open the correct file (e.g., clicking on a chapter will not open that chapter's file)
- It's hard to quickly navigate between files. You either have to open all of them at once (which is a tedious process of clicking on each one) and deal with lots of tabs, or click back and forth to the files tab each time you want to open a new file. In ShareLatex and JupyterLab, there is a file browser in a sidebar that lets you easily switch the current file.

I just tried to help a user switch from ShareLatex to Sage Cloud to edit a Latex book. They switched back after a day or two. I sat down with them to see what was lacking in the Cloud, and these things are what they explained.

**Comment by williamstein** [comment]
We simply haven't even started to implement multi-file latex editing yet.   I've changed the title to more clearly indicate this.

**Comment by jasongrout** [comment]
Yep, no problem. Just wanted to keep track of it in an issue.

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/smc/issues/86 which was about some technical thing I've never heard of.

**Comment by crockeea** [comment]
This is a pain point for my team as well. Issue #86 describes how most desktop TeX editors handle the problem, while Overleaf simply has a [UI feature](https://www.overleaf.com/learn/how-to/Can_I_choose_which_file_is_the_main_tex_file_in_a_project_on_Overleaf%3F) for it.

Using the `subfiles` package is annoying because I have to modify existing projects that I'm importing into CoCalc.

**Comment by williamstein** [comment]
I recently did some work [here](https://github.com/sagemathinc/cocalc/commits/time-travel-frame) which , when done right, will make it easy to implement this feature for latex.  I.e., this is close.

**Comment by williamstein** [comment]
Work in progress here -- https://github.com/sagemathinc/cocalc/pull/4209

**Comment by williamstein** [comment]
![image](https://user-images.githubusercontent.com/1276278/68099438-6aed2300-fe77-11e9-8aab-859c14be3b36.png)

**Comment by williamstein** [comment]
Heh, it's implemented now.  Will be live soon...

**Comment by williamstein** [comment]
Multfile LaTeX editing is now live.  You'll have to restart your project (if it is running) before this works.

The user interface is initially (and with a single file) identical to how it was before, except with some bug fixes.  The difference is that if you explicitly `\input` other files, then build, then there is a new menu on the top of a text editor that lets you select from any of the subfiles.  Also, if you double click on the pdf on some latex generated by a subfile, then that file is automatically opened.   Also things like errors/warnings have links that, when clicked, may open a subfile.  And forward search from subfiles works as it should. Saving a subfile, saves all files and kicks off a build.  If you switch a frame to be a terminal and use the open command you can also open any file (not necessarily one listed in the dropdown).  

![image](https://user-images.githubusercontent.com/1276278/68356950-a3377000-00c8-11ea-95fd-84f01a20caaa.png)

**Comment by crockeea** [comment]
Very excited to try this out! Is it in the docker image yet?
