### ISSUE TITLE
create a 32-bit Docker image, e.g., for raspberry 2 [raspian]

### ISSUE THREAD

**Issue by projetmbc** [sagemathinc/cocalc#910]
I have tried to use the docker image on my raspberry 2 but I have the following error message.

```
xxxxxxxx
docker: Error response from daemon: Cannot start container xxxxxxxx: [9] System error: exec format error.
```

**Comment by williamstein** [comment]
I only built a 64-bit x86 version, so it can't possibly work on raspberry pi; sorry.  It might be possible to build the image on one though (not sure).

**Comment by projetmbc** [comment]
Ok.

I was planing to buy a Raspberry 3, it is the time to do it.

**Comment by projetmbc** [comment]
Maybe you should add that the image is for 64 bit version in the readme.

**Comment by williamstein** [comment]
@projetmbc -- done

**Comment by projetmbc** [comment]
Thanks.

**Comment by haraldschilly** [comment]
I'm closing this, since the current raspberry pi is 64bit (Arm Cortex A76 processor) and well, the docker variant is discontinued as well.
