### ISSUE TITLE
smc docker image -- set language environment

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#921]
when running a dask client, which is python 3, I get this:

```
$ dask-worker
Your terminal does not properly support unicode text required by command line
utilities running Python 3.  This is commonly solved by specifying encoding
environment variables, though exact solutions may depend on your system:

    $ export LC_ALL=C.UTF-8
    $ export LANG=C.UTF-8

For more information see: http://click.pocoo.org/5/python3/
```

It's not really about dask at all, but that python 3 libs seem to want this.

Maybe take some ideas about how to setup this image from the k8s compute image?

https://github.com/sagemathinc/smc/blob/k8s/src/k8s/smc-project/image-base/Dockerfile

**Comment by williamstein** [comment]
@haraldschilly  - is this easy?

**Comment by haraldschilly** [comment]
Well, yes, the referenced Dockerfile does set all those environment variables. The page here http://click.pocoo.org/5/python3/ explains why Python3 needs those unicode variables set.

```
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV TERM screen
```

**Comment by williamstein** [comment]
I don't get it.   Are you saying that https://github.com/sagemathinc/cocalc/blob/master/src/dev/docker/Dockerfile should have the lines 
```
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV TERM screen
```
included in it?  And/or this should get run?   
```
locale-gen en_US.UTF-8 de_DE.UTF-8 fr_FR.UTF-8 ru_RU.UTF-8 es_ES.UTF-8 fr_CH.UTF-8 \
               fr_CA.UTF-8 de_AT.UTF-8 de_CH.UTF-8 en_GB.UTF-8 hi_IN.UTF-8 fr_BE.UTF-8 es_MX.UTF-8 \
               pt_PT.UTF-8 pt_BR.UTF-8 ja_JP.UTF-8 it_IT.UTF-8 zh_TW.UTF-8 en_AU.UTF-8 nl_NL.UTF-8 \
               ko_KR.UTF-8 sv_SE.UTF-8
```

Sorry for being slow, but you've already completely solved this problem, so help me :-)

**Comment by haraldschilly** [comment]
Yes, exactly. (Locale gen is a bit excessive, though)

I looked this up today again, and did some experiments. The unconventional side of docker is that it starts the container processes completely clean and there is no linux boot step. So, even files like `/etc/environment` have no effect and only bash's own initialization would provide some environment variables.

With those `ENV` variables, the image does get these variables baked-in. That's what we really want, and hence have them set by default (e.g. running python directly (or via some init task) in a container has them set).

The image configuration is visible this way:

```
$ docker inspect <image-name:tag>
[...]
        "ContainerConfig": {
[...]
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LC_ALL=C.UTF-8",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
```

and a dockerfile is a way to set this (or alternatively via `docker commit`).

If known in advance, that's also an opportunity to extend the PATH :-)

**Comment by williamstein** [comment]
> Yes, exactly. (Locale gen is a bit excessive, though)

Done, without locale gen.
