### ISSUE TITLE
add hashtag functionality to chatrooms

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#932]
From @haraldschilly "we teach our chat here hashtags, just like everywhere else, such that we can filter by them. e.g. #course would cover all messages related to courses, #admin are admin related aspects."
1. Bare minimum: add a search box for chatrooms, that restricts to messages with given text.  In there, using #foo would just happen to restrict to things with that tag (and -#foo to things without), exactly like in projects, tasks.  This would be enough to be useful and live.
2. Next: a bar at the top, exactly like in the projects page (and in tasks) showing all hashtags, that is clickable.    Relevant: https://github.com/sagemathinc/smc/issues/933
3. Would be nice: actually render #tag differently in output of chats -- even this isn't done yet for the project listing page!
4. When entering a chat message, it would be nice if typing # would autocomplete on known hashtags.    This is done nowhere else yet.

Each of 1-4 could be a separate pull request.

**Comment by williamstein** [comment]
> I would like to see the ability to mark certain hashtags as things I don't care about, e.g. don't show me and don't alert me to.

I agree.  Note that this is different than in the project listing and tasks, but it is a reasonable change.   One way would be three states for each hashtag:  show only stuff with the tag, only stuff without the tag, ignore the tag in search.

I've moved changing hashtags to https://github.com/sagemathinc/smc/issues/933

**Comment by williamstein** [comment]
Just re-iterating the need for this: You would type #foo and #important #side, etc., and they would get highlighted nicely. A bar would appear at the top also with all tags (exactly like with task lists). Clicking on the tag in a message (or at the top) would show only those chats (with a reminder message that 78 other chats are hidden, say). Also, search box – basically identical to task lists ,but as chat.

**Comment by williamstein** [comment]
[some private discussion](https://cloud.sagemath.com/projects/369491f1-9b8a-431c-8cd0-150dd15f7b11/files/work/2016-12-07.sage-chat)

**Comment by johnjeng** [comment]
>A bar would appear at the top also with all tags

For the chatroom files, I suggest that this go on the side. I'm thinking like the things on the side of chats in messenger.com

**Comment by williamstein** [comment]
have it already
