### ISSUE TITLE
Make it possible to drag and drop images on chats, .md files, latex files, jupyter notebooks, sage worksheets

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#935]
I just experienced the coolest thing. I was making a Github issue and was able to drag and drop my cropped screenshot image. 

On drag and drop on one of these file editors SMC would save the file and then based on the editor add the correct markup code for embedding it. 

These are the areas where this might work. There should be more concrete tickets for each of them:
- [x] chat: that's https://github.com/sagemathinc/cocalc/issues/1238 ?
- [ ] text editor (md, html, ...)
- [ ] latex
- [ ] jupyter
- [ ] sagews

**Comment by williamstein** [comment]
>  SMC would save the file 

For precision -- it would save the file to the database blob store.

**Comment by timothyclemansinsea** [comment]
@williamstein is this database blob store used for anything else right now? I would have assumed this would be saved as a regular file.

**Comment by williamstein** [comment]
>  is this database blob store used for anything else right now?

Yes, it is used for all output in Sage worksheets.  That's why you can copy/paste content of a worksheet **with images** from one project to another no problem, and why there aren't image files cluttering up the filesystem. 

Likewise, here, by making drag and drop work this way you don't even have to worry about what the image is called or where it is stored.  

The blob store is automatically moved to Googel cloud storage after a week (or so) and served from there, so it is very scalable.

**Comment by haraldschilly** [comment]
I've added the label metabug [in the hopes it means what I think], since it covers many different areas.

**Comment by williamstein** [comment]
> I've added the label metabug [in the hopes it means what I think]

I'm not sure I know what it means either.  However, this is definitely not a bug, but a feature/enhancement, and a "metabug" should be a bug at least...

**Comment by williamstein** [comment]
What about a new label: "metafeature" or "meta-enhancement"?

**Comment by haraldschilly** [comment]
or just "metaissue" to cover everything? We could also edit the very first
description to include `- [ ]` checkboxes in a list. Then, github will show
a progress bar for partially completed issues and we categorize these as
"metaissue". from that list there, we could easily reference more concrete
issues.

**Comment by williamstein** [comment]
Most of this has been implemented years ago...
