### ISSUE TITLE
provide command line course hooks

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#948]
What users might want:

> "In a course, is there any way to hook into the code that assigns an assignment to students? I would like to have a script of a sort that either emails students that the assignment was assigned, or posts an announcement to our LMS.  Similarly, if there was a way to hook into the code that submits a grade, I could have a hook that submits the grade to the LMS gradebook."

How this could work:

In course settings there is a panel called "hooks".  A hook is a path to a shell script that gets run when certain actions are completed, and has options for what gets passed to the script.  

Requested by: Jan Hlavacek

**Comment by paulsmart101** [comment]
A Rest API would really help me to automate provision of environments to learners.

**Comment by novoselt** [comment]
Does not seem to be popular, but it feels that it should be easy to implement and will give a lot of power to users who may use it for interesting things. If indeed it is easy to do, I would prioritize this.

**Comment by williamstein** [comment]
I'm closing this since it is so old, and nobody ever requested it since then, and it's also pretty vague.
