### ISSUE TITLE
install optional QPA GAP package

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#949]
http://www.gap-system.org/Packages/qpa.html

REQUESTED BY: Minako Chinen

**Comment by williamstein** [comment]
Right now if one goes to `/projects/sage/sage-7.3/local/gap/latest/pkg` and does

```
wget http://www.gap-system.org/pub/gap/gap4/zip/packages/qpa-version-1.24.zip
wget http://www.gap-system.org/pub/gap/gap4/tar.gz/packages/GBNP-1.0.3.tar.gz
```

then extract GBNP-1.0.3.tar.gz and qpa-version-1.24.zip (and also renames the weird resulting dir to `qpa`!) then it works, which can be tested via `LoadPackage("qpa")` in gap.

For debugging this `DisplayPackageLoadingLog` was useful, and realizing that Gap's package system just silently fails when there are dependencies... but the webpage lists them.

**Comment by haraldschilly** [comment]
I'm assigning this to me, but I have to scratch my head when I think about how to script this ...

**Comment by williamstein** [comment]
On Tue, Sep 27, 2016 at 12:20 AM, Harald Schilly <notifications@github.com>
wrote:

> I'm assigning this to me, but I have to scratch my head when I think about
> how to script this ...
>

I almost wonder if we should write a "install GAP package" script, which
scrapes the website, etc.  It's so embarrassing (IMHO) that the GAP devs
haven't done something already!


-- 
William (http://wstein.org)

**Comment by slel** [comment]
Solved by the recent installation of GAP 4.9.1 system-wide on CoCalc.

```
~$ gap
 ┌───────┐   GAP 4.9.1 of 05-May-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.0, readline
 Loading the library and packages ...
 Packages:   AClib 1.3, Alnuth 3.1.0, AtlasRep 1.5.1, AutPGrp 1.9, Browse 1.8.7, Carat 2.2.2, CRISP 1.4.4, Cryst 4.1.17,
             CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.1, IO 4.5.1, IRREDSOL 1.4, LAGUNA 3.9.0,
             Polenta 1.3.8, Polycyclic 2.13.1, PrimGrp 3.3.1, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, Sophus 1.24,
             SpinSym 1.5, TomLib 1.2.6, TransGrp 2.0.2, utils 0.54
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> LoadPackage("qpa");
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  GBNP 1.0.3 (Non-commutative Gröbner bases)
by A.M. Cohen (http://www.win.tue.nl/~amc) and
   J.W. Knopper (J.W.Knopper@tue.nl).
Homepage: http://mathdox.org/products/gbnp/
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  QPA 1.27 (Quivers and Path Algebras)
by Edward Green (http://www.math.vt.edu/people/green) and
   Oeyvind Solberg (https://folk.ntnu.no/oyvinso/).
Homepage: https://folk.ntnu.no/oyvinso/QPA/
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
true
gap> 
```

**Comment by slel** [comment]
See the README of QPA at https://github.com/gap-packages/qpa
which reads, in the "Installation" section:
```
Since the release of GAP version 4.7.8, the package QPA is distributed
with GAP, so if you download this version or any later version QPA
will be installed at the same time as GAP is installed.  Follow the
instructions for installing GAP on the web page

  http://www.gap-system.org/Download/index.html

After having successfully started GAP, give the command

gap> LoadPackage("qpa");

which loads QPA and you can start using QPA.
```

**Comment by haraldschilly** [comment]
I'm closing this. The original request from ~2 years ago was solved by installing the package locally in the project. The takeaway seems to be that this package was installed for quite some time by default anyways.

**Comment by slel** [comment]
William wrote:

> I almost wonder if we should write a "install GAP package" script, which
> scrapes the website, etc. It's so embarrassing (IMHO) that the GAP devs
> haven't done something already!

This functionality is now provided by the `PackageManager` package for GAP,
which comes installed by default in GAP 4.10.2.

In SageMath, installing the `gap_packages` optional Sage package installs `QPA`, see
https://github.com/sagemath/sage/blob/develop/build/pkgs/gap_packages/SPKG.txt

Links
- https://www.gap-system.org/Packages/packagemanager.html
- https://gap-packages.github.io/PackageManager/

**Comment by williamstein** [comment]
Yeah!!
