### ISSUE TITLE
project backend autosave of sagews files doesn't make images permanent

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#974]
The rule is that images in sage worksheets don't expire if the user explicitly clicks save.  However, if the automatic project-level backend autosaves the worksheet, the "save" button is greyed out, and the user can't click on it without making some other change to the worksheet.

Backend autosave is frequent right now: every 30s.  So this could easily be a common reason for images to not be made permanent. 

I'm not sure how to fix this yet, but probably the best solution is: (1) relax backend auto as 30s is overly aggressive (?), and (2) enhance the backend autosave to properly make images permanent by adding that message to smc-project/client.coffee (similar to smc-util/client.coffee) and hooking into syncstring save.  This will be a bit complicated.

**Comment by gabindu** [comment]
Being a teacher who has to mark students' exam worksheets, this often affects me (as the students don't always explicitly click the save button), causing me lots of extra work during marking to recreate the images (which might not even match anymore what the student had originally evaluated...)

As such, I think option 2) would be preferable in the long run, but (seeing how this seems complicated) in the meantime a warning message or a note about this in the "new to cocalc" tutorial would be important. (I've used SMC/CoCalc for a long time now, and I was never aware of this...)

**Comment by williamstein** [comment]
> I've used SMC/CoCalc for a long time now, and I was never aware of this...

I think backend autosave is relatively recent.  I'm going to completely disable it right now; it's better to not have it all, than for it to have this bug.  Frontend autosave will still happen.

**Comment by williamstein** [comment]
NOTE: autosave of sagews is now disabled (on newly started projects).

**Comment by haraldschilly** [comment]
I'm removing myself from this. I'm wondering what's the status of this is. It's disabled since Dec. 2017? So, it's only the front-end saving and that makes images persistent? Maybe we can close this ticket,  @williamstein  ?

**Comment by williamstein** [comment]
> Maybe we can close this ticket,

Yes, let's close it.  Autosave fully happens on the frontend, and even when the user just tabs away, which should mostly be sufficient.  There could be a new ticket called "implement autosave", but I think it's better just to make a cocalc jupyter kernel and presentation mode that completely replaces sagews, but with equivalent functionality.
