### ISSUE TITLE
Move sign out to top of account page

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#977]
Some users find it hard to find the sign out button. Let's move it to the very top of the account page.

**Comment by haraldschilly** [comment]
well, it's already quite at the top. I think the issue is they don't know that this is in the account page.

**Comment by haraldschilly** [comment]
closing this. at the moment it is at the top and always visible (i.e. sign out isn't hidden when you open another tab than the prefs)

![Screenshot from 2020-02-18 20-31-03](https://user-images.githubusercontent.com/207405/74771008-b217ec00-528d-11ea-82b6-c2d071ccce5e.png)
