### ISSUE TITLE
[vague] Create a site license for universities

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#998]

**Comment by haraldschilly** [comment]
My strategy would be

1. start asking around, to understand common ground what this actually is.
2. define what we think we can do under that title that fits many/most of who asked.
3. figure out the technical scope, which we only know after we have defined it
4. try to find a few customers who are willing to be private testers … for them we have a vague pricing idea, but we likely have to tests our assumptions about how much work it is
5. think very hard about pricing and if we really want to offer this, or if we should delay it a bit

**Comment by haraldschilly** [comment]
closing, too vague. in some sense we have that, in other senses we don't.
